### ISSUE TITLE
Question about File Limit

### ISSUE THREAD

**Issue by iAmWillX** [lingochamp/FileDownloader#1]
Hi,

Nice work on this.

If we wanted to have a file downloaded that was about 2G, how would we go in achieving this? Would we be splitting and downloading in parts?

Thanks,
 Will

**Comment by Jacksgong** [comment]
Thank you very much for your question.

Of course, you can consider split, but after they download, you have to manually put the document together.

But In my opinion, I'm afraid this can only be resolved at the code level.
I have following two ideas to solve this problem without affecting the performance of the original interface: 

1. To use negative values in range of int, this will raise the upper limit to 4G
2. To make a separate callback interface for large file, and replace int with long, this will raise the upper limit to 8EB.

I will try my best to submit this adjustment in my free time, and also welcome PR.

**Comment by Jacksgong** [comment]
fix: 
[library: [enhance] no longer subject to the upper bound of 1.99G, with the results from PerformanceTestActivity,The SoFarBytes and TotalBytes parameters as long type is not hte performance bottleneck, but it's a direction](https://github.com/lingochamp/FileDownloader/commit/5b1e6dc433c765c620f12587145c6bc79d81c516)
