### ISSUE TITLE
网络错误后，不能断点续传

### ISSUE THREAD

**Issue by Luckymin** [lingochamp/FileDownloader#10]
在下载中时断开网络连接，然后重新开始下载的时候又重头开始下了

**Comment by Jacksgong** [comment]
恩。你看看`FileDownloadListener#connected`，这个回调带回来的etag是多少。顺便贴一下下载链接，我看下。

**Comment by Jacksgong** [comment]
多谢你的提醒。

确实是这样的，现在的版本在做这块处理的时候，如果是出现错误了就将数据重新下载了，现在想来其实这块确实可以根据具体的错误情况具体考究，我会在下个版本将这个问题解决。

**Comment by ayou6232290** [comment]
这个问题解决没?

**Comment by Jacksgong** [comment]
@ayou6232290 恩。正在处理。预计这两天会提交一个新版本，新版本会带上这个feature.

**Comment by Jacksgong** [comment]
[fix(Download error and resume): be able to resume from break point naturally, although the download status of the task is Error
Closed #10](https://github.com/lingochamp/FileDownloader/commit/8bc69381b49ce8e1fca90322f101949370f86027)
