### ISSUE TITLE
我这样添加多任务下载，什么方法都不走，直接走completed方法，还希望赐教，谢谢

### ISSUE THREAD

**Issue by xyZangGit** [lingochamp/FileDownloader#1000]
我下载多任务的方法：
final FileDownloadQueueSet queueSet = new FileDownloadQueueSet(downLoadAdapter.getFileDownloadListener());

        final List<BaseDownloadTask> tasks = new ArrayList<>();

        for (DownLoadBean.Data data : dataList) {
            tasks.add(
                    FileDownloader.getImpl()
                            .create(data.getUrl())
                            .setPath(FileDownloadUtils.getDefaultSaveFilePath(data.getUrl()))
                            .setTag(data.getUrl()));

        }
        queueSet.downloadSequentially(tasks);
        queueSet.start();

这个是log日志：
DownLoadAdapter: completed:
DownLoadAdapter: completed:
DownLoadAdapter: completed:
DownLoadAdapter: completed:

W/art: Couldn't lock the profile file /data/misc/profiles/cur/0/com.creatoo.culturaltv/primary.prof: Failed to open file '/data/misc/profiles/cur/0/com.creatoo.culturaltv/primary.prof': Permission denied
W/art: Could not save profiling info to /data/misc/profiles/cur/0/com.creatoo.culturaltv/primary.prof

下载地址和存储权限是都有的
我要实现的功能是
 多任务下载并在列表上展示进度和状态，还希望赐教；
下载地址是正确的

**Comment by rantianhua** [comment]
请提供 FileDownloader 的日志，否则看不出什么问题来。

**Comment by xyZangGit** [comment]
已经找到问题了，因为文件已经存在了
