### ISSUE TITLE
你好，很高兴能看到您的开源框架，可否在demo里面的任务管理器页面添加一下思路注释（方法注释，作用，），逻辑有点绕，很多不理解为什么要那样写，谢谢

### ISSUE THREAD

**Issue by xyZangGit** [lingochamp/FileDownloader#1003]
任务管理器页面就是  TasksManagerDemoActivity  页面

**Comment by Jacksgong** [comment]
我也觉得这块当时写的却是有点绕，主要的核心原因是FileDownloader本身不够纯粹。比如需要考虑:

1. 需要确保下载服务是否启动，因为如果没有启动就取不到有效的进度，因为进度数据存储在下载服务访问的到的数据库中
2. 需要自建一个数据库，因为下载进度数据都是存储在下载服务中的，因此我们在这块需要做一层映射
3. 而关于一个任务的状态会受到`status`，文件是否存在等影响，所以不得不自行进行判断

----

上述的一系列的问题，以及demo的可读性，已经在FileDownloader2 - okdownload中进行改善与优化，FileDownloader本身不会做过多的需求相关的维护，更多的是bug fix。
