### ISSUE TITLE
tmp文件大小的疑虑

### ISSUE THREAD

**Issue by wangsuicheng** [lingochamp/FileDownloader#1004]
未下载的时候，存储的大小
1|root@JDRead:/ # df mnt/sdcard/
Filesystem               Size     Used     Free   Blksize
mnt/sdcard/              5.5G   209.1M     5.3G   4096

下载中途的时候，free和used都会开始变化:
root@JDRead:/ # df mnt/sdcard/
Filesystem               Size     Used     Free   Blksize
mnt/sdcard/              5.5G   289.6M     5.2G   4096

最后下载完了：
root@JDRead:/ # df mnt/sdcard/
Filesystem               Size     Used     Free   Blksize
mnt/sdcard/              5.5G   435.6M     5.1G   4096

上面可以看出，free部分变化了两次，请问这个tmp文件是实质会占据文件系统存储的大小的吗？
但下载中途和下载完成后free是有变化的，如果是实质占据大小，那tmp文件在创建的时候，应该就占据了大小才是？
我用ls -al 命令，也看到了-rw-rw---- root     sdcard_r 227708406 2018-04-17 12:31 file.temp
是有大小显示的

**Comment by zetaoWu** [comment]
我也有相同的疑惑。 已经生成了对应的tmp文件， 但是磁盘剩余空间却没有变化。

**Comment by rantianhua** [comment]
Please refer to #1020
