### ISSUE TITLE
下载文件url重定向的问题

### ISSUE THREAD

**Issue by rubickcc** [lingochamp/FileDownloader#101]
我在使用中发现，如果url使用cdn重定向的话，就会发生下载失败的情况。阅读源码也发现FileDownloadRunnable中loop方法仅对200和206认为success。

请问如果使用cdn重定向url了，怎么才能下载成功？

**Comment by Jacksgong** [comment]
可否贴下，有重定向的url，或者邮件私信我，我看看。

**Comment by Jacksgong** [comment]
是这样的，OkHttp 已经处理了重定向了。具体你可以留意下这篇文章: https://github.com/square/okhttp/wiki/Interceptors

**Comment by Jacksgong** [comment]
这是我在FileDownloader模拟下载一个存在重定向的连接，okHttp的处理结果:

![image](https://cloud.githubusercontent.com/assets/6176417/14449415/4c756c80-00a5-11e6-9d5e-36ed95576e28.png)

**Comment by Jacksgong** [comment]
你具体留意下其他的错误信息，应该不是重定向的问题。
