### ISSUE TITLE
无法访问内网

### ISSUE THREAD

**Issue by Suma-sun** [lingochamp/FileDownloader#1015]
#### Before Issue

PC在host中设置了映射,可以下载成功.
手机连接的PC发出来的,访问同一个url去下载,一直超时.
请问有什么办法解决?

**Comment by Suma-sun** [comment]
通过设置Proxy可以下载成功,但是外网的就下载失败,有没有办法两种都可以?

**Comment by rantianhua** [comment]
第一点，设置 Proxy 不就是正确的解决方法吗？没有 Proxy 的，不就没发连接你的内网？如果不需要 Proxy 就能直接访问你的内网，那内网我外网还有什么区别呢？所以第一个问题我不是很明白。

第二点，是的，默认判定两个任务相等是通过 path  和 url ，但是 FileDownloader 提供了自定义 IDGenerator 的接口，你可实现自己的判定两个任务相同的规则。具体见 [Wiki](https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component) 里的 `IdGenerator ` 。

**Comment by rantianhua** [comment]
Closing because we haven't heard back yet. But please let us know if this is still happening.
