### ISSUE TITLE
Android 8/8+: Fatal Exception: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by Saren-Arterius** [lingochamp/FileDownloader#1017]
Library version: `com.liulishuo.filedownloader:library:1.6.5`

Build Environment
- compileSdkVersion 26
- buildToolsVersion "27.0.3"
- minSdkVersion 15
- targetSdkVersion 26

Observations
- 100% of this crash happens in Android 8+
- 99% of this crash happens when app is at background

Info from Crashlytics
> 
> Not allowed to start service Intent { cmp=com.XXXX.YYYY/com.liulishuo.filedownloader.services.FileDownloadService$SeparateProcessService }: app is in background uid UidRecord{51e9798 u0a324 CAC bg:+1m31s64ms idle procs:2 seq(73,73,73)}
> ```
> Fatal Exception: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.XXXX.YYYY/com.liulishuo.filedownloader.services.FileDownloadService$SeparateProcessService }: app is in background uid UidRecord{51e9798 u0a324 CAC  bg:+1m31s64ms idle procs:2 seq(73,73,73)}
>        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1522)
>        at android.app.ContextImpl.startService(ContextImpl.java:1478)
>        at android.content.ContextWrapper.startService(ContextWrapper.java:645)
>        at com.liulishuo.filedownloader.services.BaseFileServiceUIGuard.bindStartByContext(SourceFile:157)
>        at com.liulishuo.filedownloader.services.BaseFileServiceUIGuard.bindStartByContext(SourceFile:126)
>        at com.liulishuo.filedownloader.FileDownloadServiceProxy.bindStartByContext(SourceFile:112)
>        at com.liulishuo.filedownloader.FileDownloader.bindService(SourceFile:486)
>        at com.liulishuo.filedownloader.LostServiceConnectedHandler.disconnected(SourceFile:94)
>        at com.liulishuo.filedownloader.FileDownloadConnectListener.callback(SourceFile:45)
>        at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.trigger(SourceFile:132)
>        at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.publish(SourceFile:107)
>        at com.liulishuo.filedownloader.event.DownloadEventPoolImpl$1.run(SourceFile:121)
>        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
>        at java.lang.Thread.run(Thread.java:764)
> ```

Related:
https://stackoverflow.com/questions/46445265/android-8-0-java-lang-illegalstateexception-not-allowed-to-start-service-inten?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by tomUp** [comment]
Library version: `com.liulishuo.filedownloader:library:1.6.9`

Build Environment

- compileSdkVersion 27
- buildToolsVersion "27.0.3"
- minSdkVersion 19
- targetSdkVersion 27

devices

- OS：Android 8.1
- model：VIVO X21A

error message
`Fatal Exception: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.XXXX.YYYY/com.liulishuo.filedownloader.services.FileDownloadService$SeparateProcessService }: app is in background uid UidRecord{ef05957 u0a126 LAST  bg:+1m57s667ms idle change:cached proces:2 seq(0,0,0)}`

**Comment by rantianhua** [comment]
@Saren-Arterius you said : 
> 99% of this crash happens when app is at background

So you mean 1% of this crash happens when app is at foreground?

**Comment by Saren-Arterius** [comment]
Statistically, yes

在 2018年5月2日週三 17:52，冉天华 <notifications@github.com> 寫道：

**Comment by tomUp** [comment]
@rantianhua 

In my case, when the APP is back in the background, about 5 minutes or so will be killed, and then the download will be wrong.

All Android 8.1 devices have this crash.

**Comment by rantianhua** [comment]
@tomUp Yes, After Android 8.0, background service is limited.
