### ISSUE TITLE
Download acceleration with split downloading

### ISSUE THREAD

**Issue by surahul** [lingochamp/FileDownloader#102]
Is there any plan to add multithread split downloading for single file download to increase download speed ?

**Comment by Jacksgong** [comment]
👍  Yeap, I considered,  and in the later version, after some other more important things all done.

> P.S: Welcome PR :)

**Comment by surahul** [comment]
Ok... The point is you have actively maintained this download manager and it is by far the most reliable and customisable manager, but due to lack of this particular feature I've being kept from using this library ..Hope to see it soon

**Comment by Jacksgong** [comment]
Thank you, I get it.

**Comment by MatoMA** [comment]
感觉其实对提速没有太大意义，这边测试基本可以到2Mb/s，基本把带宽吃完了。

**Comment by sajadmartiny** [comment]
The issue is solved ?

**Comment by Jacksgong** [comment]
@sajadmartiny Thanks for you remind this issue, though in case of the mobile device, the I/O、 CPU、Network resources is very limited, and in the current version, FileDownloader has already used them very nervous in the most cases, so this feature isn't so urgency, but we will implement this feature when other more urgent feature have been done, and also, very welcome your pull request.

**Comment by Jeffin21** [comment]
Need multi thread downloading. Thank You

**Comment by Jacksgong** [comment]
I rewrite all download logic to support such feature, relate to [DownloadLaunchRunnable](https://github.com/lingochamp/FileDownloader/blob/072f4a80f73368f5617de36b9533c50c00a88dfd/library/src/main/java/com/liulishuo/filedownloader/download/DownloadLaunchRunnable.java):

```
You can use this to launch downloading, on here the download will be launched separate following.
 steps:
 <p/>
 step 1. create the first connection
          ( this first connection is used for:
                  1. checkup the saved etag is overdue
                  2. checkup whether the partial-accept is supported
                  3. checkup whether the current connection is chunked. )

 step 2. if the saved etag is overdue -> jump to step 1 to checkup whether the partial-accept is supported.
 step 3. if (NOT chunked) & partial-accept & output stream support-seek:
              create multiple {@link DownloadTask} to download.
         else:
              reuse the first connection and use {@link FetchDataTask} to fetch data from the connection.
 <p/>
 We use {@link DownloadStatusCallback} to handle all events sync to DB/filesystem and callback to user.
```

**Comment by Jacksgong** [comment]
I test on my home, it can use all resources on my network (the broadband on my home is 100Mb/s):

36MB file would be finished on about 3.082s:

![image](https://cloud.githubusercontent.com/assets/6176417/26762628/065dbcee-4978-11e7-9265-a2267a000708.png)

**Comment by wenzhihao123** [comment]
> Since the new architecture support multi-connection I test on my home, it can use all resources on my network (the broadband on my home is 100Mb/s):
> 
> 36MB file can be finished on about 3.082s:
> 
> ![image](https://cloud.githubusercontent.com/assets/6176417/26762628/065dbcee-4978-11e7-9265-a2267a000708.png)
> 
> ![image](https://cloud.githubusercontent.com/assets/6176417/26762651/68ad76c8-4978-11e7-9eed-821f73efe536.png)

楼主有单个任务多线程的栗子么~
