### ISSUE TITLE
RandomAccessFile setLength 预占位文件产生，但是 df 系统的磁盘没有变化

### ISSUE THREAD

**Issue by zetaoWu** [lingochamp/FileDownloader#1020]
/sdcard/下   RandomAccessFile setLength(1024 * 1024 * 1024)  1个G预占位文件产生，但是 df 查看系统的磁盘却没有变化？

**Comment by rantianhua** [comment]
你可以参考[这里](https://www.ibm.com/support/knowledgecenter/zh/ssw_aix_72/com.ibm.aix.cmds2/df.htm) 里面的描述部分说了：
> 在某些例外情况下，例如运行 df 命令时，文件系统正在被修改，那么 df 命令显示的统计信息可能并不正确。
