### ISSUE TITLE
同一个文件，每次访问都有动态参数。

### ISSUE THREAD

**Issue by yhd888** [lingochamp/FileDownloader#1021]
问题：
1、下载文件url都是动态参数。
2、每次下载的url参数内容value值都不一样。
3、下载的文件如何 区分 已经 已经下载 不进行 重复下载。
思考：
1、我下载下来的文件，文件名 都是 您的框架 进行M5的。
2、我在哪里可以设置 动态参数？
3、当前 这种下载模式，框架能 区分开 文件是否已经下载？

**Comment by rantianhua** [comment]
请参照 #224 ，自定义 `FileDownloadHelper.IdGenerator`
