### ISSUE TITLE
TaskID does not place in Integer

### ISSUE THREAD

**Issue by mahdihs76** [lingochamp/FileDownloader#1022]
Hello guys.
When I started download task, library gives me negative task id. I guess id does not place in (int) primitive.
This problem occurs in big files.
I guess it will be fixed by replacing this type to (long).
`        BaseDownloadTask.IRunningTask runningTask = FileDownloadList.getImpl().get(fileRow.getDownloadTaskId());
`
in this part runningTask will be null.

**Comment by rantianhua** [comment]
Below is the code for generating id:
```
    @Override
    public int generateId(String url, String path, boolean pathAsDirectory) {
        if (pathAsDirectory) {
            return FileDownloadUtils.md5(formatString("%sp%s@dir", url, path)).hashCode();
        } else {
            return FileDownloadUtils.md5(formatString("%sp%s", url, path)).hashCode();
        }
    }
```

You can see that the id is a hash code of the string, so it's reasonable that the id is negative sometime.
