### ISSUE TITLE
如果在真正下载之前，只想获取一下文件长度，然后提示用户文件大小，该怎么做呢

### ISSUE THREAD

**Issue by humanheima** [lingochamp/FileDownloader#1029]

**Comment by rantianhua** [comment]
你可以在 `FileDownloadListener#connected` 回调中获取到文件长度（`totalBytes`）后暂停下载，待用户确认之后，再重新开启下载。这是一个解决方案，不过不建议这样做，因为在 `connect` 回调中暂停下载也不能保证没有进行任何数据下载，对用户来说是有流量浪费的。

你的场景更好的方式是在没有进行任何下载前就知道文件的长度了，即在下载前你有文件大小和文件链接这两个数据，而这一般是你们自己的业务，而不是通过 `FileDownloader` 来提供方案。
