### ISSUE TITLE
Logo offer for FileDownloader

### ISSUE THREAD

**Issue by familqasimov** [lingochamp/FileDownloader#1031]
Hi sir. I'm graphic designer. I have studied your work and I think a new design will make you more visible. I would like to offer logo. I can give you all the formats of the design free. If you want I send you PR or a change please specify.

![untitled-3](https://user-images.githubusercontent.com/36432269/40271944-f4ef4116-5bb5-11e8-9551-d53b1b7e4c6f.png)

Best regard
Famil :)

**Comment by rantianhua** [comment]
Thank you so much and welcome your PR. I choose the second one.
