### ISSUE TITLE
为什么下载的视频没有后缀名

### ISSUE THREAD

**Issue by darkrevier** [lingochamp/FileDownloader#1037]
String path = Environment.getExternalStorageDirectory()+ File.separator+ "xxx_video";
FileDownloader.getImpl().create("http://flv3.bn.netease.com/tvmrepo/2018/5/Q/M/EDHM2GIQM/SD/EDHM2GIQM-mobile.mp4").setWifiRequired(true).setPath(path,true).setListener(new FileDownloadListener() {
                    @Override
                    protected void pending(BaseDownloadTask task, int soFarBytes, int totalBytes) {

                    }

                    @Override
                    protected void progress(BaseDownloadTask task, int soFarBytes, int totalBytes) {
                        int percent=(int) ((double) soFarBytes / (double) totalBytes * 100);
                    }

                    @Override
                    protected void blockComplete(BaseDownloadTask task) {

                    }

                    @Override
                    protected void completed(BaseDownloadTask task) {
                    }

                    @Override
                    protected void paused(BaseDownloadTask task, int soFarBytes, int totalBytes) {

                    }

                    @Override
                    protected void error(BaseDownloadTask task, Throwable e) {

                    }

                    @Override
                    protected void warn(BaseDownloadTask task) {
                    }
                }).start();

**Comment by rantianhua** [comment]
因为你没有调用 `setFilename` ，FileDownloader 会在 response header 里面的 Content-Disposition 里面去找，如果还没有，那就把 url 的 md5 值作为文件名，所以就是你看到的没有后缀名。

**Comment by darkrevier** [comment]
请问setFilename在哪指定

**Comment by rantianhua** [comment]
`BaseDownloadTask#setFilename(String)`

**Comment by darkrevier** [comment]
BaseDownloadTask这个类中没有这个方法啊,是需要setTag方法吗

**Comment by rantianhua** [comment]
抱歉，确实没有。其实在接口中注释已经说得很清楚了：
```
/**
     * @return If {@link #isPathAsDirectory()} is {@code true}, the {@code filename} will be found
     * in contentDisposition from the response as default, if can't find contentDisposition, the
     * {@code filename} will be generated by {@link FileDownloadUtils#generateFileName(String)} with
     * {@code url}. It will be found before the callback of
     * {@link FileDownloadListener#connected(BaseDownloadTask, String, boolean, int, int)}.
     * </p>
     * If {@link #isPathAsDirectory()} is {@code false}, the {@code filename} will be found
     * immediately when you invoke {@link #setPath(String, boolean)} .
     */
    String getFilename();
```
