### ISSUE TITLE
setAutoRetryTimes

### ISSUE THREAD

**Issue by 15766736837** [lingochamp/FileDownloader#1038]
#### Before Issue
设置完重试次数 setAutoRetryTimes
可以设置重试的间隔?
因为wifi跟4G的切换也会造成重试,我想设置每次重试的一个间隔

#### Issue

请在Issue前认真的跟进上面提到的建议，这样将可以极大的加快你遇到问题的处理。

**Comment by rantianhua** [comment]
目前没有这个功能，而且也不考虑添加这个功能。关于重试，在 [Okdownload](https://github.com/lingochamp/okdownload/issues/15#issuecomment-380006418) 里面用了新的机制，你可以使用 OkDownload 达到你的目的。
