### ISSUE TITLE
unexpected end of stream on com.android.okhttp.Address@31d407ff

### ISSUE THREAD

**Issue by Jamgle** [lingochamp/FileDownloader#1039]
用 这个 url  http://222.188.110.75:9002/20180530120804.ps?fid=423951,1f89505c6c0997c5&weednum=1

报出异常 unexpected end of stream on com.android.okhttp.Address@31d407ff

**Comment by rantianhua** [comment]
unexpected end of stream 这通常是后端问题。而且提 issue 最好按照模板来，尤其是要提供完整的 Filedownloader 的日志。
