### ISSUE TITLE
progress为啥不回调？

### ISSUE THREAD

**Issue by wenzhihao123** [lingochamp/FileDownloader#1040]
progress不回调啊？、
final FileDownloadListener queueTarget = new FileDownloadListener() {
            @Override
            protected void pending(BaseDownloadTask task, int soFarBytes, int totalBytes) {
                int preProgress = 0;
                if ( totalBytes != 0 ) {
                    preProgress = (int)(soFarBytes / (float)totalBytes * 100);
                }
                Log.e("wenzhihao","pending--->"+preProgress);
            }

            @Override
            protected void connected(BaseDownloadTask task, String etag, boolean isContinue, int soFarBytes, int totalBytes) {
                int preProgress = 0;
                if ( totalBytes != 0 ) {
                    preProgress = (int)(soFarBytes / (float)totalBytes * 100);
                }
                Log.e("wenzhihao","connected--->"+preProgress);
            }

            @Override
            protected void progress(BaseDownloadTask task, int soFarBytes, int totalBytes) {
                int progress = 0;
                if ( totalBytes != 0 ) {
                    progress = (int)(soFarBytes / (float)totalBytes * 100);
                }
                Log.e("wenzhihao","progress--->"+progress);
            }
            @Override
            protected void blockComplete(BaseDownloadTask task) {
            }

            @Override
            protected void retry(final BaseDownloadTask task, final Throwable ex, final int retryingTimes, final int soFarBytes) {
            }

            @Override
            protected void completed(final BaseDownloadTask task) {
                Log.e("wenzhihao","completed--->"+task.getPath());
            }

            @Override
            protected void paused(BaseDownloadTask task, int soFarBytes, int totalBytes) {
                int progress = 0;
                if ( totalBytes != 0 ) {
                    progress = (int)(soFarBytes / (float)totalBytes * 100);
                }
                Log.e("wenzhihao","paused--->");
            }

            @Override
            protected void error(BaseDownloadTask task, Throwable e) {
                Log.e("wenzhihao","error--->");
            }

            @Override
            protected void warn(BaseDownloadTask task) {
                Log.e("wenzhihao","warn--->");
            }
        };
        String url = "http://dl.ops.baidu.com/baidusearch_AndroidPhone_757p.apk";
        FileDownloader.getImpl().create(url)
                .setListener(queueTarget)
                .setAutoRetryTimes(1)
                .setTag(url.hashCode())
                .setCallbackProgressTimes(0)
                .asInQueueTask()
                .enqueue();
        FileDownloader.getImpl().start(queueTarget, true);

**Comment by BCsl** [comment]
更新到 1.7.4 后也有这个问题，获取文件大小失败了，用 1.7.3 吧

**Comment by wenzhihao123** [comment]
.setCallbackProgressTimes(0) 这里设置更新的时间  传100ms就回调啦

**Comment by Jacksgong** [comment]
根据文档:

```java
/**
 * Set the maximum callback count of
 * {@link FileDownloadListener#progress(BaseDownloadTask, int, int)} during the entire process
 * of downloading.
 * <p>
 * <strong>Note:</strong> this function will not work if the URL is refer to 'chucked' resource.
 *
 * @param callbackProgressCount The maximum callback count of
 *                              {@link FileDownloadListener#progress}
 *                              during the entire process of downloading.
 *                              <p>
 *                              Default value is 100, If the value less than or equal to 0, you
 *                              will not receive any callback of
 *                              {@link FileDownloadListener#progress}
 *                              .
 * @see #setCallbackProgressMinInterval(int)
 */
BaseDownloadTask setCallbackProgressTimes(int callbackProgressCount);

/**
 * Set the minimum time interval between each callback of
 * {@link FileDownloadListener#progress(BaseDownloadTask, int, int)}.
 *
 * @param minIntervalMillis The minimum interval between each callback of
 *                          {@link FileDownloadListener#progress(BaseDownloadTask, int, int)}.
 *                          <p>
 *                          Unit: millisecond.
 *                          <p>
 *                          Default value is
 *                          {@link #DEFAULT_CALLBACK_PROGRESS_MIN_INTERVAL_MILLIS}.
 *                          <p>
 *                          Scope: [5, {@link Integer#MAX_VALUE}.
 * @see #setCallbackProgressTimes(int)
 */
BaseDownloadTask setCallbackProgressMinInterval(int minIntervalMillis);

```

@wenzhihao123 说的不完全对，但是有提到，`setCallbackProgressTimes(0)`设置的就是全程最多的回调次数，你设置的是`0`，因此没有回调。

---

> P.S. 如果你希望设置最小回调间隔，请使用: `setCallbackProgressMinInterval`

**Comment by wenzhihao123** [comment]
setCallbackProgressTimes是设置回调次数吗？setCallbackProgressMinInterval才是设置每次回调间隔~ 谢谢

**Comment by Jacksgong** [comment]
@wenzhihao123 嗯。是的。

**Comment by wenzhihao123** [comment]
@Jacksgong 谢谢 大佬 ~

**Comment by jhwsx** [comment]
对于多任务下载的情形，setCallbackProgressTimes 是设置单个任务的回调次数，还是总的任务的回调次数呢？
