### ISSUE TITLE
请问我开启下载跟继续下载都是以下代码这样会出现问题吗?

### ISSUE THREAD

**Issue by 15766736837** [lingochamp/FileDownloader#1041]
#### Issue
/** 开启下载跟继续下载都是以下代码  url数组里面有两个文件 */
for (int i = 0; i < url.length; i++) {
FileDownloader.getImpl()
.create(url[i])
.setPath(path)
.setListener(queueTarget)
.setAutoRetryTimes(50)
.setTag(position)
.asInQueueTask()
.enqueue();
}
mImpl.start(queueTarget, true);

/** 暂停下载的代码 */
mImpl.pause(item.getApkId());
mImpl.pause(item.getObbId());

多次暂停跟继续来回切换,会进入pending, 然后就不再下载了

**Comment by rantianhua** [comment]
不好意思，请务必按照问题模板提问，尤其是 FileDownload 日志，不然只根据描述的现象无法帮助你解决问题。
