### ISSUE TITLE
下载zip文件 响应很慢是怎么回事

### ISSUE THREAD

**Issue by Godsbox** [lingochamp/FileDownloader#1044]
文件越大响应越慢 开启下载到有数据返回  基本需要10秒以上

06-02 16:04:17.139 com.lzj.shanyi:filedownloader D/FileDownloader.FileDownloadManager: request start the task with url(http://apppic.3000test.com/s1/game_source_zip/2C600D04-A52F-F69E-64C7-47894BE6A85D-1527753034.zip) path(/storage/emulated/0/Android/data/com.lzj.shanyi/files/game70628/json/2C600D04-A52F-F69E-64C7-47894BE6A85D-1527753034.zip) isDirectory(FALSE)
06-02 16:04:17.159 com.lzj.shanyi:filedownloader D/FileDownloader.FileDownloadUtils: can't continue 1930072384 file not suit, exists[FALSE], directory[FALSE]
06-02 16:04:17.159 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: 1930072384 request header {Range=[bytes=0-]}
06-02 16:04:22.949 com.lzj.shanyi:filedownloader D/FileDownloader.FileDownloadUtils: etag find "402c309-56d7bb939e574" for task(1930072384)
06-02 16:04:22.969 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadLaunchRunnable: fetch data with multiple connection(count: [4]) for task[1930072384] totalLength[67289865]
06-02 16:04:22.969 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadLaunchRunnable: enable multiple connection: id[1930072384] index[0] range[0, 16822465) current offset(0)
06-02 16:04:22.969 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadLaunchRunnable: enable multiple connection: id[1930072384] index[1] range[16822466, 33644931) current offset(16822466)
06-02 16:04:22.969 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadLaunchRunnable: enable multiple connection: id[1930072384] index[2] range[33644932, 50467397) current offset(33644932)
06-02 16:04:22.969 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadLaunchRunnable: enable multiple connection: id[1930072384] index[3] range[50467398, 0) current offset(50467398)
06-02 16:04:22.969 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: 1930072384 request header {Range=[bytes=0-16822465]}
06-02 16:04:22.969 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: 1930072384 request header {Range=[bytes=16822466-33644931]}
06-02 16:04:22.969 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: 1930072384 request header {Range=[bytes=33644932-50467397]}
06-02 16:04:22.969 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: 1930072384 request header {Range=[bytes=50467398-]}
06-02 16:04:25.889 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadRunnable: the connection[3] for 1930072384, is connected range[50467398, 0) current offset[50467398] with code[206]
06-02 16:04:25.889 com.lzj.shanyi:filedownloader D/FileDownloader.FetchDataTask: start fetch(3): range [50467398, 0), seek to[50467398]
06-02 16:04:25.909 com.lzj.shanyi:filedownloader D/FileDownloader.FetchDataTask: require sync id[1930072384] index[3] offset[50470238], consume[16]
06-02 16:04:27.899 com.lzj.shanyi:filedownloader D/FileDownloader.FetchDataTask: require sync id[1930072384] index[3] offset[58701514], consume[8]
06-02 16:04:28.659 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadRunnable: the connection[1] for 1930072384, is connected range[16822466, 33644931) current offset[16822466] with code[206]
06-02 16:04:28.659 com.lzj.shanyi:filedownloader D/FileDownloader.FetchDataTask: start fetch(1): range [16822466, 33644931), seek to[16822466]

06-02 16:01:40.659 com.lzj.shanyi V/FileDownloader.DownloadTaskHunter: the task[1930072384] has been into the launch pool.
06-02 16:01:40.659 com.lzj.shanyi D/FileDownloader.FileDownloadMessenger: notify begin 1930072384@com.liulishuo.filedownloader.DownloadTask@4b21c0f8
06-02 16:01:40.659 com.lzj.shanyi V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@4b21c13c by 11 
06-02 16:01:40.669 com.lzj.shanyi D/FileDownloader.MessageSnapshotGate: ~~~callback 1930072384 old[11] new[1] 1
06-02 16:01:40.669 com.lzj.shanyi D/FileDownloader.FileDownloadMessenger: notify pending 1930072384@com.liulishuo.filedownloader.DownloadTask@4b21c0f8
06-02 16:01:40.669 com.lzj.shanyi D/FileDownloader.MessageSnapshotGate: ~~~callback 1930072384 old[1] new[6] 1
06-02 16:01:40.669 com.lzj.shanyi D/FileDownloader.FileDownloadMessenger: notify started 1930072384@com.liulishuo.filedownloader.DownloadTask@4b21c0f8
06-02 16:01:46.469 com.lzj.shanyi D/FileDownloader.MessageSnapshotGate: ~~~callback 1930072384 old[6] new[2] 1
06-02 16:01:46.469 com.lzj.shanyi D/FileDownloader.FileDownloadMessenger: notify connected 1930072384@com.liulishuo.filedownloader.DownloadTask@4b21c0f8
06-02 16:01:49.359 com.lzj.shanyi D/FileDownloader.MessageSnapshotGate: ~~~callback 1930072384 old[2] new[3] 1
06-02 16:01:49.359 com.lzj.shanyi D/FileDownloader.FileDownloadMessenger: notify progress 1930072384@com.liulishuo.filedownloader.DownloadTask@4b21c0f8 2840 67289865
06-02 16:01:49.539 com.lzj.shanyi D/FileDownloader.MessageSnapshotGate: ~~~callback 1930072384 old[3] new[3] 1
06-02 16:01:49.539 com.lzj.shanyi D/FileDownloader.FileDownloadMessenger: notify progress 1930072384@com.liulishuo.filedownloader.DownloadTask@4b21c0f8 673044 67289865
06-02 16:01:49.719 com.lzj.shanyi D/FileDownloader.MessageSnapshotGate: ~~~callback 1930072384 old[3] new[3] 1
06-02 16:01:49.719 com.lzj.shanyi D/FileDownloader.FileDownloadMessenger: notify progress 1930072384@com.liulishuo.filedownloader.DownloadTask@4b21c0f8 1341172 67289865
06-02 16:01:49.869 com.lzj.shanyi D/FileDownloader.MessageSnapshotGate: ~~~callback 1930072384 old[3] new[3] 1

**Comment by Jacksgong** [comment]
```
06-02 16:01:40.659 com.lzj.shanyi V/FileDownloader.DownloadTaskHunter: the task[1930072384] has been into the launch pool.
06-02 16:01:40.659 com.lzj.shanyi D/FileDownloader.FileDownloadMessenger: notify begin 1930072384@com.liulishuo.filedownloader.DownloadTask@4b21c0f8
06-02 16:01:40.659 com.lzj.shanyi V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@4b21c13c by 11
06-02 16:01:40.669 com.lzj.shanyi D/FileDownloader.MessageSnapshotGate: ~~~callback 1930072384 old[11] new[1] 1
06-02 16:01:40.669 com.lzj.shanyi D/FileDownloader.FileDownloadMessenger: notify pending 1930072384@com.liulishuo.filedownloader.DownloadTask@4b21c0f8
06-02 16:01:40.669 com.lzj.shanyi D/FileDownloader.MessageSnapshotGate: ~~~callback 1930072384 old[1] new[6] 1
06-02 16:01:40.669 com.lzj.shanyi D/FileDownloader.FileDownloadMessenger: notify started 1930072384@com.liulishuo.filedownloader.DownloadTask@4b21c0f8
06-02 16:01:46.469 com.lzj.shanyi D/FileDownloader.MessageSnapshotGate: ~~~callback 1930072384 old[6] new[2] 1
06-02 16:01:46.469 com.lzj.shanyi D/FileDownloader.FileDownloadMessenger: notify connected 1930072384@com.liulishuo.filedownloader.DownloadTask@4b21c0f8
```

根据日志，这里的耗时是`started -> connected`的环节，该环节是URL的建连与响应的耗时，这个只与该URL连接的耗时以及网络环境有关，与是否是zip，以及文件大小没有关系，与FileDownloader无关，FileDownloader从begin到下载线程启动开始下载的`started`大约10ms左右。

**Comment by Godsbox** [comment]
但是我用浏览器 下载是不会的哦~  我用HttpURLConnection直接下载 也不会啊
 D/FileDownloader.FileDownloadUtils: etag find "402c309-56d7bb939e574" for task(1930072384)
这个步骤是做什么的呢

**Comment by Godsbox** [comment]
我看都是 分段在下载 我可以关闭这个功能吗？
06-02 16:04:22.969 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadLaunchRunnable: enable multiple connection: id[1930072384] index[0] range[0, 16822465) current offset(0)
06-02 16:04:22.969 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadLaunchRunnable: enable multiple connection: id[1930072384] index[1] range[16822466, 33644931) current offset(16822466)
06-02 16:04:22.969 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadLaunchRunnable: enable multiple connection: id[1930072384] index[2] range[33644932, 50467397) current offset(33644932)
06-02 16:04:22.969 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadLaunchRunnable: enable multiple connection: id[1930072384] index[3] range[50467398, 0) current offset(50467398)
