### ISSUE TITLE
文件没有正确下载就回调了complete

### ISSUE THREAD

**Issue by CleverSJX** [lingochamp/FileDownloader#1048]
#### 200多M的视频文件 刚开始下载就回调了complete 下面是再次调用这个文件下载的日志
06-04 14:14:05.708 26672-26798/com.longjing.debug D/FileDownloader.LaunchTaskPool: expire 0 tasks
06-04 14:14:05.716 26672-26798/com.longjing.debug D/FileDownloader.FileDownloadProperties: not found filedownloader.properties
06-04 14:14:05.716 26672-26798/com.longjing.debug I/FileDownloader.FileDownloadProperties: init properties 0
                                                                                            load properties: http.lenient=FALSE; process.non-separate=FALSE; download.min-progress-step=65536; download.min-progress-time=2000; download.max-network-thread-count=3; file.non-pre-allocation=FALSE; broadcast.completed=FALSE; download.trial-connection-head-method=FALSE
06-04 14:14:05.723 26672-26798/com.longjing.debug D/FileDownloader.FileDownloadServiceUIGuard: bindStartByContext LongJingApp
06-04 14:14:05.765 26672-26798/com.longjing.debug D/FileDownloader.DownloadTask: setPath /data/data/com.longjing.debug/files/download/78a487ba6a6564a4a7f45b25b511c47e
06-04 14:14:05.769 26672-26798/com.longjing.debug D/FileDownloader.DownloadTask: setListener com.longjing.service.DownloadService$2@72b9e0e
06-04 14:14:05.789 26672-26798/com.longjing.debug D/FileDownloader.InQueueTaskImpl: add the task[-8947698] to the queue
06-04 14:14:05.789 26672-26798/com.longjing.debug V/FileDownloader.FileDownloadList: add list in all -8947698@com.liulishuo.filedownloader.DownloadTask@248ec02f 0 1
06-04 14:14:05.794 26672-26798/com.longjing.debug V/FileDownloader.FileDownloader: start list attachKey[581981756] size[1] listener[com.longjing.service.DownloadService$2@72b9e0e] isSerial[TRUE]
06-04 14:14:05.795 26672-26798/com.longjing.debug D/FileDownloader.SerialHandlerCallback: start next com.longjing.service.DownloadService$2@72b9e0e 0
06-04 14:14:05.809 26672-26851/com.longjing.debug V/FileDownloader.DownloadTaskHunter: call start Url[http://s.swao.cn/o_1cf57jequ1hvj1bkg1c3a98kqff7.mp4], Path[/data/data/com.longjing.debug/files/download/78a487ba6a6564a4a7f45b25b511c47e] Listener[com.longjing.service.DownloadService$2@72b9e0e], Tag[null]
06-04 14:14:05.810 26672-26851/com.longjing.debug V/FileDownloader.DownloadTaskHunter: the task[-8947698] has been into the launch pool.
06-04 14:14:05.830 26672-26852/com.longjing.debug V/FileDownloader.FileDownloadEventPool: setListener event.service.connect.changed
06-04 14:14:05.830 26672-26852/com.longjing.debug D/FileDownloader.LostServiceConnectedHandler: Waiting for connecting with the downloader service... -8947698
06-04 14:14:05.830 26672-26852/com.longjing.debug D/FileDownloader.FileDownloadServiceUIGuard: bindStartByContext LongJingApp
06-04 14:14:05.834 26672-26852/com.longjing.debug D/FileDownloader.DownloadTaskHunter: free the task -8947698, when the status is 10
06-04 14:14:06.424 26834-26834/com.longjing.debug:filedownloader D/FileDownloader.FileDownloadProperties: not found filedownloader.properties
06-04 14:14:06.425 26834-26834/com.longjing.debug:filedownloader I/FileDownloader.FileDownloadProperties: init properties 11
                                                                                                           load properties: http.lenient=FALSE; process.non-separate=FALSE; download.min-progress-step=65536; download.min-progress-time=2000; download.max-network-thread-count=3; file.non-pre-allocation=FALSE; broadcast.completed=FALSE; download.trial-connection-head-method=FALSE
06-04 14:14:06.439 26834-26834/com.longjing.debug:filedownloader D/FileDownloader.FileDownloadDatabase: refreshed data count: 0 , delete data count: 0, reset id count: 0. consume 1
06-04 14:14:06.446 26672-26672/com.longjing.debug D/FileDownloader.FileDownloadServiceUIGuard: onServiceConnected ComponentInfo{com.longjing.debug/com.liulishuo.filedownloader.services.FileDownloadService$SeparateProcessService} com.liulishuo.filedownloader.i.IFileDownloadIPCService$Stub$Proxy@3c8160e6
06-04 14:14:06.447 26834-26850/com.longjing.debug:filedownloader D/FileDownloader.FileDownloadManager: pause all tasks 0
06-04 14:14:06.449 26672-26672/com.longjing.debug V/FileDownloader.FileDownloadEventPool: asyncPublishInNewThread event.service.connect.changed
06-04 14:14:06.457 26672-26864/com.longjing.debug V/FileDownloader.FileDownloadEventPool: publish event.service.connect.changed
06-04 14:14:06.457 26672-26864/com.longjing.debug D/FileDownloader.LostServiceConnectedHandler: The downloader service is connected.
06-04 14:14:06.459 26672-26864/com.longjing.debug D/FileDownloader.InQueueTaskImpl: add the task[-8947698] to the queue
06-04 14:14:06.459 26672-26851/com.longjing.debug D/FileDownloader.SerialHandlerCallback: start next com.longjing.service.DownloadService$2@72b9e0e 0
06-04 14:14:06.460 26672-26851/com.longjing.debug V/FileDownloader.DownloadTaskHunter: call start Url[http://s.swao.cn/o_1cf57jequ1hvj1bkg1c3a98kqff7.mp4], Path[/data/data/com.longjing.debug/files/download/78a487ba6a6564a4a7f45b25b511c47e] Listener[com.longjing.service.DownloadService$2@72b9e0e], Tag[null]
06-04 14:14:06.460 26672-26851/com.longjing.debug V/FileDownloader.DownloadTaskHunter: the task[-8947698] has been into the launch pool.
06-04 14:14:06.464 26672-26865/com.longjing.debug D/FileDownloader.FileDownloadMessenger: notify begin -8947698@com.liulishuo.filedownloader.DownloadTask@248ec02f
06-04 14:14:06.464 26672-26865/com.longjing.debug V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@1f4927d by 11 
06-04 14:14:06.474 26672-26865/com.longjing.debug D/FileDownloader.MessageSnapshotGate: ~~~callback -8947698 old[11] new[-3] 1
06-04 14:14:06.474 26672-26865/com.longjing.debug V/FileDownloader.FileDownloadList: remove -8947698@com.liulishuo.filedownloader.DownloadTask@248ec02f left -3 0
06-04 14:14:06.474 26672-26865/com.longjing.debug D/FileDownloader.FileDownloadMessenger: notify block completed -8947698@com.liulishuo.filedownloader.DownloadTask@248ec02f FileDownloader-LauncherTask2
06-04 14:14:06.490 26672-26865/com.longjing.debug D/FileDownloader.MessageSnapshotGate: updateKeepFlow
06-04 14:14:06.490 26672-26866/com.longjing.debug D/FileDownloader.FileDownloadMessenger: notify completed -8947698@com.liulishuo.filedownloader.DownloadTask@248ec02f
06-04 14:14:06.490 26672-26866/com.longjing.debug V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@1f4927d by -3 
06-04 14:14:06.491 26672-26866/com.longjing.debug D/FileDownloader.SerialHandlerCallback: start next com.longjing.service.DownloadService$2@72b9e0e 1
06-04 14:14:06.491 26672-26851/com.longjing.debug D/FileDownloader.SerialHandlerCallback: final serial null 1

**Comment by CleverSJX** [comment]
再次下载这个文件就会直接回调complete

**Comment by wman0211** [comment]
可以看一下文件管理工具里面是不是已经存在这个同名文件了,已经存在的话就会直接complete

**Comment by CleverSJX** [comment]
文件下载显然是错误的，我无法播放这个视频，我app后再下载又可以了正常下载了，这是个偶然出现的bug。在不止一个设备上出现

**Comment by CleverSJX** [comment]
如果下载文件错误就调用了complete  存在了这个错误文件,再次下载 是没有校验文件合法性的吗

**Comment by CleverSJX** [comment]
还有就是 下载完成的回调 貌似没有校验文件的合法性

**Comment by rantianhua** [comment]
下载完成后是有校验文件长度的，如果下载结束后获取的长度和文件本身长度不符的话会有 Exception 抛出。请给出 `filedownloader` 进程的日志，我好确认内部具体发生了什么。

**Comment by rantianhua** [comment]
@CleverSJX 我在 Demo 中测试下载 http://s.swao.cn/o_1cf57jequ1hvj1bkg1c3a98kqff7.mp4 是没有问题的。所以希望你能提供 `filedownloader` 进程的日志。当然，为了提取日志简单，你可以在 `filedownloader.properties` 里配置 `process.non-separate=true`。这样你只需要提供你主进程的日志就好了。

**Comment by liaoxiang0808** [comment]
我这边碰到的一个类似的问题，下载的文件收到completed了，然后却不是正确的文件，去校验md5就会发现问题了，偶现的bug。

**Comment by rantianhua** [comment]
应该和 #804 一样的问题，后续请关注它。
