### ISSUE TITLE
图片下载大小和实际大小不符，无法打开

### ISSUE THREAD

**Issue by wangjian1154** [lingochamp/FileDownloader#1049]
图片地址
https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1528187214557&di=99894af78a6bb1a0d7b025fd707eeb8c&imgtype=0&src=http%3A%2F%2Fup.enterdesk.com%2Fedpic_source%2F2c%2F1a%2Ff4%2F2c1af4e395a1af8a57f67ab5b3772569.jpg

下载时Progress的回调里面，totalBytes的值是-1，文件下载不完整，走了下载完成。图片大小与实际大小不一样，无法打开

**Comment by rantianhua** [comment]
在用 chrome 打开时，可以注意到 chrome 的 request header 里面，`Accept-Encoding` 为 `gzip, deflate, br` ，你只需要在实例化 task 的时候添加这个请求头就好了：
```
FileDownloader.getImpl().create("https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1528187214557&di=99894af78a6bb1a0d7b025fd707eeb8c&imgtype=0&src=http%3A%2F%2Fup.enterdesk.com%2Fedpic_source%2F2c%2F1a%2Ff4%2F2c1af4e395a1af8a57f67ab5b3772569.jpg")
    .addHeader("Accept-Encoding", "gzip, deflate, br")
```

**Comment by Jacksgong** [comment]
Http协议并没有强制需要提供`Accept-Encoding`，也没有强制要求客户端需要支持哪些编解码方式，而后端在没有提供就返回一个非真实的数据，只有可能是为了某种私有协议的安全校验，亦或是后端根本就是写的有问题，Chrome提供这些，是因为Chrome对这些编解码支持。

#### 因此这个的具体的问题是

后端约定的私有协议，只有在提供`Accept-Encoding`的时候，才返回真实数据；或者是后端编写的时候存在问题，似的不符合http协议本身，恶心的强制校验`Accept-Encoding`

#### 解决方案

正如@rantianhua所说，这种私有协议的设计，恰好可以通过添加请求头绕过，不过需要特别注意的是，这个解决方案对于符合HTTP协议的共有协议来说并非正确的做法，因为默认的FileDownloader的connection并不支持这些编解码方式（如果你需要支持这些编解码方式，可以通过引入okhttp支持)。

#### 其他建议

建议以后遇到类似的问题，可以先自行通过抓包发现问题尝试进行解决。
