### ISSUE TITLE
自定义数据库组件无效

### ISSUE THREAD

**Issue by cunmin** [lingochamp/FileDownloader#1056]
我设置了FileDownloader.setupOnApplicationOnCreate(this)
                                         .database(new DatabaseCustomMaker(this))
                                         .commit();
参考网上修改数据库路径方法，重写mContext的getDataBasePath方法，但也不起作用
请问大神如果设置呢？

**Comment by rantianhua** [comment]
这其实和 FileDownloader 没有什么关系。这种问题你直接在 StackOverflow 搜一下就好了。比如 https://stackoverflow.com/questions/3911123/how-to-change-the-android-database-storage-path

**Comment by cunmin** [comment]
谢谢你回复我，我的需求是app卸载后仍然保存下载的状态，说白了我想要修改/data/data/Package Name/database/filedownloader.db数据库的路径，
FileDownloader.setupOnApplicationOnCreate(this)
        .database(new FileDownloadHelper.DatabaseCustomMaker() {
            @Override
            public FileDownloadDatabase customMake() {
                return XXX;
            }
        })
        .commit();
上面代码我自定义了的FileDownloadDatabase，但是customMake()没有被调用

**Comment by rantianhua** [comment]
请提供下 FileDownloader 版本，还有你在哪里进行 `FileDownloader`  的 `setup` 操作。

**Comment by rantianhua** [comment]
我在 Demo 中试了，自定义 Database 组件是有效的。所以需要再次确认一下，你是依据什么判断 `customMake()` 没有调用，有没有通过 debug 模式启动并在 `customMake()` 处断点？

**Comment by cunmin** [comment]
就是通过 debug 模式启动，在customMake()里打了个断点，但是没有跳到断点里，打印也一样没执行，会不会跟进程有关？我初始化前有下面的代码
String processName = getProcessName();
if (processName == null ||!processName.equalsIgnoreCase(getPackageName())) {
      return;
}
FileDownloader.setupOnApplicationOnCreate(this)
.............................

**Comment by cunmin** [comment]
起初我以为要进行下载操作才触发customMake()的，但是进行下载操作后还是没有被调用，

**Comment by cunmin** [comment]
哦哦，再问一下，不应该区分进程的话，如果有多个进程会不会初始化多个同样的组件？

**Comment by cunmin** [comment]
没事了，谢谢！
