### ISSUE TITLE
下载zip文件有几率出现重命名出错

### ISSUE THREAD

**Issue by Suma-sun** [lingochamp/FileDownloader#1058]
_java.io.IOException: Can't rename the  temp downloaded file(/storage/emulated/0/Android/data/**.demo/files/model/download/hema01.zip.temp) to the target file(/storage/emulated/0/Android/data/**.demo/files/model/download/hema01.zip

设置的单线程,下载7个zip

**Comment by rantianhua** [comment]
查看下 /storage/emulated/0/Android/data/.demo/files/model/download/hema01.zip.temp 文件是否存在？

**Comment by yueshao6800** [comment]
重命名错误我也边遇到的几率也不较大，目前不知道什么原因

**Comment by Suma-sun** [comment]
让同事加了日志，确实那个文件没下载下来。。。
还有测试有反馈，有时候下载到快下载完突然变成60%+重新下载，这种问题

**Comment by rantianhua** [comment]
@Suma-sun 你的版本是多少？你说的这个问题在 1.7.0 已经修复了。

**Comment by rantianhua** [comment]
@yueshao6800 你的版本是多少？在 1.7.0 之前，在 rename 失败的时候 FileDownloader 删除了临时文件。

**Comment by Suma-sun** [comment]
现在用的应该是1.7.3，那个问题，我找到了，同事调用下载的时候存储的path路径相同（文件名一样），导致A下载完后rename完被移动至其他目录，B任务就找不着这个文件了

**Comment by fastZhang** [comment]
没有   <uses-permission android:name="android.permission.INTERNET" />，会出现这个error log，却没有提示权限相关的信息。

我个人出现这种情况是因为，这个demo 我之前调试好了，然后把这个这个权限注释掉了。过段时间，回头再看这个项目，出了这个问题

希望作者把提示优化下
