### ISSUE TITLE
java.net.ProtocolException: unexpected end of stream

### ISSUE THREAD

**Issue by zhangming170622** [lingochamp/FileDownloader#1059]
I try download video. But I cannot complete download.Because error occur.The progress is 92%. I often fail download.Help me.

**Comment by rantianhua** [comment]
`unexpected end of stream` it's a server error and this a better question for StackOverFlow: https://stackoverflow.com/questions/45838774/java-io-ioexception-unexpected-end-of-stream-on-connection-in-android
