### ISSUE TITLE
Support configuration: does not downloading in separate process(:filedownloader), just share the main process

### ISSUE THREAD

**Issue by niejunhong** [lingochamp/FileDownloader#106]

**Comment by Jacksgong** [comment]
具体细节我没有测过，不过目前整体解耦的很干净，有一个简单粗暴的方法（如下图修改）:

![image](https://cloud.githubusercontent.com/assets/6176417/14524355/7e512f2a-026a-11e6-83c1-483a8437738b.png)

不过这样该内部还会绕一下binder，如果需要把这个干掉，就把 `FileDownloadServiceUIGuard` 中所有暴露的方法都直接转到 `FileDownloadMgr`，干掉 service。

---

> 后面我会考虑根据情况，真的做一个是否启用独立进程的适配。

**Comment by Jacksgong** [comment]
我评估下，如果不出意外，预计会在下个版本提供一键配置。

**Comment by niejunhong** [comment]
@Jacksgong 感谢啊，响应好快啊！超赞这个项目

**Comment by niejunhong** [comment]
@Jacksgong  刚看代码，没太明白DownloadTransferEvent这个是下载线程给主线程的各种状态的通知吧，如果按照那样改，那最后事件是在哪儿发出来的？

**Comment by Jacksgong** [comment]
注释掉的那两个，只是作为多进程通信时候的转发，真正的发起是在 `FileDownloadRunnable` 与 `FileDownloadMgr`。

**Comment by niejunhong** [comment]
@Jacksgong Can i just don't register callback for download service in BaseFileServiceUIGuard?

**Comment by Jacksgong** [comment]
👍 Yeap, You can do that and so, you will no need remove bellow codes:

![image](https://cloud.githubusercontent.com/assets/6176417/14551765/be39fca8-0309-11e6-936d-2ddf79a1e4ca.png)

**Comment by Jacksgong** [comment]
Has been supported in [v0.2.4](https://github.com/lingochamp/FileDownloader/releases/tag/v0.2.4).
