### ISSUE TITLE
Etag 的一些问题

### ISSUE THREAD

**Issue by Godsbox** [lingochamp/FileDownloader#1066]
Etag如果是弱值总是报 412错误 如：ETag: W/"5afcde22-f67"
 是服务端的配置问题是吗？ 我们可以手动修改etag吗 比如把 w去掉 直接变为 强值

**Comment by Godsbox** [comment]
服务端说需要使用 if-none-match 是否能增加一个配置 是否使用 这个来请求资源

**Comment by rantianhua** [comment]
抱歉现在才回复。

---

FileDownloader 内部通过 Etag 进行断点续传的功能。根据你的描述，确实是服务端问题的可能性更大。

---

手动修改的话，你只能通过自定义 `FileDownloadConnection` ，重写 `addHeader` 方法，判断是 `If-Match` 时，把 etag 改为强值。

**Comment by humanheima** [comment]
我想问一下把把 etag 改为强值。是什么意思？

**Comment by rantianhua** [comment]
弱值：ETag: W/"5afcde22-f67"
强值：ETag: "5afcde22-f67"

**Comment by humanheima** [comment]
好的，谢谢。研究研究。

**Comment by icetea0822** [comment]
我这里把etag改为强值还是不行

**Comment by zhouxiongjie** [comment]
> 抱歉现在才回复。
> 
> FileDownloader 内部通过 Etag 进行断点续传的功能。根据你的描述，确实是服务端问题的可能性更大。
> 
> 手动修改的话，你只能通过自定义 `FileDownloadConnection` ，重写 `addHeader` 方法，判断是 `If-Match` 时，把 etag 改为强值。

如何修改etag呢，我没找到相关调用方法

**Comment by rantianhua** [comment]
我回复里面描述了，需要自定义 FileDwonloadConnection 然后重写 addHeader 方法，判断 If-Match 时，把 Etag 改为强制。

修改就在你重写 `addHeader` 方法的时候。
