### ISSUE TITLE
下载出现412问题

### ISSUE THREAD

**Issue by Godsbox** [lingochamp/FileDownloader#1067]
我使用implementation引入方式出错, 但是当我把library并不会出错，这是为什么呢？
下面是出错日志

06-27 10:13:15.750 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: <---- -1472190497 request header {If-Match=["5b2361af-bc9"], Range=[bytes=0-], User-Agent=[FileDownloader/1.7.4]}
06-27 10:13:15.760 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: ----> 2118892285 response header {null=[HTTP/1.1 412 Precondition Failed], Connection=[keep-alive], Content-Length=[189], Content-Type=[text/html], Date=[Wed, 27 Jun 2018 02:15:36 GMT], Server=[nginx/1.10.1], X-Android-Received-Millis=[1530065595771], X-Android-Response-Source=[NETWORK 412], X-Android-Selected-Transport=[http/1.1], X-Android-Sent-Millis=[1530065595668], X-Dscp-Value=[0], X-Via=[1.1 PSgdhzdx6dk57:6 (Cdn Cache Server V2.0), 1.1 PSgddgdx4lv73:1 (Cdn Cache Server V2.0)]}
06-27 10:13:15.760 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadRunnable: the connection[-1] for 2118892285, is connected range[0, -1) current offset[0] with code[412]
06-27 10:13:15.770 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: <---- 2118892285 request header {If-Match=[W/"5afcde22-f67"], Range=[bytes=0-], User-Agent=[FileDownloader/1.7.4]}
06-27 10:13:15.780 com.lzj.shanyi:filedownloader D/dalvikvm: GC_FOR_ALLOC freed 487K, 14% free 3448K/4000K, paused 8ms, total 8ms
06-27 10:13:15.810 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: ----> -1472190497 response header {null=[HTTP/1.1 206 Partial Content], Accept-Ranges=[bytes], Cache-Control=[max-age=600], Connection=[keep-alive], Content-Length=[3017], Content-Range=[bytes 0-3016/3017], Content-Type=[application/json], Date=[Wed, 27 Jun 2018 02:15:36 GMT], ETag=["5b2361af-bc9"], Expires=[Wed, 27 Jun 2018 02:25:36 GMT], Last-Modified=[Fri, 15 Jun 2018 06:50:23 GMT], Server=[nginx/1.10.1], X-Android-Received-Millis=[1530065595825], X-Android-Response-Source=[NETWORK 206], X-Android-Selected-Transport=[http/1.1], X-Android-Sent-Millis=[1530065595768], X-Dscp-Value=[0], X-Via=[1.1 PSgdhzdx6aa56:5 (Cdn Cache Server V2.0), 1.1 PSgddgdx4fx71:1 (Cdn Cache Server V2.0)]}
06-27 10:13:15.810 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadRunnable: the connection[-1] for -1472190497, is connected range[0, -1) current offset[0] with code[206]
06-27 10:13:15.810 com.lzj.shanyi:filedownloader D/FileDownloader.FetchDataTask: start fetch(-1): range [0, -1), seek to[0]
06-27 10:13:15.810 com.lzj.shanyi:filedownloader I/FileDownloader.DownloadStatusCallback: inspectNeedCallbackToUser need callback to user
06-27 10:13:15.810 com.lzj.shanyi:filedownloader D/FileDownloader.FetchDataTask: require flushAndSync id[-1472190497] index[-1] offset[3017], consume[1]
06-27 10:13:15.810 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadLaunchRunnable: the connection has been completed(-1): [0, -1)  3017
06-27 10:13:15.810 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: <---- -811684309 request header {Range=[bytes=0-0], User-Agent=[FileDownloader/1.7.4]}
06-27 10:13:15.890 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: ----> 2118892285 response header {null=[HTTP/1.1 412 Precondition Failed], Connection=[keep-alive], Content-Length=[189], Content-Type=[text/html], Date=[Wed, 27 Jun 2018 02:15:36 GMT], Server=[nginx/1.10.1], X-Android-Received-Millis=[1530065595899], X-Android-Response-Source=[NETWORK 412], X-Android-Selected-Transport=[http/1.1], X-Android-Sent-Millis=[1530065595796], X-Dscp-Value=[0], X-Via=[1.1 PSgdhzdx6dk57:6 (Cdn Cache Server V2.0), 1.1 PSgddgdx4lv73:1 (Cdn Cache Server V2.0)]}
06-27 10:13:15.890 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadRunnable: the connection[-1] for 2118892285, is connected range[0, -1) current offset[0] with code[412]
06-27 10:13:15.890 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: <---- 2118892285 request header {If-Match=[W/"5afcde22-f67"], Range=[bytes=0-], User-Agent=[FileDownloader/1.7.4]}
06-27 10:13:15.890 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: ----> -811684309 response header {null=[HTTP/1.1 206 Partial Content], Accept-Ranges=[bytes], Cache-Control=[max-age=600], Connection=[keep-alive], Content-Length=[1], Content-Range=[bytes 0-0/2812], Content-Type=[application/javascript], Date=[Wed, 27 Jun 2018 02:15:36 GMT], ETag=["5b2258e0-afc"], Expires=[Wed, 27 Jun 2018 02:25:36 GMT], Last-Modified=[Thu, 14 Jun 2018 12:00:32 GMT], Server=[nginx/1.10.1], X-Android-Received-Millis=[1530065595903], X-Android-Response-Source=[NETWORK 206], X-Android-Selected-Transport=[http/1.1], X-Android-Sent-Millis=[1530065595829], X-Dscp-Value=[0], X-Via=[1.1 jfzhdx100:5 (Cdn Cache Server V2.0), 1.1 PSgddgdx4lv73:8 (Cdn Cache Server V2.0)]}
06-27 10:13:15.890 com.lzj.shanyi:filedownloader D/FileDownloader.FileDownloadUtils: etag find "5b2258e0-afc" for task(-811684309)
06-27 10:13:15.890 com.lzj.shanyi:filedownloader D/FileDownloader.FileDownloadUtils: can't continue -811684309 file not suit, exists[FALSE], directory[FALSE]
06-27 10:13:15.890 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: <---- -811684309 request header {If-Match=["5b2258e0-afc"], Range=[bytes=0-], User-Agent=[FileDownloader/1.7.4]}
06-27 10:13:15.960 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: ----> -811684309 response header {null=[HTTP/1.1 206 Partial Content], Accept-Ranges=[bytes], Cache-Control=[max-age=600], Connection=[keep-alive], Content-Length=[2812], Content-Range=[bytes 0-2811/2812], Content-Type=[application/javascript], Date=[Wed, 27 Jun 2018 02:15:36 GMT], ETag=["5b2258e0-afc"], Expires=[Wed, 27 Jun 2018 02:25:36 GMT], Last-Modified=[Thu, 14 Jun 2018 12:00:32 GMT], Server=[nginx/1.10.1], X-Android-Received-Millis=[1530065595970], X-Android-Response-Source=[NETWORK 206], X-Android-Selected-Transport=[http/1.1], X-Android-Sent-Millis=[1530065595906], X-Dscp-Value=[0], X-Via=[1.1 jfzhdx100:5 (Cdn Cache Server V2.0), 1.1 PSgddgdx4lv73:8 (Cdn Cache Server V2.0)]}
06-27 10:13:15.960 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadRunnable: the connection[-1] for -811684309, is connected range[0, -1) current offset[0] with code[206]
06-27 10:13:15.960 com.lzj.shanyi:filedownloader D/FileDownloader.FetchDataTask: start fetch(-1): range [0, -1), seek to[0]
06-27 10:13:15.960 com.lzj.shanyi:filedownloader I/FileDownloader.DownloadStatusCallback: inspectNeedCallbackToUser need callback to user
06-27 10:13:15.960 com.lzj.shanyi:filedownloader D/FileDownloader.FetchDataTask: require flushAndSync id[-811684309] index[-1] offset[2812], consume[1]
06-27 10:13:15.960 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadLaunchRunnable: the connection has been completed(-1): [0, -1)  2812
06-27 10:13:15.960 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: <---- -153206950 request header {Range=[bytes=0-0], User-Agent=[FileDownloader/1.7.4]}
06-27 10:13:16.010 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: ----> 2118892285 response header {null=[HTTP/1.1 412 Precondition Failed], Connection=[keep-alive], Content-Length=[189], Content-Type=[text/html], Date=[Wed, 27 Jun 2018 02:15:36 GMT], Server=[nginx/1.10.1], X-Android-Received-Millis=[1530065596019], X-Android-Response-Source=[NETWORK 412], X-Android-Selected-Transport=[http/1.1], X-Android-Sent-Millis=[1530065595906], X-Dscp-Value=[0], X-Via=[1.1 PSgdhzdx6dk57:6 (Cdn Cache Server V2.0), 1.1 PSgddgdx4lv73:1 (Cdn Cache Server V2.0)]}
06-27 10:13:16.010 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadRunnable: the connection[-1] for 2118892285, is connected range[0, -1) current offset[0] with code[412]

**Comment by Godsbox** [comment]
这是 直接把library下载后，不会出错的 初始化日志：
06-27 10:28:07.280 com.lzj.shanyi:filedownloader D/dalvikvm: Late-enabling CheckJNI
06-27 10:28:07.310 com.lzj.shanyi:filedownloader I/MultiDex: VM with version 1.6.0 does not have multidex support
06-27 10:28:07.310 com.lzj.shanyi:filedownloader I/MultiDex: Installing application
06-27 10:28:07.310 com.lzj.shanyi:filedownloader I/MultiDex: MultiDexExtractor.load(/data/app/com.lzj.shanyi-2.apk, false, )
06-27 10:28:07.310 com.lzj.shanyi:filedownloader I/MultiDex: Blocking on lock /data/data/com.lzj.shanyi/code_cache/secondary-dexes/MultiDex.lock
06-27 10:28:07.310 com.lzj.shanyi:filedownloader I/MultiDex: /data/data/com.lzj.shanyi/code_cache/secondary-dexes/MultiDex.lock locked
06-27 10:28:07.310 com.lzj.shanyi:filedownloader I/MultiDex: loading existing secondary dex files
06-27 10:28:07.310 com.lzj.shanyi:filedownloader I/MultiDex: load found 2 secondary dex files
06-27 10:28:07.310 com.lzj.shanyi:filedownloader I/MultiDex: install done
06-27 10:28:07.310 com.lzj.shanyi:filedownloader I/MultiDex: Installing application
06-27 10:28:07.310 com.lzj.shanyi:filedownloader I/MultiDex: install done
06-27 10:28:07.330 com.lzj.shanyi:filedownloader D/FileDownloader.FileDownloader: init Downloader with params: com.lzj.shanyi.DebugShanyi@4a7dda64 component: database[null], maxNetworkCount[4], outputStream[null], connection[com.liulishuo.filedownloader.connection.FileDownloadUrlConnection$Creator@4a7efea8], connectionCountAdapter[null]
06-27 10:28:07.370 com.lzj.shanyi:filedownloader D/dalvikvm: JIT code cache reset in 0 ms (0 bytes 1/0)
06-27 10:28:07.380 com.lzj.shanyi:filedownloader D/dalvikvm: GC_FOR_ALLOC freed 379K, 14% free 2896K/3340K, paused 4ms, total 6ms
06-27 10:28:07.430 com.lzj.shanyi:filedownloader I/dalvikvm: Failed resolving Lcom/taobao/accs/utl/h$a; interface 7947 'Lcom/taobao/orange/OrangeConfigListenerV1;'
06-27 10:28:07.430 com.lzj.shanyi:filedownloader W/dalvikvm: Link of class 'Lcom/taobao/accs/utl/h$a;' failed
06-27 10:28:07.430 com.lzj.shanyi:filedownloader E/dalvikvm: Could not find class 'com.taobao.accs.utl.h$a', referenced from method com.taobao.accs.internal.ACCSManagerImpl.bindApp
06-27 10:28:07.430 com.lzj.shanyi:filedownloader W/dalvikvm: VFY: unable to resolve new-instance 2729 (Lcom/taobao/accs/utl/h$a;) in Lcom/taobao/accs/internal/ACCSManagerImpl;
06-27 10:28:07.430 com.lzj.shanyi:filedownloader D/dalvikvm: VFY: replacing opcode 0x22 at 0x00f0
06-27 10:28:07.430 com.lzj.shanyi:filedownloader I/dalvikvm: Failed resolving Lcom/taobao/accs/utl/h$a; interface 7947 'Lcom/taobao/orange/OrangeConfigListenerV1;'
06-27 10:28:07.430 com.lzj.shanyi:filedownloader W/dalvikvm: Link of class 'Lcom/taobao/accs/utl/h$a;' failed
06-27 10:28:07.430 com.lzj.shanyi:filedownloader D/dalvikvm: DexOpt: unable to opt direct call 0x3cba at 0xf2 in Lcom/taobao/accs/internal/ACCSManagerImpl;.bindApp
06-27 10:28:07.450 com.lzj.shanyi:filedownloader D/dalvikvm: GC_FOR_ALLOC freed 407K, 14% free 3000K/3472K, paused 2ms, total 2ms
06-27 10:28:07.450 com.lzj.shanyi:filedownloader I/dalvikvm: Could not find method com.taobao.orange.OrangeConfig.getInstance, referenced from method com.taobao.accs.utl.h.a
06-27 10:28:07.450 com.lzj.shanyi:filedownloader W/dalvikvm: VFY: unable to resolve static method 45354: Lcom/taobao/orange/OrangeConfig;.getInstance ()Lcom/taobao/orange/OrangeConfig;
06-27 10:28:07.450 com.lzj.shanyi:filedownloader D/dalvikvm: VFY: replacing opcode 0x71 at 0x0004
06-27 10:28:07.450 com.lzj.shanyi:filedownloader W/dalvikvm: VFY: unable to find class referenced in signature (Lcom/taobao/orange/OrangeConfigListenerV1;)
06-27 10:28:07.450 com.lzj.shanyi:filedownloader I/dalvikvm: Could not find method com.taobao.orange.OrangeConfig.getInstance, referenced from method com.taobao.accs.utl.h.a
06-27 10:28:07.450 com.lzj.shanyi:filedownloader W/dalvikvm: VFY: unable to resolve static method 45354: Lcom/taobao/orange/OrangeConfig;.getInstance ()Lcom/taobao/orange/OrangeConfig;
06-27 10:28:07.450 com.lzj.shanyi:filedownloader D/dalvikvm: VFY: replacing opcode 0x71 at 0x0004
06-27 10:28:07.450 com.lzj.shanyi:filedownloader D/dalvikvm: Trying to load lib /data/app-lib/com.lzj.shanyi-2/libtnet-3.1.11.so 0x94fb4680
06-27 10:28:07.450 com.lzj.shanyi:filedownloader D/FileCheckUtils: st.getAvailableBlocks()=6312141,st.getAvailableBlocks() * blockSize=25854529536
06-27 10:28:07.560 com.lzj.shanyi:filedownloader D/dalvikvm: Added shared lib /data/app-lib/com.lzj.shanyi-2/libtnet-3.1.11.so 0x94fb4680
06-27 10:28:07.600 com.lzj.shanyi:filedownloader D/dalvikvm: GC_FOR_ALLOC freed 306K, 15% free 3035K/3564K, paused 3ms, total 3ms
06-27 10:28:07.630 com.lzj.shanyi:filedownloader I/dalvikvm: Could not find method android.content.Context.checkSelfPermission, referenced from method com.tencent.smtt.utils.k.a
06-27 10:28:07.630 com.lzj.shanyi:filedownloader W/dalvikvm: VFY: unable to resolve virtual method 543: Landroid/content/Context;.checkSelfPermission (Ljava/lang/String;)I
06-27 10:28:07.630 com.lzj.shanyi:filedownloader D/dalvikvm: VFY: replacing opcode 0x6e at 0x0012
06-27 10:28:07.670 com.lzj.shanyi:filedownloader D/dalvikvm: GC_FOR_ALLOC freed 384K, 13% free 3155K/3608K, paused 2ms, total 4ms
06-27 10:28:07.670 com.lzj.shanyi:filedownloader I/FileDownloader.FileDownloadProperties: init properties 5
                                                                                           load properties: http.lenient=FALSE; process.non-separate=FALSE; download.min-progress-step=65536; download.min-progress-time=2000; download.max-network-thread-count=3
06-27 10:28:07.680 com.lzj.shanyi:filedownloader D/FileDownloader.FileDownloadUtils: can't continue 1397192529 file not suit, exists[FALSE], directory[FALSE]
06-27 10:28:07.680 com.lzj.shanyi:filedownloader D/FileDownloader.FileDownloadDatabase: refreshed data count: 1 , delete data count: 0, reset id count: 0. consume 8
06-27 10:28:07.680 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadMgrInitialParams: initial FileDownloader manager with the customize maxNetworkThreadCount: 4

**Comment by Godsbox** [comment]
这个是 直接引用 的初始化日志：（即会报错的日志）
06-27 10:47:26.920 ? D/dalvikvm: Late-enabling CheckJNI
06-27 10:47:26.990 ? I/dalvikvm: ignoring registerObject request in thread=1
06-27 10:47:26.990 ? I/dalvikvm: ignoring registerObject request in thread=1
06-27 10:47:27.000 ? I/MultiDex: VM with version 1.6.0 does not have multidex support
06-27 10:47:27.000 ? I/MultiDex: Installing application
06-27 10:47:27.000 ? I/MultiDex: MultiDexExtractor.load(/data/app/com.lzj.shanyi-1.apk, false, )
06-27 10:47:27.000 ? I/MultiDex: Blocking on lock /data/data/com.lzj.shanyi/code_cache/secondary-dexes/MultiDex.lock
06-27 10:47:27.000 ? I/MultiDex: /data/data/com.lzj.shanyi/code_cache/secondary-dexes/MultiDex.lock locked
06-27 10:47:27.010 ? I/MultiDex: loading existing secondary dex files
06-27 10:47:27.010 ? I/MultiDex: load found 2 secondary dex files
06-27 10:47:27.010 ? I/MultiDex: install done
06-27 10:47:27.010 ? I/MultiDex: Installing application
06-27 10:47:27.010 ? I/MultiDex: install done
06-27 10:47:27.020 ? D/FileDownloader.FileDownloader: init Downloader with params: com.lzj.shanyi.DebugShanyi@4a794ce0 component: database[null], maxNetworkCount[4], outputStream[null], connection[com.liulishuo.filedownloader.connection.FileDownloadUrlConnection$Creator@4a7a7184], connectionCountAdapter[null]
06-27 10:47:27.090 ? D/dalvikvm: JIT code cache reset in 0 ms (0 bytes 1/0)
06-27 10:47:27.090 ? D/dalvikvm: GC_CONCURRENT freed 289K, 11% free 2888K/3244K, paused 2ms+5ms, total 9ms
06-27 10:47:27.290 ? D/dalvikvm: GC_CONCURRENT freed 306K, 12% free 2966K/3340K, paused 2ms+1ms, total 5ms
06-27 10:47:27.320 ? I/dalvikvm: Failed resolving Lcom/taobao/accs/utl/h$a; interface 7773 'Lcom/taobao/orange/OrangeConfigListenerV1;'
06-27 10:47:27.320 ? W/dalvikvm: Link of class 'Lcom/taobao/accs/utl/h$a;' failed
06-27 10:47:27.320 ? E/dalvikvm: Could not find class 'com.taobao.accs.utl.h$a', referenced from method com.taobao.accs.internal.ACCSManagerImpl.bindApp
06-27 10:47:27.320 ? W/dalvikvm: VFY: unable to resolve new-instance 2729 (Lcom/taobao/accs/utl/h$a;) in Lcom/taobao/accs/internal/ACCSManagerImpl;
06-27 10:47:27.320 ? D/dalvikvm: VFY: replacing opcode 0x22 at 0x00f0
06-27 10:47:27.330 ? I/dalvikvm: Failed resolving Lcom/taobao/accs/utl/h$a; interface 7773 'Lcom/taobao/orange/OrangeConfigListenerV1;'
06-27 10:47:27.330 ? W/dalvikvm: Link of class 'Lcom/taobao/accs/utl/h$a;' failed
06-27 10:47:27.330 ? D/dalvikvm: DexOpt: unable to opt direct call 0x3cbc at 0xf2 in Lcom/taobao/accs/internal/ACCSManagerImpl;.bindApp
06-27 10:47:27.370 ? I/dalvikvm: Could not find method com.taobao.orange.OrangeConfig.getInstance, referenced from method com.taobao.accs.utl.h.a
06-27 10:47:27.370 ? W/dalvikvm: VFY: unable to resolve static method 43051: Lcom/taobao/orange/OrangeConfig;.getInstance ()Lcom/taobao/orange/OrangeConfig;
06-27 10:47:27.370 ? D/dalvikvm: VFY: replacing opcode 0x71 at 0x0004
06-27 10:47:27.370 ? W/dalvikvm: VFY: unable to find class referenced in signature (Lcom/taobao/orange/OrangeConfigListenerV1;)
06-27 10:47:27.370 ? I/dalvikvm: Could not find method com.taobao.orange.OrangeConfig.getInstance, referenced from method com.taobao.accs.utl.h.a
06-27 10:47:27.370 ? W/dalvikvm: VFY: unable to resolve static method 43051: Lcom/taobao/orange/OrangeConfig;.getInstance ()Lcom/taobao/orange/OrangeConfig;
06-27 10:47:27.370 ? D/dalvikvm: VFY: replacing opcode 0x71 at 0x0004
06-27 10:47:27.380 ? D/dalvikvm: Trying to load lib /data/app-lib/com.lzj.shanyi-1/libtnet-3.1.11.so 0x94f22b78
06-27 10:47:27.450 ? D/FileCheckUtils: st.getAvailableBlocks()=6312090,st.getAvailableBlocks() * blockSize=25854320640
06-27 10:47:27.670 ? D/dalvikvm: Added shared lib /data/app-lib/com.lzj.shanyi-1/libtnet-3.1.11.so 0x94f22b78
06-27 10:47:27.750 ? D/dalvikvm: GC_CONCURRENT freed 301K, 11% free 3055K/3432K, paused 0ms+0ms, total 7ms
06-27 10:47:27.860 com.lzj.shanyi:filedownloader I/dalvikvm: Could not find method android.content.Context.checkSelfPermission, referenced from method com.tencent.smtt.utils.k.a
06-27 10:47:27.860 com.lzj.shanyi:filedownloader W/dalvikvm: VFY: unable to resolve virtual method 512: Landroid/content/Context;.checkSelfPermission (Ljava/lang/String;)I
06-27 10:47:27.860 com.lzj.shanyi:filedownloader D/dalvikvm: VFY: replacing opcode 0x6e at 0x0012
06-27 10:47:28.000 com.lzj.shanyi:filedownloader D/dalvikvm: GC_FOR_ALLOC freed 415K, 14% free 3144K/3624K, paused 17ms, total 22ms
06-27 10:47:28.050 com.lzj.shanyi:filedownloader I/FileDownloader.FileDownloadProperties: init properties 1
                                                                                           load properties: http.lenient=FALSE; process.non-separate=FALSE; download.min-progress-step=65536; download.min-progress-time=2000; download.max-network-thread-count=3; file.non-pre-allocation=FALSE; broadcast.completed=FALSE; download.trial-connection-head-method=FALSE
06-27 10:47:28.090 com.lzj.shanyi:filedownloader D/FileDownloader.FileDownloadUtils: can't continue 1397192529 file not suit, exists[FALSE], directory[FALSE]
06-27 10:47:28.100 com.lzj.shanyi:filedownloader D/FileDownloader.FileDownloadDatabase: refreshed data count: 1 , delete data count: 0, reset id count: 0. consume 19
06-27 10:47:28.100 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadMgrInitialParams: initial FileDownloader manager with the customize maxNetworkThreadCount: 4
06-27 10:47:32.380 com.lzj.shanyi:filedownloader W/AppMonitor: load ut_c_api.so failed

**Comment by Godsbox** [comment]
现在这个问题已经解决了， 是服务端清理了一下 cdn节点缓存，但是我想知道为什么 这两个情况下 一种会出错一种不会呢？？？？

而且前面 好像是gzip压缩部分 也导致412，服务端现在关闭gzip压缩， 但是这样带宽会增加很多？ 这是为什么呢？

**Comment by humanheima** [comment]
我想问一下，这个问题和服务端有关吗？

**Comment by Godsbox** [comment]
服务端的问题的 新版的下载库 使用了 Etag， 服务端和cdn的传递过程 有一些问题 我这里是 cdn取文件 没有使用 rang

**Comment by humanheima** [comment]
我想问一下，这个问题我们可以通过更换FileDownloader的版本解决吗？或者说我们使用FileDownloader能否解决这个问题，还是说需要服务端做改动

**Comment by rantianhua** [comment]
@humanheima 这个的本质问题是处在服务端没有正确支持 range header ，所以 FileDownloader 会认为这是一个错误，需要服务端进行纠正。
