### ISSUE TITLE
https连接无法下载, 如何添加https的自签名证书?

### ISSUE THREAD

**Issue by zuohp** [lingochamp/FileDownloader#1068]
错误日志: filedownload: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found

项目比较老,使用的是HttpClient请求, 但是最近升级到自签名证书的https后, 发现不能下载, 请教一下如何添加自签名证书呢

**Comment by rantianhua** [comment]
请参考 #437
