### ISSUE TITLE
blockComplete 在主线程回调

### ISSUE THREAD

**Issue by yangkai3** [lingochamp/FileDownloader#1069]
#### Before Issue

1. Please search on the [Issues](https://github.com/lingochamp/FileDownloader/issues)
2. Please search on the [wiki](https://github.com/lingochamp/FileDownloader/wiki)
3. Please set `FileDownloadLog.NEED_LOG=true` and review the Logcat output from main process and `:filedownloader` process ( pay attention to Warn and Error level logcat)

#### Issue

1. What problem do you get?
2. Which version of FileDownloader are you using when you produce such problem?
3. How to reproduce such problem?
4. Do you set `FileDownloadLog.NEED_LOG=true`?
5. Could you please reproduce this problem and provide all main process and `:filedownloader` process logcat 
6. Can you fix it by yourself and request PR, if not, what's problem do you get when you try to fix it

>P.S. If you don't know how to get `:filedownloader` process, it's recommended to using `pidcat` to just filter all your application logcat, or define `process.non-separate=true` on [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)

---

blockComplete 按照注释应该是在非UI线程回调，但是在使用中发现并不是这样的
打log看了下，原因如下：
1. FileDownloadList 在文件下载完成后，remove方法会回调，switch 走FileDownloadStatus.completed 分支，然后在 FileDownloadMessenger 中的parcelQueue队列后面加入BlockCompleteMessageImpl
2. 但是这时候，parcelQueue可能不为空，里面还有没处理完的 ProgressMessageSnapshot
3. FileDownloadMessageStation 的 requestEnqueue 判断是否走blockCompletedPool 的逻辑是parcelQueue头，是否是 BlockCompleteMessageImpl。但是这时候 parcelQueue 头是还没处理完的 ProgressMessageSnapshot，BlockCompleteMessageImpl其实在队列尾部。这样就造成了这个不会走blockCompletedPool，而是走UI线程。
4. 如上所述，这个设计本身就隐形的要求 BlockCompleteMessageImpl 入队列时，队列为空？如果不为空就不走UI线程？ 为什么不能在 BlockCompleteMessageImpl 入队列时，清空一下队列？

**Comment by rantianhua** [comment]
在你描述的第三点里：
> FileDownloadMessageStation 的 requestEnqueue 判断是否走blockCompletedPool 的逻辑是parcelQueue头，是否是 BlockCompleteMessageImpl。但是这时候 parcelQueue 头是还没处理完的 ProgressMessageSnapshot，BlockCompleteMessageImpl其实在队列尾部。这样就造成了这个不会走blockCompletedPool，而是走UI线程。

FileDownloadMessageStation 的作用是按照队列的顺序处理 task 的回调，即每一次处理队列头上的回调。所以按照你说的，假如这个时候拿到头上的 message 是 progress ，那么下面的回调是回调 progess ，而不是 blockComplete ，注意在 `FileDownloadMessenger#handOverMessage` 方法里是用 `poll` 方法，在 `FileDownloadMessenger#isBlockingCompleted` 方法里面用的是 `peek` 方法。

所以想问一下，你说你通过打 log 看到 blockComplete 没有在非 UI 线程回调，这个能更具体一点吗？你是在哪些地方打了 log ？具体输出是怎样？

**Comment by salmonocean** [comment]
blockComplete 的消息发出来的时候，如果没有在parcelQueue 队列的头（也就是队列里还有其他消息），FileDownloadMessageStation.requestEnqueue 中，就不会执行blockCompletedPool.execute， 
messenger.handoverMessage 不会在子线程执行
而错过了这个时机，之后parcelQueue 队列中的消息处理函数，也就是messenger.handoverMessage 全都在主线程调用了
从而blockComplete 的回调也发生在主线程了

在一个性能比较差的手机上，很容易就能复现这个问题。 @rantianhua

**Comment by yangkai3** [comment]
@salmonocean 是的，只要消息处理速度赶不上塞的进度，就会有这个问题，性能差的手机比较容易复现，或者在demo里面，处理progress的函数里面sleep 1s也可以复现。
另外，这样的设计模式，至少理论上是存在这个问题的。我自己暂时得解决办法是，blockComplete消息进来时候，看消息队列里面如果只有 progress 消息，就清空消息队列，这样就可以通过后面的判断。当然坏处很明显，如果UI在做进度动画，可能会卡一下（卡在blockComplete的回调），然后从80%跳到100%（举例）。但这样至少能保证blockComplete方法一定不会在UI线程里回调。
另外，这个问题出现在性能差的手机上，影响是blockComplete回调在UI线程，加剧了UI的卡顿，略蛋疼。。。。

**Comment by rantianhua** [comment]
其实按照现在的设计，即使在性能差的手机上，出现的情况也应该是消息处理的慢，但不会把 blockComplete 消息当做别的消失处理，因为队列是 FIFO 的，永远只在头部取消息回调，即进来的消息都在尾部，不会影响它前面的消息，所以顺序不会乱。当然了，我会按照你们说的多测试测试，然后再给一个确切的结论。

**Comment by yangkai3** [comment]
现在的设计确实可以保证顺序到达、执行，这个没问题。我比较care的是blockComplete消息在主进程回调，这个太卡UI，毕竟我在里面是做unzip的，很耗时。
感谢

**Comment by rantianhua** [comment]
@yangkai3 其实我说的按照顺序执行就意味着会保证 blockComplete 会在异步线程回调。因为在进行回调前都会检查消息是不是 blockComplete ，如果是，都会扔到异步去处理的。

**Comment by BCsl** [comment]
同样遇到在主线程回调的情况，使用的版本是 1.7.4

**Comment by rantianhua** [comment]
@yangkai3 @salmonocean 已发布 1.7.7 snapshot 并修复该问题，请先试用 1.7.7-SNAPSHOT 版本验证一下。
