### ISSUE TITLE
支持Android8.0后台下载么？

### ISSUE THREAD

**Issue by cjqq354139968** [lingochamp/FileDownloader#1070]
#### Before Issue

1. Please search on the [Issues](https://github.com/lingochamp/FileDownloader/issues)
2. Please search on the [wiki](https://github.com/lingochamp/FileDownloader/wiki)
3. Please set `FileDownloadLog.NEED_LOG=true` and review the Logcat output from main process and `:filedownloader` process ( pay attention to Warn and Error level logcat)

#### Issue

1. What problem do you get?
2. Which version of FileDownloader are you using when you produce such problem?
3. How to reproduce such problem?
4. Do you set `FileDownloadLog.NEED_LOG=true`?
5. Could you please reproduce this problem and provide all main process and `:filedownloader` process logcat 
6. Can you fix it by yourself and request PR, if not, what's problem do you get when you try to fix it

>P.S. If you don't know how to get `:filedownloader` process, it's recommended to using `pidcat` to just filter all your application logcat, or define `process.non-separate=true` on [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)

---

请在Issue前认真的跟进上面提到的建议，这样将可以极大的加快你遇到问题的处理。

**Comment by rantianhua** [comment]
请描述得具体一点，你指的是退到后台还能继续下载还是说在 Service 中进行下载？

**Comment by cjqq354139968** [comment]
Service中下载,或者是程序进入后台,还能继续下载.

**Comment by rantianhua** [comment]
这个是支持的。本身 FileDownloader 的下载就是在一个 Service 中进行，你还可以将这个 Service 配置在独立的进程。
