### ISSUE TITLE
从设置有防盗链的网站下载文件，如何添加Referer

### ISSUE THREAD

**Issue by DingZugeng** [lingochamp/FileDownloader#1073]
有一个问题，就是我有一些文件是存放在阿里云的OSS对象存储内，并开启了防盗链设置，Referer设置为“http://www.sample.com”，在FileDownloader库中，我应该如何添加此参数呢？
像OKhttp里，可以直接在Request里用addHeader()方法来添加，但不知道这个库怎么处理。

**Comment by rantianhua** [comment]
`BaseDownloadTask#addHeader`
