### ISSUE TITLE
Chunked文件可以下载吗

### ISSUE THREAD

**Issue by Godsbox** [lingochamp/FileDownloader#1074]
我的试探链接获取到了 弱值的 Etag ，并且这个文件是Transfer-Encoding: chunked，这种情况下载库还是使用了 if match来进行下载，我查看源码没有对这种样式判断，只是对 length为-1的时候定义为了chunked，并且直接输出异常， 下载库不支持 chunked模式的下载的吗？

**Comment by rantianhua** [comment]
FileDownloader 是支持的。

**Comment by rantianhua** [comment]
请提供下 FileDownloader 的具体日志
