### ISSUE TITLE
下载前获取状态相关问题

### ISSUE THREAD

**Issue by nanchen2251** [lingochamp/FileDownloader#1077]
作者你好，目前我们的需求实现有以下困惑。
- 下拉刷新后需要显示之前暂停下载的进度，以及已下载的状态；但目前我发现假设我一个文件已经下载完成了，此时下拉刷新，正确情况是该项显示已完成状态，但我目前由于无法去获取该项是否已经下载，不知道如何从 db 里面拿出这个之前下载的数据，只有再次 start 后，才会直接回调 onComplete.所以很困惑；
在下反复查看 wiki 后没有得出具体定论，然后下定决心从你的线程池，db，以及各种回调看了一整天，很无奈，由于能力有限，被你的各种回调和 Message发送搞得完全晕乎状态。

其实我的需求很简单，就是假设我现在下载后这个状态肯定存在数据库了。当我下拉刷新继续去获取接口数据的时候，我需要从数据库拿出之前的状态，然后更新到model后再更新 Adapter。

其次，我们希望是一次只下载一个任务，假设我点击了Item1，Item1 进入到下载状态，还未完成，我们就点击 Item2，此时应该是Item2 进入下载状态，Item1暂停，待 Item2 下载完成后再去进行 Item1 的下载。我发现现在 Task 提供的 API 中，似乎只有设置线程数量的方法，而没有设置下载数目的方法；

恳请维护者的帮助，Thx

**Comment by rantianhua** [comment]
FileDownloader 内部的数据库是功能性组件，目的是断点续传，所以当任务下载完成后，会主动删除数据库里面的数据。从你的描述来看，你需要的是数据库相关的业务需求，所以你需要保存数据库的数据。从 FileDownloader 的角度，它是一个下载引擎，是不会干预你的业务的。

不过，FileDownloader 本身的数据库组件是可以自定义的，详见：https://github.com/lingochamp/FileDownloader#open-customize-component 。所以你可以自定义自己的数据库组件，这样按照你自己的业务需求操作数据库就好。

**Comment by rantianhua** [comment]
关于一次只下载一个任务，这个其实可以很方便的实现，即在开始一个 task 前：
```
// 简单直接，停止了所有的下载任务
// FileDownloader.pauseAll();
// 只停止绑定了该 listener 的所有任务，此时要求你的 item1 , item2 ... itemN 都绑定了同一个 listener
// FileDownloader.pause(listener);
// 停止指定的任务
FileDownloader.pause(item1TaskId);
// 开始下载 item2
task2.start();
```

**Comment by nanchen2251** [comment]
我看你们的RxDownload 已经具备了直接获取 info 的功能了？而且也可以直接获取是否下载了的状态通过 StatusUti.getStatus

**Comment by rantianhua** [comment]
整个结构上 RxDownload 做了很多优化提升，所以相较而言， RxDownload 能更好满足你的需求。

**Comment by nanchen2251** [comment]
但 RxDownload 的 Status 获取非常奇葩，两个暂停的任务，一个获取出来是  IDLE , 一个获取出来是 COMPLETED

**Comment by rantianhua** [comment]
@nanchen2251 那建议这个问题在 OkDownload 的 issue 里反馈一下。把信息给全。尤其是日志。

**Comment by rantianhua** [comment]
这个就先 close 了。

**Comment by rantianhua** [comment]
话说 RxDownload 是啥？
