### ISSUE TITLE
pause掉某个任务之后，我怎么resume这个任务

### ISSUE THREAD

**Issue by niejunhong** [lingochamp/FileDownloader#108]

**Comment by Jacksgong** [comment]
参看这个wiki: https://github.com/lingochamp/FileDownloader/wiki/Pause-or-Stop

你还是以一个新任务的方式启动，会自动断点续传。

**Comment by niejunhong** [comment]
就是与pasuse(id)对应的 是否应有个resume(id)

**Comment by nukc** [comment]
@niejunhong `···.start()`对应`pasuse(id)`，pasuse后，如果想要resume，再次start就可以了。

**Comment by lefu999** [comment]
@Jacksgong  请问您有QQ吗T.T

**Comment by Jacksgong** [comment]
@lenage 直接来这里吧: https://gitter.im/lingochamp/FileDownloader

**Comment by niejunhong** [comment]
@nukc 恩。我其实想表达的是在FileDownloader这一层。start是在task这一层，pause(id)提供在FileDownloader这一层，如果不想把downloadTask这个数据接口暴露出去的话就只能重新create一个task，底层根据参数去判断是否需要断点续传。其实只是个接口设计的疑惑吧

**Comment by Jacksgong** [comment]
@niejunhong 如果我理解的没有错误的话，你想表达的是， FileDownloader 提供了 `pause(id)` ，也需要提供 `start(id)` 以对称。

有一下几个显而易见的原因，不这么做:

- 所有的 start 与 pause 都是 task 提供的功能。你看下 `BaseDownloadTask`。
- FileDownloader 提供的是上层封装。
- 你可以自己存储创建好的 Task，在重新使用的时候调用 `BaseDownloadTask#reuse()` 即可。
- 也并没有必要，因为对于外界而言只需要足够简单的逻辑进行启动，不需要mark是否去resume。如果提供这样，上层反而会更加复杂，需要去维护一个是否去resume的状态，来切换启动方式是resume or start。如果你的下载业务足够复杂，建议上层业务层自己为需求维护一套自己的数据结构（参考: `TasksManagerDemoActivity` ）
- 为了防止内存泄漏，以及不必要的内存暂用，因此在你 `pause` 以后内部就释放了该任务以及其对象，因此，因此想要在 `FileDownloader` 直接提供一个 `start(id)` 类似的接口，归根结底内部也是需要重新创建一个（如果说和进程生命周期绑定，显然不符合预期，因为进程重启以后依然需要重新创建），也就是现在的 `FileDownloader#create()` 内部封装一层来做，那么这里又会存在几个问题

  - 内部数据现有的存储的数据是为了断点续传做到了足够的轻量，并且自动维护; 如果需要如此，内部就需要重新维护一套数据库，这套数据库存储的是 任务对象(不仅仅是断点续传的数据，数据就如: `id`、 `isForceReDownload`、`autoRetryTimes`、`callbackProgressTimes`、甚至是用户主动添加的整个 `header` 等等)(可能可以考虑直接序列化存储吧，不过感觉挺恶心)。
 - 为了符合预期这块存储对象的数据需要无限膨胀。
 - 出现相同id的任务，内部覆盖是否又会符合用户预期等。

**Comment by Jacksgong** [comment]
@niejunhong 希望能够解决你的困惑。

**Comment by Jacksgong** [comment]
其实归根结底，应该还是我的文档中没有写的很清楚，回头我更新下文档。
