### ISSUE TITLE
how we can get active tasks (pending, running,....)when kill app and reopen app ?

### ISSUE THREAD

**Issue by 3r-ulduz** [lingochamp/FileDownloader#1087]
#### Before Issue

1. Please search on the [Issues](https://github.com/lingochamp/FileDownloader/issues)
2. Please search on the [wiki](https://github.com/lingochamp/FileDownloader/wiki)
3. Please set `FileDownloadLog.NEED_LOG=true` and review the Logcat output from main process and `:filedownloader` process ( pay attention to Warn and Error level logcat)

#### Issue

1. What problem do you get?
2. Which version of FileDownloader are you using when you produce such problem?
3. How to reproduce such problem?
4. Do you set `FileDownloadLog.NEED_LOG=true`?
5. Could you please reproduce this problem and provide all main process and `:filedownloader` process logcat 
6. Can you fix it by yourself and request PR, if not, what's problem do you get when you try to fix it

>P.S. If you don't know how to get `:filedownloader` process, it's recommended to using `pidcat` to just filter all your application logcat, or define `process.non-separate=true` on [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)

---

请在Issue前认真的跟进上面提到的建议，这样将可以极大的加快你遇到问题的处理。

**Comment by 3r-ulduz** [comment]
i add libray as package in my app and dont use gradle but library work 
i created a hashmap<int,basedownloadtask> in FileDownloader class when i kill app and reopen the hashmap clear() automaticlly  download is progress in fourground but hashmap clear

`@SuppressWarnings("WeakerAccess")
public class FileDownloader {
    public static HashMap<Integer, BaseDownloadTask> taskSparseArray = new HashMap<>();
`

**Comment by rantianhua** [comment]
HashMap saves data in memory, after reopen the app, all memory data is cleared, so you cannot use memory to persist data. 

You should use database to save tasks you want to recover after reopen app.

By the way, why do you need to get 'active' task? `FileDownload` support downloading from breakpoint, you just need to start a new task with the same url and target path.

**Comment by 3r-ulduz** [comment]
tnx for reply 
i have database and i can recover tasks and dont problam with recover them my problam is update view when kill app and reopen it beacuse hashmap clear and  i cant update view 

in TaskmanagerDemo you update view with taskSparseArray and saves tasks this way correct when app dont kill but when app kill this array also clear .

i set to filedownloader work in forground with FileDownloader.getImpl().startForeground(1992, notification);  code 
Actually when i kill app download continue in forground but i want when i reopen app show active tasks for this reason i try to find save active tasks 

In addition i save hashmap in FileDownloaderService class  but clear when app kill but download continue

**Comment by rantianhua** [comment]
The simplest way is starting download tasks again and update view through `FileDownloadListener`.
