### ISSUE TITLE
3G/4G及Wifi網路切換時，如何自動停止/重啟任務

### ISSUE THREAD

**Issue by ArthurPai** [lingochamp/FileDownloader#109]
我目前遇到一個功能，需要讓使用者可以切換是否只允許Wifi時可以下載。

如果 **“只允許Wifi時可以下載的話”** 的功能啟動時，
當網路轉換成3G/4G時，就要自動停止下載，
而當網路回復到Wifi時就要自動開始下載先前被自動停止的Task。

請問這個功能要如何達成？

**Comment by Jacksgong** [comment]
恩。你监听网络状态变化（系统广播）:

1. 发现网络变为 移动网络的时候 调用 `FileDownloader.getImpl().pause(downloadId)` 或者 `FileDownloader.getImpl().pauseAll()`。
2. 发现网络恢复为 Wifi网络的时候 和启动一个新任务一样启动之前的任务，内部会自动断点续传的。

**Comment by ArthurPai** [comment]
主要是當App進入背景後，App這邊就無法監聽網路狀態變化。
是否需要另外寫一個Service去控制FileDownloader?

**Comment by Jacksgong** [comment]
广播监听器只要注册着并且没有绑定某组件的生命周期，只要进程还在，都可以监听的到。

**Comment by ArthurPai** [comment]
瞭解。
不好意思，Android新手，問了笨問題。

謝謝～

**Comment by Jacksgong** [comment]
👍 屌屌地。

**Comment by AlawnXu** [comment]
监听网络变化，执行leDownloader.getImpl().pauseAll()之后会发生这个crash。请问是什么原因导致啊！~
java.lang.IllegalStateException
Fatal-Exception: You can't bind the FileDownloadService in :filedownloader process. It's the invalid operation, and is likely to cause unexpected problems. Maybe you want to use non-separate process mode for FileDownloader, More detail about non-separate mode, please move to wiki manually: https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties

**Comment by Jacksgong** [comment]
https://github.com/lingochamp/FileDownloader/issues/128#issuecomment-217195174
