### ISSUE TITLE
一直返回-1

### ISSUE THREAD

**Issue by dreamerleeli** [lingochamp/FileDownloader#1092]
08-14 16:32:40.931 3718-5313/com.rj.syslearning W/FileDownloader.DownloadServiceNotConnectedHelper: request clear all tasks data in the database, but the download service isn't connected yet.
    You can use FileDownloader#isServiceConnected() to check whether the service has been connected, 
    besides you can use following functions easier to control your code invoke after the service has been connected: 
    1. FileDownloader#bindService(Runnable)
    2. FileDownloader#insureServiceBind()
    3. FileDownloader#insureServiceBindAsync()
08-14 16:32:45.956 3718-6364/com.rj.syslearning W/FileDownloader.DownloadTaskHunter: warn, but no mListener to receive, switch to pending -1201824152 -1
08-14 16:32:47.559 3718-6364/com.rj.syslearning W/FileDownloader.DownloadTaskHunter: warn, but no mListener to receive, switch to pending -1201824152 -1
08-14 16:32:50.669 3718-6362/com.rj.syslearning W/FileDownloader.DownloadTaskHunter: warn, but no mListener to receive, switch to pending -1201824152 -1

**Comment by rantianhua** [comment]
日志已经说的很清楚了，你需要在使用 FileDownloader#bindService() 方法启动下载服务
