### ISSUE TITLE
 # FileDownloader-EventPool1(4223)  java.lang.IllegalStateException  This task is dirty to restart, If you want to reuse this task, please invoke #reuse method manually and retry to restart again.com.liulishuo.filedownloader.e@3cafb024

### ISSUE THREAD

**Issue by bing2006200** [lingochamp/FileDownloader#1095]
#### Before Issue

1. Please search on the [Issues](https://github.com/lingochamp/FileDownloader/issues)
2. Please search on the [wiki](https://github.com/lingochamp/FileDownloader/wiki)
3. Please set `FileDownloadLog.NEED_LOG=true` and review the Logcat output from main process and `:filedownloader` process ( pay attention to Warn and Error level logcat)

#### Issue

1 com.liulishuo.filedownloader.d.ae(SourceFile:321)
--
2 com.liulishuo.filedownloader.d.Y(SourceFile:581)
3 com.liulishuo.filedownloader.ad.a(SourceFile:65)
4 com.liulishuo.filedownloader.f.a(SourceFile:43)
5 com.liulishuo.filedownloader.d.a.a(SourceFile:131)
6 com.liulishuo.filedownloader.d.a.a(SourceFile:105)
7 com.liulishuo.filedownloader.d.a$1.run(SourceFile:119)
8 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
9 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10 java.lang.Thread.run(Thread.java:818)

1. What problem do you get?
2. Which version of FileDownloader are you using when you produce such problem?
3. How to reproduce such problem?
4. Do you set `FileDownloadLog.NEED_LOG=true`?
5. Could you please reproduce this problem and provide all main process and `:filedownloader` process logcat 
6. Can you fix it by yourself and request PR, if not, what's problem do you get when you try to fix it

>P.S. If you don't know how to get `:filedownloader` process, it's recommended to using `pidcat` to just filter all your application logcat, or define `process.non-separate=true` on [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)

---

请在Issue前认真的跟进上面提到的建议，这样将可以极大的加快你遇到问题的处理。

**Comment by rantianhua** [comment]
The error message is very clear. You need to invoke `reuse` before you restart the previous task.
