### ISSUE TITLE
The foreground Services  keeps running even if there is no download task

### ISSUE THREAD

**Issue by BCsl** [lingochamp/FileDownloader#1096]
### 1. What problem do you get?
Since #1078 and #1082  change the download service  to foreground  service on Android O , these foreground Services  keeps running even if there is no download task （The notification title: "FileDownloader"  content: "FileDownloader is running."）. This will make my users very confused. My suggestion is to add a button to force cancel the foreground in the notification bar or cancel the foreground service after downloaded all the tasks.

### 2. Which version of FileDownloader are you using when you produce such problem?
1.7.5

**Comment by virengujariya** [comment]
This is happening with me too. FileDownloader version 1.7.5

**Comment by rantianhua** [comment]
I will handle this issue in 1.7.6. Please be patient, thanks.

**Comment by Allyns** [comment]
When will the 1.7.6 version be released?

**Comment by rantianhua** [comment]
@BCsl @virengujariya @Allyns 1.7.6-SNAPSHOT is published, please try it! Look forward to your guys feedback!

**Comment by shembil** [comment]
Thanks guys. I try 1.7.6-SNAPSHOT and its wrok successfully.

**Comment by jhwsx** [comment]
Yes，I have been confused with this problem，too.

**Comment by rantianhua** [comment]
> Yes，I have been confused with this problem，too.

Can 1.7.6-SNAPSHOT solve your problem?

**Comment by Allyns** [comment]
ERROR: Failed to resolve: com.liulishuo.filedownloader:library:1.7.6
Show in Project Structure dialog
Affected Modules: app

**Comment by rantianhua** [comment]
Please use 1.7.6-SNAPSHOT, 1.7.6 has not been released.

**Comment by Allyns** [comment]
> Please use 1.7.6-SNAPSHOT, 1.7.6 has not been released.

ok
