### ISSUE TITLE
下载大小一直不能到达文件总大小

### ISSUE THREAD

**Issue by sdgSnow** [lingochamp/FileDownloader#1099]
#### Before Issue

在处理进度的时候，拿progress回调的值，下载的大小在最后下载成功的那一刻，总到达不了文件总大小
因此进度总是小于100%

以下是我打印的log

08-22 15:38:05.384 20931-20931/com.weidu.dimenoproject I/test_download: soFarBytes = 300770,totalBytes = 319586
    progress = 94.11
08-22 15:38:05.610 20931-20931/com.weidu.dimenoproject I/test_download: soFarBytes = 306288,totalBytes = 319586
    progress = 95.84
08-22 15:38:09.246 20931-20931/com.weidu.dimenoproject I/test_download: soFarBytes = 310384,totalBytes = 319586
    progress = 97.12
08-22 15:38:09.294 20931-21699/com.weidu.dimenoproject I/test_download: blockComplete
08-22 15:38:09.305 20931-20931/com.weidu.dimenoproject I/test_download: completed

到了最后一刻就直接走成功了，然后显现不出来100%

**Comment by rantianhua** [comment]
是的，progress 是根据缓存大小、时间间隔进行回调的，当最后完成的时候，是直接毁掉了 complete ，所以你可以在 complete 回调里把结果更新为 100% 即可。
