### ISSUE TITLE
How can I set my custom headers?

### ISSUE THREAD

**Issue by HamedGh** [lingochamp/FileDownloader#11]
I found that FileDownloadRunnable class have a addHeader() method, but I can't figure out how to use it!
could give me an example?

**Comment by Jacksgong** [comment]
Sorry, FileDownloader not supported this interface. it will support in next version.

**Comment by Jacksgong** [comment]
[feat(Download Header): support set custom headers
Cloased #11](https://github.com/lingochamp/FileDownloader/commit/be773704fbf708c056494fca7cc788bdc380c8c5)

```
BaseDownloadTask task = FileDownloader.getImpl().create(url);
...
task.addHeader(name,value);
...
task.start();
```
