### ISSUE TITLE
Support Foreground Mode

### ISSUE THREAD

**Issue by Jacksgong** [lingochamp/FileDownloader#110]
For covering the case of removing the application from recent apps without stop downloading easily.

**Comment by deeppandya** [comment]
Hello,
According to you we have to start all tasks again.  and it'll be handled by filedownloder service. but my problem is when i kill application from recent apps, download files should continue downloading. In the current scenario it stops downloading as soon as i kill application from recent apps.

So can you please help me  with this ?

**Comment by Jacksgong** [comment]
@deeppandya Yes, We can handle such problem in this way.

**Comment by Jacksgong** [comment]
@deeppandya Please fetch the latest code in master branch, and run the NotificationDemoActivity, it will cover your want.

**Comment by Jacksgong** [comment]
Has been supported in [v0.2.4](https://github.com/lingochamp/FileDownloader/releases/tag/v0.2.4).
