### ISSUE TITLE
DownloadRunnable类中getDownloadedOffset()方法NPE问题

### ISSUE THREAD

**Issue by Xiaojuanmao** [lingochamp/FileDownloader#1100]
```
    private long getDownloadedOffset() {
        final FileDownloadDatabase database = CustomComponentHolder.getImpl().getDatabaseInstance();
        if (connectionIndex >= 0) {
            // is multi connection
            List<ConnectionModel> connectionModels = database.findConnectionModel(downloadId);
            for (ConnectionModel connectionModel : connectionModels) {
                if (connectionModel.getIndex() == connectionIndex) {
                    return connectionModel.getCurrentOffset();
                }
            }
        } else {
            // is single connection
            FileDownloadModel downloadModel = database.find(downloadId);
            // 这个地方报出NPE问题
            return downloadModel.getSoFar();
        }
        return 0;
    }
```

**Comment by Xiaojuanmao** [comment]
目前使用的版本是1.7.5版本

**Comment by rantianhua** [comment]
请提供一份完整的 FileDownloader 的日志，如果 FileDownloader 运行在 `filedownloader` 进程，那么改进程的日志也是必须的。

目前推测出一个可能得原因，但是需要通过日志来进行确认。

**Comment by Xiaojuanmao** [comment]
`
# FileDownloader-Network2(14110)
java.lang.NullPointerException
Attempt to invoke virtual method 'long com.liulishuo.filedownloader.model.FileDownloadModel.getDownloadedOffset()' on a null object reference

com.liulishuo.filedownloader.download.DownloadRunnable.getDownloadedOffset(SourceFile:170)
com.liulishuo.filedownloader.download.DownloadRunnable.run(SourceFile:138)
com.liulishuo.filedownloader.download.DownloadLaunchRunnable.realDownloadWithSingleConnection(SourceFile:609)
com.liulishuo.filedownloader.download.DownloadLaunchRunnable.run(SourceFile:295)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
java.lang.Thread.run(Thread.java:764)
`
