### ISSUE TITLE
Resume Download after app was closed 

### ISSUE THREAD

**Issue by bennik7** [lingochamp/FileDownloader#1103]
I use the `FileDownloadSerialQueue` class to download multiple files. The `FileDownloadSerialQueue` is started within a service, and `BaseTasks` are added dynamically to the queue (if the user decides to download multiple files). How can I i resume/restart the download when the user kills the app?

**Comment by rantianhua** [comment]
Just restart tasks, FileDownloader will start downloading from breakpoint.
