### ISSUE TITLE
Connection failed with request

### ISSUE THREAD

**Issue by q805699513** [lingochamp/FileDownloader#1107]
Connection failed with request[{If-Match=["5ad02b71-4c32a70"], Range=[bytes=39949624-59924435], User-Agent=[FileDownloader/1.7.4]}] response[{null=[HTTP/1.1 503 Service Temporarily Unavailable], Connection=[keep-alive], Content-Length=[206], Content-Type=[text/html], Date=[Wed, 05 Sep 2018 15:12:55 GMT], Server=[nginx], X-Android-Received-Millis=[1536160374403], X-Android-Response-Source=[NETWORK 503], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1536160374352]}] http-state[503] on task[1391656753-2], which is changed after verify connection, so please try again.

**Comment by q805699513** [comment]
你好，下载这个链接出的问题。http://yesky.xzstatic.com/2018/04/13/shoujitaobao_v7.7.2.apk

**Comment by q805699513** [comment]
换个链接就可以了。估计是这个链接用这个框架会有问题

**Comment by rantianhua** [comment]
日志很明显是 server 的问题：
> 503 Service Temporarily Unavailable
