### ISSUE TITLE
当返回的content-length不等于通过Range计算出来的content-length时直接抛回GiveUpException而不继续下载。 这个校检怎么取消。1.6.0以后的版本下载全部报这个异常

### ISSUE THREAD

**Issue by mrchenmo** [lingochamp/FileDownloader#1108]
#### Before Issue

1. Please search on the [Issues](https://github.com/lingochamp/FileDownloader/issues)
2. Please search on the [wiki](https://github.com/lingochamp/FileDownloader/wiki)
3. Please set `FileDownloadLog.NEED_LOG=true` and review the Logcat output from main process and `:filedownloader` process ( pay attention to Warn and Error level logcat)

#### Issue

1. What problem do you get?
2. Which version of FileDownloader are you using when you produce such problem?
3. How to reproduce such problem?
4. Do you set `FileDownloadLog.NEED_LOG=true`?
5. Could you please reproduce this problem and provide all main process and `:filedownloader` process logcat 
6. Can you fix it by yourself and request PR, if not, what's problem do you get when you try to fix it

>P.S. If you don't know how to get `:filedownloader` process, it's recommended to using `pidcat` to just filter all your application logcat, or define `process.non-separate=true` on [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)

---

请在Issue前认真的跟进上面提到的建议，这样将可以极大的加快你遇到问题的处理。

**Comment by rantianhua** [comment]
这个检验是必要的，为什么要取消？如果发生了这样的事情，说明错误的根源在于服务端没有返回正确的 content-length 或者在进行流读取时有问题。
