### ISSUE TITLE
can not download when the status is pending  (if already three files being downloaded)

### ISSUE THREAD

**Issue by nukc** [lingochamp/FileDownloader#111]
当3个文件正在下载，点击开始下载第4,5及之后的就会进入pending状态，按逻辑来说是，当前3个其中有1个完后，第4个就会开始下载，5及之后的仍会在pending进行等待之前下载完再继续下载。但是测试了却是第4个及之后进入pending之后当前面下载完了也不会开始下载。当再次点击在pending状态的文件，文件状态也不会改变（可以多点几次试试），当然，我也用demo测试了一遍（由于demo的任务管理器案例文件都太小，下载完很快，所以我使用了`Constant.BIG_FILE_URLS`数组进行测试）。

我也想替你分担一下，于是我自己也开始尝试解决：
我在按钮点击事件里设置了断点调式，在第4个（pending状态）获取status是1（即pending），当再次点击还是pending。所以我就在`FileDownloadMgr`的`pause(final int id)`方法里强制加入了：
```java
model.setStatus(FileDownloadStatus.paused); 
```
但问题依旧，并log：
```java
com.liulishuo.filedownloader.demo W/FileDownloader.FileDownloadTask: warn, but no listener to receive progress, switch to pending -1011761149 -2
```
然后定点在`BaseDownloadTask`的`update(final FileDownloadTransferModel transfer)`方法，之后我看见下面有个判断之后`getDriver().notifyPending();`进行通知，之后我又尝试：
在`FileDownloadStatus`增加了1个status：
```java
public final static byte waiting = 7;

public static boolean isIng(final int status) {
        return status >= pending && status <= waiting;
    }
```
在`FileDownloadMgr`的`pause(final int id)`：
```java
if (getStatus(id) == FileDownloadStatus.pending) {
       model.setStatus(FileDownloadStatus.waiting);
}
```
最后在`FileDownloadRunnable`的`run()`：
```java
if (model.getStatus() == FileDownloadStatus.waiting) {
        model.setStatus(FileDownloadStatus.pending);
 }

// Step 2, check status  在这步之前强行了setStatus
```
再次测试，第4及之后进入pending状态的文件，再次点击按钮，文件按钮状态是可以是改变的，点击`pause`后显示`start`，点击`start`之后显示`pause`。
但是，当前3个文件其中1个下载完后，第4及之后的仍不会开始下载（有情况是会继续开始下载，例如我在公司的时候，公司网络差，继续下载的几率会大大提高）。

我对这个库还没有吃透，我也感觉我这样改有点感觉不对。

我希望你能指点一下我，我可以增加对这个库的了解，同时，这对我的学习也很有帮助，谢谢。:)

另：鉴于之前的issues只有我才这样，我也担心这次也只有我。。。

**Comment by Jacksgong** [comment]
> 当3个文件正在下载，点击开始下载第4,5及之后的就会进入pending状态，按逻辑来说是，当前3个其中有1个完后，第4个就会开始下载，5及之后的仍会在pending进行等待之前下载完再继续下载。

确实就是这样。你可以试试，项目 demo中的项目管理案例。

**Comment by Jacksgong** [comment]
我再看看这个问题。

**Comment by Jacksgong** [comment]
💯   这个我看了下，是FileDownloader架构设计缺陷，不过我可以快速修复下这个问题。

首先目前的 TasksManagerDemoActivity 有一点bug，这个我一会儿修复了提交。

这个bug复现的方法比较简单: 加入: T1、T2、T3、T4、T5、T6 6个任务启动。

Downloading: T1、T2、T3
Pending: T4、T5、T6

如果这时候没有任何Action那么是没有问题的（一会我提交以后，你可以在任务管理中测试(我全部替换为大文件下载，也修复了一个demo中的bug），但是这时候我暂停T5、再启动T5这时候会收到这个不达预期的警告: `warn, but no listener to receive progress, switch to pending 677920034 1`，具体原因是这样的:

暂停T5时，调用了 `FileDownloadMgr#pause(id):boolean` 此时没有将T5运行的Runnable从线程池FileDownloadThreadPool中移走，而是将标志位`FileDownloadModel#isCanceled`置为`true`，原本是制药这个置为true那么一旦到这个任务，就会return掉，或者是运行过程中发现这个标志位也会return掉不进行继续下载。
但是现在的场景是: 此时又执行了T5的运行，此时还没有轮到之前标记为Cancel的T5任务，于是就判断线程池中存在T5任务，就抛了Warn，于是就运行不了这个任务了。

---

这个问题，我一会儿修复了提交。

**Comment by nukc** [comment]
嗯，好的。我也看到`pause(id)·里有设置`FileDownloadModel#isCanceled`为`true`，但我却没去深入，导致了我找错了方向，谢谢你的指导。至于上个issues https://github.com/lingochamp/FileDownloader/issues/98 我明天会检测一下`bindService()`移除后会不会正常，明天测试后在#98后评论，正常后我会该close issues。

**Comment by Jacksgong** [comment]
@nukc 💯

**Comment by Jacksgong** [comment]
@nukc 你拉最新代码，然后跑下 TasksManagerDemoActivity，应该是修复了的。而且现在这里面也都是大文件。

**Comment by nukc** [comment]
我刚刚测试了，确实已经修复了，辛苦你了，感谢！我想问下，下个版本会在什么时候出？

**Comment by Jacksgong** [comment]
我尽量在明后天。

**Comment by nukc** [comment]
好的，请注意身体。

**Comment by Jacksgong** [comment]
Has been fixed in [v0.2.4](https://github.com/lingochamp/FileDownloader/releases/tag/v0.2.4).
