### ISSUE TITLE
All the downloads are paused when clear the app from recent screen.How to continue download even after the app killed

### ISSUE THREAD

**Issue by kanivel** [lingochamp/FileDownloader#1110]
Hi,

     I want the the download to continue to run in the background even after the app is killed.but in in this demo when i clear the app from recent screen the running downloads are paused.what i have to do to continue download in background even after the app killed

**Comment by rantianhua** [comment]
Under Android O, you can do that through `FileDownloader#startForeground(int, Notification)`. This will make download service be a foreground service so that the service will not be killed when user kill the app from recent tasks.
