### ISSUE TITLE
没有下载的时候通知栏会弹出一个无意义的通知

### ISSUE THREAD

**Issue by Allyns** [lingochamp/FileDownloader#1117]
通知提示：filedownloader is running 
不知道在哪里去掉，也不知道什么时候会弹出。
看了源代码没找到可以去掉的地方

[查看图片](http://download.hchezhu.com/img/TIM图片20180913105805.jpg)

**Comment by Allyns** [comment]
请查看图片，这不是的自己添加显示的

**Comment by rantianhua** [comment]
Please refer to #1096
