### ISSUE TITLE
How to get all tasks ?

### ISSUE THREAD

**Issue by Anton111111** [lingochamp/FileDownloader#1119]
Hi! How can i request all tasks on start app? Or i need save all task myself to restart them?

**Comment by rantianhua** [comment]
You just need to save the urls which will be downloaded and then recreate tasks to start them.

**Comment by rantianhua** [comment]
Database component in FileDownloader is just used to save status during download, the status will be recover in next download and will be remove if the task finished. It is clean as soon as possible and business independent.
