### ISSUE TITLE
response code error: 400, 

### ISSUE THREAD

**Issue by Andjdd** [lingochamp/FileDownloader#1122]
response code error: 400, 
 request headers: {authorization=[eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1Mzc0MjcyNTk1ODEsInBheWxvYWQiOiJ7XCJ1c2VySWRcIjoxNTM1NTMyOTAwMzU3MjAsXCJhdXRoVXNlclwiOntcImlkXCI6MTUzNTUzMjkwMDM1NzIwLFwiaWRlbnRpdHlcIjpcImFkbWluXCIsXCJ0b2tlblwiOm51bGwsXCJ2aXNpdFRpbWVcIjoxNTM1NDcyMDAwMDAwLFwiY29va2llS2V5XCI6bnVsbCxcImlzTG9ja1wiOjAsXCJjcmVhdGVUaW1lXCI6MTUzNTUzMjkwMDAwMCxcInNhbHRcIjpudWxsLFwicGhvbmVcIjpudWxsLFwiZW1haWxcIjpudWxsLFwiaGVhZEltZ1wiOm51bGwsXCJ1c2VybmFtZVwiOlwiYWRtaW5cIn0sXCJsb2dpbklwXCI6XCIxOTIuMTY4LjIuMTY2XCJ9In0.3eUTHabyhVnELTl5B1q2579letcBkbcx2rvh1yqACZY], Range=[bytes=0-0], User-Agent=[FileDownloader/1.7.5]} 
 response headers: {null=[HTTP/1.1 400 ], Connection=[close], Date=[Thu, 20 Sep 2018 06:20:19 GMT], Transfer-Encoding=[chunked], X-Android-Received-Millis=[1537424580176], X-Android-Response-Source=[NETWORK 400], X-Android-Sent-Millis=[1537424580174]}

**Comment by Andjdd** [comment]
response code error: 400,

**Comment by Andjdd** [comment]
response code error: 400,

**Comment by Andjdd** [comment]
response code error: 400,

**Comment by rantianhua** [comment]
You can try again with configuring 
```
download.trial-connection-head-method=true
```
in your `filedownloader.properties` file.

**Comment by Andjdd** [comment]
return FileDownloader.getImpl()
                .create(url)
                .addHeader("authorization", token)
                .setPath(path)
                .setCallbackProgressTimes(300)
                .setMinIntervalUpdateSpeed(400)
                .setListener(new FileDownloadSampleListener() {
No effect

**Comment by rantianhua** [comment]
I guess your authorization is not right so server return 400 for you.

**Comment by Andjdd** [comment]
On Android 4.4, you can report this error on 5.1.1.

**Comment by Andjdd** [comment]
How to add   download.trial-connection-head-method=true

**Comment by Andjdd** [comment]
在平板android5.1.1 上提示400  在手机8.0上面使用都没问题

**Comment by Andjdd** [comment]
求证此框架在android 5.1.1 系统上面是没法使用的

**Comment by rantianhua** [comment]
URL 链接和 FileDownloader 完成日志请提供一下。

**Comment by espring** [comment]
@Andjdd  取log的方法, 可以参考#1121

**Comment by Andjdd** [comment]
解决了:问题在5.1.1 版本上 url 编码问题

**Comment by tiewantn** [comment]
遇到类似的中文404问题，但是是偶现bug。
工程项目在二十多款手机上测试，当文件路径中或文件名称有中文时，会偶现404异常，大多数手机上下载正常，复现该bug机型为红米note2，红米note1lte。希望作者能复现，并提出借解决方案，多谢
