### ISSUE TITLE
请问如何清除当前所有下载任务, 开始一批新的下载任务.

### ISSUE THREAD

**Issue by espring** [lingochamp/FileDownloader#1123]
不好意思, 这个问题我查询了wiki和issue, 没有找到确切的答案.

清除当前所有下载任务:
FileDownloader.getImpl().pauseAll();
FileDownloader.getImpl().clearAllTaskData();

之后, 开始一批新下载任务, 立刻 FileDownloadQueueSet.downloadSequentially(taskList).start();

我使用的版本是1.6.9

**Comment by espring** [comment]
android 5.1.1, sdk版本22

**Comment by Andjdd** [comment]
我也在5.1.1使用的但是提示response code error: 400,

**Comment by Andjdd** [comment]
我是这样用的  return FileDownloader.getImpl()
                .create(url)
            //  .setForceReDownload(true)
             //   .addHeader("authorization", token)
                .setPath(path)//下载文件的存储绝对路径
                .setCallbackProgressTimes(300)//设置progress最大回调次数
                .setMinIntervalUpdateSpeed(400)//设置下载中刷新下载速度的最小间隔
                .setListener(new FileDownloadSampleListener() {

**Comment by Andjdd** [comment]
报错为:response code error: 400, 
 request headers: {authorization=[eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1Mzc0MjcyNTk1ODEsInBheWxvYWQiOiJ7XCJ1c2VySWRcIjoxNTM1NTMyOTAwMzU3MjAsXCJhdXRoVXNlclwiOntcImlkXCI6MTUzNTUzMjkwMDM1NzIwLFwiaWRlbnRpdHlcIjpcImFkbWluXCIsXCJ0b2tlblwiOm51bGwsXCJ2aXNpdFRpbWVcIjoxNTM1NDcyMDAwMDAwLFwiY29va2llS2V5XCI6bnVsbCxcImlzTG9ja1wiOjAsXCJjcmVhdGVUaW1lXCI6MTUzNTUzMjkwMDAwMCxcInNhbHRcIjpudWxsLFwicGhvbmVcIjpudWxsLFwiZW1haWxcIjpudWxsLFwiaGVhZEltZ1wiOm51bGwsXCJ1c2VybmFtZVwiOlwiYWRtaW5cIn0sXCJsb2dpbklwXCI6XCIxOTIuMTY4LjIuMTY2XCJ9In0.3eUTHabyhVnELTl5B1q2579letcBkbcx2rvh1yqACZY], Range=[bytes=0-0], User-Agent=[FileDownloader/1.7.5]} 
 response headers: {null=[HTTP/1.1 400 ], Connection=[close], Date=[Thu, 20 Sep 2018 06:20:19 GMT], Transfer-Encoding=[chunked], X-Android-Received-Millis=[1537424580176], X-Android-Response-Source=[NETWORK 400], X-Android-Sent-Millis=[1537424580174]}

**Comment by Andjdd** [comment]
想请求你下你在5.1.1 上面是怎么使用的

**Comment by espring** [comment]
呵呵, 你是另外那张票吧:)

我是参考Demo里, 用FileDownloadQueueSet的.

        new FileDownloadQueueSet(serialTarget)
                .setCallbackProgressMinInterval(3000) // 3000ms
                .setAutoRetryTimes(6)
                .downloadSequentially(taskList)
                .start();

其中task list
List<BaseDownloadTask> taskList = new ArrayList<>();
for循环中:
taskList.add(FileDownloader.getImpl().create(url)
                    .setPath(path)
                    .setMinIntervalUpdateSpeed(3000) //
                    .setTag(nDwId + 1));

**Comment by Andjdd** [comment]
你qq 或者微信多少想请教哈你

**Comment by rantianhua** [comment]
其实不太理解你的问题，不过 
```
FileDownloader.getImpl().pauseAll();
FileDownloader.getImpl().clearAllTaskData();
```
确实能清楚所有正在下载的任务。

**Comment by espring** [comment]
背景还是#959 这张票里描述的问题

: 下载任务一直结束不了, 一直是temp文件.

发生的概率不高, 在一些网络环境不太稳定的设备上容易出现, 但一直没有完整的log.

所以想着绕过去的方法,  消除原有下载任务, 重新开始.

**Comment by espring** [comment]
接之前的话题:

clearAllTaskData()调用之后, 再重新开始下载任务, 
之前下载的文件, 是否还能断点续传?

从on progress回调里看"已下载字节数(soFarBytes)",  是从0开始, 但是很快就能增长上来, 看起来又好像是接着断点处下载了?

**Comment by rantianhua** [comment]
clearAll 之后就重新开始下载了。还是希望能有一份完整的日志，这样对排查问题帮助很大，谢谢！

**Comment by espring** [comment]
哎, 我确实是很难重现问题, 拿到完整的log...

我现在是想绕过去,  想把FileDownloader这个进程/实例结束掉, 再重新开始, 接着原来的断点继续下载.

请问怎么做到? 

我试过pauseAll(), 然后再重新开始, 结果反复十多次这样调用后, FileDownloader没有任何动静了, 
这里有些log:  https://gist.github.com/espring/c900baebf483cdad32914be472e88cd1

**Comment by espring** [comment]
绕过去, 是指我找不到下载进程有时候会没动静的原因, 
所以想不去管它原因, 看能不能reset掉, 让下载再重新开始.

我用的方法是这样的:

`
// 先暂停所有的任务.
FileDownloader.getImpl().pauseAll(); 
// 不能调用clearAllTaskData, 否则下载一半的文件就会被删除了.

// unBindService && bindService的方法达到reset
FileDownloader.getImpl().unBindService();
FileDownloader.getImpl().bindService();

// 再重新add一遍tasks
...
// 因为有断点续传, 所有任务都还是能接着进行.

`

看起来比较奇怪的作法, 目前经过一段时间的应用观察, 应该是达到目的了.

以上, 希望能给有类似问题的一些帮助.
也谢谢FileDownloader这个开源项目!
