### ISSUE TITLE
Can not download file if there is spacing on name file

### ISSUE THREAD

**Issue by lethanhtan89** [lingochamp/FileDownloader#1125]
I would like to download a file which is spaceing on url, but it's can not.

Ex: http://abc.com/hello word.pdf

what i have to do ?

**Comment by rantianhua** [comment]
Please refer to https://www.arclab.com/en/kb/htmlcss/uri-url-encoding-spaces-in-links-href-img-src.html. Actually, this is not a issue about FileDownloader.

**Comment by lethanhtan89** [comment]
thanks
