### ISSUE TITLE
android.database.sqlite.SQLiteFullException  database or disk is full (code 13)

### ISSUE THREAD

**Issue by pgeeKer** [lingochamp/FileDownloader#1127]
你好，在使用的时候遇到了如 title 的问题，请问是否在新版本已经修复？我使用的是 1.6.9版本。
crash 堆栈如下：

java.lang.RuntimeException:Unable to create service com.liulishuo.filedownloader.services.FileDownloadService$SeparateProcessService: android.database.sqlite.SQLiteException: Failed to change locale for db '/data/data/xxx/databases/filedownloader.db' to 'zh_CN'.
--
2 android.app.ActivityThread.handleCreateService(ActivityThread.java:2655)
3 ......
4 Caused by:
5 android.database.sqlite.SQLiteFullException:database or disk is full (code 13)
6 android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
7 android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:555)
8 android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:371)
9 android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:218)
10 android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
11 android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
12 android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
13 android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
14 android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
15 android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:789)
16 android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
17 android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1010)
18 android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:281)
19 android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:224)
20 android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
21 com.liulishuo.filedownloader.database.SqliteDatabaseImpl.<init>(SqliteDatabaseImpl.java:70)
22 com.liulishuo.filedownloader.database.RemitDatabase.<init>(RemitDatabase.java:55)
23 com.liulishuo.filedownloader.services.DownloadMgrInitialParams.createDefaultDatabase(DownloadMgrInitialParams.java:166)
24 com.liulishuo.filedownloader.services.DownloadMgrInitialParams.createDatabase(DownloadMgrInitialParams.java:70)
25 com.liulishuo.filedownloader.download.CustomComponentHolder.getDatabaseInstance(CustomComponentHolder.java:88)
26 com.liulishuo.filedownloader.services.FileDownloadManager.<init>(FileDownloadManager.java:53)
27 com.liulishuo.filedownloader.services.FileDownloadService.onCreate(FileDownloadService.java:56)
28 android.app.ActivityThread.handleCreateService(ActivityThread.java:2645)
29 android.app.ActivityThread.access$1800(ActivityThread.java:156)
30 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1310)
31 android.os.Handler.dispatchMessage(Handler.java:102)
32 android.os.Looper.loop(Looper.java:136)
33 android.app.ActivityThread.main(ActivityThread.java:5365)
34 java.lang.reflect.Method.invokeNative(Native Method)
35 java.lang.reflect.Method.invoke(Method.java:515)
36 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:855)
37 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:671)
38 dalvik.system.NativeStart.main(Native Method)

**Comment by rantianhua** [comment]
请参照 #206 和 #583
