### ISSUE TITLE
急求: 局域网下载失败 

### ISSUE THREAD

**Issue by CleverSJX** [lingochamp/FileDownloader#1137]
#### error 回调的 message
http://192.168.1.53/resource/7662066a85cbab8583dfe4f27d07bb1c.jpg  Connection failed with request[{If-Match=[W/"5bd1b669-1d400"], Range=[bytes=0-], User-Agent=[FileDownloader/1.7.5]}] response[{null=[HTTP/1.1 412 Precondition Failed], Connection=[keep-alive], Content-Length=[173], Content-Type=[text/html], Date=[Thu, 25 Oct 2018 13:58:59 GMT], Server=[nginx/1.15.5], X-Android-Received-Millis=[1540475932314], X-Android-Response-Source=[NETWORK 412], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1540475932306]}] http-state[412] on task[1123815684--1], which is changed after verify connection, so please try again.

**Comment by CleverSJX** [comment]
很急

**Comment by rantianhua** [comment]
> 有一行 FileDownloader.FileDownloadUtils: don't get instance length fromContent-Range header

这表示第一次 trail connection 的时候没有获取到文件长度，正常的话，response header 应该返回 Content-Range

**Comment by rantianhua** [comment]
错误日志显示 HTTP/1.1 412 Precondition Failed ，意味着请求的 range 出错。但是日志也很清楚，下载时请求的 range 为 `Range=[bytes=0-]` ，这完全是合法的 range ，而服务器返回了 412 ，所以这是服务器问题，需要服务器去解决。

**Comment by CleverSJX** [comment]
嗯 你说的很正确 是服务端的问题已经解决了 谢谢!
