### ISSUE TITLE
已经调用了暂停的任务，还会不停的回调listener中的progress方法

### ISSUE THREAD

**Issue by menshen** [lingochamp/FileDownloader#1139]
测试中发现刚刚已经调用过暂停的任务，还在回调progress方法！
这属于正常现象吗 ？

**Comment by menshen** [comment]
参考了：https://github.com/lingochamp/FileDownloader/issues/246#issuecomment-237133750
这个issue后调整了setCallbackProgressMinInterval
问题似乎得到了解决，继续观察下！
顺便问一句，开启单个任务：
FileDownloader.getImpl().create(url)
.setListener()
这里的listener是需要每个任务new一个还是全局用一个即可呢？

**Comment by rantianhua** [comment]
一个 listener 可以与多个 Task 进行关联，你可以根据你的使用场景决定使用  listener 的方式。假如你有 3 个下载任务，你需要同时暂停掉三个下载任务，那么你可以三个任务使用同一个 listener 。

**Comment by menshen** [comment]
通过观察发现设置了setCallbackProgressMinInterval后问题已经没了

**Comment by Jacksgong** [comment]
还有一个原因是分包分时机制导致的，可以通过`FileDownloader.disableAvoidDropFrame()`对其进行关闭。
