### ISSUE TITLE
　小图片，文档下载不下来

### ISSUE THREAD

**Issue by hfox09211** [lingochamp/FileDownloader#1140]
Connection failed with request[{If-Match=["876f0b53e4428f0d2077eb7c4e06f5bc"], Range=[bytes=0-], User-Agent=[FileDownloader/1.7.5]}] response[{null=[HTTP/1.1 412 Precondition Failed], Connection=[keep-alive], Content-Length=[92], Content-Type=[text/html; charset=UTF-8], Date=[Wed, 14 Nov 2018 01:50:07 GMT], X-Android-Received-Millis=[1542160149836], X-Android-Response-Source=[NETWORK 412], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1542160149770]}] http-state[412] on task[-1795655863--1], which is changed after verify connection, so please try again.

**Comment by lofts** [comment]
同问

**Comment by lofts** [comment]
Connection failed with request[{If-Match=[W/"963f2b1d3282d41:0"], Range=[bytes=0-], User-Agent=[FileDownloader/1.7.5]}] response[{null=[HTTP/1.1 412 Precondition Failed], Connection=[close], Content-Length=[331], Content-Type=[text/html; charset=us-ascii], Date=[Thu, 22 Nov 2018 07:08:58 GMT], Server=[Microsoft-HTTPAPI/2.0], X-Android-Received-Millis=[1542870261000], X-Android-Response-Source=[NETWORK 412], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1542870260996]}] http-state[412] on task[-596941228--1], which is changed after verify connection, so please try again.

**Comment by rantianhua** [comment]
这应该是服务端的问题，request with range: [bytes=0-] 是一个合法的请求，E-Tag 也是服务端返回的。所以可以和服务端沟通下为什么这里会返回 412 。

**Comment by rantianhua** [comment]
另外请参考 #1137
