### ISSUE TITLE
无法在下载前获取文件大小

### ISSUE THREAD

**Issue by wangxiufeng** [lingochamp/FileDownloader#1141]
你好，我想在下载前获取下载的文件大小，尝试了几个方法都是返回0，请问如何才能获取呢？
方法一：  
DownloadTask downloadTask = (DownloadTask) FileDownloader.getImpl().create(downLoadUrl);
 downloadTask.getTotalBytes()和downloadTask.getSmallFileTotalBytes() 返回的都是0
方法二：
 int id = FileDownloadUtils.generateId(downLoadUrl, localPath);
long total = FileDownloader.getImpl().insureServiceBind().getTotal(id);
total值也是返回的是0
谢谢

**Comment by rantianhua** [comment]
如果是一个新的下载任务，那么你可以在 `FileDownloadListener#connected` 中得到文件大小，如果是之前已经下载过的任务，那么你可以在 `FileDownloadListener#pending` 的时候就能获取大小。在任务下载过程中，也可以通过 `downloadTask.getSmallFileTotalBytes()` 获得大小。

在你的示例中，你只是创建了任务，并没有开启任务，自然没法知道文件大小，因为文件大小也需要请求网络去获取的。

**Comment by wangxiufeng** [comment]
如果是一个新的下载任务，那么你可以在 FileDownloadListener#connected 中得到文件大小：

现在我有这么一个需求，我要下载多个文件，我需要在下载前提示用户这几个文件总共更有多大。
如果用FileDownloadQueueSet.downloadSequentially(tasks);我没有办法实现下载之前获取到总共有多大啊。多个任务下载FileDownloadListener只能回调一个任务的信息，并不是所有任务的信息。
