### ISSUE TITLE
无法下载文件，多次出现Connection failed with request

### ISSUE THREAD

**Issue by lofts** [lingochamp/FileDownloader#1145]
Connection failed with request[{If-Match=[W/"16d5498b3582d41:0"], Range=[bytes=0-], User-Agent=[FileDownloader/1.7.5]}] response[{null=[HTTP/1.1 412 Precondition Failed], Connection=[close], Content-Length=[331], Content-Type=[text/html; charset=us-ascii], Date=[Thu, 22 Nov 2018 07:33:45 GMT], Server=[Microsoft-HTTPAPI/2.0], X-Android-Received-Millis=[1542871748104], X-Android-Response-Source=[NETWORK 412], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1542871748100]}] http-state[412] on task[-403978202--1], which is changed after verify connection, so please try again.

**Comment by rantianhua** [comment]
Duplicate with #1140
