### ISSUE TITLE
为什么下载下来的图片文件名是一串数字 而且没有扩展名？

### ISSUE THREAD

**Issue by LuMgYu** [lingochamp/FileDownloader#1147]
难受，文档也没提到这个东西，唉
咋回事嘛。
在service里面写下如下代码：
String url4 ="http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4";
 ArrayList<String> list = new ArrayList<>();
list.add(url4);
FileManager.getInstance().start_multi(list,FileManager.getInstance().picPath);

Log打印出来如下
E/TESTService: e
E/pending: pending
E/progress: progress
E/progress: progress
E/progress: progress
E/progress: progress
E/progress: progress
E/progress: progress
E/progress: progress
E/progress: progress
E/progress: progress
E/progress: progress
E/progress: progress
E/progress: progress
E/progress: progress
E/progress: progress
E/progress: progress
E/progress: progress
E/progress: progress
E/blockComplete: blockComplete
E/TESTActivity: TESTActivity
E/list: [/storage/emulated/0/Android/data/com.leo.entranceguard/cache/TEST/pic/bf2977e50cb5ed6a5783d50a39d554b8]

最后一行是拿到的文件地址，没有扩展名，可以播放 但是没有扩展名，下载APK有扩展名，但是图片和视频都是这样，下载下来之后没有扩展名。

start_multi的配置如下：

 public void start_multi(List<String> urls, String path) {
        multiple = urls.size();
        downloadListener = createLis();
        //(1) 创建 FileDownloadQueueSet
        final FileDownloadQueueSet queueSet = new FileDownloadQueueSet(downloadListener);
        //(2) 创建Task 队列
        final List<BaseDownloadTask> tasks = new ArrayList<>();
        for (int i = 0; i < urls.size(); i++) {
            tasks.add(FileDownloader.getImpl().create(urls.get(i)).setPath(path, true));
        }
        //(3) 设置参数
        // 每个任务的进度 无回调
        //queueSet.disableCallbackProgressTimes();
        // do not want each task's download progress's callback,we just consider which task will completed.
        queueSet.setCallbackProgressTimes(100);
        queueSet.setCallbackProgressMinInterval(100);
        //失败 重试次数
        queueSet.setAutoRetryTimes(3);
        //避免掉帧
        FileDownloader.enableAvoidDropFrame();
        //(4)串行下载
        queueSet.downloadSequentially(tasks);
        //(5)任务启动
        queueSet.start();
    }

FileManager的配置如下：

 BaseDownloadTask singleTask;
    public int singleTaskId = 0;
    public String picPath = FileDownloadUtils.getDefaultSaveRootPath() + File.separator + "TEST"
            + File.separator + "pic";
    public static FileManager instance = null;
    private FileManager() {
    }
    public static FileManager getInstance() {
        if (null == instance) {
            instance = new FileManager();
        }
        return instance;
    }

FileDownloadListener 的配置如下：

public FileDownloadListener createLis() {
        return new FileDownloadSampleListener() {
            @Override
            protected void pending(BaseDownloadTask task, int soFarBytes, int totalBytes) {
                Log.e("pending", "pending");
                if (task.getListener() != downloadListener) {
                    return;
                }
            }

            @Override
            protected void progress(BaseDownloadTask task, int soFarBytes, int totalBytes) {
                Log.e("progress", "progress");
                if (task.getListener() != downloadListener) {
                    return;
                }
            }

            @Override
            protected void blockComplete(BaseDownloadTask task) {
                Log.e("blockComplete", "blockComplete");
                if (task.getListener() != downloadListener) {
                    return;
                }
            }

            /**
             * @param task
             */
            @Override
            protected void completed(BaseDownloadTask task) {
                if (task.getListener() != downloadListener) {
                    return;
                }
                if (count >= multiple) {
                    Intent intent = new Intent("TESTACTIVITY");
                    intent.putExtra(ConnectionManager.MESSAGE, "DownloaderManager");
                    MyApplication.getInstance().sendBroadcast(intent);
                    count = 1;
                    return;
                }
                count++;
            }

            @Override
            protected void paused(BaseDownloadTask task, int soFarBytes, int totalBytes) {
                Log.e("paused", "paused");
                if (task.getListener() != downloadListener) {
                    return;
                }
            }

            @Override
            protected void error(BaseDownloadTask task, Throwable e) {
                Log.e("error", "error");
                if (task.getListener() != downloadListener) {
                    return;
                }
            }

            @Override
            protected void warn(BaseDownloadTask task) {
                Log.e("warn", "warn");
                if (task.getListener() != downloadListener) {
                    return;
                }
            }
        };
    }

**Comment by rantianhua** [comment]
请按照以下 issue 模板尽可能多提供信息，光这样无法提供帮助。
#### Before Issue

1. Please search on the [Issues](https://github.com/lingochamp/FileDownloader/issues)
2. Please search on the [wiki](https://github.com/lingochamp/FileDownloader/wiki)
3. Please set `FileDownloadLog.NEED_LOG=true` and review the Logcat output from main process and `:filedownloader` process ( pay attention to Warn and Error level logcat)

#### Issue

1. What problem do you get?
2. Which version of FileDownloader are you using when you produce such problem?
3. How to reproduce such problem?
4. Do you set `FileDownloadLog.NEED_LOG=true`?
5. Could you please reproduce this problem and provide all main process and `:filedownloader` process logcat 
6. Can you fix it by yourself and request PR, if not, what's problem do you get when you try to fix it

>P.S. If you don't know how to get `:filedownloader` process, it's recommended to using `pidcat` to just filter all your application logcat, or define `process.non-separate=true` on [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)

---

请在Issue前认真的跟进上面提到的建议，这样将可以极大的加快你遇到问题的处理。

**Comment by zichenly** [comment]
你给他设置路径的时候，后面是由文件名加后缀就是有你说的 .jpg 或.mp4
l例如
String savePath = FileDownloadUtils.getDefaultSaveRootPath() + File.separator + "notification.apk";
FileDownloader.getImpl().create(url)
                    .setPath(savePath)
                    .setListener(listener)
                    .start();

**Comment by LuMgYu** [comment]
> 你给他设置路径的时候，后面是由文件名加后缀就是有你说的 .jpg 或.mp4
> l例如
> String savePath = FileDownloadUtils.getDefaultSaveRootPath() + File.separator + "notification.apk";
> FileDownloader.getImpl().create(url)
> .setPath(savePath)
> .setListener(listener)
> .start();

谢谢你，这样试过，但是按你给的例子得到的会是一个名为notification.apk的文件夹，下载好的文件在这个文件夹里面。
按我的例子，得到的文件路径差不多会是这样：
/storage/emulated/0/Android/data/com.leo.entranceguard/cache/TEST/pic/big_buck_bunny.mp4/bf2977e50cb5ed6a5783d50a39d554b8
可能是我哪里还是有疏忽。因为时间关系已经用AndroidVideoCache+Glide代替FileDownloader，纯缓存不下载了。

**Comment by LuMgYu** [comment]
回过头耐心一看，setpath()里面需要设置一个布尔值来分辨 path为路径还是文件名，刚上手的时候太过急躁，拿起demo就是干，唉，结果有稍微点问题就不知道怎么办了。谢谢大佬的回复，以后我用东西之前，一定要先看了。
