### ISSUE TITLE
每调用一次开始下载，就重新调用application.onCreate

### ISSUE THREAD

**Issue by lbs522633682** [lingochamp/FileDownloader#1148]
我发现必须要在Application中去调用init方法，如果不在就不行，最后找到是因为在调用下载的时候，会重新去加载Application

那是不是我APplication中的方法都会重新加载一遍

**Comment by rantianhua** [comment]
FileDownloader 默认运行在独立进程，所以当 `filedownloader` 进程启动的时候，所以 Application 会再创建一次。这属于多进程开发的问题。如果你不想多进程，可以在 filedownloader.properties 里面进行配置，具体可见： https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties
