### ISSUE TITLE
使用过程中出现崩溃

### ISSUE THREAD

**Issue by appledong** [lingochamp/FileDownloader#115]
![image](https://cloud.githubusercontent.com/assets/5242789/14600610/29d9ca14-0590-11e6-8289-bd6d31b8f281.png)

**Comment by Jacksgong** [comment]
这个是因为，你没有在 `Application#onCreate` 中执行 `FileDownloader#init` 导致的。

**Comment by appledong** [comment]
执行了，不过我是在service里面启动下载

**Comment by Jacksgong** [comment]
这个异常是因为 `FileDownloadHelper#APP_CONTEXT` 为 null 导致的。正常情况是在下载进程启动的时候，会调用下载进程 Application对象的 `onCreate`，然后我们在 这里执行`FileDownloader#init`  来对这个参数进行赋值。这是一个很简单的业务逻辑，你可以debug下看看为什么你会没有给这个赋值。

**Comment by appledong** [comment]
![image](https://cloud.githubusercontent.com/assets/5242789/14625357/fad4a5e2-0614-11e6-8327-d89678bb06b4.png)
![image](https://cloud.githubusercontent.com/assets/5242789/14625363/098ed512-0615-11e6-8071-a70ab96ac001.png)
由此可见在启动下载的时候App_context是有值不为null的

**Comment by Jacksgong** [comment]
那你debug下，看看在你上面抛npe的时候，是哪个为null了。因为我这边无法复现类似问题，我们自己的应用也在使用。

**Comment by appledong** [comment]
![image](https://cloud.githubusercontent.com/assets/5242789/14626686/65e10730-0620-11e6-9df9-412c3cbfcf50.png)
启动下载的时候，Helper还持有呢，但是在获取数据库的时候就为空了？麻烦楼主帮忙看一下？方便加个联系方式？

**Comment by Jacksgong** [comment]
@appledong 

![image](https://cloud.githubusercontent.com/assets/6176417/14629299/3f118018-0638-11e6-94f8-b31102a511a4.png)


很明显。所在的进程不同，看你的日志应该是下载进程没有调到初始化的 `FileDownloader#init`，你如果直接放在 `Application#onCreate` 中，肯定会调用到的，只有可能你没有放到 `Application#onCreate` 或者你 在调用之前过滤掉了。你留意下。

**Comment by appledong** [comment]
问题原因是：init调用进程和下载启动不在一个进程里面
