### ISSUE TITLE
网络切换会报错，偶尔会出现重头开始下载，期望是能够断点续传

### ISSUE THREAD

**Issue by niemj** [lingochamp/FileDownloader#1150]
11-29 14:52:01.166 28851-32374/? V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@fd25912 by 11 
11-29 14:52:01.167 28851-32374/? V/FileDownloader.FileDownloadList: add list in all 1278042210@com.liulishuo.filedownloader.DownloadTask@c3a509d 11 1
11-29 14:52:01.174 28851-32121/? D/FileDownloader.MessageSnapshotGate: ~~~callback 1278042210 old[11] new[1] 1
11-29 14:52:01.174 28851-32121/? D/FileDownloader.FileDownloadMessenger: notify pending 1278042210@com.liulishuo.filedownloader.DownloadTask@c3a509d
11-29 14:52:01.175 28851-32121/? D/FileDownloader.MessageSnapshotGate: updateKeepFlow
11-29 14:52:01.176 28851-32121/? D/FileDownloader.MessageSnapshotGate: ~~~callback 1278042210 old[1] new[6] 1
11-29 14:52:01.177 28851-32121/? D/FileDownloader.FileDownloadMessenger: notify started 1278042210@com.liulishuo.filedownloader.DownloadTask@c3a509d
11-29 14:52:01.178 28851-32121/? D/FileDownloader.MessageSnapshotGate: updateKeepFlow
11-29 14:52:01.532 28965-32375/? W/FileDownloader.DownloadLaunchRunnable: there is precondition failed on this request[1278042210] with old etag["26c6-2789477-57bc7f4dff2cd"]、new etag["3275-2789477-57bc818bfbb9d"]、response code is 412
11-29 14:52:01.656 28851-32121/? D/FileDownloader.MessageSnapshotGate: ~~~callback 1278042210 old[6] new[2] 1
11-29 14:52:01.656 28851-32121/? D/FileDownloader.FileDownloadMessenger: notify connected 1278042210@com.liulishuo.filedownloader.DownloadTask@c3a509d
11-29 14:52:01.657 28851-32121/? D/FileDownloader.MessageSnapshotGate: updateKeepFlow
11-29 14:52:01.793 28851-32121/? D/FileDownloader.MessageSnapshotGate: ~~~callback 1278042210 old[2] new[3] 1
11-29 14:52:01.795 28851-32121/? D/FileDownloader.FileDownloadMessenger: notify progress 1278042210@com.liulishuo.filedownloader.DownloadTask@c3a509d 5455 41456759
11-29 14:52:01.796 28851-32121/? D/FileDownloader.MessageSnapshotGate: updateKeepFlow
11-29 14:52:05.228 28851-32121/? D/FileDownloader.MessageSnapshotGate: ~~~callback 1278042210 old[3] new[3] 1
11-29 14:52:05.230 28851-32121/? D/FileDownloader.FileDownloadMessenger: notify progress 1278042210@com.liulishuo.filedownloader.DownloadTask@c3a509d 420105 41456759

应该是这句报错： there is precondition failed on this request[1278042210] with old etag["26c6-2789477-57bc7f4dff2cd"]、new etag["3275-2789477-57bc818bfbb9d"]、response code is 412
，但我在内部局域网不会出现这种问题？其他环境会，是不是和服务端有关？

**Comment by rantianhua** [comment]
这里是因为 Etag 发生了改变，所以出现了 412 错误，然后 FileDownloader 会重新下载，因为内容可能已经更新了。
