### ISSUE TITLE
大大，给您个建议

### ISSUE THREAD

**Issue by xyZangGit** [lingochamp/FileDownloader#1157]
我也在使用您的这个下载框架，废话不多说
 您可以在 issues入口处，明显的地方把大家问的比较多的问题 （比如 ： 怎么配置HTTPS,怎么使用自定义的证书下载）归类一下；
然后让开发者可以自行查找解决，这样可以减少开发者遇到的问题提问，也可以节省您的时间，让您更加有效的开发更好的框架，节省您的宝贵时间； 
因为我经常时不时的看我使用框架的 issues模块的问题；
希望大大看到之后可以采纳一下。

**Comment by rantianhua** [comment]
其实 Wiki 里面是有 [QA](https://github.com/lingochamp/FileDownloader/wiki/qa) 的。可以把这个 QA 链接加到 issue 模板里面去，谢谢建议。
