### ISSUE TITLE
下载tomcat相对路径下的文件，文件名获取不到，下载后的文件名为md5(url)值，且没有后缀

### ISSUE THREAD

**Issue by movie0212** [lingochamp/FileDownloader#1159]
1. 下载tomcat相对路径下的文件，文件名获取不到，下载后的文件名为md5(url)值，且没有后缀
2. 我使用的是1.7.6-SNAPSHOT源码
3. 分析源码后，可以修改FileDownloadUtils.findFilename()方法，先获取Content-Disposition中的filename，获取失败后，从url中再获取下，仍然失败则取md5(url)，代码如下：

    private static final Pattern TMP_FILE_NAME_PATTERN = Pattern
            .compile(".*\\\\|/([^\\\\|/|?]*)\\??");

    public static String findFilename(FileDownloadConnection connection, String url)
            throws FileDownloadSecurityException {
        String filename = FileDownloadUtils.parseContentDisposition(connection.
                getResponseHeaderField("Content-Disposition"));

        if (TextUtils.isEmpty(filename)) {
            Matcher m = TMP_FILE_NAME_PATTERN.matcher(url);
            while (m.find()) {
                filename = m.group(1);
            }
        }

        if (TextUtils.isEmpty(filename)) {
            filename = FileDownloadUtils.generateFileName(url);
        } else if (filename.contains("../")) {
            throw new FileDownloadSecurityException(FileDownloadUtils.formatString(
                    "The filename [%s] from the response is not allowable, because it contains "
                            + "'../', which can raise the directory traversal vulnerability",
                    filename));
        }

        return filename;
    }

**Comment by rantianhua** [comment]
FileDownloader 本身就支持 `Content-Disposition` ，没有获取到说明服务器的 response header 里面没有这个，所以 FileDownloader 用了 md5(url) 来做文件名，这对 FileDownloader 来说是正确的行为。如果你觉得有问题，得先检查 response header 里面是否有 `Content-Disposition` 。这些不需要你改代码实现的。

**Comment by movie0212** [comment]
我下载的文件是tomcat相对路径下的文件，不用后台写下载方法的，这样是没法加上Content-Disposition的啊，浏览器上跟踪下载这个文件，获取不到Content-Disposition的

**Comment by movie0212** [comment]
> FileDownloader 本身就支持 `Content-Disposition` ，没有获取到说明服务器的 response header 里面没有这个，所以 FileDownloader 用了 md5(url) 来做文件名，这对 FileDownloader 来说是正确的行为。如果你觉得有问题，得先检查 response header 里面是否有 `Content-Disposition` 。这些不需要你改代码实现的。

@rantianhua 我下载的文件是tomcat相对路径下的文件，不用后台写下载方法的，这样是没法加上Content-Disposition的，浏览器上跟踪下载这个文件，获取不到Content-Disposition的

**Comment by rantianhua** [comment]
所以这样的表现是正常的，获取不到 `Content-Disposition` 而你没有提供 filename 的话，就会用 md5(url) 作为文件名。

**Comment by rantianhua** [comment]
抱歉之前看漏了一部分，你建议在 Content-Disposition 获取不到文件名时在下载路径中获取文件名。这个可以考虑，多谢反馈。如果有兴趣欢迎提 Pull Request 。

**Comment by rantianhua** [comment]
@movie0212  已发布 1.7.7 snapshot 并优化该问题，请先试用 1.7.7-SNAPSHOT 版本验证一下。
