### ISSUE TITLE
cannot download more than 3 download files at the same time.

### ISSUE THREAD

**Issue by deeppandya** [lingochamp/FileDownloader#116]
I updated my code according to your suggestions but now i can only download maximum of 3 files simultaneously.
can you please check it and let me know ?

Thanks for your help. it's appreciated.

**Comment by Jacksgong** [comment]
Yes, it's all right, FileDownloader is designed to download 3 files simultaneously as maximum size, and the rest of the tasks is in the FIFO(First In First Out) pending queue.

#### Why?

As [Fresco](https://github.com/facebook/fresco/blob/0f3d52318631f2125e080d2a19f6fa13a31efb31/imagepipeline/src/main/java/com/facebook/imagepipeline/producers/HttpUrlConnectionNetworkFetcher.java) or [Picasso](https://github.com/square/picasso/blob/7f2e01b06db111295a2a6f593a0339a7050b9deb/picasso/src/main/java/com/squareup/picasso/PicassoExecutorService.java) do, the network resource is limited to one device, it means if you start downloading tasks unlimited simultaneously, it will be blocked by lack of the network resource, and more useless CPU occupy. 

#### Further

In addition, the relative efficiency of 3 is higher than others.  But I think for case by case, FileDownloader will consider support to configure for this.
