### ISSUE TITLE
使用多任务下载时候一直在pending滞留

### ISSUE THREAD

**Issue by JacksenLaw** [lingochamp/FileDownloader#1161]
下面是创建多任务队列，并开始下载的代码：        
        fileDownloadListener = createLis();
        //1、创建 FileDownloadQueueSet
        final FileDownloadQueueSet queueSet = new FileDownloadQueueSet(fileDownloadListener);
        //2、创建Task 队列
        final List<BaseDownloadTask> tasks = new ArrayList<>();
        final ViewHolder tag = new ViewHolder(downloadList.size(), packageName);
        BaseDownloadTask baseDownloadTask = FileDownloader.getImpl().create(downloadUrl)
                .setPath(Environment.getExternalStorageDirectory().getAbsolutePath() + "/" + apkName)
                .setCallbackProgressTimes(300)
                .setMinIntervalUpdateSpeed(400)
                .setTag(tag)
                .setForceReDownload(true)
                .setWifiRequired(true);
        tasks.add(baseDownloadTask);
        //3、设置参数
        queueSet.setCallbackProgressTimes(100);
        queueSet.setCallbackProgressMinInterval(100);
        //失败重试次数
        queueSet.setAutoRetryTimes(3);
        //避免掉帧
        FileDownloader.enableAvoidDropFrame();
        // 并行执行该任务队列
//        queueSet.downloadTogether(tasks);
        // 串行执行该任务队列
        queueSet.downloadSequentially(tasks);
        queueSet.start();

**Comment by rantianhua** [comment]
你使用的代码有个不必要的地方：
```
BaseDownloadTask baseDownloadTask = FileDownloader.getImpl().create(downloadUrl)
.setPath(Environment.getExternalStorageDirectory().getAbsolutePath() + "/" + apkName)
.setCallbackProgressTimes(300)
.setMinIntervalUpdateSpeed(400)
.setTag(tag)
.setForceReDownload(true)
.setWifiRequired(true);
tasks.add(baseDownloadTask);
//3、设置参数
queueSet.setCallbackProgressTimes(100);
queueSet.setCallbackProgressMinInterval(100);
```
如果你给 queueSet 设置了 progress times 和 min interval ，那么构建 Task 时设置的参数会被覆盖，所以你只在一个地方设置即可。

--- 

关于状态一直在 pending ，这个我需要看了日志才能判断是什么问题，所以请提供下 FileDownloader 的日志。
