### ISSUE TITLE
https问题（已看问题#437）

### ISSUE THREAD

**Issue by xyZangGit** [lingochamp/FileDownloader#1163]
log日志：
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

测试下载链接：

下载文件原来是http，现在换成https出现这个错误：
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
看到问题锦集437，具体是如何绕过证书校验
这个地方具体代码需要怎么写？没有太理解，怎么定制？
你可以定制自己的FileDownloadUrlConnection来绕过证书校验，可以通过FileDownloader.setupOnApplicationOnCreate(this).connectionCreator(...).commit()来传入你的FileDownloadUrlConnection

**Comment by 50kg** [comment]
楼主解决了吗？
