### ISSUE TITLE
我想问下okdownload不维护了么？

### ISSUE THREAD

**Issue by kerneltea** [lingochamp/FileDownloader#1165]
我想问下okdownload不维护了么？
从FileDownloader的readme上看介绍说建议我们用okdownload，看最后更新记录，都是两三个月前的，而且issues列表也没有人维护了，反而这个说不维护的FileDownloader更新的却很频繁，issues列表也一直在有回复。
如果说okdownload不维护，不更新，请说清楚嘛。不要让大家都去用okdownload.
从现在的情况来看。。并不是很想让人们用OkDownload呀

**Comment by rantianhua** [comment]
没有，主要是最近都特别忙，所以 OkDownload 那边回复很慢，请谅解。不过开源项目的话，也欢迎大家帮助解决问题，提相关的 Pull Request。
