### ISSUE TITLE
从1.6.9更新到1.7.5部分之前任务继续下载出现Requested Range Not Satisfiable问题

### ISSUE THREAD

**Issue by qwwuyu** [lingochamp/FileDownloader#1168]
**从1.6.9更新到1.7.5 部分任务请求头从Range=[bytes=25046605-]变成Range=[bytes=25046605-0]**
(如果在1.7.5上创建任务再回到1.6.9的继续下载,请求头会从Range=[bytes=25046605-]变成Range=[bytes=25046605--1])
导致连接创建失败,下面是大致日志,具体出错在HTTP/1.1 416 Requested Range Not Satisfiable.

**v1.6.9产生的任务使用v1.7.5的请求头**
D/FileDownloader.ConnectTask: <---- -1189118502 request header {If-Match=["5c0b79f9-2216fa0"], Range=[bytes=0-0], User-Agent=[FileDownloader/1.7.5]}
D/FileDownloader.ConnectTask: <---- -1189118502 request header {If-Match=["5c0b79f9-2216fa0"], Range=[bytes=1726298-11915231], User-Agent=[FileDownloader/1.7.5]}
D/FileDownloader.ConnectTask: <---- -1189118502 request header {If-Match=["5c0b79f9-2216fa0"], Range=[bytes=13217018-23830463], User-Agent=[FileDownloader/1.7.5]}
D/FileDownloader.ConnectTask: <---- -1189118502 request header {If-Match=["5c0b79f9-2216fa0"], **Range=[bytes=25046605-0]**, User-Agent=[FileDownloader/1.7.5]}
**v1.7.5产生的任务请求头使用v1.7.5的请求头**
D/FileDownloader.ConnectTask: <---- -1359419612 request header {If-Match=["5c0b79f9-2216fa0"], Range=[bytes=0-0], User-Agent=[FileDownloader/1.7.5]}
D/FileDownloader.ConnectTask: <---- -1359419612 request header {If-Match=["5c0b79f9-2216fa0"], Range=[bytes=2317602-11915231], User-Agent=[FileDownloader/1.7.5]}
D/FileDownloader.ConnectTask: <---- -1359419612 request header {If-Match=["5c0b79f9-2216fa0"], Range=[bytes=14052602-23830463], User-Agent=[FileDownloader/1.7.5]}
D/FileDownloader.ConnectTask: <---- -1359419612 request header {If-Match=["5c0b79f9-2216fa0"], **Range=[bytes=25967834-]**, User-Agent=[FileDownloader/1.7.5]}
**v1.6.9产生的任务响应**
D/FileDownloader.ConnectTask: ----> -1189118502 response header {null=[HTTP/1.1 206 Partial Content], Cache-Control=[max-age=7200], Connection=[keep-alive], Content-Length=[1], Content-Range=[bytes 0-0/35745696], Content-Type=[application/octet-stream], Date=[Fri, 04 Jan 2019 04:10:31 GMT], ETag=["5c0b79f9-2216fa0"], Expires=[Fri, 04 Jan 2019 06:10:31 GMT], Last-Modified=[Sat, 08 Dec 2018 07:59:53 GMT], Server=[nginx/1.11.7], X-Android-Received-Millis=[1546575033888], X-Android-Response-Source=[NETWORK 206], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1546575033872]}
D/FileDownloader.ConnectTask: ----> -1189118502 response header {null=[HTTP/1.1 206 Partial Content], Cache-Control=[max-age=7200], Connection=[keep-alive], Content-Length=[10086904], Content-Range=[bytes 1828328-11915231/35745696], Content-Type=[application/octet-stream], Date=[Fri, 04 Jan 2019 04:10:31 GMT], ETag=["5c0b79f9-2216fa0"], Expires=[Fri, 04 Jan 2019 06:10:31 GMT], Last-Modified=[Sat, 08 Dec 2018 07:59:53 GMT], Server=[nginx/1.11.7], X-Android-Received-Millis=[1546575033945], X-Android-Response-Source=[NETWORK 206], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1546575033918]}
D/FileDownloader.ConnectTask: ----> -1189118502 **response header {null=[HTTP/1.1 416 Requested Range Not Satisfiable]**, Cache-Control=[max-age=7200], Connection=[keep-alive], Content-Length=[213], Content-Range=[bytes */35745696], Content-Type=[text/html], Date=[Fri, 04 Jan 2019 04:10:31 GMT], Expires=[Fri, 04 Jan 2019 06:10:31 GMT], Server=[nginx/1.11.7], X-Android-Received-Millis=[1546575034018], X-Android-Response-Source=[NETWORK 416], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1546575033956]}
D/FileDownloader.ConnectTask: ----> -1189118502 response header {null=[HTTP/1.1 206 Partial Content], Cache-Control=[max-age=7200], Connection=[keep-alive], Content-Length=[10544185], Content-Range=[bytes 13286279-23830463/35745696], Content-Type=[application/octet-stream], Date=[Fri, 04 Jan 2019 04:10:31 GMT], ETag=["5c0b79f9-2216fa0"], Expires=[Fri, 04 Jan 2019 06:10:31 GMT], Last-Modified=[Sat, 08 Dec 2018 07:59:53 GMT], Server=[nginx/1.11.7], X-Android-Received-Millis=[1546575034221], X-Android-Response-Source=[NETWORK 206], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1546575033956]}
**v1.7.5产生的任务响应**
D/FileDownloader.ConnectTask: ----> -1359419612 response header {null=[HTTP/1.1 206 Partial Content], Cache-Control=[max-age=7200], Connection=[keep-alive], Content-Length=[1], Content-Range=[bytes 0-0/35745696], Content-Type=[application/octet-stream], Date=[Fri, 04 Jan 2019 04:10:44 GMT], ETag=["5c0b79f9-2216fa0"], Expires=[Fri, 04 Jan 2019 06:10:44 GMT], Last-Modified=[Sat, 08 Dec 2018 07:59:53 GMT], Server=[nginx/1.11.7], X-Android-Received-Millis=[1546575046560], X-Android-Response-Source=[NETWORK 206], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1546575046499]}
D/FileDownloader.ConnectTask: ----> -1359419612 response header {null=[HTTP/1.1 206 Partial Content], Cache-Control=[max-age=7200], Connection=[keep-alive], Content-Length=[8807480], Content-Range=[bytes 15022984-23830463/35745696], Content-Type=[application/octet-stream], Date=[Fri, 04 Jan 2019 04:10:44 GMT], ETag=["5c0b79f9-2216fa0"], Expires=[Fri, 04 Jan 2019 06:10:44 GMT], Last-Modified=[Sat, 08 Dec 2018 07:59:53 GMT], Server=[nginx/1.11.7], X-Android-Received-Millis=[1546575046623], X-Android-Response-Source=[NETWORK 206], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1546575046593]}
D/FileDownloader.ConnectTask: ----> -1359419612 response header {null=[HTTP/1.1 206 Partial Content], Cache-Control=[max-age=7200], Connection=[keep-alive], Content-Length=[9610296], Content-Range=[bytes 26135400-35745695/35745696], Content-Type=[application/octet-stream], Date=[Fri, 04 Jan 2019 04:10:44 GMT], ETag=["5c0b79f9-2216fa0"], Expires=[Fri, 04 Jan 2019 06:10:44 GMT], Last-Modified=[Sat, 08 Dec 2018 07:59:53 GMT], Server=[nginx/1.11.7], X-Android-Received-Millis=[1546575046742], X-Android-Response-Source=[NETWORK 206], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1546575046642]}
D/FileDownloader.ConnectTask: ----> -1359419612 response header {null=[HTTP/1.1 206 Partial Content], Cache-Control=[max-age=7200], Connection=[keep-alive], Content-Length=[8987695], Content-Range=[bytes 2927537-11915231/35745696], Content-Type=[application/octet-stream], Date=[Fri, 04 Jan 2019 04:10:44 GMT], ETag=["5c0b79f9-2216fa0"], Expires=[Fri, 04 Jan 2019 06:10:44 GMT], Last-Modified=[Sat, 08 Dec 2018 07:59:53 GMT], Server=[nginx/1.11.7], X-Android-Received-Millis=[1546575046753], X-Android-Response-Source=[NETWORK 206], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1546575046644]}

**Comment by rantianhua** [comment]
我看你贴的请求应该都是 1.7.5 版本的吧？

**Comment by qwwuyu** [comment]
> 我看你贴的请求应该都是 1.7.5 版本的吧？

下载都是1.7.5,但是这个任务是v1.6.9创建的,使用1.7.5版本继续下载时候的请求头.和1.7.5直接创建任务再继续下载的请求头Range不一样.

不过更新后1.7.5后之前续传失败的部分任务现在都可以正常用了,非常感谢.

**Comment by congwiny** [comment]
@Jacksgong @rantianhua 
我对这个问题修复了一下。看看可以吗？
https://github.com/lingochamp/FileDownloader/pull/1234/commits/68ba999f61cd9b7e5953ec1e44e4342b0f27b5e0

**Comment by rantianhua** [comment]
在 1.6.9 版本的时候用 0 标记的 endofffset ，但是之后为了修复一个 bug 用 -1 标记了 endoffset ，所以确实有这个问题。你修复的代码是 OK 的，请提一个 MR 到 FileDownloader ，万分感谢。

**Comment by congwiny** [comment]
> 在 1.6.9 版本的时候用 0 标记的 endofffset ，但是之后为了修复一个 bug 用 -1 标记了 endoffset ，所以确实有这个问题。你修复的代码是 OK 的，请提一个 MR 到 FileDownloader ，万分感谢。

已经提交了哈~

**Comment by congwiny** [comment]
@rantianhua 已经提交了哈~
