### ISSUE TITLE
下载下来的文件名不正确

### ISSUE THREAD

**Issue by icetea0822** [lingochamp/FileDownloader#1170]
您好
  请问我下载的文件名跟服务器中的文件名不对，我看到有其他人提issue说是因为没有Content-Disposition,但是我这边的服务器端没有办法加这个，我是直接传入url进行下载的，这个出了服务器端去加上Content-Disposition以外还有别的办法把文件名改为原本的文件名吗？谢谢

**Comment by rantianhua** [comment]
在你不设置文件名的情况下，FileDownoader 会依据 response header 里面的 Content-Disposition 设置文件名，如果没有，那么使用 url 的 md5 值作为文件名。

你这种情况只能自己设置文件名。

**Comment by icetea0822** [comment]
> 在你不设置文件名的情况下，FileDownoader 会依据 response header 里面的 Content-Disposition 设置文件名，如果没有，那么使用 url 的 md5 值作为文件名。
> 
> 你这种情况只能在构建 Task 的时候自己设置文件名。

请问如何设置呢？因为我需要在progress的回调里面比对文件名，我想在下载开始前就把文件名改掉

**Comment by rantianhua** [comment]
参见 Wiki : https://github.com/lingochamp/FileDownloader/wiki/BaseDownloadTask  ，`setPath` 方法说明得很清楚。

**Comment by icetea0822** [comment]
> 参见 Wiki : https://github.com/lingochamp/FileDownloader/wiki/BaseDownloadTask ，`setPath` 方法说明得很清楚。

好的，麻烦您了
