### ISSUE TITLE
缺少android.permission.FOREGROUND_SERVICE权限

### ISSUE THREAD

**Issue by weikano** [lingochamp/FileDownloader#1171]
如题。
FiledownloaderService.makeServiceForeground方法需要用到FOREGROUND_SERVICE权限，AndroidManifest.xml中没有声明

**Comment by rantianhua** [comment]
多谢提醒！

**Comment by weikano** [comment]
这个权限不是library需要的吗，应该是library负责申明吧。

**Comment by rantianhua** [comment]
library 里面没有任何权限的申明，比如 Network 的权限都是在使用的时候使用放添加，可以参考 demo 。所以我这里也是在 Demo 处添加的。

**Comment by weikano** [comment]
我觉得library有用到的权限，就应该放在library的manifest里面声明才对。作为一个使用者，我可能仅仅是用到某些功能，而不会通篇看源码。像FOREGROUND_SERVICE这个权限，如果没看源码，我是不可能主动去添加的。

**Comment by rantianhua** [comment]
经过讨论，针对 FOREGROUND_SERVICE 这个权限的特殊性，会在 library 里面处理，同时 README 添加说明。再次多谢反馈。
