### ISSUE TITLE
大文件下载

### ISSUE THREAD

**Issue by xhh1993** [lingochamp/FileDownloader#1172]
请问，下载之前并不知道文件是否大于2G，因此默认使用FileDownloadLargeFileListener进行大文件下载会有问题吗？如果在下载列表中是不可能部分使用FileDownloadListener，部分大文件使用FileDownloadLargeFileListener的吧？

**Comment by rantianhua** [comment]
默认使用 `FileDownloadLargeFileListener ` 不会有什么问题，而且它本身也是继承自 `FileDownloadListener ` ，所以在批量下载的时候，你可以给没个 Task 设置自己的 FileDownloadListener ，所以是可以部分使用 `FileDownloadListener ` ，部分使用  `FileDownloadLargeFileListener ` 的。
