### ISSUE TITLE
单任务下载失败后重连次数的问题。

### ISSUE THREAD

**Issue by huangzhiping** [lingochamp/FileDownloader#1173]
hi，各位大哥。想问一下。为什么我在BaseDownloadTask设置了 setAutoRetryTimes 是10。为什么切换网络后，不会重新连接。回调 retry 方法 返回的值是1

 return FileDownloader.getImpl()
                .create(url)
                .setPath(fileName)
                .setMinIntervalUpdateSpeed(400) //设置下载中刷新下载速度的最小间隔
                .setAutoRetryTimes(10) // 任务在下载失败的时候都自动重试一次
                .setCallbackProgressMinInterval(1000)
                .setListener(callback);

回调监听：
    @Override
    protected void retry(BaseDownloadTask task, Throwable ex, int retryingTimes, int soFarBytes) {
        LogUtils.e("剩余次数：" + retryingTimes); //返回1 ？？
        LogUtils.e("task "+ task.getAutoRetryTimes()); //返回10 
    }

**Comment by rantianhua** [comment]
有可能抛出了 `FileDownloadGiveUpRetryException` 导致没有继续重试，所以需要你提供 FileDownoload 的完整日志帮助分析问题。

**Comment by rantianhua** [comment]
No response for a long time.
