### ISSUE TITLE
Add finish listener

### ISSUE THREAD

**Issue by Jeffin21** [lingochamp/FileDownloader#1174]
Is that possible to invoke add finished listener only for filedownload status = compleated ?

**Comment by rantianhua** [comment]
Sure, just like this: 
```
FileDownloader.getImpl().create(url)
    .setPath(path, isDir)
    .setCallbackProgressTimes(300)
    .setMinIntervalUpdateSpeed(400)
    .setTag(tag)
    .addFinishListener(new BaseDownloadTask.FinishListener() {
        @Override
        public void over(BaseDownloadTask task) {
            
        }
    })
```

**Comment by Jeffin21** [comment]
@rantianhua I needed a solution to download 2 files one after another, now  when I pause the 1st download the 2nd download will start downloading, there is only one listener available in file downloader, if I take the listener the notification Won't network, is there any way to add two listeners or any workaround for this problem? we tried queue downloading having the same problem, when I pause the 1st download the 2nd download it will start, I needed a solution to download one download task after another,

**Comment by Jeffin21** [comment]
when i pause , the add finish listener invokes

**Comment by Jeffin21** [comment]
how to use FileDownloadSerialQueue ? any code or link ?

**Comment by Jeffin21** [comment]
@rantianhua any sample code ? we didn't found FileDownloadSerialQueue in demo

**Comment by Jeffin21** [comment]
@rantianhua How to use FileDownloadSerialQueue ? didnt find how to use use this in demo

**Comment by Jeffin21** [comment]
@rantianhua just checked the FileDownloadSerialQueue having the same problem, when I downloading the 1st file and pause , the 2nd file started downloading, i wanted to start the 2nd file after finished downloading the 1st file

**Comment by Jeffin21** [comment]
can you provide a simple  code? coz we didnt find the sample in demo
thank you

**Comment by rantianhua** [comment]
Just like this: 
```
FileDownloadSerialQueue fileDownloadSerialQueue=new FileDownloadSerialQueue();
BaseDownloadTask task2 = ...
BaseDownloadTask task1 = FileDownloader.getImpl().create(url)
    .setXXX(xxx)
    .addFinishListener(new BaseDownloadTask.FinishListener() {
        @Override
         public void over(BaseDownloadTask task) {
             if (task.getStatus() == FileDownloadStatus.completed) {
                 fileDownloadSerialQueue.enqueue(task2);
             }
        }
    });
fileDownloadSerialQueue.enqueue(task1);
```

**Comment by Jeffin21** [comment]
@rantianhua  while the status is not completed -when I pause the download. After I resume addFinishlistener will not invoke again when the download completed

**Comment by Jeffin21** [comment]
@rantianhua is there any way to remove invoke of add finish listener in pause?
