### ISSUE TITLE
第三方CDN不返回Content-Length导致下载文件大小不正确

### ISSUE THREAD

**Issue by qyzhaojinxi** [lingochamp/FileDownloader#1175]
第三方CDN服务器返回数据偶尔出现response header中不包含Content-Length的情况，文件就只有单个线程下载，最终下载完成后文件大小比真实的多了二十几个字节
1.7.5版本

**Comment by rantianhua** [comment]
应该是不包含 1 `Content-Range` 吧，这种情况下确实采用流式下载，因为没办法知道具体文件大小时多少。至于文件大小不符，得先确认下改文件是否为动态更新的文件？此外没有日志的话，无法提供更多帮助，所以我先关掉了，有了日志信息后你可以重新 reopen 这个 issue 。
