### ISSUE TITLE
301重定向后下载问题

### ISSUE THREAD

**Issue by royorange** [lingochamp/FileDownloader#1176]
version: 1.7.5
后台提供的一个url会先进行重定向，经调查会在该页面中会有js通过href触发跳转下载：
![image](https://user-images.githubusercontent.com/12166563/51257349-5cb24100-19e2-11e9-825a-92e65a1bde2f.png)
对于这种场景，是否能下载到最终的文件？
已参考该[文档](https://github.com/lingochamp/FileDownloader/wiki/NOT-SUPPORT-302%E3%80%81307..%3F)，仍然无法成功下载。

**Comment by rantianhua** [comment]
还想追问一下，是只有一次 redirect 吗？还是多次？

**Comment by rantianhua** [comment]
原来如此，如果第一个请求时 200 的话，那其实没有触发 FileDownloader 的重定向处理逻辑。谢谢提供了这种 case 的具体情况。

**Comment by royorange** [comment]
@rantianhua 准确点说在www站的时候第一个请求是301的 301到m站点，但是这个m站点是200。
然而由于href的跳跃，使得在浏览器是成功会进行最后一次跳转到正确的location，但是下载器就不行了。
总不能让下载器去扫html来分析吧 🤣
