### ISSUE TITLE
下载文件时得到412

### ISSUE THREAD

**Issue by icetea0822** [lingochamp/FileDownloader#1177]
您好 
   我下载文件时遇到了412返回的错误，但是服务端也不知道该怎样改。
  这种可以通过我这边关闭断点续传之类的解决掉吗？如果可以的话可以帮忙提供一下如何解决吗？谢谢！

**Comment by icetea0822** [comment]
已解决
重写了FileDownloadUrlConnection里面的addHeader方法，把Range对应的值改为bytes=0-

**Comment by rantianhua** [comment]
> 已解决
> 重写了FileDownloadUrlConnection里面的addHeader方法，把Range对应的值改为bytes=0-

这样风险很大的，不是真正解决问题的方法，希望题型一份 FileDownloader 的日志，看看具体是什么问题。

**Comment by rantianhua** [comment]
长时间未回复，先关掉了。

**Comment by congwiny** [comment]
@rantianhua 
http://xxxy.shou.edu.cn/2019/0124/c6683a239898/page.htm
网页内容附件，下载失败，状态码返回412。Range对应的值改为bytes=0- 确实可解。有没有更好的办法？ (filedownloader版本1.7.6)
