### ISSUE TITLE
android 6,7 download usb 失敗

### ISSUE THREAD

**Issue by jiaLian** [lingochamp/FileDownloader#1178]
在android 6, 7 以上版本，下載至usb,外部sd卡裝置會失敗。
已經有開啟uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" ，
自己好像有什麼步驟少了，一直下載不了。同樣的code內存下載是可以。

**Comment by rantianhua** [comment]
你需要在 runtime 的时候申请读写外部存储的权限，这跟 FileDownloader 无关，是 Android 6 开始加强了权限管理。
