### ISSUE TITLE
java.net.ProtocolException: unexpected end of stream

### ISSUE THREAD

**Issue by zhouhui520w** [lingochamp/FileDownloader#1179]
<img width="1207" alt="4" src="https://user-images.githubusercontent.com/8720881/51382442-d0269080-1b51-11e9-92da-2a42b7703bb4.png">

**Comment by rantianhua** [comment]
Please refer to #1059 .

**Comment by zhouhui520w** [comment]
The reason I found is that the back end does not support short continuation, thank you
