### ISSUE TITLE
single notification for different download files

### ISSUE THREAD

**Issue by deeppandya** [lingochamp/FileDownloader#118]
Hello,

Currently i am working with FileDownloadNotificationListener to download many download files. my issues is everytime i start the download task, it's not creating new notification with progress. but instead it overrides the previous file's notification. Let's say, i started i started downloading for file1 and then i started downloading for file2, it's not creating two separate notifications. instead it's updating the notification with the file1's notification.

Can you please check it ?

Thanks for your help.

**Comment by Jacksgong** [comment]
In FileDownloadNotificationListener Architecture,  Each `BaseNotificationItem` is a bind to a single task, If you want to show a separate notification for each `BaseNotificationItem`，just use `getManager().notify(getId(), notification);`  in `BaseNotificationItem#show`.

I think you are confused with the `FileDownloader.getImpl().startForeground`, This is another function, what can let the FileDownloadService in the Foreground status, In this occasion, There is only a Notification would be shown by Android OS, what is controlled by Android OS.
