### ISSUE TITLE
如何区分开是因网络暂停的任务还是因用户主动操作暂停的任务？

### ISSUE THREAD

**Issue by jhwsx** [lingochamp/FileDownloader#1183]
#### Before Issue
无

#### Issue

1. What problem do you get?

我这边希望根据网络变化来暂停开启任务，请问一下，filedownloader 有没有提供回调值，可以区分清是网络中断导致的停止下载。

---

请在Issue前认真的跟进上面提到的建议，这样将可以极大的加快你遇到问题的处理。

**Comment by rantianhua** [comment]
如果下载过程中网络出现了网络问题，那么会抛出异常，此时的状态会变为 error 。FileDownloader 本身不会去监听网络的变化，因为网络的变化最终会体现在下载结果里。

**Comment by jhwsx** [comment]
好的，谢谢您！
