### ISSUE TITLE
是否应该迁移到 okdownload？

### ISSUE THREAD

**Issue by zhenian** [lingochamp/FileDownloader#1184]
#### Issue

FileDownloader 的 issues 越积越多。看样子重心全在 okdownload 了。

FileDownloader 1.7.5 在 Aug 3, 2018 发布后，一直没更新版本。 

请问，后继 FileDownloader 的开发维护的规划是如何的？
作为用户是否应该迁移到 okdownload？？

**Comment by rantianhua** [comment]
年后会有计划出文档，帮助用户无缝切换到 OkDownload ，请耐心等待。

**Comment by zhenian** [comment]
缝切换到 OkDownload 的文档出来了么？

**Comment by 1993xuge** [comment]
同问？有迁移文档吗

**Comment by rantianhua** [comment]
抱歉，一直有各种事情忙，这也算是再次提醒了，我再加个日程。

**Comment by rantianhua** [comment]
目前无缝迁移的模块已经完成，请关注：https://github.com/lingochamp/okdownload/pull/331 。接下来会再写一份详细的文档说明，然后发布 OkDownload 1.0.7-SNAPSHOT 让大家尝试。

**Comment by rantianhua** [comment]
专门写了一篇文章介绍如何无缝切换：https://juejin.im/post/5dc527fcf265da4d3429ab5c 。这个就先关掉了。
