### ISSUE TITLE
pause 失效

### ISSUE THREAD

**Issue by JacksenLaw** [lingochamp/FileDownloader#1187]
FileDownloader.FileDownloader: request pause but not exist 2024840949

**Comment by rantianhua** [comment]
仅凭这一行日志并不能得出你标题的结论，出现改行日志的情况有：

1.  该 Task 已经出现 error 之后调用了 pause 方法。
2. 该 Task 已经下载完成之后调用了 pause 方法。
3. 该 Task 已经被暂停之后又调用了 pause 方法。

所以请按照 issue 模板重新提 issue 。
