### ISSUE TITLE
重复下载一个资源后,之前下载的本地资源会被删除

### ISSUE THREAD

**Issue by yyfBlog** [lingochamp/FileDownloader#1188]
#### Before Issue

1. Please search on the [Issues](https://github.com/lingochamp/FileDownloader/issues)
2. Please search on the [wiki](https://github.com/lingochamp/FileDownloader/wiki)
3. Please set `FileDownloadLog.NEED_LOG=true` and review the Logcat output from main process and `:filedownloader` process ( pay attention to Warn and Error level logcat)

#### Issue

1. What problem do you get?
2. Which version of FileDownloader are you using when you produce such problem?
3. How to reproduce such problem?
4. Do you set `FileDownloadLog.NEED_LOG=true`?
5. Could you please reproduce this problem and provide all main process and `:filedownloader` process logcat 
6. Can you fix it by yourself and request PR, if not, what's problem do you get when you try to fix it

>P.S. If you don't know how to get `:filedownloader` process, it's recommended to using `pidcat` to just filter all your application logcat, or define `process.non-separate=true` on [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)

---

请在Issue前认真的跟进上面提到的建议，这样将可以极大的加快你遇到问题的处理。
重复下载一个资源后,之前下载的本地资源会被删除

**Comment by rantianhua** [comment]
请说清楚，是你要下载的资源被清楚了还是有资源 A B C ... ，你重复下载 A ，结果之前已经下载的 B C ... 被删除了？还有请务必按照模板提供尽可能详细的信息。

**Comment by yyfBlog** [comment]
1.第一次下载了3个图片,本地目录中存在着三张图片,第二次重复下载其中一张图片,本地中的这张图片会被移除,回调方法如下:
02-18 08:48:33.780 2709-2709/com.example.testdownload D/MainActivity: pending: 
02-18 08:48:34.030 2709-2709/com.example.testdownload D/MainActivity: connected: 
02-18 08:48:34.180 2709-2762/com.example.testdownload D/MainActivity: blockComplete: 
02-18 08:48:34.190 2709-2709/com.example.testdownload D/MainActivity: completed:

**Comment by yyfBlog** [comment]
1.第一次下载3张图片,下载成功,本地图片也能够保存正常,在次重复下载三张,本地的三张图片会被移除(换言之 只要是重复下载的,下载一张 移除本地一张  下载两张  移除本地两张) ,以下是回调方法顺序
02-18 11:05:03.230 6423-6423/com.example.testdownload D/MainActivity: pending: 
02-18 11:05:03.240 6423-6423/com.example.testdownload D/MainActivity: pending: 
    warn: 
02-18 11:05:03.250 6423-6423/com.example.testdownload D/MainActivity: warn: 
    pending: 
02-18 11:05:03.580 6423-6423/com.example.testdownload D/MainActivity: connected: 
02-18 11:05:03.590 6423-6423/com.example.testdownload D/MainActivity: connected: 
02-18 11:05:03.610 6423-6423/com.example.testdownload D/MainActivity: connected: 
02-18 11:05:03.760 6423-6492/com.example.testdownload D/MainActivity: blockComplete: 
02-18 11:05:03.770 6423-6423/com.example.testdownload D/MainActivity: completed: /mnt/internal_sd/testImg/ddfeca62a90576bd95f22a2df9d5ab70
02-18 11:05:04.270 6423-6493/com.example.testdownload D/MainActivity: blockComplete: 
02-18 11:05:04.280 6423-6423/com.example.testdownload D/MainActivity: completed: /mnt/internal_sd/testImg1/a30682dcfa810e324ff958631cf5f6b9
02-18 11:05:05.410 6423-6496/com.example.testdownload D/MainActivity: blockComplete: 
02-18 11:05:05.420 6423-6423/com.example.testdownload D/MainActivity: completed: /mnt/internal_sd/testImg1/51084ed7631b257db802246e8786430c
