### ISSUE TITLE
请问如何在当前线程下载

### ISSUE THREAD

**Issue by fanmingyi** [lingochamp/FileDownloader#1190]
在某个需求下，我自行开启了子线程请问如何在当前线程下开始下载呢

**Comment by rantianhua** [comment]
你是指下载文件流的操作所在的线程吗？如果是的话，那么这个是无法指定线程的，FileDownloader 内部维护了自己的线程池去操作，而且这个也没理由进行线程指定。如果理解有误的话，请再详细说明一下。

**Comment by fanmingyi** [comment]
在kotlin有协程库，有时候我会在下载前已经开启了协程 做了其他事情 然后想在协程中直接下载文件而不是重新开启另一个线程，博主考虑开一个分支更好支持协程吗？我相信很多人愿意共享和维护这个分支

**Comment by abner89** [comment]
可以支持回调不要强制回调到主线程吗？

**Comment by rantianhua** [comment]
@abner89 这个是有的，详情见：`BaseDownloadTask#setSyncCallback`
