### ISSUE TITLE
下载流文件失败

### ISSUE THREAD

**Issue by oarage** [lingochamp/FileDownloader#1191]
IOS下载是好的,Android下载流文件失败,提示如下:
Connection failed with request[{Range=[bytes=0-], User-Agent=[FileDownloader/1.7.5]}] response[{null=[HTTP/1.1 201 Created], Connection=[keep-alive], Content-Disposition=[attchement;filename=archive.zip], Content-Length=[2054], Content-Type=[application/octet-stream], Date=[Wed, 20 Feb 2019 09:17:24 GMT], Server=[nginx/1.4.6 (Ubuntu)], X-Android-Received-Millis=[1550654247612], X-Android-Response-Source=[NETWORK 201], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1550654247597]}] http-state[201] on task[-1040270803--1], which is changed after verify connection, so please try again.

**Comment by oarage** [comment]
下载流文件的时候,是没有长度的,这个时候就下载不了了

**Comment by rantianhua** [comment]
方便提供一下 url 好进行验证吗？可以的话请发我邮箱：vesperdone@gmail.com
