### ISSUE TITLE
1.7.6 卡在pending

### ISSUE THREAD

**Issue by XunMengWinter** [lingochamp/FileDownloader#1195]
重现很简单。

断网，下载一个任务，error，然后5秒后重试（只要error就重试）；

过几秒，联网；

再断网，卡pending！！！

**Comment by congwiny** [comment]
下载的地址能提供一下吗？

**Comment by rantianhua** [comment]
@XunMengWinter 为了加快定位问题，请你提供一下完整日志。另外，你是在我们的 demo 上复现的吗？
