### ISSUE TITLE
读取数据库时引发NPE

### ISSUE THREAD

**Issue by zsigui** [lingochamp/FileDownloader#1196]
你好，我们项目在使用库的过程中遇到了如下NPE崩溃，看异常上报量，占到我们失败率的接近一半量。希望能帮忙接近该异常，非常感谢

相关堆栈信息与关键点Mapping如下：
![image](https://user-images.githubusercontent.com/5293511/54067593-d47f4800-427c-11e9-904d-cce08339bb12.png)

com.liulishuo.filedownloader.b.a.b(int) 对应  com.liulishuo.filedownloader.database.FileDownloadDatabase.find(int)
com.liulishuo.filedownloader.c.b$a$a.c 对应 com.liulishuo.filedownloader.i.IFileDownloadIPCService$Stub$Proxy.clearAllTaskData()
com.liulishuo.filedownloader.o.b 对应 com.liulishuo.filedownloader.FileDownloadServiceUIGuard.getService()
com.liulishuo.filedownloader.m.b 对应com.liulishuo.filedownloader.FileDownloadServiceProxy.getSofar(int)
com.liulishuo.filedownloader.q.a 对应 com.liulishuo.filedownloader.FileDownloader.getImpl()

**Comment by rantianhua** [comment]
请提供下使用的版本。

**Comment by rantianhua** [comment]
Same as #1180.
