### ISSUE TITLE
How can i set download limit speed and thread per download for this?

### ISSUE THREAD

**Issue by dinhlamvn** [lingochamp/FileDownloader#1198]
Hi,
Before, thank for your lib, it very good.
But i need to set download limit speed per download item and number of thread for it. I don't see same issue, can you help me resolve it? Tks

**Comment by rantianhua** [comment]
You have two question in fact. The first is that you want to set download limit speed, we are sorry that FileDownloader doesn't support it(Maybe we will consider this requirement in OkDownload). The second is that you want to set download thread number, you can do it by custom `ConnectionCountAdapter` and you can have a look at [here](https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component) to know about the detail.
