### ISSUE TITLE
setCallbackProgressTimes

### ISSUE THREAD

**Issue by ayou6232290** [lingochamp/FileDownloader#12]
对这个回调次数不是很理解,能简单说明一下吗.

**Comment by Jacksgong** [comment]
好的。也可以先参看下这里的[接口说明](https://github.com/lingochamp/FileDownloader/blob/master/README-zh.md)

#### 简单来说:
设置progress最大回调次数。

---

回调接口类(`FileDownloadListener`)拥有回调: `pending`、`connected`、`progress`、`blockComplete`、`completed`等。
其中`progress`的进度回调有时候我们需要用作进度条的进度，`setCallbackProgressTimes`就是设置这个回调的最大的回调次数。

#### 需要注意:

-  默认值是100次
- 设置小于等于0的值，将不会收到该回调（有时候我们多任务处理的时候不需要这个进度回调）。
- 而之所以是最大值不是一个精确的值，是因为收到文件大小影响，比如文件大小就只有4kb，那么即便设置回调100次，那么最多也只能收到1次`progress`回调，由于我们内部使用单次buffer是4096byte.
- 如果不需要这个回调，将这个回调设置为小于等于0的值，将会使整个下载回调性能提高。
