### ISSUE TITLE
下载途中APP进程被射死，重新打开后如何从上次断开的地方继续下载

### ISSUE THREAD

**Issue by AutumnLeavesss** [lingochamp/FileDownloader#1202]
您好，请问下载到一半关闭了APP进程，然后重新打开APP，发现进度为0，开始下载也不能继续下载，该怎么解决，怎样操作才能从从关闭前的位置重新开始文件的下载

**Comment by roy9527** [comment]
> 您好，请问下载到一半关闭了APP进程，然后重新打开APP，发现进度为0，开始下载也不能继续下载，该怎么解决，怎样操作才能从从关闭前的位置重新开始文件的下载

建立相同存储目录的task再start

**Comment by TsuiYC** [comment]
> > 您好，请问下载到一半关闭了APP进程，然后重新打开APP，发现进度为0，开始下载也不能继续下载，该怎么解决，怎样操作才能从从关闭前的位置重新开始文件的下载
> 
> 建立相同存储目录的task再start

这样不会从断点处下载吧，他是一个新的task了，直接就从0开始了，我的就是
