### ISSUE TITLE
Demo 中NotificationMinSetActivity,NotificationSampleActivity在8.0以上Notification是无法显示的

### ISSUE THREAD

**Issue by dongdaniqng** [lingochamp/FileDownloader#1204]
### 问题
如题:Demo 中NotificationMinSetActivity,NotificationSampleActivity在8.0以上Notification是无法显示的,缺少了channel信息

### 我的解决方案
加上

    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        if (getManager().getNotificationChannel("channelId") == null) {
            getManager().createNotificationChannel(new NotificationChannel("channelId", "channelName",NotificationManager.IMPORTANCE_LOW));
        }
    }

修改

    builder = new NotificationCompat.
            Builder(FileDownloadHelper.getAppContext(),"channelId");

**Comment by rantianhua** [comment]
该问题在 #1224 已修复，你用最新的 Demo 就没有问题了。
