### ISSUE TITLE
FileDownloader已经对Service做targetSdkVersion 26的适配了吗？

### ISSUE THREAD

**Issue by congwiny** [lingochamp/FileDownloader#1205]
android 8.0对targetSdkVersion26的应用的Service做了一些限制：
1. 在不允许其创建后台服务的情况下使用 startService() 函数，则该函数将引发一个 IllegalStateException。
    - 但是可以用 Context.startForegroundService()方法启动一个前台服务，必须在创建服务后的五秒内调用该服务的 startForeground() 函数；
    - 调用startForeground(0, notification) 的id 设置为0是不可以的，直接报ANR

2. 应用进入后台数分钟后，就变成了后台应用，系统将停止该应用的后台服务。

**Comment by rantianhua** [comment]
1.7.5 已经适配了，Wiki 上有说明。
