### ISSUE TITLE
apk文件没下载完就complete 了、导致安装apk时解析包失败

### ISSUE THREAD

**Issue by dfm899** [lingochamp/FileDownloader#1206]
这个问题复现率非常高，有时又不会、今天用vivoY51A 手机必现、
04-19 12:18:20.037 14201-14201/com.googlehelper I/FileDownLoadUtil: 3649494/4083888
04-19 12:18:20.167 14201-14201/com.googlehelper I/FileDownLoadUtil: 3691218/4083888
04-19 12:18:20.277 14201-14201/com.googlehelper I/FileDownLoadUtil: 3732166/4083888
04-19 12:18:20.397 14201-14201/com.googlehelper I/FileDownLoadUtil: 3773114/4083888
04-19 12:18:20.507 14201-14201/com.googlehelper I/FileDownLoadUtil: 3814062/4083888
04-19 12:18:20.597 14201-14201/com.googlehelper I/FileDownLoadUtil: 3855010/4083888
04-19 12:18:20.697 14201-14201/com.googlehelper I/FileDownLoadUtil: 3895958/4083888
04-19 12:18:20.797 14201-14201/com.googlehelper I/FileDownLoadUtil: 3938178/4083888
04-19 12:18:20.877 14201-14201/com.googlehelper I/FileDownLoadUtil: 3979266/4083888
04-19 12:18:20.937 14201-14201/com.googlehelper I/FileDownLoadUtil: 4020214/4083888
04-19 12:18:21.027 14201-14201/com.googlehelper I/FileDownLoadUtil: 4061162/4083888
04-19 12:18:21.107 14201-14201/com.googlehelper I/FileDownLoadUtil: /storage/emulated/0/GoogleHelper/apk/20190418googleplayfwkj.apk下载完毕

从这个日志可以看出soFarBytes 与 totalBytes 不相等 就complete了，到相应目录查看是个.apk文件 并不是 .temp 、打开提示包解析错误、不是完整的包、我看了其它Issues、类似问题也有2-3个、帮忙查找一下问题呗

**Comment by NBXXF** [comment]
解决了么？我也遇到过
