### ISSUE TITLE
如何获取HTTP状态码？

### ISSUE THREAD

**Issue by tiansos110** [lingochamp/FileDownloader#1208]
error方法里抛出的异常，没方法获取到请求码啊？只有一个getErrorCause，返回的是string类型， 想根据请求码自己处理问题怎么办？

**Comment by rantianhua** [comment]
可以考虑对外提供接口或者回调。如果在 `connected` 回调里面添加该参数能满足你的需求吗？

**Comment by rantianhua** [comment]
可以判断 error 的类型是否为 `FileDownloadHttpException` ，然后可以通过 `FileDownloadHttpException#getCode()` 方法获取。
