### ISSUE TITLE
Filename changed after download

### ISSUE THREAD

**Issue by akashk92** [lingochamp/FileDownloader#121]
I want to keep file name same as original downloading file, but download completed filename changes to 'files'

completed: /storage/sdcard/Android/data/parkingmadeeasy.ehc.com.parkingmadesimple/files

My Request:
FileDownloader.getImpl().create("https://api.backendless.com/3ACAA31D-E13B-D3BC-FFEA-D0BBC2918200/v1/files/documents/What%2Bis%2BSmart%2BCity.pdf")
        .setCallbackProgressTimes(0) // why do this? in here i assume do not need for each task callback `FileDownloadListener#progress`,
        .setListener(queueTarget)
        .setPath(HoohaApplication.getAppContext().getExternalFilesDir("").toString())
        .addHeader("Content-disposition", "attachment; filename=What%2Bis%2BSmart%2BCity.pdf")
        .ready();

**Comment by Jacksgong** [comment]
Problem in here: `.setPath(HoohaApplication.getAppContext().getExternalFilesDir("").toString())`

Maybe you need: `.setPath(HoohaApplication.getAppContext().getExternalFilesDir("").toString() + File.separator "What%2Bis%2BSmart%2BCity.pdf")`


For `BaseDownloadTask#setPath`, it doesn't want a directory, it want a absolutely path.

**Comment by Jacksgong** [comment]
Maybe you need to take a look the demo project.

**Comment by akashk92** [comment]
setPath(HoohaApplication.getAppContext().getExternalFilesDir("").toString() + File.separator + "What%2Bis%2BSmart%2BCity.pdf") 


This says " no such file or directory"

**Comment by Jacksgong** [comment]
So your problem is `no such file or directory`. Please look at the `Context#getExternalFilesDir` carefully, Maybe try to do like this: `setPath(HoohaApplication.getAppContext().getExternalFilesDir(null).toString() + File.separator + "What%2Bis%2BSmart%2BCity.pdf")`

**Comment by akashk92** [comment]
So i need to pass null in getExternalFilesDir(). 
Ok i'll give it a try
