### ISSUE TITLE
如何查看日志

### ISSUE THREAD

**Issue by weituotian** [lingochamp/FileDownloader#1210]
发送的请求，能不能log出来，供自己看看url是否正确，header是否正确

**Comment by stefanJi** [comment]
可以使用 `Listener`，在回调中 log. 参考 [wiki start-downloading](https://github.com/lingochamp/FileDownloader/wiki/Start-downloading)

**Comment by weituotian** [comment]
这个FileDownloader太垃圾了，logger都没有。okhttp都有这样的logger的：
![image](https://user-images.githubusercontent.com/7270968/58234288-c1a2ec80-7d70-11e9-977b-9b7641ce62dc.png)

**Comment by rantianhua** [comment]
FileDownloader 内部也有打印这些信息，至于怎么看，你可以参照 https://github.com/Jacksgong/okcat 提高看日志体验。

**Comment by rantianhua** [comment]
最简单你可以过滤 `FileDownloader` 这个 Tag 即可
