### ISSUE TITLE
部分手机下载gif图，图片播放不了

### ISSUE THREAD

**Issue by darkrevier** [lingochamp/FileDownloader#1213]
在oppo r15x中 会出现这种情况，代码如下
 FileDownloader.setup(context);
        FileDownloader fileDownloader = FileDownloader.getImpl();

        fileDownloader.create(url)
                .setPath(createSavePhotoFile("gif").toString())
                .setListener(new FileDownloadSampleListener() {
                    @Override
                    protected void completed(BaseDownloadTask task) {
                      
                    }

                    @Override
                    protected void error(BaseDownloadTask task, Throwable e) {
                    }
                })
                .start();
    }

**Comment by rantianhua** [comment]
请提供完整的 FileDownloader 的版本和日志才能帮你分析问题。或者你提供 url 也可以如果方便的话。
