### ISSUE TITLE
不超时

### ISSUE THREAD

**Issue by qiqinbo** [lingochamp/FileDownloader#1215]
#### Before Issue

1. Please search on the [Issues](https://github.com/lingochamp/FileDownloader/issues)
2. Please search on the [wiki](https://github.com/lingochamp/FileDownloader/wiki)
3. Please set `FileDownloadLog.NEED_LOG=true` and review the Logcat output from main process and `:filedownloader` process ( pay attention to Warn and Error level logcat)

#### Issue

1. What problem do you get?
2. Which version of FileDownloader are you using when you produce such problem?
3. How to reproduce such problem?
4. Do you set `FileDownloadLog.NEED_LOG=true`?
5. Could you please reproduce this problem and provide all main process and `:filedownloader` process logcat 
6. Can you fix it by yourself and request PR, if not, what's problem do you get when you try to fix it

>P.S. If you don't know how to get `:filedownloader` process, it's recommended to using `pidcat` to just filter all your application logcat, or define `process.non-separate=true` on [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)

---

请在Issue前认真的跟进上面提到的建议，这样将可以极大的加快你遇到问题的处理。

**Comment by qiqinbo** [comment]
网速差时，下载70m的文件，进度条经常下载到一半就不动了（手机上显示的网速就几kb），一直不回调失败，希望在这种情况下能响应失败。

**Comment by rantianhua** [comment]
请提供日志，仅凭描述很难帮助你解决问题。

**Comment by rantianhua** [comment]
如果你想设置超时时间的话可以如下操作：
```
FileDownloader.setupOnApplicationOnCreate(this)
                .connectionCreator(new FileDownloadUrlConnection
                        .Creator(new FileDownloadUrlConnection.Configuration()
                        .connectTimeout(15_000) // set connection timeout.
                        .readTimeout(15_000) // set read timeout.
                ))
                .commit();
```

**Comment by XunMengWinter** [comment]
> 如果你想设置超时时间的话可以如下操作：
> 
> ```
> FileDownloader.setupOnApplicationOnCreate(this)
>                 .connectionCreator(new FileDownloadUrlConnection
>                         .Creator(new FileDownloadUrlConnection.Configuration()
>                         .connectTimeout(15_000) // set connection timeout.
>                         .readTimeout(15_000) // set read timeout.
>                 ))
>                 .commit();
> ```

我也遇到了楼主所说的情况，请问超时可以设置单个请求吗？

**Comment by rantianhua** [comment]
@XunMengWinter 目前不支持，可以考虑在 OkDownload 里面支持。
