### ISSUE TITLE
我看您是英语流利说公司的，请问这个项目跟流利说有关系嘛？还是您个人的？

### ISSUE THREAD

**Issue by Liweiwei2Anna** [lingochamp/FileDownloader#1218]
我看您是英语流利说公司的，请问这个项目跟流利说有关系嘛？还是您个人的？

**Comment by Jacksgong** [comment]
不好意思，因为最近新项目很忙无法快速回复信息，项目是建立在lingochamp下面，lingochamp是隶属于流利说的组织，该项目是英语流利说的开源项目。谢谢。
