### ISSUE TITLE
How to get Real Name of A File?

### ISSUE THREAD

**Issue by thatsenam** [lingochamp/FileDownloader#1219]
implementation 'com.liulishuo.filedownloader:library:1.7.6' using this version 
 when i am trying to get file names its returning a random number or may be md5 hash. is it possible to get the real file name. like if i am downloading big_buck_buny.mp4 i should get big_buck_buny.mp4 as file name

**Comment by rantianhua** [comment]
If you've set the file name during you creating the BaseDownloadTask, FileDownloader will use it as the file name, if not, FileDownloader will read `Content-Disposition` from respond header and use read file name. If you don't set file name and no `Content-Disposition`, then Filedownloader will use the hash of  url as the file name.
