### ISSUE TITLE
notification not appear

### ISSUE THREAD

**Issue by renaldi2108** [lingochamp/FileDownloader#1224]
#### Before Issue

1. Please search on the [Issues](https://github.com/lingochamp/FileDownloader/issues)
2. Please search on the [wiki](https://github.com/lingochamp/FileDownloader/wiki)
3. Please set `FileDownloadLog.NEED_LOG=true` and review the Logcat output from main process and `:filedownloader` process ( pay attention to Warn and Error level logcat)

#### Issue

1. What problem do you get? _notification not appear on 1.7.5 version_

>P.S. If you don't know how to get `:filedownloader` process, it's recommended to using `pidcat` to just filter all your application logcat, or define `process.non-separate=true` on [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)

---

请在Issue前认真的跟进上面提到的建议，这样将可以极大的加快你遇到问题的处理。

**Comment by rantianhua** [comment]
What method you use and can you try 1.7.6 version ?

**Comment by renaldi2108** [comment]
I have tried it based on the wiki that you created in **_[this link](https://github.com/lingochamp/FileDownloader/wiki/Compatibility-of-Android-O-Service)_** regarding foreground services, and the references that I use to bring up notifications on **_[this link](https://github.com/lingochamp/FileDownloader/blob/master/demo/src/main/java/com/liulishuo/filedownloader/demo/NotificationSampleActivity.java)_**. I matched this code with the one in the reference I used, but the notification didn't appear but the download process continued.

It looks like something is wrong with your library, especially on the notification manager. I tried to use the notificationmanager without this library and the notification appeared. My advice, try adding it also for the use of foreground, I've tried it this way

```
FileDownloader fileDownloader = new FileDownloader();
fileDownloader.startForeground(getId(), builder.build());
```

and succeed.

**Comment by renaldi2108** [comment]
i want to ask about use foreground service from this library, can it run more than one foreground service? If can it, how do you do it?? I have tried running more than one foreground service, and i have a no results.

Help me in this case @rantianhua

**Comment by rantianhua** [comment]
I will try NotificationSampleActivity at first.

**Comment by rantianhua** [comment]
Yes, the NotificationSampleActivity cannot show notification on Android O and later, I will fix it later.

**Comment by rantianhua** [comment]
You can have more than one foreground service, I will add this sample on the fix.
