### ISSUE TITLE
下载速度确实有问题

### ISSUE THREAD

**Issue by coldmn3** [lingochamp/FileDownloader#1229]
参考了优化方案，爬完了issue还是没有效果。使用原生下载方式或者其他类似类库能跑满，FileDownloader最多只能跑2/3的最大速度。okdownloader也是如此。具体场景是从相机wifi下载照片。

**Comment by VliceZ** [comment]
之前有系统解决过这个问题，问题原因主要有两方面1、框架bug 2、框架的策略，详细的写在[简书](https://www.jianshu.com/p/bf0db2cda0dd)了，希望可以帮助到你。

**Comment by coldmn3** [comment]
> 之前有系统解决过这个问题，问题原因主要有两方面1、框架bug 2、框架的策略，详细的写在[简书](https://www.jianshu.com/u/4557163d19e6)了，希望可以帮助到你。

感谢老哥！试了下果然是你提到的分块策略的bug， 修改了下终于可以跑满速了，再次感谢！！！
