### ISSUE TITLE
The flow callback did not consumed

### ISSUE THREAD

**Issue by uiiang** [lingochamp/FileDownloader#123]
请问，task设置setSyncCallback(true)后，下载进度错误，log提示The flow callback did not consumed，如何处理？

**Comment by Jacksgong** [comment]
进度错误是什么意思? 可以具体点吗，或者指明下在 demo中如何修改以后，会有类似问题。

**Comment by Jacksgong** [comment]
这个log有可能会在一些十分密集或者进程方面比较特殊情况的时候出现，但是并不会将进度打乱。只是一个警告。

**Comment by uiiang** [comment]
可以用FileDownloaderFinal复现， 在DownloaderManager中的startTask方法中，给task设置setSyncCallback(true)，可以复现此问题

**Comment by Jacksgong** [comment]
如果是用 FileDownloaderFinal中遇到，不一定是 FileDownloader 的问题导致的，你可以直接提issue给那个Repo定位问题会快些。

**Comment by Jacksgong** [comment]
Fixed since [v0.3.3](https://github.com/lingochamp/FileDownloader/releases/tag/v0.3.3).
