### ISSUE TITLE
下载进度条无法到达100%

### ISSUE THREAD

**Issue by igding** [lingochamp/FileDownloader#1230]
@Override
            protected void progress(BaseDownloadTask task, int soFarBytes, int totalBytes) {
                if (task.getListener() != downloadListener) {
                    return;
                }
              
                Log.e(percent:" + soFarBytes * 1.0 / totalBytes);
            }

这里的percent有的时候最多到60，有的时候到90，始终无法到达100%

**Comment by igding** [comment]
我指的是多任务下载的时候

**Comment by igding** [comment]
下载和解压都可以成功，就是这里 进度的时候，始终无法到达满的值
例如log展示  soFarBytes:690876,totalBytes:993148 percent:0.6956425427025982

**Comment by igding** [comment]
又调试了一下，一直都无法进入到completed回调中

**Comment by igding** [comment]
complete没走，error也没走，看了log

**Comment by rantianhua** [comment]
请提供完整日志。

**Comment by rantianhua** [comment]
能否在我们的 demo 中复现你的问题？

**Comment by rantianhua** [comment]
No response for a long time.
