### ISSUE TITLE
这个库支持同步下载吗？

### ISSUE THREAD

**Issue by wangsuicheng** [lingochamp/FileDownloader#1237]
有一种需求，在当前线程中同步下载，后续的操作需要阻塞，直到这个文件下载完成或者尝试重复失败之后。

**Comment by rantianhua** [comment]
FileDownloader 不支持同步下载。
不过你所描述的需求，com.liulishuo.filedownloader.util.FileDownloadSerialQueue 可以很好支持，你尽管往这个 queue 里面扔 Task 即可。
