### ISSUE TITLE
chunk问题咨询

### ISSUE THREAD

**Issue by kerneltea** [lingochamp/FileDownloader#1238]
#### Before Issue

1. 请帮忙看下下面两个在OKDOWNLOAD中出现的问题：
[Issues1](https://github.com/lingochamp/okdownload/issues/35)
[Issues2](https://github.com/lingochamp/okdownload/issues/31)

#### Issue
上面的问题是在okdownload上面解决的问题，当时切换到okdownload的时候也是因为fileDownloader并不准备FIX该错误，我想问下，上述问题，现在是否在filedownloader中解决？

**Comment by rantianhua** [comment]
对于 Issues1 ， 我在最新版的 FileDownloader 的 Demo 里试是可以下载的。对于 Issues2 ，你也可以配置单线程下载。

**Comment by kerneltea** [comment]
也就是说，现在这两个问题在filedownloader中都已经fix了

**Comment by rantianhua** [comment]
目前看下来应该不会有这个问题。你可以用最新版本试一下。
