### ISSUE TITLE
1.7.6版本，配置了file.non-pre-allocation=true，下载1G的文件一开始xxx.temp文件就已经是1G的大小了

### ISSUE THREAD

**Issue by DTDeng** [lingochamp/FileDownloader#1239]
如题，在项目及Demo中都尝试了，点击下载后马上暂停，去到下载目录发现.temp文件大小已经是文件大小了。file.non-pre-allocation=true是生效了的而且FileDownloadRandomAccessFile#setLength方法也的确没有执行。

**Comment by DTDeng** [comment]
已找到原因：虽然设置取消了预分配，但是默认的分块策略DefaultConnectionCountAdapter会使得开始下载后FileDownloadRandomAccessFile seek到后面块的位置，文件就增大到了接近原始文件的大小了。取消分块下载返回1可以解决这个问题，但是还有没有更优的方法呢？

**Comment by rantianhua** [comment]
目前 FileDownloader 的策略下确实没有更好的办法，不过预分配会对你使用造成什么影响吗？

**Comment by DTDeng** [comment]
> 目前 FileDownloader 的策略下确实没有更好的办法，不过预分配会对你使用造成什么影响吗？

使用上不会有什么影响，不过在实际应用上如果用户误点了下载然后又暂停掉而这个文件又非常大，这时候已经创建这个文件了占据了不少空间，体验上不太好

**Comment by rantianhua** [comment]
明白，暂时这种情况下，需要使用者维护好文件，具体就是在取消的同时删除目标文件。
