### ISSUE TITLE
进度不刷新

### ISSUE THREAD

**Issue by Gofar** [lingochamp/FileDownloader#124]
我的适配器继承BaseAdapter,用一个HashMap存储ViewHolder,url作为key,在getView()中将ViewHolder放入HashMap.在回调中更新进度
 @Override
        public void downloading(BaseDownloadTask task, int currentBytes, int totalBytes, int progress) {
            ViewHolder holder = mHolderList.get(task.getUrl());
            if (holder != null) {
                holder.updateDownloading(VideoDownloadManager.STATE_DOWNLOADING, currentBytes, totalBytes);
            }
        }
发现进度不刷新

**Comment by Jacksgong** [comment]
这应该不是 FileDownloader 的bug，如果使用方面遇到问题，参考下 GitHub 中的 demo。
