### ISSUE TITLE
预分配+分块出现的下载文件大小问题

### ISSUE THREAD

**Issue by weigtman** [lingochamp/FileDownloader#1242]
07-25 17:33:58.388 D/FileDownloader.FetchDataTask( 3170): require flushAndSync id[-1732704606] index[-1] offset[87620], consume[7]
07-25 17:33:58.388 D/FileDownloader.DownloadLaunchRunnable( 3170): the connection has been completed(-1): [9287, -1)  87620
07-25 17:33:58.388 E/FileDownloader.DownloadLaunchRunnable( 3170): the single task not completed corrected(9287, -1 != 87620) for task(-1732704606)

**Comment by rantianhua** [comment]
可以提供完整的日志吗？或者提供你出现下载问题的链接也可以。
