### ISSUE TITLE
如何能够提前创建服务

### ISSUE THREAD

**Issue by jmzhangyiming** [lingochamp/FileDownloader#1243]
#### Before Issue
目前filedownloader对26的适配是，startForeground创建前台服务，但是我们并不想用户感知到我们在下载离线包。

#### Issue
可以提前开启服务，后续下载任务都在提前开启的服务中执行吗？

**Comment by rantianhua** [comment]
其实这是系统本身的限制。针对 26 的适配，1.7.5 添加的逻辑是，如果开始下载服务时，App 在后台，那么这个 Service 会变成一个前台 Service ，否则程序会挂掉，具体可见 #1078 。

开启服务是使用者自己控制的，什么时候开启服务由你决定，FileDownloader 只能提供开启服务的能力。如果 App 在前台的时候开启下载服务，对用户本身是无感知的，下载过程中退到后台后，只要系统资源还够就不会回收这个下载服务，也还是在静默下载。

综上，针对你的问题。提前开启服务是你自己控制的，比如你在第一个 Activity 的时候就开启下载服务，等后面需要下载的时候，服务已经启动了，不会再启动 Service 。
