### ISSUE TITLE
弃用了本地数据库，并且不使用分块下载的情况下，重新开关机必现无法断点续传问题

### ISSUE THREAD

**Issue by lq19931201** [lingochamp/FileDownloader#1244]
FileDownloader.DownloadTaskHunter: the task[947238671] has been into the launch pool.
08-02 15:21:23.007  8648  8865 D FileDownloader.FileDownloadMessenger: notify begin 947238671@com.liulishuo.filedownloader.DownloadTask@c564e3b
08-02 15:21:23.007  8648  8865 V FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@d518f00 by 11 
08-02 15:21:23.010  8648  8865 D FileDownloader.FileDownloadUtils: can't continue 947238671 the downloaded-record is zero.
08-02 15:21:23.013  8648  8853 D FileDownloader.MessageSnapshotGate: ~~~callback 947238671 old[11] new[1] 1
08-02 15:21:23.013  8648  8853 D FileDownloader.FileDownloadMessenger: notify pending 947238671@com.liulishuo.filedownloader.DownloadTask@c564e3b
08-02 15:21:23.013  8648  8853 D FileDownloader.MessageSnapshotGate: updateKeepFlow
08-02 15:21:23.014  8648  8853 D FileDownloader.MessageSnapshotGate: ~~~callback 947238671 old[1] new[6] 1
08-02 15:21:23.015  8648  8867 D FileDownloader.ConnectTask: <---- 947238671 request header {Range=[bytes=0-0], User-Agent=[FileDownloader/1.7.6]}

**Comment by rantianhua** [comment]
这，哈哈，你把数据库启用了，自然就失去了断点的功能。数据库在这里的作用就是为了断点续传服务的。
