### ISSUE TITLE
java.net.SocketException: Software caused connection abort

### ISSUE THREAD

**Issue by Punishing** [lingochamp/FileDownloader#1245]
问题：下载对话框显示正在下载，按home键切换到后台一两分钟再进入时就报java.net.SocketException: Software caused connection abort或者是报SocketTimeoutException 
版本：1.7.6

而且报这个异常的时候。。只有回到APP界面才能收到 error的回调。。其实在后台已经停止下载了

**Comment by Punishing** [comment]
为什么收到这两个异常的时候 手机APP在后台不会立即走error回调？

**Comment by rantianhua** [comment]
Duplicate with #1249.
