### ISSUE TITLE
为什么收到这SourketException和SourketTimeoutException两个异常的时候 手机APP在后台不会立即走error回调？

### ISSUE THREAD

**Issue by Punishing** [lingochamp/FileDownloader#1246]
而且在后台容易 报这两个错。 每次都会

**Comment by Punishing** [comment]
后台报这两个异常的时候已经停止下载了，但是不会立即走error回调，只有回到App界面的时候才会走error回调。体验不好，希望作者看到能帮忙解决

**Comment by Punishing** [comment]
后台报这两个异常的时候已经停止下载了，但是不会立即走error回调，只有回到App界面的时候才会走error回调。体验不好，希望作者看到能帮忙解决

**Comment by rantianhua** [comment]
Duplicate with #1249.
