### ISSUE TITLE
status问题

### ISSUE THREAD

**Issue by diorslau** [lingochamp/FileDownloader#1248]
FileDownloader.getImpl().create(url).getStatus();
视频已经下载完成,然后调用上面这个方法 为啥返回值不是complete 而是INVALID_STATUS 呢

**Comment by diorslau** [comment]
另外测试了下 正在下载中的时候调用这个方法  返回的也是0

**Comment by rantianhua** [comment]
如果此时没有在下载，在利用该方法时，需要确保下载服务已经开启，否则是获取不到你想要的数据。所以正确的使用姿势可以是这样：
```
FileDownloader.getImpl().bindService(new Runnable() {
    @Override
    public void run() {
        FileDownloader.getImpl().create(url).getStatus();
    }
});
```
或者
```
FileDownloader.getImpl().insureServiceBind().getStatus(id, path);
```
`FileDownloader.getImpl().insureServiceBind()` 会返回一个 `FileDownloadLine` 对象，里面封装了获取任务状态的方法。具体你可以看看 `FileDownloader.getImpl().insureServiceBind()` 的注释。
