### ISSUE TITLE
Pause, resume download - exception - sofar not equal total

### ISSUE THREAD

**Issue by SvehlaJan** [lingochamp/FileDownloader#125]
Hello!

I am encountering an unpleasant error after I resume paused download.
I create download task like this
```
private BaseDownloadTask getDownloadTask(EpisodeEntity product) {
		String fileName = DownloadsUtility.getFileName(product);
		String folderPath = DownloadsUtility.getDownloadsFolderPath(this);
		String filePath = folderPath + "/" + fileName;

		return FileDownloader.getImpl().create(product.getAudioUrl())
				.setPath(filePath)
				.setCallbackProgressTimes(300)
				.setMinIntervalUpdateSpeed(400)
				.setListener(mDownloadListener);
	}
```
Download starts and finished perfectly. However, the problem is when I pause the download manually or the connection is lost.
I resume the download using the same `getDownloadTask()` method and call `.start()`.
Download continues from the last progress but when the download is finished, I get `error()` callback and message in throwable says `sofar[4130846] not equal total[4130847]`.
Did anybody encounter similar error? Am I doing something wrong?

Thanks for help and for this great library!

**Comment by Jacksgong** [comment]
If you occur such exception, it must be the `content-length` which is provided by the server is not equal to the length of the downloaded file.

I think it must be the problem in your server not in FileDownloader, Just consider the architecture in FileDownloader for Resuming:

FileDownloader resumes from the breakpoint, the Breakpoint was saved in FileDownloader Database,  and when you try to resume the download, FileDownloader will seek to the Breakpoint position provided from DB for a file to continue write forward, and request to the server from the Breakpoint to the end of the data, and then, FileDownloader fetches the data from the server. When the buffer from the server is in the end, the downloading is in the end, so FileDownloader will compare the length of the downloaded file with the `content-length` provided by the server.

- Requesting the data from the Breakpoint: [FileDownloadRunnable#addHeader](https://github.com/lingochamp/FileDownloader/blob/master/library/src/main/java/com/liulishuo/filedownloader/services/FileDownloadRunnable.java#L374).
- Seeking to the Breakpoint position for a File: [FileDownloadRunnable#getRandomAccessFile](https://github.com/lingochamp/FileDownloader/blob/master/library/src/main/java/com/liulishuo/filedownloader/services/FileDownloadRunnable.java#L587)
- The buffer from the server is in the end, the downloading is in the end: [FileDownloader#fetch](https://github.com/lingochamp/FileDownloader/blob/master/library/src/main/java/com/liulishuo/filedownloader/services/FileDownloadRunnable.java#L307)

> P.S: Considering to try to resume the download in the demo project has provided by FileDownloader, It would be work well.

**Comment by SvehlaJan** [comment]
Hello.
Thank you for your quick response!
Yes, it looks like there is problem with the `content-length` from server. It works with other servers. I will check more thoroughly next time :-)
Thanks again.

**Comment by Jacksgong** [comment]
Good job :)
