### ISSUE TITLE
1.7.3版本android.database.sqlite.SQLiteFullException: database or disk is full (code 13)

### ISSUE THREAD

**Issue by zzzzKidd** [lingochamp/FileDownloader#1254]
**1.7.3版本还是碰到了这个问题**

08-26 03:06:45.650 E/AndroidRuntime( 9639): android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
08-26 03:06:45.650 E/AndroidRuntime( 9639): 	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
08-26 03:06:45.650 E/AndroidRuntime( 9639): 	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:735)
08-26 03:06:45.650 E/AndroidRuntime( 9639): 	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
08-26 03:06:45.650 E/AndroidRuntime( 9639): 	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
08-26 03:06:45.650 E/AndroidRuntime( 9639): 	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1653)
08-26 03:06:45.650 E/AndroidRuntime( 9639): 	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1599)
08-26 03:06:45.650 E/AndroidRuntime( 9639): 	at com.liulishuo.filedownloader.database.SqliteDatabaseImpl.update(SourceFile:161)
08-26 03:06:45.650 E/AndroidRuntime( 9639): 	at com.liulishuo.filedownloader.database.RemitDatabase.syncCacheToDB(SourceFile:100)
08-26 03:06:45.650 E/AndroidRuntime( 9639): 	at com.liulishuo.filedownloader.database.RemitDatabase.access$200(SourceFile:39)
08-26 03:06:45.650 E/AndroidRuntime( 9639): 	at com.liulishuo.filedownloader.database.RemitDatabase$1.handleMessage(SourceFile:76)
08-26 03:06:45.650 E/AndroidRuntime( 9639): 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-26 03:06:45.650 E/AndroidRuntime( 9639): 	at android.os.Looper.loop(Looper.java:164)
08-26 03:06:45.650 E/AndroidRuntime( 9639): 	at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by rantianhua** [comment]
其实应该是手机空间的问题，FileDownloader 只会保存跟断点有关的信息，下载完成后是不会继续保存的。可以参考 https://stackoverflow.com/a/46210506/6310495 。同时很早之前处理过这个问题，你也可以看看 #206 。

**Comment by zzzzKidd** [comment]
> 其实应该是手机空间的问题，FileDownloader 只会保存跟断点有关的信息，下载完成后是不会继续保存的。可以参考 https://stackoverflow.com/a/46210506/6310495 。同时很早之前处理过这个问题，你也可以看看 #206 。

如果是手机空间的问题，那么应该是在FileDownloader 的回调中处理？还是项目其他代码中处理呢？
谢谢！

**Comment by rantianhua** [comment]
其实默认不需要你管理数据库部分，FileDownloader 用它处理断点，而下载完成的数据都会被清楚掉，所以数据库里面不会持续增加数据。你需要检查你的手机空间主要被什么占满了，不放心的话，可以把 FileDownloader 的数据库 dump 出来看看有多大。
