### ISSUE TITLE
当调用  FileDownloader.getImpl().pause(final int id) 时，暂停的是哪些状态的任务？

### ISSUE THREAD

**Issue by jhwsx** [lingochamp/FileDownloader#1259]
我这边需要暂停的任务比较多（2000+），但是发现在调用这个方法之后，有些任务没有暂停住。就只好在它们在出现 progress 回调时“补刀”（就是再暂停一次），但觉得这样不太好。现在也不知道什么原因？谢谢。

**Comment by rantianhua** [comment]
`FileDownloader.getImpl().pause(final int id)` 是暂停指定任务，如果你需要暂停所有任务，调用 `pauseAll` 方法。

**Comment by jhwsx** [comment]
并不是要暂停全部任务，而是一部分任务。准确地说，是一批任务，比方说暂停2000个（总共有3000个）。

**Comment by rantianhua** [comment]
那建议是，针对需要批量控制的任务，使用同一个 Listener ，比如 3000 中的 2000 个使用同一个 FileDownloadListener ，然后使用 `FileDownloader#pause(FileDownloaderListener)` 防范。

**Comment by jhwsx** [comment]
我今天下午改一下，看可以吗？就是觉得自己要维护管理那些 `FileDownloadListener`，有点麻烦。

**Comment by jhwsx** [comment]
很有效果，谢谢大神。

**Comment by rantianhua** [comment]
OK.
