### ISSUE TITLE
关于多任务下载进度

### ISSUE THREAD

**Issue by MrLiKH** [lingochamp/FileDownloader#126]
使用多任务下载的时候，我发现不走progress方法 ，检测不到当前的下载进度，只能知道单个文件是否下载完成，不能检测单个文件和整体的下载进度，求指导。

**Comment by Jacksgong** [comment]
如果你需要其中单个的进度，只能开启走progress，然后再自己计算整体进度。

否则就只能根据下载多少个文件，然后根据文件大小来计算进度（颗粒度就大了）。

因为多任务下载的时候，只有在某个任务开始建立连接以后，我们才知道那个任务的文件大小，但是引擎中默认同时建立连接数是3个(目前同时建立连接数是[可配置](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)的)，因此在进行多任务的时候，引擎并不知道整个多任务的总大小是多大，因此引擎本身无法给出你想要的颗粒度很小的根据文件大小的进度。

这个可以类比传统的单个流媒体下载，由于无法获知流媒体最终的大小，因此无法提供进度，但是我们可以每个chunked给一个回调（这个可以等比你可以设置progress回调次数然后自己进行计算）。

**Comment by MrLiKH** [comment]
可以每个chunked给一个回调----这个需要怎么做  不是很明白

**Comment by Jacksgong** [comment]
流媒体下载是，未知要下载的流媒体的大小的，因此下载引擎只能 一块 一块的从 输入流中取，取一块内容，写一块，然后再给一个回调告知取了多少资源了。
