### ISSUE TITLE
FileDownloadService$SeparateProcessService未注册

### ISSUE THREAD

**Issue by aa5279aa** [lingochamp/FileDownloader#1261]
这只是一个建议，
新引入FileDownloadService，一直不能运行。由于刚入手不熟悉项目，所以最后排查了整整一下午时间（当然，这期间也对项目结构有了一个大致的了解，也算收获），最终发现是由于library中的mainfest文件没有正常的merge到项目中导致，最后被迫在项目的mainfest中对FileDownloadService$SeparateProcessService进行了注册。
能否在启动service之后启动一个延时任务，检查service是否正常启动。如果未启动，log中进行提示即可。
如果采纳，我愿意完成这项功能，提pr合并到主分支。

**Comment by rantianhua** [comment]
真正的问题应该是为什么 library 的 manifest 没有 merge 到项目中去。
你想知道 Service 有没有启动，可以使用 `FileDownloader#bindService(final Runnable runnable)` 方法，Service 启动后就会执行 runnable 。

**Comment by rantianhua** [comment]
如果你想看日志的话，现在也是有的，FileDownloadService 连接后会有这样一条日志输出：
```
FileDownloader.LostServiceConnectedHandler: The downloader service is connected.
```

**Comment by aa5279aa** [comment]
你好，library中的manifest没有merge到项目中去，推测是因为改了gradle文件，使用了Flavors加载不同路径下的代码文件导致。
其实我遇到的核心问题就是无法下载，只看FileDownloadService的日志，并不知道需要启动service去下载，也没有任何日志提示我需要serivce，所以一时不知道如何处理。
所以当我debug到FileDownloader中BaseFileServiceUIGuard.bindStartByContext方法的时候，发现ActivityManager中的log提示service not found的时候，也就知道问题所在了。
感谢回复！

**Comment by rantianhua** [comment]
FileDownloader 不强制要求你手动控制 Service ，你在任何时候启动一个下载，FileDownloader 会自动检查 Service 是否启动，如果没有启动，会先启动 Service ，等启动成功后自动开始下载，所以这一层可以对使用者透明。

**Comment by aa5279aa** [comment]
其实我表达的就是merge mainfest出异常时，service是不能正常启动的，并且没有log帮助排查到是被阻塞在了serivce未正常启动这个原因上，因为如果不看源码是不知道service下载的。
这个问题就这样把，提这个issue，方便后来有相同问题的人排查。

**Comment by chj233** [comment]
> 其实我表达的就是merge mainfest出异常时，服务是不能正常启动的，并且没有日志帮助排查到是被阻塞在了serivce未正常启动这个原因上，因为知道如果不看源码是不服务下载的 。问题就这样把，提这个问题，方便后面有相同问题的人排查。

太棒了，我就是根据这条issues排查解决了我目前的问题。我这边集成了一个百度的SDK，这个SDK跟我现在的项目有冲突合并时只能用项目的清单文件覆盖所有SDK的清单文件，这样造成了其它所有插件的清单文件失效。如果不在本地项目中配置<service android:name="com.liulishuo.filedownloader.services.FileDownloadService"/>
        <service
            android:name="com.liulishuo.filedownloader.services.FileDownloadService$SeparateProcessService"
            android:process=":filedownloader" />
那么下载就无法启动，解决方案就是将插件中的清单文件复制出来放到项目中
