### ISSUE TITLE
Resume downloaded files throws( java.lang.IllegalArgumentException: Unexpected char )

### ISSUE THREAD

**Issue by AhmedAsser** [lingochamp/FileDownloader#127]
Could not resume files if the default device language does not belong to Arabic numbers Locale (such as Eastern  Arabic or Persian numbers ).

this exception happens because okhttp3 expected ascii code characters for http headers.
i fixed this issue by using : 
String.format(Locale.ENGLISH,........) rather than String.format(........).

**Comment by Jacksgong** [comment]
💯  Thanks so much. I will cover this exception as soon as possible.

**Comment by Jacksgong** [comment]
Fixed in [v0.2.8](https://github.com/lingochamp/FileDownloader/releases/tag/v0.2.8).
