### ISSUE TITLE
下载完成后 getTotal 0

### ISSUE THREAD

**Issue by Biswangluo** [lingochamp/FileDownloader#1275]
改的TasksManagerDemoActivity 暂停中的任务可以获取到总大小，下载完成后的获取到为0，已下载数据也为 sofar 0。

**Comment by Biswangluo** [comment]
手动查找filedownloader.db 内的数据，但是这个表没有任何数据，我哪里做的不对了呢？

**Comment by Biswangluo** [comment]
![微信图片_20190909105901](https://user-images.githubusercontent.com/2362450/64500721-e5267e80-d2f0-11e9-9164-8fe59d568665.png)

下载完成后，执行了删除代码，从数据库删除了这条信息，导致下载完成后，无法获取到文件总大小了，为什么要这么设计呢？

**Comment by rantianhua** [comment]
数据库仅仅是为了断点续传服务的，当一个文件下载完成，那么它也就不需要保存什么断点续传的数据信息了，所以将它的信息清除。如果不清除，那么对 FileDownloader 来说，数据会一直增加，而且这个存储的数据对下次下载没有任何意义，所以需要清除。
