### ISSUE TITLE
Some big files are corrupted after download.

### ISSUE THREAD

**Issue by AhmadullahSaikat** [lingochamp/FileDownloader#1276]
I'm using 1.7.6 version of this library.
I have some zip files on my server.
When I download those zip files from server, then some zip files are corrupted after download.
Please fix this issue asap.

**Comment by rantianhua** [comment]
Sorry, I cannot get useful information to help you to locate the problem. I will close this issue and I hope you can provide enough information according to the issue template, thanks.
