### ISSUE TITLE
FileDownloader.getImpl().getStatus(long downloadId) always return INVALID_STATUS

### ISSUE THREAD

**Issue by ericxiang** [lingochamp/FileDownloader#128]
When my app is force stopped and restart, I try to query all the status by download id which is stored by my own database.
But FileDownloader.getImpl().getStatus(long downloadId) always return INVALID_STATUS

**Comment by Jacksgong** [comment]
Invoking the `FileDownloader#getStatus` must after the FileDownlaodService has bound ( `FileDownloader#isServiceConnected()`, otherwise the status will be always INVALID_STATUS.

**Comment by Jacksgong** [comment]
You can use `FileDownlaoder#addServiceConnectListener` and `FileDownloader#removeServiceConnectListener`、`FileDownlaoder#bindService` .

**Comment by Jacksgong** [comment]
Ref: [TasksManagerDemoActivity.java](https://github.com/lingochamp/FileDownloader/blob/58e733acff2654a76e96cfbe2c62878aac4855c5/demo/src/main/java/com/liulishuo/filedownloader/demo/TasksManagerDemoActivity.java)

**Comment by ericxiang** [comment]
Thank you for the Demo project, I will check it.
BTW, there is another question: Is the DownloadService work in another process?
When i arrange a download task, I found there is a new process forked

**Comment by ericxiang** [comment]
One more question:
When a download task is processing, I just disable the WIFI and data connection, the task is failed directly.
If i try to resume the task with same path and url, I found that this task is not restarted from the bytes it has downloaded. It restart the task from 0 byte again

**Comment by ericxiang** [comment]
is it able to pause the download task when network is lost, and resume the download task the network is retained.
currently I try to use a CONNECTIVITY_CHANGE receiver to control this, but it behavior just like I said in pervious comment

**Comment by Jacksgong** [comment]
First of all, Please look at the [wik](https://github.com/lingochamp/FileDownloader/wiki), I spent much time to perfect it, to cover as much as FileDownloader want you to know, And you can configure the FileDownloadService running in the main process instead of in another process: https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties

Second, please use the lastest version, because your problem about resume from intercepting the downloading after no-connection already fixed in an old version, At least, In the lastest version, this problem is fixed.

**Comment by ericxiang** [comment]
Thank you so much for all your detailed feedback, really appreciate it.
I have checked the wiki and update my FileDownload library to 0.2.7
The second question seems to be resolved, when i restart the task ,it will download from the latest bytes.
But I still got an error callback when the network is disabled, and I can't distinguish this error(paused by network not available, I want show an "paused" state in my action button) from other errors(the task is failed and I will setForceReDownload as true to redownload totally)

Any idea about this?
Thank you

**Comment by ericxiang** [comment]
And also when i set the task.setForeReDownload true and try to start
I got an warn() callback, without download the file from the begining

**Comment by Jacksgong** [comment]
> But I still got an error callback when the network is disabled, and I can't distinguish this error(paused by network not available, I want show an "paused" state in my action button) from other errors(the task is failed and I will setForceReDownload as true to redownload totally)

Yes, If you want to distinguish the error whether it is called back from network not available, you can do it manually in error callback method:

> There are two kinds of Throwable would be thrown when network not available: `UnknowHostException` and `ConnectException`.

```
@Override
protected void error(BaseDownloadTask task, Throwable e) {
    super.error(task, e);
    if ((e instanceof UnknownHostException || e instanceof ConnectException)
            && !isNetworkAvailable()) {
        // the task occur error because of the network not online.
    }
}
```

**Comment by Jacksgong** [comment]
If you occur `warn()` callback, it must have already had some same Tasks(Same-URL & Same-SavePath) in Pending-Queue or is running in FileDownloader.

**Comment by ericxiang** [comment]
Yes, there is a same task (Same-URL & Same-SavePath) running in FileDownloader
But if i want clear the old task(status and files that already downloaded) and just redownload from all the beginning, how can i do this?

Because sometimes there may be CDN hijack or something that leading to invalid file
I will tell the users to change WIFI or network and redownload using same url and path

**Comment by Jacksgong** [comment]
So, pause the running task in FileDownloader:

1. `FileDownloader.getImpl().pauseAll()`
2. `task.pause()`
3. `FileDownloader.getImpl().pause(FileDownloadUtils.generateId(URL,PATH))`

After above operation. delete the old file, restart the task.

**Comment by ericxiang** [comment]
I tried FileDownloader.getImpl().pause(FileDownloadUtils.generateId(URL,PATH)) and it works well for me. Thank you for your suggestions and the FileDownloader is excellent!

**Comment by Jacksgong** [comment]
💯
