### ISSUE TITLE
下载文件时候开启新任务下载其他文件，报错 inputstream colsed

### ISSUE THREAD

**Issue by sfy2371** [lingochamp/FileDownloader#1281]
单独下载文件是没有问题的，并且已经添加.header("Connection", "close")

**Comment by rantianhua** [comment]
缺少必要的关键信息：

- 版本
- 日志

还可以提供额外的可选信息：

- 你使用的什么 API 开启新的任务
- 可以提供你这部分逻辑的伪代码

该 Issue 我先关掉了，请提供以上信息后重新提 Issue 。
