### ISSUE TITLE
文件下载的时候，文件大小总是2281，提示complete，但是源文件大小不是那么多

### ISSUE THREAD

**Issue by shaoyu0829** [lingochamp/FileDownloader#1284]
文件下载的时候，文件大小总是2281，提示complete，但是源文件大小不是那么多，怎么回事

**Comment by rantianhua** [comment]
缺少必要信息，比如：
- 日志
- 版本
只有这种现象性描述没有实际帮助，请提供必要信息后重新提 Issue 。
