### ISSUE TITLE
1.7.7-snapshot版本服务器总是出现异常，可以发一个正式版吗

### ISSUE THREAD

**Issue by zhpanvip** [lingochamp/FileDownloader#1286]
出现很多次1.7.7-SNAPSHOT找不到的情况，在浏览器里打开报500.

**Comment by rantianhua** [comment]
就在这两天了，请问有添加：
repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}
吗？

**Comment by zhpanvip** [comment]
有的，时不时的snapshots就会报500异常

**Comment by rantianhua** [comment]
1.7.7 released.
