### ISSUE TITLE
可以讲解下关于网络或机器处于什么情况下使用单/多线程下载会合适吗

### ISSUE THREAD

**Issue by lefu999** [lingochamp/FileDownloader#129]
可以讲解下关于网络或机器处于什么情况下使用单/多线程下载会合适吗

**Comment by Jacksgong** [comment]
这个主要看业务需求，主要目的是在不影响现有需求的同时，将资源利用最大化。

**Comment by lefu999** [comment]
而且我想问下为什么选择用okhttp作为通讯方式 相比原生的httpconnect的优势在哪里呢

**Comment by Jacksgong** [comment]
@lefu999 其实这个业界已经有非常多的资料了。包括Android系统默认UrlConnection 在5.0以后就默认走okhttp了: https://android.googlesource.com/platform/external/okhttp/

**Comment by Jacksgong** [comment]
#158
