### ISSUE TITLE
下载前下载信息获取问题

### ISSUE THREAD

**Issue by Moster1h** [lingochamp/FileDownloader#1290]
作者你好，
问题：当下载多个任务，任务在下载中，我退出应用。数据库中会保存断点的数据（导出数据库文件查看的），但是重新进应用，我重新创建下载任务（只是创建没有下载），都是同样的链接，为什么获取的ID是存在数据库中的，但是获取Sofar和Total都是0，我也通过FileDownloader根据下载ID获取过（下载ID是存在数据库中的），也是0，为什么？

**Comment by Moster1h** [comment]
如果我自己创建一个新的数据库去保存下载中的进度，是很耗时间的（放在子线程中），我不想对这么耗时间的事情做两遍，太耗时间了

**Comment by Moster1h** [comment]
还得自己创建一个数据库查询工具去查询，你们就不能内置一下吗？

**Comment by rantianhua** [comment]
不通过下载回调获取下载信息需要确保 FileDownloadService 已经开启。你可以参考 `Filedownloader#insureServiceBind` 的注释。

**Comment by Moster1h** [comment]
就查询一下数据库，还要启动FileDownloadService从才能获取信息，这设计的不太合理呀

**Comment by rantianhua** [comment]
所以开发了 OkDownload 。
