### ISSUE TITLE
使用task.start断点续传出错

### ISSUE THREAD

**Issue by MingHaoDu** [lingochamp/FileDownloader#1298]
您好，我将BaseDownloadTask放到集合里，然后暂停/开始下载的时候根据taskid取到对象，然后调用start方法时出错。
下面是报错信息：
![image](https://user-images.githubusercontent.com/25945385/68467173-b37a5700-0250-11ea-9cf0-bdc40e68450b.png)

> 

下面是代码（我是在react-native的原生里面写的）：
`  BaseDownloadTask task = FileDownloader.getImpl().create(downloadUrl).setTag(tasks.size() + 1).setPath(downloadDest);`
        `tasks.add(task);`
`//        queueSet.setAutoRetryTimes(1);`
       ` queueSet.downloadTogether(tasks);`
        `queueSet.start();`
       ` int taskId = task.getId();`

` @ReactMethod`
    `public void stop(int taskId){`
       ` for(BaseDownloadTask task:tasks){`
           ` if(taskId == task.getId()){`
              `  task.pause();`
         `   }`
       ` }`
   ` }`
   ` @ReactMethod`
  `  public void start(int taskId){`
       ` for(BaseDownloadTask task:tasks){`
           ` if(taskId == task.getId()){`
               `task.start();`
        `    }`
       ` }`
  `  }`

**Comment by rantianhua** [comment]
能把代码的 format 整理一下吗？这样太难受了。

**Comment by MingHaoDu** [comment]
第一次发帖， 不太懂咋整理，这个问题你知道吗？

**Comment by rantianhua** [comment]
其实错误日志已经说得比较清楚了，你在一个 queue 里面启动了一个任务，然后你之后想单独再启动同一个 Task ，这个 Task 已经在 queue 里面启动一次了，不能重复启动，所以抛出你看到的问题。看你的情况，应该是想先一次性启动若干个任务，当某个任务出错时，你想再单独尝试启动这个任务。你有两种方式：
1. 按照你现在的设计，你自己记录了之前创建的 Task ，然后在单独启动时，通过 id 找到之前创建的 Task 然后启动它。但这样是有问题的，原因就是我上面说到的，不过你如果真的想继续这样的结构，那么在调用 `task.start()` 之前，先调用 `task.reuse` 即可。
2. 避免和 queue 里面的 Task 重复启动，你可以利用同样的参数创建一个新的 Task 再直接启动即可。

（另外，建议迁移到 OkDownload ，对应文档可见 ：https://juejin.im/user/574e8041816dfa0067eee0c6

**Comment by MingHaoDu** [comment]
> 其实错误日志已经说得比较清楚了，你在一个 queue 里面启动了一个任务，然后你之后想单独再启动同一个 Task ，这个 Task 已经在 queue 里面启动一次了，不能重复启动，所以抛出你看到的问题。看你的情况，应该是想先一次性启动若干个任务，当某个任务出错时，你想再单独尝试启动这个任务。你有两种方式：
> 
> 1. 按照你现在的设计，你自己记录了之前创建的 Task ，然后在单独启动时，通过 id 找到之前创建的 Task 然后启动它。但这样是有问题的，原因就是我上面说到的，不过你如果真的想继续这样的结构，那么在调用 `task.start()` 之前，先调用 `task.reuse` 即可。
> 2. 避免和 queue 里面的 Task 重复启动，你可以利用同样的参数创建一个新的 Task 再直接启动即可。
> 
> （另外，建议迁移到 OkDownload ，对应文档可见 ：https://juejin.im/user/574e8041816dfa0067eee0c6

嗯嗯，谢谢，可以了。
