### ISSUE TITLE
单任务如何重复下载同一资源

### ISSUE THREAD

**Issue by KafukaChen** [lingochamp/FileDownloader#1299]
FileDownloader.getImpl().create(url)
        .setPath(path)
        .setListener(new FileDownloadListener() {
            @Override
            protected void pending(BaseDownloadTask task, int soFarBytes, int totalBytes) {
            }

            @Override
            protected void connected(BaseDownloadTask task, String etag, boolean isContinue, int soFarBytes, int totalBytes) {
            }

            @Override
            protected void progress(BaseDownloadTask task, int soFarBytes, int totalBytes) {
            }

            @Override
            protected void blockComplete(BaseDownloadTask task) {
            }

            @Override
            protected void retry(final BaseDownloadTask task, final Throwable ex, final int retryingTimes, final int soFarBytes) {
            }

            @Override
            protected void completed(BaseDownloadTask task) {
            }

            @Override
            protected void paused(BaseDownloadTask task, int soFarBytes, int totalBytes) {
            }

            @Override
            protected void error(BaseDownloadTask task, Throwable e) {
            }

            @Override
            protected void warn(BaseDownloadTask task) {
            }
        }).start();

启用单任务下载同一资源，一次下载成功后再下载直接走onCompleted方法，如何取消，就让他执行一次就再下载一遍

**Comment by rantianhua** [comment]
```java
FileDownloader.getImpl()
    .create(url)
    .setPath(path)
    .setForceReDownload(true)
```
