### ISSUE TITLE
如何重新设置监听

### ISSUE THREAD

**Issue by ayou6232290** [lingochamp/FileDownloader#13]
hi 大神:
例如:
某个Activity里面多个下载Task,开启下载后,退出当前Activity(不暂停任务),这个时候再进入当前Activity, 如何对我所有Task重新设置监听,可以收到之前下载的回调?    还是需要自己手动记录Id,重新start设置监听?

**Comment by ayou6232290** [comment]
看到另外的回答,已经知道怎么处理了 :).

**Comment by Jacksgong** [comment]
恩好的。 :100:
