### ISSUE TITLE
targetSdkVersion 为29 存储卡权限全部申请了，无法下载得问题

### ISSUE THREAD

**Issue by diswy** [lingochamp/FileDownloader#1312]
1.7.7
当targetSdkVersion  29改28后，可以正常下载，但是targetSdkVersion  为29 仍然会报错 permission denied, 存储卡读写权限全部申请了。请问这个问题如何解决？

**Comment by wakakajp** [comment]
请问解决了么

**Comment by diswy** [comment]
@wakakajp 没有解决- -所以我是降低版本了

**Comment by rantianhua** [comment]
我在 Demo 中将 target sdk 从 28 升级为 29 ，下载是可以正常进行的。所以还想你们多尝试下，多给些信息，看能不能找到问题的根源。

**Comment by diswy** [comment]
我这边尝试一下看能否复现

**Comment by diswy** [comment]
无法复现该问题了，可以正常进行。如果遇到类似问题的同学，请检查下载路径。或尝试用getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS)

**Comment by diswy** [comment]
原因找到了：
    /**
     * @deprecated To improve user privacy, direct access to shared/external
     *             storage devices is deprecated. When an app targets
     *             {@link android.os.Build.VERSION_CODES#Q}, the path returned
     *             from this method is no longer directly accessible to apps.
     *             Apps can continue to access content stored on shared/external
     *             storage by migrating to alternatives such as
     *             {@link Context#getExternalFilesDir(String)},
     *             {@link MediaStore}, or {@link Intent#ACTION_OPEN_DOCUMENT}.
     */
大概意思：当你target在29的时候，应用程序不可以直接访问此方法返回的路径了，因此导致了权限被拒绝。
