### ISSUE TITLE
使用Https下载，filedownloader内存溢出

### ISSUE THREAD

**Issue by layox2008** [lingochamp/FileDownloader#1313]
你好，我在使用Filedownloader https下载时，低于80M的文件下载正常，但是下载大文件（300M）时，只会走到download started回调，一直走不到download connected回调，有时会报OOM异常，然后filedownloader就会重启，感觉像是一直连接不上，烦请大神指点，十分感谢!

开始下载连接时，内存增长很快，到峰值时filedownloader OOM，然后重启
![图片](https://user-images.githubusercontent.com/7877311/71242663-627a7a00-2349-11ea-9aac-c4aae0b28d22.png)

初始化代码：
SSLSocketFactory socketFactory = SSLHelper.getSingleAuthSocketFactory(this);
            HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
            interceptor.setLevel(HttpLoggingInterceptor.Level.BODY);
            Cache cache = new Cache(new File(this
                    .getCacheDir(), "HttpCache"), 1024 * 1024 * 10);
            OkHttpClient.Builder builder = new OkHttpClient.Builder();
            builder.cache(cache)
                    .addInterceptor(interceptor)
                    .sslSocketFactory(socketFactory)
                    .retryOnConnectionFailure(true)
                    .connectTimeout(15_000, TimeUnit.SECONDS)
                    .writeTimeout(15_000, TimeUnit.SECONDS)
                    .readTimeout(15_000, TimeUnit.SECONDS)
                    .hostnameVerifier((hostname, session) -> true);

            FileDownloadLog.NEED_LOG = true;
            FileDownloader.setupOnApplicationOnCreate(this)
                    .connectionCreator(new OkHttp3Connection.Creator(builder))
                    .commit();

OkHttp3Connection用的 https://github.com/Jacksgong/filedownloader-okhttp3-connection
提示excuse
Log信息：
12-20 09:37:55.520 17974-18000/com.land.sun:filedownloader E/art: Throwing OutOfMemoryError "Failed to allocate a 400 byte allocation with 182416 free bytes and 178KB until OOM; failed due to fragmentation (required continguous free 32768 bytes for a new buffer where largest contiguous free 8192 bytes)" (recursive case)
12-20 09:37:55.554 17974-18000/com.land.sun:filedownloader E/art: "FileDownloader-Network1" prio=5 tid=16 Runnable
12-20 09:37:55.554 17974-18000/com.land.sun:filedownloader E/art:   | group="main" sCount=0 dsCount=0 obj=0x22c07400 self=0xb85f1068
12-20 09:37:55.555 17974-18000/com.land.sun:filedownloader E/art:   | sysTid=18000 nice=10 cgrp=bg_non_interactive sched=0/0 handle=0xb85f1548
12-20 09:37:55.555 17974-18000/com.land.sun:filedownloader E/art:   | state=R schedstat=( 22445814702 4333756018 60037 ) utm=1614 stm=630 core=3 HZ=100
12-20 09:37:55.555 17974-18000/com.land.sun:filedownloader E/art:   | stack=0xa4d95000-0xa4d97000 stackSize=1036KB
12-20 09:37:55.555 17974-18000/com.land.sun:filedownloader E/art:   | held mutexes= "mutator lock"(shared held)
12-20 09:37:55.555 17974-18000/com.land.sun:filedownloader E/art:     at okio.Segment.<init>(Segment.java:63)
12-20 09:37:55.555 17974-18000/com.land.sun:filedownloader E/art:     at okio.SegmentPool.take(SegmentPool.java:48)
12-20 09:37:55.555 17974-18000/com.land.sun:filedownloader E/art:     at okio.Buffer.writableSegment(Buffer.java:1163)
12-20 09:37:55.555 17974-18000/com.land.sun:filedownloader E/art:     at okio.Okio$2.read(Okio.java:137)
12-20 09:37:55.555 17974-18000/com.land.sun:filedownloader E/art:     at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
12-20 09:37:55.555 17974-18000/com.land.sun:filedownloader E/art:     at okio.RealBufferedSource.read(RealBufferedSource.java:46)
12-20 09:37:55.555 17974-18000/com.land.sun:filedownloader E/art:     at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:384)
12-20 09:37:55.555 17974-18000/com.land.sun:filedownloader E/art:     at okio.RealBufferedSource.request(RealBufferedSource.java:67)
12-20 09:37:55.555 17974-18000/com.land.sun:filedownloader E/art:     at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:237)
12-20 09:37:55.555 17974-18000/com.land.sun:filedownloader E/art:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
12-20 09:37:55.555 17974-18000/com.land.sun:filedownloader E/art:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
12-20 09:37:55.555 17974-18000/com.land.sun:filedownloader E/art:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
12-20 09:37:55.555 17974-18000/com.land.sun:filedownloader E/art:     at okhttp3.RealCall.execute(RealCall.java:69)
12-20 09:37:55.555 17974-18000/com.land.sun:filedownloader E/art:     at com.land.xtms.net.helper.OkHttp3Connection.execute(OkHttp3Connection.java:107)
12-20 09:37:55.556 17974-18000/com.land.sun:filedownloader E/art:     at com.liulishuo.filedownloader.download.ConnectTask.connect(ConnectTask.java:93)
12-20 09:37:55.556 17974-18000/com.land.sun:filedownloader E/art:     at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.trialConnect(DownloadLaunchRunnable.java:380)
12-20 09:37:55.556 17974-18000/com.land.sun:filedownloader E/art:     at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.run(DownloadLaunchRunnable.java:254)
12-20 09:37:55.556 17974-18000/com.land.sun:filedownloader E/art:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-20 09:37:55.556 17974-18000/com.land.sun:filedownloader E/art:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-20 09:37:55.556 17974-18000/com.land.sun:filedownloader E/art:     at java.lang.Thread.run(Thread.java:818)
12-20 09:37:55.752 17974-18000/com.land.sun:filedownloader I/art: Alloc partial concurrent mark sweep GC freed 43226(253MB) AllocSpace objects, 0(0B) LOS objects, 40% free, 2MB/3MB, paused 1.476ms total 169.436ms
12-20 09:37:55.752 17974-17986/com.land.sun:filedownloader I/art: WaitForGcToComplete blocked for 169.968ms for cause Alloc
12-20 09:37:55.753 17974-18000/com.land.sun:filedownloader E/AndroidRuntime: FATAL EXCEPTION: FileDownloader-Network1
                                                                                Process: com.land.sun:filedownloader, PID: 17974
                                                                                java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack available
12-20 09:37:55.760 17974-18000/com.land.sun:filedownloader I/Process: Sending signal. PID: 17974 SIG: 9
12-20 09:37:55.851 830-849/? I/ActivityManager: Start proc 18116:com.google.android.gms/u0a67 for broadcast com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
12-20 09:37:55.967 18116-18116/? W/ResourcesManager: Asset path '/system/framework/com.android.media.remotedisplay.jar' does not exist or contains no resources.
12-20 09:37:55.970 18116-18116/? W/ResourcesManager: Asset path '/system/framework/com.android.location.provider.jar' does not exist or contains no resources.
12-20 09:37:55.973 7906-7906/com.land.sun D/FileDownloader.FileDownloadServiceUIGuard: onServiceDisconnected ComponentInfo{com.land.sun/com.liulishuo.filedownloader.services.FileDownloadService$SeparateProcessService} com.liulishuo.filedownloader.i.IFileDownloadIPCService$Stub$Proxy@1da13a42
12-20 09:37:55.974 7906-7906/com.land.sun D/FileDownloader.FileDownloadServiceUIGuard: release connect resources com.liulishuo.filedownloader.i.IFileDownloadIPCService$Stub$Proxy@1da13a42
12-20 09:37:55.974 7906-7906/com.land.sun V/FileDownloader.FileDownloadEventPool: asyncPublishInNewThread event.service.connect.changed
12-20 09:37:55.978 830-6133/? I/ActivityManager: Process com.land.sun:filedownloader (pid 17974) has died
12-20 09:37:55.979 830-6133/? W/ActivityManager: Service crashed 2 times, stopping: ServiceRecord{7a8aaab u0 com.land.sun/com.liulishuo.filedownloader.services.FileDownloadService$SeparateProcessService}
12-20 09:37:55.984 7906-18134/com.land.sun V/FileDownloader.FileDownloadEventPool: publish event.service.connect.changed
12-20 09:37:55.984 7906-18134/com.land.sun D/FileDownloader.LostServiceConnectedHandler: lost the connection to the file download service, and current active task size is 1
12-20 09:37:55.985 7906-18134/com.land.sun D/FileDownloader.DownloadTaskHunter: free the task -231267743, when the status is 6
12-20 09:37:55.985 7906-18134/com.land.sun D/FileDownloader.FileDownloadServiceUIGuard: bindStartByContext App
12-20 09:37:56.035 830-2887/? I/ActivityManager: Start proc 18135:com.land.sun:filedownloader/u0a75 for service com.land.sun/com.liulishuo.filedownloader.services.FileDownloadService$SeparateProcessService

**Comment by layox2008** [comment]
在线等，想弄清楚FileDownloader是怎么控制内存的，为什么内存会一直增加呢？

**Comment by layox2008** [comment]
找到问题了，在HttpLoggingInterceptor中，读取内容，由于数据太大导致内存溢出，建议这个类也更新下
就是这句 source.request(Long.MAX_VALUE); 

`BufferedSource source = responseBody.source();
                source.request(Long.MAX_VALUE); // Buffer the entire body.
                Buffer buffer = source.buffer();
                Charset charset = UTF8;
                MediaType contentType = responseBody.contentType();`

**Comment by rantianhua** [comment]
晚点儿会确认下，感谢反馈！

**Comment by rantianhua** [comment]
如你所说，是 `HttpLoggingInterceptor ` 的问题，请关注 OkHttp 对应的 Issue ： https://github.com/square/okhttp/issues/4132
