### ISSUE TITLE
FileDownloader不能设置Filename

### ISSUE THREAD

**Issue by githubZYQ** [lingochamp/FileDownloader#1314]
#### Before Issue
如题：1，FileDownloader可以setPath，但是不能setFilename，使用不便；
2，FileDownloadListener的completed回调中BaseDownloadTask不能getFile使用不便；
比如我们服务端存的123.bin（某种原因不能直接存123.apk）,我下载完需要直接去执行安装，此时bin文件是不能用的。
#### Issue
希望
1，FileDownloader可以直接setFilename，
2，BaseDownloadTask的回调completed中，BaseDownloadTask可以直接获取下载成功的File
---

**Comment by rantianhua** [comment]
> FileDownloader 可以直接 setFilename。

---

实际上，`BaseDownloadTask#setPath(final String path)` 方法中 path 是需要包含文件名的，所以可以理解为这个就是你需要的 `setFilename` 。

> BaseDownloadTask 的回调 completed 中，BaseDownloadTask 可以直接获取下载成功的 File 。

--- 

`BaseDownloadTask#getTargetFilePath` 获取的就是下载成功的文件路径。`complete` 回调中提供了 `BaseDownloadTask` 对象。

**Comment by githubZYQ** [comment]
非常感谢rantianhua的解答，setPath方法中的pathAsDirectory参数 是控制是否作为文件夹的。
但是更改文件名后我遇到了另外一个问题：
setForceReDownload(true)，
发生异常：java.io.IOException: Can't delete the old java.io.IOException: Can't delete the old file([/storage/emulated/0/Android/data/cn.yt.driver/cache/倚天司机端.apk], [4096]), so can't replace it with the new downloaded one.

**Comment by rantianhua** [comment]
再确认几个问题：

- 每一次都不成功吗？
- file([/storage/emulated/0/Android/data/cn.yt.driver/cache/倚天司机端.apk  这个文件是否在其他线程打开且为关闭？
- 当抛出这个错误的时候，再检查下，file.exists 是否为 true ？

**Comment by githubZYQ** [comment]
你好：
1，不是每一次都不成功，第一次是回调的completed；
2，此文件只在此线调用；
3，之前出现此问题是在“逍遥模拟器”，在真机未复现；
4，今天看到你的问题，再次使用逍遥模拟器去复现，发现没有复现此问题；所以出现问题是的file.exists 暂时不能确定；
5，感谢你的答疑，之后如果能够复现相同问题，我再提出更详细的条件。
