### ISSUE TITLE
动态更新要串行下载的任务列表

### ISSUE THREAD

**Issue by StayZeal** [lingochamp/FileDownloader#133]
```
  for (String url : urls) {
            FileDownloader.getImpl().create(url)
                    .setListener(serialTarget)
                    .setPath(Environment.getExternalStorageDirectory().getAbsolutePath() + File.separator + "123456.mp4")
                    .setCallbackProgressTimes(100)
                    .setTag(++i)
                    .ready();
        }

        FileDownloader.getImpl().start(serialTarget, false);
```
怎么在FileDownloader.getImpl().start(serialTarget, false)方法调用之后动态更新这个串行下载的列表？
` public void start(final FileDownloadListener listener, final boolean isSerial) {

        if (listener == null) {
            return;
        }

        final List<BaseDownloadTask> list = FileDownloadList.getImpl().copy(listener);

        if (FileDownloadMonitor.isValid()) {
            FileDownloadMonitor.getMonitor().onRequestStart(list.size(), isSerial, listener);
        }

        if (FileDownloadLog.NEED_LOG) {
            FileDownloadLog.v(this, "start list size[%d] listener[%s] isSerial[%B]", list.size(), listener, isSerial);
        }

        if (isSerial) {
            // serial
            final Handler serialHandler = createSerialHandler(list);
            Message msg = serialHandler.obtainMessage();
            msg.what = WHAT_SERIAL_NEXT;
            msg.arg1 = 0;
            serialHandler.sendMessage(msg);
            synchronized (RUNNING_SERIAL_MAP) {
                RUNNING_SERIAL_MAP.put(listener, serialHandler);
            }
        } else {
            // parallel
            for (final BaseDownloadTask downloadTask : list) {
                downloadTask.start();
            }
        }
    }`
final List<BaseDownloadTask> list = FileDownloadList.getImpl().copy(listener);这个copy方法是不是改成复制指针这不是整个列表就能动态更新了？

**Comment by Jacksgong** [comment]
这个是浅复制，源码都在你可以稍微看下就清楚了。

`FileDownloadList` 是一个已经启动并且没有结束(`started`)/将要运行(`ready`)的队列，这个队列是全局共用的，

这里的 `clone` 是对队列中与指定 `listener` 相同的所有任务的引用（指针）拷贝一份到一个新的队列中，也是为了快照，作为这个 启动 需要执行的队列，因此在这个快照之后，当前这个启动只会按照这个快照执行，也就是如果还有绑定这个`listener`的任务加入，无法影响之前正在执行的快照。

**Comment by StayZeal** [comment]
我通过看源码的理解是`FileDownloader.getImpl().start(listener, false);`方法调用之后，这个串行下载的队列（A）就无法更新了--不知道我理解的是否正确。然后我再次调用`FileDownloader.getImpl().start(listener, false);`方法之后就会报错：
` java.lang.IllegalStateException: This task is running -197085054, if you want to start the same task, please create a new one by FileDownloader.create
                                                                       at com.liulishuo.filedownloader.BaseDownloadTask.start(BaseDownloadTask.java:396)
                                                                       at com.liulishuo.filedownloader.FileDownloader.start(FileDownloader.java:241)`

我的代码是这样的：在一个for循环中调用如下代码：
` public void addTask(FileBean file) {
        FileDownloader.getImpl().create(file.url)
                .setListener(lis)
                .setPath(file.path)
                .setCallbackProgressTimes(100)
                .setTag(++taskFlag)
                .ready();
//        if (isFirst == false) {
            FileDownloader.getImpl().start(lis, false);
            isFirst = true;
//        }
    }`

**Comment by Jacksgong** [comment]
@StayZeal sorry，一直没有留意这个issue，报这个错误是FileDownloader不支持对正在运行中的任务对象再次启动，如果需要启动相同url与相同path的任务，需要重新create。抛这个异常也说明这个任务对象正在运行。
