### ISSUE TITLE
想问下为什么不支持多线程分块下载？是因为高并发下这样会有什么问题吗？

### ISSUE THREAD

**Issue by lefu999** [lingochamp/FileDownloader#134]

**Comment by Jacksgong** [comment]
这块其实是一个决策性的问题，这个问题在很早就有人提过了: #102 。

我说下一开是没有支持的原因吧。

#### 多线程分块下载的好处:

1. 进一步占满网络资源
2. 进一步占满I/O资源

#### 多线程分块下载的坏处:

1. 对于目前的Android环境而言，绝大多数的Android设备I/O资源十分有限，我们发现很大程度上在取输入流buffer的时候，网络资源显得十分的充裕，而下载数据受限的瓶颈反而在I/O这块，因此开再多的线程，也会因为I/O资源有限，而被Block，反而加重了CPU的冗余消耗。下载速度没有有效提升，反而加重了手机资源的无效占用。

#### 展望:

这个是为来的方向，如同我在另外一个issue说的，在接下来的版本中，我会考虑加入该功能，并且由用户在 `filedownloader.properties` 中进行选择性配置，也会加入一些策略性机制来优化上面带来的坏处。

**Comment by Jacksgong** [comment]
关注 #102 进度即可。

**Comment by lefu999** [comment]
兄弟 感谢了 因为关于下载这块的资源实在是太少人分享经验了。
其实我最近是在做一件事 就是在将系统的downloadManager改成多线程的，我也考虑过你说的这些问题，其实我想知道的是在大概在多少个线程同时开启的时候IO Block的时间会比单线程下载还要费时？您有做过相关的研究吗？@Jacksgong 谢谢

**Comment by Jacksgong** [comment]
> 大概在多少个线程同时开启的时候IO Block的时间会比单线程下载还要费时？

这个是个伪命题，IO Block时间 与 单线程下载 没有可比性。

我前面提到的：是网络资源与I/O资源，比如，在跑满某个资源下载策略分配一个连接供给带宽4000Kb/s的时候，本地I/O 能够同时吃满 4000Kb/s，这里就到达了一个峰值；但是如果某个资源连接带宽是4000Kb/s，但是本地I/O 资源 吃不满 4000Kb/s，那么就是IO Block了下载速度，也就是说开再多线程，再多连接也都无济于事；但，如果本地IO 吃完4000Kb/s 的同时还有很多的IO资源剩余，假如还有2000Kb/s的提升空间，那么这时再建立一个连接 将这 2000Kb/s 也吃满，那么此时的速度就可以达到 6000Kb/s，这时就有意义。

而我上面提到的现状，可能并不是看起来那么简单，一方面是因为这里并非一个持续的I/O，而是间断性的I/O，这也带来了一些其他抽象层的开销，另一方面是多纬度的I/O，维护业务逻辑的同时，Android整个体系包括ActivityManager，各类广播、网络状态监控等，这些所有的跨进程通信，都不断的抢占I/O资源进行维系，更显得Android IO资源稀缺。
具体多少个线程，这个因设备而异，我并没有研究过，不过系统的DownloadManager目前还没有这块支持应该也是这块考量。这块应该在现有其他领域上的已有的各类解决方案来看，应该支持起来不难。如果目的只是为了下载更加轻量、更加快速，这块并非当务之急。

之所以我前面会说到这块I/O Block，是之前我持续优化FileDownloader的时候发现，在将输入流中buffer不断写入文件的间隙，不断的将一些小数据同步到数据库，虽然数据量很小，但是非常影响下载速度，因此我对这块进行了优化，也是我前面为什么提到的间断性I/O(这里应该是涉及到RAF中flush策略等相关)，以及I/O是现在的瓶颈，相关的参数，目前也是开放配置的[wiki](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties): `download.min-progress-step`、`download.min-progress-time`。

**Comment by lefu999** [comment]
再次感谢@Jacksgong兄弟 这么认真的去分析 回答我的问题。因为我实在是找不到人可以沟通这方面问题，有时候觉得很是迷茫又不知道怎么办因为我以前对网络这块几乎没有什么经验的。
我想就你上面提到的一个峰值有点疑问 您所说的IO Block有没有办法通过对IO操作的一些优化去避免呢(除去低配置硬件的情况因为我只针对一个品牌的手机来说) 例如说我用4M的缓冲区去读数据，存满了再写入一次，这样能否避免IO Block，或者有没有更好的方式推荐呢。我注意到小米手机的下载甚至还支持了迅雷的BT下载引擎，我想知道关于这块他们是不是已经有了什么结论了呢。
另外我还有一些疑问，系统的DownLoadManager看上去Google本身也不想支持修改，耦合性非常高，他最多支持开5个线程，重定向次数7次，我想知道是怎么来的，是他们经过了某种试验觉得这是最好的策略吗？另外就是我想问下如果您去拓展系统的DownLoadManager，您会选择保留系统的大部分逻辑还是按自己的来呢？因为他下载线程中有很多OS方法对内存方面有支持，不知道您怎么看？

**Comment by Jacksgong** [comment]
> 例如说我用4M的缓冲区去读数据，存满了再写入一次，这样能否避免IO Block。

这块分两点分析：

1. 一个是你谈的这个问题本身，RAF中的几种模式，或者是FOS都有对这块进行优化，而且也已经十分成熟，不过这块目前的瓶颈在于case by case，也就是并非是绝对的大小相关（一定是到一定阀值刷入文件？）、也不是绝对时间相关（一定是到了一定的时间节点刷入文件？）。
2.  是一个策略性的问题，也是FileDownloader 中的 `download.min-progress-step`、`download.min-progress-time` 的由来，这块主要矛盾点在于，如果程序奔溃了，或者是其他原因，下次启动下载的时候断点续传的点。也就是说如果你存满4M再写入，那么也就是很有可能一旦有特殊的情景，有可能丢失之前下载的4M文件需要重新下载，也就是稳定性的问题。

---

> 系统的DownLoadManager看上去Google本身也不想支持修改，耦合性非常高

> P.S: 其实并不是不支持修改，我觉得你想表达的是对上层拓展的灵活性很差。耦合是一个架构层面的术语，内部而言DownloadManager一直处于维护状态（参考 4.4.4_r1->5.0.0_r1)，而对拓展开放，对修改关闭这样的基本架构理念谷歌这些高工应该还是很清楚的。

作为系统的 DownloadManager，考虑的是一个整个系统层面的支持，考虑所有应用共用的下载引擎，因此稳定性高于一切，由于是一个全局的引擎，考虑到很多拓展相关会连带影响到其他应用程序对DownloadManager的使用，甚至是系统层面的下载，因此对上层可拓展性以及灵活性的决策也就可以理解了

从另一方面来说: DownloadManager提供基本的下载功能，但是如果你要的不是简单的下载，而又复杂的业务需求，自己写一个也不困难。

而系统的 DownloadManager 中的一些策略，应该都是相对平均值的一个全很，就如同picasso与fresco默认3个下载线程。

---

> 您会选择保留系统的大部分逻辑还是按自己的来呢？因为他下载线程中有很多OS方法对内存方面有支持，不知道您怎么看？

这一点Case By Case，根据应用场景不同决定，如果你想做的并不是一个像DownloadManager这样整个系统层级全局公用的下载引擎的话。

**Comment by lefu999** [comment]
@Jacksgong 对上层拓展的灵活性差的话我这边有什么办法能去解决吗 因为我就是要改系统DownloadProvider本身，用户用DownloadManager的时候并不知道我改了（PS:我目前是做手机平台的）。其实android的下载是在DownloadProvider里面完成的，DownloadManager只是一个对外提供的接口。可是DownloadProvider这个东西，我举个实例吧，他在DownInfo中不仅只是当成一个bean存放信息，他在里面直接开启了下载线程，对当前网络状态的判断等等，其实我本身是不理解为什么要这样做的。并没有把所有的东西剥离开。也非常难以去修改。如果我自己做一个的话，我要考虑到的风险其实还是很大的，因为毕竟是基于系统的，牵一发而动全身，可能会有很多bug。

**Comment by lefu999** [comment]
http://androidxref.com/6.0.1_r10/xref/packages/providers/DownloadProvider/src/com/android/providers/downloads/DownloadInfo.java 
参见492行

**Comment by Jacksgong** [comment]
已经支持分块下载，参考 https://github.com/lingochamp/FileDownloader/issues/102#issuecomment-306016976 近期版本会带上。

**Comment by lefu999** [comment]
谢谢告知！

**Comment by LY1806620741** [comment]
多线程下载一般用于网络不好的情况下加速下载
