### ISSUE TITLE
Get running tasks count 

### ISSUE THREAD

**Issue by YuriHeupa** [lingochamp/FileDownloader#136]
I didn't found any method to retrieve the current count of running task, the methods in `FileDownloadList` is not public and cannot be accessed from outside package.

I just want to know if is there any running tasks, is there any other method to retrieve this info?

**Comment by Jacksgong** [comment]
Sorry, If you want to retrieve the current count of running task or find any running tasks, you need to maintain another running list by yourself, just for your up-layer business. (Such as the demo: TasksManagerDemoActivity).

The running task in FileDownloadList is very instability, what is just used for FileDownloader internal, and it's not only used for maintaining the running task but also used for maintaining special situation, such as the whole running task would be diverted to `FileDownloadTask#NEED_RESTART_LIST` when FileDownloadService is unbound unexpectedly.

**Comment by YuriHeupa** [comment]
no problem.. I'll rely on the `TasksManagerDemoActivity` implementation
