### ISSUE TITLE
使用下载框架，点击下载后无法进入回调，文件也没有下载

### ISSUE THREAD

**Issue by Quenstin** [lingochamp/FileDownloader#1387]
背景：
    1.新项目、模块化、kotlin
     2.gradle中按照文档进行配置，读写权限也给了
     3.需要下载的资源路径没有问题
      4.在Application中进行了初始化

调用：
![image](https://user-images.githubusercontent.com/26788041/133386937-e7e4652c-5666-47b6-9888-32f0ebb1b325.png)

问题：下载没有走进回调，文件也没有下载
请问我是少了什么特殊配置了吗

**Comment by Quenstin** [comment]
我是NC。没有start

**Comment by zhangxiaojin770** [comment]
我是发现调用了start也没有回调  有个线上用户的问题
