### ISSUE TITLE
请为该库是否会自动收集用户隐私数据？

### ISSUE THREAD

**Issue by HysonHou** [lingochamp/FileDownloader#1388]
你好作者！
最近国内、工信部在严查APP数据合规问题，请问该库源码中是否存在自动收集用户隐私数据的行为？如果有希望更新到readme。
该库是否又调用了第三方SDK，如果又也希望更新到readme，多谢~~

**Comment by Jacksgong** [comment]
理解的，FileDownloader没有任何采集以及与之相关的第三方应用，请放心使用~
