### ISSUE TITLE
想用这个library做一个下载中心供系统的其他APP调用，使用AIDL遇到问题

### ISSUE THREAD

**Issue by Ernest-su** [lingochamp/FileDownloader#139]
IFileDownloadServiceHandler、FDServiceSeparateHandler的构造函数不是public的，因而不能在包外使用

**Comment by Jacksgong** [comment]
不明白你的问题所在，为什么需要用到这些。

你可以试试demo project里面的使用。

**Comment by Ernest-su** [comment]
demo里是在同一个app调用，我想要做的是发布一个下载的SDK，然后其他应用集成这个SDK就拥有了下载的能力。但是真正的下载工作是在下载中心这个APP完成。能加QQ请教一下吗？我的QQ是307141632

**Comment by Jacksgong** [comment]
可以直接到我们的gitter中聊天的: https://gitter.im/lingochamp/FileDownloader
