### ISSUE TITLE
Can I change my DefaultSaveRootPath

### ISSUE THREAD

**Issue by orangecoder** [lingochamp/FileDownloader#14]
Hi, thinks for your project , and I have a question that can I custom my DefaultSaveRootPath?

**Comment by Jacksgong** [comment]
sorry，we didn't provide such interface.

And if you want to set the custom path to one task, just invoke `BaseDownloadTask#setPath(String)`.

In the next version, we will provider `QueueConfig` , let you start the queue with the same `QueueConfig`, you will be able to set the custom path just one time in `QueueConfig`.

---

#### But

I know what your want. and that will be more convenient. It will be implemented in the next version, too. :)

**Comment by orangecoder** [comment]
Looking forward to your next version  :+1:

**Comment by Jacksgong** [comment]
[feat(New Interface): add new interface in FileDownloadUtils: for set default root path which is used in the case of task without setting path.](https://github.com/lingochamp/FileDownloader/commit/c0a006e700af48996acc1077b7511b6bf6465960)
