### ISSUE TITLE
关于后台下载

### ISSUE THREAD

**Issue by MrLiKH** [lingochamp/FileDownloader#140]
您好  再请教一个问题，当我退出当前的下载界面 怎么保证后台下载一直再继续呢

**Comment by Jacksgong** [comment]
如果是你退出下载界面，是不会影响的。不过如果你希望退出应用以后（比如用户通过 最近应用列表将应用 划掉关了），还能够保证下载一直在进行。就需要借用服务的前台模式: `FileDownloader.getImpl().startForeground(notificaitonId, notification)`，这样虽然通知栏里面会有一个通知在，但是可以保证下载一直在进行，不会被用户干掉，即使应用退出了。

**Comment by baoyachi** [comment]
之前也遇到过这个问题，下载要在通知栏显示，后台参照了[NotificationDemoActivity](https://github.com/lingochamp/FileDownloader/blob/master/demo/src/main/java/com/liulishuo/filedownloader/demo/NotificationDemoActivity.java)之后，就非常方便的集成了
