### ISSUE TITLE
如何能强制重复下载同一个连接？

### ISSUE THREAD

**Issue by iLibra** [lingochamp/FileDownloader#142]
我之前已经把某一个url下载过了。
第二次又要下载同一个url时。
会调用warn方法，然后就自动停止了。

我已经设置了  .setForceReDownload(true)
我觉的这里的设计不太合理。

同一个url应该允许反复下载。比如我前一次下载后检查md5不对，那我应该有机会再次下载。

**Comment by Jacksgong** [comment]
是支持的，只是下载引擎里面已经存在了相同任务（`相同URL` 与 `相同存储路径` ）**正在下载中**，而同时不可能对相同任务同时下载，这是无效的也是不和情理的，因此对新开的抛了 `warn`。当然如果相同任务在下载引擎中已经结束了（无论是error、还是paused、completed），是可以再次启动的。

因此，如果你希望 下载相同的任务，需要停止正在执行中的任务(`Filedownloader#pause`、`Filedownloader#pauseAll`、etc.)。换句话说，这个任务已经在执行了，为什么还需要启动呢，所以抛了 `warn`。 

而， `BaseDownload#setForceReDownload(true)` 的含义是相对于: 下载引擎 对于已经下载完成，并且文件是有效存在的任务直接 回调 `completed` ，不会重新下载；因此这里设置`BaseDownload#setForceReDownload(true)`，会触发的是: 即便是文件已经下载完成，并且文件有效存在，依然重新下载。

> P.S: 建议Clone demo project 下载，看看。还有就是可以多留意下我写的注解，每个都是花了很多心思写的 :).

**Comment by iLibra** [comment]
你好，
感谢回复，
那么看来就是现在的程序应该有bug了。因为我的测试时在BlockComplete中已经明确看到前一个任务结束了。
然后我再次发送下载命令。那么每次都收到了warn。导致我以为不能重复下载url.

如你所解释的，收到warn应该是当前正在下载那个url.这点我可以保证是肯定没有的。

**Comment by iLibra** [comment]
我又仔细测试了。从目前看的分析，应该是你内部的数据库因为某种原因没有更新，导致那个task已经下载完了。但是没有标记成完成。后续就永远没有机会再重新下载这个url了。
我尝试过执行pauseAll.依然无效。

以下是log

05-09 15:30:34.847 7283-7963/com.xxx D/FileDownloader.FileDownloadTask: setPath /sdcard/Download/env
05-09 15:30:34.847 7283-7963/com.xxx D/FileDownloader.FileDownloadTask: setListener com.xxx.upgrade.CheckUpdateService$1@4280e2d8
05-09 15:30:34.847 7283-7963/com.xxx D/FileDownloader.FileDownloadTask: ready 2 download 1880174692@com.liulishuo.filedownloader.FileDownloadTask@426166b0
05-09 15:30:34.847 7283-7963/com.xxx V/FileDownloader.FileDownloadList: add list in all 1880174692@com.liulishuo.filedownloader.FileDownloadTask@426166b0 0 1
05-09 15:30:34.887 7283-7963/com.xxx V/FileDownloader.FileDownloader: start list size[1] listener[com.xxx.upgrade.CheckUpdateService$1@4280e2d8] isSerial[TRUE]
05-09 15:30:34.917 7283-8011/com.xxx V/FileDownloader.FileDownloadTask: call start url[http://172.21.0.105/img/201605050/env.fex], setPath[/sdcard/Download/env] listener[com.xxx.upgrade.CheckUpdateService$1@4280e2d8], tag[null]
05-09 15:30:34.927 7283-8013/com.xxx D/FileDownloader.FileDownloadTask: no connect service !! 1880174692
05-09 15:30:34.927 7283-8013/com.xxx W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1479 android.content.ContextWrapper.startService:494 com.liulishuo.filedownloader.FileDownloadServiceSharedTransmit.bindStartByContext:123 com.liulishuo.filedownloader.FileDownloadServiceSharedTransmit.bindStartByContext:110 com.liulishuo.filedownloader.FileDownloadServiceProxy.bindStartByContext:122 
05-09 15:30:34.977 7283-7283/com.xxx I/Choreographer: Skipped 45 frames!  The application may be doing too much work on its main thread.
05-09 15:30:35.027 7283-7283/com.xxx D/FileDownloader.FileDownloadMgr: can't reuse 782434411 file not exists
05-09 15:30:35.027 7283-7283/com.xxx D/FileDownloader.FileDownloadMgr: can't continue 782434411 file not suit, exists[FALSE], directory[FALSE]
05-09 15:30:35.027 7283-7283/com.xxx D/FileDownloader.FileDownloadDBHelper: delete 782434411
05-09 15:30:35.047 7283-7283/com.xxx D/FileDownloader.FileDownloadDBHelper: refresh data 6 , will delete: 1 consume 16
05-09 15:30:35.057 7283-7283/com.xxx V/FileDownloader.FileDownloadEventPool: asyncPublishInNewThread event.service.connect.changed
05-09 15:30:35.057 7283-8017/com.xxx V/FileDownloader.FileDownloadEventPool: publish event.service.connect.changed
05-09 15:30:35.057 7283-8017/com.xxx D/FileDownloader.FileDownloadTask: callback connect service connected
05-09 15:30:35.057 7283-8017/com.xxx D/FileDownloader.FileDownloadTask: ready 2 download 1880174692@com.liulishuo.filedownloader.FileDownloadTask@426166b0
05-09 15:30:35.057 7283-8011/com.xxx D/FileDownloader.SerialHandlerCallback: start next com.xxx.upgrade.CheckUpdateService$1@4280e2d8 0
05-09 15:30:35.057 7283-8011/com.xxx V/FileDownloader.FileDownloadTask: call start url[http://172.21.0.105/img/201605050/env.fex], setPath[/sdcard/Download/env] listener[com.xxx.upgrade.CheckUpdateService$1@4280e2d8], tag[null]
05-09 15:30:35.057 7283-8018/com.xxx D/FileDownloader.FileDownloadMessenger: notify begin 1880174692@com.liulishuo.filedownloader.FileDownloadTask@426166b0
05-09 15:30:35.057 7283-8018/com.xxx V/FileDownloader.FileDownloadTask: filedownloader:lifecycle:start 1880174692@com.liulishuo.filedownloader.FileDownloadTask@426166b0 by 0 
05-09 15:30:35.067 7283-8018/com.xxx D/FileDownloader.FileDownloadTask: start downloaded by ui process http://172.21.0.105/img/201605050/env.fex
05-09 15:30:35.067 7283-8018/com.xxx D/FileDownloader.FileDownloadMgr: has already started download 1880174692
05-09 15:30:35.067 7283-8018/com.xxx D/FileDownloader.FileDownloadTask: ~~~callback 1880174692 old[0] new[-4] 1
05-09 15:30:35.067 7283-8018/com.xxx W/FileDownloader.FileDownloadTask: warn, but no listener to receive progress, switch to pending 1880174692 -3
05-09 15:30:35.067 7283-8018/com.xxx V/FileDownloader.FileDownloadList: remove 1880174692@com.liulishuo.filedownloader.FileDownloadTask@426166b0 left -4 0
05-09 15:30:35.067 7283-8018/com.xxx D/FileDownloader.FileDownloadMessenger: notify warn 1880174692@com.liulishuo.filedownloader.FileDownloadTask@426166b0
05-09 15:30:35.067 7283-8018/com.xxx V/FileDownloader.FileDownloadTask: filedownloader:lifecycle:over 1880174692@com.liulishuo.filedownloader.FileDownloadTask@426166b0 by -4 
05-09 15:30:35.067 7283-8018/com.xxx D/FileDownloader.SerialHandlerCallback: start next com.xxx.upgrade.CheckUpdateService$1@4280e2d8 1
05-09 15:30:35.067 7283-8011/com.xxx D/FileDownloader.SerialHandlerCallback: final serial null 1
05-09 15:30:35.077 7283-7283/com.xxx I/CheckUpdateService: warn: http://172.21.0.105/img/201605050/env.fex

**Comment by Jacksgong** [comment]
> `blockCompleted` 的时候，并没有真正结束。`blockCompleted` 只是内部下载结束了。但是对于 Task任务而言，还没有结束。

你可以给下你遇到这个问题的 简单的 demo project 吗，我认真检查下问题。因为我在 FileDownloader 提供的 demo project 中无法复现。

**Comment by Jacksgong** [comment]
还有一点我比较疑惑的是抛 `warn` 这个和数据库无关，是memory里面的临时数据决定的。
我比较建议你体验下  FileDownloader demo project 中的 单任务测试，然后对比下你的项目，看看是哪里使用出现了问题。如果你始终无法找到原因，提供一个简单的你遇到问题的 demo，我给你看下。

**Comment by iLibra** [comment]
你好，我分析了下了我的过程。
我发现我在BlockComplete中去读取下载的文件，然后把系统重启了。

所以我猜是这个原因导致数据库的记录没有机会更新。

但是从这个看。目前的机制缺失有问题。就是如果下载到BlockComplete阶段。程序crash或者系统重启。

你就没有机会重新修复这些状态错误的task.而我每次在新的下载开始之前调用PauseAll。也是无法重置这些错误状态task的。

所以希望你能考虑到这种情况做一下修复。谢谢
毕竟下载中crash的几率还是很多的。

**Comment by iLibra** [comment]
另外你说的“是memory里面的临时数据决定的。”
这个是不是因为每次程序重新启动，你从数据库中又读回来原来的数据，而数据库中有task依然标记为running的状态。而实际此时并没有task在运行，导致了这个错误？
我没有看你的代码。所以这是我猜测。

**Comment by Jacksgong** [comment]
你可以稍微看下代码，所有在你回调之前，数据都是已经同步到了数据库中的。

**Comment by Jacksgong** [comment]
还有。从数据库读回来原来数据的时候，会处理所有的脏数据，不会存在读回来以后还是running的情况，这个你留意下 FileDownloadDbHelper 86行。

具体希望你看看demo project 中的使用，以及wiki，我怀疑你是使用问题。

如果还有什么必现问题，直接提供你遇到问题的简单的demo project，我直接给你看下，这样最快。

**Comment by Jacksgong** [comment]
下载到 `BlockComplete` ，内部已经下载完成了。如果说你希望重启了，或者是其他因素，重新启动任务，会直接 走 `completed`。

**Comment by Jacksgong** [comment]
这块的内部流是这样的: `FileDownloadRunnable#onComplete`(**包含写数据库**) -> `FileDownoadRunnable#onStatusChanged` -> `BaseDownloadTask#update` -> `FileDownloadList#remove` -> `FileDownloadMessenger#notifyBlockComplete` -> **`FileDowloadListener#blockComplete`(在任务flow线程执行回调)** -> `FileDownloadListener#completed` (默认在 UI线程执行)`
