### ISSUE TITLE
Socket deconnection 问题

### ISSUE THREAD

**Issue by itsmallsun** [lingochamp/FileDownloader#143]
log:[ 05-08 22:36:13.513    64:   64 D/         ]
                                                        Socket deconnection
每次进度回调都会打出这个信息，这个是什么原因呢？ 是否会影响下载速度呢？

**Comment by Jacksgong** [comment]
FileDownloader 中并没有打印这个日志。

**Comment by itsmallsun** [comment]
谢谢，我自己会好好看看的！

**Comment by Jacksgong** [comment]
👍

**Comment by baoyachi** [comment]
@Jacksgong FileDownloader这个库更新的好勤啊，屌屌的！
