### ISSUE TITLE
每次调用下载都Crash，

### ISSUE THREAD

**Issue by iLibra** [lingochamp/FileDownloader#145]
遇到个问题，每次一调用下载就crash.重启程序后依然无法恢复。

具体内容见log

05-09 18:33:06.875 12562-12562/com.xxx D/FileDownloader.FileDownloadDBHelper: delete 2006914847
05-09 18:33:06.885 12562-12562/com.xxx D/FileDownloader.FileDownloadDBHelper: refresh data 0 , will delete: 1 consume 11
05-09 18:33:06.895 12562-12562/com.xxx D/FileDownloader.FileDownloadMgr: pause all tasks 0
05-09 18:33:06.895 12562-12562/com.xxx V/FileDownloader.FileDownloadEventPool: asyncPublishInNewThread event.service.connect.changed
05-09 18:33:06.905 12562-13132/com.xxx V/FileDownloader.FileDownloadEventPool: publish event.service.connect.changed
05-09 18:33:06.905 12562-13132/com.xxx D/FileDownloader.FileDownloadTask: callback connect service connected
05-09 18:33:06.905 12562-12562/com.xxx V/FileDownloader.FileDownloadEventPool: asyncPublishInNewThread event.service.connect.changed
05-09 18:33:06.905 12562-13132/com.xxx D/FileDownloader.FileDownloadTask: ready 2 download 2006914847@com.liulishuo.filedownloader.FileDownloadTask@41fdc7a0
05-09 18:33:06.905 12562-13133/com.xxx V/FileDownloader.FileDownloadEventPool: publish event.service.connect.changed
05-09 18:33:06.905 12562-13121/com.xxx D/FileDownloader.SerialHandlerCallback: start next com.xxx.upgrade.CheckUpdateService$1@41e0e178 0
05-09 18:33:06.905 12562-13133/com.xxx D/FileDownloader.FileDownloadTask: callback connect service connected
05-09 18:33:06.905 12562-13121/com.xxx V/FileDownloader.FileDownloadTask: call start url[http://172.21.0.105/img/201605060/system.fex], setPath[/sdcard/Download/seconds] listener[com.xxx.upgrade.CheckUpdateService$1@41e0e178], tag[null]
05-09 18:33:06.905 12562-13121/com.xxx D/FileDownloader.SerialHandlerCallback: start next com.xxx.upgrade.CheckUpdateService$1@41e0e178 0
05-09 18:33:06.905 12562-13134/com.xxx D/FileDownloader.FileDownloadMessenger: notify begin 2006914847@com.liulishuo.filedownloader.FileDownloadTask@41fdc7a0
05-09 18:33:06.905 12562-13121/com.xxx W/dalvikvm: 1 threadid=28: systemTid:13121 thread exiting with uncaught exception (group=0x415e9560)
05-09 18:33:06.905 12562-13134/com.xxx V/FileDownloader.FileDownloadTask: filedownloader:lifecycle:start 2006914847@com.liulishuo.filedownloader.FileDownloadTask@41fdc7a0 by 0 
05-09 18:33:06.905 12562-13134/com.xxx D/FileDownloader.FileDownloadTask: start downloaded by ui process http://172.21.0.105/img/201605060/system.fex
05-09 18:33:06.905 12562-13121/com.xxx D/dalvikvm: Calling process 2 is: com.xxx
05-09 18:33:06.905 12562-13121/com.xxx W/dalvikvm: mCallingProcess:com.xxx
05-09 18:33:06.925 12562-13134/com.xxx D/FileDownloader.FileDownloadRunnable: On resume 2006914847
05-09 18:33:06.935 12562-13135/com.xxx D/FileDownloader.FileDownloadTask: ~~~callback 2006914847 old[0] new[1] 1
05-09 18:33:06.935 12562-13135/com.xxx D/FileDownloader.FileDownloadMessenger: notify pending 2006914847@com.liulishuo.filedownloader.FileDownloadTask@41fdc7a0
05-09 18:33:06.935 12562-13136/com.xxx D/FileDownloader.FileDownloadRunnable: start download 2006914847 http://172.21.0.105/img/201605060/system.fex
05-09 18:33:06.935 12562-13136/com.xxx D/FileDownloader.FileDownloadMgr: can't continue 2006914847 file not suit, exists[FALSE], directory[FALSE]
05-09 18:33:06.935 12562-13121/com.xxx E/AndroidRuntime: FATAL EXCEPTION: filedownloader serial thread com.xxx.upgrade.CheckUpdateService$1@41e0e178
                                                                   Process: com.xxx, PID: 12562
                                                                   java.lang.IllegalStateException: This task is running 2006914847, if you want to start the same task, please create a new one by FileDownloader.create
                                                                       at com.liulishuo.filedownloader.BaseDownloadTask.start(BaseDownloadTask.java:381)
                                                                       at com.liulishuo.filedownloader.FileDownloader$SerialHandlerCallback.handleMessage(FileDownloader.java:614)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by Jacksgong** [comment]
你先试下demo project，我抽空看下你的log。

**Comment by Jacksgong** [comment]
```
java.lang.IllegalStateException: This task is running 2006914847, if you want to start the same task, please create a new one by FileDownloader.create
```

这里已经有非常清晰的解释了。这个是你调用的问题的，因为这个是非常高level的错误，FileDownloader直接用 Exception的形式抛出来给你了。

**Comment by iLibra** [comment]
谢谢你的回复，
不过这里这个问题不是你看到的那么简单。我也看到了那个exception.然而。这个时候是整个程序刚刚启动，正在添加第一个task.

这个问题应该和我之前报给你的那个问题相关。都是数据库有问题。我后来把数据库全部删除掉。然后确保每次系统重启前已经执行完了BlockComplete.这个问题才消失了。
而我添加任务的代码一行都没有改。

**Comment by Jacksgong** [comment]
我估计你是使用上遇到问题了。 首先对于内部而言，相关的任务对象是在内部流当中非常不稳定的，因此不建议在运行了以后再对任务对象(BaseDownloadTask)做任何操作，如果你需要重新启动这个任务，直接通过 `FileDownloader.getImpl().create` 重新创建一个，哪怕是相同的任务都是允许的。

**Comment by Jacksgong** [comment]
你可以 clone 下来 项目的 demo project ，然后跑一跑，看看里面的使用。看看是否有你想要的需求的case。
