### ISSUE TITLE
下载后的文件不能重命名

### ISSUE THREAD

**Issue by chile-zhong** [lingochamp/FileDownloader#146]
下载后的文件不能重命名

**Comment by Jacksgong** [comment]
没有特殊处理确实是如果重命名以后，再通过FileDownloader检测会发现需要重新下载。

解决方案: 重命名以后可以通过这个方式通知FileDownloader文件路径/文件名发生变化： `FileDownloader#setTaskCompleted(Url, absolutePath)`。
