### ISSUE TITLE
Doubt if the file

### ISSUE THREAD

**Issue by seransaca** [lingochamp/FileDownloader#148]
I have a doubt, I would like to know whether the file has been download if you redownload or not. Because if you redownload it has to overwrite. and my application files can have the same name, but they can be different files depending on the day.

Thanks

**Comment by Jacksgong** [comment]
If the file has been downloaded, and you want to redownload it, just set the value in `BaseDownloadTask#setForceReDownload` to true.

```
/**
 * Force re download whether already downloaded completed
 *
 * @param isForceReDownload If set to true, will not check whether the file is downloaded
 *                          by past, default false
 */
public BaseDownloadTask setForceReDownload(final boolean isForceReDownload) {
    this.isForceReDownload = isForceReDownload;
    return this;
}
```

**Comment by seransaca** [comment]
I downloading the carried follows:
`new FileDownloadQueueSet(mDownloadListener)
                .disableCallbackProgressTimes()
                .setAutoRetryTimes(RETRY_TIMES)
                .downloadTogether(downloadTasks)
                .start();`
As "downloadTasks" is a queue of files to download, where I have to force the download?

**Comment by Jacksgong** [comment]
it also has a function `FileDownloadQueueSet#setForceReDownload` free to use, If you set `true` to this function, each task in the queue will be redownloaded if it has already downloaded.

**Comment by seransaca** [comment]
Okay, but I think that time whenever I say download through the Completed method of FileDownloadListener

Thank you very much

**Comment by Jacksgong** [comment]
Yes, what I said 'downloaded' also means that it has already completed downloaded whole file and  would be call-backed function `completed` of FileDownloadListener.
