### ISSUE TITLE
在下载服务不在独立进程的情况，调用了 BaseDownloadTask.addHeader 后好像没作用

### ISSUE THREAD

**Issue by SamuelGjk** [lingochamp/FileDownloader#149]
你好，我遇到个问题，调用了 BaseDownloadTask.addHeader 后, FileDownloadRunnable 里的
```Java
if (header != null && header.getNamesAndValues() != null) {
    if (FileDownloadLog.NEED_LOG) {
        FileDownloadLog.v(this, "%d add outside header: %s", getId(), header);
    }
    builder.headers(Headers.of(header.getNamesAndValues()));
}
```
这个Log没有打印出来，也就是说header为空了？

**Comment by Jacksgong** [comment]
💯 

如果是在`process.non-separate=false`，也就是下载进程在独立进程的情况下是没有有问题的，这个时候有两个可能原因:

1. `FileDownloadLog.NEED_LOG` 是 `false`。
2. 你查看的不是 `FileDownloadRunnable` 所在进程的日志。

> 你可以保证 `FileDownloadLog.NEED_LOG` 是 `true` 的情况下，在终端输入 `adb logcat | grep "add outside header"`，就可以看到日志。
---

如果是在 ``process.non-separate=true`，也就是下载服务所在进程不在独立进程的时候，**确实存在这个Bug，我现在立马修复提交新版本**。 多谢你的issue.

> P.S: `process.non-separate` 的相关配置在 [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)

**Comment by Jacksgong** [comment]
Fixed since [0.3.0](https://github.com/lingochamp/FileDownloader/releases/tag/v0.3.0).

**Comment by SamuelGjk** [comment]
谢谢大神这么快的回复和修复，我确实是在 process.non-separate = true 的情况下遇到的
