### ISSUE TITLE
怎么让下载速度更快

### ISSUE THREAD

**Issue by mokuang** [lingochamp/FileDownloader#150]

**Comment by Jacksgong** [comment]
Ref: [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)

1. `process.non-separate=true` 关闭独立进程模式，减少每次回调的IPC的I/O 。
2. 调高: `download.min-progress-step` 与 `download.min-progress-time` 。
3. 根据实际环境调整网络连接线程数: `download.max-network-thread-count` 。

---

#### `filedownloader.properties`

> 如果你需要定制化FileDownloader，可以在你的项目模块的`assets` 目录下添加 'filedownloader.properties' 文件(如 `/demo/src/main/assets/filedownloader.properties`)，然后添加以下可选相关配置。

> 格式: `keyword=value`

| 关键字 | 描述 | 默认值
| --- | --- | ---
| http.lenient | 如果你遇到了: 'can't know the size of the download file, and its Transfer-Encoding is not Chunked either', 但是你想要忽略类似的返回头不规范的错误，直接将该关键字参数设置为`true`即可，我们将会将其作为`chunck`进行处理 | false
| process.non-separate | FileDownloadService 默认是运行在独立进程':filedownloader'上的, 如果你想要FileDownloadService共享并运行在主进程上, 将该关键字参数设置为`true`，可以有效减少IPC产生的I/O | false
| download.min-progress-step | 最小缓冲大小，用于判定是否是时候将缓冲区中进度同步到数据库，以及是否是时候要确保下缓存区的数据都已经写文件。值越小，更新会越频繁，下载速度会越慢，但是应对进程被无法预料的情况杀死时会更加安全 | 65536
| download.min-progress-time | 最小缓冲时间，用于判定是否是时候将缓冲区中进度同步到数据库，以及是否是时候要确保下缓存区的数据都已经写文件。值越小，更新会越频繁，下载速度会越慢，但是应对进程被无法预料的情况杀死时会更加安全 | 2000
| download.max-network-thread-count | 用于同时下载的最大网络线程数, 区间[1, 12] | 3

**Comment by itsmallsun** [comment]
@Jacksgong  如何能让它下载速度达到最大带宽呢？   我这边的下载速度一直上不去！

**Comment by Jacksgong** [comment]
@itsmallsun 要达到最大带宽除了 `filedownloader.properties` 提供的这些配置以外，和当前的网络环境 以及 资源本身对当前链接提供的带宽也是有紧密的关系的。

**Comment by itsmallsun** [comment]
@Jacksgong  谢谢大神  忽略外部的因素  单就filedownloader.properties 该怎么去配？

**Comment by Jacksgong** [comment]
@itsmallsun 你可以参考下，我在这个答复已经答复了的: https://github.com/lingochamp/FileDownloader/issues/150#issuecomment-219220078

**Comment by itsmallsun** [comment]
@Jacksgong   好 谢谢您！

**Comment by 10045125** [comment]
对于下载速度我的看法，首先作者在下载文件采用单线程下载，在网络IO和文件IO中，如果当前写文件，那么势必会造成网络IO时间的浪费，这样会导致网络下载速度变慢，通过我对代码中下载速度值的监控，下载速度值波动很大，很大原因是网络IO和文件IO没有协调好。

**Comment by Jacksgong** [comment]
@10045125 这里的波动值抛去其他外界因素，是由于 `download.min-progress-step` 与 `download.min-progress-time` 的一次数据库写入照成的，你可以尝试调整这个值，来对比波动情况。

网络这块的输入流主要是载入内存，而写文件这块主要是内存输出到本地磁盘，而何时真正输出到本地磁盘，RAF已经有优化，而内存这块理论上不是瓶颈的。

**Comment by 10045125** [comment]
我的想法是这样的，目前文件下载是在线程池中的单独一个线程中完成，如果这个时候写文件（网络IO就浪费（时间）），我们能不能够把一个文件分成3段下载，一个文件下载同时3个线程执行，这样能不能够提升下载文件速度？这样能够充分利用文件IO和网络IO带来的消耗。你的想法呢？

**Comment by mokuang** [comment]
@Jacksgong 谢谢

**Comment by Jacksgong** [comment]
@10045125 这里已经回答你的问题了: https://github.com/lingochamp/FileDownloader/issues/187#issuecomment-227376148
