### ISSUE TITLE
监听网络状态变化（系统广播)，在3G/4G下执行leDownloader.getImpl().pauseAll()之后会发生异常

### ISSUE THREAD

**Issue by AlawnXu** [lingochamp/FileDownloader#151]
java.lang.IllegalStateException
Fatal-Exception: You can't bind the FileDownloadService in :filedownloader process. It's the invalid operation, and is likely to cause unexpected problems. Maybe you want to use non-separate process mode for FileDownloader, More detail about non-separate mode, please move to wiki manually: https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties

**Comment by Jacksgong** [comment]
这个错误，是FileDownloader主动抛出的，抛出这个错误的原因是: 你在下载进程中主动请求，或者你的请求中包含，绑定下载服务操作。这个是不允许的。你可以检查下你的 Application中是否在没有判定进程名的情况下调用了绑定下载服务。

**Comment by AlawnXu** [comment]
是因为我执行了 FileDownloader.getImpl().unBindService();导致的？？？

**Comment by Jacksgong** [comment]
如果你不是很理解，可以提供下必现的demo project，我给你看下是哪里的问题。

**Comment by Jacksgong** [comment]
@AlawnXu 问题解决了吗？
