### ISSUE TITLE
Adding more than a file download listener

### ISSUE THREAD

**Issue by bluemix** [lingochamp/FileDownloader#152]
Hello,
is it possible to add more than a listener to a file download?
or if any other technique that can achieve it.

i.e., ````BaseDownloadTask````'s ````setListener```` be like ```addListener```? 
so that I have a download service that updates the notifications in one place, and progress bars on
other fragments in other place.

and thanks a lot for this great downloading library.

**Comment by Jacksgong** [comment]
Yes, you can achieve it through creating your own manager: https://github.com/lingochamp/FileDownloader/issues/103#issuecomment-209173124

**Comment by bluemix** [comment]
Actually, I was using other download library that has ```addLisener``` in its API,
so I thought this might be here too.

Thanks a lot for this library. I did the above approach (from #103 ) and it worked with me.

**Comment by Jacksgong** [comment]
Thanks for your suggestion. As you know FileDownloader is provided some way to avoid missing screen frames and it will not work if there are too many listeners on one task. But it has `addFinishListener` in `BaseDownloadTask` , though it will  be invoked in other thread to UI thread.

**Comment by bluemix** [comment]
yes, true.
thanks a lot for your reply and 
keep doing great stuff with this library 👍
