### ISSUE TITLE
okhttp是否可由compile更改为 provided更好？ 

### ISSUE THREAD

**Issue by shingohu** [lingochamp/FileDownloader#153]
因为项目中使用的okhttp 2.x 引入您的library后导致两个不同版本的okhttp会被打包到apk

**Comment by Jacksgong** [comment]
其实如果采用 `provided` 会导致引了 okhttp，但是对外界不可见，外带包变大了，我也看了一些业界的常见库，如: `Reftrofit`、`Picasso` 等，都不是这种方案的。

对了。我是比较推荐使用最新版本的okhttp。如果你也使用okhttp 3.x，你可以考虑这样引入，这样可以定制你自己想要引入的okhttp版本，并且可以保证代码中只引入了一份okhttp:

```
compile ('com.liulishuo.filedownloader:library:0.3.1') {  
  // 保证只引入filedownloader，而不引入okhttp。
  exclude module: 'okhttp'
}

compile 'com.squareup.okhttp3:okhttp:3.2.0'
```

---

> 其实我有考虑在下个版本将okhttp从原有库中肢解出去，然后分离为两个库，一个特例库引入了okhttp，另外一个基本库支持传入采用任意方式建立下载。

**Comment by Jacksgong** [comment]
#158
