### ISSUE TITLE
Cancel/Pause Download from Notification Action Button

### ISSUE THREAD

**Issue by tuysotheara** [lingochamp/FileDownloader#154]
Hi! I've been using FileDownloadNotificationHelper to create notification of my download. I want to know how I can pause or cancel the download from notification action button. I have tried FileDownloader.getImpl().pause(id) in my broadcast receiver but no effect.

Please kindly guide me through. Thanks in advance!!

**Comment by Jacksgong** [comment]
Though I don't know what problem in your code, But I write a Notification demo which contain the pause action button in the notification, and works fine, please try it.
