### ISSUE TITLE
如果项目中也是用 OkHttp, 再加上这个 FileDownloader，是否有可能出现阻塞普通的接口情况？

### ISSUE THREAD

**Issue by gdky005** [lingochamp/FileDownloader#155]
很常见的一个例子，如果项目中使用了 Okhttp 作为请求 Api 的框架，然后再加上 FileDownloader，那么如果有多个下载任务，对于普通的接口情况是否会阻塞？ 

尤其在2/3G 网络情况下，或者是 4G 网络不稳定的情况。

**Comment by Jacksgong** [comment]
不会的。

不过如果你的项目中也是使用okhttp 3.x版本，建议直接使用以下方式，这样代码中不会有多份okhttp:

```
compile ('com.liulishuo.filedownloader:library:0.3.1') {  
  // 保证只引入filedownloader，而不引入okhttp。
  exclude module: 'okhttp'
}
// 这里引入你项目自己要用的任意3.x版本的okhttp
compile 'com.squareup.okhttp3:okhttp:3.2.0'
```

**Comment by gdky005** [comment]
OkHttp 应该也是有线程池的概念，不知道你在这个开源框架里面有没有其他的处理？ 能简单说说原理吗？

**Comment by gdky005** [comment]
OkHttp 里面应该也是有线程池的概念，如果你用了一下下载任务，那么对于其他并发接口，可能就少了一个可用的资源。对于这里你是怎么做的呢？ 能否简单说说。谢谢

**Comment by Jacksgong** [comment]
这里提到的网络资源或者是i/o资源其实是全局的，但是站在应用层面目前在okhttp 3.x中是每个 okHttpClient 相互独立的。因此不会有影响。

FileDownloader 中也有非常多的线程池，有些用于通信，有些确实是用于网络相关，比如你可以配置 [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties) 来调配 用于网络通信的并发线程数 `download.max-network-thread-count`，默认值是3个。

**Comment by gdky005** [comment]
Ok ,你这么一说就明白了，谢谢哈。只要控制好 下载线程的个数 就不会造成阻塞。如果配置过多线程，在3G 网络下确实会出问题，并且可能导致低配手机卡顿。

**Comment by Jacksgong** [comment]
如果你谈到的是UI线程掉帧相关的，FileDownloader已经有处理，默认是打开的，你可以看下  `FileDownloader.enableAvoidDropFrame()`。
