### ISSUE TITLE
Deprecated init()

### ISSUE THREAD

**Issue by seransaca** [lingochamp/FileDownloader#159]
Good morning,
I'm going to implement this library in my application and when I go to initialize it, the init() method tells me is deprecated. I would like to know how to initialize this library as it worked before but now I do not know if anything has changed in that function.

Thank you and I hope your answer

**Comment by Jacksgong** [comment]
:) Good morning, There is nothing has been changed(https://github.com/lingochamp/FileDownloader/blob/master/library/src/main/java/com/liulishuo/filedownloader/FileDownloader.java#L98), as you know the old function needs param Application, but in fact, we just need Context, so consider more make sense, and compatibility, we just deprecated the old function.

```
/**
 * @deprecated Consider use {@link #init(Context)} instead.
 */
public static void init(final Application application) {
    init(application.getApplicationContext());
}

/**
 * @deprecated Consider use {@link #init(Context, FileDownloadHelper.OkHttpClientCustomMaker)}
 * instead.
 */
public static void init(final Application application,
                        FileDownloadHelper.OkHttpClientCustomMaker okHttpClientCustomMaker) {
    init(application.getApplicationContext(), okHttpClientCustomMaker);
}
```

**Comment by seransaca** [comment]
Ok thanks, but a have a problem, I initialize thus:
`FileDownloader.init(this, okHttpClientCustomMaker);`

And he tells me that the variable "okHttpClient Custom Maker" does not know, so I think before sending as a param thus:
`FileDownloadHelper.OkHttpClientCustomMaker okHttpClientCustomMaker;`

But in this case it tells me I have to initialize the variable

What would be the correct way to call the function init () in my application?

Thank you very much for your kind and quick willingness to help others CONGRATULATIONS

**Comment by Jacksgong** [comment]
I think you can quick see this: [DemoApplication.java](https://github.com/lingochamp/FileDownloader/blob/master/demo/src/main/java/com/liulishuo/filedownloader/demo/DemoApplication.java#L30)

But there isn't has to provide a [OkHttpClientCustomMaker](https://github.com/lingochamp/FileDownloader/blob/98ec80fedd5c29bfebc4061d1a3460d09d37e56e/library/src/main/java/com/liulishuo/filedownloader/util/FileDownloadHelper.java#L54) if you don't need to customize it, so in this case just invoke feel free: `FileDownloader.init(getApplicationContext())`.

**Comment by seransaca** [comment]
ok thanks you very much
