### ISSUE TITLE
Video download

### ISSUE THREAD

**Issue by franciscerio** [lingochamp/FileDownloader#16]
I tried video download but it cant continue the last breakpoint/soFarBytes. Is this possible?

Thanks.

**Comment by Jacksgong** [comment]
Please check whether your `FileDownloadListener#connected` with the non nil `ETag` back.

**Comment by franciscerio** [comment]
I tried to download a video but the etag is always nil but if image not nil.

**Comment by Jacksgong** [comment]
So sorry, `ETag` is carry back by the response's header, I think you should ask your back-end colleague for help.  

> ps: Support for Resume Breakpoint because `ETag`.

**Comment by franciscerio** [comment]
ohhh. i see. cool! I think all of the sample images have ETags. :)

Thanks!

**Comment by Jacksgong** [comment]
Good luck. :)

**Comment by franciscerio** [comment]
Hi @Jacksgong does cache control matters? like public or private.

This is my error.

`response code error: 500, 
 request headers: If-Match: "asset-12c1031-3c834c-52c187443f040"
Range: bytes=723115-
Cache-Control: no-cache
 
 response headers: Server: nginx/1.8.1
Date: Tue, 08 Mar 2016 03:03:07 GMT
Content-Type: text/html
Content-Length: 19229
Connection: keep-alive
Cache-Control: private, must-revalidate
Set-Cookie: laravel_session=eyJpdiI6ImtyVFZcL3dOU0d1XC9tTW92N2FDQzFRQT09IiwidmFsdWUiOiIranFFbUhXaHVwc1RMZVlWNWhQVmVhKzZjXC9TZFhTa3FoNzZSbVVXc1JXWW9pMnljT2l4eWV5dDdERFRVaDZmOTI2QjBHalNMdENzdXVadXk2T3psekE9PSIsIm1hYyI6IjE0OGNkOTA4Njg1NjA4Y2UzZjM0Yzc5MjU1OGMwNGZjNWIwY2YxNzdjMGY2OTYyZDA3YzZmNWQ0Y2VjMmUwNGMifQ%3D%3D; expires=Tue, 08-Mar-2016 05:03:07 GMT; Max-Age=7200; path=/; httponly
Last-Modified: Wed, 12 Feb 2014 19:04:52 GMT
Accept-Ranges: bytes
OkHttp-Sent-Millis: 1457406184805
OkHttp-Received-Millis: 1457406185253`

We tried cache control private but no luck. We are new in caching stuffs. 

Thanks

**Comment by Jacksgong** [comment]
The `Cache-Control` is just for OkHttp, and we already save the response content to our path, so we don't need and Cache by OkHttp.

P.S: `response code error: 500` means: Remote Server Internal Error(Ref. [HTTP Error 500 Internal server error](http://www.checkupdown.com/status/E500.html) ), Not our Application's fault.
