### ISSUE TITLE
下载如何提速（局域网）

### ISSUE THREAD

**Issue by changjiashuai** [lingochamp/FileDownloader#160]
局域网速度是3M/s ，为什么下载是935.93KB/s 有办法提速吗?

**Comment by Jacksgong** [comment]
你用的是最新的 `0.3.1` 吗？

**Comment by Jacksgong** [comment]
1. 保证你使用的最新版本的FileDownloader 0.3.x版本对速度做过优化。
2. 参考这里: https://github.com/lingochamp/FileDownloader/issues/150#issuecomment-219220078

**Comment by changjiashuai** [comment]
0.3.1 有问题 暂停后状态是下载完成的， 用的0.2.0 参考#150设置过了不起作用？ 下载速度你是根据文件大小判断的吗？

**Comment by Jacksgong** [comment]
@changjiashuai 如果暂停的瞬间（或者完成已经在消息流中）已经完成，你点击暂停，肯定还是完成的。具体你可以参考下demo。之前有版本确实 filedownloader.properties配置是有问题的，建议升级到最新版本以后进行配置。
