### ISSUE TITLE
退出Activity，再进入，看不到进度更新

### ISSUE THREAD

**Issue by MaXiaoWu2015** [lingochamp/FileDownloader#165]
你好，我在写的程序是仿造你Demo中的TaskManagerDemo的，用的也是RecyclerView，但是当我在有任务下载的时候退出Activity，再进入的时候，任务的进度就不更新了，但是打印log，任务确实还在下载

**Comment by Jacksgong** [comment]
恩。如果是TaskManagerDemo，确实是并没有覆盖这种情况的，TaskManagerDemo再退出页面的时候就暂停了所有的下载。

对于TaskManagerDemo来说，如果退出时没有暂停任务，那么再进入也不会有进度，是**因为**:


下载回调的 `FileDownloadListener` 在之前退出的Activity对象(我们将其简称为`对象A`)的中，而新进入的Activity对象（我们将其简称为`对象B`）并不会收到之前的任务的回调。 （这里其实还有引入另外一个问题，那就是在对象A中启动的任务还没有结束之前，都会对 对象A进行泄漏）。

---

如果需要满足你想要的功能，就需要你自己将 下载监听器管理起来。具体小demo可以参考这里:https://github.com/lingochamp/FileDownloader/issues/4#issuecomment-168692266

**Comment by MaXiaoWu2015** [comment]
你好，我昨天按照#4 里的方法试了一下，但是并没有成功，下面是我对那个更新界面接口的实现，我是在Adapter中定义的，在Adapter构造函数里addUpdater(mDownloadUpdater); 在Activity的onDestroy进行remove，请问还有其他的我没有注意的地方吗
`public DownLoaderManager.DownloadUpdater mDownloadUpdater=new DownLoaderManager.DownloadUpdater(){

    @Override
    public void update(BaseDownloadTask task)
    {
        int status=task.getStatus();
        Log.d(TAG, "update: ");
        DownLoadViewHolder holder= (DownLoadViewHolder) task.getTag();
        switch (status) {
            case FileDownloadStatus.pending:
                holder.tv_state.setText(R.string.wait_download);
                holder.tv_completed.setText("");
                holder.btn_operation.setText(Utils.getStringFromRes(mContext,R.string.pause));
                break;

            case FileDownloadStatus.progress:
                int soFarBytes=task.getSmallFileSoFarBytes();
                int totalBytes=task.getSmallFileTotalBytes();
                int progress=soFarBytes*100/totalBytes;
                holder.tv_completed.setText(progress+"%");
                holder.tv_state.setText(R.string.downloading);
                holder.tv_speed.setText(Utils.getSpeedStr(task.getSpeed()));
                holder.tv_size.setText(Utils.getDataSize(totalBytes));
                holder.btn_operation.setText(Utils.getStringFromRes(mContext,R.string.pause));
                Log.d(TAG, "update: progress"+progress);
                if (holder.once)
                {
                    updateTaskTotalSize(totalBytes,holder);
                }

                break;
            case FileDownloadStatus.paused:
                holder.tv_state.setText(R.string.pause);
                holder.tv_completed.setText("");
                holder.tv_speed.setText("");
                holder.btn_operation.setText(Utils.getStringFromRes(mContext,R.string.continue_download));

                updateTaskState(FileDownloadStatus.paused,holder.getPosition());

                break;
            case FileDownloadStatus.completed:
                holder.tv_state.setText(R.string.completed);
                holder.tv_completed.setText("");
                holder.tv_speed.setText("");

                updateTaskState(FileDownloadStatus.completed,holder.getPosition());

                break;
            case FileDownloadStatus.error:
                holder.tv_state.setText(R.string.failed);
                holder.tv_completed.setText("");
                holder.tv_speed.setText("");
                holder.tv_size.setText(Utils.getStringFromRes(mContext,R.string.unkown_size));
                holder.btn_operation.setText(Utils.getStringFromRes(mContext,R.string.download_again));

                updateTaskState(FileDownloadStatus.error,holder.getPosition());
                break;


        }
    }

};`

**Comment by MaXiaoWu2015** [comment]
`updateTaskState(FileDownloadStatus.error,holder.getPosition());`
这个方法是用来在数据库中记录任务状态的

**Comment by Jacksgong** [comment]
首先 https://github.com/lingochamp/FileDownloader/issues/4#issuecomment-168692266 的原理就是让 `FileDownloadListener` 与`Activity`对象解耦，就如之前的方案（没有那个 https://github.com/lingochamp/FileDownloader/issues/4#issuecomment-168692266 中的Manager）Activity没关就始终有回调，同样的道理，放到https://github.com/lingochamp/FileDownloader/issues/4#issuecomment-168692266 中的Manager中后，只要 https://github.com/lingochamp/FileDownloader/issues/4#issuecomment-168692266 中的 Manager 没有释放对应的监听之类的，就始终会有回调了，**除非任务都结束了**。

---

你再认真检查下你的代码到底是哪里出了问题，如果始终找不到原因，根据你自己的代码写一个复现你问题的简单的 demo project，通过邮件 (igzhenjie@gmail.com) 或者是开源的方式，我抽空给你看看问题所在。

**Comment by MaXiaoWu2015** [comment]
我把代码发到你的邮箱了，麻烦了

**Comment by Jacksgong** [comment]
@MaXiaoWu2015 麻烦你建一个demo project 发给我，你发一个Adapter与Manger我这里很难定位到问题。我需要跑起来看看，这个和调用关系很有关系。

**Comment by MaXiaoWu2015** [comment]
现在问题已经解决，原因是我task.setTag()时，将ViewHolder作为Tag，具体原理我还没有弄明白，但是我将Tag换成Position，就可以显示了，十分感谢您的解答！

**Comment by Jacksgong** [comment]
:) OK.
