### ISSUE TITLE
Don't close the service at the end

### ISSUE THREAD

**Issue by seransaca** [lingochamp/FileDownloader#166]
Good I have encountered a problem, I use the library as a service or intentService and performs well the download process, but when I close the application looks like redownload.

What is not is whether if there is any way to stop the service completely discharge, since I find it strange that "continue downloading"

a greeting

**Comment by Jacksgong** [comment]
OK, First of all, If you don't like FileDownloadService in the separate process to UI process, you can set `process.non-separate` in [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties).

And If you want to unbind the FileDownloadService, just feel free to invoke `FileDownloader#unBindService()`, then if the FileDownloadService has bound, it would be unbound immediately, but If you want to release all resources in FileDownloadService, it's recommended invoke `FileDownloader#pauseAll()` before unbinding the service. Finally, for the process, it doesn't mean that the process would be killed immediately when without any Android component(like Service) on it.

**Comment by seransaca** [comment]
I didn't understand very well what you told me, I tried it and it did not work.

The only way I had to stop the service using the Library is doing a `nameActivity.stopSelf()`.

Thank you so much

**Comment by Jacksgong** [comment]
Whether it has been OK for you?

**Comment by seransaca** [comment]
yes

**Comment by Jacksgong** [comment]
OK. Nice.
