### ISSUE TITLE
setForceReDownload Not Work

### ISSUE THREAD

**Issue by Jacksgong** [lingochamp/FileDownloader#169]
@244317809 

---

The `BaseDownloadTask#setForceReDownload` not work. If `setForceReDownload(true)` it will call-back `warn` when it has already downloaded, And in this case for the task has already downloaded the right logic would redownload the task.

**Comment by 244317809** [comment]
你好，请问这个fix了这个bug的版本什么时候放出来，或者说我该怎么应用新的代码？

**Comment by Jacksgong** [comment]
这周会上一个新版本。如果你比较紧急等待这个版本，我可以先发一个beta版本，然后你下载beta的aar导入项目即可。很紧急吗？

**Comment by 244317809** [comment]
还好，也不是太紧急，可以在这周内。因为经过测试，0.3.x 的下载速度比 0.2.x 快很多，所以想尽快使用新的版本。

还有一个问题，我可以控制全局的FileDownloader只串行，不并发下载吗？目前只看到某一次批量下载可以指定是否串行 `FileDownloader.getImpl().start(listener, true)` , 问题比较多，先谢谢你。

**Comment by Jacksgong** [comment]
好的。可以的。

你在 [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties) 中配置 `download.max-network-thread-count=1`，这样即便是再多任务，对于全局而言也只能有一个网络线程，就是全局串行下载了。

**Comment by 244317809** [comment]
这个filedownloader.properties是否只在新版本有效？我目前用的 0.2.0 版本貌似设置了没作用。

**Comment by Jacksgong** [comment]
是的。最新版本有。0.2.0还不支持。

**Comment by 244317809** [comment]
很好，那两个问题都会在新版本中得到解决，静待新版本的发布，希望快点，感谢！

**Comment by Jacksgong** [comment]
@244317809 你改用，线上最新的版本就已经支持 filedownloader.properties配置的，不用等这个版本发布。

**Comment by Jacksgong** [comment]
Fixed since [v0.3.2](https://github.com/lingochamp/FileDownloader/releases/tag/v0.3.2).
