### ISSUE TITLE
filedownloader E/MscSpeechLog: init failed, please call this method in your main process!

### ISSUE THREAD

**Issue by MrLiKH** [lingochamp/FileDownloader#170]
![qq20160602-0 2x](https://cloud.githubusercontent.com/assets/8737484/15738450/e560b782-28dd-11e6-9317-3db25c06469d.png)

您好 请教一个问题我的程序老是出现
filedownloader E/MscSpeechLog: init failed, please call this method in your main process!
这个错误，不知道什么原因，没有影响使用 
还有就是图中的报错，是什么意思啊 求指教

**Comment by Jacksgong** [comment]
`filedownloader E/MscSpeechLog: init failed, please call this method in your main process!` 这个是讯飞报的。你是有用讯飞吗，FileDownloader没有报过这种异常。

下面的`MessageReceiver.receive`的npe已经在 0.3.1修复了。请更新到最新版本。
