### ISSUE TITLE
退出下载列表，后台下载任务，再重新启动下载页面 能否实现任务进度正常更新

### ISSUE THREAD

**Issue by renfu8888** [lingochamp/FileDownloader#171]
1，在TasksManagerDemoActivity 里一个下载列表展示需要下载几个文件，点击其中一个item 的开始按钮后任务正常执行。
2，现在按下返回键回到主页面（在退出后不调用pauseAll()方法，也不unbindService（））我这边log信息看到还是有任务在下载还有进度信息（这是正常的）
3，现在再点击进入TasksManagerDemoActivity 这个页面，能否实现 点击返回按钮之前页面上显示的那个任务继续下载并且正常更新进度的功能呢（目前是只有下载完成的时候会显示正常，但是progress的时候进度条不走，viewHolder对象都在 position位置也对 task！=null 但是进度条就是不走，按下暂停也不管用（实际上任务已经暂停 但是页面展示不对））请指教，要是我描述不清，我可以把改写后的demo给你发过去。PS：我使用了FileDownloader.getImpl().replaceListener(task.getId(), taskDownloadListener);这个方法设置监听

**Comment by Jacksgong** [comment]
你参考这个: https://github.com/lingochamp/FileDownloader/issues/165#issuecomment-222299118

**Comment by renfu8888** [comment]
谢谢。这个问题我前几天已经解决了（需要调用 task.settag（null）task.setListener(null)）防止内存泄漏（因为viewHolder和downloadListener 拿着adapter的引用间接拿着activity/fragment的引用 ）但是问题又来了
会抛出一个空指针的问题 具体代码是FileDownloadMessenger 的255行代码 task.getListener().callback(message); 麻烦看一下。

**Comment by Jacksgong** [comment]
是这样的，如果你的任务在Activity/Fragment已经结束以后(`onDestroy`/onDetach`)还需要在运行，不建议将这个监听器定义在某个Activity/Fragment对象里面（如果是内部静态类是没有问题的），而是维护一个与Activity/Fragment对象无关的 Listener管理器，这个可以参考这里: https://github.com/lingochamp/FileDownloader/issues/4#issuecomment-168692266

----

在任务已经结束的时候(`error`/`paused`/`completed`/`warn`)，任务会直接被孤立(会在FileDownloader中完全释放)，是不会存在内存泄漏的。

**Comment by Jacksgong** [comment]
FileDownloadMessenger 的255行在任务运行时设置Listener的这个NPE，我会处理的。谢谢~。:)

**Comment by Jacksgong** [comment]
[这个NPE](https://github.com/lingochamp/FileDownloader/issues/171#issuecomment-226110474) 已经修复了，会在下个版本带上，还有任何的问题与建议，重新开新的Issue即可。:)

**Comment by renfu8888** [comment]
好的 我在我的测试中又发现一个新问题 我也看下你消息处理的源码看看能不能找出问题，我给你开个新的issue描述一下这个问题。

**Comment by Jacksgong** [comment]
Fixed since [v0.3.3](https://github.com/lingochamp/FileDownloader/releases/tag/v0.3.3).
