### ISSUE TITLE
Error or Warn in download

### ISSUE THREAD

**Issue by seransaca** [lingochamp/FileDownloader#173]
Hi,
I would like to know in which case the system / library downloads stops completely to show that there has been a problem, or to restart the download.

I know that there are a number of retries but do not know that exact time is stopped and does not return to retry.

Thanks and sorry for the disturbances

**Comment by seransaca** [comment]
When you download service reaches the listener method "warn" the file download or not?
Because in the "error" I do know that retries the number of times you have been instructed, but I have not very clear "warn"

**Comment by Jacksgong** [comment]
OK, If you receive the listener method "warn", It means that the task is redundant, because of there is the same task(the same path to store the file, and the same downloading URL) has already been started in FileDownloader, and it is in downloading or in pending queue currently.

**Comment by seransaca** [comment]
ok thanks.
When there is an error and the number of retries is completed, the library stops working? It is to display a message that there has been an error and restart the app or some action

**Comment by Jacksgong** [comment]
You mean crash(restart the app)? Please provide crash log, let me check it.

**Comment by seransaca** [comment]
There is no problem with your application. I said that to be an error in the download, how could be detected to warn the user that a file has not been downloaded correctly

**Comment by seransaca** [comment]
I what I want is that in the case of not downloaded a file by mistake, it will send a notice to the user of my own application so you know you have to try again.

Thanks!!

**Comment by Jacksgong** [comment]
Sorry, If you want to notice to the user, just do that. And if you want to try to download again, just start the new one.

**Comment by seransaca** [comment]
ok thanks
