### ISSUE TITLE
数据库中的下载数据会定时清除吗？

### ISSUE THREAD

**Issue by mcshengInworking** [lingochamp/FileDownloader#176]

**Comment by Jacksgong** [comment]
目前是下载服务启动的时候，会扫一遍，所有[无用的数据都会清除一遍](https://github.com/lingochamp/FileDownloader/blob/06be971b5a4a7480206bf6a396881fc87d38d26c/library/src/main/java/com/liulishuo/filedownloader/services/FileDownloadDBHelper.java#L63)。

**Comment by mcshengInworking** [comment]
// consider check in new thread, but SQLite lock | file lock aways effect, so sync
                if (model.getStatus() == FileDownloadStatus.pending) {
                    //脏数据 在数据库中是pending或是progress，说明是之前
                    dirtyList.add(model.getId());
                } else if (!FileDownloadMgr.checkReuse(model.getId(), model)
                        && !FileDownloadMgr.checkBreakpointAvailable(model.getId(), model)) {
                    // can't use to reuse old file & can't use to resume form break point
                    // = dirty
                    dirtyList.add(model.getId());
                }

从这里可以看出是将需要删除的数据加入dirtyList中，但是为啥pending状态的的数据也要删除？

**Comment by Jacksgong** [comment]
👍 其实最早这么写的时候，是考虑到如果一个任务还在 `pending` 中的话，那么这个任务肯定没有开始，那这个任务的存储是没有意义的，为了减少数据的压力，所以就将其也删除了。


其实我刚刚认真思考了下，有可能是一个断点续传的任务重新被抛到 `pending` 队列中，因此这里可能会在小概率下（比如一个断点续传任务被暂停了以后又被启动，而刚好前面已经有很多任务在运行了这个 断点续传的任务还在 `pending`队列中，此时下载服务被强杀了）导致一个断点续传任务因为数据被清除导致，失效。

我会将这边的条件缩紧，立马修复这个bug。多谢你的反馈。

**Comment by mcshengInworking** [comment]
同时在checkReuse方法里面发现：

if (model.getStatus() != FileDownloadStatus.completed) {
                // 数据状态没完成
                if (FileDownloadLog.NEED_LOG) {
                    FileDownloadLog.d(FileDownloadMgr.class, "can't reuse %d status not completed %s",
                            downloadId, model.getStatus());
                }
                break;
            }

当状态不为completed时返回false，表示不可以使用，正确的逻辑不应该是状态为completed时，返回false吗？表示已下载完成，不再需要重复下载。

**Comment by Jacksgong** [comment]
@mcshengInworking `FileDownloadMgr#checkReuse` 的返回值的含义是: 是否可以复用。这里没有问题。

**Comment by mcshengInworking** [comment]
当状态不为completed就不被复用，为completed就能够被复用？我的理解是下载完成之后就不需要重复下载了吧

**Comment by Jacksgong** [comment]
不是的，你认真看看这里的逻辑。

这里的逻辑是这样的:

```
A. 数据库中的状态不是 `completed`
B. 文件不存在
C. 脏数据
D. 无效文件
```

满足A、B、C、D任意条件皆表示 该次任务需要重新下载，旧的已下载文件是无效文件不可复用。

> P.S: 当然这里的判断并不能决定是否可以断点续传。

**Comment by Jacksgong** [comment]
@mcshengInworking [这个](https://github.com/lingochamp/FileDownloader/issues/176#issuecomment-225773719) bug 已经修复了，会在下个版本带上（发布时我会到这个issue评论的），还有任何其他问题，直接提新的issue即可。多谢你的关注。

**Comment by mcshengInworking** [comment]
数据库中的状态不是 `completed`时，checkReuse方法返回的是false，为completed时，返回的是true。


false表示需要重新下载？true表示不需要重新下载？

**Comment by Jacksgong** [comment]
数据库中的状态不是 `completed`时，会立马返回 `false` 表示需要开启该任务，也就是需要重新下载。
数据库中的状态为 `completed` 时，会进入下一轮的条件判断。

**Comment by Jacksgong** [comment]
你捋一捋，这里其实是这样的:

根据这里提到的A~E的条件 ， `checkReuse` 的逻辑是：

```
/**
 * @return 已经下载的已存在的该任务是否是有效并可以复用.
                 如果是{@code true} : 是有效的可以复用，因此不需要再启动该任务默认情况下直接返回 完成
                 如果是{@code false}: 是无效的或者不存在，因此需要启动该任务进行下载。
public boolean checkRuse(){

  if(A||B||C||D||E){
     return false;
  } else {
     return true;
  }
}
```

**Comment by Jacksgong** [comment]
当然在[解决前几天的一个issue](https://github.com/lingochamp/FileDownloader/issues/172)中，由于新的架构体系，引入了下载中的文件名(.temp)与下载结束的文件名不同，因此这块逻辑会考虑因此进行简化，包括为数据库减压之类的优化。

**Comment by mcshengInworking** [comment]
状态为completed时，表示文件已经下载完成，此时没有将这个数据加入dirtyList，那这个数据记录不是会留在数据库里？什么时候会将它从数据库中删除？

**Comment by Jacksgong** [comment]
是的。状态为 `completed` 的有效数据会一直留在数据库中，为了判定本地已经下载的那个文件是否是有效存在。

---

## 原因:

主要是因为以下原因至今没有进行这块的维护:

1. 由于之前整个下载过程都是存储在同一个文件(`BaseDownloadTask#path`路径)，而FileDownloader在下载之初就pre-alloc整个文件大小(防止下载过程中突然发现磁盘空间不足)的文件用于存储下载文件（这样一来无论文件已经下载了多少，文件的`length`始终是等于下载完成的文件大小`content-length`），因此判定文件是否是有效的无损的就十分依赖数据库中的状态等数据。
2. 这块到目前为止一直不是FileDownloader的瓶颈所在，主要是[如果已下载的文件被删除了](https://github.com/lingochamp/FileDownloader/blob/e9655c4a8b3df9b4c73800d90498717236144a33/library/src/main/java/com/liulishuo/filedownloader/services/FileDownloadDBHelper.java#L113)，即便是`completed`也会被添加到`dirtyList`的。并且我们通过测试发现如果确实是对于FileDownloader达到几千个有效存在的完整的文件，数据的初始化加载也会在个位数秒级别，并且由于是简单的数据结构，内存占用依然非常小，对内存中的Map的Index性能没有影响。而对于单一的Android应用而言(说实话我们自己的应用(英语流利说核心课程中)部分用户这块数据一直是几千个的体量，都是各类小的题型文件)，突破上千个完整的已下载的文件体量已经非常大，可能性非常小（考虑到用户手机的磁盘大小以及体量，即便是完全用于下载的应用 迅雷也很少有说有Android用户有上万的下载，并且这些下载文件都没有被删除）。
3. 一直得不到一个非常万全的解决方案。由于考虑到到后面这块是会成为瓶颈，其实是有考虑对这类数据进行一月为有效期进行维护(可以看看之前写的TODO(FileDownloadDBHelper中的))。但很显然这并非一个非常好的解决方案。

---

## 解决方案

目前的打算处理方案:

其实你可以看到最新的代码我将那个[FileDownloadDBHelper中的TODO删除了](https://github.com/lingochamp/FileDownloader/commit/bf8be9d006ba6832ad16a9e17d0da2f88d91f2ed#diff-71b33dd324a94263c77478eee42cfa94L59)，一方面是我考量之前那个策略并不是一个十分好的策略，另一方面是因为前几天的重构使得这块已经有了一个更好的处理方案。

因此我是有打着小算盘的，正如我刚刚[评论所说](https://github.com/lingochamp/FileDownloader/issues/176#issuecomment-225788927)的。在前几天的一个重构中，我将下载过程中对文件的存储路径由原来的`path`改为了`tempPath`， 也就是说，这样使得对于未完成的任务其实一直是存储在一个临时文件中，而这个下载过程中的存储路径与下载完成后存储路径不同的机制，**恰恰可以使得是否是有效下载完成文件的判断可以摆脱数据库的依赖**，目前这个机制已经完成，因此这块数据的减压优化也是我接下来有打算做的。

**Comment by Jacksgong** [comment]
Fixed since [v0.3.3](https://github.com/lingochamp/FileDownloader/releases/tag/v0.3.3).
