### ISSUE TITLE
Crash when FileDownloader#pause

### ISSUE THREAD

**Issue by lct8712** [lingochamp/FileDownloader#177]
Hi

I'm using FileDownloader in my app, and a crash was reported as following. 

![2016-06-14 17 02 47](https://cloud.githubusercontent.com/assets/2209588/16037205/0dfdf632-3252-11e6-82be-e82c9915ecc5.png)

Do you have any suggestion to fix this?
Thank you.

**Comment by Jacksgong** [comment]
Yes, This crash already fixed since v0.3.2.

It occurred when the download service has not been connected yet, by [this commit](https://github.com/lingochamp/FileDownloader/commit/bc5643f971862764b5f8d0a11671063efde668c4).
