### ISSUE TITLE
Can i still use okhttp 3.2.0?

### ISSUE THREAD

**Issue by niejunhong** [lingochamp/FileDownloader#179]
I want exclude FileDownloader’s okhttp in my gradle.
because i use retrofit in my same project,retrofit still in okhttp 3.2.0
I checked your new commit, in 0.3.2 version ,there is no code to about okhttp 3.3.1.
Is safe to exclude the okhttp in FileDownloader?

**Comment by Jacksgong** [comment]
Yes, It is safe to exclude the okhttp in FileDownloader, and using any 3.x version okhttp(such as 3.2.0, what you want).
