### ISSUE TITLE
你好，你的demo里面的library这个modulce我总是引用不了

### ISSUE THREAD

**Issue by itcheng** [lingochamp/FileDownloader#18]
我下载了你的demo代码，我现在写代码过程中，在你的MainActivity里面有这句FileDownloadMonitor.setGlobalMonitor(GlobalMonitor.getImpl());，我就引用你demo里的library。但是引用library总是会报错呀！

android {
    compileSdkVersion COMPILE_SDK_VERSION as int
    buildToolsVersion BUILD_TOOLS_VERSION as String

    defaultConfig {
        minSdkVersion 8
        targetSdkVersion COMPILE_SDK_VERSION as int
        versionCode VERSION_CODE as int
        versionName VERSION_NAME as String
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile 'com.squareup.okhttp3:okhttp:3.0.1'
}

apply from: 'https://raw.githubusercontent.com/Jacksgong/JCenter/master/license.gradle'

if (isForUpload2Maven()) {
    println ':library:include upload 2 maven methods'
    apply from: 'https://raw.githubusercontent.com/Jacksgong/JCenter/master/installv1.gradle'
    apply from: 'https://raw.githubusercontent.com/Jacksgong/JCenter/master/bintrayv1.gradle'
}

这段代码是在我的工程也是报错的，后来我改成我自己工程里面的

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "com.baimes.myapplication"
        minSdkVersion 14
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile 'com.squareup.okhttp3:okhttp:3.0.1'
}

apply from: 'https://raw.githubusercontent.com/Jacksgong/JCenter/master/license.gradle'

if (isForUpload2Maven()) {
    println ':library:include upload 2 maven methods'
    apply from: 'https://raw.githubusercontent.com/Jacksgong/JCenter/master/installv1.gradle'
    apply from: 'https://raw.githubusercontent.com/Jacksgong/JCenter/master/bintrayv1.gradle'
}

还是总报错，并且你demo里面的library，总是无法再我的工程里面把他设置成modulce。。。还请多多指教，说明一下

**Comment by itcheng** [comment]
方便加我下QQ么？1617044578，希望跟你沟通一下

**Comment by Jacksgong** [comment]
恩。请问，你用的是ant编译，还是gradle编译呢? (or eclipse 还是 Android Studio/Idea?).

**Comment by Jacksgong** [comment]
我加你q了。
