### ISSUE TITLE
怎么使用这个库进行大文件的多线程分段下载

### ISSUE THREAD

**Issue by helloyxc** [lingochamp/FileDownloader#180]
您好，能不能提供一些简单的代码帮忙描述下：怎么使用这个库进行大文件（比如500M视频）的多线程分段下载？

**Comment by Jacksgong** [comment]
如果要在上层实现可能需要涉及到需要后端配合。因此这个最好是FileDownloader内部去实现，很早的时候就有类似issue了，只是这个的优先级比较低，在后面的几个版本中，我会加入这个功能的，你可以关注下这个issue即可: #102

**Comment by Jacksgong** [comment]
已经支持分块下载，参考 https://github.com/lingochamp/FileDownloader/issues/102#issuecomment-306016976 近期版本会带上。
