### ISSUE TITLE
下载进度更新消息滞后问题（请看具体描述）

### ISSUE THREAD

**Issue by renfu8888** [lingochamp/FileDownloader#181]
1，我是后台执行下载任务（用户离开了下载页面此时其中一个任务进度更新到20%）
2，离开下载页面5秒后重新进入下载页面，给所有的task重新设置listener（task.setListener(taskDownloadListener);）然后下载进度却继续从20 + 1%的位置开始更新（实际已经可能40%的进度了）
这个问题麻烦您看下，我也看下源码看能不能找到问题，谢谢~

**Comment by Jacksgong** [comment]
首先。我非常不推荐这种替换listener的方式来管理监听，一方面使得很多重要的监听数据漏掉，另一方面不方便未来维护时候的管理。再次推荐下采用这种方式: https://github.com/lingochamp/FileDownloader/issues/4#issuecomment-168692266

---

你说的这种情况，从目前的代码上来看似乎是不科学的，因为内部不知道你什么时候退出了什么页面，更不会去缓存说那时候的进度是多少。你先看看，如果实在找不到原因，你建立一个单独的项目，简单的实现下让那个项目可以复现你的问题，然后发邮件给我(igzhenjie@gmail.com)，我抽空给你看下。

**Comment by renfu8888** [comment]
嗯 好的
