### ISSUE TITLE
I cant access .getSofar(), .getTotal(), .getPaused() after binding and Filedownloader.start()

### ISSUE THREAD

**Issue by franciscerio** [lingochamp/FileDownloader#182]
Hello, 

I followed your demo application.
[https://github.com/lingochamp/FileDownloader/blob/master/demo/src/main/java/com/liulishuo/filedownloader/demo/TasksManagerDemoActivity.java](url). 

This is my bindServices and it is already connected. 
 ```
private void bindServices() {
        FileDownloader.getImpl().bindService();

        if (listener != null) {
            FileDownloader.getImpl().removeServiceConnectListener(listener);
        }

        listener = new FileDownloadConnectListener() {

            @Override
            public void connected() {
                Logger.e(TAG, "CONNECTED");
            }

            @Override
            public void disconnected() {
                Logger.e(TAG, "CONNECTED NOT");
            }
        };

        FileDownloader.getImpl().addServiceConnectListener(listener);
    }
```

This is my FileDownloader.start()
```
 FileDownloader.getImpl().create(stance.getMedia().getUrl()).setTag(holder).setForceReDownload(true)
                .setPath(path).setCallbackProgressTimes(300).setAutoRetryTimes(3)
                .setListener(downloadListener).start();
```
I cant access or always 0 in sofar, total bytes, pause and etc. I used the new gradle ` compile 'com.liulishuo.filedownloader:library:0.3.2'`. I also copied the filedownloader.properties. Did I miss something?

**Comment by franciscerio** [comment]
Oh my bad. I'm using aws url link that will always change url because of expire date. Download ID will always be unique. Thanks

**Comment by Jacksgong** [comment]
:)
