### ISSUE TITLE
批量下载时候，怎么判断全部已经下载完毕？或者其中某些下载失败（也算是下载完成）

### ISSUE THREAD

**Issue by dwdyoung** [lingochamp/FileDownloader#186]

**Comment by Jacksgong** [comment]
首先，你可以通过FileDownloadListener 中的 `error`/`paused`/`completed`/`warn`这些结束回调的总数是否等于你的任务总数来判断。其次，也可以通过 `BaseDownloadTask.FinishListener`的`over`回调次数是否等于你的任务总数据来判断。

这块恰好比较类似之前有一个issue提问，如何同步下载（这里也需要判断结束），可以参考下: https://github.com/lingochamp/FileDownloader/issues/27#issuecomment-179881455
