### ISSUE TITLE
貌似默认没有缓存，也不知道怎么设置缓存

### ISSUE THREAD

**Issue by duckAndroid** [lingochamp/FileDownloader#189]
比如我已经下载了一个文件，下次下载同一个文件，还是会去网络下载。并不会直接找到我的本地文件。 【我的下载路径没有改变】。请问该如何设置才能避免重复下载？

**Comment by Jacksgong** [comment]
我在demo中并没有发现有出现这个问题。建议你clone项目下来看看。对比下你的问题是出在哪里。

**Comment by duckAndroid** [comment]
可能是我描述的不够清楚。如果是刚刚下载完成一个文件的时候，在当前页面，继续点击下载，会直接打开文件，不会重复下载。但是，如果退出了app，最好清理进程一下，然后重新回到当前的页面，再次，点击之前的下载按钮。就会重新下载。
       我不清楚你的内部是怎样实现的，因为内容太多了...。不过我感觉，你可能是在内存中记录了一个变量，如果下载完成之后，该变量flag =true；再次调用下载的时候，就不会重复下载。但是，如果内存被清理，app重启之后，内存的数据变成默认值了，这样就导致了重复下载。
        这个周末看看出现的原因，有发现回你。

**Comment by Jacksgong** [comment]
留意下demo，如果仅仅是内存被清理是不会有这个问题的，任务的下载状态是记录在数据库中是不会丢失的。

如果是应用卸载重装了，是会出现这个问题的。这个时候就可以通过 [FileDownloader.getImpl(). setTaskCompleted](https://github.com/lingochamp/FileDownloader/blob/master/library/src/main/java/com/liulishuo/filedownloader/FileDownloader.java)，将需要置为下载完成的任务重新写入数据库。

**Comment by duckAndroid** [comment]
感谢提醒，之前的确有卸载的情况。我刚刚写了一下Demo。重启app不会导致重新下载。
如果有 FileDownloader.getImpl().setTaskCompleted(url, path, MD5)这样一个方法就更好了。

**Comment by Jacksgong** [comment]
恩。ok!
