### ISSUE TITLE
SocketTimeoutException on large files

### ISSUE THREAD

**Issue by oshanis** [lingochamp/FileDownloader#19]
I get the a SocketTimeoutException on large file downloads. Setting the setCallbackProgressTimes() and setAutoRetryTimes() on FileDownloader.getImpl() to large values did not seem to help. Any advice on how to avoid this exception?

**Comment by Jacksgong** [comment]
sorry to hear that, can you git me your large file download url, and let me check.

**Comment by Jacksgong** [comment]
and [SocketTimeOutException](http://developer.android.com/intl/zh-cn/reference/java/net/SocketTimeoutException.html): This exception is thrown when a timeout expired on a socket read or accept operation.

---

This is likely to be your network problem or the server problem

**Comment by oshanis** [comment]
This is the URL I am trying to download: "http://apidev.mylingoapp.com/api/download/4/audio"
If I use HTTPURLConnection, it seem to work fine, so I doubt this is a backend issue.

**Comment by Jacksgong** [comment]
ok, get it. 

let me take a look.

**Comment by Jacksgong** [comment]
sorry, I have to sleep now, and I will find the reason and reply you as soon as I can.

**Comment by oshanis** [comment]
I am going to continue with HTTPURLConnection on an AsyncTask. Thanks for the help. It's all good.

**Comment by Jacksgong** [comment]
@oshanis I just tried, it seems fine now.

And last night, in fact, I have tried, do have encountered SoketTimeOutException, I suspect it is because the URL(http://[hide]/api/download/4/audio) establish too slow, and causing Okhttp default 10s timeout.

And I will support new interface to set timeout value in the next version.

**Comment by oshanis** [comment]
Thanks for the response. Yeah, if you can provide a timeout interface in the future that would be great! 
Keep up the good work!

**Comment by Abhijeeth-Hiliyana** [comment]
Hi,
    I know this is an older issue but can you let me know the solution for this as I am facing the same issue on my project.

**Comment by Jacksgong** [comment]
@Abhijeeth-Hiliyana https://github.com/lingochamp/FileDownloader/issues/19#issuecomment-175357036


And now, you can set the timeout, Ref [DemoApplication](https://github.com/lingochamp/FileDownloader/blob/98ec80fedd5c29bfebc4061d1a3460d09d37e56e/demo/src/main/java/com/liulishuo/filedownloader/demo/DemoApplication.java)

**Comment by Abhijeeth-Hiliyana** [comment]
Thanks a lot.
