### ISSUE TITLE
MessageSnapshotFlow NullPointerException

### ISSUE THREAD

**Issue by corerzhang** [lingochamp/FileDownloader#190]
你好，在使用0.2.8版本，遇到下面这个空指针问题，请问是什么原因

java.lang.NullPointerException
com.liulishuo.filedownloader.message.MessageSnapshotFlow.inflow(MessageSnapshotFlow.java:46)
com.liulishuo.filedownloader.services.FileDownloadRunnable.onStatusChanged(FileDownloadRunnable.java:575)
com.liulishuo.filedownloader.services.FileDownloadRunnable.onError(FileDownloadRunnable.java:507)
com.liulishuo.filedownloader.services.FileDownloadRunnable.loop(FileDownloadRunnable.java:304)
com.liulishuo.filedownloader.services.FileDownloadRunnable.run(FileDownloadRunnable.java:176)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
java.lang.Thread.run(Thread.java:838)

**Comment by Jacksgong** [comment]
这个在 0.2.9 上修复了。建议使用最新的0.3.2版本。

**Comment by corerzhang** [comment]
好的，谢谢
