### ISSUE TITLE
等待任务的管理

### ISSUE THREAD

**Issue by xfnbing** [lingochamp/FileDownloader#191]
首先，万分感谢您的分享，其次，想问一下库中可以对任务顺序进行处理么？比如把某个任务提前，把某个任务的位置后移。希望能得到您的回答，谢谢。

**Comment by Jacksgong** [comment]
FileDownloader并不支持调整等待队列的顺序。

但是内部是一个先进先出的等待队列、并且支持移除队列中的任何队列；**因此**可以通过`pause`相关任务(将其从已有队列中移除)，然后再重新启动该任务(加入队尾(重新启动任务(reuse、start)/(重新创建)))，的方式进行相关调整。

**Comment by xfnbing** [comment]
谢谢您的回答。
在任务数比较多的时候这样做效率会较低，会比较耗时，因为需要删除重启整个任务队列，但在不可调整的情况下也不失为一个解决方法。唉····头疼ing
