### ISSUE TITLE
所有下载任务执行完毕后Service并没有关闭

### ISSUE THREAD

**Issue by ancode-cn** [lingochamp/FileDownloader#192]
必须主动调用FileDownloader.getImpl().unBindService()吗？
如果必须主动调用unBindService，那么就需要维护一个下载列表，当全部任务执行完毕（不管成功失败）
后执行unBindService，让服务停止。

**Comment by Jacksgong** [comment]
是的。为了避免重复的启动关闭服务，FileDownloader是不会主动关闭下载服务的。需要上层业务，主动调用`FileDownloader.getImpl().unBindService()` 或 `FileDownloader.getImpl().unBindServiceIfIdle()`。
