### ISSUE TITLE
关于下载服务关闭

### ISSUE THREAD

**Issue by MrLiKH** [lingochamp/FileDownloader#194]
如果用户在开启服务过程中 没有正常退出app 而是直接把app进程划掉了  发现下载的service没有关闭 ，请问一下 这个问题怎么解决啊

**Comment by Jacksgong** [comment]
如果是非前台服务，直接将app进程划掉，相关的当前app的其余进程也会被kill掉的（如下载进程）。

**Comment by Jacksgong** [comment]
杀不死应该是系统层级的配置之类的，FileDownload Service 没有在这块做特殊处理。
