### ISSUE TITLE
关于FileDownloader多进程框架

### ISSUE THREAD

**Issue by hewking** [lingochamp/FileDownloader#196]
看到流利说Android架构的文章，里面谈到了 FileDownloader 多进程，想问下具体在那部分？

**Comment by Jacksgong** [comment]
恩。赞~。

你可以看下 `BaseFileServiceUIGuard` 与 `BaseFileService`(最新版本中这个类已经被删除了) 的演变。

**Comment by hewking** [comment]
好的 谢啦 我看下提交的记录学习下
