### ISSUE TITLE
gradle 导包失败

### ISSUE THREAD

**Issue by Joyce1991** [lingochamp/FileDownloader#20]
通过gradle 导包失败，看看是不是传到maven的过程中出了什么问题，编译时下载了okhttp和okio，但是就是没有下载得到你的library包

**Comment by Jacksgong** [comment]
我们自己也是从jcenter上面下载使用的。我刚刚检查了下，无论是`jcenter`还是`mavenCentral`都是没有问题的。可能你需要再检查下看看具体的错误日志是什么与你的网络情况:

---

## Jcenter中资源地址(gradle默认的maven资源地址如果有配置仓库地址`jcenter()`默认是从这里下载的):

http://jcenter.bintray.com/com/liulishuo/filedownloader/library/

## MavenCentral中的资源地址(gralde默认的maven资源地址如果配置仓库地址`mavenCentral()`默认是从这里下载的):

https://oss.sonatype.org/content/repositories/releases/com/liulishuo/filedownloader/library/

**Comment by Joyce1991** [comment]
谢谢，已经ok了

**Comment by Jacksgong** [comment]
恩。好的。:)
