### ISSUE TITLE
支持直接取出Response Header中的filename作为文件名吗？

### ISSUE THREAD

**Issue by helloyxc** [lingochamp/FileDownloader#200]
比如下载百度图片中的一张图片时的返回头里：`Content-Disposition: attachment; filename="fecef2f7658033d66a26e504fd0b2dcd.jpg"`
，使用这个库，怎么样可以直接将这个filename里的内容当做文件名？
这样创建task时，传入一个directory就行了。

**Comment by Jacksgong** [comment]
多谢你的建议，下个版本会进行支持。

**Comment by Jacksgong** [comment]
Enhanced since [v0.3.3](https://github.com/lingochamp/FileDownloader/releases/tag/v0.3.3).

**Comment by Angdo** [comment]
下载七牛CDN文件时，它的Header文件信息是这样的`Content-Disposition → inline; filename="Unity.in.Action.2015.6.pdf"`。它无法识别使用了随机数作为文件名。
