### ISSUE TITLE
已经下载过的文件, 还要重复下载

### ISSUE THREAD

**Issue by linger1216** [lingochamp/FileDownloader#203]
1. 在sdcard的某一目录中...下载一个文件 如1.zip
2. 执行 "adb shell pm clear your_packagename"
3. 重新下载1.zip这个文件, 会发现下载进度从0开始.

期望: 第3步骤, 直接进入 download 100%的回调.

**Comment by Jacksgong** [comment]
是的，在现有release最新版本中，数据是根据数据库的存储进行判断的，因此如果数据库的数据丢失了就会出现你说的情况，如果希望直接进入 download 100% 回调，就线上release版本 可以通过 调用 `FileDownloader#setTaskCompleted` 进行设置。

---

在下个版本中（代码已经在远端，近段时间会发布），已完成的任务已经不再需要依赖数据库判断，由于#172， 因此，你如果不着急，在下个版本中就不需要通过 `FileDownloader#setTaskCompleted` 也可以match你的想法了。

**Comment by linger1216** [comment]
谢谢您的回答, 那我就不着急手动改了...期待你的update
