### ISSUE TITLE
Google play service update

### ISSUE THREAD

**Issue by theAliAkhgar** [lingochamp/FileDownloader#205]
I have tested on many devices and some devices app prompt me to update google play service but i ignored them, and on those device the download wont start! 
Im using it in my app and its making a bad situation for me!

if It might be wrong and its coming from something else please let me know!

**Comment by Jacksgong** [comment]
Sorry to hear that. But FileDownloader doesn't bind google play service, and I can't understand why you can meet such problem.

---

I test FileDownloader in China, and  I have many devices without installing google play service, but FileDownloader works well on those devices.

**Comment by theAliAkhgar** [comment]
so there isnt any special code, permission or something that i should? i got that , you R right it isnt related to google play service

**Comment by Jacksgong** [comment]
Yes, For FileDownloader internal, it doesn't need any special permission. For code, just need Ref [here](https://github.com/lingochamp/FileDownloader/wiki/Initialization).

---

Normally, 
if you need access INTERNET, so you should declare `android.permission.INTERNET`,
if you need store files in directories which need to declare permission manually,  so you should declare `android.permission.WRITE_EXTERNAL_STORAGE`.

---

Simply, you can test the demo project in the devices you got the problem.

**Comment by Jacksgong** [comment]
I saw your e-mail, any questions, please keep in touch.

**Comment by theAliAkhgar** [comment]
hi, my problem was solved! it was because of bad coding! thanks for your
fast response.

**Comment by Jacksgong** [comment]
OK.
