### ISSUE TITLE
SQLiteFullException

### ISSUE THREAD

**Issue by lct8712** [lingochamp/FileDownloader#206]
你好

我们的 app 在使用 FileDownloader 时遇到了 SQLiteFullException 的崩溃，根据统计数据，用户的存储空间并没有满。请问有什么解决的思路吗，谢谢。

![2016-07-11 10 35 14](https://cloud.githubusercontent.com/assets/2209588/16718514/52175b2c-4753-11e6-880c-5b50282b9bcf.png)
![2016-07-11 10 34 52](https://cloud.githubusercontent.com/assets/2209588/16718515/53f58626-4753-11e6-8573-cca57af86109.png)

**Comment by Jacksgong** [comment]
FileDownloader 在旧的版本，数据库会存储所有的已完成的任务，用于验证是否是下载完成，导致数据库可能比较大。是有可能出现这个问题的。

> 由于旧版本在下载的整个流程中文件名相同，并且下载之初就预申请了整个文件的大小，因此只能依赖数据库来判断是否已经下载完成

---

在新的版本([v0.3.3](https://github.com/lingochamp/FileDownloader/blob/master/CHANGELOG-ZH.md#version-033))中，不再依赖数据库中的数据判定是否已经下载完成。只存储未下载完成并且可以用于断点续传的数据，因此会大大缓解该问题。

> 在新版本中，未完成下载的文件，采用了临时文件名，因此判定是否下载完成不再需要依赖数据库。
> 在升级过程以后，会移除在数据库中已经下载完成的任务的数据。

**Comment by Jacksgong** [comment]
关于这个错误，你可以看看这个stackoverflow: http://stackoverflow.com/questions/3656417/how-to-determine-android-database-max-size-and-prevent-sqlitefullexception

**Comment by lct8712** [comment]
非常感谢！
