### ISSUE TITLE
请问FileDownloadDbHelper存储的下载数据能否被删除

### ISSUE THREAD

**Issue by Arthas8** [lingochamp/FileDownloader#208]
你好：请问下FileDownloadDbHelper存储的下载任务能否被删除，如果要做一个下载管理器，能否直接使用这个数据库？

**Comment by Jacksgong** [comment]
这块数据是为了断点续传时使用，如果只是删除了某个数据，只会影响该数据相关任务断点续传（如无法进行断点续传）。

---

但是 FileDownloadDbHelper 这个数据库是 FileDownloader 长期维护与迭代，为了基本的下载功能而存在的数据库，目前**不建议上层逻辑使用这个数据库**:

1. 有可能在接下来的迭代过程中，为了优化以及其他原因因会不断调整以及修改该数据库。考虑到兼容性以及稳定性的问题。
2. 这个数据库目前是用于存储可以用于断点续传的数据，如果数据被调整，可能会影响正常断点续传功能。
3. 在下载等过程中这个数据库处于活跃状态，里面有一个Cache队列，如果由于上层逻辑调整，导致数据不一致性，可能会带来其他风险问题。

**Comment by Arthas8** [comment]
非常感谢你及时的回复！我明白你考虑到的问题
我有几点想法：
1、我看已经有了start、pause函数，能否开放一个delete任务函数，可以彻底删除某一条任务(包括数据库记录和已下载文件）
2、能否提供一份SparseArray<FileDownloadModel> downloaderModelMap 这个数据的拷贝呢？这样用户只使用的是FileDownloadModel列表，并不会影响内部数据库修改调整
您看下如果有这两样，外部UI做下载管理时就简单多了，也不需要去再维护一个数据库，我刚看到您写的这份代码，还不是太清楚内部实现，不知道我说的对不对哈

**Comment by Jacksgong** [comment]
FileDownloadDB，从设计之初就定义为内部数据，主要考虑到以下因素不会对外开放:

1. 在每次FileDownloadDB数据库启动的时候，FileDownloader内部会对数据进行维护，剔除所有的内部判定无用的数据，保持数据尽量轻量干净。在每次下载完成或者其他一些情况也会维护数据库。因此一旦外界依赖/耦合这个FileDownloader内部数据库，会有很大的风险数据被清除，或者会出现很多不达预期的事情。
2. 在默认配置情况下，这块数据库数据是在另外一个进程(:filedownloader)，包括其cache数据。
3. FileDownloader不希望对外灌输过多的复杂的逻辑知识，希望上层使用起来将FileDownloader当做一个轻量的、灵活的下载引擎来使用，包括demo、以及我们自己的项目中引用FileDownloader，有需要cache和需求有关的数据都是封装在自己的数据库中。
4. 考虑到数据库的性能瓶颈，应用在数据库这块的性能瓶颈，往往并不是在少启动一个数据库库，或者少几张表，而是表中索引的策略、搜索的策略、以及表的尽量轻量精准。

**Comment by OrangeHao** [comment]
问一下，那个数据库大概的维护策略是怎样的，数据存在有时间限制吗？如果一直增长，会很大吗

**Comment by Jacksgong** [comment]
数据没有时间限制，但是只会存储可用于 断点续传的数据（也就是说，下载没有完成 并且 中间临时文件有效存在 = 可以继续下载）。

数据维护时机是在: 下载完成的时候、某个任务启动的时候会对对应任务数据维护、下载服务启动的时候。

---

这边我们自己的项目中有测试过，如果真的有几千个文件下载暂停，并且全部没有下载完成，并且本地临时文件全部有效存在，对性能的影响依然非常小，数据量也非常的小。

**Comment by Jacksgong** [comment]
https://github.com/lingochamp/FileDownloader/commit/eb8af2897cf23c3ab7e0c6b4ef4e5d24d392e11c
