### ISSUE TITLE
Question: How can i remove downloaded files?

### ISSUE THREAD

**Issue by farbod-s** [lingochamp/FileDownloader#209]
how can i remove downloaded files and change their status?

**Comment by Jacksgong** [comment]
In the latest version(0.3.3), FileDownload doesn't store downloaded tasks anymore. So, If the task has completed downloading, You invoke `FileDownloader#getStatusIgnoreCompleted`, you will receive the `INVALID` status.

**Comment by farbod-s** [comment]
@Jacksgong Thanks for your quick response.

i have another question: how can i get the `FileDownloadQueueSet` size? cause i want to start each task separately and they must locate in a queue and downloads one after another, and maybe other tasks added to queue in the middle of the download process, and i can't start queue set multiple times. so only need start queue set for the first time.
i would appreciate if you give me an idea about that.

**Comment by Jacksgong** [comment]
OK. You can't  modify the queen in the middle of the download process. BUT you can use `FileDownloader#setMaxNetworkThreadCount(1)` to ensure all tasks running in FileDownloader one after another.

REF [FileDownloader#setMaxNetworkThreadCount](https://github.com/lingochamp/FileDownloader/blob/d1baf672f7d9e20dd7ea0f06803fdc8b829c2e43/library/src/main/java/com/liulishuo/filedownloader/FileDownloader.java#L609).
