### ISSUE TITLE
紧急，请删除此下载地址好吗，跪谢

### ISSUE THREAD

**Issue by wangyuetingtao** [lingochamp/FileDownloader#21]
您好，请帮忙删除/filedownloader/demo/Constant.java中，第40行下载地址代码好吗，这是内部链接，麻烦您了,cx开头的。

**Comment by Jacksgong** [comment]
抱歉给你带来不便了。我这就删除。

**Comment by wangyuetingtao** [comment]
非常感谢

**Comment by benzheren** [comment]
但是理论上 commit 历史里面还是能看到的啊 @wangyuetingtao
