### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by my519820363** [lingochamp/FileDownloader#210]
java.lang.NullPointerException
Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
java.lang.RuntimeException:Unable to create application fanying.client.android.petstar.PetstarApplication: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
android.app.ActivityThread.handleBindApplication(ActivityThread.java:4990)
......
Caused by:
java.lang.NullPointerException:Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
com.liulishuo.filedownloader.util.FileDownloadUtils.isDownloaderProcess(FileDownloadUtils.java:226)
com.liulishuo.filedownloader.FileDownloader.init(FileDownloader.java:100)
com.liulishuo.filedownloader.FileDownloader.init(FileDownloader.java:68)
com.liulishuo.filedownloader.FileDownloader.init(FileDownloader.java:59)
com.liulishuo.filedownloader.FileDownloader.init(FileDownloader.java:118)
fanying.client.android.library.BaseApplication.initDownloadManager(BaseApplication.java:582)
fanying.client.android.library.BaseApplication.onCreate(BaseApplication.java:308)

**Comment by Jacksgong** [comment]
可以告知下是在什么情况下遇到的吗，这边看到日志是系统方法: `ActivityManager#getRunningAppProcesses()` 返回了空。

**Comment by my519820363** [comment]
是崩溃系统搜集到的，魅族MX4和HUAWEI P7各一次，共同特点是5.1系统。

我这边已经把自己APP的代码中的ActivityManager#getRunningAppProcesses()都做了判空处理，建议你这边也这样做用以兼容

**Comment by my519820363** [comment]
看系统源码，应该是AIDL时出了问题，返回了null。

**Comment by Jacksgong** [comment]
好的。谢谢。

**Comment by Jacksgong** [comment]
Fixed since [0.3.4](https://github.com/lingochamp/FileDownloader/releases/tag/v0.3.4).
