### ISSUE TITLE
获取或者增加下载任务数量的API

### ISSUE THREAD

**Issue by 10045125** [lingochamp/FileDownloader#211]
很多情况下，下载完成后，如果任务数量为0的话需要杀死下载所在进程，而这个结束下载进程的操作可以有外部方选择是否在没有任务的时候杀死下载进程，同时，在通知栏显示进度的时候，有可能存在不能清除掉通知栏的情况，这样会造成通知栏的进度条变成了常驻通知栏，框架内部应该设立一个机制，在通知栏下载任务数量为0的情况下强制清除通知栏。

**Comment by Jacksgong** [comment]
`FileDownloader#unBindServiceIfIdle():boolean`，是如果任务数量为0，服务处于空闲状态就解除与FileDownloader服务的绑定。

其返回值，如果是`true`代表任务数量为0，下载服务处于空闲状态，并且解绑成功；如果是`false`表示服务中还有任务正在运行，并为解绑失败。

**Comment by 10045125** [comment]
使用者更倾向于，每一个下载任务完成时，我需要知道是不是还有任务，如果没有任务我就需要结束下载进程。对于存在通知栏情况，同样下载完成后需要做出清除处理。

**Comment by Jacksgong** [comment]
由于目前FileDownload的服务采用的是`Service#START_STICKY`，因此如果仅仅是结束下载进程，一般情况下下载进程会立马重启的。需要先主动先解绑，然后在结束进程才能正确的结束了下载进程。因此提供现有的方法是也更有易于避免BUG的出现。

**Comment by 10045125** [comment]
目前的现状是，退出主进程后下载进程还是存在（此时没有下载任务），用户一般的需求是：如果我当前已经没有下载任务了，我需要结束掉下载进程。在上层Api中并没有提供可用的获取目前未完成的任务数量，也就是上层逻辑没有办法对下载进程进行合理的控制。

**Comment by Jacksgong** [comment]
我明白你的做法，但是我依然推荐，直接调用`FileDownloader#unBindServiceIfIdle()`进行解绑以及结束服务。我来解释下我的初衷吧，也是系统的初衷。

Android官方是**不希望上层应用去管理进程**的，这也是 组件与进程 分离的初衷。目前现状:

调用 `FileDownloader#unBindServiceIfIdle()` 如果解绑了服务并且停止了服务，此时 下载进程会处于空闲进程，一旦是空闲进程，对于系统与用户是没有任何的多余开销的，而是处于以下状态:

1. 对于用户，通过设置->应用->运行中，在这里是不记录空闲进程的。而是在 设置->应用->已缓存中记录。
2. 对于系统，当内存一旦不够驱动其他三类进程（前台进程、可见进程、服务进程），空闲进程立马会被回收。而当用户再次启动绑定对应进程中的服务时，如果空闲进程还没有被回收，那么就省去了重新启动进程的开销，这也是 组件与进程分离的原因。

**Comment by Jacksgong** [comment]
P.S: 如果没有特殊必要，其实并不是十分推荐将下载服务放到独立的进程，可以通过: [process.non-separate](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties) 进行配置可以有效减少下载过程的由于IPC带来的 I/O以及CPU消耗。

**Comment by 10045125** [comment]
嗯，明白你所说的。我所提到的是我想要在没有任务的时候手动的去`FileDownloader#unBindServiceIfIdle()`，这样的话就需要有Api告知当前的任务数量，如果数量为0的话，那么我就可以调用`FileDownloader#unBindServiceIfIdle()`

**Comment by Jacksgong** [comment]
在调用`FileDownloader#unBindServiceIfIdle()` 时，内部就已经判断任务数量了，如果任务数量不为0，是不会执行解绑以及结束下载服务的。

**Comment by Jacksgong** [comment]
也可以参考这个方法获取: https://github.com/lingochamp/FileDownloader/issues/214#issuecomment-233104197
