### ISSUE TITLE
请问这个支持eclipse吗

### ISSUE THREAD

**Issue by liangnansheng** [lingochamp/FileDownloader#212]
？？

**Comment by Jacksgong** [comment]
我画了个图，你先看着有问题及时评论。

## FileDownloader提取jar包到绑定源码:

> 图片2M，网速慢的稍等等。

![filedownloader-eclipse](https://cloud.githubusercontent.com/assets/6176417/16790357/cea835e0-48e7-11e6-91a8-590d6eefb1bd.jpg)

**Comment by DesignQu** [comment]
你好，我按照图片导入eclipse里，多任务，开启下载后，图片没有保存是怎么回事呢？

**Comment by DesignQu** [comment]
权限写了，服务也声明了，包导了0.35版本，和OKhttp-3.4.1,代码是复制MultitaskTestActivity里的，没什么改动，图片没有保存到把定的目录，我设置了FileDownloadUtils.setDefaultSaveRootPath(ProjectUtils.IMG_THUMB);

**Comment by Jacksgong** [comment]
你看看输出的日志。

**Comment by DesignQu** [comment]
08-19 17:07:07.393: D/Posix(28444): [Posix_connect Debug]Process com.ld.smb:filedownloader :80 
08-19 17:07:07.403: I/System.out(28444): [socket][/192.168.1.218:46958] connected
08-19 17:07:07.414: D/libc-netbsd(28444): [getaddrinfo]: hostname=cdn.llsapp.com; servname=(null); cache_mode=(null), netid=0; mark=0
08-19 17:07:07.414: D/libc-netbsd(28444): [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
08-19 17:07:07.415: I/System.out(28444): [socket][70] connection cdn.llsapp.com/58.218.206.22:80;LocalPort=37235(15000)
08-19 17:07:07.415: I/System.out(28444): [CDS]connect[cdn.llsapp.com/58.218.206.22:80] tm:15
08-19 17:07:07.424: I/System.out(28444): [CDS]rx timeout:10000
08-19 17:07:07.495: I/System.out(28444): [CDS]close[43987]

**Comment by DesignQu** [comment]
日志只显了这些东西

**Comment by DesignQu** [comment]
08-19 17:18:10.173: D/FileDownloader.FileDownloadRunnable(29600): start download 45694730 http://cdn.llsapp.com/yy/image/dd72c879-b1c4-4fb9-b871-d57dfa3aa709.jpg
			08-19 17:18:10.174: D/FileDownloader.FileDownloadMgr(29600): can't continue 45694730 file not suit, exists[FALSE], directory[FALSE]
			08-19 17:18:10.175: D/FileDownloader.FileDownloadRunnable(29600): 45694730 request header Cache-Control: no-cache
			08-19 17:18:10.175: I/System.out(29600): [CDS][DNS] getAllByNameImpl netId = 0
					08-19 17:18:10.176: I/System.out(29600): [CDS]rx timeout:10000

**Comment by DesignQu** [comment]
还需要导什么其他包吗？

**Comment by DesignQu** [comment]
08-19 17:19:38.369: D/FileDownloader.FileDownloadRunnable(29600): On retry -1759819910 java.lang.NoClassDefFoundError: Failed resolution of: Lokio/Okio; 1 1

**Comment by DesignQu** [comment]
有一句这是个

**Comment by DesignQu** [comment]
Okio

**Comment by DesignQu** [comment]
可以使用了，是因为没有引入Okio

**Comment by Jacksgong** [comment]
恩。好的。
