### ISSUE TITLE
下载速度显示异常

### ISSUE THREAD

**Issue by helloyxc** [lingochamp/FileDownloader#216]
我们这边环境下载限速400Kb/s，客户端平均下载速度是300多Kb/s。
但是通过task.getSpeed有时候会出现速度显示为3000多KB/s的：（左边为进度，右边为速度）
07-15 18:58:26.814 19373-19373 D/DownloadItemViewHolder: 15.885447, 359
07-15 18:58:28.064 19373-19373 D/DownloadItemViewHolder: 16.876251, 238
07-15 18:58:30.184 19373-19373 D/DownloadItemViewHolder: 17.872879, 142
07-15 18:58:30.274 19373-19373t D/DownloadItemViewHolder: 18.866535, 3040
07-15 18:58:31.074 19373-19373 D/DownloadItemViewHolder: 19.860985, 379

即当接口回调间隔很短时，就会显示成一个很大的速度，能帮忙分析下吗？

**Comment by Jacksgong** [comment]
可以稍微留意下我写的注解: [BaseDownoadTask#getSpeed](https://github.com/lingochamp/FileDownloader/blob/d1baf672f7d9e20dd7ea0f06803fdc8b829c2e43/library/src/main/java/com/liulishuo/filedownloader/BaseDownloadTask.java#L675):

```

    /**
     * If in downloading process(status equal {@link FileDownloadStatus#progress}) : Calculating
     * when the interval from the last calculation more than {@link #minIntervalUpdateSpeed} before
     * each {@link FileDownloadListener#progress(BaseDownloadTask, int, int)} call-back method.
     * <p/>
     * If finished({@link FileDownloadStatus#isOver(int)}): Would be average speed. The scope is
     * (connected, over).
     *
     * @return KB/s
     * @see #setMinIntervalUpdateSpeed(int)
     */
    public int getSpeed() {
        return this.speed;
    }
```



如果是在下载过程中，这里返回的速度计算是在每个`FileDownloadListener#progress`回调之前，判断如果间隔大于外界设定的最小间隔，那么与最后一次计算与该次之间求一个速度；如果已经是下载结束了，那么返回的是全程的平均值。

---

这块的代码逻辑比较简单，还有不明白希望能够自己翻看下源码更快。
