### ISSUE TITLE
断网下载失败后，重新start不能继续下载

### ISSUE THREAD

**Issue by yuchangfu** [lingochamp/FileDownloader#217]
断网下载失败后，重新用之前的task.start不能继续下载

**Comment by Jacksgong** [comment]
重新用之前要reuse。你留意下报的是什么错误。

**Comment by yuchangfu** [comment]
没报什么错，直接完成了，然后task.getTargetFilePath();拿不到下载完的文件路径

**Comment by Jacksgong** [comment]
拿到的是什么？

**Comment by yuchangfu** [comment]
拿到的是null；
这样写是否ok
if(force == false && downloadTask!=null){
            downloadTask.reuse();
            downloadTask.start();
            return;
        }

**Comment by yuchangfu** [comment]
这样写，可以继续下载，但还是拿不到下载完的文件路径，下面是去文件路径的代码
`@Override
                    protected void completed(BaseDownloadTask task) {
                        if (downloadUrls.size() > 0)
                            downloadUrls.remove(downloadUrls.size() - 1);
                        handler.sendEmptyMessage(OK);
                        saveFilePath = task.getTargetFilePath();
                    }`

**Comment by Jacksgong** [comment]
我刚刚在[demo project](https://github.com/lingochamp/FileDownloader/tree/master/demo) 中的单任务测试下载Normal Task，然后下载中断开网络，然后再开始，是没有问题的。

你参考下。demo project中的单任务测试，看看是哪里出了问题。

如果始终找不到问题。你建一个简单的项目，让项目运行起来可以复现你的问题。然后发我邮件(igzhenjie@gmail.com)，我给你看下问题出在哪里。

**Comment by Jacksgong** [comment]
已经找到原因了吗？如果是在 `error`回调中直接调用`BaseDownloadTask#reuse`然后报异常是已经在https://github.com/lingochamp/FileDownloader/commit/9c537c28e14379b738b735200d87529f641d2ece 这里修复了，下个版本会带上，你是这个问题吗？
