### ISSUE TITLE
Provide an function to clear the task ( remove its data in the internal database which used to resuming from the breakpoint, and remove the Intermediate/downloaded file)

### ISSUE THREAD

**Issue by xanaduo** [lingochamp/FileDownloader#218]
不管是从你的Demo上看还是从方法上都没发现有取消任务的操作，能不能提供一个取消的方法？或者下载的进度数据保存在什么地方，怎么去除掉？

**Comment by Jacksgong** [comment]
`FileDownloader#pause()` 暂停任务是相对与下次启动会自动断点续传来说的，实质上在缓存层面已经释放了所有的Task的数据。

若是任务的下载过程中间文件被删除了(`FileDownloadUtils#getTempPath`)，在下载服务启动的时候会清除数据库中的该条记录。

若是请求发现服务端文件已经修改，无法进行断点续传，也会弃用数据库中的数据。

若是某个任务已经下载完成，数据库中的数据也会被删除掉。

---

如果真的有需求需要清除掉整个任务，不管断点续传等，只需要在暂停以后，删除掉其中间文件即可(`FileDownloadUtils#getTempPath)，

**Comment by xanaduo** [comment]
我把缓存文件删除了，再次点击下载确实是重新开始下载，但我发FileDownloadListener的FileDownloadMessage监听还存留着之前的进度，然后就会出现先会显示之前的进度。不知道是不是我控制的问题。

**Comment by Jacksgong** [comment]
在`pending`的时候，是会带回旧的进度的(如果数据库中的数据还存在)，这个是设计如此。如果这个不达你的预期可以不使用这个参数。

**Comment by Jacksgong** [comment]
不过综合考虑。在接下来的版本我会增加一个接口，直接清除某个任务的接口。

**Comment by Jacksgong** [comment]
Enhanced since [0.3.4](https://github.com/lingochamp/FileDownloader/releases/tag/v0.3.4).
