### ISSUE TITLE
觉得是不是跟界面耦合性太高了。

### ISSUE THREAD

**Issue by xanaduo** [lingochamp/FileDownloader#219]
从你的Demo来看，只要退出界面就暂停了所有正在下载的任务，当然我知道这是因为调用了Destroy方法。我想这样，在后台下载，进来直接刷新界面就可以。但我发现跟界面绑定的太紧了，我想在其它界面也能看到下载进度，没找到方法——因为FileDownloadListener是跟Holder一起的。

**Comment by Jacksgong** [comment]
FileDownloader本身没有与Activity有任何的耦合关系，具体你参照这里: https://github.com/lingochamp/FileDownloader/issues/174#issuecomment-225772950

**Comment by xanaduo** [comment]
谢谢！
