### ISSUE TITLE
how do set FileDownloader use myself okhttp instance

### ISSUE THREAD

**Issue by fanOfDemo** [lingochamp/FileDownloader#22]
how do set FileDownloader use myself okhttp instance

**Comment by Jacksgong** [comment]
soooo.. Sorry, This is unable to support, from the current situation. Since the `OkHttpClient` instance is in a separate process `:filedownloader`.

**Comment by Jacksgong** [comment]
But we will provide some common OkHttpClient interfaces in the next version, such as: `readTimeout`、`connectTimeout`...

if you want to share the connection pool, it is very tough for the current situation.

**Comment by fanOfDemo** [comment]
got it!

**Comment by DevilGeek** [comment]
Can you also expose
okHttpClient.setSslSocketFactory
and
okHttpClient.setHostnameVerifier

**Comment by Jacksgong** [comment]
@DevilGeek I got an idea what all you need, and I will do it.

You can set your custom okHttpClient what you are like on the `Application#onCreate`, when `:filedownloader` process is launching.
