### ISSUE TITLE
相同url和path的任务重复启动,totalBytes为0

### ISSUE THREAD

**Issue by Ernest-su** [lingochamp/FileDownloader#220]
遇到一个奇怪的问题,在0.3.2中没有问题,在0.3.3中就出现.大概流程是:TASK A,TASK B是独立的,但是他们用相同的URL,PATH来启动一个任务,使用`forceReDownload`,首先启动TASK A,下载完成,再启动一次TASK A,在下载过程中启动TASK B, 然后TASK B的totalBytes就变成 0 了.  想写个demo复现的,结果又一直复现不了.特意打印了关键的log,能帮忙分析一下是什么原因吗?如下图,`taskId`,`modelId`是一直不变的.

根据commit的记录,我怀疑是跟几个地方可能有关:`ForceReDownload`,`getStatusIgnoreCompute(id)`
![1](https://cloud.githubusercontent.com/assets/5917446/16983123/f1eba410-4ea5-11e6-811c-d9813936092e.png)

其中`sofarBytes` 在下载完成前一直增长,没有因为TASK B 的启动而变化

整理了一份更多信息的log.希望能提供一些帮助.

![2](https://cloud.githubusercontent.com/assets/5917446/16983210/52943462-4ea6-11e6-8f3d-6f505600c090.png)

**Comment by Jacksgong** [comment]
我整理下:

> Task A、Task B，使用的是相同的URL、PATH，因此相同的任务。
> Task A与Task B在启动时，都定义了`forceReDownload=true`。

---

#### I. 在这种情况下，Task A还在运行过程中，Task B启动，应该Task B会收到 `warn`，但是没有收到，而是Task B继续还被启动下载，并且 totalBytes 变成了0。

如果是这种情况，确实很奇怪，不符合预期与业务逻辑。

---



#### II. 如果是 Task A下载完成，此时再启动Task A，Task A 又下载完成了。此时再启动 Task B，然后 Task B重头开始下载，但是刚开始回来的 `totalBytes`是0。

如果是这个情况，那么在`0.3.3`中确实是这样的，设计如此。

- 在`0.3.2`中，虽然任务已经下载完成，FileDownloader还是会存着该任务的信息在数据库中，因此如果启动相同任务，FileDownloader在`pending`时会返回之前数据的`totalBytes`。
- 在`0.3.3`中，一旦任务下载完成，FileDownloader就会删除该任务在数据库中的数据，此时再启动相同的任务，Filedownloader在`pending`时会返回0。

**Comment by Ernest-su** [comment]
上传了一个复现的demo,之前的说明有误,TASK A是强制重新下载,TASK B没有强制重新下载.
[downloadtest.zip](https://github.com/lingochamp/FileDownloader/files/375164/downloadtest.zip)

**Comment by Jacksgong** [comment]
@Ernest-su 👍 好的，我认真看下。如果今天白天上班没有时间，就今天晚上看下什么问题。

**Comment by Jacksgong** [comment]
感谢你的反馈，这里确实是有问题，我会尽快修复了，在下个版本带上。

**Comment by Jacksgong** [comment]
Fixed since [0.3.4](https://github.com/lingochamp/FileDownloader/releases/tag/v0.3.4).
