### ISSUE TITLE
getStatus获取不到完成状态

### ISSUE THREAD

**Issue by AndyGu** [lingochamp/FileDownloader#221]
从0.3.0升级的到0.3.3，下载完成后getStatus还是返回0

**Comment by Jacksgong** [comment]
`0.3.3` 中，数据库中不再存储已经下载完成任务的数据。

你认真看下源代码，几个`getStatus`方法，如果你调用的是`getStatusIgnoreCompleted`，已经下载完成，返回就是0。而是否下载完成，FileDownloader就是通过判断对应路径的文件是否存在，如果存在就表示已经下载完成。


---

参见注解: https://github.com/lingochamp/FileDownloader/blob/bcdaf47c7fe9ebc67aff967b86eae38ea859e2e7/library/src/main/java/com/liulishuo/filedownloader/FileDownloader.java#L356

**Comment by AndyGu** [comment]
我调用的是getStatus(final int downloadId, final String path)这个方法，应该是FileDownloadUtils.isFilenameConverted(FileDownloadHelper.getAppContext())这个方法返回了false 导致status没有返回completed，但是本地文件是已经下载好了的

**Comment by Jacksgong** [comment]
你再确认下是否是 `FileDownloadUtils.isFilenameConverted(FileDownloadHelper.getAppContext())` 这个方法返回 `false`，因为这个方法**只有在一种情况下**返回 `false`: 

升级为`0.3.3`以后，还没有启动过FileDownloadService，一旦有启动过，这个方法就会被置为 `true`，并且没有地方会主动将其设为 `false`。

**Comment by Jacksgong** [comment]
整个FileDownloader 只有这里对这个参数赋值，并且是置为 `true`，写入文件: https://github.com/lingochamp/FileDownloader/blob/d1baf672f7d9e20dd7ea0f06803fdc8b829c2e43/library/src/main/java/com/liulishuo/filedownloader/services/FileDownloadDBHelper.java#L134

**Comment by Jacksgong** [comment]
这么做的原因是:

在 `0.3.3` 之前，所有文件即便没有下载完成，也是存储在目标路径，因此我们**无法通过**判断目标路径文件是否存在来决定是否已经下载完成。

因此在 升级为 `0.3.3` 之后，启动下载服务，我们会扫描所有数据进行一次迁移，将所有未完成的任务 由目标路径文件 **迁移为** 中间路径文件，此时这个值就会被置为 `true`，此时通过判断目标路径文件是否存在来决定是否已经下载完成才**有效**。

**Comment by AndyGu** [comment]
恩，我确认是 FileDownloadUtils.isFilenameConverted(FileDownloadHelper.getAppContext()) 这个方法返回 false，我也确实没有启动过FileDownloadService，我是通过自己构建BaseDownloadTask的方法，将BaseTaskViewHolder以setTag的形式赋给task，这样也将task和view绑定，以便在跳转到其他页面再回到此一面的时候，可以通过task取tag的形式继续更新页面，这个过程中并没有显式的调用service，是我使用方式不对么？

**Comment by Jacksgong** [comment]
从 `0.3.3`之前的版本迁移到 `0.3.3`，需要在迁移以后首次打开软件，调用获取状态方法之前 启动FileDownloadService。

其实如果需要获取状态，其实也必须要启动 FileDownloadService 之后，否则启动不到状态的。这块启动 FileDownloadService 以及监听是否绑定完成可以获取 状态，这块建议你参考这里: 

https://github.com/lingochamp/FileDownloader/blob/8e9838e998c21d012b66af6dd9f216a7d530001c/demo/src/main/java/com/liulishuo/filedownloader/demo/TasksManagerDemoActivity.java#L452

452行到481行。

不要忘了需要反注册: https://github.com/lingochamp/FileDownloader/blob/8e9838e998c21d012b66af6dd9f216a7d530001c/demo/src/main/java/com/liulishuo/filedownloader/demo/TasksManagerDemoActivity.java#L485

**Comment by Jacksgong** [comment]
原因是，这块数据是存储在下载服务中的。

需要注意的是: 对于UI进程来说，下载服务只需要启动一次，之后就不再需要绑定或监听，可以直接调用获取状态的方法。

因此，在获取状态之前，是否需要做绑定与监听可以通过这个方法:  `FileDownloader#isServiceConnected`，如果服务已经连接，就不再需要去绑定与监听。可以直接调用获取状态。
