### ISSUE TITLE
Is it possible to group downloads?

### ISSUE THREAD

**Issue by SalmanTKhan** [lingochamp/FileDownloader#222]
For example I have a set of images that I want to be treated as one download, as in if paused or stopped, the group of downloads would be paused or stopped.

**Comment by Jacksgong** [comment]
Yes, you can download images as a queue ( use the same FileDownloadListener object).

- configure tasks and start the queue by [FileDownloadQueueSet](https://github.com/lingochamp/FileDownloader/blob/d1baf672f7d9e20dd7ea0f06803fdc8b829c2e43/library/src/main/java/com/liulishuo/filedownloader/FileDownloadQueueSet.java) or Use `FileDownloader#start(FileDownloadListener, boolean)`.
- paused or stopped the queue by `FileDownloader#pause(FileDownloadListener)`

---

More detail Ref [MultitaskTestActivity](https://github.com/lingochamp/FileDownloader/blob/8e9838e998c21d012b66af6dd9f216a7d530001c/demo/src/main/java/com/liulishuo/filedownloader/demo/MultitaskTestActivity.java).

**Comment by SalmanTKhan** [comment]
Thanks Jacksgong for the insight, regarding that, i'm looking to have a combination of FileDownloadQueueSet with a TaskManager and FileDownloadNotificationListener, the task manager would be an independent activity that the user can access at any point while using the application, I see that the FileDownloadQueueSet requires a target which I presume would be the notificationlistener due to the fact I want a notification while downloading, but I need to keep track for each download because at any point there could be multiple FileDownloadQueueSets, any suggestion on what I should do, I see the sample application shows different aspects of the FileDownloader, but doesn't seem to show how they would work in conjunction with another.

**Comment by Jacksgong** [comment]
Ref here please: https://github.com/lingochamp/FileDownloader/issues/103#issuecomment-209173124
