### ISSUE TITLE
No possibility to start two FileDownloadQueueSets in a row

### ISSUE THREAD

**Issue by chriswiesner** [lingochamp/FileDownloader#223]
starting two different FileDownloadQueueSets (with different tasks) at once results in
`java.lang.IllegalStateException: This task is running -781468002, if you want to start the same task, please create a new one by FileDownloader.create`

**Comment by chriswiesner** [comment]
actually it seems that this is not causing a duplicate single task, it's more due to starting two `FileDownloadQueueSet` in a row. could this be the issue?

**Comment by Jacksgong** [comment]
Is it two different FileDownloadQueueSets use the same FileDownloadListener object?

**Comment by chriswiesner** [comment]
yes

**Comment by Jacksgong** [comment]
OK, I know how it's going on, I will fix this bug, and it would be fixed in next version.

**Comment by Jacksgong** [comment]
Fixed since [0.3.4](https://github.com/lingochamp/FileDownloader/releases/tag/v0.3.4).
