### ISSUE TITLE
expose generating id of BaseDownloadTask

### ISSUE THREAD

**Issue by chriswiesner** [lingochamp/FileDownloader#224]
i request my download Urls from a Webservice which adds hashcodes as parameters (url availability is timeboxed from server) and additional information to the Url.

therefore if i'm requesting the same file two times, the url is (sightly) different. currently the download id is generated from `url` and `path` which prevents me of checking if file the file is already downloading.
so the goal would be to override the Generation of the id (e.g. then strip the hashcodes out of the url to have a "consistent" id for the same file)

**Comment by Jacksgong** [comment]
Thank you for your prompt. I know what's you mean. In the current version(0.3.3), you can use the alternative way to handle your problem: add params in request-header(BaseDownloadTask#addHeader) instead in Url.

---

For your consideration, I will enhance the FileDownloader to handle bellow two cases:

1. Two(or more than two) different Tasks with the same target path. (The case of writing data to one file simultaneously by several different input streams must not meet expectation)
2. As your case, different Url not means different resources exactly.

**Comment by mseroczynski** [comment]
I'd also vote for simplest solution - exposing id setting to the developer.

**Comment by Jacksgong** [comment]
I will consider doing that in the next version - exposing id setting to the developer.

**Comment by mseroczynski** [comment]
Is it done now?

**Comment by mseroczynski** [comment]
Kindly please respond - will it be released in nearest 2 weeks? I'm in the process of choosing new downloader but this is a must-have.

**Comment by mseroczynski** [comment]
Hey, maybe you could find few seconds to respond sometime? I'm counting on it!

**Comment by Jacksgong** [comment]
Sorry for delay to 1.5.2. I will do this through: 

1. consider the FileDownload service may be on the separate process, it will be implemented like [cusotmize-component](https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component) way.
2. old-ids on the database will be migrated each time when the FileDownload service start.
3. on the runtime, I will use the id you provide with no hesitate、no redundant processing for it.

**Comment by mseroczynski** [comment]
@Jacksgong When are you planning to release 1.5.2? Like in a week/month/year?

**Comment by Jacksgong** [comment]
@mseroczynski I try to release 1.5.2 in a week.

**Comment by Jacksgong** [comment]
Change to 1.5.3 because of it 1.5.3 has been released now with some urgency fix, which will not affect the processing of this feature.

**Comment by Jacksgong** [comment]
Now, FileDownloader support customizing the download task identify through `FileDownloadHelper.IdGenerator` and can be validated like [this](https://github.com/lingochamp/FileDownloader/commit/e8eb4dae8fa7e41d0154c09b13bdadfbfc35c031#diff-735eadfdc1093154b937a4e0d8b2b7e6R47).

#### BUT ONE MORE THING

The customized `IdGenerator` be used on the FileDownloadService and the upper-layer, so as default FileDownloadService is running on the `:filedownloader` process, and upper-layer is on the user process, in this case, if you want to cache something on the `IdGenrator` instance, it would be two different caches on two processes.

Tips: if you want the FileDownloadService runs on the upper-layer process too, just config  `process.non-separate=true` on the `filedownloader.properties` , more detail move to [here](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)
