### ISSUE TITLE
add proguard rule to avoid apk generation error (okhttp lib error)

### ISSUE THREAD

**Issue by LuisPiresSilva** [lingochamp/FileDownloader#227]
this lib uses okhttp lib

this should be added as a pro guard rule

-dontwarn okio.**

since if not it raises errors when generating apk's
or if not added to this lib it should be added to the wiki to warn

**Comment by Jacksgong** [comment]
OK，Thanks for your prompt.

**Comment by Jacksgong** [comment]
Add to wiki: https://github.com/lingochamp/FileDownloader/wiki/Proguard-rules
