### ISSUE TITLE
对于是否支持重定向下载？

### ISSUE THREAD

**Issue by 10045125** [lingochamp/FileDownloader#228]
有很多下载是重定向下载，想知道目前能不能够支持重定向下载？

**Comment by Jacksgong** [comment]
我测试过的，okhttp自动支持重定向，重定向下载是没有问题的。你是使用过程中遇到问题了吗？

**Comment by 10045125** [comment]
我只是想了解下，还有一个问题想向你请教，就是如何能够模拟下载测试，比如模拟网络情况，模拟极端网络下下载等，你那边有什么好的思路么？

**Comment by Jacksgong** [comment]
我们是用[Charles](https://www.charlesproxy.com/)的Throttle功能，具体的建议咨询下你们的测试人员。

**Comment by ShonLin** [comment]
测试过确实不支持HTTP 302重定向，我稍微修改了一下源码，在FileDownloadRunnable类的277行，拿到response的code以后添加如下代码即可支持重定向，不用修改其他地方  
```
 //重定向出处理
if (code == HttpURLConnection.HTTP_MOVED_TEMP) {
      String redirectUrl = connection.getResponseHeaderField("Location");
      connection.ending();
      connection = mConnectionCreator.create(redirectUrl);
      addHeader(connection);
      connection.execute();
      code = connection.getResponseCode();
 }
```

**Comment by 10045125** [comment]
你使用的是Okhttp？Okhttp应该是支持的

**Comment by ShonLin** [comment]
没有用OKHttp，框架默认的HttpURLConnection
