### ISSUE TITLE
关于防盗链下载处理。

### ISSUE THREAD

**Issue by 10045125** [lingochamp/FileDownloader#231]
关于防盗链就是链接的访问次数就是1次就失效，那么对于下载模块来说能不能够有什么方案来弥补这种情况？

**Comment by Jacksgong** [comment]
防盗链通常都是服务端的工作，客户端通常不用做特殊处理，除非你们有一套自己的校验。

**Comment by viphsx123** [comment]
这里我也有个问题，如果防盗链是做的url变化处理，就是说一个文件的url会变化，我看源码是downloadId是根据url和path来生成的，那么如果url变化了，downloadId不一样了，是不是就无法做断点下载了

**Comment by Jacksgong** [comment]
是的。url不一样，目前就无法做断点续传了。。

**Comment by dd2664** [comment]
能否提供方法由调用者传入一个key，通过这个key来生成downloadId，只要调用者传的key不变，url变了也能断点续传？

**Comment by Jacksgong** [comment]
@dd2664 这个任务已经在计划中了: #224

**Comment by Jacksgong** [comment]
参考 #617 与 #224 

- 1.5.4版本支持了定制id ( #224 )
- 1.5.7(准备发布中)支持了相同任务替换url ( #617 )
