### ISSUE TITLE
急！求助。no connect service !! -1052744516

### ISSUE THREAD

**Issue by bai53229** [lingochamp/FileDownloader#232]
你好，我是使用的Eclipse版（按照作者上次给的方法导入的jar包），代码参照的NotificationDemoActivity，stadio版本运行正常，但是下载异常了······，鉴于技术水平有限，看了几天源码没怎么看懂，所以过来找作者求助，急。非常感谢。下面是Logcat：
``
![7 mak cxbbk 49 4d m1](https://cloud.githubusercontent.com/assets/17465558/17243171/ba5e4a84-55ad-11e6-9915-2c99ecd48793.png)
![a z sxl499v hgxv11 isr](https://cloud.githubusercontent.com/assets/17465558/17243172/bafc562a-55ad-11e6-9a09-d02c17824904.png)
![o 9 z7yv 0txc_as3sy8 n](https://cloud.githubusercontent.com/assets/17465558/17243173/bc71b6c6-55ad-11e6-9290-ea86be13b889.png)

**Comment by Jacksgong** [comment]
`no connect service !! -1052744516` 这句日志并不打紧的。设计如此，你可以看到是debug级别的日志。

在没有连接上的时候，后面就会自动连上，我看你日志后面也连接上了，这个日志看起来是没有问题的:

![image](https://cloud.githubusercontent.com/assets/6176417/17245023/1dadd376-55b7-11e6-8c17-2a89f2e943df.png)

**Comment by Jacksgong** [comment]
我看这块日志，你这应该是wen'jia文件已经下载完成在本地了，不用重新下载因此直接完成了。如果你需要强制重新下载看下 `BaseDownloadTask#forceReDownload`
![image](https://cloud.githubusercontent.com/assets/6176417/17245044/42c92c46-55b7-11e6-9867-8aa586338ddf.png)

**Comment by bai53229** [comment]
额，是这样的，我只有去检查有没有下载后的这个文件，没有去看数据库存储的下载进度。现在正常了，非常感谢。

**Comment by Jacksgong** [comment]
好的。
