### ISSUE TITLE
能不能让下载成功后的文件自动回原成默认文件？

### ISSUE THREAD

**Issue by xanaduo** [lingochamp/FileDownloader#233]
比如我现在下载一个https://qd.myapp.com/myapp/qqteam/AndroidQQ/mobileqq_android.apk，我看到下载的时候后缀多了一个.temp，下载成功后去掉了temp后缀。我在想能不能在这个时候直接是文件名呢？

**Comment by Jacksgong** [comment]
目前下载完成，确实是自动重命名为 目标文件。

**Comment by xanaduo** [comment]
但是这样的话，我还要去改名字。因为我下载完成了还要用的。比如安装apk、解压等。

**Comment by Jacksgong** [comment]
下载完成是会自动修改为 目标文件的名字 (没有temp后缀)。 你是遇到下载完成了还有 `temp`后缀吗？

**Comment by xanaduo** [comment]
没有temp后缀，但是名字还是MD5加密的吧

**Comment by Jacksgong** [comment]
如果下载时你提供的是文档目录(`BaseDownloadTask#setPath(path, true)`)。

那么默认会通过后台返回回来的Response中的ContentDisposition去取文件名，如果后台没有给ContentDisposition或者不规范，本地文件名就只能通过对url做md5作为其文件名。

> 关于 Content-Disposition 可以看官方定义: https://www.w3.org/Protocols/rfc2616/rfc2616-sec19.html

**Comment by Jacksgong** [comment]
FileDownloader中决定文件名的相关代码: `FileDownloadRunnable#findFilename`.

**Comment by xanaduo** [comment]
好的
