### ISSUE TITLE
断点续传需要服务器做哪些支持？

### ISSUE THREAD

**Issue by bai53229** [lingochamp/FileDownloader#234]
你好，服务器端一直接收不到我发送的Range，应该是程序判断不支持断点续传，请问服务器url需要什么设置什么参数，是必须要设置eTag？

**Comment by Jacksgong** [comment]
我已最新版本0.3.3为例，

> 是支持断点续传的。你也可以直接下载demo project跑跑看看。

1. 不一定要设置ETAG。
2. 本地会尽量给range。
3. 你可以自己DEBUG下看看，能不能断点续传会先过: `FileDownloadRunnable#checkIsResumeAvailable()`，然后通过 `FileDownloadRunnable#addHeader` 添加Range。
