### ISSUE TITLE
When the provided path is a directory, and the task has already downloaded, start the task again, we receive completed, but the return value of getTargetFilePath may null

### ISSUE THREAD

**Issue by cRenJie** [lingochamp/FileDownloader#237]
你好，我在我的App上第一次下载完成之后，关闭app，再次打开并且下载同一个文件，```task.getTargetFilePath()``` 返回为 null

**Comment by Jacksgong** [comment]
## `BaseDownloadTask#getTargetFilePath` 的逻辑比较简单:

1. 如果你提供的是文档目录，文件名是在建立连接以后Response中获取的，在创建连接之前都获取不了目标路径。
2. 如果提供的是非文档目录，而是文件路径，会直接返回你提供的文件路径。

---

如果你不解，建议直接DEBUG进去看看。

**Comment by chrenjay** [comment]
我提供的是文档目录，在 ```FileDownloadListener#completed``` 中 ```getTargetFilePath```获取为 null，请问是如何辨别是同一个文件的？是不是如果辨别是下载过的文件就没有分配文件名，因为我在设置为文件路径之后工作正常

**Comment by Jacksgong** [comment]
在已经下载完成，再次启动下载，并且提供的是 文档目录的时候，确实是有可能在 `completed`中获取到的 `getTargetFilePath` 为 `null`，我已经找到原因，我会在新的版本尽快修复。 感谢你的ISSUE。

## 原因:

之前在优化的时候，为了减轻KeepFlow线程池的压力，将 `completed`(旧文件已存在的情况) 与 `warn` 不走 KeepFlow的线程池。但是如果是文档的时候，其实是不应该这样的，因为只有在 `connected` 回调以后，才会存在文件路径。

## 解决方案

在如果提供是文档目录的时候，回调始终都需要走KeepFlow线程池，保证相同任务的回调FIFO。

**Comment by Jacksgong** [comment]
Fixed since [0.3.5](https://github.com/lingochamp/FileDownloader/releases/tag/v0.3.5).
