### ISSUE TITLE
请问下载状态是通过什么来获取的？

### ISSUE THREAD

**Issue by xanaduo** [lingochamp/FileDownloader#238]
难道不是通过cache文件下的缓存文件获取的吗？为什么我删除了缓存文件还是有状态啊？

**Comment by xanaduo** [comment]
我发现我杀死进程后，这个状态才恢复正常。难道内存中还保留了吗？

**Comment by Jacksgong** [comment]
## 原因

如果某任务未下载完成，数据库中以及缓存中会存储某任务的下载状态，用于保证各种情况下的断点续传能够正常进行。

而在每次下载服务启动的时候，会扫描所有已有数据，删除脏数据，因此你在杀死进程重新启动的时候发现状态正常。

---

## 解决方案

如果你需要强制弃用某任务在FileDownloader中的所有数据，可以通过 `FileDownloader#clear` 接口进行清除。

**Comment by xanaduo** [comment]
并没有看到这个接口方法啊

**Comment by Jacksgong** [comment]
这个接口在 [0.3.4](https://github.com/lingochamp/FileDownloader/blob/master/CHANGELOG-ZH.md#version-034) 添加的。建议你使用当前最新版本0.3.4
