### ISSUE TITLE
"任务管理器案例"文佳下载成功后无法打开

### ISSUE THREAD

**Issue by huixiangdou** [lingochamp/FileDownloader#239]
例如文件地址:http://***/123.jpg
下载成功后文件名为:"353gjhjg66765hhdhjgjhg",
文件无jpg后缀,此文件手动添加jpg后缀后,可以打开.

**Comment by Jacksgong** [comment]
> 为了更加的灵活FileDownloader不会主动添加拓展名。

## FileDownloader支持: 

1. 可以主动的设置存储路径以及文件名就是包含拓展名: `BaseDownloadTask.setPath("xxx/xxx/xx/xxx.jpg", false)`。
2. 可以通过提供的是文档目录: `BaseDownloadTask.setPath(directory, true)`，然后后端返回的`response`中带下来contentDisposition中的文件名带有拓展名。

**Comment by huixiangdou** [comment]
已经解决,非常感谢!

**Comment by Jacksgong** [comment]
恩。好的。
