### ISSUE TITLE
你好，请问如何从新启动的UI界面恢复一个正在下载的后台任务？

### ISSUE THREAD

**Issue by iwhys** [lingochamp/FileDownloader#24]

**Comment by Jacksgong** [comment]
我不是很明白，正在下载，为什么还需要恢复。是说获取进度与状态吗？

**Comment by iwhys** [comment]
比如说我有一个activity启动了下载任务，之后返回到其他界面，下载任务在后台继续，再重新进入这个activity时，如何更新当前的下载进度？谢谢

**Comment by Jacksgong** [comment]
恩。好的，我知道你的问题了。

---

#### 1. 如果仅仅是需要获得进度或者是状态

> 可以通过`FileDownloader#getStatus()`、 `FileDownloader#getSoFar()`。

#### 2. 如果需要重新获得进度与状态变化监听

> 可以参考 #4 的解答。

#### 3. 如果是任务管理相关

> 建议参考: [TasksManagerDemoActivity](https://github.com/lingochamp/FileDownloader/blob/master/demo/src/main/java/com/liulishuo/filedownloader/demo/TasksManagerDemoActivity.java)

**Comment by iwhys** [comment]
好的 多谢

**Comment by Jacksgong** [comment]
:)
