### ISSUE TITLE
我将下载放在service里面 模仿demo的notificatio下载报错

### ISSUE THREAD

**Issue by yubang322311** [lingochamp/FileDownloader#240]
按照log的信息应该是getManager().notify(getId(), builder.build());这句代码报错 可是不知哪里错了 请帮忙分析下 谢谢！！！。

08-02 09:51:50.502  4662  4662 E AndroidRuntime: java.lang.IllegalArgumentException: target object must not be null
08-02 09:51:50.502  4662  4662 E AndroidRuntime: 	at com.virtualengine.reflect.Validate.isTrue(Validate.java:32)
08-02 09:51:50.502  4662  4662 E AndroidRuntime: 	at com.virtualengine.reflect.FieldUtils.writeField(FieldUtils.java:159)
08-02 09:51:50.502  4662  4662 E AndroidRuntime: 	at com.virtualengine.hook.handle.INotificationManagerHookHandle.hackNormalNotification(INotificationManagerHookHandle.java:633)
08-02 09:51:50.502  4662  4662 E AndroidRuntime: 	at com.virtualengine.hook.handle.INotificationManagerHookHandle.access$500(INotificationManagerHookHandle.java:63)
08-02 09:51:50.502  4662  4662 E AndroidRuntime: 	at com.virtualengine.hook.handle.INotificationManagerHookHandle$enqueueNotificationWithTag.beforeInvoke(INotificationManagerHookHandle.java:548)
08-02 09:51:50.502  4662  4662 E AndroidRuntime: 	at com.virtualengine.hook.HookedMethodHandler.doHookInner(HookedMethodHandler.java:48)
08-02 09:51:50.502  4662  4662 E AndroidRuntime: 	at com.virtualengine.hook.binder.BinderHook.invoke(BinderHook.java:59)
08-02 09:51:50.502  4662  4662 E AndroidRuntime: 	at com.virtualengine.hook.binder.INotificationManagerBinderHook.invoke(INotificationManagerBinderHook.java:34)
08-02 09:51:50.502  4662  4662 E AndroidRuntime: 	at java.lang.reflect.Proxy.invoke(Proxy.java:393)
08-02 09:51:50.502  4662  4662 E AndroidRuntime: 	at $Proxy3.enqueueNotificationWithTag(Unknown Source)
08-02 09:51:50.502  4662  4662 E AndroidRuntime: 	at android.app.NotificationManager.notify(NotificationManager.java:230)
08-02 09:51:50.502  4662  4662 E AndroidRuntime: 	at android.app.NotificationManager.notify(NotificationManager.java:194)
08-02 09:51:50.502  4662  4662 E AndroidRuntime: 	at com.mephone.greenbox.activity.NotificationItem.show(NotificationItem.java:99)
08-02 09:51:50.502  4662  4662 E AndroidRuntime: 	at com.liulishuo.filedownloader.notification.BaseNotificationItem.show(BaseNotificationItem.java:46)
08-02 09:51:50.502  4662  4662 E AndroidRuntime: 	at com.liulishuo.filedownloader.notification.FileDownloadNotificationHelper.showIndeterminate(FileDownloadNotificationHelper.java:105)
08-02 09:51:50.502  4662  4662 E AndroidRuntime: 	at com.liulishuo.filedownloader.notification.FileDownloadNotificationListener.showIndeterminate(FileDownloadNotificationListener.java:92)
08-02 09:51:50.502  4662  4662 E AndroidRuntime: 	at com.liulishuo.filedownloader.notification.FileDownloadNotificationListener.pending(FileDownloadNotificationListener.java:138)
08-02 09:51:50.502  4662  4662 E AndroidRuntime: 	at com.mephone.greenbox.activity.NotificationListener.pending(NotificationListener.java:64)
08-02 09:51:50.502  4662  4662 E AndroidRuntime: 	at com.liulishuo.filedownloader.FileDownloadListener.callback(FileDownloadListener.java:60)
08-02 09:51:50.502  4662  4662 E AndroidRuntime: 	at com.liulishuo.filedownloader.FileDownloadMessenger.handoverMessage(FileDownloadMessenger.java:255)
08-02 09:51:50.502  4662  4662 E AndroidRuntime: 	at com.liulishuo.filedownloader.FileDownloadMessageStation$UIHandlerCallback.dispose(FileDownloadMessageStation.java:179)
08-02 09:51:50.502  4662  4662 E AndroidRuntime: 	at com.liulishuo.filedownloader.FileDownloadMessageStation$UIHandlerCallback.handleMessage(FileDownloadMessageStation.java:170)
08-02 09:51:50.502  4662  4662 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
08-02 09:51:50.502  4662  4662 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:207)
08-02 09:51:50.502  4662  4662 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5728)
08-02 09:51:50.502  4662  4662 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-02 09:51:50.502  4662  4662 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
08-02 09:51:50.502  4662  4662 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by yubang322311** [comment]
对了 demo里面到通知下载案例也会报错 我手机6.0的  android:targetSdkVersion="22"
08-02 10:38:23.872 27016 27016 E AndroidRuntime: Process: com.liulishuo.filedownloader.demo, PID: 27016
08-02 10:38:23.872 27016 27016 E AndroidRuntime: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(pri=-2 contentView=com.liulishuo.filedownloader.demo/0x1090085 vibrate=null sound=null tick defaults=0x4 flags=0x3 color=0x00000000 actions=1 vis=PRIVATE)
08-02 10:38:23.872 27016 27016 E AndroidRuntime: 	at android.app.NotificationManager.notify(NotificationManager.java:222)
08-02 10:38:23.872 27016 27016 E AndroidRuntime: 	at android.app.NotificationManager.notify(NotificationManager.java:194)
08-02 10:38:23.872 27016 27016 E AndroidRuntime: 	at com.liulishuo.filedownloader.demo.NotificationDemoActivity$NotificationItem.show(NotificationDemoActivity.java:264)
08-02 10:38:23.872 27016 27016 E AndroidRuntime: 	at com.liulishuo.filedownloader.notification.BaseNotificationItem.show(BaseNotificationItem.java:46)
08-02 10:38:23.872 27016 27016 E AndroidRuntime: 	at com.liulishuo.filedownloader.notification.FileDownloadNotificationHelper.showIndeterminate(FileDownloadNotificationHelper.java:105)
08-02 10:38:23.872 27016 27016 E AndroidRuntime: 	at com.liulishuo.filedownloader.notification.FileDownloadNotificationListener.showIndeterminate(FileDownloadNotificationListener.java:92)
08-02 10:38:23.872 27016 27016 E AndroidRuntime: 	at com.liulishuo.filedownloader.notification.FileDownloadNotificationListener.pending(FileDownloadNotificationListener.java:138)
08-02 10:38:23.872 27016 27016 E AndroidRuntime: 	at com.liulishuo.filedownloader.demo.NotificationDemoActivity$NotificationListener.pending(NotificationDemoActivity.java:165)
08-02 10:38:23.872 27016 27016 E AndroidRuntime: 	at com.liulishuo.filedownloader.FileDownloadListener.callback(FileDownloadListener.java:60)
08-02 10:38:23.872 27016 27016 E AndroidRuntime: 	at com.liulishuo.filedownloader.FileDownloadMessenger.handoverMessage(FileDownloadMessenger.java:262)
08-02 10:38:23.872 27016 27016 E AndroidRuntime: 	at com.liulishuo.filedownloader.FileDownloadMessageStation$UIHandlerCallback.dispose(FileDownloadMessageStation.java:179)
08-02 10:38:23.872 27016 27016 E AndroidRuntime: 	at com.liulishuo.filedownloader.FileDownloadMessageStation$UIHandlerCallback.handleMessage(FileDownloadMessageStation.java:170)
08-02 10:38:23.872 27016 27016 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
08-02 10:38:23.872 27016 27016 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:207)
08-02 10:38:23.872 27016 27016 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5728)
08-02 10:38:23.872 27016 27016 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-02 10:38:23.872 27016 27016 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
08-02 10:38:23.872 27016 27016 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by Jacksgong** [comment]
你找到原因了吗。因为我初步看了下没有看出端倪，本来下抽空的时候再看的。
