### ISSUE TITLE
一键清理之后，下载状态有问题

### ISSUE THREAD

**Issue by viphsx123** [lingochamp/FileDownloader#241]
当正在后台进行下载时，使用一键清理这类的软件之后，下次再进入下载界面时，会发现那些下载的任务的状态都是0，即    public final static byte INVALID_STATUS = 0;
这样就无法进行逻辑判断了啊，针对此类问题，有什么解决办法呢？

**Comment by Jacksgong** [comment]
## FileDownloader会将未下载完成的文件的一些信息以及状态存储到数据库中

> 以便于断点续传。

如果应用被卸载了，或者应用数据库被清理都会引起 未下载完成的任务 无法再进行断点续传，因为已经数据库中已经没有任何数据了。此时如果通过获取下载任务的状态，也肯定都是INVALID_STATUS的。

**这种情况暂时没有办法解决。**

### 但是也不推荐解决，主要原因

> 去解决这个问题，是很常见的过渡设计的一种

1. 无论用户是卸载应用，或者清理应用数据库，都是主动的需要将应用的数据清除，当用户重新安装或者清理完再进入的时候，一切重头开始，这个是符合用户预期的。
2. 这个Case有点类似系统推荐应用存储: 系统推荐非机密文件存储放到`Context#getExternalFilesDir`(`/sdcard/data/Android/<package name>/`)，机密或特殊的小文件放到`Context#getFilesDir`(`/data/data/<package name>/files`)，这些目录在应用清理，或者是卸载的时候，都会一并被删除。

**Comment by viphsx123** [comment]
@Jacksgong  但是好像还有一个问题，也是关于下载状态的，当我手动暂停一个任务，执行如下代码                FileDownloader.getImpl().pause(holder.donwloadId);
暂停之后，退出应用；然后再次打开应用进入下载页面，发现那些暂停的应用获取到的状态不是暂停，而是    public final static byte INVALID_STATUS = 0;
但是我去filedownloader的数据库中看到的下载状态是暂停，即    public final static byte paused = -2;
这是什么原因呢

**Comment by Jacksgong** [comment]
这是因为FileDownloadService没有打开，你可以留意下IDE中的Logcat，如果遇到不达预期的情况，FileDownloader通常会直接输出WARN级别的日志的。

> P.S: 在开始下载任意一个任务的时候，如果检测到FileDownloadService还没有启动，会自动启动。

```
if (FileDownloader.getImpl().isServiceConnected()) {
       // 直接获取状态
} else {
    final FileDownloadConnectListener listener = new FileDownloadConnectListener() {
        @Override
        public void connected() {
            // 直接获取状态。
        }

        @Override
        public void disconnected() {

        }
    };

    FileDownloader.getImpl().addServiceConnectListener(listener);
    // waiting to connect....


    // 别忘了在不需要使用的时候移除监听
}
```
