### ISSUE TITLE
退出后应用后下载问题

### ISSUE THREAD

**Issue by Owen0103** [lingochamp/FileDownloader#242]
demo去掉删除通知的操作，退出应用后会一直下载，并且通知栏进度条会更新，但是直接把demo拷贝到自己的工程，什么都没修改，退出后后进度条却停止更新 了，是什么原因呢大神？

**Comment by Owen0103** [comment]
@Jacksgong 是什么原因导致的 呢

**Comment by Jacksgong** [comment]
demo中的 通知案例有BUG，在退出应用的时候，没有cancel掉对应的通知。我抽空的时候会修复掉。

**Comment by Owen0103** [comment]
@Jacksgong 你的意思本身是不支持退出应用后继续回调下载进度的吗 、包括下载完成的回调

**Comment by Owen0103** [comment]
@Jacksgong 如果我想退出应用后也支持下载，包括进度条继续展示，就当前的这个lib有什么好的解决方案吗？

**Comment by Jacksgong** [comment]
当前lib是没有绑定任何Activity的，当前lib就支持的。

**Comment by Jacksgong** [comment]
你只需要在退出应用的时候不要停止下载或者关闭通知即可。

**Comment by Jacksgong** [comment]
这只是一个下载的组件，理论上可以应付任何的场景。
