### ISSUE TITLE
请问下 我设置了下载文件的绝对路径 也就是setPath 没有作用

### ISSUE THREAD

**Issue by zxc120301945** [lingochamp/FileDownloader#244]
设置了下载路径 只是给了文件路径的参数 下载回调完成后并没有在这个路径里面找到下载的文件，我甚至不知道文件下载到哪里去了 ，居然会回调完成。我使用默认的下载路径，就能下载成功并且能正确获取到下载的文件。
还有一个问题，我使用的是FileDownloadListener这个回调，我在所有的回调方法中打上了Log,但是只有完成的方法 completed() ，调用了 ，能指导下吗 谢谢！

**Comment by Jacksgong** [comment]
在完成之前，会检测本地文件的大小与`content-length`，如果不相等就不会回调 `completed`。

将你的场景放到 里面试试看。因为你这个是很简单的Case，根据你的描述我并不能分析除问题在哪，很有可能是使用的问题。

建议你clone [demo project](https://github.com/lingochamp/FileDownloader/tree/master/demo)，然后看看里面的 `SingleTaskTestActivity`。

**Comment by zxc120301945** [comment]
我使用的是这个 github 上面所说的 启动多任务下载的方法
在每一个回调函数里面去打印log  发现只是走了 completed这个方法 但是我设置了setpath 就出现了上述的问题

**Comment by zxc120301945** [comment]
我刚用了 singleTaskTestActivity Demo 里面的方法 发现都不能下载了 - - 因为没有报错 我现在也不知道是什么原因。我用 FileDownloader.getImpl().create(url)
        .setListener(new FileDownloadListener() 至少还能下载成功 只是不能设置路径而已

**Comment by Jacksgong** [comment]
不能下载，也没有报错？好奇怪。你看看Logcat里面有没有FileDownloader输出的warn级别或warn级别以上的日志。

如果demo没有问题，你一替换成你的url就出现这个问题。你把url发给我，我看看是什么诡异的情况。

**Comment by zxc120301945** [comment]
url 应该是可以下载的 因为我用了FileDownloader.getImpl().create(url)
.setListener(new FileDownloadListener() 这个下载函数 是可以下载成功的 只是设置路径的问题 我按照您github上的设置路径是先创建了文件的绝对路径然后开始下载的
另外一个下载函数为什么出现不能下载的情况，而且我在log里面也没有任何的日志 是没有任何关于下载的日志。我暂时没有找到原因。

**Comment by Jacksgong** [comment]
你了解下:

- `BaseDownloadTask#setPath(文档目录, true)`
- `BaseDownloadTask#setPath(下载文件的绝对路径(文档目录/文件名), false)` 或 `BaseDownloadTask#setPath(下载文件的绝对路径(文档目录/文件名))`

---

在下载之前，不需要提前创建文件。

---

不能下载没有任何日志，我觉得好诡异。**由于你现在的描述我并不能定位出问题所在，如果你始终无法找到根源问题，也可以直接将你的有问题的项目（或者建一个小的有问题的项目），发给我(可以通过邮件igzhenjie@gmail)，我抽空给你看看原因**。

**Comment by zxc120301945** [comment]
我使用FileDownloader.getImpl().create(url)
.setListener(new FileDownloadListener()
的时候有日志出现了
filedownloader D/ResourcesManager: creating new AssetManager and set to /data/app/com.you.edu.school-2/base.apk

**Comment by zxc120301945** [comment]
FileDownloader.getImpl().create(segs1.getPlayUrl())
//                            .setPath(localpath)
//                            .setCallbackProgressTimes(300)
//                            .setMinIntervalUpdateSpeed(400)
//                            .setListener(new FileDownloadSampleListener()
这个方法 我就只是这样做了 
localpath: /storage/emulated/0/YouSchool/downloader/temp 这个是文件的绝对路径 我按照你说了 没有先创建出文件 只是先创建出文件夹 
但是没有任何日志 我进入这个文件夹内部 文件并没有创建出来

**Comment by zxc120301945** [comment]
然后 我又使用了
 FileDownloadQueueSet queueSet = new FileDownloadQueueSet(downloadListener);
 List<BaseDownloadTask> tasks = new ArrayList<>();
FileDownloader.getImpl().create(segs1.getPlayUrl())
                            .setPath(localpath,false)
                            .setListener(downloadListener).start();
                    tasks.add(FileDownloader.getImpl().create(segs1.getPlayUrl()).setPath(s).setTag(1));
                    queueSet.disableCallbackProgressTimes();
                    queueSet.setAutoRetryTimes(1);
                    queueSet.downloadSequentially(tasks);
                    queueSet.start();
这个函数，路径还是刚才那个路径，最后在回调中只有completed回调了 并且还返回了文件的路径，但是只有目录的路径，最后文件并没有创建出来，下载也是没有作用。最后在日志中打印了
filedownloader D/ResourcesManager: creating new AssetManager and set to /data/app/com.you.edu.school-2/base.apk 这一段信息

**Comment by zxc120301945** [comment]
下载的地址是： http://k.youku.com/player/getFlvPath/sid/847021478865296666058_00/st/mp4/fileid/030008040056F9544E0996137DF1DBBFC5BA1C-56B6-1296-5C32-90F936CEF10E?ts=382&ctype=96&token=6860&did=d584beeb&ev=1&ep=mb4Fy0b4cpLUOsROuBZhxlHUaJL%2BnpfWCmt0xXtzaAbkkuYlQdNpgxyGUS9JwDZmI%2BFhXVjhHHwC%0Ad3%2F1CrzLmiFjpAKoysbZ4C9rIMUtVlYX%2B51pgSZ0GllkNJQ64VzD&oip=3702858340&hd=1&K=dbe1b03ce5f172aa261f286c&

**Comment by Jacksgong** [comment]
我直接将 [SingleTaskTestActivity 中第一个任务中的url](https://github.com/lingochamp/FileDownloader/blob/cb04c77cf5e4aba42bcdab1ab77966325d2d341c/demo/src/main/java/com/liulishuo/filedownloader/demo/SingleTaskTestActivity.java#L157)替换为你这个连接，发现基本都是回调404错误。你可以自己试试。

```
url = "http://k.youku.com/player/getFlvPath/sid/847021478865296666058_00/st/mp4/fileid/030008040056F9544E0996137DF1DBBFC5BA1C-56B6-1296-5C32-90F936CEF10E?ts=382&ctype=96&token=6860&did=d584beeb&ev=1&ep=mb4Fy0b4cpLUOsROuBZhxlHUaJL%2BnpfWCmt0xXtzaAbkkuYlQdNpgxyGUS9JwDZmI%2BFhXVjhHHwC%0Ad3%2F1CrzLmiFjpAKoysbZ4C9rIMUtVlYX%2B51pgSZ0GllkNJQ64VzD&oip=3702858340&hd=1&K=dbe1b03ce5f172aa261f286c&";
tag = new ViewHolder(new WeakReference<>(this), progressBar1, null, speedTv1, 1);
path = llsApkFilePath;
tag.setFilenameTv(filenameTv1);
break;
```

**Comment by Jacksgong** [comment]
问题解决了吗？如果还没有解决或者不理解的，及时评论。

---

因为从你的描述中，我无法发现有用的信息，这只是一个很简单的流程。

如果始终没有解决，直接发遇到问题的demo project给我。或者你可以fork FileDownloader项目，然后修改现有的Demo Project，然后push到远端，我从你那边拉下来看看都行。

**Comment by zxc120301945** [comment]
还是不行 ，是不是我并没有开启日志的开关，我发现我做什么都没有日志输出

**Comment by Jacksgong** [comment]
你这样做:

你Clone 下来demo project，然后按照这个修改: https://github.com/lingochamp/FileDownloader/issues/244#issuecomment-237197849

然后你看看情况。

**Comment by Jacksgong** [comment]
如果你觉得你的日志显示这块有问题，最简单的方法你直接将FileDownloader中的每一个方法都用Toast, toast出来。

**Comment by zxc120301945** [comment]
我就是这样做的 但是 不管怎么修改 他只会回调completed这个方法 哪怕是我不去设置path 它下载文件是成功的

**Comment by Jacksgong** [comment]
你不设置path会使用默认的文件路径。在 `FileDownloadUtils#getDefaultSaveFilePath`，如果一启动，马上就成功了。就是文件已经下载完成了。

**Comment by Jacksgong** [comment]
完成以后，你通过 `completed`回调参数`task:BaseDownloadTask` 取出文件路径: `BaseDownloadTask#getTargetFilePath`，然后看看文件是不是存在。

**Comment by zxc120301945** [comment]
不设置的话 是可以下载成功的 
是不是我设置的路径有问题 
我是首先去创建目录文件夹 然后把这个路径给设置进去 
但是 我发现目录文件夹创建成功了，但是文件并没有创建出来，也没有进行下载

**Comment by zxc120301945** [comment]
然后我使用了 你 SingleTaskTestActivity 的demo  我就更改了路径就不能进行下载了

**Comment by Jacksgong** [comment]
> 然后我使用了 你 SingleTaskTestActivity 的demo 我就更改了路径就不能进行下载了

你看看报的错误。demo project中并没有申请 sdcard的读写权限。如果你的路径是sdcard的路径，很有可能是权限问题。 你看看 `FileDownloadListener#error`的回调。

**Comment by Jacksgong** [comment]
@zxc120301945 情况如何。

**Comment by zxc120301945** [comment]
我昨天有点忙，回去后调整了一下，使用SingleTaskTestActivity 的Demo 设置了我自己的url 和本地绝对路径，没有问题了，但是我把这些代码放到我的项目中去，什么都没改 就是把.setTag(tag)去掉了 ，然后就下载不了了 也没有日志。

**Comment by Jacksgong** [comment]
那你可以不可以自己写一个有问题的小的demo发给我(igzhenjie@gmail.com)，我给你看下是哪里出现的问题。

**Comment by Jacksgong** [comment]
你在demo SingleTaskTestActivity的Demo中，也将.setTag(tag)去掉，demo中有问题吗？

**Comment by Jacksgong** [comment]
你可以试试将demo SingleTaskTestActivity的Demo中，也将.setTag(tag)去掉，然后将监听器里面的 `((ViewHolder) task.getTag()).xxx`修改为日志输出。


根据你的描述，我可以十分确定是上层使用的问题。

**Comment by Xanthuim** [comment]
他这种情况我也遇到过，应该是setPath的时候设置的是目录，而目录要把第二个参数加上去true。否则就会出现pending完了直接走complete

**Comment by Jacksgong** [comment]
@Xanthuim pending完直接走complete，说明本地的文件已经是存在了。

- 如果你要强制覆盖: `BaseDownloadTask#setForceReDownload(true)`

---

关于`setPath`的第二个参数，是指定该路径是否是作为目录:

```java
/**
 * @param path            The absolute path for saving the download file.
 * @param pathAsDirectory {@code true}: if the {@code path} is absolute directory to store the
 *                        downloading file, and the {@code filename} will be found in
 *                        contentDisposition from the response as default, if can't find
 *                        contentDisposition,the {@code filename} will be generated by
 *                        {@link FileDownloadUtils#generateFileName(String)}  with {@code url}.
 *                        </p>
 *                        {@code false}: if the {@code path} = (absolute directory/filename).
 * @see #isPathAsDirectory()
 * @see #getFilename()
 */
BaseDownloadTask setPath(final String path, final boolean pathAsDirectory);
```
