### ISSUE TITLE
多task下载时，onProgress 和 onComplete回调是并发的还是串行的？

### ISSUE THREAD

**Issue by pop1030123** [lingochamp/FileDownloader#245]

**Comment by Jacksgong** [comment]
默认情况下(`BaseDownloadTask#setSyncCallback(false)`)， FileDownloadListener中所有回调都是抛到UI线程中回调的，因此是串行。

如果(`BaseDownloadTask#setSyncCallback(true)`)，那么回调线程会在信息流线程，也许回调的不是同一个线程(但是肯定不是UI线程)，但是内部的 信息流线程池会保证 同一个任务的 信息流是串行的。

---

因此对外层而言，FileDownloadListener中的所有回调始终都是串行的。

> PS: FileDownloader除了控制串行，默认情况下还会开启防止回调DDOS的情况，防止由于回调太过频繁导致掉帧，可以通过`FileDownloader#disableAvoidDropFrame` 进行关闭。

**Comment by Jacksgong** [comment]
## 对外层而言，对于同一个任务而言FileDownloadListener中的所有回调始终都是串行的。
## 对外层而言，对于不同的任务而言FileDownloadListener中的所有回调始终都是并发的。

**Comment by pop1030123** [comment]
如果不同的任务传入同样的Listener对象，那个回调listener对象都是多线程访问的？

**Comment by Jacksgong** [comment]
无论是否是同一个listener，调用逻辑都是这样:

- 默认情况下(BaseDownloadTask#setSyncCallback(false))， FileDownloadListener中所有回调都是抛到UI线程中回调的，因此都是在同一个线程，是串行。

- 如果(BaseDownloadTask#setSyncCallback(true))，那么回调线程会在信息流线程，也许回调的不是同一个线程(但是肯定不是UI线程)，但是内部的 信息流线程池会保证 同一个任务的 信息流是串行的，不同的任务是并行。
