### ISSUE TITLE
下载文件时 在任务列表中关闭应用 状态栏里面的下载通知就永远不能cancel了

### ISSUE THREAD

**Issue by yubang322311** [lingochamp/FileDownloader#248]
我是在服务中开启的下载并会在通知栏显示notification  帮忙看下有没有解决方法

**Comment by Jacksgong** [comment]
> NotificationService在另外一个进程，根据不同定制ROM的不同，关闭应用是否会连带把NOTIFICATION一起关掉的机制也略有差异

> 不过NOTIFICATION显示与否，与你的应用有没有关闭没有必然关系。

你有几种方式Cancel Notification ( 这个不属于FileDownloader的范畴):

1. 非ongoing Notification，用户可以主动划掉对应通知，Ref `NotificationCompat.Builder#setOngoing(Boolean)`
2. 存储对应Notification的Id，通过 `NotificationManager#cancel` 进行清除。Ref `((NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE)).cancelAll();`
3. 通过 `((NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE)).cancelAll();` 将所有 与该应用包名相同的 并且正在显示的所有的 NOTIFICATION。


----

> P.S: DEMO PORJECT中的通知这块的bug是，我在暂停的时候就将 `notification Id`（downloadId）置位了0，导致，返回时，在cancel的时候，提供的并非正在显示的notification的ID。
