### ISSUE TITLE
FileDownloadListener的progress方法中的totalBytes为-1?

### ISSUE THREAD

**Issue by rehan91** [lingochamp/FileDownloader#249]
我可以知道sofar,但是total为-1,我怎么才能知道当前下载的百分比呢?

**Comment by Jacksgong** [comment]
如果你所下载的资源是Chunked (流媒体)，由于返回的header中不带有`content-length` 因此我们是无法获知该资源的大小的。只有在输入流中不断取，取完以后才知道流媒体的大小。

**Comment by Jacksgong** [comment]
在 Chunked 的情况下，下载过程，total始终都是-1。

**Comment by rehan91** [comment]
嗯,这个我知道,那下载的百分比可以通过什么途径得知吗?比如我现在下载了20%或者30%要告诉用户?

**Comment by rehan91** [comment]
可以设置不用chunk吗?取消Gzip?

**Comment by Jacksgong** [comment]
不行。

Chunked是Response中的 `Transfer-Encoding`字段是 `chunked`，并且按照你所描述的情况，你这个资源的Response肯定是没有`content-length`字段。

---

- 相关FileDownloader中的代码，[FileDownloadRunnalbe#isEncodingChunked](https://github.com/lingochamp/FileDownloader/blob/62a4399dfa3fe3d20d2e2445522a2ca234014fdf/library/src/main/java/com/liulishuo/filedownloader/services/FileDownloadRunnable.java#L278)
- [Chunked_transfer_encoding Wiki](https://en.wikipedia.org/wiki/Chunked_transfer_encoding).

**Comment by rehan91** [comment]
那也就是说没办法知道进度咯?

**Comment by Jacksgong** [comment]
## 不是的。你有以下方式可以获取:

1. 如果你下载的是媒体文件(如mp3、mp4等等)，那么根据不同的文件编码方式，在通常在文件头中存有相关信息，或者提供可计算长度的信息。
2. 通过独立的一个API请求来获取该文件的长度，然后再开始下载。

**Comment by JulianSong** [comment]
下载链接添加addHeader("Accept-Encoding", "identity")可以解决我的问题。不知道与作者说的有没有关系

**Comment by Jacksgong** [comment]
@JulianSong 如果服务端对该资源支持就可以的。
