### ISSUE TITLE
请问可以设置retry的间隔时间吗

### ISSUE THREAD

**Issue by goIntoAction** [lingochamp/FileDownloader#251]
我在部分MTK芯片的手机下载大文件，可能遇到网上所说的断流问题，wifi显示是连上，但是下载中断了，这时候立即重试是没用的，要等个几秒。很奇怪，为什么error也没回调

**Comment by Jacksgong** [comment]
暂时不支持，主要是考虑到这个不确定因素很多，而且是主要是上层业务需求，因此暂时并没有做支持的打算。

**Comment by auxor** [comment]
能够开放接口支持自定义retry间隔
