### ISSUE TITLE
why do not work chuncked file 

### ISSUE THREAD

**Issue by sajadmartiny** [lingochamp/FileDownloader#252]
hi, my filedownloader.properties
http.lenient=false
process.non-separate=true
download.min-progress-step=65536
download.min-progress-time=2000
download.max-network-thread-count=1
and when create new task : 

   final BaseDownloadTask task = FileDownloader.getImpl().create(model.getUrl())
                        .setPath(model.getPath())
                        .addHeader("ISDMUser64", username)
                        .addHeader("ISDMHashPassword", password)
                        .setCallbackProgressTimes(300)
                        .setMinIntervalUpdateSpeed(400)
                        .setListener(taskDownloadListener);

 my file downloaded with one chunk but i need many chunks 
pls help me

**Comment by Jacksgong** [comment]
chunked resource works well in [SingleTaskTestActivity#chunked-files-download-test Demo](https://github.com/lingochamp/FileDownloader/blob/cb04c77cf5e4aba42bcdab1ab77966325d2d341c/demo/src/main/java/com/liulishuo/filedownloader/demo/SingleTaskTestActivity.java#L175), you can clone the demo project, and check it out.

If the transfer-encoding is chunked, FileDownloader will fetch the data from the input stream with the 4096byte space buffer again and again until no data left in the input stream.

**Comment by sajadmartiny** [comment]
i can download many chunk in same time? ex download 5 chunk file same time like internet download manager windows application , i can do it with your library?

so Thanks for answer

**Comment by Jacksgong** [comment]
You can download different resources simultaneously, and the number of it is open configure by: [filedownloader.properties#download.max-network-thread-count](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties) or [FileDownloader#setMaxNetworkThreadCount](https://github.com/lingochamp/FileDownloader/wiki/FileDownloader).

**Comment by sajadmartiny** [comment]
i means  wanna downloading one file from many part in same time ,ex downloading one file with 10 part in same time , i am testing your sample chunked file but in packet capture(android application for show packet) show me one request from your application but in LoaderDriod(download manager application) when select 10 part in packet capture show 10 request from application and download in same time

**Comment by Jacksgong** [comment]
Oh... Sorry, I misunderstood. For that, you can follow this issue: #102

In current latest version (0.3.4) isn't support such feature.
