### ISSUE TITLE
我想问下，对于一开始就下载错误的是不是不会缓存？

### ISSUE THREAD

**Issue by xanaduo** [lingochamp/FileDownloader#253]
我发现我有个文件一开始就失败了，但是并没有缓存文件。

**Comment by xanaduo** [comment]
还有，我如何获取这个缓存记录啊？比如我想做一个下载管理的界面，我要查询缓存的信息。

**Comment by Jacksgong** [comment]
一开始就失败，你看看`FileDownloadListener#error`的错误信息。

如果是自己想要做一个下载管理界面，建议自己建一张表，用于存储，这样也灵活。不要过于依赖filedwonloader 内部数据库 用于上层逻辑。 filedownloader数据库中的数据主要是用于维护断点续传以及非预期特殊情况(如进程挂了之类的)之后的断点续传。

**Comment by xanaduo** [comment]
我主要是拿来测试错误的情况。我开始获取状态来判断下载状态，看来还得自己存储了，好的。

**Comment by Jacksgong** [comment]
ok.
