### ISSUE TITLE
get background task 

### ISSUE THREAD

**Issue by mohamadrezash** [lingochamp/FileDownloader#254]
I want to make an app like googleplay.  how can I get downloading tasks in a separated activity?
thanx

**Comment by Jacksgong** [comment]
Sorry, FileDownloader doesn't provide any method to get downloading tasks.

#### There are several reasons:

1. The data in filedownloader isn't bound any View/Activity.
2. The data cached in filedownloader is used for maintaining the work of downloading and message flowing. The data store in the internal filedownloader database is used for ensuring any tasks can resume from the breakpoint in any valid situation.
3. The data cached in filedownloader will be changed for more stable in many upper users don't know unexpected situations.

> So, we don't commend the upper logic coupled with the filedownloader internal data.

#### Solution:

For upper layer, for more flexible and more stable, very recommend maintaining the downloading data by yourselves. Refs [TaskManagerDemo](https://github.com/lingochamp/FileDownloader/blob/cb04c77cf5e4aba42bcdab1ab77966325d2d341c/demo/src/main/java/com/liulishuo/filedownloader/demo/TasksManagerDemoActivity.java).

**Comment by mohamadrezash** [comment]
thanx alot for your useful guidance but this lib is very complicated and im beginer in java:)
would you explain more?
thanx again

**Comment by Jacksgong** [comment]
I thank [the wiki](https://github.com/lingochamp/FileDownloader/wiki) is helpful to you.

I'm writing the more readable java doc for this library and I'm perfecting the architecture of the visible layer(BaseDownloadTask、FileDownloadTask) for more readable too, you will find those until the next version(v1.0.0).

---

### Quick view:

#### Message:

- **Model**: MessageSnapshot.java、SmallMessageSnapshot.java、LargeMessageSnapshot.java
- **Factory**: MessageSnapshotTaker.java
- **ThreadPool**: MessageSnapshotThreadPool.java
- **Driver**: MessageSnapshotFlow.java
- **Upper transmit architecture**: FileDownloadMessageStation.java、FileDownloadMessenger.java

#### Data

- **Internal Data**: FileDownloadModel.java
- **Internal Database**: FileDownloadDBHelper.java、FileDownloadDBOpenHelper.java

#### Working Component

- **Event Manager**: FileDownloadMgr.java
- **Task-Runner**: FileDownloadRunnable.java
- **Network-Thread-Pool**: FileDownloadThreadPool.java
- **Running-Task**: FileDownloadList.java
- **Launcher-directly-thread-pool and controller**: FileDownloadTaskLaunder.java
- **Service-communicator**: IFileDownloadServiceProxy.java、FileDownloadServiceProxy.java、FileDownloadServiceSharedTransmit.java、FileDownloadServiceUIGuard.java
- **Working Task**: FileDownloadTask.java

#### Host Component

- **Host**: `FileDownloadService.SharedMainProcessService`、`FileDownloadService.SeparateProcessService`

#### Visible Layer

- **Atom Task**: BaseDownloadTask.java
- **Entrance**: FileDownloader.java
- **Listener**: FileDownloadListener.java、FileDownloadLargeFileListener.java、FileDownloadSampleListener.java、FileDownloadConnectListener.java、FileDownloadNotificationListener.java、`BaseDownloadTask.FinishListener`
- **Utils**: FileDownloadUtils.java、FileDownloadProperties.java
- **Global Monitor**: FileDownloadMonitor.java
- **Notification**: FileDownloadNotificationHelper.java、BaseNotificationItem.java
- **Exception**: FileDownloadGiveUpRetryException.java、FileDownloadHttpException.java、FileDownloadOutOfSpaceException.java
- **Status**: FileDownloadStatus.java
- **Header**: FileDownloadHeader.java
- **Helper**: FileDownloadQueueSet.java

**Comment by mohamadrezash** [comment]
i appriciate that :+1: 
whene thise version wille release?
i need thet deeply

**Comment by Jacksgong** [comment]
"Quick view"  describes the current version(0.3.4). And normally the v1.0.0 will be released in next week.

**Comment by mohamadrezash** [comment]
Impatiently waiting for that
thanx for your response.

**Comment by Jacksgong** [comment]
Pleasure.
