### ISSUE TITLE
How to get Progress of FileDownloadQueueSet?

### ISSUE THREAD

**Issue by chriswiesner** [lingochamp/FileDownloader#256]
i want to have an overall progress of a queueSet not the individual tasks.
is this possible?

**Comment by Jacksgong** [comment]
Sorry, FileDownloader doesn't implement such feature, but I think you can handle this by yourself with `BaseDownloadTask.FinishListener`.

**Comment by chriswiesner** [comment]
you mean that i increase the progress as a task of the queue finishes?
this would assume that every task has equal file size.

**Comment by Jacksgong** [comment]
Yes.

---

We can't get the total size of all files in 'queue-progress' because we get one task `content-length` until it got the response from the server in the queue.

**Comment by RowlandOti** [comment]
How can I get to the total no. of tasks that are currently running?
