### ISSUE TITLE
关于FileDownloadListener状态以及下载过程中删除temp文件问题

### ISSUE THREAD

**Issue by yubang322311** [lingochamp/FileDownloader#257]
你好 发现两个问题 麻烦帮忙分析下
1，点击下载文件后 (如果网络较卡的话) 到正式下载文件之间这段时间FileDownloadListener 的状态是获取不到的，这样就导致如果是listview或者Recycleview 下载列表在滑动的时候adapter去获取item的状态是未下载。
2，如果下载过程中去文件管理器中吧下载的.temp文件删了的话 回到应用中下载的界面还是会继续下载....

**Comment by Jacksgong** [comment]
点击下载 与 到真正开始下载（与网络有关系），之前有几个状态: pending、started，到connected、progress、completed才开始和网络有关系。更多的任务管理，或者是你谈到的case，可以参考: [TaskManagerDemoActivity](https://github.com/lingochamp/FileDownloader/blob/cb04c77cf5e4aba42bcdab1ab77966325d2d341c/demo/src/main/java/com/liulishuo/filedownloader/demo/TasksManagerDemoActivity.java)

关于下载过程中删除文件的问题，可以参考: #94

**Comment by yubang322311** [comment]
好的 谢谢！！。

**Comment by Jacksgong** [comment]
恩。
