### ISSUE TITLE
请问如何控制最大的下载任务数，貌似现在是3个。

### ISSUE THREAD

**Issue by xanaduo** [lingochamp/FileDownloader#260]
请问如何控制最大的下载任务数，貌似现在是3个。

**Comment by Jacksgong** [comment]
有以下两种方式:

1. [filedownloader.properties#download.max-network-thread-count](https://github.com/lingochamp/FileDownloader/blob/master/README-zh.md#filedownloaderproperties)
2. `FileDownloader#setMaxNetworkThreadCount`

**Comment by Jacksgong** [comment]
更多内容可以先翻阅翻阅 [wiki](https://github.com/lingochamp/FileDownloader/wiki).
