### ISSUE TITLE
【建议】关于Okhttp独立出来的问题

### ISSUE THREAD

**Issue by haodynasty** [lingochamp/FileDownloader#261]
将Okhttp深度结合固然不错，然是损失了很多可扩展性，是否可以考虑将Http连接请求单独独立出来，使用适配器模式，像Retrofit一样，可以使用任何一种Http请求连接方式，这样FileDownloader肯定会更加受欢迎，而且http连接可以独立升级

**Comment by Jacksgong** [comment]
这个很早就在计划内了，只是一直有更重要的迭代一直还没有做，这边预计1.0.0发布以后，1.1.0 或 1.2.0会带上的。

你关注这个Issue就好: #158
