### ISSUE TITLE
大文件下载问题

### ISSUE THREAD

**Issue by zaxcler** [lingochamp/FileDownloader#262]
我下载一个30多兆的apk文件，下到10几兆就报错， Unable to resolve host "www.XXX.com": No address associated with hostname, 是什么原因呢？
有时候还报其他的错比如：recvfrom failed: ECONNRESET (Connection reset by peer)

**Comment by Jacksgong** [comment]
> FileDownloader的下载和文件大小没有太大关系，除非文件超过1.99G那么需要使用`FileDownloadLargeFileListener`。

Unable to resolve host 是网络问题。

**Comment by zaxcler** [comment]
好像是我们后台服务器的原因  谢谢

**Comment by Jacksgong** [comment]
恩。
