### ISSUE TITLE
FileDownloadConnectListener监听中connected一直没有调？

### ISSUE THREAD

**Issue by a1506766443** [lingochamp/FileDownloader#263]
按照demo的监听方法写的，这个监听一直没有回调，也没有回调 disconnected，请教一下这个问题怎么避免？谢谢
日志：request get the status for the task[-1724412690] in the download service, but the download service isn't connected yet.

**Comment by a1506766443** [comment]
请问有没有eclipse用的jar包 ，能发一个给我吗？谢谢

**Comment by Jacksgong** [comment]
这个是由于服务没有连接上，但是如果你是调用了启动某个任务，会自动去连接与启动服务，并且等待连接上后，开始任务。

----

eclipse的jar包，你参照这里取最新版本: https://github.com/lingochamp/FileDownloader/issues/212#issuecomment-232240415

**Comment by a1506766443** [comment]
那这个怎么才能让它连接上服务呢，连接不上我调用了启动某个任务，FileDownloadSampleListener这个回调也不会调，等了很久也没有调 也没有进度更新，就启动任务时打印了上面的日志：request get the status for the task[-1724412690] in the download service, but the download service isn't connected yet.

请问，这个服务连接 不上和什么有关系呢？

**Comment by Jacksgong** [comment]
不好意思，不小心略过了这个Issue。

恩。这个日志，是你在调用 `FileDownloader#getStatus` 但是也是没有连接上服务。

连接服务: 启动某个任务的时候会自动连接服务并且等待连接上。也可以主动进行连接 `FileDownloader#bindService`，判断是否连接上: `FileDownloader#isServiceConnected`，监听连接的状态: `FileDownloader#addServiceConnectListener`
