### ISSUE TITLE
How to delete a running download file?

### ISSUE THREAD

**Issue by xiejinglan** [lingochamp/FileDownloader#264]
hi, i have a question .  how to delete a running task and the temp file ? has any API ?

**Comment by Jacksgong** [comment]
You can delete the temp file by yourself( `new File(FileDownloadUtils.getTempPath(targetPath)).delete()`).

 If the temp file is deleted:

- Its data in filedownloader database will be invalid and replace with the new one when you start the relate-task again.
- Its data in filedownloader database will be deleted automatically when FileDownloadService start in next time.

---

You also can delete its data in filedownloader database manually: ` FileDownloader#clear(downloadId:int, targetPath:String)`.
