### ISSUE TITLE
我想参与开源，为什么提交不了代码

### ISSUE THREAD

**Issue by caopeng000** [lingochamp/FileDownloader#266]
我想参与开源，为什么提交不了代码

**Comment by Jacksgong** [comment]
很感谢。

你fork了以后，切换到独立分支，按照 [规范](https://github.com/lingochamp/FileDownloader/wiki/Welcome-PR)进行编写代码，好了以后提Pull request即可。具体可以参照[Github官方文档](https://guides.github.com/activities/contributing-to-open-source/)
