### ISSUE TITLE
如何跑在ApplicationTestCase中

### ISSUE THREAD

**Issue by wangsuicheng** [lingochamp/FileDownloader#267]
我在测试用例中，已经传进去context了，但是Caused by: java.lang.IllegalStateException: Please invoke the FileDownloader#init in Application#onCreate first.还是会引起这个错误

**Comment by Jacksgong** [comment]
你可以参考下这个: https://github.com/lingochamp/FileDownloader/issues/201#issuecomment-235221055

也可以看下源码，在调用 `FileDownloader#init`的时候，就缓存了AppContext，报这个错误是因为，没有找到缓存的AppConext

**Comment by wangsuicheng** [comment]
谢谢，参考了你引用的issue，还想请问你，有没有什么方法在代码里设置，让这个下载运行在主进程，不用运行在独立进程？

**Comment by Jacksgong** [comment]
可以的，在filedownloader.properties中配置[process.non-separate=true](https://github.com/lingochamp/FileDownloader/blob/master/README-zh.md#filedownloaderproperties)

**Comment by Jacksgong** [comment]
wiki中也有: https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties

**Comment by wangsuicheng** [comment]
恩，看了，不过你这是通过配置文件去取得的，没有用代码set的方式吗

**Comment by Jacksgong** [comment]
没有，为了减少复杂度与提高稳定性。

**Comment by Jacksgong** [comment]
filedownloader.properties中只有最大网络线程数支持动态设定，不过这个的设定也需要在保证当前没有任务在运作，否则返回值（是否成功）也会是false。

**Comment by wangsuicheng** [comment]
那就有点尴尬了，我把你这个库是放到sdk lib里的，现在就是要在sdk的TestCase里测试，看这201commit里有个说法，这独立进程没法保证了context的引用

**Comment by Jacksgong** [comment]
不是很明白。无论是哪个进程都一样，如果你的应用，在所有进程启动的时候都会调用 Application#onCreate，只要在这里调用即可。

**Comment by Jacksgong** [comment]
还有如果你写的是androidTest，应该是可以指定任意的assets目录的。

**Comment by wangsuicheng** [comment]
怎么指定任意的assets目录，用什么代码实现吗？

**Comment by Jacksgong** [comment]
http://stackoverflow.com/questions/25683552/setting-a-custom-assets-directory-for-unit-testing-in-android-studio

**Comment by wangsuicheng** [comment]
谢谢哥们了哈~~

**Comment by Jacksgong** [comment]
恩。
