### ISSUE TITLE
如果本地存在文件，启动任务时还会去下载吗？还是直接就completed了？

### ISSUE THREAD

**Issue by wangsuicheng** [lingochamp/FileDownloader#269]
1.直接就调用监听的completed了吗？如果不是的话，我能不能在started这个方法里判断如果存在本地文件，然后就调用监听的completed，然后取消这个任务？下面的2问题
2.如何把这个任务从任务队列中移除掉？

**Comment by Jacksgong** [comment]
如果任务已经下载完成了，目前的最新版本(0.3.5):

1. 会直接回调completed。
2. 如果任务下载暂停了之类的，不希望下次开始的时候自动断点续传，可以通过`FileDownloader#clear(downloadID, targetFilePath)`进行清理。
3. 如果任务已经下载完成了，但是还是需要强制重新下载，可以通过`BaseDownload#setForceReDownload(true)`。

**Comment by wangsuicheng** [comment]
谢谢快速回复~~
我现在有个需求就是，如果本地存在文件，就不去下载了，除非我强制设置重新下载。

**Comment by Jacksgong** [comment]
恩。那默认就是这样。
