### ISSUE TITLE
请问，能不能对下载到指定路径里的文件重命名？

### ISSUE THREAD

**Issue by a1506766443** [lingochamp/FileDownloader#270]
我下载了几个**.apk的文件在我设置的路径里，进去路径看都是一串很长的名字，请问可以自己设置要下载的名字吗？然后也能根据自己设置的文件名字去查找是否已经存在该文件。
比如：我想下载一个游戏，我给这个游戏的apk命名为myplay1.2.apk.我安装时直接找这个名字的文件去安装。
谢谢！

**Comment by Jacksgong** [comment]
`BaseDownloadTask#setPath` 两个接口:

1. `BaseDownloadTask#setPath(filePath)` 指定的就是下载文件的绝对路径。包含存储目录与文件名(`filePath = directory/filename`)。
2. `BaseDownloadTask#setPath(path, true) `, 此时给的路径是目录(`path = directory/`)，这种情况下，FileDownloader会先检查response回来的头中是否根据http协议带回文件名，如果有就使用response带回的，如果没有就将url做md5作为文件名。

**Comment by a1506766443** [comment]
恩恩 ，谢谢！
