### ISSUE TITLE
What happens in Configuration change or after closing activity?

### ISSUE THREAD

**Issue by xoex** [lingochamp/FileDownloader#271]
Hi. Great library but lacks documentation.
What exactly happened when config changes happens? 
Or what happen when activity closed and how to resume or set listeners when activity will open later?
And are listeners run in ui thread?
Thank you

**Comment by Jacksgong** [comment]
Thanks!

1. FileDownloader doesn't bind any Activity.
2. Yes, as default, all methods in `FileDownloadListener` is invoked in UI Thread. (addition: FileDownloader handle methods in `FileDownloadListener` too frequent calls as default, Ref `FileDownloader#disableAvoidDropFrame()`.

----

More detail Ref [Wiki](https://github.com/lingochamp/FileDownloader/wiki).

**Comment by xoex** [comment]
Thanks for you reply,

but every download task have a listener, normally this listeners are in a activity/fragment, so there would be a reference to activity, And I don't see any way to change or remove listener.

```
    public FileDownloadQueueSet(FileDownloadListener target) {
        // TODO, support target is null
        if (target == null) {
            throw new IllegalArgumentException("create FileDownloadQueueSet must with valid target!");
        }
        this.target = target;
    }
```

**Comment by Jacksgong** [comment]
Please refs this comment: https://github.com/lingochamp/FileDownloader/issues/103#issuecomment-209173124
