### ISSUE TITLE
请问

### ISSUE THREAD

**Issue by jeyhan** [lingochamp/FileDownloader#272]
`if (container == null) {
            synchronized (eventId.intern()) {
                container = listenersMap.get(eventId);
                if (container == null) {
                    listenersMap.put(eventId, container = new LinkedList<>());
                }
            }
        }`        
DownloadEventPool.java的代码片段中，想问一下对eventId.intern()进行加锁的写法是否等价于对一个普通的final object加锁?

**Comment by Jacksgong** [comment]
是的。这里是对相同内容的String进行同步。

```
/**
 * Returns an interned string equal to this string. The VM maintains an internal set of
 * unique strings. All string literals found in loaded classes'
 * constant pools are automatically interned. Manually-interned strings are only weakly
 * referenced, so calling {@code intern} won't lead to unwanted retention.
 *
 * <p>Interning is typically used because it guarantees that for interned strings
 * {@code a} and {@code b}, {@code a.equals(b)} can be simplified to
 * {@code a == b}. (This is not true of non-interned strings.)
 *
 * <p>Many applications find it simpler and more convenient to use an explicit
 * {@link java.util.HashMap} to implement their own pools.
 */
public native String intern();
```

**Comment by jeyhan** [comment]
我也看明白了api描述，这段代码被converity报了issue，并被推荐使用final Object做锁
之所以不用的话是因为预留扩展吗，毕竟这种写法不多见
感谢！



hjw3156@126.com
 
发件人： Jacksgong
发送时间： 2016-08-17 18:02
收件人： lingochamp/FileDownloader
抄送： Jey Han; Author
主题： Re: [lingochamp/FileDownloader] 请问 (#272)
是的。这里是对相同内容的String进行同步。
/**
 * Returns an interned string equal to this string. The VM maintains an internal set of
 * unique strings. All string literals found in loaded classes'
 * constant pools are automatically interned. Manually-interned strings are only weakly
 * referenced, so calling {@code intern} won't lead to unwanted retention.
 *
 * <p>Interning is typically used because it guarantees that for interned strings
 * {@code a} and {@code b}, {@code a.equals(b)} can be simplified to
 * {@code a == b}. (This is not true of non-interned strings.)
 *
 * <p>Many applications find it simpler and more convenient to use an explicit
 * {@link java.util.HashMap} to implement their own pools.
 */
public native String intern();

**Comment by Jacksgong** [comment]
通常如果是成员变量作为锁的话，确实跑一些inspection的时候，会有这样的提示，目的就是防止由于变量发生改变导致同一个变量，但是由于指向不同的对象，导致锁作用在不同的对象上。

这里使用 `eventId.intern()` 就是保证了无论是哪个eventId，只要是同样的内容，就是对同一个对象进行加锁。这里并没有对什么作为拓展，就是完成: 对相同eventId的事件进行加锁。
