### ISSUE TITLE
下载https异常，请教要怎么做？谢谢

### ISSUE THREAD

**Issue by ThreeThree** [lingochamp/FileDownloader#275]
W/System.err: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
08-18 16:19:45.089 21407-21407/rj.com.myapps W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:410)
08-18 16:19:45.089 21407-21407/rj.com.myapps W/System.err:     at okhttp3.internal.io.RealConnection.connectTls(RealConnection.java:239)
08-18 16:19:45.089 21407-21407/rj.com.myapps W/System.err:     at okhttp3.internal.io.RealConnection.establishProtocol(RealConnection.java:196)
08-18 16:19:45.089 21407-21407/rj.com.myapps W/System.err:     at okhttp3.internal.io.RealConnection.buildConnection(RealConnection.java:171)
08-18 16:19:45.099 21407-21407/rj.com.myapps W/System.err:     at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
08-18 16:19:45.099 21407-21407/rj.com.myapps W/System.err:     at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:187)
08-18 16:19:45.099 21407-21407/rj.com.myapps W/System.err:     at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:123)
08-18 16:19:45.099 21407-21407/rj.com.myapps W/System.err:     at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:93)
08-18 16:19:45.099 21407-21407/rj.com.myapps W/System.err:     at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:296)
08-18 16:19:45.099 21407-21407/rj.com.myapps W/System.err:     at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
08-18 16:19:45.099 21407-21407/rj.com.myapps W/System.err:     at okhttp3.RealCall.getResponse(RealCall.java:243)
08-18 16:19:45.099 21407-21407/rj.com.myapps W/System.err:     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
08-18 16:19:45.099 21407-21407/rj.com.myapps W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
08-18 16:19:45.099 21407-21407/rj.com.myapps W/System.err:     at okhttp3.RealCall.execute(RealCall.java:57)
08-18 16:19:45.109 21407-21407/rj.com.myapps W/System.err:     at com.liulishuo.filedownloader.services.FileDownloadRunnable.loop(FileDownloadRunnable.java:250)
08-18 16:19:45.109 21407-21407/rj.com.myapps W/System.err:     at com.liulishuo.filedownloader.services.FileDownloadRunnable.run(FileDownloadRunnable.java:200)
08-18 16:19:45.109 21407-21407/rj.com.myapps W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
08-18 16:19:45.109 21407-21407/rj.com.myapps W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
08-18 16:19:45.109 21407-21407/rj.com.myapps W/System.err:     at java.lang.Thread.run(Thread.java:841)
08-18 16:19:45.109 21407-21407/rj.com.myapps W/System.err: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
08-18 16:19:45.109 21407-21407/rj.com.myapps W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:288)

**Comment by Jacksgong** [comment]
对于相关的https验证相关，目前可以使用okhttp进行定制，在`FileDownloader.getImpl().init(Context,FileDownloadHelper.OkHttpClientCustomMaker)` 传入 `FileDownloadHelper.OkHttpClientCustomMaker`，并且在 `FileDownloadHelper.OkHttpClientCustomMaker` 中可以通过 `OkHttpClient.Builder#	hostnameVerifier(HostnameVerifier)`进行自己想要的校验。

---

如果上层没有通过`OkHttpClientCusomMaker`进行定制，目前FileDownloader使用的是Okhttp默认的校验: `OkHostnameVerifier.INSTANCE.verify(host, session)`。

**Comment by ThreeThree** [comment]
谢谢大牛〜，问题解决了！

**Comment by Jacksgong** [comment]
恩。
