### ISSUE TITLE
init方法放在主线程太耗时,放在子线程就会init失败,能否优化其耗时?

### ISSUE THREAD

**Issue by hss01248** [lingochamp/FileDownloader#277]
这是放在子线程里初始化时报的: Caused by: java.lang.IllegalStateException: Please invoke the FileDownloader#init in Application#onCreate first.

**Comment by Jacksgong** [comment]
init的主要耗时是在加载 assets中的 `filedownloader.properties`文件。

我不清楚你所说的耗时的标准。我一直十分关注这块的耗时的，我在Nexus5中的测试结果是耗时是在: 10ms ~25ms之间不等。

**Comment by Jacksgong** [comment]
我看了下，我先优化下让这边的UI进程的初始化耗时再降下来。

**Comment by Jacksgong** [comment]
不知道你这边测出来的耗时是多少呢。你认为多少的耗时是可以接受的。

**Comment by hss01248** [comment]
@Jacksgong  sorry,应该是我这里multidex的耗时,刚刚测了,FileDownloader#init 用时4-30ms之间,可以接受

**Comment by Jacksgong** [comment]
好的。我这边会持续关注这块的。谢谢你的提出。
