### ISSUE TITLE
文件保存目录如何设置？

### ISSUE THREAD

**Issue by DesignQu** [lingochamp/FileDownloader#278]

**Comment by Jacksgong** [comment]
Ref: https://github.com/lingochamp/FileDownloader/issues/244#issuecomment-237160759

**Comment by DesignQu** [comment]
请问这是一个任务一个保存路径吗？在外层有一次修改默认路径的吗？

**Comment by Jacksgong** [comment]
恩。

可以修改默认路径: `FileDownloadUtils#setDefaultSaveRootPath`。

更多的可以参考[README](https://github.com/lingochamp/FileDownloader/blob/master/CHANGELOG-ZH.md)。

**Comment by DesignQu** [comment]
谢谢
