### ISSUE TITLE
连接上需要登录的WIFI后，下载后文件不正确

### ISSUE THREAD

**Issue by weikano** [lingochamp/FileDownloader#279]
有些WIFI在连接上后，需要在网页登录后才能使用。这种情况下下载链接经过重定向会指向登录页面，点击下载后，文件并不是原下载链接指向的文件。

请问这种情况有方法绕过吗？

**Comment by Jacksgong** [comment]
没有办法绕过，除非你有登录相关信息，添加到 header中。

重定向是服务端返回的，从原地址是获取不到任何的数据的，只有返回 [200,300)，我们才有可能获取到输入流数据。

**Comment by weikano** [comment]
如果我事先知道对应链接的Content-type，是否可以在response根据Content-type是否匹配来判断是否成功或者失败

**Comment by Jacksgong** [comment]
如果是成功了，也只是服务端的漏洞而已。后端如果需要做校验，就和这些无关。你说的是取不取输入流，这个确实是本地的事，但是给不给是服务端的事，走校验无论你要怎样不给客户端就取不到数据。
