### ISSUE TITLE
retry时支持替换url

### ISSUE THREAD

**Issue by pop1030123** [lingochamp/FileDownloader#280]
由于资源url有备份的服务器，所以一个Url下载失败的时候，需要替换另外一个url 进行下载。不知道当前是否支持？

**Comment by Jacksgong** [comment]
1. 不支持retry的时候替换url，这个上层很容易实现的，在回调 `error`的时候，创建一个使用另外Url的任务启动即可。
2. 如果path的文件存在，默认情况，会直接返回 `completed`。
