### ISSUE TITLE
这个下载引擎可以支持仅在wifi环境下下载吗？因为通过应用内自己控制 在网络环境切换的时候还是会消耗掉几十兆流量

### ISSUE THREAD

**Issue by logan62334** [lingochamp/FileDownloader#281]
这个下载引擎可以支持仅在wifi环境下下载吗？
因为通过应用内自己控制 在网络环境切换的时候还是会消耗掉几十兆流量

**Comment by Jacksgong** [comment]
内部也会有一点误差，但是应该不会这么大，会考虑在1.1.0版本中支持的。

**Comment by logan62334** [comment]
@Jacksgong 谢谢，测试team报的这个问题，他们的手机流量每天设置的上限是30mb，说是下载的过程中切网直接消耗完了。
