### ISSUE TITLE
[Small probability event]Can bring on an illegalStateException when there are multiple single tasks and queues with the same listener object, and start them in the different thread

### ISSUE THREAD

**Issue by pop1030123** [lingochamp/FileDownloader#282]
异常如下：
java.lang.IllegalStateException
This task is running 213853733, if you want to start the same task, please create a new one by FileDownloader.create
com.liulishuo.filedownloader.BaseDownloadTask.int start()(BaseDownloadTask.java:469)

same task是如何判断的？我可以在start之前判断一下。

**Comment by Jacksgong** [comment]
> 对于这类问题，可以考虑一个替代方案: 执行任务直接创建一个新的Task即可。

1. 如果该任务对象有使用过 或者 正在运行 `BaseDownloadTask#isUsing()` 返回 `true`。
2. 如果该任务对象正在运行 `BaseDownloadTask#isRunning()` 返回 `true`，这种情况下 不能进行 `BaseDownloadTask#reuse()`。

对于一个启动过的应用，只有在 `BaseDownloadTask#isRunning() == false` 的情况下才能进行 `BaseDownloadTask#reuse()`，在reuse以后才能重新调用其`start()`。

**Comment by pop1030123** [comment]
现在有一种情况是FileDownloadQueueSet里面的某个task和其它某个task有冲突，这个在FileDownloadQueueSet里面应该无法判断task是否isUsing .

**Comment by Jacksgong** [comment]
isUsing是针对 对象的。不是针对不同的任务的。

**Comment by pop1030123** [comment]
那这样的话，我现在代码里面没有使用reuse相关的接口，我现在下载都是create一个task ,或者创建一个FileDownloadQueueSet来下载，理论上来讲，都是创建不同的对象，为什么还会出现上面的异常呢？

**Comment by pop1030123** [comment]
![image](https://cloud.githubusercontent.com/assets/5387719/17842192/bd801a8c-6852-11e6-9704-9c3919ab3e5a.png)

**Comment by pop1030123** [comment]
![image](https://cloud.githubusercontent.com/assets/5387719/17842228/13c3c3bc-6853-11e6-9db0-63be46d593d8.png)

**Comment by pop1030123** [comment]
上面我现在使用的2种方式

**Comment by Jacksgong** [comment]
我不是很了解你遇到问题的情景。你可以看下代码 `DownloadTaskHunter#mIsUsing` 只有在当前对象进去启动队列的时候才会设置为`true`，不会因为有相同任务或者是其他情况设置为`true`的。

**Comment by pop1030123** [comment]
没有DownloadTaskHunter.java这个类吧？

**Comment by Jacksgong** [comment]
目前最新版本的(v1.0.0)。

**Comment by pop1030123** [comment]
java.lang.IllegalStateException
This task is running -856186866, if you want to start the same task, please create a new one by FileDownloader.create
com.liulishuo.filedownloader.BaseDownloadTask.int start()(BaseDownloadTask.java:469)
##_parent_##1##_parent_##
##_child_##                                              int _getStatusFromServer(int)##_child_##
com.liulishuo.filedownloader.FileDownloader$SerialHandlerCallback.boolean handleMessage(android.os.Message)(FileDownloader.java:703)
android.os.Handler.dispatchMessage(Handler.java:106)
android.os.Looper.loop(Looper.java:193)
android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by pop1030123** [comment]
这是从bugly上面提取的LOG ，看着是从FileDownloader.java的代码触发的：
`final BaseDownloadTask stackTopTask = this.list.get(runningIndex);
                synchronized (pauseLock) {
                    if (!FileDownloadList.getImpl().contains(stackTopTask)) {
                        // pause?
                        if (FileDownloadLog.NEED_LOG) {
                            FileDownloadLog.d(SerialHandlerCallback.class, "direct go next by not contains %s %d", stackTopTask, msg.arg1);
                        }
                        goNext(msg.arg1 + 1);
                        return true;
                    }
                }
                stackTopTask
                        .addFinishListener(serialFinishListener.setNextIndex(runningIndex + 1))
                        .start();`

**Comment by pop1030123** [comment]
现在感觉是FileDownloadQueueSet串行执行有问题。

**Comment by pop1030123** [comment]
创建FileDownloadQueueSet时候，参数传入的是一个静态变量，不知道会不会有影响？代码如下：
FileDownloadQueueSet downloadQueueSet = new FileDownloadQueueSet(sTieDownloadListener);

**Comment by pop1030123** [comment]
能否继承BaseDownloadTask ，自定义downloadTask ?

**Comment by pop1030123** [comment]
已经升级到1.0.0 ，改了源码。

**Comment by Jacksgong** [comment]
还有什么问题吗？

**Comment by pop1030123** [comment]
DownloadTask.java的start方法我改了一下，如下 ，抛异常的代码删除了，会不会有什么问题？

`

    @Override
    public int start() {
        if (isUsing()) {
            if (isRunning()) {
                FileDownloadLog.w(this ,FileDownloadUtils.formatString("This task is running %d, if you" +
                        " want to start the same task, please create a new one by" +
                        " FileDownloader.create", getId())) ;
            } else {
                FileDownloadLog.w(this,"This task is dirty to restart, If you want to " +
                        "reuse this task, please invoke #reuse method manually and retry to " +
                        "restart again.") ;
            }
            return -1 ;
        }
        if (mAttachKey == 0) {
            mAttachKey = mListener.hashCode();
        }
        mHunter.intoLaunchPool();
        return getId();
    }

`

**Comment by Jacksgong** [comment]
我建议你直接跑跑 demo project试试，而不是去将 抛异常的代码删除。

我不是很明白为什么你正常的使用会抛 这个异常，这个我都有测试过是没有问题的。你认真检查下，应该是哪里你重复启动的相同的任务对象。

如果 `isRunning()` 是 `true` 你重新start了，必定会有各种奇怪的问题，因为这个任务对象还在任务流中流转着。

如果是`isUsing()` 是`true`，你重新start了，也会导致各种奇怪的问题，原因是里面的各种 `status`、`sofarBytes`、`Etag`等等，都是之前运行过的该任务对象中依然存在的数据。

**Comment by Jacksgong** [comment]
如果是你正常的使用，始终存在该问题。可否将你的出现问题的代码，写成一个简单的必现问题的小项目，然后发给我igzhenjie@gmail.com，我给你看看?

**Comment by Jacksgong** [comment]
或者我加你QQ，快速将你的问题解决了。

**Comment by Jacksgong** [comment]
对了，你可以断点下 抛异常的那里，看看同一个对象在什么时候，多次调用了 `start()`，因为只有同一个对象多次调用 `start()`才会抛这个异常的。

**Comment by pop1030123** [comment]
我QQ是77276575

**Comment by Jacksgong** [comment]
最终结果如何，我们都在ISSUE中总结跟进，保证该ISSUE的有效性。

**Comment by Jacksgong** [comment]
如果是只有单任务使用同一个listener是没有问题的。
如果是只有队列任务使用同一个listener也是没有问题的。
如果启动任务都是在相同的线程也是没有问题的。

但是，如果是单任务与队列任务启动是在不同线程，并且他们使用相同的listener对象。那么就有小概率引起这个异常，

#### 目前v1.0.0快速的解决方法是 ：

在使用这个listener的所有单任务与队列任务都加上锁，保证他们的 start，都是互斥即可。

#### 这个问题会在1.0.1修复。

**Comment by Jacksgong** [comment]
This problem occurs when there are multiple single tasks and queues with the same listener object, and start them in different thread simultaneously.

#### For v1.0.0 the quick way to fix this problem:

use `synchronized` ensure they don't invoke `start()` method simultaneously.

#### This problem will be fixed in 1.0.1.
