### ISSUE TITLE
下载文件有大小限定吗?还是需要服务器做什么支持?

### ISSUE THREAD

**Issue by rehan91** [lingochamp/FileDownloader#286]
我在下载App的时候,出现这种问题:当文件大小在6M以内的时候可以正常下载,也可以监听进度,
但是在文件大小大于6M的时候,出现了没有文件进度,文件没有下载的情况.
另外,服务器是PHP搭建的.

**Comment by Jacksgong** [comment]
文件大小没有限制，如果遇到问题，留意下`error`回调。
