### ISSUE TITLE
状态为FileDownloadStatus.blockComplete时回调的一个bug

### ISSUE THREAD

**Issue by viphsx123** [lingochamp/FileDownloader#287]
``` java
public boolean callback(FileDownloadMessage message) {
    final MessageSnapshot snapShot = message.getSnapshot();

    switch (snapShot.getStatus()) {
        case FileDownloadStatus.pending:
            pending(message.getTask(),
                    snapShot.getSmallSofarBytes(),
                    snapShot.getSmallTotalBytes());
            break;
        case FileDownloadStatus.started:
            started(message.getTask());
            break;
        case FileDownloadStatus.connected:
            connected(message.getTask(),
                    snapShot.getEtag(),
                    snapShot.isResuming(),
                    message.getTask().getSmallFileSoFarBytes(),
                    snapShot.getSmallTotalBytes());
            break;
        case FileDownloadStatus.progress:
            progress(message.getTask(),
                    snapShot.getSmallSofarBytes(),
                    message.getTask().getSmallFileTotalBytes());
            break;
        case FileDownloadStatus.retry:
            retry(message.getTask(),
                    snapShot.getThrowable(),
                    snapShot.getRetryingTimes(),
                    snapShot.getSmallSofarBytes());
            break;
        case FileDownloadStatus.blockComplete:
            blockComplete(message.getTask());
            break;
        case FileDownloadStatus.completed:
            completed(message.getTask());
            break;
        case FileDownloadStatus.error:
            error(message.getTask(),
                    snapShot.getThrowable());
            break;
        case FileDownloadStatus.paused:
            paused(message.getTask(),
                    snapShot.getSmallSofarBytes(),
                    snapShot.getSmallTotalBytes());
            break;
        case FileDownloadStatus.warn:
            // already same url & path in pending/running list
            warn(message.getTask());
            break;
    }

    return false;
}
```

以上代码出自com.liulishuo.filedownloader.FileDownloadListener

在switch中snapShot.getStatus()的值为FileDownloadStatus.blockComplete ，

但是此时获取到的message.getTask()中的status却为-3，即FileDownloadStatus.completed，

会导致在实际使用中，如果按照task的status字段判断状态，则会回调completed的方法，如果在该方法中更新ui即会报错，望确认。

**Comment by Jacksgong** [comment]
这并不是bug，在内部流中，其实是不存在 `blockComplete` 状态的。在回调 `blockComplete` 的时候，内部其实已经下载完成了，已经是 `completed`的状态。

而 `blockComplete` 的回调只是为了方便上层用户在下载完成之后 与 最终结束之前 插入一个 异步的线程 block 住 `completed` 的回调。 

一般建议用于对下载完成的文件进行解压缩、或者解码之类的操作。

**Comment by viphsx123** [comment]
但是这样一来就会导致completed的回调不在主线程了啊

**Comment by Jacksgong** [comment]
不会的，内部已经处理了相关问题。

代码可以参看: `FileDownloadMessenger` 、`FileDownloadMessageStation`。
验证: 可以参看demo project中众多的案例都是在 `completed` 中更新UI布局。

**Comment by viphsx123** [comment]
我是按照[103](https://github.com/lingochamp/FileDownloader/issues/103#issuecomment-209173124)来写的自定义的downloadmanager，然后也是就一个update方法，然后在update的实现中
按照task.getStatus()来判断各个状态，然后写具体的业务逻辑，实际上task.getStatus()获取的completed，有可能是内部为blockComplete时调用的，可能是写法的问题吧

**Comment by Jacksgong** [comment]
感谢你的细心。https://github.com/lingochamp/FileDownloader/issues/103#issuecomment-209173124 这里的写发确实导致了 `blockComplete` 在这里产生了这样的问题。这里确实需要对 `blockComplete`进行特殊回调处理。

我已经对这里的案例做了修正了，多谢你的指出。~

**Comment by viphsx123** [comment]
不客气，感谢你的回复和认真对待

**Comment by viphsx123** [comment]
@Jacksgong 
不过我感觉103的改法好像还是有点问题，
public interface DownloadStatusUpdater{
        void blockComplete(BaseDownloadTask task);
        void update(BaseDownloadTask task);
    }
因为问题不是发生在blockComplete，而是在我实现update方法时，根据task获取的状态为completed时，此时update的回调有可能还是在非主线程中，因为有可能内部走的是blockComplete的逻辑。

我改成如下写法，我这边没问题了。

public interface DownloadStatusUpdater {
        /**
         * Enqueue, and pending, waiting for {@link #started(BaseDownloadTask)}.
         *
         * @param task       The task
         * @param soFarBytes Already downloaded bytes stored in the db
         * @param totalBytes Total bytes stored in the db
         */
        void pending(final BaseDownloadTask task, final int soFarBytes,
                     final int totalBytes);

        /**
         * Finish pending, and start the download runnable.
         *
         * @param task Current task.
         */
        void started(final BaseDownloadTask task);

        /**
         * Already connected to the server, and received the Http-response.
         *
         * @param task       The task
         * @param etag       ETag
         * @param isContinue Is resume from breakpoint
         * @param soFarBytes Number of bytes download so far
         * @param totalBytes Total size of the download in bytes
         */
        void connected(final BaseDownloadTask task, final String etag,
                       final boolean isContinue, final int soFarBytes, final int totalBytes);

        /**
         * Fetching datum from network and Writing to the local disk.
         *
         * @param task       The task
         * @param soFarBytes Number of bytes download so far
         * @param totalBytes Total size of the download in bytes
         */
        void progress(final BaseDownloadTask task, final int soFarBytes,
                      final int totalBytes);

        /**
         * Achieve complete ceremony.
         * <p/>
         * Complete downloading.
         *
         * @param task The task
         */
        void completed(final BaseDownloadTask task);

        /**
         * Task is paused, the vast majority of cases is invoking the {@link BaseDownloadTask#pause()}
         * manually.
         *
         * @param task       The task
         * @param soFarBytes Number of bytes download so far
         * @param totalBytes Total size of the download in bytes
         */
        void paused(final BaseDownloadTask task, final int soFarBytes,
                    final int totalBytes);

        /**
         * Occur a exception, but don't has any chance to retry.
         *
         * @param task The task
         * @param e    Any throwable on download pipeline
         * @see com.liulishuo.filedownloader.exception.FileDownloadHttpException
         * @see com.liulishuo.filedownloader.exception.FileDownloadGiveUpRetryException
         * @see com.liulishuo.filedownloader.exception.FileDownloadOutOfSpaceException
         */
        void error(final BaseDownloadTask task, final Throwable e);

    }

**Comment by Jacksgong** [comment]
如果是真的`completed`回调在非主线程，就是库存在bug，不过我在对库进行高压测试的时候并没有遇到类似的问题。

我相信之前在 `update`中在非主线程，肯定是 `blockComplete` 回调回来的，因为 状态同为 `completed`。

---

麻烦你再试试：如果你用我修改后的接口，默认情况下遇到`update`在非主线程，直接提bug，给我最后能够输出栈信息给我定位下问题。

**Comment by Jacksgong** [comment]
我相信你也可以通过代码看到默认情况下`FileDownloadMessageStation#requestEnqueue`，只有在 `FileDownloadMessenger#isBlockingCompleted`的情况下才会将回调抛到 `blockCompletedPool` 线程池中去执行。

而 `FileDownloadMessenger#isBlockingCompleted` 是 队头为 `blockCompleted` 才为 `true`，而队列是FIFO的，而每次`handover` 都会有消息出队，逻辑层面应该是没有问题的。

**Comment by viphsx123** [comment]
嗯，我想了一下现在103的写法应该没问题了，因为blockCompleted时，走了void blockComplete(BaseDownloadTask task)的逻辑，不再走update了，谢谢回复

**Comment by Jacksgong** [comment]
恩。好的。
