### ISSUE TITLE
stable downloading

### ISSUE THREAD

**Issue by mohamadrezash** [lingochamp/FileDownloader#288]
hey mr jak
First : how i can control downloading task from servic ? my point is start , pause and resume from servic and get donloading task from activity
Second : also i whant to get all downloading task in a diffrent activity how i can?
please help  
thanx alot

**Comment by Jacksgong** [comment]
1. start、pause、resume, Please Ref the demo project or [wiki](https://github.com/lingochamp/FileDownloader/wiki).
2. You can manage you tasks by yourself, Ref: https://github.com/lingochamp/FileDownloader/issues/103#issuecomment-209173124 , or Ref the [TaskManageDemo](https://github.com/lingochamp/FileDownloader/blob/cb04c77cf5e4aba42bcdab1ab77966325d2d341c/demo/src/main/java/com/liulishuo/filedownloader/demo/TasksManagerDemoActivity.java).

**Comment by Jacksgong** [comment]
@mohamadrezash any problem, this issue will be reopened.

**Comment by mohamadrezash** [comment]
i try to made stable download by this downloader but i have problem yet :(

**Comment by Jacksgong** [comment]
OK... What problem?

**Comment by Jacksgong** [comment]
> You can test the demo project first. I test hundreds of tasks or event thousands of tasks in the demo project, to make sure how it work stabled.

**Comment by mohamadrezash** [comment]
my first problem is how manage download in service? its mean i want to create service that implement  FileDownloadListener but i dont know how handle it?

**Comment by mohamadrezash** [comment]
i know mr jack evry thing in demo project is prefect It is possible i cant to undrestand because im beginer

**Comment by mohamadrezash** [comment]
com.liulishuo.filedownloader.services could helpfull?

**Comment by Jacksgong** [comment]
Yes, you can manage download in service feel free, just manage listeners in service (https://github.com/lingochamp/FileDownloader/issues/103#issuecomment-209173124) and wrap the downloading function method in your service.

**Comment by Jacksgong** [comment]
> [Wiki](https://github.com/lingochamp/FileDownloader/wiki).

No, Classes in `com.liulishuo.filedownloader.services` the package is for the internal mechanism to  execute tasks in the FileDownloadService.

**Comment by mohamadrezash** [comment]
i try again:)
if you put example of download from service in your demo everything Was completed 
this downloader is amazing 
thanx for this

**Comment by Jacksgong** [comment]
Thanks.

But the FileDownloader doesn't bound any component(Such as Activity) of the upper layer. You can simply replace any Activity in the demo project with the Service, and display the downloading information in another way.

If you find any problem when you downloading task in Service, please let me know, I will help you.
