### ISSUE TITLE
一个关于listener的问题

### ISSUE THREAD

**Issue by junkaizhou** [lingochamp/FileDownloader#289]
是不是下载文件可能大于1.99GB时所有的listener用largeListener，还是说1.99GB以下的用普通listener,1.99GB以上的用largeListener？

**Comment by Jacksgong** [comment]
是 1.99GB以下的用普通listener,1.99GB以上的用largeListener。 这里的主要原因是越界的问题，有因为 普通的listener中 sofarBytes 与 totalBytes 都是整型，无法表示 1.99G以上。而largeListener中都是 长整型(long)。
