### ISSUE TITLE
FileDownloadGiveUpRetryException

### ISSUE THREAD

**Issue by rehan91** [lingochamp/FileDownloader#290]
①这个异常在请求头的返回形式是怎么样的时候会返回这个异常?
②添加 http.lenient=true后,进行下载,文件大小为8M多,但是每次都是下载到2574/8942628这个进度就停止了,并且走了onComplete方法;
③请求的过程中,有看到这两个字段:
Content-Encoding: gzip
Transfer-Encoding: chunked

如果方便的话,希望可以加一下我QQ(321741341),我想更好的说明一下情况,谢谢!

**Comment by Jacksgong** [comment]
#### 1. 

> Ref: https://github.com/lingochamp/FileDownloader/blob/80471aa6f43109767efb7364e5061080d14bbee2/library/src/main/java/com/liulishuo/filedownloader/exception/FileDownloadGiveUpRetryException.java#L21

 就是在 response头中没有 `content-length`，并且reponse中其 `Transfer-Encoding` 不为 `Chunked`，这个是不符合http标准的，这是一个服务端的的错误，并且重试也无济于事。


#### 2.

 添加 `http.lenient=true` 以后，只是将 1中的这类情况，直接当做流媒体下载，也就是说不知道这个文件多大，只能不断的从输入流中取数据，直到取到取完了就回调 `completed`。但是如果原本的response是符合http标注的这个标签就不会有任何的影响。

> 2574/8942628就停止走了。

1. 如果是这个情况是不可能回调 completed的。

> 参考代码: https://github.com/lingochamp/FileDownloader/blob/80471aa6f43109767efb7364e5061080d14bbee2/library/src/main/java/com/liulishuo/filedownloader/services/FileDownloadRunnable.java#L448

如果在输入流中的数据都取完，发现其已经完成的大小不等于 response返回的 content-length，也就是 这里的 8942628，那么就会直接抛出异常。

#### 3. 

`Transfer-Encoding: chunked` 说明这是一个流媒体，在下载全程我们是不知道这个流媒体的大小的，因此全程返回的totalBytes都是-1。

**Comment by rehan91** [comment]
我发现,Accept-Encoding: gzip,始终为gzip,设置了identity还是请求的是gzip,使用其他的下载框架可以实现identity下载,感覺有点懵
