### ISSUE TITLE
下载失败/数据不完整

### ISSUE THREAD

**Issue by rehan91** [lingochamp/FileDownloader#291]
①:没有addHeader("Accept-Encoding", "identity"),并且没有忽略的前提下,也就是Gzip传输,会报错:FileDownloadGiveUpRetryException: can't know the size of the download file, and its Transfer-Encoding is not Chunked either.并且文件没有下载;
②:在①的前提,做了这一步,add http.lenient=true to the filedownloader.properties,不报错,文件下载了,但是只下载了2kb的数据,数据不完整;
③有addHeader("Accept-Encoding", "identity"),不使用配置和使用配置都不报错,但是结果跟②一样,只下载2kb数据;

**Comment by rehan91** [comment]
另外,response header有返回length:Content-Length: 8942628,但是还是说,不知道文件的长度.......

**Comment by rehan91** [comment]
发现一个奇怪的现象,fiddler选择Streaming mode后可以下载了,但是wifi断开后再链接,不能继续下载,也就是不能断点了,退出后重新进入也不能继续下载,作者有试过这个现象吗?

**Comment by Jacksgong** [comment]
> 建议你直接clone demo project 下来跑下，或者先看看相关的源码。

#### 1. 

> :FileDownloadGiveUpRetryException: can't know the size of the download file, and its Transfer-Encoding is not Chunked either

无论你的请求头是什么，服务端返回的response不符合http的规范导致的。response header中不包含 content-length，`Transfer-Encoding`不是Chunked (也就是不是流媒体)。

如果需要忽略这样的问题，直接当做流媒体来下载，参照[这里的http.lenient](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)的设置。

#### 2. 

添加了 add http.lenient=true to the filedownloader.properties，以后，由于1情况的资源response header中不包含content-length，本地并不知道完整文件的大小是多大，而是直接直接从输入流中取数据，直到取完。如果你发现数据不完整，请咨询你们的后端同学。

#### 3.

无论是什么形式，返回回来的response，如果包含 content-length，取完输入流的数据发现与 content-length 不符，会直接抛对应的异常；如果返回的response不包含content-length，会直接以输入流的结束作为结尾，本地并不知道该文件是否完整。

这个很明显是服务端的坑。

---

如果response header中返回中有 Content-Lengt，目前FileDownloader是的http库是基于okhttp，而获取content-length是通过: [okhttp3.ResponseBody#contentLength](https://github.com/lingochamp/FileDownloader/blob/80471aa6f43109767efb7364e5061080d14bbee2/library/src/main/java/com/liulishuo/filedownloader/services/FileDownloadRunnable.java#L266) 进行获取。 建议通过DEBUG FileDownloadRunnable进行定位问题。

如果觉得实在是存在，并且okhttp3这边取不到可以提供下URL，我这边给你看看具体问题所在。

---

目前流媒体是不支持断点续传的。这里主要考虑到流媒体的初衷，就是动态的将数据流塞给客户端。

**Comment by rehan91** [comment]
感谢回答!我们的目的是下载一个apk文件,服务端的url是一个html文件,但是并不是http://xxxxx.com/abc.apk形式,而是http://xxx.com/abc.html,在这个html文件中,包含一个输出流,把apk文件进行输出,然后客户端进行接收,不知道服务端这么做算不算流媒体,如果是的话应该是不能断点了,我也一直认为应该是服务端有问题...但服务器好像也觉得自己没错,哎

**Comment by Jacksgong** [comment]
。。。。 无论你是什么形式。即便是html，也是没有问题的，哪怕是302我们都有处理。

我相信我写的这些答复你和后端都看得懂，他们觉得他们没有问题是引擎的问题，你可以改用系统DownloadManager去尝试下载看看。

---

你问后端同学，那调试下看看，如果说后端没有问题，你问他们为什么我们从输入流中只能取出2kb的数据而非完整的数据，是否要带什么请求头之类的。

2kb有点像是一个网页，FileDownloader是有自动处理302 redirection的，所以是否是服务端没有返回redirection，还有你们也可以抓包看看服务端返回的是什么，没准是一个500的页面。

**Comment by rehan91** [comment]
content-length和transfer_encoding:trunked都有,但是还是报错,说不知道大小和不是chunked协议,有点懵了.这跟服务器有关吗?服务器是nginx

**Comment by Jacksgong** [comment]
**错误描述** : 这两个参数通常是互斥的。 transfer encoding 是chunked，就没有content-length，有content-length 就不是 chunked，为啥都有？

#### 建议定位问题方法:

1. 你可以直接在FileDownloadRunnable中debug看看，取到的是什么
2. 你将你的抓包结果贴给我看看。
3. 直接将连接发给我，我给你看看。

**Comment by rehan91** [comment]
对,是互斥的,我的意思是当不是trunked的时候,也获取不到content_length;当设置为trunked的时候,又说不是trunked模式.现在就这个问题比较难搞.我先调一下FileDownloadRunnable试试

**Comment by Jacksgong** [comment]
你拼写错了。是chunked，不是trunked

**Comment by Jacksgong** [comment]
Ref: https://en.wikipedia.org/wiki/Chunked_transfer_encoding

**Comment by rehan91** [comment]
嗯,服务器这个:Transfer-Encoding: chunked,但是还是报错

**Comment by Jacksgong** [comment]
> 这些case我项目中的demo project中都已经覆盖，我在demo project中并为发现有什么问题。

你先按照上面我给你的三个方法的其中一个方法定位下问题吧。

**Comment by rehan91** [comment]
FileDownloadRunnable中好像不能debug吧

**Comment by Jacksgong** [comment]
FileDownloadRunnable默认情况下是运行在下载进程，你需要debug对应的进程才行。比如你的主进程的进程名是: com.aaa.bbb，那么下载默认所在进程是: com.aaa.bbb:filedownloader。

> P.S: 你可以通过配置 [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties) 让FileDownloadRunnable运行在主进程，这样就只需要对主进程进行Debug即可。

**Comment by Jacksgong** [comment]
@rehan91 该问题，处理的怎么样了？

**Comment by rehan91** [comment]
现在是这个情况的log:
I/TAG: content_length--------==-1
I/TAG: progress: ----soFarBytes/totalBytes---1582/2571
I/TAG: completed: -------download completed!!!
content_length为-1,是chunked模式,progress只走了一次,complete也走了,但是文件只有2k多

**Comment by Jacksgong** [comment]
这边对于FileDownloader来说，这样来看并没有问题的。因为流媒体，取完输入流了就只有2k,对于客户端来说就是下载完成了的。

**Comment by Jacksgong** [comment]
> content_length为-1,是chunked模式,progress只走了一次,complete也走了,但是文件只有2k多。

根据这个表述，这个问题并非FileDownloader的问题，流媒体测试可以参照 demo project中的单任务测试中的流媒体测试，如果是流媒体，FileDownloader是不知道文件大小的，取完以后就会直接回调completed，并且progress回调次数也是和每次给回的流大小有关系的，输入流中的数据太小，以及每次从流中取出的数据太大(默认buffer大小是4096byte)，都会影响progress的次数。

如果有任何的问题没有解决该issue再重新打开。

----

建议clone demo project然后跑跑看看。

**Comment by asdf19910719** [comment]
...和题主的一样,我也遇到了下载的文件只有2kb的情况,不过只有少部分用户是这样的,看了这个问题的解答好几遍,能确定就是在我的手机上时是返回的header是有Content-Length而 没有Transfer-Encoding的,但是有Content-Length的情况下为什么会下载不完整就不清楚了...
