### ISSUE TITLE
集成app后安装错误，请问是什么原因，报错信息如下

### ISSUE THREAD

**Issue by itsmallsun** [lingochamp/FileDownloader#293]
WARNING: linker: could not load library "libsigchain.so" from LD_PRELOAD for "/system/bin/sh"; caused by "libsigchain.so" is 32-bit instead of 64-bit CANNOT LINK EXECUTABLE:....

**Comment by Jacksgong** [comment]
FileDownloader本身并没有带任何的so，也没有任何native层的代码，`libsigchain.so` 这个so不是FileDownloader的，这个应该不是FileDownloader的问题。

**Comment by itsmallsun** [comment]
这么快就回复了，谢谢，可以帮我分析一下是什么问题吗？

**Comment by Jacksgong** [comment]
- 确定下这个日志是否是你的进程输出的。
- 这里有一个类似的，不过他是系统bug，并且给出了解决方案: https://groups.google.com/forum/#!topic/tasker/y7a-SBGEyJI
- 你多google看看，好像挺多人遇到的。
