### ISSUE TITLE
WIFi断开重连可以继续下载吗?

### ISSUE THREAD

**Issue by rehan91** [lingochamp/FileDownloader#294]
网络断开后,比如下载过程中断开wifi,然后再连上wifi,可以自动继续下载吗?还是要自己写一个广播监听?

**Comment by rehan91** [comment]
另外一个问题,现在都不访问连接了,就直接走complete方法了,在fiddler上并没有看到有访问连接.......有点懵啊

**Comment by Jacksgong** [comment]
这个是上层的业务，需要上层实现。

**Comment by Jacksgong** [comment]
如果文件已经下载完成，是不需要网络，直接检测如果本地文件存在就是直接 completed。

> 都有源码，建议遇到问题可以先稍微看看代码这样可能会更快定位问题。
