### ISSUE TITLE
从手机的任务列表清除程序，下载进程被强制杀死？

### ISSUE THREAD

**Issue by 10045125** [lingochamp/FileDownloader#295]
情况是这样的，下载进程是一个独立的进程，此时有正在下载的进程，如果我从手机的任务列表清除应用，下载进程同样会被干掉？请问下这个情况是属于正常的？

**Comment by Jacksgong** [comment]
如果你希望下载进程在应用从任务列表清除以后，不被删除，就需要使用 [`FileDownloader#startForeground`](https://github.com/lingochamp/FileDownloader/blob/80471aa6f43109767efb7364e5061080d14bbee2/library/src/main/java/com/liulishuo/filedownloader/FileDownloader.java#L557)

---

- Ref #110
