### ISSUE TITLE
DeadObjectException

### ISSUE THREAD

**Issue by victordigio** [lingochamp/FileDownloader#298]
Hi, I'm getting this excepción sometimes in an emulator with android 7.0, and my app crashes:

    E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 144)
    W/System.err: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
    W/System.err:     at android.os.BinderProxy.transactNative(Native Method)
    W/System.err:     at android.os.BinderProxy.transact(Binder.java:615)
    W/System.err:     at com.liulishuo.filedownloader.i.IFileDownloadIPCService$Stub$Proxy.registerCallback(IFileDownloadIPCService.java:255)
    W/System.err:     at com.liulishuo.filedownloader.FileDownloadServiceUIGuard.registerCallback(FileDownloadServiceUIGuard.java:70)
    W/System.err:     at com.liulishuo.filedownloader.FileDownloadServiceUIGuard.registerCallback(FileDownloadServiceUIGuard.java:50)
    W/System.err:     at com.liulishuo.filedownloader.services.BaseFileServiceUIGuard.onServiceConnected(BaseFileServiceUIGuard.java:78)
    W/System.err:     at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1496)
    W/System.err:     at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1513)
    W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
    W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
    W/System.err:     at android.os.Looper.loop(Looper.java:154)
    W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6044)
    W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
    W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
    W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

And also this one:

    W/System.err: android.os.DeadObjectException
    W/System.err:     at android.os.BinderProxy.transactNative(Native Method)
    W/System.err:     at android.os.BinderProxy.transact(Binder.java:615)
    W/System.err:     at com.liulishuo.filedownloader.i.IFileDownloadIPCService$Stub$Proxy.registerCallback(IFileDownloadIPCService.java:255)
    W/System.err:     at com.liulishuo.filedownloader.FileDownloadServiceUIGuard.registerCallback(FileDownloadServiceUIGuard.java:70)
    W/System.err:     at com.liulishuo.filedownloader.FileDownloadServiceUIGuard.registerCallback(FileDownloadServiceUIGuard.java:50)
    W/System.err:     at com.liulishuo.filedownloader.services.BaseFileServiceUIGuard.onServiceConnected(BaseFileServiceUIGuard.java:78)
    W/System.err:     at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1496)
    W/System.err:     at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1513)
    W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
    W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
    W/System.err:     at android.os.Looper.loop(Looper.java:154)
    W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6044)
    W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
    W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
    W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

I get this exception when I download multiples files at the same time, and cancel some of them. I can't reproduce it in a concrete way.

**Comment by Jacksgong** [comment]
It is a little weird from the stack, it seems like that the filedownloader process was killed when call-backing the `ServiceConnection#onServiceConnected`, so the host process of the parameter `service:IBinder` doesn't exist, so the `service:IBinder` is DeadObject.

**Comment by Jacksgong** [comment]
You can fix such problem by another way: You can set the `process.non-separate=true` in the [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties), If you don't need the FileDownloadService hosts in the separate process.

**Comment by vicpinm** [comment]
Okey, I'll try it. Maybe it's something related with the emulator, I haven't got a real device with Andriod 7.0 yet.

**Comment by Jacksgong** [comment]
Okey, If you meet such problem in the real device, I will reopen it. Thanks.

**Comment by kineam** [comment]
I hava the same problem in device~ When user upload message to cloud service,it happend~
 W ActivityManager: Failure disconnecting service ComponentInfo{-----service} to connection android.os.BinderProxy@d262b9d (in -----service:sync)
10-11 18:35:59.790  1383  1818 W ActivityManager: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
10-11 18:35:59.790  1383  1818 W ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
10-11 18:35:59.790  1383  1818 W ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:503)
10-11 18:35:59.790  1383  1818 W ActivityManager: 	at android.app.IServiceConnection$Stub$Proxy.connected(IServiceConnection.java:92)
10-11 18:35:59.790  1383  1818 W ActivityManager: 	at com.android.server.am.ActiveServices.bringDownServiceLocked(ActiveServices.java:1823)
10-11 18:35:59.790  1383  1818 W ActivityManager: 	at com.android.server.am.ActiveServices.killServicesLocked(ActiveServices.java:2455)
10-11 18:35:59.790  1383  1818 W ActivityManager: 	at com.android.server.am.ActivityManagerService.cleanUpApplicationRecordLocked(ActivityManagerService.java:15786)
10-11 18:35:59.790  1383  1818 W ActivityManager: 	at com.android.server.am.ActivityManagerService.handleAppDiedLocked(ActivityManagerService.java:4653)
10-11 18:35:59.790  1383  1818 W ActivityManager: 	at com.android.server.am.ActivityManagerService.appDiedLocked(ActivityManagerService.java:4826)
10-11 18:35:59.790  1383  1818 W ActivityManager: 	at com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied(ActivityManagerService.java:1339)
10-11 18:35:59.790  1383  1818 W ActivityManager: 	at android.os.BinderProxy.sendDeathNotice(Binder.java:558)
10-11 18:35:59.791  1383  2546 I ActivityManager: Process -----service:sync (pid 18810) has died


i can't see what's wrong~
