### ISSUE TITLE
你好，请问下获取下载速度的API怎么才能调用到。

### ISSUE THREAD

**Issue by liqk2014** [lingochamp/FileDownloader#299]
如题。好像被封装到DownloadTask里面了，尝试使用FileDownloader.getImpl().create(downloadUrl).getSpeed() 去获取，一直为0.

**Comment by xiejinglan** [comment]
see  BaseDownloadTask#getSpeed()

**Comment by Jacksgong** [comment]
`create`始终创建一下新的对象，是不行的。

正在下载的`BaseDownloadTask`对象，也可以在`FileDownloadListener`中获取对象到下载速度，也可以参考Demo中 `SingleTaskTestActivity.java`对获取速度的使用。

---

需要特别注意的是，在下载过程中，该速度是瞬时速度，下载结束以后，是全程的平均速度，具体看注解: [BaseDownloadTask#getSpeed()](https://github.com/lingochamp/FileDownloader/blob/80471aa6f43109767efb7364e5061080d14bbee2/library/src/main/java/com/liulishuo/filedownloader/BaseDownloadTask.java#L395)。

**Comment by liqk2014** [comment]
好的谢谢。
