### ISSUE TITLE
OkHttp version

### ISSUE THREAD

**Issue by pengjianbo** [lingochamp/FileDownloader#3]
现在OkHtttp3.0出来了，可更新到最新版本吗

**Comment by benzheren** [comment]
@pengjianbo 欢迎 PR 啊 :smile_cat:

**Comment by Jacksgong** [comment]
欢迎PR :)， 多谢提醒，我抽空因为是RC，我看下他的changelog，如果没有及时更新也会给出个解决方案的。

**Comment by Jacksgong** [comment]
我刚刚看了下。okhttp 3.0.0-RC1做来这块兼容，改了包名，2.x与3.0两个一起用是没有问题的（也会引起一个问题，你无法`exclude`我这边的引用，而直接用你那边3.0的引用，包名不同），我这边会先升级到2.7.1，多谢提醒。后续如果okhttp升级到了3.0正式版了，我这边会跟着升的。

```
This release obsoletes OkHttp 2.x, and all code that uses OkHttp's com.squareup.okhttp package should upgrade to the okhttp3 package. Libraries that depend on OkHttp should upgrade quickly to prevent applications from being stuck on the old version.
```

**Comment by pengjianbo** [comment]
上周末收到okhttp开发者Jesse Wilson的消息，叫我更新到okhttp3.因为我现在项目更新到3，我想用你这个框架可是版本不一样。哈哈~

**Comment by Jacksgong** [comment]
哦。 不过你们同时引用使用okhttp3，引用我们的项目应该是不会有问题的。ps. 今天我们会发一个版本，带上okhttp `2.7.1`

**Comment by pengjianbo** [comment]
嗯。谢谢~.我还是等正式版吧。对了，FileDownloader还是0.x版本，什么时候可以出正式版或稳定的版本呀

**Comment by Jacksgong** [comment]
:) 其实我们没有beta、alpha，0.x只是版本号，一直都是当做正式版发布，我们自己也在使用。不过还有很多想要做的在排期做。不过不会影响正常的使用。

现在这个版本可以有已知的问题是，如果不同的[下载链接与路径]达到一定的阀值，比如10w或者100w，下载进程 初始化(从数据库中加载数据)的时候可能会有些吃力，并且吃内存，所以这边还要处理类似的边界情况（时效性？分时加载之类的），这个问题预计会在下个的下个版本处理掉。其他问题可能只有在大量使用以后发现吧。

**Comment by pengjianbo** [comment]
嗯~好的，三克油

**Comment by Jacksgong** [comment]
恩~。不用~，我已经提交[新版本](https://github.com/lingochamp/FileDownloader/commit/2c2700e0db1a5cdc03ad887d2f72a0fc00e609d8)了。
