### ISSUE TITLE
Application中初始化后 isDownloaderProcess出现异常

### ISSUE THREAD

**Issue by heming0512** [lingochamp/FileDownloader#302]
Application中初始化之后 FileDownloader.init(getApplicationContext())。出现一下异常。
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
 排查发现FileDownloadUtils isDownloaderProcess（）方法中针对list循环缺少防止空指针处理？

**Comment by Jacksgong** [comment]
This has already fixed since [0.3.4](https://github.com/lingochamp/FileDownloader/blob/master/CHANGELOG.md#version-034).

**Comment by Jacksgong** [comment]
Ref: #210

**Comment by heming0512** [comment]
Thanks.
