### ISSUE TITLE
Remove Download

### ISSUE THREAD

**Issue by Trinkes** [lingochamp/FileDownloader#304]
Hi, 
Is there any way to remove a download? I know there is the pause method but i want to remove the download.
Thanks for sharing this lib! :+1:

**Comment by Jacksgong** [comment]
Thanks, Yes: [FileDownloader#clear(id:int, targetFilePath:String)](https://github.com/lingochamp/FileDownloader/blob/80471aa6f43109767efb7364e5061080d14bbee2/library/src/main/java/com/liulishuo/filedownloader/FileDownloader.java#L325)

**Comment by Trinkes** [comment]
Yeah, meanwhile i found it in documentation and on code, sorry for bother.
keep up the good job!
