### ISSUE TITLE
我也出现leDownloader#bindService调用了却没有任何反应的问题

### ISSUE THREAD

**Issue by xanaduo** [lingochamp/FileDownloader#306]
不知道为什么突然就不行了。按照Demo里面的还是不行。

**Comment by Jacksgong** [comment]
可以贴下之前问题的issue吗？我不是很明白你是什么问题。

**Comment by xanaduo** [comment]
#263 我看到有人提出这样的问题。看不到任何错误，只有一个FileDownloader.DownloadServiceNotConnectedHelper: request get the status for the task[761951672] in the download service, but the download service isn't connected yet.

**Comment by Jacksgong** [comment]
`FileDownloader#bindService` 不是同步调用的，是异步的，因为是启动一个服务，回调是在链接上以后，系统回调链接上，然后再回调给上层。

如果你是通过 `FileDownloader#getStatus`、`FileDownloader#getTotal` 之类的操作，需要确保服务已经链接上，你可以参照: https://github.com/lingochamp/FileDownloader/issues/241#issuecomment-236877194 或者https://github.com/lingochamp/FileDownloader/issues/235#issuecomment-236560136

**Comment by Jacksgong** [comment]
如果等了很久，始终没有连接上的，说明服务始终没有起来，你看看是否是有其他异常，或者日志，因为这块是直接调用系统接口进行启动Service与绑定Service的。

**Comment by xanaduo** [comment]
后来有又好了，不过确实没看到错误信息。

**Comment by Jacksgong** [comment]
你检查下，也有可能是你在`Application#onCreate`中做了一些事情没有根据进程判断处理，导致启动下载进程的时候进行了相关处理导致的。

也可以在filedownloader.properties中定义 `process.non-separate=true`，使得下载服务在主进程，这样启动下载服务会更加轻量，也会更快。

**Comment by xanaduo** [comment]
filedownloader.properties在哪个地方啊，我使用gradle方式引用的。

**Comment by Jacksgong** [comment]
README中有说明的: https://github.com/lingochamp/FileDownloader/blob/master/README-zh.md#filedownloaderproperties
Wiki中也有说明: https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties

---

放到`asset`目录。

**Comment by xanaduo** [comment]
好的，谢谢了

**Comment by Jacksgong** [comment]
恩
