### ISSUE TITLE
如果下载是在下载进程，这时不启动下载进程，如何与主进程在显示下载页面时保持数据同步

### ISSUE THREAD

**Issue by 10045125** [lingochamp/FileDownloader#308]
如果下载是在下载进程，这时不启动下载进程，如何与主进程在显示下载页面时保持数据同步

**Comment by Jacksgong** [comment]
所有数据都是在下载服务中(如果默认情况是在独立(下载)进程)，上层代码`FileDownloadList`只存储了运行时的队列，如果没有启动下载服务，是无法启动下载的。

> PS: 1. 任意下载任务启动时，会自动启动下载服务，并且下载服务启动后开始执行任务。
> PS: 2. 如果在下载过程中下载服务被杀，所有运行中的任务会全部终止(`freeze`)，进入等待队列，并且尝试重新启动服务，连接上后重启启动等待队列中的任务，由于默认有异常断点续传保证，所以上层几乎无感。

**Comment by Jacksgong** [comment]
下载服务（默认在独立（下载）进程）存储的数据的数据结构: `FileDownloadModel.java`
