### ISSUE TITLE
Chunk下载不支持

### ISSUE THREAD

**Issue by 10045125** [lingochamp/FileDownloader#309]
我这边试了一个chunked的下载链接，如果暂停后再继续是会出现下载失败。

**Comment by Jacksgong** [comment]
报的是什么错误，我测试 demo project中的 `SingleTaskTestActivity` 中的 chunked 下载，暂停后再下载没有任何问题啊。

**Comment by 10045125** [comment]
你是不是使用了重试机制？

**Comment by 10045125** [comment]
我用demo试了，也是不行的，异常是if (soFar == total) {

                // Step 9, rename the temp file to the completed file.
                renameTempFile();

                // callback completed
                iDownLoadCoreCallBack.onComplete(total);

                return true;
            } else {
                throw new RuntimeException(
                        FileDownloadUtils.formatString("sofar[%d] not equal total[%d]", soFar, total));
            }
sofar != total,而抛出的异常。

**Comment by Jacksgong** [comment]
你可以试试demo project，没有使用重试机制。

我这边测试可以啊，你是什么时候的代码？

---

你认真看下最新代码，如果是chunked是不可能走这个逻辑的:

```
// Step 7, adapter chunked transfer encoding
if (total == TOTAL_VALUE_IN_CHUNKED_RESOURCE) {
    total = soFar;
}

// Step 8, Compare between the downloaded so far bytes with the total bytes.
if (soFar == total) {

    // Step 9, rename the temp file to the completed file.
 
```

**Comment by Jacksgong** [comment]
1. 你看看你的代码是否是最最新代码。
2. 你可以debug看下为何你那边会走到这个不该走的路径。

> 根据你的阐述我这边无法定位到这个问题。并且我这边无法复现类似问题。

**Comment by 10045125** [comment]
我拉了最新代码，如果是chunk重头开始下到尾（不暂停，不中断）是没问题的，但是暂停后再继续，明明是chunk，但是还是会像断点续传的方式下载，但是下到最后出现sofar not equal total，
![image](https://cloud.githubusercontent.com/assets/2945098/18336061/bccf42ea-75b6-11e6-929e-4fa3342882c3.png)，我调试后发现首次启动下载的时候response.header("Transfer-Encoding")获取到的是chunked，之后返回的是null。response.body().contentLength()一开始是－1，后来是有值的。

**Comment by Jacksgong** [comment]
我这边按照你所说的逻辑无法复现:

录制视频: 
[record.mp4.zip](https://github.com/lingochamp/FileDownloader/files/460791/a.mp4.zip)

---

1. 你看看你的代码是你fork的代码的最新代码，还是 `lingochamp/FileDownloader` 的最新代码。
2. 如果1确定是 `lingochamp/FileDownloader`的最新代码，你debug看看，是什么时候，total突然又有值了。

----

> P.S: chunked资源下载，应该是在下载结束的时候 total才会有值，并且等于sofar，因为在下载过程中不知道文件的大小，只能从输入流不断取，直到结束，就将sofar，作为total。

**Comment by 10045125** [comment]
代码是你的最新代码，我先贴张图：
![image](https://cloud.githubusercontent.com/assets/2945098/18339597/08ae16ca-75d3-11e6-8f68-669b924deceb.png)
从日志上看出，第一次成功开始的时候，response.header("Transfer-Encoding"):chunked，当暂停后继续下载的时候response.header("Transfer-Encoding"):null，我觉得是这里出现了问题。如果出现了null,一下代码：
`if (isSucceedStart || isSucceedResume) {
                    long total = model.getTotal();
                    final String transferEncoding = response.header("Transfer-Encoding");

                    // Step 5, check response's header
                    if (isSucceedStart || total <= 0) {
                        if (transferEncoding == null) {
                            total = response.body().contentLength();
                        } else {
                            // if transfer not nil, ignore content-length
                            total = TOTAL_VALUE_IN_CHUNKED_RESOURCE;
                        }
                    }`
问题是在total ＝ -1 这个时候transferEncoding也是为null，而response.body().contentLength() 也是有值的。。。。。。

**Comment by Jacksgong** [comment]
@10045125 根据你的描述，十分明显是这个是个服务端的错误。

- 第一，十分的诡异不符合规范，同一个资源，第一次请求返回头告知是流媒体，而第二次请求由于不同的请求头返回的是，返回的却是非流媒体。
- 第二，第二次请求，我们根据服务端返回非流媒体结果，进行正常资源的下载，1) 告知服务器我们需要的数据流区间与Etag，2) 服务端返回 206说明会按照区间返回，3)我们从输入流中取数据并且写入到文件中，4) 但是在我们写结束的时候发现，写完以后的总大小不符合服务端给回来告知内容应有的总大小，那就是说服务端给回的数据有问题才抛这个异常。

**Comment by 10045125** [comment]
我觉得程序处理还是不够健壮，同是这个链接在QQ、UC浏览器中下载都是OK的

**Comment by Jacksgong** [comment]
#### 其实这里是一个取舍。

因为我们这个是一个库，而非一个产品:

我是觉得作为库，这个是服务端的错误，我们需要将这个错误暴露出来，这样才能让整个程序更加稳定，而非存在隐藏的问题。
如果是作为产品，可以考虑说，第一次是流媒体，第二次发现非流媒体，就自动抛弃从头开始下载。

**Comment by Jacksgong** [comment]
第一次是流媒体，服务端返回的第二次不是流媒体，而且告知客户端说可以断点续传，其实FileDownloader也是支持这样的断点续传的，但是刚好这个服务端给回来的数据流大小还是错误的。

**Comment by Jacksgong** [comment]
就程序而言: 如果说我们这边直接简单粗暴的: 发现第一次为流媒体，第二次不是流媒体，就重头下载，就等于不信任http返回。如果说我们这么做了，相对而言又存在另外一个问题，就是如果第一次为流媒体，第二次我给后台Etag，给后台区间，后台告诉我们支持断点续传了，我们却重头开始下载，从另一个侧面看不符合预期。

---

如果作为业务层你允许后台犯这样的错误，你只需要发现这种`total!=sofar`的异常，直接转为成功即可，因为此时所有数据都已经写入完毕。

**Comment by 10045125** [comment]
我个人观点是：既然下载框架承接了下载功能，就应该尽最大的可能保证结果的正确性，比如针对我这种情况，从服务器读取文件到结束，就是文件读取完毕，这个时候其实结果是完整的。而不应该单纯的以sofar != total而否定结果的正确性（实际上下载文件是完整的）

**Comment by Jacksgong** [comment]
- -||。不是说从输入流取完以后就下载完成了，文件就完整了，除非是流媒体。

这个也是`content-length`的作用之一。

这里的 `sofar!=total` 实际上就是 `最后取完结果的大小 是否等于 服务端告知的内容的大小content-length`的大小，是防止传输过程中的丢包、或者是网络中的劫持，这是一个最基本的校验。如果服务端给了`content-length`，最后判定取完流后的大小不等于这个值，那么所下载的内容就肯定是有问题的。这个是 下载的一个最基本的验证。

**Comment by 10045125** [comment]
如何保证content-length结果是正确的呢？

**Comment by Jacksgong** [comment]
#### 这个是服务端的问题。
输入流的数据是服务端给的，`content-length`也是服务端给的。

**Comment by 10045125** [comment]
能不能通过下载文件后的md5校验文件的完整性？

**Comment by Jacksgong** [comment]
关于 `content-length`的验证，我在系统的DownloadThread也是类似的做法，你可以看下: http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android-apps/5.1.1_r1/com/android/providers/downloads/DownloadThread.java#583

这种基本校验是下载最基本的依据。

关于md5的校验，这个是并非一个普遍的做法，并且考虑到md5生成的消耗，通常如果上层业务在一些场景下需要，可以自己在下载完成以后做相应的校验(如，可以在 `blockComplete`中进行校验)。
