### ISSUE TITLE
下载过程中退出当前页面，再进来怎么让progressbar进度恢复呢

### ISSUE THREAD

**Issue by HuangShun** [lingochamp/FileDownloader#31]

**Comment by Jacksgong** [comment]
可以参考下。任务管理的demo

**Comment by Jacksgong** [comment]
如果需要获得某任务的进度`FileDownloader#getSoFar(downloadId):int` 与`FileDownloader#getTotal(downloadId):int`来获取的。

**Comment by HuangShun** [comment]
我看了下#4的方法。有一个问题就是下载界面都是B界面。从不同的界面进来，数据还是第一个界面的数据。这该怎么弄

**Comment by Jacksgong** [comment]
我不是很明白你的需求与困难所在。

你可以理解FileDownloader是一个驱动下载的lib，业务层面如何应该是业务层级需要实现的，但是如果lib这边相对与业务层级这边无法满足，你详细描述下，我给你思考下处理方式，或者是对FileDownloader进行拓展。

**Comment by HuangShun** [comment]
额。就是这样。跟应用市场差不多。A界面有个游戏的Listview，从不同的item进来，下载的地址不同但界面都是同一个。现在想做的就是可以同时下多个游戏，并且退出来再进某个游戏下载界面的时候，能重新获取该游戏下载的监听事件。

**Comment by Jacksgong** [comment]
你所说的这种情况，就是 [TasksManagerDemoActivity.java](https://github.com/lingochamp/FileDownloader/blob/master/demo/src/main/java/com/liulishuo/filedownloader/demo/TasksManagerDemoActivity.java) 的case，你可以运行下demo，然后稍微调整下，就是你想要的case了。

**Comment by HuangShun** [comment]
java.lang.ExceptionInInitializerError
                                                                                           at com.example.administrator.myapplication.download.util.TasksManagerDemoActivity$TasksManager.getImpl(TasksManagerDemoActivity.java:371)
                                                                                           at com.example.administrator.myapplication.download.util.TasksManagerDemoActivity.onCreate(TasksManagerDemoActivity.java:54)

直接用的你的。会报这个错误。

**Comment by Jacksgong** [comment]
demo中的代码是没有问题的。我的意思是你在项目demo上进行执行，然后做调整后，可以参考类似方法实现。并不建议你直接拷贝对应的Activity过去的。

P.S: FileDownloader已经支持了类似TasksManagerDemo中的功能，一些业务层级的还希望能够自己在上层封装(TasksManagerDemo中也是模拟了一些业务需求，然后根据业务需求进行实现了业务需求相关部分，所以不建议直接拷贝过去使用而是参考)。

---

如果你遇到类似问题找不出原因，可以提取你 出现问题的那部分代码，做一个简单的项目，通过github repo的方式给我地址，我抽空给你看下。

**Comment by HuangShun** [comment]
嗯。我先试试

**Comment by Jacksgong** [comment]
恩。:)

**Comment by HuangShun** [comment]
刚开始学，有的东西还看不懂所以用了一种比较笨的方式，效果还过得去吧。十分感谢。

**Comment by Jacksgong** [comment]
Well done.
