### ISSUE TITLE
删除正在下载文件的问题

### ISSUE THREAD

**Issue by 13107422824** [lingochamp/FileDownloader#310]
我删除一个正在下载的文件，代码如下：
   //这句应该是将下载的任务设置成暂停状态吧？看其他的帖子这里设置后缓存的数据全部都会清空掉，
                FileDownloader.getImpl().pause(downloadItemModel.getId());
               //移除数据库中的记录 并且将.temp文件也删除
                c.removeTask(downloadItemModel.getId(), downloadItemModel.getPath());
                listItems.remove(downloadItemModel);
                this.notifyDataSetChanged();
                // 删除了 就要去更新列表 状态
但是我这样写当我删除下载文件后，数据库删除掉了，文件也删除掉了，当我重新点击该文件下载的时候，第一下显示上一次已经下载的进度，然后才会从0开始。这是什么原因呢？

**Comment by 13107422824** [comment]
希望得到帮助

**Comment by Jacksgong** [comment]
恩。这个主要是因为你调用的是 `FileDownloader#pause`，这里之所以说是`pause`是因为下一次启动的时候是自动断点续传的，但是实际上清除了所有的缓存数据，但是数据库中的数据还是存在的是为了下一次断点续传。

---

`FileDownloader#pause`之后删除对应的下载中的文件，确实下一次启动，第一次会回调数据上一次的数据，这个是告知最后一次下载的数据，而后FileDownloader发现之前的文件不存在，会从0开始。

---

### 解决方案

如果你需要清除一个任务的数据，下次完全重头开始，你需要调用 `FileDownloader#clear`，这样可以符合你的预期。

**Comment by 13107422824** [comment]
非常感谢你的解答，才发现我使用的这个包中没有clear方法。感谢。

**Comment by Jacksgong** [comment]
恩。升级到最新版本即可。
