### ISSUE TITLE
issue in downloading a url

### ISSUE THREAD

**Issue by sanishks** [lingochamp/FileDownloader#311]
http://blogs-images.forbes.com/kristintablang/files/2016/03/Bugatti-Chiron-2016-1200x675.jpg
issue in downloading this url
content-length -1

**Comment by Jacksgong** [comment]
There are all information in the message of FileDownloadGiveUpRetryException which thrown when you try to download this resource:

```
can't know the size of the download file, and its Transfer-Encoding is not Chunked either.
you can ignore such exception by add http.lenient=true to the filedownloader.properties
```

---

It means there is no `content-length` in the response header and also it isn't `Chunked` resource which declared in the `Transfer-Encoding` key, what isn't follow HTTP rules.

But you can add `http.lenient=true` to the [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties) to prevent such exception, and deal with it as the case of chunked resource.

---

Response header:

```
0 = "Server"
1 = "Apache"
2 = "Last-Modified"
3 = "Fri, 04 Mar 2016 23:58:48 GMT"
4 = "Vary"
5 = "Accept-Encoding"
6 = "Content-Type"
7 = "image/jpeg"
8 = "Backend"
9 = "blogs"
10 = "x-url"
11 = "/kristintablang/files/2016/03/Bugatti-Chiron-2016-1200x675.jpg"
12 = "x-host"
13 = "blogs.forbes.com"
14 = "Accept-Ranges"
15 = "bytes"
16 = "X-Frame-Options"
17 = "SAMEORIGIN"
18 = "Cache-Control"
19 = "public, max-age=2591990"
20 = "Expires"
21 = "Wed, 12 Oct 2016 10:20:13 GMT"
22 = "Date"
23 = "Mon, 12 Sep 2016 10:20:23 GMT"
24 = "Connection"
25 = "keep-alive"
```
