### ISSUE TITLE
Complie error

### ISSUE THREAD

**Issue by dogialong** [lingochamp/FileDownloader#312]
can't  Initialization  with   compile 'com.liulishuo.filedownloader:library:1.0.2'
please help

**Comment by Jacksgong** [comment]
Sorry, I don't know what problem with you.

FileDownloader 1.0.2 is available in JCenter: http://jcenter.bintray.com/com/liulishuo/filedownloader/library/1.0.2/ , and also available in Maven Central: https://oss.sonatype.org/content/repositories/releases/com/liulishuo/filedownloader/library/1.0.2/

**Comment by dogialong** [comment]
![image](https://cloud.githubusercontent.com/assets/15606147/18460567/d52cee66-799c-11e6-8558-682964965d73.png)
this error

**Comment by Jacksgong** [comment]
Please check your root path `build.gradle` file, make sure there is `jcenter()` or `mavenCentral()` declared in the `buildscript.repositories`:

```groovy
...
buildscript {
         repositories {
                 jcenter()
                 // or mavenCentral() is fine
                 ...
          }
...
}
...
```

If you have already declared it, please check your network  whether it can access [jcenter-repository](http://jcenter.bintray.com/com/liulishuo/filedownloader/library/1.0.2/) or [mavenCentral-repository](https://oss.sonatype.org/content/repositories/releases/com/liulishuo/filedownloader/library/1.0.2/).

**Comment by dogialong** [comment]
okay . its working
