### ISSUE TITLE
建议下载完成后不要自动remove

### ISSUE THREAD

**Issue by 10045125** [lingochamp/FileDownloader#315]
最近代码的改动有一处是：在下载完成后会自动清空下载的数据库记录，我认为这个自动清除不大好。
原因有几点：
1. 数据库只是记录信息的，作为下载最底层的数据存储，其数据是可靠、稳定的
2. 删除下载记录应该由上层逻辑调用，也就是说用户把下载列表的东西删除了，上层业务应该是需要自己去调用移除下载记录的逻辑，下载框架提供这个接口就ok的。
3. 我在做数据同步的时候（原因是在不启动下载进程也能够准确的同步下载数据），由业务方告知需要移除记录的id就OK了。
4. 给上层业务更强的扩展性。

以上是个人见解。

**Comment by Jacksgong** [comment]
这个是内部的数据库，不建议用于外界业务层使用，并且也不会提供给外界接口调用。

数据库的初衷非常的简单：维护断点续传。因此内部设计尽量的简单轻量。

**Comment by Jacksgong** [comment]
就如同Demo中写的，如果上层需要有相关下载业务相关，可以考虑自建数据库或者其他方式，如果依赖内部数据库将会十分的不稳定。

- 一方面内部数据库会由于不断的迭代发生改变，甚至重构，规则会随着内部的需要不断改变。
- 内部数据库会在各种情况下进行维护以及清理相关数据，不适用上层对其耦合。

**Comment by Jacksgong** [comment]
目前对于你提到的内部数据作为依据，是为上层提供稳定的，可靠的数据源这点，FileDownloader已经对其暴露了必要的提供灵活性的接口，如: `FileDownloader#getStatus`、`FileDownloader#getSoFar`等等。

至于是否已经下载完成，也可以通过 `FileDownloader#getStatus(url:String, path:String)`来获知。

---

更多的使用，可以参照 `TasksManagerDemoActivity`。

**Comment by Jacksgong** [comment]
另一方面，相比之前一直存储数据在数据库而言，目前这种策略对于FileDownloader而言会更加可靠。

- 之前如果本地文件删除了，数据库中的数据没有得到更新，你获得的`status`是`completed`但是其实已经被删除了。
- 新的策略，由于FileDownloader只有在确保文件正确的下载完成了，才会重命名临时文件为目标文件路径，因此新的策略只需要通过路径判定是否存在来判定是否已经下载完成。这个基本上可以是最轻量，干净，可靠的策略，也是各个平台中在这块比较常见的策略方式。

**Comment by 10045125** [comment]
我移除了下载完整后的删除数据库的记录，但是为什么最终还是会把下载完成后的记录删除？

**Comment by Jacksgong** [comment]
这里目前是在`FileDownloadDBHelper`有做类似的数据库维护。不过在未来的迭代中，预计可能为了FileDownloader更加轻量以及灵活，还会有其他的迭代，甚至字段的变化。如果你有逻辑与内部数据库直接耦合，建议改用上层接口的方式，避免导致各种不达预期的问题。

**Comment by Jacksgong** [comment]
我上面几个答复已经很用心的写了：`该需求的解决方案` 以及 `原因`，希望能够认真看看。

**Comment by 10045125** [comment]
其实我的问题来源是：
1. 下载进程作为一个独立进程的情况下，在不启动下载进程如何获取下载的相关的数据状态
2. 下载进程启动的情况下，我希望直接通过FileDownloader去获取

**Comment by 10045125** [comment]
非常感谢你的耐心解答，为了实现不启动下载进程数据同步问题我不得不修改源代码，目前我已经完善了满足我要求的功能需求。非常感谢

**Comment by Jacksgong** [comment]
Okey.

**Comment by 10045125** [comment]
在使用中遇到进程会重启后自动下载的情况，请问这是如何控制的？

**Comment by Jacksgong** [comment]
为了做到对上层无感，下载引擎如果识别到当前不是主动触发的的断开连接，而是 以外的丢失与服务的连接，会尝试重启并且在重启以后继续下载剩余的任务。相关的逻辑可以参考: `LostServiceConnectedHandler`

#### 如果你希望杀死进程，不会被自动重启

1. 建议直接通过 `FileDownloader#unBindService()`即可。因为`unBindService()`以后，下载进程就是空进程了，这样是不会消耗任何资源的，很快就会被系统回收的，在 `设置->运行中的应用` 中也不会看到当前应用存在进程，因为已经被移到缓存进程。具体进程回收机制可以参看: [Android中线程、进程与组件的关系](http://blog.dreamtobe.cn/2015/04/08/android_thread_process_components/)。
2. 如果实在是想要主动杀死下载进程(不建议)，那么在服务连接(`FileDownloader#isServiceConnected()`)的情况下，监听服务连接状态`FileDownloader#addServiceConnectListener(FileDownloadConnectListener)`, 主动触发`FileDownloader#unBindService()`，然后调用该方法后，监听到`FileDownloadConnectListener#disconnected()`，然后在回调中杀死下载进程就可以了。
