### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by pop1030123** [lingochamp/FileDownloader#316]
线上的应用在bugly上面报了如下错误：

java.lang.IllegalStateException
No reused downloaded file' in this message -863250521 -3
com.liulishuo.filedownloader.message.MessageSnapshot.boolean isReusedDownloadedFile()(MessageSnapshot.java:103)
com.liulishuo.filedownloader.DownloadTaskHunter.void update(com.liulishuo.filedownloader.message.MessageSnapshot)(DownloadTaskHunter.java:197)
com.liulishuo.filedownloader.DownloadTaskHunter.boolean updateKeepFlow(com.liulishuo.filedownloader.message.MessageSnapshot)(DownloadTaskHunter.java:82)
com.liulishuo.filedownloader.MessageSnapshotGate.boolean transmitMessage(java.util.List,com.liulishuo.filedownloader.message.MessageSnapshot)(MessageSnapshotGate.java:44)
com.liulishuo.filedownloader.MessageSnapshotGate.void receive(com.liulishuo.filedownloader.message.MessageSnapshot)(MessageSnapshotGate.java:84)
com.liulishuo.filedownloader.message.MessageSnapshotThreadPool$FlowSingleExecutor$1.void run()(MessageSnapshotThreadPool.java:102)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
java.lang.Thread.run(Thread.java:841)

**Comment by Jacksgong** [comment]
看这个栈，确实是FileDownloader的BUG，但是我检查代码，没有找出原因:

1. 能够进入 `DownloadTaskHunter.java:197` 说明该`Message`的状态是`Completed`
2. 所有能够到达的`MessageSnapshotGate `的`Completed`状态的Message，都是实现了`isReusedDownloadedFile()`方法的，Ref: `SmallMessageSnapshot.CompletedFlowDirectlySnapshot`、`SmallMessageSnapshot.CompletedSnapshot`、`LargeMessageSnapshot.CompletedFlowDirectlySnapshot`、`LargeMessageSnapshot.CompletedSnapshot`。
3. 同时满足是`Completed`状态，并且没有实现`isReusedDownloadedFile()`的对象，只有可能是`BlockCompleteMessageImpl`的实例，但是这个只在对外消息的`FileDownloadMessageStation`中用到，并不会与内层消息有关系。

#### 想了解下几个情况来进一步定位问题:

1. 这是哪个版本的异常，你有修改过内部代码实现吗？
2. 这个的Crash率如何？

**Comment by pop1030123** [comment]
1. 版本是1.0.0  ，使用gradle compile引用 ，没有使用源码 ；
2.crash 比较低 ，几千个用户，crash不到10次 。

**Comment by Jacksgong** [comment]
@pop1030123 好的，我再认真看看。

**Comment by lct8712** [comment]
我也在 bugly 上收到了同样的问题，版本是 1.0.1

**Comment by lct8712** [comment]
稍微具体一点的跟踪日志：


36--------- beginning of /dev/log/main
3709-13 18:48:20.311 18557 18711 W FileDownloader.MessageSnapshotTaker: it can't takes a snapshot for the task(id[446579513], url[http://dl-android.gotokeep.com/keep-beta1120_a507c96ead20287ef373b817ae5b9461.apk?download/keep-beta1120.apk], path[/storage/emulated/0/keep/image/keep.apk], status[-3], sofar[34954279], total[34954279], etag[null], com.liulishuo.filedownloader.model.FileDownloadModel@42c0d428) when its status is -3,
3809-13 18:48:20.312 18557 18710 D dalvikvm: create interp thread : stack size=128KB
3909-13 18:48:20.312 18557 18710 D dalvikvm: create new thread
4009-13 18:48:20.312 18557 18710 D dalvikvm: new thread created
4109-13 18:48:20.312 18557 18710 D dalvikvm: update thread list
4209-13 18:48:20.312 18557 19113 D dalvikvm: threadid=37: interp stack at 0x7f860000
4309-13 18:48:20.312 18557 19113 D dalvikvm: threadid=37: created from interp
4409-13 18:48:20.312 18557 18710 D dalvikvm: start new thread
4509-13 18:48:20.312 18557 18710 D dalvikvm: threadid=63: exiting
4609-13 18:48:20.312 18557 18710 W dalvikvm: threadid=63: thread exiting with uncaught exception (group=0x41cc0ce0)
4709-13 18:48:20.312 18557 19113 D dalvikvm: threadid=37: notify debugger
4809-13 18:48:20.312 18557 18710 W dalvikvm: threadid=63: uncaught exception occurred
4909-13 18:48:20.312 18557 19113 D dalvikvm: threadid=37 (FileDownloader-FowSingleExecutor0-2): calling run()
5009-13 18:48:20.312 18557 18710 W System.err: java.lang.IllegalStateException: No reused downloaded file' in this message 446579513 -3
5109-13 18:48:20.312 18557 18710 W System.err: at com.liulishuo.filedownloader.message.MessageSnapshot.isReusedDownloadedFile(MessageSnapshot.java:104)
5209-13 18:48:20.312 18557 18710 W System.err: at com.liulishuo.filedownloader.DownloadTaskHunter.update(DownloadTaskHunter.java:197)
5309-13 18:48:20.313 18557 18710 W System.err: at com.liulishuo.filedownloader.DownloadTaskHunter.updateKeepFlow(DownloadTaskHunter.java:82)
5409-13 18:48:20.313 18557 18710 W System.err: at com.liulishuo.filedownloader.MessageSnapshotGate.transmitMessage(MessageSnapshotGate.java:44)
5509-13 18:48:20.313 18557 18710 W System.err: at com.liulishuo.filedownloader.MessageSnapshotGate.receive(MessageSnapshotGate.java:84)
5609-13 18:48:20.313 18557 18710 W System.err: at com.liulishuo.filedownloader.message.MessageSnapshotThreadPool$FlowSingleExecutor$1.run(MessageSnapshotThreadPool.java:102)
5709-13 18:48:20.313 18557 18710 W System.err: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
5809-13 18:48:20.313 18557 18710 W System.err: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
5909-13 18:48:20.313 18557 18710 W System.err: at java.lang.Thread.run(Thread.java:848)
6009-13 18:48:20.313 18557 18710 W dalvikvm: threadid=63: calling UncaughtExceptionHandler
6109-13 18:48:20.313 18557 18710 I dalvikvm: +++ calling Ljava/lang/ThreadGroup;.uncaughtException
6209-13 18:48:20.313 18557 18710 E MtaSDK :
6309-13 18:48:20.313 18557 18710 E MtaSDK : java.lang.IllegalStateException: No reused downloaded file' in this message 446579513 -3
6409-13 18:48:20.313 18557 18710 E MtaSDK : at com.liulishuo.filedownloader.message.MessageSnapshot.isReusedDownloadedFile(MessageSnapshot.java:104)
6509-13 18:48:20.313 18557 18710 E MtaSDK : at com.liulishuo.filedownloader.DownloadTaskHunter.update(DownloadTaskHunter.java:197)
6609-13 18:48:20.313 18557 18710 E MtaSDK : at com.liulishuo.filedownloader.DownloadTaskHunter.updateKeepFlow(DownloadTaskHunter.java:82)
6709-13 18:48:20.313 18557 18710 E MtaSDK : at com.liulishuo.filedownloader.MessageSnapshotGate.transmitMessage(MessageSnapshotGate.java:44)
6809-13 18:48:20.313 18557 18710 E MtaSDK : at com.liulishuo.filedownloader.MessageSnapshotGate.receive(MessageSnapshotGate.java:84)
6909-13 18:48:20.313 18557 18710 E MtaSDK : at com.liulishuo.filedownloader.message.MessageSnapshotThreadPool$FlowSingleExecutor$1.run(MessageSnapshotThreadPool.java:102)
7009-13 18:48:20.313 18557 18710 E MtaSDK : at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
7109-13 18:48:20.313 18557 18710 E MtaSDK : at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
7209-13 18:48:20.313 18557 18710 E MtaSDK : at java.lang.Thread.run(Thread.java:848)

**Comment by Jacksgong** [comment]
@lct8712 好的，多谢。

**Comment by Jacksgong** [comment]
看起来确实是bug，但是我找了很久没有找到原因，又无法复现，我今晚再看下。你们看看有空也思考下哈。

**Comment by Jacksgong** [comment]
会尽量在今晚的`1.1.5`版本带上。如果可以，你们也提供下思路，我再思考思考。

**Comment by pop1030123** [comment]
我的APP使用场景比较多一点 ，主要有以下几类：
1.手动单文件下载；
2.手动多文件串行下载；
3.自动多文件串行下载；
由于以上3个场景使用的是同一个下载组件 ，会存在场景组合使用的情况 ，比如串行下载的同时，又手动单文件下载 ，我看demo里面可能没有这么复杂，看看从我的使用场景里面是否能分析出可能的问题；

**Comment by Jacksgong** [comment]
@pop1030123 恩恩。多谢。

**Comment by Jacksgong** [comment]
@pop1030123 其实你锁的这种情况完全可以在demo中的混合测试中模拟的。

**Comment by Jacksgong** [comment]
我明早再看看。今晚还没有看出问题。1.1.5延后到明天发布。
