### ISSUE TITLE
已经下载了的url,task获取其状态是INVALID_STATUS？

### ISSUE THREAD

**Issue by mzpbvsig** [lingochamp/FileDownloader#317]
如题

**Comment by Jacksgong** [comment]
如果你是使用`FileDownloader#getStatusIgnoreCompleted(id)`，确实是这样子的，这个方法原本就忽略完成状态，具体可以看注解:  https://github.com/lingochamp/FileDownloader/blob/master/library/src/main/java/com/liulishuo/filedownloader/FileDownloader.java#L390

**Comment by Jacksgong** [comment]
如果你需要覆盖已经下载的状态，请使用: `FileDownloader#getStatus(id, path)` 这个接口。

**Comment by mzpbvsig** [comment]
就是想知道这个url是否已经下载。 ～ 其实可以由上层逻辑实现的。

**Comment by mzpbvsig** [comment]
还要就是每个task单独start 会不会消耗比多任务消耗更多的资源？

**Comment by Jacksgong** [comment]
不会的，其实如果每个Task都单独启动与一个队列任务并行启动一样的。

一般来说有两个情况可以考虑队列任务下载:

1. 需要使用 `FileDownloadQueueSet` 可以方便队列中的任务批量配置。
2. 需要一个任务接的一个任务串行的下载。

**Comment by mzpbvsig** [comment]
好的，谢谢。
