### ISSUE TITLE
set max download task

### ISSUE THREAD

**Issue by mohamadrezash** [lingochamp/FileDownloader#319]
hi
i want to set one task to max download task
it,s mean when  task 1 is running and i start task 2, then task 2 Go into the queue. and when task 1 finished, task 2 start  Automatically.
Thank you.

**Comment by Jacksgong** [comment]
Okey, FileDownloader has already supported this feature.

1. If you want to download tasks one by one, just start a queue in serial, more detail Ref: [Start downloading task queue](https://github.com/lingochamp/FileDownloader/wiki/Start-downloading#start-downloading-task-queue).
2. If you want to set max download task what you want, just set `download.max-network-thread-count=[max-count]` in [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties).

**Comment by mohamadrezash** [comment]
thanx dear
but i dont undrestand yet,
i have activity like google play app page act, how can i have public  queue? this activity has diffrent url each time. do you get the point?

**Comment by Jacksgong** [comment]
sorry, what is the 'public queue'?

**Comment by mohamadrezash** [comment]
the queue that not bound on activity
it,s mean i can access them from anywhere of activity

**Comment by Jacksgong** [comment]
Okey, You ref [here](https://github.com/lingochamp/FileDownloader/issues/103#issuecomment-209173124).
