### ISSUE TITLE
设置最大下载量问题

### ISSUE THREAD

**Issue by Hao-Kid** [lingochamp/FileDownloader#320]
FileDownloader.getImpl().setMaxNetworkThreadCount(1);
没有起作用,不管设置多少,最大并行下载的数目都是3个,
我是使用单任务下载的.

**Comment by Hao-Kid** [comment]
W/FileDownloader.FileDownloadRunnable: tried to resume from the break point[4410047], but the response code is 412, not 206(PARTIAL).


error:response code error: 412, 
                                                            request headers: If-Match: "57d6616d-65329d"
                                                           Range: bytes=4410047-
                                                           Cache-Control: no-cache
                                                            
                                                            response headers: Server: openresty/1.7.2.1
                                                           Date: Wed, 21 Sep 2016 06:02:27 GMT
                                                           Content-Type: text/html
                                                           Content-Length: 194
                                                           Connection: keep-alive

还有一个问题,报这种错,麻烦问下是什么问题
第一行是默认log,
第二行是Throwable.getMessage()

**Comment by Jacksgong** [comment]
## 设置最大下载量的问题

你看看`FileDownloader.getImpl().setMaxNetworkThreadCount(1)` 的返回值是`true`还是`false`，如果是`false`，看看logcat中的warn级别日志是什么。

## response state code: 412

这个是服务器端返回的，说明服务器侧断点续传失败，你具体问问服务器端为什么会失败，因为客户端完全是按照规范进行处理的。

**Comment by Hao-Kid** [comment]
request set the max network thread count[1] in the download service, but the download service isn't connected yet.
请问我应该在哪里设置最大下载量?

**Comment by Hao-Kid** [comment]
我之前没有使用bindService(void),
请问下这个应该什么时候使用?

**Comment by Jacksgong** [comment]
- `FileDownloader.getImpl().setMaxNetworkThreadCount(1)` 这个其实是运行时设置最大下载数，你的warn日志，说明下载服务还没有启动，因此设置失败（因为这个参数是在下载服务上的）。
- 如果你是需要一启动就是你指定的一个最大下载量，可以在[filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties) 中添加 `download.max-network-thread-count=你想要的数目`，这样默认就是你给的这个值了，这个是静态的数据。

> `bindService()` 这个就是启动并且绑定下载服务，默认如果没有启动，但是启动了下载任务就会自动去调用`bindService()`并且等待连接上服务以后开始下载。如果你希望自己手动启动下载服务，就可以直接调用`bindService()`进行启动，并且你可以通过`addServiceConnectListener`来监听连接启动状态，以及`isServiceConnected`来获知服务是否启动以及连接上。

**Comment by Hao-Kid** [comment]
解决了,谢谢

**Comment by Jacksgong** [comment]
好的。

**Comment by jhwsx** [comment]
Awesome
