### ISSUE TITLE
ava.lang.StackOverflowError?

### ISSUE THREAD

**Issue by yanglichuan** [lingochamp/FileDownloader#321]
#769 Binder_5
java.lang.StackOverflowError
解析原始
}
1 java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:256)
2 java.util.concurrent.LinkedBlockingQueue.offer(LinkedBlockingQueue.java:386)
3 cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:118)
4 cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
5 java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
6 java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
7 cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
8 cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
9 cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
10 java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
11 java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
12 cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
13 cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
14 cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
15 java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
16 java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
17 cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
18 cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
19 cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
20 java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
21 java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
22 cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
23 cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
24 cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
25 java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
26 java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
27 cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
28 cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
29 cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
30 java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
31 java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
32 cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
33 cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
34 cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
35 java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
36 java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
37 cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
38 cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
39 cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
40 java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
41 java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
42 cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
43 cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
44 cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
45 java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
46 java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
47 cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
48 cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
49 cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
50 java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
51 java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
52 cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
53 cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
54 cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
55 java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
56 java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
57 cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
58 cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
59 cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
60 java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
61 java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
62 cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
63 cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
64 cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
65 java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
66 java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
67 cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
68 cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
69 cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
70 java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
71 java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
72 cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
73 cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
74 cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
75 java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
76 java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
77 cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
78 cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
79 cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
80 java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
81 java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
82 cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
83 cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
84 cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
85 java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
86 java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
87 cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
88 cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
89 cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
90 java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
91 java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
92 cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
93 cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
94 cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
95 java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
96 java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
97 cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
98 cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
99 cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
100 java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
101 java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
102 cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
103 cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
104 cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
105 java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
106 java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
107 cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
108 cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
109 cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
110 java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
111 java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
112 cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
113 cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
114 cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
115 java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
116 java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
117 cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
118 cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
119 cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
120 java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
121 java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
122 cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
123 cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
124 cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
125 java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
126 java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
127 cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
128 cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)

**Comment by yanglichuan** [comment]
[Stack over limit size :20000 , has been cutted !]

**Comment by Jacksgong** [comment]
多谢，我认真看下问题所在。

**Comment by jitongkai** [comment]
同样遇到该问题

**Comment by jitongkai** [comment]
在不停切换暂停开始下载操作时，会遇到该问题。

**Comment by chonamdoo** [comment]
http://crashes.to/s/8b7b1e08027

**Comment by Jacksgong** [comment]
@yanglichuan @jitongkai @chonamdoo OK, thank you! I will check this issue tonight.

**Comment by bryant-wang** [comment]
does this issue resolved?

**Comment by Jacksgong** [comment]
@bryant-wang not yet, I will resolve it tonight as soon as possible.

I will close this issue when it is fixed, so you can follow this issue, also welcome request your pull request, if you fix it, thank you.
