### ISSUE TITLE
IOException: open failed 

### ISSUE THREAD

**Issue by vicpinm** [lingochamp/FileDownloader#322]
In version 1.1.0, from demo project.

If I change download path in Single task test (button 1), I get IOException: open failed.

Default download path is /storage/emulated/0/Android/data/com.liulishuo.filedownloader.demo/cache/tmpdir1/LLS-v4.0-595-20160908-143200.apk. 

This path works well. If I change to /storage/emulated/0/LLS-v4.0-595-20160908-143200.apk, for example, I get this exception. 

Tested on a Moto G with android 5.1.

Stacktrace:

java.io.IOException: open failed: EACCES (Permission denied)
09-21 16:21:48.636 17451-17451/com.liulishuo.filedownloader.demo W/System.err:     at java.io.File.createNewFile(File.java:941)
09-21 16:21:48.636 17451-17451/com.liulishuo.filedownloader.demo W/System.err:     at com.liulishuo.filedownloader.services.FileDownloadRunnable.getRandomAccessFile(FileDownloadRunnable.java:859)
09-21 16:21:48.636 17451-17451/com.liulishuo.filedownloader.demo W/System.err:     at com.liulishuo.filedownloader.services.FileDownloadRunnable.fetch(FileDownloadRunnable.java:422)
09-21 16:21:48.636 17451-17451/com.liulishuo.filedownloader.demo W/System.err:     at com.liulishuo.filedownloader.services.FileDownloadRunnable.loop(FileDownloadRunnable.java:364)
09-21 16:21:48.636 17451-17451/com.liulishuo.filedownloader.demo W/System.err:     at com.liulishuo.filedownloader.services.FileDownloadRunnable.run(FileDownloadRunnable.java:220)
09-21 16:21:48.636 17451-17451/com.liulishuo.filedownloader.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
09-21 16:21:48.636 17451-17451/com.liulishuo.filedownloader.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
09-21 16:21:48.636 17451-17451/com.liulishuo.filedownloader.demo W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by Jacksgong** [comment]
#### Yes, That is expected, because of the android permission mechanism: 

If the path you use to store downloading resource is not below the path got from `Context#getExternalCacheDir` or another similar way(`/sdcard/Android/data/<package name>/`), you need to remove `android:maxSdkVersion="18"` which declared below `android.permission.READ_EXTERNAL_STORAGE` and `android.permission.WRITE_EXTERNAL_STORAGE` in the AndroidManifest.xml in demo project
