### ISSUE TITLE
Foreground-Notification does not work after app start

### ISSUE THREAD

**Issue by chriswiesner** [lingochamp/FileDownloader#324]
if i call `FileDownloader.getImpl().startForeground()` for the first time after app start, i get sometimes this:

```
W/FileDownloader.DownloadServiceNotConnectedHelper: request set the download service as the 
foreground service([354],[Notification(pri=2 contentView=null vibrate=null sound=null 
defaults=0x4 flags=0x3 color=0x00000000 actions=1 vis=PRIVATE)]), but the download service 
isn't connected yet.
```

is it necessary to issue the `start()` command of e.g. a `FileDownloadQueueSet` before to make sure the service is started?
currently i call first `startForeground()` as i want to display the notification already, where in the meanwhile i'm fetching the download urls and starting the actual download after i get the download-url response.

if i then issue a second download afterwards, the notification works properly.

**Comment by Jacksgong** [comment]
## Reason:

Through the logcat, the reason is because the filedownloader service isn't bound with the process you invoke `FileDownloader.getImpl().startForeground()`, so it is failed to start foreground service because can't communicate.

## Resolution:

You can use `FileDownloader#isServiceConnected()` to get whether the filedownloader service has been bound with the current process. If not you can use `FileDownloader#bindService()` to bind the filedownloader service manually, meanwhile you can register connect listener through `FileDownloader#addServiceConnectListener(FileDownloadConnectListener)`, and after the filedownloader connected you invoke `FileDownloader#startForeground()` will be work properly.

**Comment by Jacksgong** [comment]
> P.S: When you start a downloading task, and if FileDownloader service isn't bound yet, FileDownloader will bind and start it automatically.

**Comment by chriswiesner** [comment]
so the conclusion is, if i want to start it in foreground before actually starting a download, i have to manually start/bind the service

**Comment by Jacksgong** [comment]
Yep, If the FileDownloader service has not been connected or even started, we can't transmit any message to it.

**Comment by chriswiesner** [comment]
sure, but would it make sense to move the start/binding logic inside `startForeground()` ?
this way, the users don't need to know that they have to have a running service, when they call it.

**Comment by Jacksgong** [comment]
I know, I considered that. But there are some reasons let me hesitate.

1. If do that, this method will no longer simple and flexible.
2. Wrap such logic on the upper layer would be very easy and clearly.
3. We have already considered supporting RxJava in FileDownloader, this pipeline work will be easier to wrap with RxJava.

**Comment by Jacksgong** [comment]
I will add a property key to `filedownloader.properties`: `service.start-foreground` to configure whether start the FileDownloader with `startForeground` as default, to cover your case.

**Comment by Jacksgong** [comment]
Sorry, It does not make sense because `startForeground` need a customize `notification`.........

**Comment by Jacksgong** [comment]
I have an idea to make you do that easier, like below two pattern:

```java
// If the FileDownloader service isn't start and connected yet, will block the thread to start service the connected to it, after connected unblock the thread, and invoke startForeground(Notification); If the FileDownloader service has already started and connected, just invoke startForeground(Notification).
FileDownloader.insureServiceBind().startForeground(Notification):void
// If the FileDownloader service isn't start and connected yet, will start and connecte to it asynchronous and return false, after connected to the service, invoke startForeground(Notification); If the FileDownloader service has already started and connected, just invoke startForeground(Notification) and return true.
FileDownloader.insureServiceBindAsync().startForeground(Notification):boolean
```
