### ISSUE TITLE
请问我弄一份到AS上后报这个错是什么原因啊

### ISSUE THREAD

**Issue by xanaduo** [lingochamp/FileDownloader#325]
Error:(1, 0) Could not initialize class com.android.build.gradle.AppPlugin
<a href="openFile:E:\Xanthium\Project\FileDownloader\demo\build.gradle">Open File</a>

导进去后gradle开始编辑，结果这样了，不知道什么意思。

**Comment by Jacksgong** [comment]
看样子是android的gradle插件加载失败。这个应该和FileDownloader没有关系，建议通过以下途径尝试解决:

- 检查 根目录下的`buld.gradle`文件中 `buildscript`中`dependencies`引用的`com.android.tools.build:gradle`是否正确。
- 重启AS
- 重新Clean Build
- 通过`File->invalidate Caches/Restart...`删除所以已经下载好的依赖。

**Comment by xanaduo** [comment]
好的
