### ISSUE TITLE
关于开启下载的时候add了FinishListener，但是怎么把FinishListener移除掉的问题。

### ISSUE THREAD

**Issue by peerless2012** [lingochamp/FileDownloader#326]
前提，自己封装了一个DownloadManager，单例。

比如开始下载的时候可以add完成的监听，比如下面
    
    public void starDownLoad(Story story){
        FileDownloader
                .getImpl()
                .create(story.getUrl())
                .addFinishListener(mInnerOnFileDownloadFinishListener)
                .setPath(mDownloadPath,true)
                .setTag(story)
                .start();
    }

但是如果程序退出（比如application的onDestroy）的时候，我没有办法把这个listener移除掉。因为移除listener的方法在create方法的返回值上，不在FileDownloader上。

**Comment by Jacksgong** [comment]
是的，因为这个`addFinishListener`就是作用在`BaseDownloadTask`上的(也就是你说的`create`的返回值)，并不是作用在`FileDownloader`上的。

#### 你可以在你的`DownloadManager`中考虑缓存`create`返回值(如: `List<BaseDownloadTask>`):

1. 在`FinishListener`回调的时候，将缓存去掉防止泄漏。
2. 需要`removeFinishListener`的地方进行remove即可。

**Comment by peerless2012** [comment]
```java```
private class InnerOnFileDownloadFinishListener implements BaseDownloadTask.FinishListener{

        @Override
        public void over(BaseDownloadTask task) {
//            task.removeFinishListener(this)
            task.removeFinishListener(mInnerOnFileDownloadFinishListener);
        }
    }

刚大概跟了下，这样写就可以吧。

**Comment by Jacksgong** [comment]
恩。你说的这个也是一个，我说的是:

```
List<BaseDownloadTask> mTaskList = new ArrayList<>();

...

public BaseDownloadTask create(){
  ...
  BaseDownloadTask task = FileDownloader.getImpl().create(url);
  mTaskList.add(task);

  task.addFinishListener(mFinishListener);
  ...

  return task;
}

// 在你说的onDestroy的情况调用。
public void removeAllFinishListener(){
  for (BaseDownloadTask task: mTaskList){
    task.removeFinishListener(mFinishListener);
  }

  mTaskList.clear();
}

private CustomFinishListener mFinishListener = new CustomFinishListener();

private class CustomFinishListener implements FinishListener{
  over(BaseDownloadTask task){
      task.removeFinishListener(this);
      mTaskList.remove(task);
  }
}
```

**Comment by xanaduo** [comment]
请问addFinishListener的作用是什么啊，监听不是有onComplete方法吗？

**Comment by Jacksgong** [comment]
如果没有特殊的需求可以不考虑使用。`FinishListener`相比而言，只是在任务结束时回调，如`error`、`paused`、`warn`、`completed`，并且也不会在UI线程回调。
