### ISSUE TITLE
Files are removed when app is (force) closed

### ISSUE THREAD

**Issue by chriswiesner** [lingochamp/FileDownloader#327]
I have the issue, that recently downloaded files are getting "removed" when i kick the app. (remove the app from recents)

so i start downloading some files. the files are present in their destination directory. then i kick the app and the files are gone in the directory. BUT i have the *.temp version in the destination directory.

i'm using `process.non-separate=true`, could it affect this?

**Comment by Jacksgong** [comment]
nope. `process.non-separate=true` is only used for when you want FileDownloader service running in the main process.

---

I don't understand very clear about your point, If you start downloading some files and files all in the downloading state, they must be in *.temp version, it doesn't care about whether the downloading process is alive. That is it.

**Comment by chriswiesner** [comment]
Maybe i was not clear enough. Files are downloaded correctly (download is
complete). If i kick the app AFTER the download finished, i end up with
.temp files for the last 5-6 Files i downloaded.

Jacksgong <notifications@github.com> schrieb am Fr., 23. Sep. 2016, 17:05:

**Comment by Jacksgong** [comment]
If all downloaded correctly files transmit from "completed" version to *.temp version when you kick the app, that is a bug, but I check this in the demo project, I can't meet it:

1. Enter the "Single task test" Activity
2. Start download "Normal Task", and wait for it finish downloading. After it complete, it settle download in the folder `/sdcard/Android/data/com.liulishuo.filedownloader.demo/cache`, and it's file name is "tmp2" .
3. Start the first one in the "Single task test", and when it is in downloading state, I kick the app.
4. Finally, I find it is expected, there is the "tmp2" file still in the `/sdcard/Android/data/com.liulishuo.filedownloader.demo/cache` folder, and also the "LLS-v4.0-595-20160908-143200.apk.temp" in the `/sdcard/Android/data/com.liulishuo.filedownloader.demo/cache/tmpdir1` folder. 


---

#### After complete download "Normal Task" in "Single task test":

![image](https://cloud.githubusercontent.com/assets/6176417/18805385/fde80be2-823e-11e6-8b81-602bd426b70b.png)

#### After kick the app when "Normal Task" had already completed downloaded, and the first one task in "Single task test" page has been started, and in downloading state now:


![image](https://cloud.githubusercontent.com/assets/6176417/18805706/90949ce6-8247-11e6-808f-7ab1e08b3854.png)

**Comment by chriswiesner** [comment]
it doesn't apply for all files. i downloaded 30 files in parallel and 5-6 (i guess the most recent downloaded) of those have this issue.

i checked the download directory and all files were properly stored. (so no *.temp files). but if i kick the app then, these recent downloads get somehow "renamed" to their *.temp version

i will try to setup a demo project

**Comment by Jacksgong** [comment]
Okey, thanks. Wait for your testing result in the demo project.

And welcome PR, if you find any problem and fix it.

**Comment by chriswiesner** [comment]
i'm sorry. it seems that it wasn't related to the library. cannot reproduce it any longer. 
therefore no issue here.

**Comment by Jacksgong** [comment]
Okey.
