### ISSUE TITLE
为啥经常无响应？

### ISSUE THREAD

**Issue by liangnansheng** [lingochamp/FileDownloader#328]
:filedownloader I/dalvikvm: Wrote stack traces to '/data/anr/traces.txt' 尤其是网络不好的时候

**Comment by liangnansheng** [comment]
其他情况也会 经常发生。。。

**Comment by Jacksgong** [comment]
你是指ANR吗？是什么操作导致的？FileDownloader中有几类线程池，几乎所有的操作都不是在主线程上执行的，甚至都不是在主进程。

**Comment by Jacksgong** [comment]
或者你提供下traces.txt文件我看以下，谢谢。

**Comment by Jacksgong** [comment]
我这边并没有出现，可否提供下`/data/anr/traces.txt`文件给我分析下。

**Comment by Jacksgong** [comment]
@liangnansheng 由于我这边做压测的时候无法复现类似的情况。你提供'/data/anr/traces.txt'以后，我重新打开这个issue。
