### ISSUE TITLE
请问任务管理器的形式，如果页面滑动的时候是否需要移除监听呢？

### ISSUE THREAD

**Issue by xanaduo** [lingochamp/FileDownloader#330]
根据#4 的Demo来看，Activity的onDestroy的时候会移除监听，那如果是RecyclerView的话，每点击一个他下载按钮就得添加一个监听，但如果当页面滑动的时候，ViewHolder被回收复用了，我这个时候是否需要对上面的监听进行移除，如果是这样的话回来的时候继续添加监听对吧？

**Comment by Jacksgong** [comment]
复用相关的属于上层的代码架构，其实都可以很灵活的设计，其中一个方案就是结合`TasksManagerDemoActivity`中的方案，一个列表就共用一个`FileDownloadListener`。
