### ISSUE TITLE
你好，请问这个项目支持多任务单回调的形式吗？

### ISSUE THREAD

**Issue by a483210** [lingochamp/FileDownloader#331]
你好，请问这个项目支持多任务单回调的形式吗？
就是是多个任务只有一个开始和结束，
progress返回的[soFarBytes, totalBytes]为所有任务的总和？

**Comment by Jacksgong** [comment]
可以参考下[这里](https://github.com/lingochamp/FileDownloader/issues/126#issuecomment-214096879)。

**Comment by a483210** [comment]
谢谢
