### ISSUE TITLE
请问：列表已有的下载任务，再次添加，会删除旧的，重新开始么

### ISSUE THREAD

**Issue by corymail** [lingochamp/FileDownloader#332]
如题

**Comment by Jacksgong** [comment]
> FileDownloader 中区别两个任务是否是相同任务是根据三个参数: `下载连接`&`存储路径`&`存储路径是否是目录`，可以参考:`FileDownloadUtils#generateId`。

#### 假如有两个相同的任务A 与任务B:

- A正在下载中，此时B被启动，此时B会直接收到`warn`的回调。
- A已经下载完成，此时B被启动，此时B会直接回调`blockComplete`->`completed`。
- A已经下载完成，此时B被设置`BaseDownloadTask#setForceReDownload(true)`，此时B会从头开始下载。
