### ISSUE TITLE
demo跑步起来，一个最最简单的问题我却无可奈何

### ISSUE THREAD

**Issue by qssq** [lingochamp/FileDownloader#334]
Error:(1, 0) Could not initialize class com.android.build.gradle.AppPlugin
<a href="openFile:C:\Users\Administrator\Downloads\FileDownloader-master\demo\build.gradle">Open File</a>

**Comment by qssq** [comment]
那种插件没用过。 我复制粘贴我自己项目gradle的终于搞定了，但是还是有问题

Error:(33, 47) 错误: 找不到符号
符号:   变量 DOWNLOAD_NEED_LOG
位置: 类 BuildConfig
Error:(44, 28) 错误: 找不到符号
符号: 类 OkHttpClient

Error:(46, 43) 错误: 程序包OkHttpClient不存在
demo还是缺东西了。

**Comment by qssq** [comment]
终于搞定了，不容易。啊

**Comment by qssq** [comment]
哥们qq多少 青椒 listview 方案 各种ui交互的。我之前用爱哥的 他的不是所有的请求都有回调结果所以 后面出现了很多ui进度bug

**Comment by Jacksgong** [comment]
这个不是demo的bug，demo项目一直都是没有问题的。如果你将 `com.android.tools.build:gradle`根据IDE的建议升级到`2.2.0`了，你就要确保在你的环境中有`2.2.0`，否则就会找不到AppPlugin插件。

**Comment by qssq** [comment]
嗯。

**Comment by Jacksgong** [comment]
有问题建议直接提Issue即可，我会尽量第一时间更进的。这样也方便别人遇到问题的时候可以直接在Issue中找到答案。

**Comment by qssq** [comment]
嗯，谢谢大神 ，有机会教教我，探讨下怎么实现 多线程加入后台下载 下载列表显示进度，在线音乐 视频列表显示是否已下载状态，还有一些 json数据绑定在一起图文并茂的显示  类似视频下载音乐下载  。我现在愁死了这个项目。 不知道怎么架构最完美 。

**Comment by Jacksgong** [comment]
多任务进度相关的，可以简单参考下demo project中的[TasksManagerDemoActivity.java](https://github.com/lingochamp/FileDownloader/blob/cb04c77cf5e4aba42bcdab1ab77966325d2d341c/demo/src/main/java/com/liulishuo/filedownloader/demo/TasksManagerDemoActivity.java)。

架构方面，你根据你的需求，可以先了解清楚具体业务需要的接口，然后再尽量功能单一的划分模块，然后一一攻克即可。一些思想方面的你可以参考下[这里](https://blog.dreamtobe.cn/2016/03/09/oo_architecture/)。

**Comment by qssq** [comment]
好的，谢谢  但是 ， 我发现你那个 是 前台下载的，我那个是后台下载通知前台的哦 。   现在我快乱套了，还是请列出多线程暂停 取消 继续 永久暂停的方法吧，我怕乱一乱 就没效率 不知道如何是好了。 那个demo写的太多信息了。一层套一层 。全是封装 。

**Comment by Jacksgong** [comment]
demo已经尽量简单了。无论前台后台都一样，FileDownloader没有和任何的组建绑定。里面也有Notification的案例。

#### 你说的这些简单的使用，建议先按照一下方法处理:

> 接口都是很简单的，没有什么难点，我相信你可以的。

1. 快速过一遍README文档，或者Wiki。
2. 实在不清楚可以在README文档中进行搜索。
