### ISSUE TITLE
我快疯了，完全不知道怎么用您的框架放到我的服务里做下载

### ISSUE THREAD

**Issue by qssq** [lingochamp/FileDownloader#335]
请问多线程下载  暂停的方法是啥？
继续的方法是啥 ？
永久移除队列 也就是以后不继续下载了，彻底清除的方法是啥？
多线程下载的方法是啥？
根据id删除 id获取的方法是啥。

**Comment by qssq** [comment]
看了demo 写了太多代码了，我不知道怎么看起。。。信息量太大， 还是简要说明简单的写法比较好。

**Comment by Jacksgong** [comment]
你可以先看下[README-zh](https://github.com/lingochamp/FileDownloader/blob/master/README-zh.md) 或 [Wiki](https://github.com/lingochamp/FileDownloader/wiki)。

**Comment by Jacksgong** [comment]
- 暂停相关可以看 `FileDownloader#pause` 与 `BaseDownloadTask#pause`，暂停以后内存当中就没有相关数据了，会将用于断点续传的数据存储在数据库中。
- 暂停以后，默认情况下就是断点续传的。哪怕是重新创建一个任务。
- 永久删除一个任务，默认情况下下载完成该任务就会被删除，否则可以通过 `FileDownloader#clear`方法永久删除一个任务。
- 下载不用关系是否是多线程，默认就是在不同的线程下载的，默认情况下还是在另外一个进程。
- 根据id，可以直接获取该任务的进度、状态，也可以进行暂停等操作，相关可以查看`FileDownloader.java`。如果要启动一个任务直接`FileDownloader.getImpl().create`创建一个`start`就行，如果已经存在了相同的任务(id相同，id的生成可以参看`FileDownloadUtils#generateId`)，后一个任务会收到`warn`回调。

**Comment by Jacksgong** [comment]
可以先不要看那个Manager，先看看其他的几个简单的demo，使用起来很简单。

**Comment by qssq** [comment]
那么 我加入了多个任务 ，我这需要把FileDownloader.getImpl().创建后的对象存起来吗？ 因为 我 这是后台下载，可能滑动了几下 ，然后我发送一个消息给服务，服务可能出现正在下载的情况和没有下载的情况   那么正在下载的情况   我 也需要调用FileDownloader.getImpl().create（）吗?您这个和爱哥的那个下载框架有点不同，设计的很好，我作为初学者看起来有点晕，乱套了， 我现在是服务里面吧所有的回调 存起来比较好  还是应该吧所有创建的对象存起来 ，然后发送信息控制？ 在爱哥的那个下载框架我是吧所有回调存起来， 因为那里面没有create（）方法 只需要根据回调控制相应的功能。

**Comment by qssq** [comment]
看了一下clear方法 是根据 本地路径和id清除的那么这样说的话 没下载完成之前我就应该吧本地路径也存到数据库啊。本来是打算当 下载完成您的回调给我然后我更新数据库的本地字段的。。现在看来不能这么做咯？

**Comment by qssq** [comment]
如果从来没有 下载过的情况 调用pause()方法会怎么样 - -

**Comment by qssq** [comment]
我有种不祥的预感 create 返回了一个base*** 然后才能调用start()那么 我这需要存起来 才行啊不然从前台发送到后面没法控制呀。

**Comment by Jacksgong** [comment]
- `FileDownloader.getImpl()`是一个单例，不用单独存储。
- 正在下载的情况，如果你要获取其状态，可以参考`TasksManagerDemoActivity`中的做法，通过`FileDownloader`去获取状态。
- 上层的设计还是自己设计，你只要将这个库当做是一个简单的下载库就行了，简单的调用也work，如果有复杂的需求，看看文档基本也都可以支持，很灵活。
- 默认`FileDownloadListener`中的回调时会在ui线程执行，如果你是在后台服务，没有这个需求，可以通过`BaseDownloadTask#setSyncCallback(true)`，这样回调不在ui线程，但是由于少了线程切换回调更加及时些。 
- 通常情况下你是不用`clear`的，因为下载完成了，或者对应文件被删除了之类的FileDownloader自己会维护删除内部数据，你不用担心里面数据太多之类的问题，一般情况下，你只需要`start`与`pause`就行了(`pause`就已经释放所有内存中的数据了，之所以称为pause是因为下次启动默认或断点续传)。
- 如果从来没有下载过, 调用`pause`会打出一个warn级别的logcat，没有任何多余的操作。
- 你的最后一个问题我不是很理解。


> FileDownloader是十分稳定可靠的。考虑了各种各样的异常情况，包括多进程的回收等等情况。demo中我一般都是就上千个任务在混合测试中混合测试的，一般情况下你只要充分信任接口描述就行。

**Comment by Jacksgong** [comment]
上层通常不需要缓存其 `BaseDownloadTask`对象，要的话就存储其Id即可，因为`BaseDownloadTask`在下载过程中，是一直在变化中的对象。

如果是队列下载，可以参看下`FileDownloadQueueSet`便于批量配置。

**Comment by Jacksgong** [comment]
都有源码，建议多看看。里面绝大多数的接口，我都有写了java-doc，建议直接参看里面的java-doc，有问题也可以先在issue中搜索下，然后再提问题，这样会更加高效。

**Comment by qssq** [comment]
FileDownloader.getImpl().start(,)后面调用那为什么直接用   public boolean start(final FileDownloadListener listener, final boolean isSerial) { 我看到这个就吓到我了 后面那个参数必须设置，  - - 另外 那么 还有一个 create()又是咋回事 ，既然是单例模式 那么 是不是只需要create()一次？

**Comment by qssq** [comment]
希望可以想爱哥那个框架一样 有一个非常简单的用法 ，太多信息量 让我晕头转向的。

**Comment by qssq** [comment]
不过他那个框架不是所有 调用 都有回调结构 ，所以我为了做获取暂停 继续操作结果做的更完美一点  才尝试换一个框架。  - -

**Comment by Jacksgong** [comment]
`FileDownloader.java`的对象是单例，这个是FileDownloader的入口；

---

希望你能够留意下接口上的java-doc，`FileDownloader#start`是用于启动队列任务，而`FileDownloader#create`是创建一个任务。


---

FileDownloader的接口已经十分的简单，如果你能稍微看一眼[Wiki](https://github.com/lingochamp/FileDownloader/wiki)，或者是README-doc，或者是demo的话你就会十分明白`FileDownloader#start`与`FileDownloader#create`的差别。

**Comment by Jacksgong** [comment]
目前这个库全球有超过几万的aar下载量，全球至少有几百家公司在使用，稳定性方面以及实用性方面应该是可以放心的。

如果你有更好的建议，十分欢迎提出以及PR，不过十分建议你不用心急，先看看Wiki与README文档，或者是接口java-doc，这些都是为我们花了很多时间写了，就是为了解决你提出来的这些问题的。谢谢。

**Comment by qssq** [comment]
好的，谢谢大神  主要是信息量大 我搞混了，我只想要我简单的那条 下载

**Comment by qssq** [comment]
文档我真的看了 ，但是还是没理解呀creates是创建一个下载任务 ，能不能智能呢？ 有时候我并不知道到底有没有在下载，如果 直接调用 start（）就好了  还有 start（）我并不知道到底有没已经调用 过 。

**Comment by qssq** [comment]
一个 为task 一个 为filedownloader 我真的不知道到底2个 的start()存在什么关系，内部的结构 我不知道怎么去理解，希望告诉我 就像这个一样 ，https://github.com/AigeStudio/MultiThreadDownloader/wiki/%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95 根据 地址开始 根据 地址 结束 ，由于您那个是根据id来的 ，我是先把地址转 文件地址 然后文件地址转id已经很麻烦了还不知道我这么做是不是对的，然后 就是 移除任务的 需要根据 文件的本地路径和id才能删除 我又懵逼了，如果一个start()参数包含多个配置我感觉还方便一些 ，那种 链式编程就是让我 搞不懂到底哪些参数是需要哪些是不需要的了，比如create() 这个东西 ， 是不是启动app如果要进行下载就一定要调用create()呢 ， 我就单纯的想下载   和暂停下载 永远移除 下载这3个功能而已 。 爱哥的就是不是所有 都能回调，所以才考虑换新的得。您那个 就是 对我我这种不懂设计模式的  真的有难度了 。  信息多   有很多 疑问。

**Comment by Jacksgong** [comment]
> FileDownloader无论里面多复杂，都是上层尽量简单灵活。

- [下载](https://github.com/lingochamp/FileDownloader/wiki/Start-downloading)。
- [暂停](https://github.com/lingochamp/FileDownloader/wiki/Pause-or-Stop)。
- 永久删除: 1. 内部自动不用理会；2. 外部调用(`FileDownloader#clear`)

---

不过如果你有更好的选择也挺好的，但是，FileDownloader本身对上层的使用，并没有任何的设计模式可言，这库可以非常简单的使用，也可以非常灵活的应付复杂需求，谢谢。

**Comment by qssq** [comment]
恩 ，我 又看了 一遍您的回答 ， 感觉里面很多隐藏的设计 ，但是 还是不知道 我有种不祥的预感 create 返回了一个base*对象 然后这个对象可以调用start() 空参数方法，而不create（）发现 又可以调用start() 2个参数的方法，所以这里懵逼呢，请大神教我正确的使用方法。 。  是这样的 我做了个ibinder  然后里面有一个  startDownload(url)  pauseDownload(url) 当 调用start()我首先 判断 集合里面是否有您那个回调，集合中没有的话 就是 oncreate().onstart() 那么有的话 说明已经加入下载队列了，这个 oncreate()返回的对象我又没存起来 只能直接掉那个 oncreate()所属类的onstart()2个参数的方法了。

**Comment by qssq** [comment]
可以告诉我联系方式嘛,我真的不知道该怎么弄呢。

**Comment by qssq** [comment]
看过一个 iqq开源项目 ，也是写的精妙绝伦但是我这种水平的人 都不知道怎么入手去升级这个项目 。  但是 很多大神就知道是怎么架构的。

**Comment by qssq** [comment]
我现在是这样写的，还没有测试 ,ui那边绑定了服务之后调用者2个方法。 

`
  public boolean continueDownload(String url, IResultCallBack callBack) {
            if (mDownloadMaps.get(url) != null) {
                FileDownloader.getImpl().start(mDownloadMaps.get(url), false);
                callBack.onSucc();
                return true;
            } else {
                callBack.onFail("抱歉,下载队列中并没有存在此数据");
                return false;
            }

        }

        @Override
        public boolean startDownload(String url, IResultCallBack callBack) {
            if (url == null) {
                callBack.onFail("地址错误");
                return false;
            }
            FileDownloadListener fileDownloadListener = mDownloadMaps.get(url);
 /*           LocalMusicInfo info = dbUtils.queryByColumn(LocalMusicInfo.class, "", url);
            if (info == null || isEmptyFiled(info.getLocalurl())) {
                BaseDownloadTask baseDownloadTask = FileDownloader.getImpl().create(url);
                taskDownloadListener
                baseDownloadTask.addFinishListener(new)
                //只有下载完成的才保存到数据库里面去？

            }*/
            if (fileDownloadListener == null) {

                //创建数据
                int id = urlToId(url);
                LocalMusicInfo queryFromDb = dbUtils.queryByID(LocalMusicInfo.class, id);
                if (queryFromDb == null) {
                    queryFromDb = new LocalMusicInfo();
                    queryFromDb.setNeturl(url);
                    long insert = dbUtils.insert(queryFromDb);
                    if (insert > 0) {
                        if (mDownloadMaps.get(url) != null) {
                            callBack.onFail("数据库不存在，但是下载队列已存在");
                            return false;
                        }
                        MyFileDownloadListener dListener = new MyFileDownloadListener();
                        dListener.setInfo(queryFromDb);
                        mDownloadMaps.put(url, dListener);
                        FileDownloader.getImpl().create(url).setListener(dListener).start();
                        Log.i(TAG, "下载新数据");
//                    iNotify.onNotify(Pair.create(true, "加入下载队列 成功"));
                    } else {
                        callBack.onFail("抱歉,数据库出现错误" + insert);
                        return false;
//                    dListener.setIdListener(null);
                    }
                }
            } else {
                callBack.onSucc();
                Log.i(TAG, "继续下载");
                FileDownloader.getImpl().start(fileDownloadListener, false);

            }
            return false;
        }
`

**Comment by qssq** [comment]
不知道写没写错 。服务里面的开始方法 上面发的有点乱 ，就是第一次下载和后面下载的 ，第一次 就是判断 集合里面有没有 ，请问写错了没有呢？
`
        @Override
        public boolean startDownload(String url, IResultCallBack callBack) {
            if (url == null) {
                callBack.onFail("地址错误");
                return false;
            }
            FileDownloadListener fileDownloadListener = mDownloadMaps.get(url);
            if (fileDownloadListener == null) {
                //创建数据
                int id = urlToId(url);
                LocalMusicInfo queryFromDb = dbUtils.queryByID(LocalMusicInfo.class, id);
                if (queryFromDb == null) {
                    queryFromDb = new LocalMusicInfo();
                    queryFromDb.setNeturl(url);
                    long insert = dbUtils.insert(queryFromDb);
                    if (insert > 0) {
                        if (mDownloadMaps.get(url) != null) {
                            callBack.onFail("数据库不存在，但是下载队列已存在");
                            return false;
                        }
                        MyFileDownloadListener dListener = new MyFileDownloadListener();
                        dListener.setInfo(queryFromDb);
                        mDownloadMaps.put(url, dListener);
                        FileDownloader.getImpl().create(url).setListener(dListener).start();
                        Log.i(TAG, "下载新数据");
                    } else {
                        callBack.onFail("抱歉,数据库出现错误" + insert);
                        return false;

                    }
                }
            } else {
                callBack.onSucc();
                Log.i(TAG, "继续下载");
                FileDownloader.getImpl().start(fileDownloadListener, false);

            }
            return false;
        }`

**Comment by qssq** [comment]
public static boolean isEmptyFiled(String filed) {
                          if (filed == null || filed == "" || filed == "null") {
                        return true;
                    } else {
                        return false;
                    }
                            }
            
                public static int urlToId(String url) {
                          return FileDownloadUtils.generateId(url, FileDownloadUtils.getDefaultSaveRootPath());
                }

**Comment by qssq** [comment]
由于是下载界面更新listview recyclerview，所以 我想不到什么好的方法。 就是每一个下载任务都有一个 监听每个监听都发送 事件过去，那边有一个方法受到监听 就 寻找列表中id等于 这个的，然后一个一个notifyitem 。。。。自己也觉得写得不好，可是后台更新前台到底改怎么写呢？

              @Override
                          protected void started(BaseDownloadTask task) {
                  super.started(task);
                     Log.i(TAG, "started " + info.getTitle());
                        DownloadEvent downloadEvent = new DownloadEvent(info);
                  downloadEvent.setType(DownloadEvent.TYPE.START);
                  downloadEvent.setArg1(task.getSmallFileTotalBytes());
                  if (EventBus.getDefault().hasSubscriberForEvent(DownloadEvent.class)) {
                      EventBus.getDefault().post(downloadEvent);
                  }
              }
