### ISSUE TITLE
对比使用Advanced Download Manager Pro专门下载的软件，建议加入多线程多段同时下载

### ISSUE THREAD

**Issue by 10045125** [lingochamp/FileDownloader#337]
具体情况如下：
在使用Advanced Download Manager Pro的提前开申请磁盘内容大小后，ADM在多线程下载中速度表现非常稳定和快速。
所以下载框架能不能够加入多线程下载？

**Comment by Jacksgong** [comment]
关注这个Issue即可 #102 ，后面抽空会实现的，谢谢。

**Comment by Jacksgong** [comment]
已经支持分块下载，参考 https://github.com/lingochamp/FileDownloader/issues/102#issuecomment-306016976 近期版本会带上。

**Comment by Jacksgong** [comment]
我这边测试可以跑满我家100Mb/s的宽带: https://github.com/lingochamp/FileDownloader/issues/102#issuecomment-306044546
