### ISSUE TITLE
从taskdemo里面看 每次点击开始都 是同一个监听,我现在要弄的就是注册不同监听

### ISSUE THREAD

**Issue by qssq** [lingochamp/FileDownloader#338]
但是每次调用开始就设置监听 好像不太好呀。能不能只设置一次呢。 后面只需要调用开始方法就行了。     final BaseDownloadTask task = FileDownloader.getImpl().create(model.getUrl())
                            .setPath(model.getPath())
                            .setCallbackProgressTimes(100)
                            .setListener(taskDownloadListener);

                    task.start();

**Comment by qssq** [comment]
因为我是每一个 监听 继承类都维护一个 model的.然后eventbus吧model发送到前台界面。

**Comment by Jacksgong** [comment]
如果你希望每次点击都注册不同的监听，就直接注册不同的监听就行了。你甚至可以自己全局管理自己的下载，可以参考 [这里](https://github.com/lingochamp/FileDownloader/issues/4#issuecomment-168692266) 或 [这里](https://github.com/lingochamp/FileDownloader/issues/103#issuecomment-209173124)。

**Comment by qssq** [comment]
唉，贵框架写的太复杂，我还是用爱哥那个简单的工具类比较实在。

**Comment by qssq** [comment]
final int status = FileDownloader.getImpl().getStatus(id, pathByUrl);
        if (status == FileDownloadStatus.pending || status == FileDownloadStatus.started ||
                status == FileDownloadStatus.connected) {
            // start task, but file not created yet
            Log.i(TAG, "没有创建" + url);
            return DownloadState.STATE_DOWNLOADFINSIH;
//            return DownloadState.STATE_NOT_DOWNLOAD;
//            return DownloadState.STATE_NOT_DOWNLOAD;
        } else if (!new File(pathByUrl).exists() &&
                !new File(FileDownloadUtils.getTempPath(pathByUrl)).exists()) {
            Log.i(TAG, "文件不存在应该没下载" + url);
            // not exist file
            return DownloadState.STATE_NOT_DOWNLOAD;
        } else if (status == FileDownloadStatus.completed) {
            Log.i(TAG, "下载完成了" + url);

**Comment by qssq** [comment]
请问task demo里面的第二句话 是否是错误的呢 ，第二句话是判断临时文件 和 我设置的路径 是否 都不存在,那么 我已经调用start()方法了，结果 还是不存在 。然后  获取状态的时候结果读取的是这个了。

**Comment by qssq** [comment]
非常抱歉，我之前是一直没测试 ，所以在写架构的时候非常烦躁，因为没测试的情况下真的不理解到底 这个和那个什么区别，这样做到底可不可以，感觉测试出真理，暂时感觉还不做，我已经把 在线音乐列表的已下载状态完成了。

**Comment by Jacksgong** [comment]
恩，如果没有测试，并且你用过类似的工具库，并且将它接口的思想直接套用到FileDownloader中，这样来使用一个新的东西，难度确实有点大。

可能学习FileDownloader对于你这种情况来说，确实不是很适合，考虑到你的时间消耗，可以考虑看看通过你之前使用的库，这样可能更有益于你的项目更近。

FileDownloader的接口已经十分简单了，不过我们后面会考虑在wiki当中针对一些复杂情况再写一些简单的案例。并且会对上层接口做一些优化，以及guideline。

很感谢你的使用。谢谢了。
