### ISSUE TITLE
请问pauseAll()是同步请求吗

### ISSUE THREAD

**Issue by qssq** [lingochamp/FileDownloader#339]
我的意思是 调用pauseAll() ->调用 pause()回调 我这边的dbutils.update 保存进度到本地  然后dbutils.close()  如果是异步的话 那么dbutils就报错了哈

**Comment by Jacksgong** [comment]
不好意思，我不是很理解你说的dbutlis.update的意思，不过你也不用解释的。

对于FileDownloader而言，`pauseAll`是同步的请求。但是`FileDownloadListener#paused`默认是异步的回调（因为默认情况下是会抛到UI线程的Looper中的）。

**Comment by qssq** [comment]
那 我应该如何解决 在 服务停止后  保存下载任务里面的 进度呢?

**Comment by qssq** [comment]
在service 的onDestory()走了之后, 停止 所有下载 并 把 我写的dbutils的 数据库链接关闭, 但是 停止后我想把进度保存到数据库中去。 我是自己单独维护了一个 bean 存到数据的。

**Comment by qssq** [comment]
dbutils关闭了但是 停止方法回调给我也没用了，又不是同步请求，莫非我需要重新打开一次再关闭，但是这么多下载 但是下载队列中这么多 ，我 也不可能都这么写。

**Comment by Jacksgong** [comment]
恩。我明白你的意思了。先`FileDownloader#pauseAll`，然后通过遍历你存储的所有任务：通过`FileDownloader#getSofar` 或者 `BaseDownloadTask#getSoFarBytes` 获取其进度进行存储即可。

**Comment by qssq** [comment]
或者 有没有 非异步请求的方法 （主线程） 根据 地址查询进度 这样 可以一定程度保存一些进度 虽然不是非常准确的。 这样的话ondestory(）后我可以 先查询出下载队列中所有的 进度 并存起来然后close()这样就保证完全不会出现 下次app启动产生进度为0的情况。

**Comment by qssq** [comment]
嗯。我试试

**Comment by qssq** [comment]
那么我这样是不是正确的写法呢？         
      @Override
               public void onDestroy() {
                   super.onDestroy();
                   FileDownloader.getImpl().pauseAll();
                   for (Map.Entry<String, MyFileDownloadListener> entry : mDownloadMaps.entrySet())                                                              {
                                  int idByUrl = getIdByUrl(entry.getKey());
                       long totalBytes = FileDownloader.getImpl().getTotal(idByUrl);
                       long soFarBytes = FileDownloader.getImpl().getSoFar(idByUrl);
                       int currentProgress = (int) ((soFarBytes / (float) totalBytes) * 100);
                       LocalMusicInfo info = entry.getValue().getInfo();
                       info.setProgress(currentProgress);
                       dbUtils.update(LocalMusicInfo.class,"progress");
                   }
                   dbUtils.close();
               }

**Comment by Jacksgong** [comment]
恩。这样也可以。

**Comment by qssq** [comment]
嗯，好的谢谢，我现在差不多写好了就是我后台更新前台是一个一个遍历，实在想不出什么绑定view接口的方法呢 -  -

**Comment by Jacksgong** [comment]
不过，考虑到性能的优化，由于`FileDownloader#getTotal`与`FileDownloader#getSoFar`默认情况下涉及到IPC，所以如果没有特殊必要，可以考虑通过在[filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)中配置`process.non-separate=true`。

---

还有一个要注意的，就是如果文件已经下载完成，你通过`FileDownloader#getSoFar`与`FileDownloader#getTotal`会收到0，因此你可以先判断下目标文件是否存在，不存在再这样去取。

**Comment by qssq** [comment]
嗯。好的，前面不太懂，不过谢谢了ipc是什么鬼-   进程通讯。

**Comment by Jacksgong** [comment]
是的。默认情况下FileDownloader自己的一个服务FileDownloadService是运行在独立的进程中的。但是可以通过在`filedownloader.properties`中配置让它不用运行在独立进程。

**Comment by qssq** [comment]
.FileDownloader: Tasks with the listener can't start, because can't find any task with the provided listener: [com.buyao.tv.service.DownloadService$MyFileDownloadListener@23a153d5, FALSE]这是怎么回事呢？
