### ISSUE TITLE
find any task with the provided 

### ISSUE THREAD

**Issue by qssq** [lingochamp/FileDownloader#340]
暂停了之后再次开始 必须create().start() 直接 filedownloder.start()报错。 不调用create不行

**Comment by qssq** [comment]
正在下载的 为何获取状态还是0？     String pathByUrl = getPathByUrl(url);
        final int status = FileDownloader.getImpl().getStatus(id, pathByUrl);

**Comment by qssq** [comment]
只有下载完成的判断文件是否存在的方法正确的，其他度不行 。无法获取正在下载的状态state

**Comment by qssq** [comment]
没有 设置路径 create().strat()和     return FileDownloadUtils.getDefaultSaveFilePath(url); 相等吗?   不然我不知道为什么 状态获取获取不到了。   id和 那个都是根据 这个方法。

**Comment by qssq** [comment]
可是还是获取不到啊，一直是0

**Comment by qssq** [comment]
我 最后 用第二个方法貌似正确了。。

**Comment by qssq** [comment]
请问这是为什么呢 ，id我也是通过 那个方法获取的，url也是 结果 我不得不放弃这个方法，用url和 url转本地路径方法。 而且 奇怪的是 没下载完成 那个 文件竟然存在？

**Comment by qssq** [comment]
理论上 这个路径不应该存在的呀   final int status = FileDownloader.getImpl().getStatus(url, getPathByUrl(url));
        if (status == FileDownloadStatus.pending || status == FileDownloadStatus.started ||
                status == FileDownloadStatus.connected) {
            // start task, but file not created yet
            Log.i(TAG, "state:没有创建" + url);
            return DownloadState.STATE_DOWNLOADFINSIH;
//            return DownloadState.STATE_NOT_DOWNLOAD;
//            return DownloadState.STATE_NOT_DOWNLOAD;
        } else if (new File(pathByUrl).exists()) {
            Log.i(TAG, "state:已下载完成" + url);
            // not exist file
            return DownloadState.STATE_DOWNLOADFINSIH;
        } else if (status == FileDownloadStatus.completed) {
            Log.i(TAG, "state:下载完成了" + url);
            return DownloadState.STATE_DOWNLOADFINSIH;
            // already downloaded and exist
        } else if (status == FileDownloadStatus.progress) {
            Log.i(TAG, "state:正在下载" + url);
            // downloading
            return DownloadState.STATE_DOWNLOADING;
        } else {

**Comment by Jacksgong** [comment]
是的，每次你只要重新 create，然后启动就行，内部会自动处理断点续传，就是为了简化上层的工作。

----

如果你的获取的状态不符合预期，你留意下你的logcat，是否有输出warn的日志。
