### ISSUE TITLE
360网盘下载必然失败，错误码514，但是UC和QQ浏览器能够正常下载。是不是OKHTTP的问题？

### ISSUE THREAD

**Issue by 10045125** [lingochamp/FileDownloader#341]
response code error: 514, 
                                                                request headers: Cache-Control: no-cache
                                                                
                                                                response headers: Server: nginx
                                                               Date: Fri, 30 Sep 2016 08:49:15 GMT
                                                               Content-Type: text/plain;charset=utf-8
                                                               Content-Length: 0
                                                               Connection: keep-alive
                                                               errno: 1001
                                                               errmsg: param invalid
                                                               OkHttp-Sent-Millis: 1475225354344
                                                               OkHttp-Received-Millis: 1475225354424
                                                               , url=http://dl85.yunpan.360.cn/intf.php?method=Download.downloadFile&qid=2772885398&fname=%2FScreenshot_20160930-121324.png&fhash=66f287402630e384a4d9f6438539913b81293187&dt=85_85.8295710036bd3bfd232185833e3c8923&v=1.0.1&rtick=14752241554737&open_app_id=0&devtype=web&sign=039a002352af10661b62a5b772db18f6&})

**Comment by Jacksgong** [comment]
5xx的错误都是 服务器端那边发生的错误。根据response code error，来判定是 服务器端 发生了错误导致。

---

如果是你在UC或者QQ浏览器可以正常下载，你可以看看是否和session有关，或者你可以用debug工具看看他们的请求头是什么，在FileDownloader中也添加对应的请求头试试。

**Comment by 10045125** [comment]
应该是有些下载站点需要cookie信息，将网页中存储的cookie添加到头部就OK。

**Comment by Jacksgong** [comment]
恩。Okey.
