### ISSUE TITLE
create a dowload queue

### ISSUE THREAD

**Issue by miladz68** [lingochamp/FileDownloader#345]
I want to create a download queue which downloads tasks one after the other. for example I start downloading a file and in the middle I order FileDownloader to download another file, I want the second file to go to queue and get downloaded after the first file is finished downloading.

How can I implement this ?

**Comment by Jacksgong** [comment]
There are two ways to achieve:

1. Set the count of global network threads to 1: `download.max-network-thread-count=1` in [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties) or `FileDownloader.getImpl().setMaxNetworkThreadCount(1)`.

2. Implement your own download manager or copy the [FileDownloadSerialQueue](https://github.com/lingochamp/FileDownloader/commit/ac59705522529245664242497aea8fe6def22755) which will be released in 1.3.0.

**Comment by miladz68** [comment]
thank you for your patient answer.

I tried to use the second way that you suggested. I called this code and an exception raised:

`FileDownloadSerialQueue queue = new FileDownloadSerialQueue();`

**Comment by Jacksgong** [comment]
Sorry about that, I fix the problem you issued, please copy the new code of `FileDownloadSerialQueue` again to fix it.

**Comment by 947000711** [comment]
FileDownloadSerialQueue  这个类应该如何使用呢 ? 我现在同时多个队列任务,max-network-thread-count=1.    出现的情况是 一个队列下载一会然后暂停 ,另一个队列会开始下载 这样循环 ,  我想一个队列一直保持下载 除非我暂停 .

**Comment by Jacksgong** [comment]
> 一个队列下载一会然后暂停 ,另一个队列会开始下载 这样循环 

这个暂停是你主动促发的吗？我不是很理解你的问题。

`max-network-thread-count=1`了以后，全局就只有一个网络线程池，无论你有多少个队列，都是串行的下载序列。

**Comment by 947000711** [comment]
是串行下载,但是如果我有2个队列同时下载的话 , 我想要的是一个队列下完整以后 再开始另外一个队列 , 现在是2个队列会交叉下载,(一个队列下载完某个任务会进入pending,然后另一个队列的任务会开始下载这样循环)

**Comment by Jacksgong** [comment]
@947000711 好的，我明白了。`max-network-thread-count=1`确实只能保证单网络线程池，但是由于队列之间是孤立的，因此确实存在你所描述的这种现象。

FileDownloader目前的版本也是支持你所说的这种情况的（不需要设置`max-network-thread-count=1`）:

创建串行队列任务A(简称: 串A)，与串行队列任务B((简称: 串B)。

这边要做的就是，串A的最后一个任务添加上`FinishListener`监听串A任务结束，在串A的最后一个任务结束以后再启动串B即可。

**Comment by 947000711** [comment]
1.3 新增的这个类 FileDownloadSerialQueue 完全不知道怎么用啊, 跟 FileDownloadQueueSet 类一起配合使用吗?

**Comment by Jacksgong** [comment]
@947000711 不用配合使用，创建`FileDownloadSerialQueue`对象以后使用即可。

你可以留意代码上面的注解，如:

```
/**
  * Enqueues the given task sometime in the serial queue. If the {@code task} is in the head of
  * the serial queue, the {@code task} will be started automatically.
  */
 public void enqueue(BaseDownloadTask task) {
     ...
 }
```

根据代码注解，进入队列，当所提供的队列在队列头的时候，就会自动被启动。

**Comment by yuqizi** [comment]
利用FileDownloadSerialQueue下载过程中，我应该怎样获取下载状态（包括正在下载的和在队列中等待下载的）

**Comment by Jacksgong** [comment]
@yuqizi 由于是串行任务，正在下载的任务就只有一个 `FileDownloadSerialQueue#getWorkingTaskId`。

我增加一个接口来获取，正在等待中的任务个数。

**Comment by Jacksgong** [comment]
@yuqizi 这个新的方法(`getWaitingTaskCount`)会在[1.4.2](https://github.com/lingochamp/FileDownloader/milestone/14)中会带上去。

**Comment by yuqizi** [comment]
@Jacksgong 如果我在不同的activity中，向FileDownloadSerialQueue队列中添加了若干个下载任务，我如何在一个新的activity中获取的当前正在下载的任务的信息（如进度、速度）以及等待下载的任务列表？
PS：即实现一个下载任务的查看管理界面

**Comment by Jacksgong** [comment]
@yuqizi FileDownloader本身没有和Activity耦合，如果你要做下载管理，可以参考下这个: https://github.com/lingochamp/FileDownloader/issues/103#issuecomment-209173124

**Comment by ximencx** [comment]
how to use this library download m3u8 url??
