### ISSUE TITLE
使用replaceListener方法替换监听后，回调的进度soFarBytes数据不对！

### ISSUE THREAD

**Issue by liang530** [lingochamp/FileDownloader#346]
使用FileDownloader.getImpl().replaceListener(tasksManagerModel.getId(),downloadListener);替换监听后，进度soFarBytes不对，开启日志后可以看到这个数据比日志打出来的要小！新开启的下载任务再不替换监听的情况下进度信息和日志输出是一致的！

**Comment by liang530** [comment]
L.e(TAG,"下载中："+task.getId()+"  进度："+soFarBytes+"--> "+totalBytes);
L.e(TAG,"下载中："+task.getId()+"  进度："+task.getLargeFileSoFarBytes()+"--> "+task.getLargeFileTotalBytes());

输出：
com.liulishuo.filedownloader.DownloadTask@6f186ba 20419965 171687944
Progress ] 下载中：222948621  进度：15316029--> 171687944
#Progress ] 下载中：222948621  进度：20419965--> 171687944

**Comment by Jacksgong** [comment]
可能我不是很明白你的意思，不是很清楚你的日志是加在哪里，导致不一致。

####不过根据你提出来的，我可以明确两点:

1.  从源代码看，`replaceListener` 这个接口，仅仅只是替换了 `mListener` 这个监听器对象，对于内部逻辑没有因此做任何特殊的处理。
2. 会影响Listener回调到达的，只有内部防止回调过于频繁的 分包、分时回调机制，可以通过 `FileDownloader.disableAvoidDropFrame()` 禁用该机制。
