### ISSUE TITLE
In 1.2.0, If you don't provide the FileDownloadListener to the task, you can't receive FileDownloadMonitor.IMonitor#onTaskOver callback when the task is finished

### ISSUE THREAD

**Issue by liang530** [lingochamp/FileDownloader#348]
升到1.2.0之后你改掉了notifyCompleted的回调判断，不设置下载监听，连全局Monitor的成功回调都没了！！！！我说之前还是好好的，看了下源码发现改了！

**Comment by Jacksgong** [comment]
源码都在那里，如果是能够找到原因，也十分欢迎修改PR，我这边的话，要等国庆以后，回去再看看。

**Comment by Jacksgong** [comment]
非常感谢你提出的bug，我看了下代码，确实如果没有设置监听，全局Monitor的`onTaskOver`就不会被回调到，我会在明晚release的补丁版本，将这个问题修复。

**Comment by Jacksgong** [comment]
Sorry for my mistake, this problem is still exist.

**Comment by Jacksgong** [comment]
我将会在明天，1.2.2版本中确保这个问题得到修复。

**Comment by liang530** [comment]
嗯，希望这个框架越来越好！

**Comment by Jacksgong** [comment]
谢谢。
