### ISSUE TITLE
断点续传问题

### ISSUE THREAD

**Issue by ayou6232290** [lingochamp/FileDownloader#35]
断点续传只有eTag判断么? ,现在我们cdn有个问题, ETAG标识一直返回空, 所以断点续传一直失败,但是我用浏览器下载此文件,是可以断点续传的

**Comment by pengjianbo** [comment]
@ayou6232290 大部分CDN都支持ETag断点下载。开始我们的也是不支持ETag,后来后台人员简单的弄一下就可以了

**Comment by Jacksgong** [comment]
@pengjianbo :+1:

**Comment by Jacksgong** [comment]
ETag是文件下载的基本属性，也是一个公共协定，ETag支持有条件请求，以及辨别当前断点cache所保留的ETag是否有效（如请求指定要下载的文件区间，断点续传基本的要求），目前我也没有更好的方案。

PS: 绝大多数CDN供应商都会有ETag支持的（如七牛之类的）。

**Comment by nukc** [comment]
@Jacksgong 不知道这个issues是否能帮到你：https://github.com/Aspsine/MultiThreadDownload/issues/45
我这有很多链接ETag都是NULL，所以并不能断点续传，但是MultiThreadDownload可以（但目前并不稳定），我转而使用FileDownloader。

**Comment by Jacksgong** [comment]
@nukc 多谢啦，我抽空认真看下。

**Comment by Jacksgong** [comment]
Fixed in [v0.2.1](https://github.com/lingochamp/FileDownloader/releases/tag/v0.2.1).
