### ISSUE TITLE
任务管理器中最多只支持同时下载3个任务吗？

### ISSUE THREAD

**Issue by jettyang** [lingochamp/FileDownloader#353]
超过3个的任务就需要排队？可支持跟多任务同时下载吗？

**Comment by Jacksgong** [comment]
- 支持脚本配置(#116): `download.max-network-thread-count` in [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties).
- 支持动态配置(#168): `FileDownloader#init`中传入，或者`FileDownloader#setMaxNetworkThreadCount`
