### ISSUE TITLE
设置多个监听

### ISSUE THREAD

**Issue by wman0211** [lingochamp/FileDownloader#356]
我在A页面create一个下载并添加了FileDownloadNotificationListener监听, 增加了通知栏通知显示.
此时切换到B页面(文件管理器页面) , 此页面包含所有A页面添加的task ,  我希望能给B页面的每一个task额外增加一个监听来做一些UI上的交互 .

当前使用replaceListener来切换监听会导致通知栏的通知死掉
能否把setListener 改为 addListener 或者指点实现方法 ?

**Comment by Jacksgong** [comment]
参考这里: https://github.com/lingochamp/FileDownloader/issues/4#issuecomment-168692266

**Comment by Jacksgong** [comment]
参考这里: https://github.com/lingochamp/FileDownloader/issues/4#issuecomment-168692266

**Comment by Jacksgong** [comment]
参考这里: https://github.com/lingochamp/FileDownloader/issues/4#issuecomment-168692266

**Comment by Jacksgong** [comment]
参考这里: https://github.com/lingochamp/FileDownloader/issues/4#issuecomment-168692266

**Comment by Jacksgong** [comment]
参考这里: https://github.com/lingochamp/FileDownloader/issues/4#issuecomment-168692266

**Comment by Jacksgong** [comment]
参考这里: https://github.com/lingochamp/FileDownloader/issues/4#issuecomment-168692266

**Comment by Jacksgong** [comment]
参考这里: https://github.com/lingochamp/FileDownloader/issues/4#issuecomment-168692266

**Comment by Jacksgong** [comment]
参考这里: https://github.com/lingochamp/FileDownloader/issues/4#issuecomment-168692266
