### ISSUE TITLE
暂停的任务如何再次启动？

### ISSUE THREAD

**Issue by jettyang** [lingochamp/FileDownloader#358]
在您的demo中暂停的任务再次启动你是调用的
FileDownloader.getImpl().create(url)
                        .setPath(path, isDir)
                       .start();
方法，这样不又创建了一个任务吗？
我将已经开启的任务保存起来，试着将暂停的任务调用start(),报错，说任务已启动

**Comment by mzpbvsig** [comment]
reuse()
start()

**Comment by Jacksgong** [comment]
考虑到下载的特殊性（如可能下载过程中，应用被kill，或者其他情况）任意任务，无需存储对应的对象进行resuem，只要重新创建启动，FileDownloader会根据存储路径以及下载链接判断该新建的任务是否可以断点续传，如果可以默认就会断点续传。

当然如果你不希望某个任务被断点续传，你也可以通过`FileDownloader#clear`对其进行清除（对应数据也会在任务下载完成后，或者内部维护发现无法断点续传时自动清除）。
