### ISSUE TITLE
Listener duplicate call from filedownloader process

### ISSUE THREAD

**Issue by yuraj11** [lingochamp/FileDownloader#36]
First time when `start` is called - connected in listener has been fired two times from main application process and then from filedownloader process. Second time `start` works as intended. But when you do Force stop in App info, you can simulate this again.
```
//download file
int downloadId = FileDownloader.getImpl()
    .create(...)
    .setPath(...)
    .setListener(mQueueTarget)
    .setTag(...).ready();
//start downloading parallel
FileDownloader.getImpl().start(mQueueTarget, false);
```

mQueueTarget listener:
```
@Override
protected void connected(BaseDownloadTask task, String etag, boolean isContinue, int soFarBytes, int totalBytes) {
    Log.d("DownloadService.connected()", " Etag " + etag + ", pid " + android.os.Process.myPid());
}

...
```
Also other listener overriden methods like progress are called twice (causes problems on UI)
Log output:
```
02-26 12:58:55.800 D/DownloadService.connected(): at Etag "56cfffaf-22a7f", pid 26967
02-26 12:58:55.801 D/DownloadService.connected(): at Etag "56cfffaf-22a7f", pid 26473
```

It looks like FileDownloader.init(this) will duplicate Application class on first download (Application onCreate will be called again while main process still exists, I do not want reinitialize all libraries etc. in onCreate).

Temporary fix we have applied:
```
<service
    android:name="com.liulishuo.filedownloader.services.FileDownloadService"
    tools:remove="process" />
```

**Comment by Jacksgong** [comment]
Thank you for such a detailed feedback.

----

> Application onCreate will be called again while main process still exists.

Application onCreate will be called when one process is launching,  So it is ok for FileDownloader.init(this) will be called twice. one by the main(UI) process, another by the `:filedownloader` process, that is what FileDownloader want. ( And in normally, the `:filedownloader` progress will launch when start is called first time and main process has already launched.)

---

> First time when start is called - connected in listener has been fired two.

I tried in the FileDownloader demo project but didn't occur such problem. and couldn't output such log. Could you change the code in the FileDownloader demo project to the repetition of this problem?

---

> First time when start is called - connected in listener has been fired two times from main application process and then from filedownloader process.

I'm very confusion for the descriptions given by you. If you set the FileDownloadListener in main(UI) Process, it impossible be accessed by other processes.

---

Maybe I misunderstood you mean, so could you please provide your sample project which can output the following log(by Github, or Gmail), I will check it very carefully.

```
02-26 12:58:55.800 D/DownloadService.connected(): at Etag "56cfffaf-22a7f", pid 26967
02-26 12:58:55.801 D/DownloadService.connected(): at Etag "56cfffaf-22a7f", pid 26473
```
