### ISSUE TITLE
队列下载过程中是否可以在该队列中增加/移除任务

### ISSUE THREAD

**Issue by AllenMeex** [lingochamp/FileDownloader#360]
我试了下，直接create一个新任务，然后enqueue()，这个任务会和之前的任务队列作为两个队列并列执行，是否可以向已存在的队列中增加一个新任务呢？

**Comment by Jacksgong** [comment]
如果是并行的任务，你只要直接运行，默认就是与其他任务并行的，你也可以自己封装一层，比较简单。

如果是动态的串行任务队列，会在1.3.0中带上，你可以关注下这个Issue: #345
