### ISSUE TITLE
如何在url变化之后，还能断点续传？

### ISSUE THREAD

**Issue by wangsuicheng** [lingochamp/FileDownloader#362]
我能取得文件的md5，这个应该不会变，url是动态的，间隔只有几个小时。谢谢~~~

**Comment by Jacksgong** [comment]
目前，url改变了就无法支持断点续传了。

这里有一个问题就是，使用什么作为断点续传的依据。因为文件的md5也是在文件下载结束以后，我们得到完整的文件才去做md5，才知道他的md5是多少的。

相关这个问题，可以到这个Issue中评论: #231 欢迎有更好的解决方案。
