### ISSUE TITLE
不执行下载就无法获取sofar和total的问题(同#182)

### ISSUE THREAD

**Issue by wman0211** [lingochamp/FileDownloader#364]
请您帮忙看看这个问题
如题 同 #182 相同的问题, 但是我们需要动态的资源路径, 有什么办法能让我获得sofar和total ?
试过在服务端加一个静态的url重定向到真实的动态url, 但是并没有效果

**Comment by Jacksgong** [comment]
你可以参考下这个: https://github.com/lingochamp/FileDownloader/issues/324#issuecomment-248889564

看完以后，你可以通过以下几个接口来简化流程:

- `FileDownloader.insureServiceBind()`
- `FileDownloader.insureServiceBindAsync()`
- `FileDownloader.bindService(Runnable)`

**Comment by wman0211** [comment]
感谢  先执行绑定服务  然后监听绑定成功状态然后再获得soFar等数据
不过您说的简化流程是指 ?

**Comment by Jacksgong** [comment]
恩。我这里说的简化流程的意思是，通过上面的几个方法，写起来会更加方便，比如 `FileDownloader.insureServiceBind()` 这个可以阻塞住当前线程，当服务连接上了再处理对应的命令。更多的细节，建议直接看看对应方法上的注解。

**Comment by wman0211** [comment]
谢谢   这下载框架很棒   对比其他github上我所知的下载文件工具  您这个可以算作框架  其他的只能叫做工具类

**Comment by Jacksgong** [comment]
谢谢~

**Comment by BinarySatan** [comment]
不执行下载还是没有办法 获取到数据总大小。
