### ISSUE TITLE
Question: Using Cached File to Resume Download

### ISSUE THREAD

**Issue by farbod-s** [lingochamp/FileDownloader#368]
I'm using proxy to cache live streaming, i want to use this cached file for continuing download process  with FileDownloader library. how can i do that?
i appreciate that any kind of help.

**Comment by Jacksgong** [comment]
Okey, If you want the OkHttpClient which is used in FileDownloader access the resource through the proxy, just customize it through [OkHttpClientCustomMaker ](https://github.com/lingochamp/FileDownloader/blob/master/demo/src/main/java/com/liulishuo/filedownloader/demo/DemoApplication.java#L50).
