### ISSUE TITLE
Support throw non-RuntimeException in the callback method: FileDownloadList#blockCompleted

### ISSUE THREAD

**Issue by wangsuicheng** [lingochamp/FileDownloader#369]
想问下，如果支持的话，需要怎么配置？谢谢~~

**Comment by Jacksgong** [comment]
恩。可以在 `FileDownloadListener#blockCompleted`的地方直接做 md5 校验（我们自己也是这样做），如果校验失败了直接抛一个`Exception`:

1. `blockCompleted` 就是在独立线程中执行的
2. `blockCompleted` 回调的时候已经下载完成
3. 在`blockCompleted`中抛`Exception`会自动回调到`error`中。

> 我们自己的项目中也是在`blockCompleted`中校验的。

**Comment by wangsuicheng** [comment]
意思就是说如果在blockCompleted中抛出异常，就走error不走Completed这个回调了吧？

**Comment by Jacksgong** [comment]
> 意思就是说如果在blockCompleted中抛出异常，就走error不走Completed这个回调了吧？

是的。

---

如果抛出的异常非`RuntimeException`或其子类的`Exception`的话，是需要强制处理的。在3.0版本中我会对这个支持。

---

目前的解决方案: 你捕捉到以后将其转为 `RuntimeException`或其子类的Exception抛出即可。
