### ISSUE TITLE
下载过程中，杀掉进程，再重新进入程序下载，进度不对

### ISSUE THREAD

**Issue by TyrionCN** [lingochamp/FileDownloader#371]
我下载一个文件20%几后，杀掉进程；然后重新进入应用程序下载，发现进度是从10%开始的，请问这是什么原因？

**Comment by Jacksgong** [comment]
考虑到性能，这边是一个取舍的过程，目前同步数据库以及强制固化进度到本地是根据以下两个参数:

- `download.min-progress-time`
- `download.max-network-thread-count`

可以进行动态配置: [filedownloader.properties-中文文档](https://github.com/lingochamp/FileDownloader/blob/master/README-zh.md#filedownloaderproperties)，[filedownloader.properties-wiki](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties).

**Comment by Jacksgong** [comment]
其实，下载过程中，进程被杀掉，这个是小概率事件，因此这里是一个妥协的点，这两个参数越大，下载速度会更快，因为一次吞吐的数据变大，下载速度受限系统的CPU、IO资源减少。

**Comment by TyrionCN** [comment]
这个不是小概率事件啊，比如在应用商店正在下载更新很多应用，但是用户这时一键杀掉所有进程，这时下载就停止了，下次启动应用商店，肯定要接续上次的进度下载的，从flyme系统来看，做这个是很正常的操作

**Comment by Jacksgong** [comment]
Okey, 在你的需求中，需要在后台下载，并且不将下载服务设置为前台服务(`FileDownloader#startForeground`)，在后台被杀死确实是很有可能。

FileDownloader默认就是做了这块的保护，也就是默认情况下，即便是进程被杀了，下一次开始也可以从之前下载的过程中断点续传。这里你需要注意的，默认情况下我们确保这个情况与系统保持同意，下载大于2s，并且大于65536byte，我们才会强制sync一次。并且这个值是可配置的，如果你希望你希望即便是进程被意外杀了，下次也是0误差的断点续传，就将这两个配置值调为0。

**Comment by Jacksgong** [comment]
或者你可以稍作配置，比如你希望误差不超过8192byte，你就将 `download.min-progress-time`配置为0，将`download.min-progress-step`设置为8192即可。
