### ISSUE TITLE
下载过程中，杀掉进程，再重新进入应用程序，怎么进入程序后，下载自动重连

### ISSUE THREAD

**Issue by TyrionCN** [lingochamp/FileDownloader#372]
如题，不管我的应用之前是被杀掉还是退到后台了，我都需要在进入应用的时候继续之前的下载，请问我该如何做？

**Comment by Jacksgong** [comment]
如果是某个任务重试次数，可以参看: `BaseDownloadTask#setAutoRetryTimes`。

如果是希望自动重新启动所有任务，这边希望上层自己去管理根据上层feature挂钩的任务即可，这块的疑惑可以通过这里获知: #347

---

如果是需要一个动态的串行任务队列，可以参考 #345
