### ISSUE TITLE
你好,我想知道M3U8这种格式的文件怎么下载?

### ISSUE THREAD

**Issue by 947000711** [lingochamp/FileDownloader#374]
目前我把解析出来的链接放在一个串行队列里面,但是多个任务时,我怎么让一个任务一直保持下载状态,暂停和恢复下载

**Comment by Jacksgong** [comment]
> 目前我把解析出来的链接放在一个串行队列里面

这个我理解的。

> 多个任务时,我怎么让一个任务一直保持下载状态,暂停和恢复下载

这个我不是很理解，多任务 与 某一个任务一致保持下载状态 有什么关系？

**Comment by 947000711** [comment]
就是我怎么管理这个队列任务 和 单个任务 一样,如果我现在有2个队列 ,max-network-thread-count=1 .这2个任务会出现 : 一个队列任务下完其中一个task , 然后pending , 另外一个队列会开始下载 , 我现在想其中一个队列一直下完,除非我暂停,

**Comment by 947000711** [comment]
还有就是,我怎么删除一个队列的任务呢 ? 一个hls文件里可能又上千个小任务, 我恢复 , 暂停 , 删除 这些操作要怎么做呢 ? 有没有什么好的建议啊 . 如果出现进程后台被清掉时 , 怎么恢复这样一个队列任务呢 ?  如果可以直接下载M3U8这种格式的就好了,

**Comment by Jacksgong** [comment]
> 就是我怎么管理这个队列任务 和 单个任务 一样,如果我现在有2个队列 ,max-network-thread-count=1 .这2个任务会出现 : 一个队列任务下完其中一个task , 然后pending , 另外一个队列会开始下载 , 我现在想其中一个队列一直下完,除非我暂停

这个 串行任务动态管理 参考: #345 

> 我怎么删除一个队列的任务呢 ?

FileDownloader中，是根据不同的Task绑定相同的`FileDownloadListener`，将其关联起来。

比如，需要 暂停/删除 所有绑定了`targetListener`(`FileDownloadListener`实例)的任务，只需要执行: `FileDownloader.getImpl().pause(targetListener)`。

队列任务的创建与批量配置也可以通过辅助类: `FileDownloadQueueSet`。

> 一个hls文件里可能又上千个小任务, 我恢复 , 暂停 , 删除 这些操作要怎么做呢 ? 

demo中的混合测试也是几千个任务一起测试的，你可以clone下来看看。

- 恢复，就重新创建Task实例然后start，默认是自动断点续传的。
- 暂停，就执行`BaseDownloadTask#pause`，或者知道它的id，通过`FileDownloader.getImpl().pause(id)`即可；如果需要暂停所有运行中的任务，通过`FileDownloader.getImpl().pauseAll()`即可。暂停以后，内存中就清理了左右必要的数据，只有数据库中存有一点数据用于下一次断点续传使用。
- 删除，也就是说需要创建相同任务启动的时候，不再断点续传，调用`FileDownloader.getImpl().clear(id, path)`即可。

> 出现进程后台被清掉时 , 怎么恢复这样一个队列任务呢 ?

默认情况下FileDownloader就是支持的，也就是说，如果下载的时候突然进程被杀了，那么下次创建相同任务，FileDownloader会保证尽可能的从上次下载过程中恢复（这块的误差调整，可以参考: https://github.com/lingochamp/FileDownloader/issues/371#issuecomment-254746479）。

如果希望下载服务进程不被杀，可以考虑使用: `FileDownloader.getImpl().startForeground`，使下载服务成为前台服务。


---

> 代码对每个类与方法都有详细的注解，可以直接通过阅读注解了解更多方法的功能。

**Comment by 947000711** [comment]
在 progress(BaseDownloadTask task, int soFarBytes, int totalBytes)回调里接收到状态为FileDownloadStatus.completed 的回调信息,是正常的吗

**Comment by xiandao** [comment]
你好，我也是遇到了这样的问题，我也是做m3u8 下载的，遇到很多的坑，目前我的做法是 每次 暂停，重新启动再创建 一堆 task ,但是特别耗费资源，我还担心老的task 会不会有内存泄露的问题，请你是怎么做的

**Comment by Jacksgong** [comment]
@947000711

内部是有对这样的流进行控制，应该是没有这种问题的。如果你是一个高并发的下载，并且都公用同一个Listener，应该有可能是不同的任务的回调。

**Comment by Jacksgong** [comment]
@947000711

内部是有对这样的流进行控制，应该是没有这种问题的。如果你是一个高并发的下载，并且都公用同一个Listener，应该有可能是不同的任务的回调。

**Comment by Jacksgong** [comment]
@947000711

内部是有对这样的流进行控制，应该是没有这种问题的。如果你是一个高并发的下载，并且都公用同一个Listener，应该有可能是不同的任务的回调。

**Comment by Jacksgong** [comment]
@947000711

内部是有对这样的流进行控制，应该是没有这种问题的。如果你是一个高并发的下载，并且都公用同一个Listener，应该有可能是不同的任务的回调。

**Comment by Jacksgong** [comment]
@947000711

内部是有对这样的流进行控制，应该是没有这种问题的。如果你是一个高并发的下载，并且都公用同一个Listener，应该有可能是不同的任务的回调。

**Comment by Jacksgong** [comment]
@947000711

内部是有对这样的流进行控制，应该是没有这种问题的。如果你是一个高并发的下载，并且都公用同一个Listener，应该有可能是不同的任务的回调。

**Comment by Jacksgong** [comment]
@947000711

内部是有对这样的流进行控制，应该是没有这种问题的。如果你是一个高并发的下载，并且都公用同一个Listener，应该有可能是不同的任务的回调。

**Comment by Jacksgong** [comment]
@947000711

内部是有对这样的流进行控制，应该是没有这种问题的。如果你是一个高并发的下载，并且都公用同一个Listener，应该有可能是不同的任务的回调。

**Comment by Jacksgong** [comment]
@947000711

内部是有对这样的流进行控制，应该是没有这种问题的。如果你是一个高并发的下载，并且都公用同一个Listener，应该有可能是不同的任务的回调。

**Comment by Jacksgong** [comment]
@947000711

内部是有对这样的流进行控制，应该是没有这种问题的。如果你是一个高并发的下载，并且都公用同一个Listener，应该有可能是不同的任务的回调。

**Comment by Jacksgong** [comment]
@947000711

内部是有对这样的流进行控制，应该是没有这种问题的。如果你是一个高并发的下载，并且都公用同一个Listener，应该有可能是不同的任务的回调。

**Comment by Jacksgong** [comment]
@xiandao 

FileDownloader对于多任务并发下载，还是很稳定的，我们自己也是这样类似的使用场景，也是一次几百个任务下载，只不过在调优的时候，如果可以忽略每一个单个任务自己的`progress`回调，可以考虑`BaseDownloadTask#setCallbackProgressIgnored()`，这样可以减少这块回调时的额外CPU/IO的消耗。

对于泄露而言，对于某个任务只要是结束了，内部就会进行释放，是不存在泄露的问题的。这点你可以放心。

**Comment by 947000711** [comment]
@xiandao 我的需求是当前时间只下载一个任务 , 我就自己维护了一个列表 ,一个一个下载 ,只用Filedownloader的下载部分 ,其他全部自己在外层搞 . 参考 #4 的downloadmanager ,自己改下,基本上就可以了
