### ISSUE TITLE
怎么让下载线程sleep，来达到限速的效果？

### ISSUE THREAD

**Issue by lengyue524** [lingochamp/FileDownloader#376]
我尝试调用setSyncCallback(true)，
在 progress中让线程sleep来达到限速的效果。
但是我发现不起作用，progess好像与下载线程是异步的，好像是通过消息机制来调用的。

有没有其他的方法能够使下载线程睡眠？

我没有仔细看源码，看表象setSyncCallback(true)只是让消息通知的线程同步了。
下载的线程是一个service吧？看来要限速，要进行源码级的修改了。

仔细看了下文档，发现了outputStreamCreator。
但是没找到怎么使用- -
怎么自定义流处理？

**Comment by Jacksgong** [comment]
`setSyncCallback`实际上是让回掉在 回调线程 中执行（而不直接抛到主线程），而真正的下载是在网络线程，默认情况下还是在下载进程中的网络线程。

---

OutputStreamCreator，如果你需要自定义，可以参考目前[已有的几个类](https://github.com/lingochamp/FileDownloader/tree/master/library/src/main/java/com/liulishuo/filedownloader/stream)，方法上面我已经写了所有的注解了，你可以对照看看；

> 说实话你直接在OutputStream直接阻塞线程确实有用，只不过有点hack的感觉。

----

不过关于限速这块，已经在预计需要开发中了，只不过目前还没有排出时间开发，你可以关注下: #156

**Comment by lengyue524** [comment]
@Jacksgong 爬了下源码，发现自定义流，会让所有下载的任务限速，我想做到只限速一个下载任务。
有没有什么思路呢？
感谢！

**Comment by lengyue524** [comment]
好像我只能在任务启动前自定义参数
FileDownloadHelper.initializeDownloadMgrParams(initCustomMaker);
pending的时候再
FileDownloadHelper.initializeDownloadMgrParams(null);

**Comment by Jacksgong** [comment]
OutputStreamCreator，你可以根据传入的路径，来判定是否是需要限速的任务。
