### ISSUE TITLE
百分网下载链接，下载存在问题，具体问题是下载不到源文件，而是一个错误文件

### ISSUE THREAD

**Issue by 10045125** [lingochamp/FileDownloader#377]
url="http://web.dl.byfen.com/app/201631/1470281368903.apk", refUrl="http://a.byfen.com/", contentDisposition="attachment;filename="/app/201631/1470281368903.apk"", mimetype="application/octet-stream"

**Comment by Jacksgong** [comment]
这个不是FileDownloader的问题。

有可能需要在请求头中添加相关的校验，FileDownloader支持添加自定义请求头。

---

我在firebox中直接访问该连接(http://web.dl.byfen.com/app/201631/1470281368903.apk)，直接302重定向到: android.byfen.com ：

<img width="806" alt="screen shot 2016-10-25 at 8 30 25 am" src="https://cloud.githubusercontent.com/assets/6176417/19668854/52859686-9a8d-11e6-81dd-682b2e116d43.png">

**Comment by 10045125** [comment]
我这边设置了cookie,UA,Content-Type,Content-Disposition这些还是不能进行下载，从信息来看，mimetype="application/octet-stream"是一个流形式，不知道你那边有没有解决办法，我试过ADM，我直接拷贝下载地址，ADM还是能够下载

**Comment by Jacksgong** [comment]
这个应该是服务端的问题，或者是你与服务端那边协定的对接的问题。对于FileDownloader来说，就是建立连接，如果输入流中有内容，就直接取回，无论`mimetype`是什么。

---

PS: 我不是很清楚ADM是什么，你用ADM，然后抓包看看请求头，以及返回头，有什么不同。

**Comment by 10045125** [comment]
ADM 是一个java实现的下载App，其大小1.63MB,全称：Advanced Download Manager Pro，目前版本是5.1.2

**Comment by Jacksgong** [comment]
多谢你推荐这么好的软件，我回头会看看一些可取的点，以优化FileDownloader，

针对你这个问题，我刚刚抓包了下。
ADM发了两个请求，第一个 http://web.dl.byfen.com/app/201631/1470281368903.apk，返回也一样，是302重定向了。
于是ADM发起了第二个请求，在头部加入了`Referer`，值为`http://web.dl.byfen.com/app/201631/1470281368903.apk`，就可以了。

---

介于此，你这个资源的下载，你可以尝试通过下面的方式解决这个问题:

```
task.addHeader("Referer", "http://web.dl.byfen.com/app/201631/1470281368903.apk");
```

**Comment by Jacksgong** [comment]
添加头以后，问题如果得到解决，回来答复下。

**Comment by Jacksgong** [comment]
我测试了下，已经可以了。

这个是由于"百分网"，对请求做了安全校验，需要来源（referer）是来自已知的这个地址的。因此这里mock了下就可以了。

**Comment by Jacksgong** [comment]
我已经将这个案例添加到Wiki中了: https://github.com/lingochamp/FileDownloader/wiki/Can't-download-for-some-Urls%3F

之后还有类似的问题欢迎提出。

**Comment by 10045125** [comment]
thanks,希望FileDownloader下载模块越来越优秀
