### ISSUE TITLE
com.liulishuo.filedownloader.i.IFileDownloadIPCService$Stub$Proxy.unregisterCallback(IFileDownloadIPCService.java:220)

### ISSUE THREAD

**Issue by xiaomeixw** [lingochamp/FileDownloader#38]
02-29 10:54:51.798    8463-8463/com.cleverm.smartpen W/System.err﹕ android.os.DeadObjectException
02-29 10:54:51.798    8463-8463/com.cleverm.smartpen W/System.err﹕ at android.os.BinderProxy.transactNative(Native Method)
02-29 10:54:51.798    8463-8463/com.cleverm.smartpen W/System.err﹕ at android.os.BinderProxy.transact(Binder.java:496)
02-29 10:54:51.798    8463-8463/com.cleverm.smartpen W/System.err﹕ at com.liulishuo.filedownloader.i.IFileDownloadIPCService$Stub$Proxy.unregisterCallback(IFileDownloadIPCService.java:220)
02-29 10:54:51.798    8463-8463/com.cleverm.smartpen W/System.err﹕ at com.liulishuo.filedownloader.FileDownloadServiceUIGuard.unregisterCallback(FileDownloadServiceUIGuard.java:66)
02-29 10:54:51.798    8463-8463/com.cleverm.smartpen W/System.err﹕ at com.liulishuo.filedownloader.FileDownloadServiceUIGuard.unregisterCallback(FileDownloadServiceUIGuard.java:35)
02-29 10:54:51.798    8463-8463/com.cleverm.smartpen W/System.err﹕ at com.liulishuo.filedownloader.services.BaseFileServiceUIGuard.releaseConnect(BaseFileServiceUIGuard.java:99)
02-29 10:54:51.798    8463-8463/com.cleverm.smartpen W/System.err﹕ at com.liulishuo.filedownloader.services.BaseFileServiceUIGuard.onServiceDisconnected(BaseFileServiceUIGuard.java:93)
02-29 10:54:51.798    8463-8463/com.cleverm.smartpen W/System.err﹕ at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:1208)
02-29 10:54:51.798    8463-8463/com.cleverm.smartpen W/System.err﹕ at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1222)
02-29 10:54:51.798    8463-8463/com.cleverm.smartpen W/System.err﹕ at android.os.Handler.handleCallback(Handler.java:739)
02-29 10:54:51.798    8463-8463/com.cleverm.smartpen W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:95)
02-29 10:54:51.798    8463-8463/com.cleverm.smartpen W/System.err﹕ at android.os.Looper.loop(Looper.java:135)
02-29 10:54:51.798    8463-8463/com.cleverm.smartpen W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5221)
02-29 10:54:51.798    8463-8463/com.cleverm.smartpen W/System.err﹕ at java.lang.reflect.Method.invoke(Native Method)
02-29 10:54:51.798    8463-8463/com.cleverm.smartpen W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:372)
02-29 10:54:51.798    8463-8463/com.cleverm.smartpen W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
02-29 10:54:51.798    8463-8463/com.cleverm.smartpen W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by Jacksgong** [comment]
多谢。

**Comment by xiaomeixw** [comment]
@Jacksgong Thanks~~~

**Comment by Jacksgong** [comment]
Fixed in [v0.2.1](https://github.com/lingochamp/FileDownloader/releases/tag/v0.2.1).
