### ISSUE TITLE
https的文件链接下载不了

### ISSUE THREAD

**Issue by sohandsome1** [lingochamp/FileDownloader#380]
下载的文件链接是这样的https://60.190.238.184:28015/outside_download?key=102485922c0b1009/update.apk，但是下载不了，提示信息是这样的org.wlf.filedownloader.listener.OnDetectUrlFileListener$DetectUrlFileFailReason: url file does not exist !。。。。。。但是我把这个链接放在电脑浏览器进行下载，是下载的了的。。。是哪里配置出现问题，，还是不支持下载https链接的文件

**Comment by Jacksgong** [comment]
FileDownloader目前使用Okhttp，是**支持`Http`以及`Https`协议**的。

我这边直接在demo project中测试你提供的连接下载是**没有任何问题**的。

> 挺奇怪的，我扫了一遍代码，你贴出来的这个提示，并不是FileDownloader输出的。

**Comment by jarvan11** [comment]
你好，我遇到了同样的问题，请问你解决了吗？
下载https的文件报错：E/FileDownloader.FileDownloadList: remove error, not exist: -1117771318@com.liulishuo.filedownloader.FileDownloadTask@929e3ef

**Comment by jarvan11** [comment]
已经解决。解决方法：FileDownloader.init(getAppContext());初始化方法必须放在Application的onCreate()方法里面。
