### ISSUE TITLE
不能断点续传

### ISSUE THREAD

**Issue by hu499019771** [lingochamp/FileDownloader#381]
作者你好:
1.在做一个需求:开始/暂停/继续下载.
2.参考TasksManagerDemoActivity来写的.
3.在可以正常启动下载,可以正常暂停,在点击继续下载后,又从头开始下载.
4.我把filedownloader数据库文件导出来看,发现开始和继续下载操作的downloadId是一样的,但是继续下载后,sofar的值重新开始写进去,eTag是有值的,不知道是那个地方出了问题?谢谢
下面是开始/继续下载的启动任务代码:
 else if (action.equals(v.getResources().getString(R.string.txt_download)) 
                        ||action.equals(v.getResources().getString(R.string.txt_continue))
                        || action.equals(v.getResources().getString(R.string.txt_retry))) {
                    // to start
                    final TasksManagerModel model = TasksManager.getImpl().getById(holder.id);
                    final BaseDownloadTask task = FileDownloader.getImpl().create(
                            url)
                            .setPath(path)
                            .setCallbackProgressTimes(100)
                            .setListener(taskDownloadListener);

                    TasksManager.getImpl()
                            .addTaskForViewHolder(task);

                    TasksManager.getImpl()
                            .updateViewHolder(holder.id, holder);
  }

**Comment by Jacksgong** [comment]
FileDownloader内部默认走的就是断点续传的。

通过你贴出的代码，我无法定位问题所在，如果你在demo中断点续传没有问题，但是在自己的应用中遇到的相关问题。建议直接debug进去看看，重点留意下这个方法 `FileDownloadRunnable#checkIsResumeAvailable`

**Comment by hu499019771** [comment]
已解决,今天上班重开电脑就可以了,(汗,昨天忘了clean项目)谢谢提供这么好的下载框架.

**Comment by Jacksgong** [comment]
👍 谢谢~
