### ISSUE TITLE
代码写的超级乱，没有很好的运用设计模式   各种静态内部类 看起来太费劲了

### ISSUE THREAD

**Issue by konglingkuan** [lingochamp/FileDownloader#382]

**Comment by Jacksgong** [comment]
很感谢你的建议，也十分欢迎PR。

#### 代码写的超级乱

也许对于刚刚接触FileDownloader来说，由于存在一定的复杂度，确实是有些困难的。为了内部更加稳定，以及规范在上层的结构中使用了很多的面向接口编程，尽量减少针对特定场景没有必要的接口暴露，虽然在Java虚拟机上这种最佳实践，[并非是好性能的选择](https://blog.dreamtobe.cn/2015/10/26/android_optimize/)。

如果觉得哪里的代码觉得不应该使用某种写法，十分欢迎指点与讨论。

#### 运用设计模式

所谓的设计模式只是一类范式，不能只是生搬硬套，目的就是为了更易于维护、拓展，更稳定，更可读。

目前而言: 代码是十分稳定的，并且可拓展性也很强，迭代了几十个版本，bug修复也是十分快速的。

我之前也有整理过一些[常见的模式](https://blog.dreamtobe.cn/2016/10/25/oo_architecture/)，如果读代码过程中觉得哪里可以有更好的设计方式欢迎提出，欢迎PR。

#### 静态内部类，看起来太费劲了

有些小的十分明确的存在宿主关系，并且是很小的类，确实使用了静态的内部类，如果这个影响到了可读性，我已经写了尽可能多的注解以及[wiki](https://github.com/lingochamp/FileDownloader/wiki)，如果觉得有更好的建议，欢迎具体举出，这样也便于交流与探讨。谢谢~

---

FileDownloader确实还有很多需要改进的地方，十分迫切希望能够得到大家的加入，一起维护，让其变得更好，我也会保持学习的心态，不断的改进FileDownloader，谢谢~

**Comment by konglingkuan** [comment]
作者您好，我看过okhttp源码和pascal源码asynhttpclient 以及UIL图片下载器等源码 他们充分运用了设计模式 逻辑十分清晰 主线逻辑基本上能1-2天内理清楚，您的这个作品源码我看了一些 感觉很费劲  等我研究差不多再来回复吧

**Comment by Jacksgong** [comment]
其实FileDownloader中也是有利用很多的设计模式的。非常感谢你能够做这方面的思考，欢迎讨论以及学习，如果有更好的方案，或者建议我们一定会第一时间采纳的~  非常欢迎PR哈~

> PS: 当然我们也很希望能够做的足够优秀，我们也一直向okhttp、picasso等这些优秀的开源库学习的。

**Comment by Jacksgong** [comment]
这个Issue一直在勉励我，也给我警示，我一直忠告自己，质量质量，质的重要性远远大于量，无论是团队，还是自己，要做就做精，要写就写优秀的code，这样才能给自己带来成长，给社区带来有效的回馈，才能有效能。

很感谢你给我的警示，有任何的更新，这个Issue将被重新打开。
