### ISSUE TITLE
Pause a download task before entering Pending state

### ISSUE THREAD

**Issue by Anchorer** [lingochamp/FileDownloader#384]
当一个BaseDownloadTask调用start()方法进行启动时，大致会经历这样一个过程：
downloadTask.start() --> Pending -> Progress...
在下载过程中调用pause()方法可以将该task暂停，并且在接下来调用start()时自动断点续传。

在我使用FileDownloader的过程中，我发现，当一个downloadTask在start()后，在到达Pending状态之前会有一个时间空隙，在这个过程中，如果调用pause()将其暂停，再通过start()继续该项下载时，看起来该项下载任务就无法正常进行了。

这种场景下，downloadTask无法再次进入Pending状态，并且无法开始下载。然后，再次对该任务调用pause()暂停以及start()启动，就可以正常下载了。

我的大致操作流程总结为：
```
1. downloadTask.start()
2. 在进入Pending状态之前pause() --> start()：此时无法下载（也没有报warn或者异常）；
3. 再次pause() --> start()：下载正常。
```

因此想请教一下，FileDownloader在start后，进入Pending状态之前处于怎样的状态？这个场景下pause()会引起怎样的问题？以及如何解决这个问题？

**Comment by Reza7z** [comment]
me too problem:|

**Comment by Jacksgong** [comment]
### FileDownloader在start后，进入Pending状态之前处于怎样的状态？

Task进入全局的启动任务线程池，然后在池中排队(三个窗口)，当轮到该任务的时候就通过Binder通知FileDownloadService启动该任务，此时任务进入pending状态。

#### 启动任务线程池

该池子最大运行3个线程，每个线程闲置5s自动被回收，整个池子中的任务是FIFO的执行的。

该池子的任务很简单，将池子中的任务在非UI线程下启动。

#### 对于某一个任务该过程的线程切换

##### FileDownloadService运行在独立进程的情况

用户调用`start`方法的线程 -> `LaunchTaskPool`中的非UI线程 -> 跨进程通信时的Binder(默认线程数是16)（此时对应的`LaunchTaskPool`中的线程会被block）-> 进入Pending(此时对应的`LaunchTaskPool`中的线程会被unblock)

##### FileDownloadService运行在UI进程的情况

用户调用`start`方法的线程 -> `LaunchTaskPool`中的非UI线程 ->  进入Pending

---

这个情况我在设计FileDownloader之初就有思考过，也处理了。 如果现在的版本存在这个问题，说明是出bug了，我会在目前master分支上进行测试，如果有问题，会在新版本优先得到修复。

**Comment by Jacksgong** [comment]
@Anchorer @Reza7z 这个确实是个bug，目前已经修复了，可以关注下这个Issue: #402

今晚或者明晚会Release v 1.4.0 ，带上这个修复。

**Comment by Anchorer** [comment]
谢谢！
