### ISSUE TITLE
如何删除文件？

### ISSUE THREAD

**Issue by JaminFan** [lingochamp/FileDownloader#385]
你好，请问如何删除文件？我使用FileDownloader.getImpl().clear（）方法无法删除下载的文件，无论是已下载的还是正在下载的。
还有个问题：FileDownloadList用downloadId获取的IRunningTask都是null，无法获取已经下载完成的任务

**Comment by Jacksgong** [comment]
#### FileDownloader.getImpl().clear（）方法无法删除下载的文件，无论是已下载的还是正在下载的

`FileDownloader#clear`，如果没有warn的Logcat，说明清理数据成功，就会删除正在下载的文件以及已经下载完成的文件，具体可以参考下[源码](https://github.com/lingochamp/FileDownloader/blob/master/library/src/main/java/com/liulishuo/filedownloader/FileDownloader.java#L343)。

#### FileDownloadList用downloadId获取的IRunningTask都是null

无论是`FileDownloadList`以及`IRunningTask`都是内部架构使用的，为了维护上层接口能够正确运作的，并非对外开放（由于动态以及对外界而言这个数据是十分不可控的）。

如果你希望获知所有已经下载完成的任务，希望能够自己根据业务需求去实现，而非耦合FileDownloader内部架构，因为内部架构随着版本迭代，以及上层接口，是会不断变动的。

**Comment by JaminFan** [comment]
1、我发现异常退出（其实我是在下载中直接覆盖安装了）的时候就无法删除了，查看了没有log打出，我断点源码到clear方法，在判断文件是否存在的时候判断成了不存在，但是文件夹确实是有文件的。
2、要获取下载完成的所有任务，我只能想到去遍历文件夹，请问有其他思路吗？
3、我用isServiceConnected去判断是否断开，断开后使用insureServiceBind去绑定，但是经常重进应用的时候会打印log说我断开了连接，提示使用insureServiceBind去绑定。
感谢回复

**Comment by Jacksgong** [comment]
#### 我断点源码到clear方法，在判断文件是否存在的时候判断成了不存在，但是文件夹确实是有文件的

是指系统`File.exists()` 返回与实际不符吗？ 

#### 要获取下载完成的所有任务，我只能想到去遍历文件夹，请问有其他思路吗？

这个根据自己上层的业务需求，进行管理，你可以将下载结束的`数据存储到你的自定义数据库表中`，或者通过 `遍历文件夹`中，或者其他方式。

> FileDownloader在文件下载完成后，就会清楚内部数据，已防止数据无限膨胀，以及保持下载的轻盈。

#### 我用isServiceConnected去判断是否断开，断开后使用insureServiceBind去绑定，但是经常重进应用的时候会打印log说我断开了连接，提示使用insureServiceBind去绑定。

这个我不明白你的问题所在，因为这里，服务的断开，以及关闭，在应用进入后台以后，确实有可能受到系统的回收的。

**Comment by JaminFan** [comment]
1、是指系统File.exists() 返回与实际不符吗？ 
是的，
2、明白了，谢谢。
3、你的意思是提示的那log是正常的，是因为服务可能被后台杀死了
PS：我发现上述问题，在我使用 FileDownloader.getImpl().bindService();去绑定后，都得到了解决。我猜出现上述问题的原因可能是我每次都没绑定服务成功。

**Comment by Jacksgong** [comment]
恩。好的。
