### ISSUE TITLE
对于Post下载方式如何支持？

### ISSUE THREAD

**Issue by 10045125** [lingochamp/FileDownloader#387]
http://2016w.j289cwsupdownspckxs.info/freeone/file.php/OF57THr.html 这里面的种子文件下载。WebView回调过来的数据是
url="http://2016w.j289cwsupdownspckxs.info/freeone/down.php", refUrl="http://2016w.j289cwsupdownspckxs.info/freeone/file.php/OF57THr.html", contentDisposition="attachment; filename="OF57THr.torrent"", mimetype="application/force-download", textEncoding=null, contentLength=19485, isPost=true, isMultiPart=false, postBody="type=torrent&id=OF57THr&name=OF57THr"，这种情况如何解决？

**Comment by Jacksgong** [comment]
> Post协议适用于提交大量数据，FileDownloader目前不支持，通常来说如果是Get完全够用，一些校验或者其他信息直接通过Header带上去就可以了。

FileDownloader 1.4.0中我们会提供支持自定义网络组件，到时候应该是可以通过比较hacker的方法将请求转为post协议的请求。关于自定义网络组件，这块follow这个Issue即可: #158

**Comment by 10045125** [comment]
弱弱的问下，上面的postBody转为okhttp的post有没有示例代码。不胜感激

**Comment by Jacksgong** [comment]
1.4.0支持以后，你先试试，如果有疑惑重新提Issue，到时候我给你看看。
