### ISSUE TITLE
problem with download in service

### ISSUE THREAD

**Issue by mohamadrezash** [lingochamp/FileDownloader#389]
i created my service as follows
`public class DownloadServ extends Service {
    public static final int STATUS_DOWNLOADING = 0;
    public static final int STATUS_DOWNLOADING_INPROSESS = 5;
    public static final int STATUS_PAUSE = 3;
    public static final int STATUS_FINISHED = 1;
    public static final int STATUS_ERROR = 2;
    public static final int StatusFailed=4;
    SharedPreferences sharedPreferences;
    static ResultReceiver receiver;
    String path;
    NotificationCompat.Builder mBuilder;
    static Bundle bundle;
    static NotificationManager notificationManager;
    public DownloadServ() {
    }
    @Override
    public void onCreate() {
        super.onCreate();
    }
    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        FileDownloader.init(getApplicationContext(),
                new FileDownloadHelper.OkHttpClientCustomMaker() { // is not has to provide.
                    @Override
                    public OkHttpClient customMake() {
                        // just for OkHttpClient customize.
                        final OkHttpClient.Builder builder = new OkHttpClient.Builder();
                        // you can set the connection timeout.
                        builder.connectTimeout(15_000, TimeUnit.MILLISECONDS);
                        // you can set the HTTP proxy.
                        builder.proxy(Proxy.NO_PROXY);
                        // etc.
                        return builder.build();
                    }
                });
        File pathfile= new File(Environment.getExternalStorageDirectory()+ File.separator + "zanbilstore");
        if (!pathfile.isDirectory()){
            pathfile.mkdir();
        }
         path=pathfile.getAbsolutePath();
        if (intent == null){
            sharedPreferences= PreferenceManager.getDefaultSharedPreferences(getApplicationContext());
          String  url= sharedPreferences.getString("url","");
        }
        Intent pintent = new Intent();
        PendingIntent pendingIntent = PendingIntent.getActivity(getBaseContext(), 0, pintent, PendingIntent.FLAG_UPDATE_CURRENT);
        mBuilder =
                new NotificationCompat.Builder(getBaseContext())
                        .setSmallIcon(R.mipmap.ic_launcher)
                        .setContentTitle("اطلاعات دانلو").setProgress(100,0,false)
                        .setContentText("در حال دانلود...")
                        .setContentIntent(pendingIntent);
        notificationManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
        bundle = new Bundle();
        if (intent!=null) {
            receiver = intent.getParcelableExtra("receiver");
             String url=intent.getStringExtra("url");
            final FileDownloadModel model = new TasksManagerDBController().addTask(url,path);
            model.setId(1);
            model.setFilename("whatsapp.apk");
             FileDownloader.getImpl().create(model.getUrl())
                    .setPath(model.getPath())
                    .setCallbackProgressTimes(100)
                    .setListener(new FileDownloadSampleListener() {
                        @Override
                        protected void pending(BaseDownloadTask task, int soFarBytes, int totalBytes) {
                            super.pending(task, soFarBytes, totalBytes);
                            Toast.makeText(getApplicationContext(),"pending",Toast.LENGTH_LONG).show();
                        }
                        @Override
                        protected void progress(BaseDownloadTask task, int soFarBytes, int totalBytes) {
                            Toast.makeText(getApplicationContext(),"progres",Toast.LENGTH_LONG).show();
                            super.progress(task, soFarBytes, totalBytes);
                            double percent = ((double) soFarBytes) / ((double) totalBytes);
                            int progress=(int) (percent * 100);
                            bundle.putInt("downloading",progress);
                            bundle.putInt("isdownloding",1);
                            bundle.putString("urlofdownloading",task.getUrl());
                            mBuilder.setProgress(100,progress,false);
                            notificationManager.notify(1, mBuilder.build());
                            if (receiver!=null) {
                                receiver.send(STATUS_DOWNLOADING, bundle);
                                receiver.send(STATUS_DOWNLOADING_INPROSESS, bundle);
                            }
                        }
                        @Override
                        protected void error(BaseDownloadTask task, Throwable e) {
                            super.error(task, e);
                            Toast.makeText(getApplicationContext(),"eror",Toast.LENGTH_LONG).show();
                        }
                        @Override
                        protected void connected(BaseDownloadTask task, String etag, boolean isContinue, int soFarBytes, int totalBytes) {
                            super.connected(task, etag, isContinue, soFarBytes, totalBytes);
                            Toast.makeText(getApplicationContext(),"conected",Toast.LENGTH_LONG).show();

                        }

                        @Override
                        protected void paused(BaseDownloadTask task, int soFarBytes, int totalBytes) {
                            super.paused(task, soFarBytes, totalBytes);
                            Toast.makeText(getApplicationContext(),"pused",Toast.LENGTH_LONG).show();

                        }

                        @Override
                        protected void completed(BaseDownloadTask task) {
                            super.completed(task);
                            Toast.makeText(getApplicationContext(),"completed",Toast.LENGTH_LONG).show();
                        }

                        @Override
                        protected void warn(BaseDownloadTask task) {
                            super.warn(task);
                            Toast.makeText(getApplicationContext(),"wharn",Toast.LENGTH_LONG).show();

                        }
                    }).start();
        }
        return START_STICKY;
    }
    @Override
    public void onDestroy() {
        super.onDestroy();
        notificationManager.cancel(1);
    }
    @Override
    public IBinder onBind(Intent intent) {
        throw new UnsupportedOperationException("Not yet implemented");
    }
}`

but when I close the application, Service is  also closed and download stops and in a moment service restarts but download doesn't resume. what shall i do to make download resume again??

**Comment by Jacksgong** [comment]
> but when I close the application, Service is also closed and download stops and in a moment service restarts but download doesn't resume. what shall i do to make download resume again??

Please move to [this comment](https://github.com/lingochamp/FileDownloader/issues/347#issuecomment-252430496).

**Comment by mohamadrezash** [comment]
thanx
but i dont know how to use startforeground()?
this method only get id and Notification not url or patch or id ......
and another question. if i use  startforeground() then downlownload from service is necessary? or not

**Comment by Jacksgong** [comment]
> but i dont know how to use startforeground()?

You can ref [here](https://developer.android.com/reference/android/app/Service.html#startForeground(int, android.app.Notification)).

> if i use startforeground() then downlownload from service is necessary?

The FileDownloader has a service : FileDownloadService, what is used for downloading files and store the downloading data.

The action `startForeground()` effect on `FileDownloadService`, so it is not about what's your architecture or component you use.
