### ISSUE TITLE
暂停后再次下载出错

### ISSUE THREAD

**Issue by changjiashuai** [lingochamp/FileDownloader#39]
error()-629675092, msg=fstat failed: ENOENT (No such file or directory)

**Comment by Jacksgong** [comment]
恩。我无法通过你的描述定位到问题，可以详细一些吗，比如提供下你下载该文件时候指定的路径，以及出现该情况的上下文。因为FileDownloader demo中的暂停后再下载是没有问题的(如果你觉得这点不正确，可以先使用demo中的暂停后再次下载试试)。

**Comment by changjiashuai** [comment]
暂时加了句.setAutoRetryTimes(1)解决，但现在又有新问题了，已经提交#40

**Comment by Jacksgong** [comment]
我不知道你的问题是什么，要不你创建一个有问题的demo项目，发github或者发邮件给我，我给你看下。
