### ISSUE TITLE
FileDownloadQueueSet  不好使

### ISSUE THREAD

**Issue by xiandao** [lingochamp/FileDownloader#390]
FileDownloadQueueSet queueSet = new FileDownloadQueueSet(listener)
                    .setAutoRetryTimes(1)
                    .downloadSequentially(newList);
            queueSet.start();

//暂停这个下载队列
FileDownloader.getImpl().pause(listener);

//根据业务需要，一会之后 要重新启动这个下载队列，但是不好使，请问楼主有没有好的办法
 queueSet.start();

提示的错误
W/FileDownloader.FileDownloader: Tasks with the listener can't start, because can't find any task with the provided listener

明明已经设置过了 listener

**Comment by 947000711** [comment]
你暂停以后应该就清空任务了,再次start 之前要重新加载下任务吧 . 我也是下载M3U8 , 到最后发现 ,如果你一次性把任务加载到队列里面去 , 如果文件很大的话 ,暂停,恢复,等 会比较蛋疼, 个人建议 自己维护一张表, 只用Filedownloader的下载模块 , 其他的都在外层自己弄

**Comment by Jacksgong** [comment]
这个问题参考[这个Issue](https://github.com/lingochamp/FileDownloader/issues/383#issuecomment-258091596)。

**Comment by ximencx** [comment]
@947000711  @Jacksgong 请教下如果下载多个m3u8，使用框架的队列，那么多个队列怎么去用？？？因为框架维护了一个单例list

**Comment by ximencx** [comment]
@Jacksgong  可以改成维护一个键值对么
```
public class FileDownloadList
 private final ArrayList<BaseDownloadTask.IRunningTask> mList;

```
