### ISSUE TITLE
如何在notification上显示下载失败的一些信息？

### ISSUE THREAD

**Issue by wangsuicheng** [lingochamp/FileDownloader#391]
有api能获取到这个task下载失败了（比如一些异常）的信息？

**Comment by Jacksgong** [comment]
可以啊， 在`FileDownloadListener#error`回调中传回的就是`Throwable`，并且`BaseDownloadTask#getErrorCause`也可以获取到当前错误的`Throwable`。

**Comment by wangsuicheng** [comment]
谢谢快速回复，能通过id，去取得某个BaseDownloadTask吗？因为我在NotificationItem 这个里面只传入了task的id

**Comment by Jacksgong** [comment]
### 能通过id，去取得某个BaseDownloadTask吗? 

因为内部的运行时队列变化很快，目前没有提供这个接口，如果有这个需求，建议上层去wrap一层，这样回好很多: https://github.com/lingochamp/FileDownloader/issues/103#issuecomment-209173124
