### ISSUE TITLE
getSoFar()和getTotal()返回大小为0

### ISSUE THREAD

**Issue by 280017423** [lingochamp/FileDownloader#392]
你好，我暂停下载，退出应用再次进来，想恢复进度，我调用了如下方法：
int id = FileDownloadUtils.generateId(url, path);
long soFar = FileDownloader.getImpl().getSoFar(id);
long total = FileDownloader.getImpl().getTotal(id);
但是返回的结果都是0，如果再次点击下载后，回调返回的进度就是正确的，
这个是还有哪里有设置么？谢谢！

**Comment by Jacksgong** [comment]
你可以关注下Logcat中的日志输出。

这个是由于，数据是存储在下载服务中的，服务没有启动就没有数据，你可以采用[这样的方式](https://github.com/lingochamp/FileDownloader/issues/235#issuecomment-236560136)。

或者是: `FileDownloader#insureServiceBind`

**Comment by 280017423** [comment]
非常感谢，我用如下方法解决了问题：
int id = FileDownloadUtils.generateId(url, path);
long soFar = FileDownloader.getImpl().insureServiceBind().getSoFar(id);
long total = FileDownloader.getImpl().insureServiceBind().getTotal(id);

**Comment by BinarySatan** [comment]
我如果想提前获取文件大小 应该怎么做?   (没有调用start方法)
