### ISSUE TITLE
下载错误，是因为cache的问题吗？

### ISSUE THREAD

**Issue by qiangzhou** [lingochamp/FileDownloader#393]
11-12 22:20:35.100 18864-18864/com.blackmamal.smartmedia3 I/download: filedownloader listener error!
11-12 22:20:35.100 18864-18864/com.blackmamal.smartmedia3 D/test_status: received command status event !
11-12 22:20:35.100 18864-18864/com.blackmamal.smartmedia3 D/test_status: indicator:0.16
11-12 22:20:35.100 18864-18864/com.blackmamal.smartmedia3 D/test_status: name:framelayout
11-12 22:20:35.100 18864-18864/com.blackmamal.smartmedia3 D/test_status: sn:4333f487-e369-4d2e-9824-fa9a9216662e
11-12 22:20:35.100 18864-18864/com.blackmamal.smartmedia3 I/download: task framelayout:f59a7f3ea67d11e6965900163e001f91 finished!
11-12 22:20:35.100 18864-18864/com.blackmamal.smartmedia3 W/System.err: com.liulishuo.filedownloader.exception.FileDownloadHttpException: response code error: 412, 
11-12 22:20:35.100 18864-18864/com.blackmamal.smartmedia3 W/System.err:  request headers: If-Match: "58247f9a-49adb4"
11-12 22:20:35.100 18864-18864/com.blackmamal.smartmedia3 W/System.err: Range: bytes=66633-
11-12 22:20:35.100 18864-18864/com.blackmamal.smartmedia3 W/System.err: Cache-Control: no-cache
11-12 22:20:35.100 18864-18864/com.blackmamal.smartmedia3 W/System.err:  
11-12 22:20:35.100 18864-18864/com.blackmamal.smartmedia3 W/System.err:  response headers: Server: nginx/1.4.6 (Ubuntu)
11-12 22:20:35.101 18864-18864/com.blackmamal.smartmedia3 W/System.err: Date: Sat, 12 Nov 2016 14:20:35 GMT
11-12 22:20:35.101 18864-18864/com.blackmamal.smartmedia3 W/System.err: Content-Type: text/html
11-12 22:20:35.101 18864-18864/com.blackmamal.smartmedia3 W/System.err: Content-Length: 197
11-12 22:20:35.101 18864-18864/com.blackmamal.smartmedia3 W/System.err: Connection: keep-alive
11-12 22:20:35.101 18864-18864/com.blackmamal.smartmedia3 W/System.err:     at com.liulishuo.filedownloader.services.FileDownloadRunnable.loop(FileDownloadRunnable.java:371)
11-12 22:20:35.101 18864-18864/com.blackmamal.smartmedia3 W/System.err:     at com.liulishuo.filedownloader.services.FileDownloadRunnable.run(FileDownloadRunnable.java:222)
11-12 22:20:35.101 18864-18864/com.blackmamal.smartmedia3 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-12 22:20:35.101 18864-18864/com.blackmamal.smartmedia3 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)

**Comment by Jacksgong** [comment]
这个是一个http状态码: 412，你可以和你后台了解下，为什么有这个先决条件错误。

这边内部请求头的信息肯定是没有错的，因为内部自动添加的`Etag`是后台返回回来的。
