### ISSUE TITLE
how use WeakReference in TasksManager.getImpl().onCreate(new WeakReference<>(  *** ))

### ISSUE THREAD

**Issue by AndroidDesigner** [lingochamp/FileDownloader#395]
i want to use TasksManager.getImpl().onCreate(new WeakReference<>(  *** )) in onCreateView() method a dialogFragment.
what do i write instead of '***' ?
when i write 'getActivity' , postNotifyDataChanged() method in  your TaskManagerDemoActivity (sample code) result in error and does not recognized.

**Comment by Jacksgong** [comment]
Sorry to heard that, `TasksManager` In  `TasksManagerDemoActivity` just a demonstrate, **If you need to use it, you have to customize you own one refer to that**.
