### ISSUE TITLE
Download reconnect

### ISSUE THREAD

**Issue by rharesh90** [lingochamp/FileDownloader#396]
Hello 
I  am  using FileDownloader and it's working fine but when  my network  is disconnect after reconnect the network. i can't start download restart automatically  please help me

**Comment by HarkBen** [comment]
I'm very sorry, my English from youdao translation...
Hope the following solutions can help you
First set the cache, and confirm the background support breakpoint continuingly.The client has already begun to download task information, network has reopened after open a download task can be recorded.

**Comment by Jacksgong** [comment]
Thanks, @HarkBen , you are right, FileDownloader support resuming download from breakpoint, and  when you start a task, FileDownloader will resume the task from the last downloaded point automatically if the breakpoint is available and Etag not change.

---

@rharesh90 Sorry FileDownloader is a pure downloader engine, If you have such feature, you can handle it by your upper layer:

1. You can have you own [DownloadManager](https://github.com/lingochamp/FileDownloader/issues/103#issuecomment-209173124).
2. If occur `error` callback with the network is disconnected, you `reuse` and store those tasks.
3. When you receive the network changed broadcast with the network is reconnected, just start all tasks you stored.
