### ISSUE TITLE
Resume the download of same file from mirror(different) URL?

### ISSUE THREAD

**Issue by vipulpurohit** [lingochamp/FileDownloader#397]
Hello,
Thanks for this great library.
I'm trying to use your library in one of my project but I'm facing an issue.

My application is going to download files from intranet networks. There are multiple intranet networks for multiple providers.

If I download a file named "FILE_1" from "URL_1" with 50% progress in "INTRANET_1" network now I moved out from the "INTRANET_1" network and after some time I moved into to "INTRANET_2" network where the same file reside with same name and length but the base ip address will be different from "INTRANET_1" network.

**eg: URL for both network:**
INTRANET_1: http://192.168.1.50/FILE_1.MOV
INTRANET_2: http://192.168.1.29/FILE_1.MOV

in this case **resume feature** will not work as the file url is different and If I try to download the same file in "INTRANET_2" it will be considered as different file and the download will start from beginning.

Am I missing any functionality of this library which can enable resume feature for same file with different urls?
Can you please guide me how can I achive this? I need to resume the download of same file but from mirror or different urls.

Thanks

**Comment by Jacksgong** [comment]
The present you provide is very clear, I know what is you want.

FileDownloader didn't support your case yet because FileDownloader generates the task identify through the md5 from the path and the Url, Sorry about that. 

But I will support that as soon as possible, you can follow this issue: #224

> Since I join the new job these days, my free time is less than before recently, so this feature may be delayed a few weeks until the 1.4.0 has already released, hope you understand.
