### ISSUE TITLE
对于当前无网络,error返回的错误类型的问题

### ISSUE THREAD

**Issue by zxhandroid** [lingochamp/FileDownloader#399]
您好! 下载处理的回调中如何当前没有网络状态,返回的是什么样的错误类型呢, 通过getCauseError 获取到错误类型有哪些,内部有常量声明出来吗? 急...希望您能给我解答一下,谢谢!

**Comment by Jacksgong** [comment]
> 返回常亮声明，来表达错误类型是IOS的做法。Android所有的错误都是采用`Throwable`对象的方式抛出。

因此当前无网络的时候，可能遇到的错误是: `SocketException`、`UnknownHostException`等，这边比较重要的还有在遇到问题的时候，再检测下当前的网络是否可用。
