### ISSUE TITLE
下载显示完成但是文件没保存成功

### ISSUE THREAD

**Issue by changjiashuai** [lingochamp/FileDownloader#40]
I/CameraActivity: url=http://192.168.77.1:8000/sdcard/VID_000920@4K.insv
03-01 18:14:50.642 32464-32464/com.insta360.explore I/CameraActivity: flag=true
03-01 18:14:50.642 32464-32464/com.insta360.explore I/CameraActivity: Stack Size=1
03-01 18:14:50.922 32464-32464/com.insta360.explore I/CameraActivity: long pending()-903804433
03-01 18:14:50.922 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=687903
03-01 18:14:50.922 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=687903
03-01 18:14:50.922 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=687903
03-01 18:14:50.922 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=687903
03-01 18:14:51.182 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=730736
03-01 18:14:51.192 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=730736
03-01 18:14:51.192 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=730736
03-01 18:14:51.192 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=730736
03-01 18:14:51.192 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=730736
03-01 18:14:51.192 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=730736
03-01 18:14:51.372 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1031792
03-01 18:14:51.372 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1031792
03-01 18:14:51.372 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1031792
03-01 18:14:51.372 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1031792
03-01 18:14:51.382 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1031792
03-01 18:14:51.382 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1031792
03-01 18:14:51.442 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1289840
03-01 18:14:51.442 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1289840
03-01 18:14:51.442 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1289840
03-01 18:14:51.452 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1289840
03-01 18:14:51.452 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1289840
03-01 18:14:51.452 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1289840
03-01 18:14:51.482 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1418864
03-01 18:14:51.482 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1418864
03-01 18:14:51.482 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1418864
03-01 18:14:51.482 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1418864
03-01 18:14:51.482 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1418864
03-01 18:14:51.482 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1418864
03-01 18:14:51.512 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1504880
03-01 18:14:51.512 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1504880
03-01 18:14:51.512 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1504880
03-01 18:14:51.522 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1504880
03-01 18:14:51.522 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1504880
03-01 18:14:51.522 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1504880
03-01 18:14:51.552 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1590896
03-01 18:14:51.552 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1590896
03-01 18:14:51.552 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1633904
03-01 18:14:51.562 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1633904
03-01 18:14:51.602 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1762928
03-01 18:14:51.602 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1762928
03-01 18:14:51.602 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1762928
03-01 18:14:51.632 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1891952
03-01 18:14:51.632 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1891952
03-01 18:14:51.632 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1891952
03-01 18:14:51.662 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1977968
03-01 18:14:51.662 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=1977968
03-01 18:14:51.682 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=2063984
03-01 18:14:51.682 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=2063984
03-01 18:14:51.712 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=2150000
03-01 18:14:51.712 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=2150000
03-01 18:14:51.732 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=2236016
03-01 18:14:51.742 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=2236016
03-01 18:14:51.772 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=2365040
03-01 18:14:51.772 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=2365040
03-01 18:14:51.772 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=2365040
03-01 18:14:51.802 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=2494064
03-01 18:14:51.802 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=2494064
03-01 18:14:51.802 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=2494064
03-01 18:14:51.812 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=2537072
03-01 18:14:51.852 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=2666096
03-01 18:14:51.852 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=2666096
03-01 18:14:51.852 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=2666096
03-01 18:14:51.882 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=2752112
03-01 18:14:51.882 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=2752112
03-01 18:14:51.972 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=2967152
03-01 18:14:51.972 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=2967152
03-01 18:14:51.972 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=2967152
03-01 18:14:51.972 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=2967152
03-01 18:14:51.972 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=3012208
03-01 18:14:52.012 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=3096176
03-01 18:14:52.012 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=3096176
03-01 18:14:52.012 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=3096176
03-01 18:14:52.062 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=3182192
03-01 18:14:52.062 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=3182192
03-01 18:14:52.092 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=3268208
03-01 18:14:52.092 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=3311216
03-01 18:14:52.102 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=3354224
03-01 18:14:52.112 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=3354224
03-01 18:14:52.142 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=3526256
03-01 18:14:52.142 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=3526256
03-01 18:14:52.142 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=3526256
03-01 18:14:52.142 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=3526256
03-01 18:14:52.172 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=3612272
03-01 18:14:52.172 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=3612272
03-01 18:14:52.202 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=3698288
03-01 18:14:52.202 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=3698288
03-01 18:14:52.232 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=3784304
03-01 18:14:52.232 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=3784304
03-01 18:14:52.272 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=3870320
03-01 18:14:52.272 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=3870320
03-01 18:14:52.302 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=4001392
03-01 18:14:52.302 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=4001392
03-01 18:14:52.302 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=4001392
03-01 18:14:52.332 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=4085360
03-01 18:14:52.332 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=4085360
03-01 18:14:52.352 32464-3128/com.insta360.explore I/CameraActivity: blockComplete()-903804433
03-01 18:14:52.372 32464-32464/com.insta360.explore I/CameraActivity: long progress() soFarBytes=4156109
03-01 18:14:52.372 32464-32464/com.insta360.explore I/CameraActivity: completed()-903804433

**Comment by Jacksgong** [comment]
我不知道你的问题是什么，要不你创建一个有问题的demo项目，发github或者发邮件给我，我给你看下。

**Comment by changjiashuai** [comment]
三星Note3 Moto X 都会出现下载第二次流程都对就是文件没有保存，步骤是这样的有A ,B两个Activity，从A进入到B,在B中有一个下载按钮，点击后setResults返回A，在A中onActivityResult处理下载，第一次是成功的，接着再试第二次，就失败了，现象流程和第一次一样，但本地就是没有文件。

**Comment by changjiashuai** [comment]
@Jacksgong 问题找到了 setPath的地方有问题，现在只能这样写
`
 FileDownloader.getImpl().create(url)
                    .setAutoRetryTimes(1)
//                    .setPath(path)  //此方法有bug
                    .setListener(fileDownloadLargeFileListener)
                    .ready();
`
下载完成后我需要重命名，有空看下什么愿意吧

**Comment by Jacksgong** [comment]
我不清楚 `setPath` 是存在什么bug，可否详细点提供下出现该bug 的上下文，因为我们自己也在使用这个库，做高并发，并没有遇到这个问题诶。

**Comment by Jacksgong** [comment]
如果你那边有必现的bug，最好是能够提供下简单的出现bug的demo project，我这边方便定位问题。
