### ISSUE TITLE
Download continues after pause is called

### ISSUE THREAD

**Issue by Trinkes** [lingochamp/FileDownloader#402]
Hi,
I'm using your library and i'm having a bug where after calling the pause method, the download continues.

I'm starting the download using the following method:

```
url = Constant.LIULISHUO_APK_URL;
path = llsApkFilePath;
BaseDownloadTask baseDownloadTask = FileDownloader.getImpl().create(url);
baseDownloadTask.setTag(tag);
int downloadId1 = baseDownloadTask.
                    setListener(listener).
                    setPath(path).
                    asInQueueTask().
                    enqueue();

path = llsApkFilePath + File.separator + "hi";
baseDownloadTask = FileDownloader.getImpl().create(url);
int downloadId12 = baseDownloadTask.
                    setListener(listener).
                    setPath(path).
                    asInQueueTask().
                    enqueue();
```

after calling 

```
FileDownloader.getImpl().pause(downloadId1);
FileDownloader.getImpl().pause(downloadId12);
```

the paused method is called but in background the download is still running (i'm checking it using charles) and i'm getting a "callback event transfer 3, but is contains false" log. it keeps logging that message until the "callback event transfer -3, but is contains false" message.

I was able to reproduce it using you demo app (i can make a pull request with it if you want).
if you want, you can check the implementation on my app [here](https://github.com/Aptoide/aptoide-client-v8/blob/master/downloadmanager/src/main/java/cm/aptoide/pt/downloadmanager/DownloadTask.java).

**Comment by Jacksgong** [comment]
Thanks for your issue, It seems a normal case, your [provided Url](https://github.com/Aptoide/aptoide-client-v8/blob/master/downloadmanager/src/main/java/cm/aptoide/pt/downloadmanager/DownloadTask.java) is broken now, could you please provide a sample project let me reproduce this problem. .

**Comment by Trinkes** [comment]
Thanks for your answer.
[Here](https://github.com/Trinkes/FileDownloaderIssue/tree/develop) is the sample. i cloned your demo and changed the single task test.
The 1st download now has a queue with 2 files to download.
the steps to reproduce the issue are:
1 - start download
2 - pause download
3 - wait like 10 sec 
4 - verify if something like the following apears on logs 
`W/FileDownloader.MessageSnapshotGate: callback event transfer 1, but is contains false
W/FileDownloader.MessageSnapshotGate: callback event transfer 6, but is contains false
W/FileDownloader.MessageSnapshotGate: callback event transfer 2, but is contains false
W/FileDownloader.MessageSnapshotGate: callback event transfer 3, but is contains false
W/FileDownloader.MessageSnapshotGate: callback event transfer 3, but is contains false
W/FileDownloader.MessageSnapshotGate: callback event transfer 3, but is contains false
W/FileDownloader.MessageSnapshotGate: callback event transfer 3, but is contains false
W/FileDownloader.MessageSnapshotGate: callback event transfer 3, but is contains false
W/FileDownloader.MessageSnapshotGate: callback event transfer -3, but is contains false`
5 - if it didn't show, try again. It happens very frequently

**Comment by Trinkes** [comment]
Any update for this issue?

**Comment by Trinkes** [comment]
btw, the sample code is in develop branch in forked repo.

Is there any progress regarding this issue?

**Comment by Jacksgong** [comment]
Thanks for your patient, I will handle this issue tonight.

**Comment by Jacksgong** [comment]
This is really a bug, what can be raised especially when you start some tasks with the 'serial-queue' way and pause them on by one(NOT pause them with their FileDownloadListener object(`FileDownloader#pause(FileDownloaderListener)`)).

---

### REAL REASON

> I add some beside Log, and running your Issue demo in the latest master branch

<img width="1249" alt="pasted_image_06_01_2017__1_33_am" src="https://cloud.githubusercontent.com/assets/6176417/21691481/aedcf794-d3b3-11e6-9d8e-c494afc046bf.png">

> P.S: `request paused` log is added on `FileDownloadMgr#pause(id:int)`; `request start` log is added on `FileDownloadMgr#start`;

**IT IS A MULTITHREADING(even about MULTIPROCESS) HIGH CONCURRENCY ISSUE. **

---

I will fix this bug as soon as possible.

**Comment by Jacksgong** [comment]
Because in this case, Start task and Pause on the different thread, and we handle pause through following three ways:

- Expire its launch task in the Launcher-Pool(This action is valid, only if the launch task has been added to the Launcher-Pool)
- Require pause it in FileDownloadService(This action is valid, only if the task has been handled in the FileDownloadService)
- Remove it from the internal list(This action is valid, only if the task doesn't schedule by Serial-Queue yet)

So..............Something like below:

![filedownloader](https://cloud.githubusercontent.com/assets/6176417/21741199/d1e4a8e8-d509-11e6-84e4-3f1588e12c58.png)

**Comment by Jacksgong** [comment]
The simplest solution is making those things thread-safe: 
![filedownloader](https://cloud.githubusercontent.com/assets/6176417/21741490/5c2b2470-d512-11e6-9bf7-7d46ab5b17aa.png)

**Comment by Jacksgong** [comment]
Another lighter way is using a thread-visible status to avoid downloading process when the task is paused, And this way is thanks for the `isUsing` param exist in the each task-object.

**Comment by Trinkes** [comment]
Thanks for solving the issue! when will it be released?

**Comment by Jacksgong** [comment]
@Trinkes tonight or tomorrow evening.
