### ISSUE TITLE
在studio中某些方法没有

### ISSUE THREAD

**Issue by 836986836** [lingochamp/FileDownloader#404]
在studio中
引用 compile 'com.liulishuo.filedownloader:library:0.1.2' 后 某些方法没有。是因为没引用library模块的原因吗？
下载后的 demo 没跑起来，

**Comment by 836986836** [comment]
在未下载之前如何获取文件的大小呢！！

**Comment by 836986836** [comment]
String path=Environment.getExternalStorageDirectory().getAbsolutePath()+ File.separator + "download"+File.separator ;
 FileUtils.createFile(path,"V"+System.currentTimeMillis() + ".apk");
 ViewHolder tag = new ViewHolder(new WeakReference<BasicActivity>(mContext), downloadBar, null, progressSpeed, 1);

  FileDownloader.getImpl().create(downloadUrl)
                .setPath(path,"V"+System.currentTimeMillis() + ".apk")
                .setCallbackProgressTimes(500)
                .setForceReDownload(true)
                .setTag(tag)
              .start();


error ;1 java.lang.RuntimeException: sofar[1293765] not equal total[-1]

**Comment by Jacksgong** [comment]
`0.1.2` 是比较旧的版本，你应该是看高版本的文档并且使用了旧的版本。使用最新版本即可。
