### ISSUE TITLE
 java.io.IOException: ftruncate failed: EINVAL (Invalid argument)

### ISSUE THREAD

**Issue by EvlinLee** [lingochamp/FileDownloader#405]
下载大文件的时候出现以下错误
 java.io.IOException: ftruncate failed: EINVAL (Invalid argument)
at java.io.RandomAccessFile.setLength(RandomAccessFile.java:628)
at com.liulishuo.filedownloader.stream.FileDownloadRandomAccessFile.setLength(FileDownloadRandomAccessFile.java:59)

**Comment by Jacksgong** [comment]
### 有几种可能导致这个问题:

1. 某个Android版本上的，Android的Bug，同样做`truncate`操作，有人在4.4遇到，最终被认定为系统bug: https://code.google.com/p/android/issues/detail?id=74039 , P.S: 我在我的MI5 MIUI7(Android 6.0) 上通过传入大小大于2G，并没有遇到这个问题。
2. 有可能是存储到了采用了FAT16的编码方式的存储卡中，FAT16格式的存储卡，只允许存储大小小于2G大小的文件。

### 避开`RandomAccessFile#setLength`

通过在[`filedownloader.properties`](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)中设置`file.non-pre-allocation=true`，避免在开始拉取数据之前预申请空间。
