### ISSUE TITLE
下载大文件的时FileDownloadListener的progress没有调用

### ISSUE THREAD

**Issue by EvlinLee** [lingochamp/FileDownloader#406]
下载大文件的时FileDownloadListener的progress没有调用，点击暂停后再点击开始下载就会调用

**Comment by Jacksgong** [comment]
FileDownloader在回调流方面，没有对大文件进行特殊处理，这块问题，可以参考下这里:

- https://github.com/lingochamp/FileDownloader/issues/246#issuecomment-237133750
- https://github.com/lingochamp/FileDownloader/issues/246#issuecomment-237135248 、https://github.com/lingochamp/FileDownloader/issues/246#issuecomment-237138109
