### ISSUE TITLE
好像不支持https的下载链接

### ISSUE THREAD

**Issue by jarvan11** [lingochamp/FileDownloader#407]
下载https的文件报错：E/FileDownloader.FileDownloadList: remove error, not exist: -1117771318@com.liulishuo.filedownloader.FileDownloadTask@929e3ef

**Comment by Jacksgong** [comment]
支持的，具体参考: https://github.com/lingochamp/FileDownloader/issues/380#issuecomment-257244236

这个日志，是移除该任务的时候，发现队列中并没有该任务。无法反映下载过程中出的错误。

你再认真留一下其他日志，以及抛回的`error`回调，FileDownloader支持http与https协议下载的。
