### ISSUE TITLE
FileDownloader.init(final Application application) 

### ISSUE THREAD

**Issue by 836986836** [lingochamp/FileDownloader#408]
在Application里面初始化，提示方法已经过期，
如果我有很多页面需要下载，需要在每个页面 都初始化一遍吗，
 对于一个下载任务， 我可能有很多地方都需要管理，那这些页面 是否还需要初始化呢

**Comment by Jacksgong** [comment]
> 在Application里面初始化，提示方法已经过期

希望能够留意下注解，为什么过期: [参考方法上的注解](https://github.com/lingochamp/FileDownloader/blob/master/library/src/main/java/com/liulishuo/filedownloader/FileDownloader.java#L144)

> 根据注解中的描述，你可以改用: [`FileDownloader#init(Context)`](https://github.com/lingochamp/FileDownloader/blob/master/library/src/main/java/com/liulishuo/filedownloader/FileDownloader.java#L48)

---

不需要每次都初始化，对于所在进程，只需要一次即可。一般来说就放到`Application`里面执行以此即可。
