### ISSUE TITLE
Resume download after losing connection

### ISSUE THREAD

**Issue by lap089** [lingochamp/FileDownloader#41]
After losing connection, all of my files which are downloading serially stop download, i also set retry download too, but it doesn't work

**Comment by Jacksgong** [comment]
Please check the call-back of `retry`  in `FileDownloadListener`. If the first task still failed after tried, the first one will receive the call-back of `error` and the next one  will start download.

**Comment by Jacksgong** [comment]
I tried it in FileDownloader Demo with just close the network connection of the device.

![ezgif com-crop](https://cloud.githubusercontent.com/assets/6176417/13483541/28e47584-e130-11e5-9583-62b7404764d4.gif)

**Comment by lap089** [comment]
Can I set the time for every retry of download?

**Comment by Jacksgong** [comment]
Yes, You can set `connectTimeout`(default 10s)、`readTimeout`(default 10s)、`writeTimeout`(default 10s)、 etc. Ref [DemoApplication](https://github.com/lingochamp/FileDownloader/blob/master/demo/src/main/java/com/liulishuo/filedownloader/demo/DemoApplication.java)

**Comment by lap089** [comment]
could you please show me a way to set the time for every retry of download?

**Comment by Jacksgong** [comment]
> could you please show me a way to set the time for every retry of download?

Ref [DemoApplication](https://github.com/lingochamp/FileDownloader/blob/master/demo/src/main/java/com/liulishuo/filedownloader/demo/DemoApplication.java)

> when does the filedownloader service stop?

You have to stop the filedownloader service manually by invoke `FileDownloader.getImpl().unBindService()`.

**Comment by lap089** [comment]
Sorry   I checked the demo application, but i really don't know how to set the interval time for every retry. I mean when i lose connection, the download continuously retry without waiting. I tried to let it sleep in the retry method of listener, but it doesn't work since it is in the main thread. Or how can i make the download process run in a separate thread? 
I tried with this code,  but it is no use!
   new Thread(new Runnable() {
                public void run() {
                            token = CreateDownloadTask(url,path).ready();
                            FileDownloader.getImpl().start(listener, true);
                }
            }).start();

**Comment by Jacksgong** [comment]
I know what you want now....

Sorry..... FileDownloader didn't provider any interface to support 'set the interval time for retry', it will retry immediately without waiting.

I know what you want, but FileDownloader downloads the file in the separate process, and in the current architecture, we can pause it, but can't block it in the UI process.

---

Maybe you can re-download manually in some seconds when receiving the call-back of `error`.

**Comment by lap089** [comment]
Ok, thanks!
