### ISSUE TITLE
低概率出现无法下载

### ISSUE THREAD

**Issue by nanweiqing** [lingochamp/FileDownloader#410]
你好，是这样的，我们app中有个资源列表，资源列表的下载引用了您的这个库，最近发现低概率会出现资源无法下载的情况，所有的资源全都无法下载，因为概率出现低，有些用户反映，但我们这边一直没复现出来，能帮着想想问题可能出在哪里吗，这是我这边在AS中的引用：compile 'com.liulishuo.filedownloader:library:+'

**Comment by nanweiqing** [comment]
ps:我这边曾经出现一次，然而因为那时没开log，看不到问题在哪，通过删除了app的缓存，重新登录账号，然后好了

**Comment by Jacksgong** [comment]
### 解决方式:

#### FileDownloader这边是有处理以下一些情况:

- 下载进程在下载过程中被kill了，这时会去恢复进程，并恢复下载。
- 在启动下载的时候，下载服务还未启动，这时会自动将所有需要下载的任务进入队列等待服务启动，服务启动后会自动启动队列中的任务下载。

因此，如果还有一些下载失败，FileDownloader都会回抛Throwable到`FileDownloadListener#error`的回调中的。因此需要你收集这些用户抛回来的错误是什么。

**Comment by nanweiqing** [comment]
感谢回复，针对这两个问题，想问个地方，
1.假如 下载进程在下载过程中被异常kill了，程序会默认自动恢复进程吗，还是需要手动写某些代码才能开启
2.在启动下载的时候，怎么判断下载服务已经启动，我想加个优化，假如下载服务未启动，则先启动下载服务再下载

**Comment by Jacksgong** [comment]
> 1.假如 下载进程在下载过程中被异常kill了，程序会默认自动恢复进程吗，还是需要手动写某些代码才能开启

会自动重启的。更多的可以参看: https://github.com/lingochamp/FileDownloader/issues/347#issuecomment-252404000，还有这里: https://github.com/lingochamp/FileDownloader/blob/master/README-zh.md#iii-低内存情况

> 2.在启动下载的时候，怎么判断下载服务已经启动，我想加个优化，假如下载服务未启动，则先启动下载服务再下载

在启动下载的时候，如果下载服务没有启动。默认会进入等待队列，然后自动启动服务，服务启动后，会自动开始任务。

- 获取服务连接状态可以是: `FileDownloader#isServiceConnected`
- 进行一些与服务连接有关的调用，可以通过以下方法辅助: `FileDownloader#insureServiceBind`、`FileDownloader#insureServiceBindAsync`、`FileDownloader#bindService(Runnable)`.
