### ISSUE TITLE
Add support for setting loading destination with URI 

### ISSUE THREAD

**Issue by bagza** [lingochamp/FileDownloader#411]
I want to use this library with `SAF`, and there is no reliable way to get filepath with it. Moreover, granted Permissions for `URIs` returned by `SAF` do NOT work with plain filesystem access bypassing `ContentResolver`. 
Since using plain file paths is getting deprecated, we should definitely consider using URI instead. 

I'm going to use persistent `URIs` and to store them the same way as `filePaths`, adding `setUri()` method to the `BaseDownloadTask`.

@Jacksgong I'd appreciate if you'd provide some hints, pitfalls or even roadmap for this approach.

referencing #349 request

**Comment by Jacksgong** [comment]
Thanks for your prompt, this is in the plan

**Comment by Jacksgong** [comment]
This has been covered on [okdownload](https://github.com/lingochamp/okdownload).
