### ISSUE TITLE
文件在下载完毕后getSmallFileTotalBytes()好像获取不到大小了

### ISSUE THREAD

**Issue by liang530** [lingochamp/FileDownloader#412]
如题

**Comment by liang530** [comment]
跟踪代码看了下，发现在FileDownloadRunnable中486行左右写着：
// Step 10, remove data from DB.
helper.remove(mId);
// callback completed
onComplete(total);
下载完成后从数据库中移除此条记录，接着通知onComplete方法里面又写了如下，去更新数据下载完成信息，都删除了，你还更新什么？这个删除操作的用意是什么？
private void onComplete(final long total) {
        if (FileDownloadLog.NEED_LOG) {
            FileDownloadLog.d(this, "On completed %d %d %B", mId, total, isCanceled);
        }
        helper.updateComplete(model, total);//更新数据信息，此时数据已经从数据库中移除，此操作无用！

        onStatusChanged(model.getStatus());
    }

**Comment by Jacksgong** [comment]
对的，一旦下载完成，所有相关的数据都会从数据库中删除，主要是为了使得FileDownloader更加轻量，如果你是使用 `BaseDownloadTask`对象，那么那个对象里面的值会一直在里面，如果你是通过Id到FileDownloader里面反查，建议反查之前，先通过`FileDownloader#getStatus`查查看是否已经下载完成。
