### ISSUE TITLE
如何改变刷新进度的频率

### ISSUE THREAD

**Issue by viphsx123** [lingochamp/FileDownloader#413]
如何改变刷新进度的频率？就是可不可以设置几秒更新一次

**Comment by HarkBen** [comment]
外部好像没有提供方法设置，你可以写个小公式，记录回掉更新次数。比如将原进度更新时间放大两倍，那更新次数%2==0 再更新UI

**Comment by Jacksgong** [comment]
@viphsx123 @HarkBen 可以的，参考下这个Issue: https://github.com/lingochamp/FileDownloader/issues/246#issuecomment-237133750
