### ISSUE TITLE
Can't download this pdf

### ISSUE THREAD

**Issue by Jeffin21** [lingochamp/FileDownloader#414]
When i try to download a PDF it doesn't start !!

http://www.lamborghini.com/sites/default/files/pdf_configurator/Lamborghini-Configuration-1480496123.pdf

**Comment by Jacksgong** [comment]
Please check out the callback error.

**Comment by 10045125** [comment]
@Jacksgong 其实很多东西不能下载和下载模块本身没有多大关系，反而是http中的header里面的东西有关系，有些服务器需要一些信息，但一些需要校验的header我也不大清楚，希望作者收集或者最大可能的提供这些指导

**Comment by Jacksgong** [comment]
@10045125 Actually I have already noticed this problem, and add one session in the wiki: [Can't download for some Urls?](https://github.com/lingochamp/FileDownloader/wiki/Can't-download-for-some-Urls%3F)

---

多谢你的建议，其实我之前就意识到了的。在Wiki里面有加了这个的: [Can't download for some Urls?](https://github.com/lingochamp/FileDownloader/wiki/Can't-download-for-some-Urls%3F)

**Comment by 10045125** [comment]
听说你换工作了，我也在阿里的一个部门，我钉钉能够找到你，😄😄
