### ISSUE TITLE
Failed to ensure directory

### ISSUE THREAD

**Issue by sinhpn92** [lingochamp/FileDownloader#419]
I have got an error when download a file when use FileDownloadUtils.getDefaultSaveFilePath(url) for save Path.
I added permission on manifest:
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>`
And i got task error status -3 on destroy notification.
Have any suggestion for fix this problem?

**Comment by Jacksgong** [comment]
Sorry, I can't understand what's the problem you occurred, If `-3` is the status of `FileDownloadStatus`, it is `FileDownloadStatus#completed`, what is means your download is complete successful.
