### ISSUE TITLE
关于释放资源

### ISSUE THREAD

**Issue by MrLiKH** [lingochamp/FileDownloader#42]
您好，使用了一下您写的代码，感觉很棒。有一个疑问，就是我用完之后，不需要在程序退出什么的释放一下资源么？

**Comment by Jacksgong** [comment]
谢谢~。

每次任务结束都会释放对应任务的资源。

程序退出的时候，建议手动将 下载服务关掉，就可以了 : `FileDownloader. unBindService()`。

**Comment by MrLiKH** [comment]
谢谢。
