### ISSUE TITLE
下载速度问题

### ISSUE THREAD

**Issue by yongcai1** [lingochamp/FileDownloader#422]
我试了咱们下载器的速度还没有android4.0自带的downloadManager快，android4.0用的是httpclient，按理说应该比咱们的下载器慢一些才对。另外，我觉得多线程下载同一个文件还是能够大大的提高下载速度的，像adm pro和uc都用的多线程下载，速度是咱们的好几倍。

**Comment by Jacksgong** [comment]
1.3.9版本，可以定制连接器(`FileDownloadConnection`)，你可以使用任何的(如`UrlConnection`、`Okhttp`)连接组件来创建连接。

---

由于FileDownloader是高定制化的，关于提高下载速度，可以参看下[这个教程](https://github.com/lingochamp/FileDownloader/wiki/Optimize-Tutorial)

---

关于一个任务分段多线程下载，可以关注下这个Issue: #102

**Comment by Jacksgong** [comment]
新架构已经支持，近期版本会带上，我这边测试可以跑满我家100Mb/s的宽带: https://github.com/lingochamp/FileDownloader/issues/102#issuecomment-306044546
