### ISSUE TITLE
how to re attach downloadlistener to 'in progress' task

### ISSUE THREAD

**Issue by hamedmohammadi** [lingochamp/FileDownloader#423]
consider i started a task and close the activity . when i come back i want to use listener for progress/complete/... callbacks

**Comment by Jacksgong** [comment]
#### For re attach downloadlistener

Please use `FileDownloader#replaceListener`

#### close the activity bind any task?

Please ref [here](https://github.com/lingochamp/FileDownloader/issues/103#issuecomment-209173124)
