### ISSUE TITLE
soFarBytes for all Tasks in a queue

### ISSUE THREAD

**Issue by MoQ93** [lingochamp/FileDownloader#425]
Hi,

Is it possible to get the sum of soFarBytes for all Tasks in a Queue (listener)? In my use case, I am downloading a list of files and show the progress in a Dialog so i would check the progress every second and update it in the dialog.

Thanks!

**Comment by Jacksgong** [comment]
Sorry we can't know the total bytes we need to download, the reason is: https://github.com/lingochamp/FileDownloader/issues/256#issuecomment-238839882
