### ISSUE TITLE
缓存机制

### ISSUE THREAD

**Issue by rehan91** [lingochamp/FileDownloader#426]
你好,我想问这个有做缓存机制吗?缓存是用传入的url进行判断吗?因为文件名都是一样的,如果是不一样的地址应该删除旧的,然后重新下载.是一样的就可以重用

**Comment by Jacksgong** [comment]
在相同的URL，相同存储路径的情况下 内部本身的机制是: 

- 如果本地已经存在下载好的文件了，默认情况下会直接返回完成
- 如果本地的文件还没有下载完成(会有临时后缀)，默认情况下会自动断点续传
- 如果本地已经存在下载好的文件了，并且对Task对象设置`BaseDownoloadTask.setForceReDownload(true)`，会删除之前已经下载完成的文件，重新进行下载。

**Comment by Lloyd0577** [comment]
你好，请问这个有做类似这样的缓存吗，就是指定一个文件夹大小，超过后，删除最老的文件
