### ISSUE TITLE
能支持https吗

### ISSUE THREAD

**Issue by LOWANGA** [lingochamp/FileDownloader#429]
能支持https吗

**Comment by Jacksgong** [comment]
目前默认的Connection使用的是[FileDownloadUrlConnection](https://github.com/lingochamp/FileDownloader/blob/master/library/src/main/java/com/liulishuo/filedownloader/connection/FileDownloadUrlConnection.java)，其是通过URL建立连接，目前就是支持https的。更多协议可以通过实现自己的Connection即可。
