### ISSUE TITLE
请问有没有eclipse的版本呢

### ISSUE THREAD

**Issue by nakisaren** [lingochamp/FileDownloader#43]
因为公司还在用eclipse，我将类都手动导入后 只有FileDownloadServiceUIGuard和另外两个相关联的类报错，FileDownloadServiceUIGuard extends BaseFileServiceUIGuard<FileDownloadServiceUIGuard.FileDownloadServiceCallback, IFileDownloadIPCService>这段一直无法进行修正，请问是什么原因呢？

**Comment by Jacksgong** [comment]
这个是jcenter上面的源码地址: [
jacksgong / maven / FileDownloader / 0.2.0](https://bintray.com/jacksgong/maven/FileDownloader/0.2.0/view#files/com/liulishuo/filedownloader/library/0.2.0)

你直接下载这个jar包( [library-0.2.0-sources.jar](https://bintray.com/artifact/download/jacksgong/maven/com/liulishuo/filedownloader/library/0.2.0/library-0.2.0-sources.jar))，然后导入试试。

**Comment by nakisaren** [comment]
你好，导入后，发现包里面都是空的package，这是为什么啊？

**Comment by Jacksgong** [comment]
我知道了。可能是因为这里面都是java源码，而不是编译好的class文件。

**Comment by Jacksgong** [comment]
你尝试下载 [
jacksgong / maven / FileDownloader / 0.2.0] 这上面的 [library-0.2.0.aar](https://bintray.com/artifact/download/jacksgong/maven/com/liulishuo/filedownloader/library/0.2.0/library-0.2.0.aar) ，然后用zip工具打开，取其中的 `classes.jar` ，然后导入试试（应该是没有问题，我们没有资源文件）。

![image](https://cloud.githubusercontent.com/assets/6176417/13521757/e8939b9e-e225-11e5-98f9-f0be0c58e185.png)

**Comment by Jacksgong** [comment]
#48 我看下。

**Comment by nakisaren** [comment]
抱歉 是我这边忘记将APPlication名字替换了 现在已经可以了 然后能加下你的QQ吗 因为我不是太熟悉 如果有问题可以问下你 我的QQ490930685 如果不方便也米关系 我这边也可以提问的。

**Comment by Jacksgong** [comment]
好吧。。。

有相关问题你无法解决直接到这个 issue里面评论，我会第一时间reopen给你看的，如果有人也遇到相同的问题，也可以给别人带来便利。谢谢了。

**Comment by nakisaren** [comment]
请问下 有没有取消下载的接口的？比如下载到一半不想下载了，将下载任务取消，同时需要将下载的内容同时清除。

**Comment by Jacksgong** [comment]
清除下载内容，可能需要你自己去删除，停止下载直接调用 `FileDownloader#pause` 或 停止下载所有 `FileDownloader#pauseAll` 这些会清除掉缓存中所有该任务相关的缓存，并且将该任务相关的线程关掉，释放所有相关资源，并且停止下载。

**Comment by wjk2813** [comment]
可以 现在点击开始按钮报错 okio  我用的是okhttp-3.2.0.jar

**Comment by Jacksgong** [comment]
@wjk2813 你可以看下错误提示是什么，到源码里面看看。
