### ISSUE TITLE
怎么下载到指定的路径

### ISSUE THREAD

**Issue by Icando26** [lingochamp/FileDownloader#432]
找到这个getDefaultSaveRootPath()方法，String mUrl = Environment.getExternalStorageDirectory().getPath()，但是出现下载异常，

**Comment by Jacksgong** [comment]
?什么异常？

如果你要存储在非当前app目录，需要申明读写权限 （目前demo中的权限申明是针对app目录）

**Comment by Icando26** [comment]
就是在manifest中申请是吧

**Comment by Jacksgong** [comment]
对的。这个是Android的权限机制，FileDownloader本身没有权限机制。

**Comment by Icando26** [comment]
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
还是不行啊 就是点击开始按钮然后状态是“出错”

**Comment by Jacksgong** [comment]
出错，你看看报的是什么错误。还有demo中的权限申明如果有不明白可以看看这个: #77

**Comment by Icando26** [comment]
public static String getDefaultSaveRootPath() {
        if (!TextUtils.isEmpty(DEFAULT_SAVE_ROOT_PATH)) {
            return DEFAULT_SAVE_ROOT_PATH;
        }
        String mUrl = Environment.getExternalStorageDirectory().getPath();
        String mFile = "/SSK_Download";//
        File file = new File(mUrl + mFile);
        if (!file.exists()) {
            file.mkdirs();
        }
   
        return file.getAbsolutePath();
我写的有问题？

**Comment by Jacksgong** [comment]
1. 如果是什么错误，你把错误信息与堆栈贴出来
2. 如果你是报权限问题，因为你的路径是需要sdcard根目录的读写权限的，直接参考下这个，看看是不是这个原因：https://github.com/lingochamp/FileDownloader/issues/77#issuecomment-205245349
