### ISSUE TITLE
下载状态在blockComplete方法的时候是-3

### ISSUE THREAD

**Issue by JaminFan** [lingochamp/FileDownloader#433]
如上述，我需要在完成状态的时候刷新界面，但是发现有多次进入到了刷新界面，调试后发现在回调blockComplete方法的时候状态就是下载完成了。

**Comment by Jacksgong** [comment]
你好，在`blockComplete`中的状态是 `-3` 是设计如此的，因此此时已经是下载完成了，只不过是 阻塞住 `complete` 的事件，用于解压缩，解码等处理操作。
