### ISSUE TITLE
快速添加新的下载任务并停止旧的下载任务导致下载的文件有问题

### ISSUE THREAD

**Issue by MUFCRyan** [lingochamp/FileDownloader#434]
下面是我的缓冲歌曲文件的代码：
public static void cacheSongToPlay(final String url, final String filePath, final String fileName,String bookId,String audioType, final
    IDownloadCallback callback){
        // TODO: 2016/7/7 数据参数的校验
        if (StringUtils.isNull(url)){
            return;
        }
        if (preCacheTask!=null){
            preCacheTask.pause();
            IDownloadCallback iDownloadCallback = preCacheTask.iDownloadCallback;
            taskList.remove(preCacheTask);
            String cacheFilePath = preCacheTask.getPath();
            TasksManager.getImpl().removeTask(preCacheTask.getUrl(), cacheFilePath);
            File file = new File(cacheFilePath);
            if (file.exists()){
                byte downloadState = MediaDownloader.getDownloadState(preCacheTask.getUrl(), cacheFilePath);
                if (downloadState != FileDownloadStatus.completed)
                    file.delete();
            }
            if (iDownloadCallback!=null)
                iDownloadCallback.onFailure(new Exception(Constants.IDOWNLOADCALLBACK_ONFAILURE_DELIVER_FLAG),Constants.IDOWNLOADCALLBACK_ONFAILURE_DELIVER_FLAG);
//            preCacheTask.clear();
        }
        File fileEncode = new File(filePath, fileName);
        TasksManagerModel model = TasksManager.getImpl().addTask(url, fileEncode.getAbsolutePath(),bookId,audioType);
        FileDownloader fileDownloader = FileDownloader.getImpl();
        fileDownloader.setMaxNetworkThreadCount(4);
        BaseDownloadTask baseDownloadTask = fileDownloader.create(model.getUrl()).setPath(model.getPath())
                .setCallbackProgressTimes(500).setCallbackProgressMinInterval(100)
                .setForceReDownload(true).setListener(taskDownloadListener);
        if (baseDownloadTask instanceof FileDownloadTask){
            //初始化相关数据.
            FileDownloadTask fileDownloadTask = (FileDownloadTask) baseDownloadTask;
            fileDownloadTask.isCacheTask = true;
            fileDownloadTask.iDownloadCallback = callback;
        }
        // TODO: 2016/7/8 线程调度 .
        taskList.add(baseDownloadTask);
        if (baseDownloadTask instanceof FileDownloadTask)
            preCacheTask = (FileDownloadTask) baseDownloadTask;
        baseDownloadTask.start();
    }

public static byte getDownloadState(final String url, final String filePath){
        if (TextUtils.isEmpty(url) || TextUtils.isEmpty(filePath)) {
            return 0;
        }
        int id = FileDownloadUtils.generateId(url, filePath);
        byte status = FileDownloader.getImpl().getStatus(id, filePath);
        return status;
    }

这里的逻辑是在快速的切换不同的歌曲时之前未下载好的缓冲文件会删除掉，对应的下载任务会暂停并移除，同时添加新的下载任务，现在发现的问题是这样多次操作后，有的歌曲文件会出现很刺耳的杂音，确认是下载的文件本身有问题，清空文件重新下载就不存在了

**Comment by Jacksgong** [comment]
FileDownloader下载的文件有问题的概率极低:

1. 本身FileDownloader就有对一个文件的写入有预分配空间以及保证引擎内对同一个文件只有一个写入的处理。
2. 如果下载结束时，文件的大小不等于服务器告知的文件大小(`content-length`)是直接回调下载失败的，我进行几千个文件高并发下载时没有遇到这种情况。
3. 之前我们有用这个FileDownloader用于高并发下载七牛的文件，并且根据七牛文件hash生成算法算出文件应有的md5，再对比文件的md5，基本上是没有校验失败的。


#### 如何验证?

如果你认为下载文件本身就有问题，你可以通过校验文件md5的方式进行验证。

---

所以，有没有可能是因为系统资源的抢占，导致某些手机上出现这种问题。
