### ISSUE TITLE
这个可以实现像网易云音乐的歌曲下载么？

### ISSUE THREAD

**Issue by jiangshihua** [lingochamp/FileDownloader#436]
这个可以实现像网易云音乐的歌曲下载么？

**Comment by jiangshihua** [comment]
比如一个界面点击下载多个开始进行下载，然后进入到下载页面可以看下载进度，怎么实现？

**Comment by Xanthuim** [comment]
你们提问的时候都不看Demo吗？这种最基本的下载还要问？至于能不能下载网易音乐已经超出本项目范围了。

**Comment by Jacksgong** [comment]
- 多任务管理，demo中的`MultitaskTestActivity`中已经有了。
- 下载进度多页面同步之类的，可以参看下这里: https://github.com/lingochamp/FileDownloader/issues/103#issuecomment-209173124

**Comment by XYScience** [comment]
下载进度多页面同步，对于两个页面都是listview时如何处理啊？怎么能正确取到当前页面的viewholder以更新界面

**Comment by Xanthuim** [comment]
@XYScience 是ListView还是RV还是其他得一点关系都没。不过作者里面得例子只是例子，真正得开发不能这么写。不要老想着界面，你要做到数据与界面分离，这个框架已经很好得做了分离了，你现在要做得就是在不同得界面获取数据并显示即可。
