### ISSUE TITLE
大神 为什么这个下载地址不能正常下载的

### ISSUE THREAD

**Issue by LOWANGA** [lingochamp/FileDownloader#437]
https://f.qr2c.cn/data/uploads/paper/2016/12/27/5861c2082ac92.zip

FileDownloader.FileDownloadMgr: can't continue 1159061853 file not suit, exists[FALSE], directory[FALSE]

FileDownloader.FileDownloadRunnable: On error 1159061853 javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by 10045125** [comment]
这是https，默认是不支持的，不过你可以自己加入。可以这样处理：
FileDownloader.init(appContext,
                new FileDownloadHelper.OkHttpClientCustomMaker() { // is not has to provide.
                    @Override
                    public OkHttpClient customMake() {
                        // just for OkHttpClient customize.
                        final OkHttpClient.Builder builder = new OkHttpClient.Builder();
                        // you can set the connection timeout.
                        builder.connectTimeout(CONNECTION_TIMEOUT, TimeUnit.MILLISECONDS);
                        builder.readTimeout(CONNECTION_TIMEOUT, TimeUnit.MILLISECONDS);
                        builder.writeTimeout(CONNECTION_TIMEOUT, TimeUnit.MILLISECONDS);
                        // you can set the HTTP proxy.
                        builder.proxy(Proxy.NO_PROXY);

                        //创建TrustManager
                        X509TrustManager xtm = new X509TrustManager() {
                            @Override
                            public void checkClientTrusted(X509Certificate[] chain, String authType) throws CertificateException {
                            }

                            @Override
                            public void checkServerTrusted(X509Certificate[] chain, String authType) throws CertificateException {
                            }

                            @Override
                            public X509Certificate[] getAcceptedIssuers() {
                                return new X509Certificate[]{};
                            }
                        };
                        //这个好像是HOST验证
                        X509HostnameVerifier hostnameVerifier = new X509HostnameVerifier() {
                            public boolean verify(String arg0, SSLSession arg1) {
                                return true;
                            }

                            public void verify(String arg0, SSLSocket arg1) throws IOException {
                            }

                            public void verify(String arg0, String[] arg1, String[] arg2) throws SSLException {
                            }

                            public void verify(String arg0, X509Certificate arg1) throws SSLException {
                            }
                        };
                        try {
                            // Install the all-trusting trust manager
                            final SSLContext sslContext = SSLContext.getInstance("TLS");
                            sslContext.init(null, new TrustManager[]{xtm}, new java.security.SecureRandom());
                            // Create an ssl socket factory with our all-trusting manager
                            final SSLSocketFactory sslSocketFactory = sslContext.getSocketFactory();
                            builder.sslSocketFactory(sslSocketFactory, xtm);
                            builder.hostnameVerifier(hostnameVerifier);

                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                        // etc.
                        return builder.build();
                    }
                });

**Comment by 10045125** [comment]
这个就是接受所有的证书，就能过正常下载https的文件链接

**Comment by Jacksgong** [comment]
- 1.3.9之前的版本使用OkHttp是默认支持的。
- 1.3.9 版本以后，默认的`FileDownloadUrlConnection`只是一个Demo的作用，默认是使用了`URL#openConnection` 去建立一个连接，默认情况下如果是Https的链接，是会实例化一个`HttpsURLConnection`的，而这个connection是有处理Https协议的请求的，你也可以通过`HttpsURLConnection#getServerCertificates`获取到当前的证书信息。

### 原因

我看你的错误信息应该是该域名的根证书不被信任。如果你的证书的根证书是不被信任的证书，你要绕过，完全可以自己实现FileDownloadConnection进行绕过。

### 可参看

默认是支持的，当然你也可以直接通过下载: https://github.com/lingochamp/FileDownloader/raw/master/art/Cause_of_Attached.png 进行简单的验证。

**Comment by byc4426** [comment]
FileDownloadUrlConnection 怎么设置   FileDownloadHelper.ConnectionCreator怎么传

**Comment by Jacksgong** [comment]
@byc4426 
![image](https://user-images.githubusercontent.com/6176417/39046966-c934a96e-44ca-11e8-9de6-4f8d0debce01.png)

**Comment by zuohp** [comment]
您好, 带有忽略SSL验证的FileDownloadUrlConnection 传入到filedownload中, 没有生效, 是我写的不对吗

**Comment by aldocano** [comment]
Can you please suggest what i need to change here to ignore self signed certificate ? 

`        FileDownloadLog.NEED_LOG=true;
        FileDownloader.setupOnApplicationOnCreate(this)
                .connectionCreator(new FileDownloadUrlConnection
                        .Creator(new FileDownloadUrlConnection.Configuration ()
                ))
                .commit();
`

**Comment by 793383996** [comment]
Can you please suggest what i need to change here to ignore self signed certificate ?

FileDownloadLog.NEED_LOG=true; FileDownloader.setupOnApplicationOnCreate(this) .connectionCreator(new FileDownloadUrlConnection .Creator(new FileDownloadUrlConnection.Configuration () )) .commit();

+1

**Comment by flyzend** [comment]
> @byc4426
> ![image](https://user-images.githubusercontent.com/6176417/39046966-c934a96e-44ca-11e8-9de6-4f8d0debce01.png)

一直在说自己定制，却从来不说怎么定制，我就是想知道怎么定制
