### ISSUE TITLE
FileDownloadHttpException存在Formatter不匹配的问题

### ISSUE THREAD

**Issue by aWangami** [lingochamp/FileDownloader#438]
https://github.com/lingochamp/FileDownloader/blob/master/library/src/main/java/com/liulishuo/filedownloader/exception/FileDownloadHttpException.java#L34

这里有三个占位符，但是只有两个参数，最新的1.3.9存在这个问题
如果下载出现错误的话，会导致二次异常
`super(FileDownloadUtils.formatString("response code error: %d, \n request headers: %s \n " +
                "response headers: %s", code, connection));`

**Comment by Jacksgong** [comment]
多谢反馈，是我疏忽了，我修复下这个。
