### ISSUE TITLE
粗略看了下，如果使用okhttp替换HttpURLConnection实现

### ISSUE THREAD

**Issue by MycroftWong** [lingochamp/FileDownloader#439]
请问如果想使用okhttp替换HttpURLConnection实现网络传输，那部分有没有抽象出来，需要实现哪个接口或重写哪部分代码？

**Comment by Jacksgong** [comment]
我今晚实现一个吧。

**Comment by MycroftWong** [comment]
@Jacksgong 您好，我现在的APP有一部分下载管理的功能，在写的时候发现下载过程中会出现一些可能的错误：断网、超时、进程被杀、内存满等，引起的最麻烦的问题是断点续传的问题，您是使用数据库中的数据来恢复下载的好像，下载之前又会检查文件是否被删除。
**因为我在写的时候遇到这么多的问题时常会感觉不知道从何入手，我想知道您在写这个库的过程中考虑的问题有哪些，又是怎样怎样解决这些问题的，希望您能传授一些经验，感谢**

**Comment by Jacksgong** [comment]
@MycroftWong 关于这个情况可以参考下: [README-iii-低内存情况](https://github.com/lingochamp/FileDownloader/blob/master/README-zh.md#iii-低内存情况)、还有[这里](https://github.com/lingochamp/FileDownloader/issues/410#issuecomment-269495704)以及相关参数配置: [download.min-progress-step与download.min-progress-time](https://github.com/lingochamp/FileDownloader/blob/master/README-zh.md#filedownloaderproperties)

**Comment by Jacksgong** [comment]
@MycroftWong 今晚后来有点事，现在太晚了，我晚上稍微写了一点，明天完善下单元测试以后发布，你关注这个repo: https://github.com/Jacksgong/filedownloader-okhttp3-connection

**Comment by MycroftWong** [comment]
@Jacksgong 您辛苦了，看了那部分说明，有些理解，还需要跟代码结合起来看。
另外已关注okhttp实现FileDownloadConnection的repo

**Comment by Jacksgong** [comment]
[filedownloader-okhttp3-connection](https://github.com/Jacksgong/filedownloader-okhttp3-connection) 已经Release 1.0.0了。
