### ISSUE TITLE
暂停下载以后如何恢复下载，默认不是断点续传，是重新下载

### ISSUE THREAD

**Issue by abc20899** [lingochamp/FileDownloader#44]
暂停下载以后如何恢复下载，默认不是断点续传，是重新下载

**Comment by Jacksgong** [comment]
你可以试下demo中是可以的。目前线上版本(0.2.0或者更低版本)的FileDownloader的断点续传是需要返回回来的response头部必须存在etag的，如果不存在etag就不支持断点续传了。(你可以检测下看看，你的`FileDownloadListener#connected`的回调中的etag是否为空。如果为空的话，可能需要你服务端添加下etag)。

**Comment by abc20899** [comment]
是空的  还有isContinue 的 false

**Comment by abc20899** [comment]
怎么在服务端添加呢

**Comment by Jacksgong** [comment]
服务端添加etag应该是比较简单的，你可以和你们服务端说下让他们支持下，一般根据不同的环境，下载Etag模块，稍作配置就可以了。
