### ISSUE TITLE
为什么FileDownloader.init 必须在 Application里面调用？

### ISSUE THREAD

**Issue by MycroftWong** [lingochamp/FileDownloader#441]
尝试在Splash里面调用，使用的是Application Context, 但是发现没有初始化，请问这是做了什么处理吗？

看了下源码，没看懂```FileDownloadUtils.isDownloaderProcess```方法的具体意思，能解释下这是什么意思吗？

**Comment by Jacksgong** [comment]
> `FileDownloader.init` 放到 Application 里面调用

是为了下载进程启动的时候，可以取到当前进程的`Context`。也是因为每个进程启动都会调用`Application`的生命周期。
