### ISSUE TITLE
How to delete file downloaded?

### ISSUE THREAD

**Issue by sinhpn92** [lingochamp/FileDownloader#443]
After I downloaded a file, i want delete this file. How can do this? `FileDownloadedUtils` can be support this function?

**Comment by Jacksgong** [comment]
- If the task has been completed downloading, all data about this task will be removed from the internal database. So if the task has been completed downloading, you just delete its file, if you use the default path to store it, it would be `FileDownloadUtils#getDefaultSaveFilePath`.
- If the task is paused(didn't complete downloading yet), some data about this task is stored in the internal database, in this case, if you want to clear its data in the internal database and delete its file, just invoke: `FileDownloader#clear`.
