### ISSUE TITLE
使用FileDownloadSampleListener的回调方法progress时，偶尔会出现进度反转的情况

### ISSUE THREAD

**Issue by lsw645** [lingochamp/FileDownloader#447]
@Override
                    protected void progress(BaseDownloadTask task, int soFarBytes, int totalBytes) {
                        super.progress(task, soFarBytes, totalBytes);
                        ((ViewHolder) task.getTag()).updateProgress(soFarBytes, totalBytes,
                                task.getSpeed());
                        Logger.d("soFarBytes: "+soFarBytes+"\ntotalBytes: "+totalBytes);
                        if(soFarBytes!=-1){
                            mAppDownLoadInfo.setMax(totalBytes);
                            mAppDownLoadInfo.setProgress(soFarBytes);
                            mAppDownLoadInfo.setStatus(2);//2的状态为app尚未下载完成的状态
                            int progress = 100 * soFarBytes / totalBytes;
                            mTv_progress.setText(progress + "%");
                            if (soFarBytes == totalBytes) {
                                mTv_progress.setText(100 + "%");
                            }
                        }

                    }

mTv_progress设置下载的进度数字时，有一定几率，进度会一直往下减（比如下载到80%时，进度会一直往下减，79，78，77...这样下去）

**Comment by Jacksgong** [comment]
**根据你的代码，很有可能是两个完全不同的任务，放到了同一个View中显示**，导致一会儿显示任务A的进度，一会儿显示任务B的进度，以至于导致这个问题。

对于同一个任务而言内部机制:

- 同时启动两个相同的任务，第二个相同的任务会直接回调`warn`，如果第一个已经下载完成，便会直接回滴`completed`
- 如果是同一个任务的进度，所有的消息都是FIFO的。
