### ISSUE TITLE
请问怎样获取返回的header信息

### ISSUE THREAD

**Issue by shiweibsw** [lingochamp/FileDownloader#449]
请问怎样获取返回的header信息

**Comment by Jacksgong** [comment]
目前确实在回调中，或是显式的接口中没有获取header的方法。 

---

#### 这块目前没有接口的原因是: 

并不是每个人都需要获知所有的返回header的信息，因此如果每个任务都从Service回传response的header到任务对象，似乎有些得不偿失。

#### 不过目前的情况是有办法获取到的:

你可以通过实现自己的`FileDownloadConnection`(或者仅仅是继承`FileDownloadUrlConnection`)，注册到FileDownloader中，在`FileDownloadConnection`中就可以取到所有任务的网络相关的一切，包括返回的`header`。

但是有一点需要注意，如果默认情况，`FileDownloadConnection`是用在独立进程的，如果你希望也是在主进程，在`filedownloader.properties`中配置即可。

##### 当然了，一般情况下:

- 你可以获取到`ETag`，`totalBytes`(这个是`content-length`)
- 如果你指定你的存储路径是目录，你的文件的filename，是从`Content-Disposition`中取下来的
- 如果下载过程中遇到`FileDownloadHttpException`的错误，是会带回当时的request的header与response的header的。

---

你可以谈谈你的场景与理由？这边我们有考虑新增这么一个接口。

**Comment by shiweibsw** [comment]
比如header中可以取到下载文件的最后一次修改时间啊，在某些场景下文件需要进行检查更新的功能，使用接口的话有些得不偿失了，可以把这个时间记录到本地，当服务器文件修改后如果header返回的时间和本地时间不匹配了就会自动重新下载最新文件。你觉得怎样？

在 2017年1月12日 下午8:03，Jacksgong <notifications@github.com>写道：

**Comment by Jacksgong** [comment]
@shiweibsw 

> 可以把这个时间记录到本地，当服务器文件修改后如果header返回的时间和本地时间不匹配了就会自动重新下载最新文件

如果目的是为了验证资源的有效性，目前下载引擎中记录的Etag就是为了验证断点续传的有效性。若是Etag在服务端没有通过校验，就会自动从头开始下载。

**Comment by lanlan-yang** [comment]
我还说，怎么找不到这个方法。。。
