### ISSUE TITLE
How to set the connection time out?

### ISSUE THREAD

**Issue by 244317809** [lingochamp/FileDownloader#45]
By default, it will time out after 10s, I need a value longer for this, how can i achieve it? thanks in advance.

**Comment by Jacksgong** [comment]
Ref [DemoApplication](https://github.com/lingochamp/FileDownloader/blob/master/demo/src/main/java/com/liulishuo/filedownloader/demo/DemoApplication.java)

**Comment by Jacksgong** [comment]
Any problem?

**Comment by 244317809** [comment]
I had read the demo, and try it. But no luck, the time out mills still be set by default(10s), here is my snippet:
builder.connectTimeout(60000, TimeUnit.MILLISECONDS);

**Comment by Jacksgong** [comment]
Did you get the `FileDownloadMgr#client` to check the connect timeout value ( `FileDownloadMgr.client.connectTimeoutMillis()` ) , because it is handled by OkHttpClient, FileDownloader just ensure this value is right. ( I checked, it was right.)

>  P.S: You can attach debugger to `com.liulishuo.filedownloader.demo:filedownloader` process, and add BreakPoint in `FileDownloadMgr#start` to find the value.

**Comment by 244317809** [comment]
I will try it, thanks for your help.  :)

**Comment by 244317809** [comment]
I found a new issue. I create a download queue and set a listener to update the progress bar, the listener's `pending()` was invoked, but the **first task's** param `totalBytes` was **0**, but it only occur for the first task, for the next other task, it return the correct totalBytes.

**Comment by Jacksgong** [comment]
If you downloaded the file, you will receive the `totalBytes` from the DB, which got from the last time download, otherwise if will be default value `0`.

**Comment by 244317809** [comment]
how can I get the **total bytes in a queue** when the download started in the first beginning ?

**Comment by Jacksgong** [comment]
Sorry, we can't. It is provided by Http-response originally. We get it one by one for tasks with each establishes connection.

If you download in a queue, sometimes it is just like chunked-data, so in this case, if you really need the total bytes in a queue,  you maybe need though a single another request to get it.
