### ISSUE TITLE
java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out)

### ISSUE THREAD

**Issue by axuan2015** [lingochamp/FileDownloader#450]
java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out)
at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:545)

网上分析:
原因：1、服务器中断
　　　2、网络连接非常慢的时候
　　　3、下载大文件时，频繁请求服务器，请求的端口一直被占用
请问 最可能出现哪一种？我怎样解决？

**Comment by Jacksgong** [comment]
这个网络错误与FileDownloader没有太大关系，如果你希望让连接超时的阀值更久些，可以参考下`DemoApplication`中，通过`FileDownloadUrlConnection.Configuration#connectTimeout`对这个值的配置。
