### ISSUE TITLE
现在有多个正在下载的任务，如何给每个任务添加多个listener？

### ISSUE THREAD

**Issue by yinyongliang** [lingochamp/FileDownloader#451]
我看了你的model中的TasksManagerDemoActivity.java类，不定时的下载多个任务。而我现在的需求就是类似于应用市场，跳转到另外一个页面，也可以观察到某个task的进度，新手望指教
![screenshot_2017-01-11-17-36-19-566_com tencent an](https://cloud.githubusercontent.com/assets/19798433/21843319/8d28b4dc-d825-11e6-8d2a-332f7d330677.png)
![screenshot_2017-01-11-17-36-29-068_com tencent an](https://cloud.githubusercontent.com/assets/19798433/21843324/8fd9e1c4-d825-11e6-8d8e-17216bada09d.png)

**Comment by Jacksgong** [comment]
参考下这里即可: https://github.com/lingochamp/FileDownloader/issues/103#issuecomment-209173124
