### ISSUE TITLE
download file in service with notification

### ISSUE THREAD

**Issue by DJafari** [lingochamp/FileDownloader#452]
thanks for your great library;

if possible, add a demo for `startForeground` option with notification (with progress) for each of downloads

**Comment by keeponZhang** [comment]
hi,do you have accomplish that by yourself?i have a need like that。

**Comment by weituotian** [comment]
i thnk it is hard to do that!

the library is not so open!
is not friendly to developer

**Comment by rantianhua** [comment]
Actually, there are notification relative samples in the demo. For example, `NotificationMinSetActivity` has shown you how to bind a notification with a downloading task through as little code as possible. `NotificationSampleActivity` has shown you how to control and custom the notification as you want. Both of the samples demonstrate downloading a single task. However, you can change the code to download multiple tasks, and then you will see there is a notification for every task.
