### ISSUE TITLE
看源码感受

### ISSUE THREAD

**Issue by caopeng000** [lingochamp/FileDownloader#453]
哎当初看0.3.2的时候，感觉代码挺符合我胃口的，分包和子线程切换主UI线程，还有HttpUrlConnection，切换线程我看你是通过接口中的静态内部类通过Handler去实现的，刚才更新了你最新的代码，第一感觉，看不懂了。分包和业务不相关了。总体来说第二个版本更高大上，利用了接口编程，不过我暂时还没找到，切换线程的方法在哪里

**Comment by Jacksgong** [comment]
你可以关注下这个Issue的迭代: #442

你所说的切换线程，是什么的切换线程，我不是很明白。

- 如果是全局线程监控。目前Demo中已经引入了[ThreadDebugger](https://github.com/Jacksgong/ThreadDebugger)，因此你可以直接通过Logcat中看到线程的切换。
- 如果是全局线程相关的创建，目前所有的线程池都是创建自 `FileDownloadExecutors`，仅仅只有 线性队列任务所用到的`HandlerThread`不是从这里创建的。

**Comment by Jacksgong** [comment]
关于代码架构: 

你可以关注下这个Issue的迭代: #442

#### 现在代码的架构相比之前:

- FileDownloadService相关 - 基本没有变化
- 消息流层面 - 基本没有变化
- 用户可见上层 - 上次调整为面向接口编程，当时考量点是两点: 1. Java-Doc更加好看; 2. 内部调用更加严谨。

---

那么为什么又有了 #442 呢？

- 由于接口拆分，导致看起来更复杂了，可读性间接变低
- 面向接口编程，在没有JIT的设备中，相比直接访问对象类(如HashMap map)，会慢6%，但是在存在JIT的设备中，两者的速度差不多。但是内存占用方面面向接口变成会消耗更多内存。
