### ISSUE TITLE
请问FileDownloadQueueSet是不是适用于一次性的下载任务啊

### ISSUE THREAD

**Issue by xanaduo** [lingochamp/FileDownloader#455]
我看到例子中FileDownloadQueueSet的任务是一次性添加进去的，然后一起启动下载。如果我要实现动态添加下载任务到FileDownloadQueueSet中，是不是要重新new FileDownloadQueueSet啊？

**Comment by Jacksgong** [comment]
> 请问FileDownloadQueueSet是不是适用于一次性的下载任务啊?

是的。

---

动态添加，删除任务:

- 对于并行任务而言，原本的每个任务在全局都是并行的，你可以动态的停止或启动。
- 对串行任务队列而言，使用`FileDownloadSerialQueue` 就支持动态的添加/删除队列中的任务。

**Comment by xanaduo** [comment]
@Jacksgong 添加/删除队列中的任务，能再详细点吗？我在FileDownloadSerialQueue没有找到添加或删除任务的方法啊。难得是操作FileDownloadSerialQueue设置的downloadTasks列表吗？

**Comment by Jacksgong** [comment]
`FileDownloadSerialQueue` 里面 public的方法都有java-doc，你可以自己看下。

主要就三个方法: 

- `enqueue`: 进入队列
- `getWorkingTaskId`: 当前运行中的任务Id
- `shutdown`: 停用与释放`FileDownloadSerialQueue`。

至于删除，你直接通过`BaseDownloadTask#pause`，或者`FileDownloader#pause`，就可以了。

**Comment by xanaduo** [comment]
@Jacksgong 哦哦，看成FileDownloadQueueSet了，但是FileDownloadSerialQueue这个跟FileDownloadQueueSet貌似没什么关系啊，怎么用呢。作者下载更新的例子的时候能不能把动态添加下载任务加上去啊。

**Comment by Jacksgong** [comment]
@xanaduo `FileDownloadSerialQueue`一共就100多行代码，都有源码，public的方法也都有java-doc了，你可以自己尝试看看代码，这个Queue太简单了，demo显得比较多余。

如果你有不同特性的feature，也可以自己实现一个类似的队列类，实现起来也简单。

**Comment by mityao** [comment]
现在也遇到了动态添加下载任务的问题，对于FileDownloadSerialQueue一头雾水，能否给个例子如何使用FileDownloadSerialQueue @Jacksgong @xanaduo 先谢过！

**Comment by mityao** [comment]
NVM!琢磨出来了！
