### ISSUE TITLE
大神，请教二个问题

### ISSUE THREAD

**Issue by PiPiCaptain** [lingochamp/FileDownloader#457]
我有二个Activity，A_Activity和B_Activity，B_Activity有一个进度条显示当前下载进度，当B_Activity返回A_Activity时，1.下载不暂停 2.重新回到B_Activity时，B_Activity的进度条控件能接着当前下载进度，继续显示

不知道，大神你理不理解我在说什么，哈哈。请问这二个功能，怎么实现？

**Comment by PiPiCaptain** [comment]
能否出个Demo？

**Comment by PiPiCaptain** [comment]
我浏览了一些issue，找到答案了，谢谢

**Comment by Jacksgong** [comment]
okay.
