### ISSUE TITLE
Check if there is enough free space

### ISSUE THREAD

**Issue by diabloo** [lingochamp/FileDownloader#46]
hi,
i'am using your library to download some file( 5-10 MB) and i want to check if there is enough free space before starting download is this possible or i sould check this in progress

and how to stop a download in case there is no space

**Comment by Jacksgong** [comment]
Year,  you don't need to check, but you will receive `error` call-back on FileDownloadListener when there is no enough free space to write buffers, on the current version(0.2.0).

**Comment by Jacksgong** [comment]
Thanks for your reminder, On the next version, I will throw `error` call-back directly when checking out the free space is less than `content-length` before start fetch datum for NON 'Chunked transfer encoding' one.

**Comment by yangwuan55** [comment]
it's useful.

**Comment by Jacksgong** [comment]
Enhanced in [v0.2.1](https://github.com/lingochamp/FileDownloader/releases/tag/v0.2.1).
