### ISSUE TITLE
SD card support

### ISSUE THREAD

**Issue by Jeffin21** [lingochamp/FileDownloader#464]
Please show a demo that download files to SD card. Thank You

**Comment by Jacksgong** [comment]
.............. Sorry, it's too easy to need to show the special demo. 


---

If you want to download files to the root of SD card, please make sure two things:

1. Using `BaseDownloadTask#setPath` to set the path to store downloading file.
2. Make sure you have been declared the `android.permission.WRITE_EXTERNAL_STORAGE` and the `android.permission.READ_EXTERNAL_STORAGE` permission correctly in the `AndroidManifest`.

**Comment by Jeffin21** [comment]
i mean DocumentFile to support direct download.

**Comment by Jacksgong** [comment]
@Jeffin21 Oh... I know now, you can vote this issue: #349  and I will support that as soon as possible.
