### ISSUE TITLE
Stop download when an error occurs in queue

### ISSUE THREAD

**Issue by Trinkes** [lingochamp/FileDownloader#465]
Hi,
I have a queue of downloads and i would like to make all downloads of the queue to stop where there is an error.
Ex: we have a queue with 2 downloads (Download A and Download B)
-Download A starts
-Download A has an error
-Download B doesn't even start

Is there any way to do that?

Thanks

**Comment by Jacksgong** [comment]
It is very simple, Just invoke `FileDownloader.getImpl().pause(listener)` when you receiving the callback of `FileDownloadListener#error`.

**Comment by Trinkes** [comment]
If i do that, the download B will call the `FileDownloadListener#pause`, i want to avoid that.

**Comment by Trinkes** [comment]
If i do that way, the download B will call `FileDownloadListener#pause`, i want to avoid that.

**Comment by Jacksgong** [comment]
@Trinkes For FileDownloader your task is real paused, so callback pause is meet the most expect, If your feature need to ignore such callback, I think you need to ignore it by yourself.
