### ISSUE TITLE
Slow file download speed on big size 

### ISSUE THREAD

**Issue by Jeffin21** [lingochamp/FileDownloader#466]
Having slow speed file download write problem when i try to download files more than 800 MB

**Comment by Jacksgong** [comment]
It's no different to others unless the file is larger than 1.99GB(If the file larger than 1.99GB, all arguments are used for store download length will be switch from `Integer` to `Long`

---

So If you want to speed up downloading, please move to [here](https://github.com/lingochamp/FileDownloader/wiki/Optimize-Tutorial).
