### ISSUE TITLE
下载链接出现中文，无法下载

### ISSUE THREAD

**Issue by a483210** [lingochamp/FileDownloader#468]
1.3.9,1.4.0,1.4.1均出现该问题
1.3.0可以下载

**Comment by Jacksgong** [comment]
你先使用这个组件看看是否就解决了: https://github.com/Jacksgong/filedownloader-okhttp3-connection

我空了给你看下。

**Comment by a483210** [comment]
可以解决，谢谢

**Comment by Jacksgong** [comment]
嗯。这个是因为新版本中默认的`FileDownloadConnection`组件使用了`URLConnection`，如果不想使用okhttp，依然想要使用默认的`FileDownloadConnection`组件，对连接中包含中文部分进行编码处理再传入即可。
