### ISSUE TITLE
下载时如何获取下载文件的流？

### ISSUE THREAD

**Issue by MUFCRyan** [lingochamp/FileDownloader#469]
我现在需要在下载时实时获取所下载文件的字节流，有相应的方法或回调吗？

**Comment by Jacksgong** [comment]
嗯，可以的，只要你定制自己的输出流组件(或者网络连接组件)即可，可以参考下[这里](https://github.com/lingochamp/FileDownloader/wiki/Open-Customized-Component)的`OutputStream`(或`Connection`)。

**Comment by MUFCRyan** [comment]
我看了一下FileDownloadBufferOutputStream的write方法，里边是需要byte[] bytes参数的，这个参数正是我需要的，所以我无法传入，有类似Demo吗？我想参考一下

**Comment by Jacksgong** [comment]
你可以参考下[FileDownloadRandomAccessFile](https://github.com/lingochamp/FileDownloader/blob/master/library/src/main/java/com/liulishuo/filedownloader/stream/FileDownloadRandomAccessFile.java)，这个是外面传进来的，`OutputStream`处理的就是把传进来的数据写入文件。

**Comment by Jacksgong** [comment]
写好了以后，在初始化的时候，通过[这个](https://github.com/lingochamp/FileDownloader/wiki/Open-Customized-Component#how-to-valid-it)注入你的`outputStream`组件即可。

**Comment by MUFCRyan** [comment]
Maker 内部实现的是一个OKHttpClient
![image](https://cloud.githubusercontent.com/assets/16255045/22675960/8d9a848c-ed23-11e6-9cbe-05aba842fbf2.png)，你的意思是我自定义一个OKHttpClient并在里边实现我的需求吗？对下载这块不是太懂有点晕。。。

**Comment by Jacksgong** [comment]
@MUFCRyan 你这个是旧的代码（新的代码已经没有`OkHttpClientCustomMaker`之类的了）(这个是网络组件（不是`OutputStream`组件）的前身)

**Comment by Jacksgong** [comment]
用最新版本，很简单的。

#### 第一步

 参考[FileDownloadRandomAccessFile](https://github.com/lingochamp/FileDownloader/blob/master/library/src/main/java/com/liulishuo/filedownloader/stream/FileDownloadRandomAccessFile.java)实现自己的`OutputStream`组件
#### 第二步

初始化时注入需要注入的组件:

```java
FileDownloader.init(getApplicationContext(), new DownloadMgrInitialParams.InitCustomMaker()
        .database(/*可传入数据库组件*/)
        .outputStreamCreator(/*可传入输出流组件*/)
        .connectionCreator(/*可传入网络组件*/));
```
