### ISSUE TITLE
断点续传时候怎么再开启任务

### ISSUE THREAD

**Issue by MrLiKH** [lingochamp/FileDownloader#47]
看您在文档说调用pause再次调用start即可自动断点续传
我调用这句之后 FileDownloader.getImpl().pause(downloadId);
请问一下我在怎么开启这个downloadId任务。。
我的需求就是 wifi断开再次连接可以自动续传。。。

**Comment by Jacksgong** [comment]
你检测到wifi连接了以后，直接重新start就可以了。传入相同的url与存储路径。

**Comment by MrLiKH** [comment]
哦哦 再次传入就会自动续传是吧？
我以为有类似这种方法FileDownloader.getImpl().start(downloadId);

**Comment by Jacksgong** [comment]
恩。作为一个新任务传入就可以了。里面是根据 路径与url 作为key的。如果识别到可以断点续传，默认都是走断点续传的。

**Comment by MrLiKH** [comment]
谢谢耐心解答

**Comment by Jacksgong** [comment]
:)

**Comment by passself** [comment]
first task reuse, then start
