### ISSUE TITLE
不同的url 但是返回下载的filename相同 文件会被覆盖

### ISSUE THREAD

**Issue by lzmlxt** [lingochamp/FileDownloader#471]
setPath(url,true)的时候 传入不同的url 但是url返回下载的filename相同 文件会被覆盖

**Comment by Jacksgong** [comment]
好的，我知道你的情况了，多谢你的反馈。

首先，第二个参数为`true`说明**所传入的是文件存储的文件夹路径**，存储的文件夹相同，文件名也相同，那么他们最终的存储路径肯定是相同的。

但是Url不同，因此就会被认定为两个不同的任务(我们定义这两个任务为`TaskA`与`TaskB`)。

#### 确实在两个相同存储路径的任务被启动时，改文件会同时被两个任务同时写入

目前的情况: 后完成的任务肯定会在写完所有数据时，因为最后的文件大小检测时失败而回调`error`从而下载失败。

#### 解决方案: 

我这边在下个版本中会进行保护，一个文件在只允许被FileDownloader中的一个任务写入，当有另外一个任务要写入时直接回调`error`。

在因为这个原因被回调`error`后，如果你想要依然想要下载这个任务，你可以启动一个修改了存储路径的任务（这个时候如果你`setPath(url,true)`已经是可以通过`BaseDownloadTask#getFilename()`获取到文件名了）。

**Comment by lzmlxt** [comment]
通过setPath(url)来设置？

**Comment by Jacksgong** [comment]
@lzmlxt 不好意思打错了，已经修改了，那个`adoptPath`应该是根据`BaseDownloadTask#getFilename()`返回的名字，适配的一个不同名的名字，防止覆盖。
