### ISSUE TITLE
已经创建的任务，如何更改header？

### ISSUE THREAD

**Issue by JaminFan** [lingochamp/FileDownloader#472]
目标文件下载是需要header的支持的，但是header会存在更改的情况。在header更改的情况下，正在下载的任务还能正常下载完，但是在队列中的任务将无法继续下载。请问下这种情况下我如何可以修改header？

**Comment by Jacksgong** [comment]
不好意思不是很明白你的意思。

如果需要添加header，可以通过`BaseDownloadTask#addHeader`进行添加或通过`BaseDownloadTask#removeAllHeaders(name)`移除相关header，如果请求头不同，可以创建多个任务带上不同的请求头即可。

**Comment by JaminFan** [comment]
我现在的情况是这样的，我创建了多个下载任务，创建时都添加了header，header的主要内容是相关的token，在下载过程中，因特殊情况，token发生了改变，所以创建任务时候添加的token已经无效，这时未开始下载的任务（在下载队列中）无法继续下载。我想问的是，能否在创建了任务之后，再次修改这个下载任务的header来更新token？

**Comment by Jacksgong** [comment]
Okay，我明白你的意思了。

### 解决方案

直接pause整个队列，然后直接创建并启动带上新`token`的新的队列(如果之前下载一半的，默认会自动断点续传)

#### 如果任务集是串行任务，还有一个解决方法（不推荐）

- **已经启动的任务，是无法修改的**，但是还在等待队列的任务，直接修改`BaseDownloadTask`对象的header即可(通过前面提到的`BaseDownloadTask#addHeader`与`BaseDownloadTask#removeAllHeaders(name)`。

**Comment by JaminFan** [comment]
感谢回答，我明白你的意思了，还有点疑问，第二个解决办法修改BaseDownloadTask对象的header，应该是在下载监听方法里修改？progress之前？说下不推荐这个方法的理由吗？

**Comment by Jacksgong** [comment]
#### 1. 第二个解决办法修改BaseDownloadTask对象的header，应该是在下载监听方法里修改？progress之前？

串行任务，只有一个任务会在运行，其余的任务都在主进程队列中（还没有被抛到FileDownloadService）修改都有效。

#### 2. 能说下不推荐这个方法的理由吗？

虽然未被启动的任务，已经修改了，但是由于有可能正在运行的任务，正在运行时，token刚好也失效了，那么正在运行的那个任务就会因为token失效而失败。

**Comment by JaminFan** [comment]
哦，明白了，谢谢
