### ISSUE TITLE
清理大师清理内存会将下载进程kill掉， 没有任何回调？ 导致ui显示有很大问题，请问有解决方案吗？ 

### ISSUE THREAD

**Issue by dinuscxj** [lingochamp/FileDownloader#475]

**Comment by Jacksgong** [comment]
#### 有的，两个解决方案:

1. 通过[filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)中的`process.non-separate`，将下载服务放到主进程中
2. 通过`FileDownloader#startForeground(id:int, notification:Notification)`将下载进程中的下载服务配置为前台服务

**Comment by dinuscxj** [comment]
还是拦不住清理

**Comment by Jacksgong** [comment]
我不是很明白。

#### 如果采用方案一(`通过filedownloader.properties中的process.non-separate=true，将下载服务放到主进程中`)

那么压根就不存在下载进程

#### 如果采用方案二(`通过FileDownloader#startForeground(id:int, notification:Notification)将下载进程中的下载服务配置为前台服务`)

那么这个是类似后台音乐播放的解决方案，下载服务所在进程（下载进程）会从`服务进程`一跃变为保护优先级最高的`前台进程`，如果"大师清理"，连前台进程都清理，那么本来就不符合Android的设计以及用户的预期。

**Comment by dinuscxj** [comment]
如果采用方案一(通过filedownloader.properties中的process.non-separate=true，将下载服务放到主进程中) 使用清理大师之后， 使用charles 抓包， 显示下载暂定。

**Comment by dinuscxj** [comment]
第二种方案没有尝试。 请问有不设置notification直接设置前台的进程方式吗？

**Comment by Jacksgong** [comment]
@dinuscxj 那我知道了，应该是方案一，主进程退入后台以后变为`服务进程`，依然被"清理大师"杀。

#### 请问有不设置notification直接设置前台的进程方式吗？

目前必须要提供notification，因为这个是Android强制的规范，希望在后台做高level的事情能被用户所知。

既然用户主动促发了"清理大师"的清理，非`服务进程`被杀也是符合用户预期的，因此没有必要在这里过度设计。

**不推荐**: 但是如果非要做，可以采用一些hacker（国内同病做法）的方式，如通过监听系统事件/content-provider，或持有文件锁，或者通过系统Api: `JobSchedule`、`AlarmManager`、`SyncAdapter`等等方式来保活自己的某一个进程，这样即便是下载进程被杀，就主动再启动一次所有任务，这样自动会断点续传的。
