### ISSUE TITLE
发现一个状态bug

### ISSUE THREAD

**Issue by lzmlxt** [lingochamp/FileDownloader#478]
第一次下载完成一个文件 然后删除这个文件 重新下载 然后在FileDownloadListener返回的BaseDownloadTask这个对象中获取status全部返回-3完成的状态 不管是progress(BaseDownloadTask task, int arg1, int arg2)这个方法中调用task.getStatus()

**Comment by Jacksgong** [comment]
请问你使用的FileDownloader的版本是哪个版本？最新版本同一个任务一旦完成是没有任何的记录的，应该没有任何影响猜对的。

**Comment by lzmlxt** [comment]
用是1.4.0 打印出来的状态都是-3

**Comment by Jacksgong** [comment]
你是指删除了之后，重新下载时监听器里面回调回来的对象状态都是-3，还是说删除了之后，再调用缓存的之前下载时从监听器取到的对象，这个对象的状态都是-3呢？

**Comment by lzmlxt** [comment]
下载完成之后把本地文件删除之后重新在下载这个url 监听器里面回调回来的对象状态都是-3

**Comment by Jacksgong** [comment]
@lzmlxt 不好意思我无法复现你的问题。我检查代码这边检测是否下载完成也仅仅是通过本地文件是否存在。


可否提供一个 可复现该问题的 一个简单的 项目(提供github地址，或发邮件给我igzhenjie@gmail.com)。 我这边跑下，认真看看到底是哪里的问题。

**Comment by lzmlxt** [comment]
出差了一段时间 我这几天整一个简单的项目在测试一下 如果有问题就发你邮箱

**Comment by lzmlxt** [comment]
@Jacksgong 写了demo没有能复现 我项目改成最新的1.4.1在看下

**Comment by Jacksgong** [comment]
@lzmlxt 好的。谢谢
