### ISSUE TITLE
你好 我点击下载后总是报这个空指针

### ISSUE THREAD

**Issue by nakisaren** [lingochamp/FileDownloader#48]
已经在application里面初始化，在manifest里面注册了服务。想知道还有什么给遗漏的吗？

03-08 09:14:14.136: W/System.err(4268): java.lang.NullPointerException
03-08 09:14:14.136: W/System.err(4268): 	at android.content.ComponentName.<init>(ComponentName.java:77)
03-08 09:14:14.136: W/System.err(4268): 	at android.content.Intent.<init>(Intent.java:3813)
03-08 09:14:14.136: W/System.err(4268): 	at com.liulishuo.filedownloader.services.BaseFileServiceUIGuard.bindStartByContext(BaseFileServiceUIGuard.java:128)
03-08 09:14:14.136: W/System.err(4268): 	at com.liulishuo.filedownloader.services.BaseFileServiceUIGuard.bindStartByContext(BaseFileServiceUIGuard.java:120)
03-08 09:14:14.140: W/System.err(4268): 	at com.liulishuo.filedownloader.FileDownloadTask._checkCanStart(FileDownloadTask.java:106)
03-08 09:14:14.140: W/System.err(4268): 	at com.liulishuo.filedownloader.BaseDownloadTask._start(BaseDownloadTask.java:586)
03-08 09:14:14.140: W/System.err(4268): 	at com.liulishuo.filedownloader.BaseDownloadTask.access$000(BaseDownloadTask.java:37)
03-08 09:14:14.140: W/System.err(4268): 	at com.liulishuo.filedownloader.BaseDownloadTask$1.callback(BaseDownloadTask.java:97)
03-08 09:14:14.140: W/System.err(4268): 	at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.trigger(DownloadEventPoolImpl.java:192)
03-08 09:14:14.144: W/System.err(4268): 	at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.publish(DownloadEventPoolImpl.java:128)
03-08 09:14:14.144: W/System.err(4268): 	at com.liulishuo.filedownloader.FileDownloadEventPool.publish(FileDownloadEventPool.java:111)
03-08 09:14:14.144: W/System.err(4268): 	at com.liulishuo.filedownloader.FileDownloadEventPool$1.run(FileDownloadEventPool.java:68)
03-08 09:14:14.144: W/System.err(4268): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
03-08 09:14:14.144: W/System.err(4268): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
03-08 09:14:14.144: W/System.err(4268): 	at java.lang.Thread.run(Thread.java:841)
03-08 09:14:14.168: E/FileDownloader.FileDownloadList(4268): remove error, not exist: 1996760519@com.liulishuo.filedownloader.FileDownloadTask@4a870f0c

**Comment by Jacksgong** [comment]
#43
