### ISSUE TITLE
when run  FileDownloader.getImpl()... .start() have app crash

### ISSUE THREAD

**Issue by yyyuuu777** [lingochamp/FileDownloader#480]
when run  FileDownloader.getImpl()... .start() have app crash

**Comment by Jacksgong** [comment]
Could you please paste your exception stack message?

---

> P.S. You can run the demo project to check out what's differ with yours

**Comment by yyyuuu777** [comment]
sorry,i have resolver the issue ,because init at activity

**Comment by Jacksgong** [comment]
Okay.
