### ISSUE TITLE
能搞个简单点的api么?

### ISSUE THREAD

**Issue by liupeng110** [lingochamp/FileDownloader#481]
之前的不变,再加个
有loading   success   failed 三个回调的就可以
回调有点多了,一大坨啊

**Comment by Jacksgong** [comment]
你可以使用`FileDownloadSampleListener`，然后覆写自己想要用到的回调，或者是继承`FileDownloadListener` 封装任何你觉得可以简化你需求的监听器。

**Comment by liupeng110** [comment]
能加一个么,这需求也是刚需

**Comment by Jacksgong** [comment]
之前的`FileDownloadSampleListener`就是这个目的了。你继承`FileDownloadSampleListener`，默认情况下不用实现任何接口。

**Comment by liupeng110** [comment]
直接new FileDownloadSampleListener ?

**Comment by liupeng110** [comment]
ok了  直接new  FileDownloadSampleListener   多谢

**Comment by Jacksgong** [comment]
好的。

```java
FileDownloader.getImpl()
  .create(url)
  .setListener(new FileDownloadSampleListener(){

    @Override
    protected void pending(BaseDownloadTask task, int soFarBytes, int totalBytes) {
      // do something you want.
    }  
  })

```

如果你只关心是否结束，也可以直接使用`BaseDownloadTask#FinishListener`即可。

**Comment by liupeng110** [comment]
对了,有没有考虑数据库用orm进行重构 ?

**Comment by Jacksgong** [comment]
嗯。有考虑过用户有类似情况，考虑优化性能之类的，目前数据库是支持用户直接定制的。

你可以通过实现相关的接口，来使用任何你想要的数据库类型(甚至你不想固化数据，全部存储在内存缓存中，都可以): 参考[这里](https://github.com/lingochamp/FileDownloader/wiki/Open-Customized-Component)

---

Ref: #157

**Comment by liupeng110** [comment]
好的,多谢咯 我看看
