### ISSUE TITLE
dex 加载完成之前启动服务

### ISSUE THREAD

**Issue by dinuscxj** [lingochamp/FileDownloader#482]
我们的应用由于方法输超过65535，所以我们分成多个dex， 在dex初始化完成之后再对filedownloadmanager进行初始化， 发现咱们的下载服务有可能（概率很低）会在dex加载完成之前尝试启动， 导致崩溃， 所以想知道服务启动的时机

**Comment by Jacksgong** [comment]
初始化(`FileDownloader#init`)是不会启动服务。

启动服务只会在以下时机启动:

1. 主动调用`FileDownloader#bindService`、`FileDownloader#insureServiceBind`进行启动服务
2. 服务没有被主动启动过，开始下载第一个任务
3. 在下载过程中，下载进程(服务进程)由于系统进程调度机制被杀，但是这时主进程(前台进程)还在，并且主进程中还有任务没有消化掉，此时会尝试修复；或者其他下载被异常中断的修复情况: [Low Memory?](https://github.com/lingochamp/FileDownloader/wiki/Low-Memory%3F)
