### ISSUE TITLE
关于下载歌曲当歌曲本身含有专辑图片的时候

### ISSUE THREAD

**Issue by lastshrek** [lingochamp/FileDownloader#483]
您好，最近在做安卓的音乐下载，我想问一下当我源文件本身含有专辑图片的时候，下载下来发现并没有，请问有什么方式可以解决这个问题嘛？因为专辑封面就是生产力呀。

**Comment by Jacksgong** [comment]
这个并非FileDownloader引擎的问题。

对于这个问题，建议通过一下方式解决:

1. 抓包看看服务端返回的数据: 推荐工具mitmproxy、Charles
2. 对下载文件做hash校验，可以考虑将`etag`(类似七牛的做法)定义为关联文件hash值，这么一来推荐在`FileDownloadListener#blockComplete`回调中做hash值校验
3. 审视自己的实现，FileDownloader本身只负责将文件正确的完成下载，并不进行解析无论是音乐还是视频还是其他类型的文件，因此你看看是否需要进行额外的解析或适配

**Comment by lastshrek** [comment]
因为您的库是我用来下载的第二个库，之前用的是okgo，当我使用okgo的时候下载下来的文件是带有专辑封面的，但是相同的实现方式用您的库就没有了，服务端是我自己写的，只返回一个文件的url，然后这个url对应我自己ftp上的一个mp3文件。

**Comment by Jacksgong** [comment]
这个应该和下载引擎没有直接关系，如果okgo做了相关的音乐模块的支持，你可以参看下。
