### ISSUE TITLE
当应用被杀死，如何恢复原先正在进行的下载任务！

### ISSUE THREAD

**Issue by mlzhang920802** [lingochamp/FileDownloader#484]

**Comment by mlzhang920802** [comment]
当我在下载过程中强制结束应用进程时，再进入app下载界面点击暂停，输出W/FileDownloader.FileDownloader: request pause but not exist 1937936575，如何能让下载任务在被强制回收之前自动暂停所有正在下载任务呢？

**Comment by NutBear** [comment]
@mlzhang920802 我觉得是不是在onDestroy里面处理一下，我还没有试验了

**Comment by Jacksgong** [comment]
> 当我在下载过程中强制结束应用进程时，再进入app下载界面点击暂停，输出W/FileDownloader.FileDownloader: request pause but not exist 1937936575，如何能让下载任务在被强制回收之前自动暂停所有正在下载任务呢？

目前就是自动暂停所有的。

---

> W/FileDownloader.FileDownloader: request pause but not exist 1937936575

这个日志，是因为你请求了暂停，但是当前队列中并没有这个任务在运行。
