### ISSUE TITLE
动态添加下载任务，但怎么没有相应的回调，比如我仿音乐播放器动态添加下载任务，在下载页面有相应下载状态显示

### ISSUE THREAD

**Issue by jiangshihua** [lingochamp/FileDownloader#487]

**Comment by Jacksgong** [comment]
不好意思，我不是很明白你的意思。FileDownloader中的回调是十分的严格的，在demo project（可以clone下来跑跑看，和自己的使用对比下）中高并发（上千个任务）下载时，我们除了保障每个任务各个节点都能够正确的回调，以及其顺序。
