### ISSUE TITLE
Default Provider

### ISSUE THREAD

**Issue by EMIN3M1986** [lingochamp/FileDownloader#488]
Hi. I'm using this library. I have to say it is perfect.
How can I change default network provider from okhttp to any other providers like volley or httpurlconnection or etc ?

**Comment by Jacksgong** [comment]
Thanks.

Yes, you can do that through [customizing the Connection Component](https://github.com/lingochamp/FileDownloader/wiki/Open-Customized-Component) in the latest version, and in the latest version, the default connection component doesn't use okhttp as default anymore.
