### ISSUE TITLE
TotalBytes = -1 on Cellular Network

### ISSUE THREAD

**Issue by oguzkc** [lingochamp/FileDownloader#49]
Hi, firstly thank you for this great library.

I'm using Single Task mode, progress method is running perfectly with Wi-Fi  but when i download with Cellular Network (3G)  totalbytes always returns -1 also sometimes in Log it writes "unused values! by process callback"  Can you help about this?

Best regards.

**Comment by Jacksgong** [comment]
Could you provide your download URL, the download resources' network deployment might be the problem? 

I haven’t had any similar problem, and the FileDownloader handle different network environment as the same, it doesn’t have any special processes regarding network environment.

---

> P.S. Appear `TotalByts=-1` Only when the downloading resource is streaming media, which means that the `Transfer-Encoding` field brought back by HTTP response header is `chunked`.

**Comment by oguzkc** [comment]
I tried many URLs. All of them were PDF files and in Wi-Fi  "progress" method works properly, i can get both totalbytes and sofar.

**Comment by Jacksgong** [comment]
Did you try FileDownloader Demo in your case. I tried FileDownloader Demo and switch to Cellular Network, It works fine.
