### ISSUE TITLE
关于下载到一半没网速,也没回调过来

### ISSUE THREAD

**Issue by MugWorld** [lingochamp/FileDownloader#490]
之前用retrofit下载大文件的时候一直下到一半随机会报java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out)
 Caused by: android.system.ErrnoException: recvfrom failed: ETIMEDOUT (Connection timed out)
java.net.SocketTimeoutException
 java.net.SocketTimeoutException: timeout

这几个异常,所以想用断点下载,用了FileDownloader,下到一半就停住了,再点击按钮下载,回调warn,应该表示还在下载中,但是一直没网速,网络应该是正常的,这个长时间没有网速停在那了怎么弄?

**Comment by Jacksgong** [comment]
应该是在等待连接，最后超时了会回调回来的，

网络好坏与等待连接无关的，这个一部分原因是服务端的问题，如果你觉得超时等待过久了，可以参考[这里](https://github.com/lingochamp/FileDownloader/blob/master/demo/src/main/java/com/liulishuo/filedownloader/demo/DemoApplication.java#L40)，进行配置超时时间。
