### ISSUE TITLE
Customize Code

### ISSUE THREAD

**Issue by EMIN3M1986** [lingochamp/FileDownloader#492]
Hi.
You write a lot of useless code. I want to remove IPC  and customize some part of your code but it is very relational and too hard to custom that.

what's your idea ?

**Comment by Jacksgong** [comment]
Okay, we considered your case, If you want to remove IPC, you can set `process.non-separate=true` on the [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties) file, if you want to customize some components you can refer to [here](https://github.com/lingochamp/FileDownloader/wiki/Open-Customized-Component).
