### ISSUE TITLE
java.lang.NoClassDefFoundError: com.liulishuo.filedownloader.FileDownloadServiceProxy$HolderClass

### ISSUE THREAD

**Issue by ZhouHoubin** [lingochamp/FileDownloader#493]
java.lang.NoClassDefFoundError: com.liulishuo.filedownloader.FileDownloadServiceProxy$HolderClass
E/AndroidRuntime( 9712):        at com.liulishuo.filedownloader.FileDownloadServiceProxy.getImpl(FileDownloadServiceProxy.java:44)
E/AndroidRuntime( 9712):        at com.liulishuo.filedownloader.FileDownloader.isServiceConnected(FileDownloader.java:513)
E/AndroidRuntime( 9712):        at com.liulishuo.filedownloader.DownloadTaskHunter.pause(DownloadTaskHunter.java:413)
E/AndroidRuntime( 9712):        at com.liulishuo.filedownloader.DownloadTask.pause(DownloadTask.java:338)
E/AndroidRuntime( 9712):        at com.liulishuo.filedownloader.FileDownloader.pause(FileDownloader.java:216)

compile 'com.liulishuo.filedownloader:library:1.4.1'

**Comment by ZhouHoubin** [comment]
找到原因了,忘记了初始化

FileDownloader.init(getApplicationContext());

**Comment by alen252** [comment]
为啥我初始化了 还是报错
