### ISSUE TITLE
version v1.4.1 can not download

### ISSUE THREAD

**Issue by lforxeverc** [lingochamp/FileDownloader#494]
I have update v1.4.1 today,but can not fetch the version,I have check gradle offwork is not open,and invalid cache and has restart as! I try other library can be fetch.wait on line!

**Comment by Jacksgong** [comment]
Could you please provide any error log?

P.S: You also can execute `./gradlew --info --debug clean assembleDebug` on the root path of FileDownloader on the terminal and copy the error message to here.
