### ISSUE TITLE
打包混淆

### ISSUE THREAD

**Issue by hu499019771** [lingochamp/FileDownloader#496]
请问下有关这个库打包时需要不混淆吗?如果不需要,是怎么配置的呢,谢谢

**Comment by Jacksgong** [comment]
是不用特别配置混淆的，可以参看: [wiki](https://github.com/lingochamp/FileDownloader/wiki/Proguard-rules)

**Comment by hu499019771** [comment]
@Jacksgong 谢谢老哥
