### ISSUE TITLE
跨进程FileDownloader无法下载

### ISSUE THREAD

**Issue by dinuscxj** [lingochamp/FileDownloader#497]
我从主进程下载没有问题， 如果我打开一个android:process标记的Activity在这个页面无法进行下载， 
我看到日志 request clear the task[975849381] data in the database, but the download service isn't connected yet.
                                                                                     You can use FileDownloader#isServiceConnected() to check whether the service has been connected, 
                                                                                     besides you can use following functions easier to control your code invoke after the service has been connected: 
                                                                                     1. FileDownloader#bindService(Runnable)
                                                                                     2. FileDownloader#insureServiceBind()
                                                                                     3. FileDownloader#insureServiceBindAsync()

我按照这些修改了， 仍然不可以下载

我在代码里面是这样的 
if (!FileDownloader.getImpl().isServiceConnected()) {
      FileDownloader.getImpl().insureServiceBind();
}

**Comment by Jacksgong** [comment]
> if (!FileDownloader.getImpl().isServiceConnected()) {
> FileDownloader.getImpl().insureServiceBind();
> }

这样是无法启动下载进程的，你可以留一下方法上的注解，这个方法是一种pipeline的方式，如`FileDownloader.getImpl().insureServiceBind().getStatus()`。

---

FileDownloader确实可以在非主进程上面请求启动的:

- 如果需要只想主动启动下载服务与服务进程，可以通过`FileDownloader.getImpl().bindService(Runnable)`或`FileDownloader.getImpl().bindService()`进行启动下载进程与服务。
- 在第一次任意任务启动时的时候，默认就会启动与绑定下载进程服务
- 如果希望下载服务不运行在独立进程，可以使用`process.non-separate=true`，这样下载服务运行在主进程

---

```java
    /**
     * If the FileDownloader service is not started and connected, FileDownloader will try to start
     * it and try to bind with it. The current thread will also be blocked until the FileDownloader
     * service is started and a connection is established, and then the request you
     * invoke in {@link FileDownloadLine} will be executed.
     * <p>
     * If the FileDownloader service has been started and connected, the request you invoke in
     * {@link FileDownloadLine} will be executed immediately.
     * <p>
     * <strong>Note:</strong> FileDownloader can not block the main thread, because the system is
     * also call-backs the {@link ServiceConnection#onServiceConnected(ComponentName, IBinder)}
     * method in the main thread.
     * <p>
     * <strong>Tips:</strong> The FileDownloader service will start and bind automatically when any
     * task is request to start.
     *
     * @see FileDownloadLine
     * @see #bindService(Runnable)
     */
    public FileDownloadLine insureServiceBind() {
        return new FileDownloadLine();
    }
```

**Comment by dinuscxj** [comment]
我也用FileDownloader.getImpl().bindService() 还是起不来， 真心感觉好奇怪

**Comment by dinuscxj** [comment]
application oncreate之后也调用init啦， 因为跨进程进行init啦， 而且在submit之前调用bindService啦， 不知道为什么还是说服务没有连接
