### ISSUE TITLE
内存不足，有考虑么？

### ISSUE THREAD

**Issue by rjliulei** [lingochamp/FileDownloader#5]
当内存不足时，怎么处理？

**Comment by longtaoge** [comment]
上传的有考虑么

**Comment by Jacksgong** [comment]
恩。很感谢你的问题，很好的问题。是有考虑的，不过下个版本的几个feature和这个有关。

## 现状:

### 非下载进程(一般是UI进程):

> 这边的数据并不多，只是一些队列数据，用不了多少内存。

#### 前台进程数据被回收:

如果在前台的时候这个数据都被回收了, 你的应用应该也挂了。极低概率事件。

#### 后台进程数据被回收:

一般事件, 如果是你的下载是UI进程启动的，如果你的UI进程处于`后台进程`(可以理解为应用被退到后台)状态，在内存不足的情况下会被回收(回收优先级高于`服务进程`)，此时分两种情况: 

1. 是串行队列任务，在回收掉UI进程内存以后，下载进程会继续下载完已经pending到下载进程的那个任务，而还未pending到下载进程的任务会中断下载(由于任务驱动线性执行的是在UI进程); 有损体验: 下次进入应用重启启动整个队列，会继续上次的下载。

2. 是并行队列任务，在回收掉UI进程内存以后，下载进程会继续下载所有任务(所有已经pending到下载进程的任务，由于这里的pending速度是很快的，因此几乎是点击并行下载，所有任务在很短的时间内都已经pending到下载进程了)，而UI进程由于被回收，将不会收到所有的监听; 有损体验: 下次进入应用重新启动整个队列，会收到一堆warn，因为整个队列都正在下载过程中(下个版本着重解决这个问题)。

### 服务进程:

> 对内存有一定的占用，但是被回收是低概率事件

由于下载不断有不同的buffer占用内存，但是由于在下载时，是活跃的`服务进程`，因此被回收是低概率事件(会先回收完所有`空进程`、`后台进程`(后台应用)以后，如果内存还不够，才会回收该进程)。

即使被回收，也不会有任何问题。由于我们使用的是`START_STICKY`，因此在内存足够的时候，下载进程会尝试重启(系统调度)，非下载进程(一般是UI进程) 接收到下载进程的连接，会继续下载与继续接收回调，下载进程也会断点续传没有下载完的所有任务(无论并行与串行)，不会影响体验。

---

下个版本会处理两个相关问题:

1. 分段下载数据库数据/下载数据库数据加载时根据时效性整理，防止数据无限膨胀 
2. 并行任务，在非下载进程(一般是UI进程)不存在回调的时候，始终提供绑定有效监听，不再以warn结束掉。

**Comment by Jacksgong** [comment]
@longtaoge 暂时还没有考虑做上传。

**Comment by MrLiKH** [comment]
想在项目中使用，可是和Picsso冲突，添加后，就不能Picsso网络请求

**Comment by Jacksgong** [comment]
@MrLiKH 其实我们也有使用picasso，可以提供下你使用的picasso的版本号与引入的方式吗？顺便提供下出现问题的warn/error log，我今天定位下，看下是什么问题导致的。

**Comment by Jacksgong** [comment]
[fix(Parallel execute & kill ui progress by sys): handle case of ui progress be killed by sys and download progress not be killed, and ui progress relives and reexecutes same ](https://github.com/lingochamp/FileDownloader/commit/b38f5d40018f5757fa3e8650a3a922324225776c)

**Comment by MrLiKH** [comment]
@Jacksgong
 java.lang.RuntimeException: Picasso detected an unsupported OkHttp on the class path.
其实解决了貌似同时引入这三个包就可以
compile 'com.squareup.okhttp:okhttp:2.2.0'
compile 'com.squareup.okhttp:okhttp-urlconnection:2.2.0'
compile 'com.squareup.picasso:picasso:2.4.0'

**Comment by Jacksgong** [comment]
@MrLiKH 
不好意思这么晚才答复你。

---

恩。我大概知道你遇到的问题了。

首先，我不知和原因你用的是低版本的picasso,目前最新版本的picasso是`2.5.2`

---

我看了下代码，你所遇到的是picasso `2.4.0`的一个坑(个人观点):

> `okhttp` 或 `okhttp-urlconnection`，要不两个都要引，要不两个都不要引，否则直接抛异常。而filedownloader引用了`okhttp`，所以触发了这个问题。

#### picasso 2.4.0 创建默认下载组件代码如下，抛错误的地方:

```
static Downloader createDefaultDownloader(Context context) {
    boolean okUrlFactory = false;
    try {
      Class.forName("com.squareup.okhttp.OkUrlFactory");
      okUrlFactory = true;
    } catch (ClassNotFoundException ignored) {
    }

    boolean okHttpClient = false;
    try {
      Class.forName("com.squareup.okhttp.OkHttpClient");
      okHttpClient = true;
    } catch (ClassNotFoundException ignored) {
    }

    if (okHttpClient != okUrlFactory) {
      throw new RuntimeException(""
          + "Picasso detected an unsupported OkHttp on the classpath.\n"
          + "To use OkHttp with this version of Picasso, you'll need:\n"
          + "1. com.squareup.okhttp:okhttp:1.6.0 (or newer)\n"
          + "2. com.squareup.okhttp:okhttp-urlconnection:1.6.0 (or newer)\n"
          + "Note that OkHttp 2.0.0+ is supported!");
    }

    return okHttpClient
        ? OkHttpLoaderCreator.create(context)
        : new UrlConnectionDownloader(context);
  }
```

> 而在picasso 的`2.5.0`或更新的版本已经不存在这个问题了。

---

#### 如果应该一些特殊原因需要使用picasso `2.4.0`版本(这个版本是2014年的版本11月份发布的)，只需要再引入一个`okhttp-urlconnection`:

如:

```
compile 'com.squareup.picasso:picasso:2.4.0'
compile 'com.liulishuo.filedownloader:library:0.1.4'
compile 'com.squareup.okhttp:okhttp-urlconnection:2.7.2'
```

#### 不过如果没有特殊情况我更推荐你使用picasso的最新版本:

```
compile 'com.squareup.picasso:picasso:2.5.2'
compile 'com.liulishuo.filedownloader:library:0.1.4'
```

希望对你能有所帮助

**Comment by MrLiKH** [comment]
谢谢你，讲解的这么详细！祝好。
-----追逐幸福的人，始终会得到幸福！----
