### ISSUE TITLE
批量下载、批量暂停、批量开始及进度接收问题

### ISSUE THREAD

**Issue by funfang** [lingochamp/FileDownloader#501]
你好，我的需求和任务管理器的demo有点像，但又不太一样，有些疑问。我有一个页面展示大量图片，recyclerview实现的网格来展示的，可以批量选中该页面的所有图片（一般都超过50张以上），然后有个下载按钮能把所有选中的图片开始下载。点击下载后所有被选中的图片上会有进度显示，默认是同时下载5张图，其余的为等待状态。可以点击全部暂停按钮将所有下载给暂停，也可以点击全部开始按钮将所有处于暂停状态的图片再继续下载。下载的过程中可以关闭这个页面，再次进入这个页面后，继续显示所有正在下载的图片的进度，处于等待状态的图片显示等待的状态。不知道我这样描述你明白没有。
我的疑问是，目前我知道可以调用pauseAll来全部暂停，我看了管理器的demo后，如果要实现全部开始的功能貌似只能再次从跑一次初始化下载，没有提供startAll的接口，对吧？我关闭该页面的时候下载还在继续，但是我得把所有监听器给移除掉，因为没在该页面时我不需要去更新界面，貌似没看到如何移除所有监听器的方法？假如我关闭页面的时候移除了监听器，我再次进来的时候想再添加监听器来更新界面貌似只能通过relaceListener来实现？希望你能帮忙回答一下，谢谢。 @Jacksgong

**Comment by Jacksgong** [comment]
> 点击下载后所有被选中的图片上会有进度显示，默认是同时下载5张图，其余的为等待状态。

参考这里 ： https://github.com/lingochamp/FileDownloader/issues/504#issuecomment-285621093

> 可以点击全部暂停按钮将所有下载给暂停，也可以点击全部开始按钮将所有处于暂停状态的图片再继续下载。

- `FileDownloader#pause(listener)`或`FileDownloader#pauseAll()`
- 要启动就直接重新创建任务开始就行，默认就会自动断点续传


> 下载的过程中可以关闭这个页面，再次进入这个页面后，继续显示所有正在下载的图片的进度，处于等待状态的图片显示等待的状态。

参考下这里: https://github.com/lingochamp/FileDownloader/issues/103#issuecomment-209173124
