### ISSUE TITLE
post请求下载 怎么用

### ISSUE THREAD

**Issue by TomLBO** [lingochamp/FileDownloader#502]
你好 我这边的下载都是post请求 FileDownloader.getImpl().create(url) 这种方式是不是就不能用了

**Comment by Jacksgong** [comment]
目前FileDownloader支持定制，网络连接组件，你可以参考[这里](https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component)，在发起网络请求的时候，改用post请求即可。
