### ISSUE TITLE
BaseDownloadTask#pause() is not called paused FileDownloadListener

### ISSUE THREAD

**Issue by CMathgician** [lingochamp/FileDownloader#503]
Hi,
Why when I use BaseDownloadTask#pause(), the downloading file is still downloading and none of  FileDownloadListener called..?

Please tell me. Thanks.

**Comment by Jacksgong** [comment]
This problem has been fix since [1.4.0](https://github.com/lingochamp/FileDownloader/releases/tag/v1.4.0), please move to here: #402
