### ISSUE TITLE
change max size of file download in java

### ISSUE THREAD

**Issue by mohammed-najeeb** [lingochamp/FileDownloader#504]

**Comment by Jacksgong** [comment]
Alternative:

- [download.max-network-thread-count on filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)
- [FileDownloader#setMaxNetworkThreadCount(count:int)](https://github.com/lingochamp/FileDownloader/wiki/FileDownloader)
- [InitCustomMaker#maxNetworkThreadCount](https://github.com/lingochamp/FileDownloader/wiki/InitCustomMaker)

**Comment by mohammed-najeeb** [comment]
thank  you

**Comment by Jacksgong** [comment]
You are welcome
