### ISSUE TITLE
Add a function to check if the application in running in filedownloader process

### ISSUE THREAD

**Issue by lucas34** [lingochamp/FileDownloader#506]
Hi,

By default the filedownloader will run in another process. So it will initialise the Application two times. 
In leak canary they have a check to put in your application class
```java
if (LeakCanary.isInAnalyzerProcess(this)) {
  // This process is dedicated to LeakCanary for heap analysis.
  // You should not init your app in this process.
  return;
}
```

I think the library should provide the same things
```java
if (FileDownloader.isInDowloaderProcess(this)) {
  // This process is dedicated to the download task
  // You should not init your app in this process.
  return;
}
```

And inside check if the current process name is ':filedownloader'

Lucas

**Comment by Jacksgong** [comment]
Thanks for your prompt, actually, on the current version you can judge whether the FileDownloadService is allowed to run on the current process: `FileDownloadUtil#isDownloaderProcess(Context)`.
