### ISSUE TITLE
why FileDownloadListener is class but not  interface ?

### ISSUE THREAD

**Issue by hurshi** [lingochamp/FileDownloader#508]
如题~~~,如下常用的写法都不能实现了...
public class MainActivity extends BaseActivity implements FileDownloadListener{
}

**Comment by Jacksgong** [comment]
为了本兼容保留`FileDownloadListener`，但会增加接口类`IFileDownloaderListener`，

**Comment by Jacksgong** [comment]
考虑到，如果改用Interface，原`FileDownloadListener`中的所有接口都需要改为`public`，这么一来旧版本升级上来的人，就不得不将所有`FileDownloadListener`实现方法都只能从`protected`改为`public`，因此这个再看看有没有更好的解决方案。

早期设计的时候，这块确实有所不周到，但是那时候的主要原因是考虑到，有些接口对与上层来说其实不一定需要实现，担心上层每次实现接口都要实现一堆方法，然后很多空方法。

**Comment by Jacksgong** [comment]
This has been solved on [okdownload](https://github.com/lingochamp/okdownload).
