### ISSUE TITLE
启动队列/全部暂停的监听

### ISSUE THREAD

**Issue by hu499019771** [lingochamp/FileDownloader#509]
您好,最近在做下载管理,包含了全部开始(即队列下载任务)/全部暂停,启动/暂停全部任务后,有方法或者思路监听到队列所有任务启动/暂停完成吗?谢谢

**Comment by Jacksgong** [comment]
参照下这个全局监控: [FileDownloadMonitor](https://github.com/lingochamp/FileDownloader/wiki/FileDownloadMonitor)

**Comment by hu499019771** [comment]
多谢，我再去研究下
