### ISSUE TITLE
暂停后，可以更换下载地址继续断点下载吗？

### ISSUE THREAD

**Issue by JakeWoki** [lingochamp/FileDownloader#51]
更换地址指向的文件都是同一个。还没看断点那块是怎么处理的，先了解下

**Comment by Jacksgong** [comment]
是说多个URL都是指向同一个文件吗？我没有看明白你的问题。

**Comment by JakeWoki** [comment]
是同一个文件，不过url变了，下载id不是根据url和path生成的md5的吗？这样可以更换吗？

**Comment by yangwuan55** [comment]
这种需求就是很极端的了 个人觉得没必要做在通用库里

**Comment by Jacksgong** [comment]
@JakeWoki 我思考了这个问题，如果需要从根源解决这个问题，那么就需要在开始请求的时候，通过某个API从后端取得当前要下载文件的md5，然后再以这个md5与当前存储的路径作为key进行处理，否则应该都会有各类临界情况的case，暂时恐怕没有打算在库中做这个拓展。

> P.S: 我倒是有个建议，如果说你有这个需求，你每次下载都调用 `BaseDownloadTask#setForceReDownload(true)` 保证不复用本地文件，恐怕只有这样才能满足你的需求了。如果断点到一半，你下次重新下载的时候下载链接指向的资源出现了变化，这个时候就是ETAG作用的时候了，这个时候看你后台的处理了，库支持重头开始填充该文件，或者是直接抛非200的异常。
