### ISSUE TITLE
如果我在一个Activity中开始下载任务，当退出（不pause）这个Activity后重新进入怎么恢复进度监听。

### ISSUE THREAD

**Issue by chenycu** [lingochamp/FileDownloader#510]
如果我在一个Activity中开始下载任务，当退出（不pause）这个Activity后重新进入怎么恢复进度监听？我个人推断重新进入这个Activity的话首先得拿到正在下载中的BaseDownloadTask对象，然后通过该对象getTag获取ViewHolder对象替换新Activity的ProgressBar来恢复进度,
但是获取后台下载中的BaseDownloadTask对像我找到了两种方式，第一种是调用FileDownloader.getImpl().create()但是这会创建一个新的对象，这种方式不可用，还有一种方式是通过FileDownloadList.getImpl().get(int id)来获取，但是这种方式只要调用了暂停pause()方法就会调用FileDownloadList的remove()方法再次获取mList.size()就为0了。

其实我就要实现的效果是：点击下载后退出当前Activity还能在后台下载并且再次进入该Activity还能显示其下载进度，并且其他Activity也能拿到该进度，能提供下思路吗？谢谢！

**Comment by xujunhe** [comment]
FileDownloader.getImpl().replaceListener() 可以，你可以试试

**Comment by JianChi8** [comment]
我是思路是可以自己写一个下载管理类，将这个类放到Application中，这样就可以让几个Activity共同使用这个下载管理类中的信息，并且可以替换它们的监听器
