### ISSUE TITLE
对于获取下载任务的暂停状态有点疑问

### ISSUE THREAD

**Issue by NutBear** [lingochamp/FileDownloader#511]
如果我进入我的app，不进行任何下载任务的开启，通过getStatus方法获得上次暂停的任务的状态为0，我看在其他问题中 @Jacksgong 你说的意思是只要FileDownloadService启动就可以获取暂停状态，但是启动FileDownloadService需要开启最少一个下载任务，如果我不想开启任何下载任务，能获得我上一次暂停任务的状态吗，如果不行，存在FileDownloadService手动开启的方法吗

**Comment by HarkBen** [comment]
我是这么处理的，自己保存一份下载数据在本地。

**Comment by NutBear** [comment]
@HarkBen 你说的是个解决方法 但是我觉得既然已经存在的数据重复保存是否冗余，如果他能提供方法我觉得最好，如果没法提供也只能自己保存进度了

**Comment by Jacksgong** [comment]
@HarkBen @NutBear 参考下这里: https://github.com/lingochamp/FileDownloader/issues/392#issuecomment-259438911
