### ISSUE TITLE
FileDownloader下载造成Application重启

### ISSUE THREAD

**Issue by nanweiqing** [lingochamp/FileDownloader#515]
你好，是这样的，我在程序启动的时候，在Application里调用了下载服务，
![image](https://cloud.githubusercontent.com/assets/2526873/24027421/1592ac90-0afa-11e7-9d84-ae53f903b365.png)
服务里会自动检测未完成的任务，如果有未完成的任务会自动下载，当调用下载的时候，发现我的Application重启了，可能会造成我Application里的数据错误，请问这种怎么解决

**Comment by Jacksgong** [comment]
可以稍微看一下源码，`FileDownloader.init`，不会启动服务以及做相关检测，只不过是缓存了context与初始参数。
