### ISSUE TITLE
下载放在IntentService里面，ANR 异常，

### ISSUE THREAD

**Issue by 836986836** [lingochamp/FileDownloader#516]
我有一大堆的 下载任务。
而且我要在多个界面呈现这些下载任务的进度，
我的下载任务是独立的，一个一个的下 没有并行 也没有串行， 就是一个一个的下，这个下完了，遍历下一个，继续开启filedownloader 下载下一个 链接的下载，
我的下载文件格式是 三层，List<A> ,A包含List<B>，B包含List<C>, C才是我要下载的链接所在，
我有一个界面 会显示 List<A>包含的下载进度及下载状态，也有多个界面显示List<B>的下载进度及状态，
由于需要下载在后台运行，于是把filedownloader 放在service里面，并把filedownloader 放在  
 new Thread(new Runnable() {
            @Override
            public void run() {
}}).start();里面，
在下载的过程中 当一组数据，也就是添加一次 A,的时候，有时当数据过大的时候，会ANR异常，
当长时间下载，也有报ANR异常，提示我的APP无响应，是否等待...ANR in com.xxx.xxxx
                                                             Reason: Executing service com.xxx.xxxx/.DownloadManage.DownloadTaskService
                                                             Load: 0.98 / 0.4 / 0.28
                                                             CPU usage from 9680ms to 3702ms ago:
                                                               75% 20241/com.xxx.xxxx: 24% user + 51% kernel / faults: 3827 minor
                                                               19% 181/surfaceflinger: 0.1% user + 19% kernel
                                                               14% 20456/com.xxx.xxxx:filedownloader: 0.8% user + 13% kernel / faults: 58 minor
                                                               9.3% 436/system_server: 0.5% user + 8.8% kernel / faults: 583 minor
                                                               6.8% 91/adbd: 0% user + 6.8% kernel / faults: 562 minor
                                                               5.3% 86/jbd2/sdb3-8: 0% user + 5.3% kernel
                                                               2.3% 185/mediaserver: 0% user + 2.3% kernel / faults: 4 minor
                                                               2% 718/com.android.launcher3: 0% user + 2% kernel / faults: 1 minor
                                                               2% 20675/kworker/0:2: 0% user + 2% kernel
                                                               2% 25258/kworker/0:0: 0% user + 2% kernel
                                                               1% 1027/com.android.bluetooth: 0% user + 1% kernel
                                                               1% 2801/logcat: 0% user + 1% kernel
                                                               0.3% 37/kswapd0: 0% user + 0.3% kernel
                                                               0.3% 174/vinput: 0% user + 0.3% kernel
                                                               0% 22/ksoftirqd/5: 0% user + 0% kernel
                                                               0% 23/migration/6: 0% user + 0% kernel
                                                               0% 68/kworker/7:1: 0% user + 0% kernel
                                                               0% 69/kworker/1:1: 0% user + 0% kernel
                                                               0% 72/kworker/2:1: 0% user + 0% kernel
                                                               0% 178/netd: 0% user + 0% kernel / faults: 36 minor
                                                               0% 1769/com.estrongs.android.pop: 0% user + 0% kernel
                                                               0.1% 18680/com.tencent.mobileqq:tool: 0% user + 0.1% kernel / faults: 4 minor
                                                             18% TOTAL: 3.1% user + 9.9% kernel + 1.8% iowait + 3.4% softirq
                                                             CPU usage from 213ms to 716ms later:
                                                               21% 20456/com.xxx.xxxx:filedownloader: 0% user + 21% kernel / faults: 15 minor
                                                                 5.8% 20509/FileDownloader-: 0% user + 5.8% kernel
                                                                 5.8% 20513/FileDownloader-: 0% user + 5.8% kernel
                                                                 3.9% 20514/FileDownloader-: 0% user + 3.9% kernel
                                                                 1.9% 20480/GC: 0% user + 1.9% kernel
                                                                 1.9% 20486/Binder_1: 0% user + 1.9% kernel
                                                                 1.9% 20487/Binder_2: 0% user + 1.9% kernel
                                                                 1.9% 20508/FileDownloader-: 0% user + 1.9% kernel
                                                               13% 20241/com.kuman.comic: 0% user + 13% kernel / faults: 23 minor
                                                                 7.6% 20241/com.xxx.xxxx: 0% user + 7.6% kernel
                                                                 1.9% 21274/FileDownloader-: 1.9% user + 0% kernel
                                                                +0% 21299/FileDownloader-: 0% user + 0% kernel
                                                               7.5% 86/jbd2/sdb3-8: 0% user + 7.5% kernel
                                                               3.7% 91/adbd: 0% user + 3.7% kernel / faults: 51 minor
                                                                 1.8% 461/adbd: 0% user + 1.8% kernel
                                                               1.8% 70/kworker/3:1: 0% user + 1.8% kernel
                                                               2% 436/system_server: 0% user + 2% kernel
                                                               1.8% 718/com.android.launcher3: 0% user + 1.8% kernel
                                                                 1.8% 718/droid.launcher3: 0% user + 1.8% kernel
                                                                 1.8% 1683/Timer-2: 0% user + 1.8% kernel
                                                               1.8% 1027/com.android.bluetooth: 0% user + 1.8% kernel
                                                                 1.8% 1113/gki timer: 0% user + 1.8% kernel
                                                               1.8% 1137/kworker/5:2: 0% user + 1.8% kernel
                                                               1.9% 25258/kworker/0:0: 0% user + 1.9% kernel
                                                             8.1% TOTAL: 0% user + 4.3% kernel + 0.5% iowait + 3.3% softirq

**Comment by Jacksgong** [comment]
很抱歉没有及时回复。

- FileDownloader的下载原本就在FileDownloadService（ 默认配置下该服务在独立的进程运行）中进行下载，非特殊情况没有必要放到服务中；
- 对上层暴露的所有接口都只是用于回调与任务控制的。
- 从这个堆栈中无法定位到到底是哪个逻辑将主线程阻塞了。

#### 新版本做了很多优化有与调整。如果有进一步的信息该Issue会重新打开进行沟通定位。
