### ISSUE TITLE
多任务后台下载问题请教

### ISSUE THREAD

**Issue by tommyfeng** [lingochamp/FileDownloader#517]
大神，请问要如何进行多任务后台下载呢？ 最近在重构代码，使用了您的类库，觉得非常好用。但是现在需要添加后台下载任务，切换Activity时，可以查看下载进度。感觉没有思路，能否占用一点点时间，帮我看看要如何实现，感激不尽！！！

**Comment by Jacksgong** [comment]
参考下这里: https://github.com/lingochamp/FileDownloader/issues/103#issuecomment-209173124
