### ISSUE TITLE
一个非常严重的bug

### ISSUE THREAD

**Issue by xiandao** [lingochamp/FileDownloader#518]
在 filedownloader.properties 文件中设置 process.non-separate=false同时设置 需要在WiFi下载（BaseDownloadTask.setWifiRequired(true);  明明在wifi 状态下 ，可就是不下载，也没有回调，挺诡异的，查了好久查到，但是把process.non-separate=false后就没有问题了

**Comment by Jacksgong** [comment]
我这边测试:

- `process.non-separate=false`
- `BaseDownloadTask.setWifiRequired(true)`

是没有问题的。请问还有什么条件吗？

**Comment by xiandao** [comment]
for (FileModel model : taskModel.fileModelList) {
            BaseDownloadTask baseDownloadTask = FileDownloader.getImpl().create(model.getUrl());
            baseDownloadTask.setPath(model.getPath());
            baseDownloadTask.setWifiRequired(isWifiRequired);

            if (Constants.M3U8.equals(taskModel.getVideoType())) {
                baseDownloadTask.setCallbackProgressTimes(1);
            } else {
                baseDownloadTask.setCallbackProgressTimes(100);
                baseDownloadTask.setCallbackProgressMinInterval(1000);
            }


            baseDownloadTask.setTag(FILE_MODEL, model);
            baseDownloadTask.setTag(TaskModel.TASK_MODEL_ID, taskModel.getId());

            taskList.add(baseDownloadTask);

        }

        map.put(taskModel.getId(), taskList);

        CLog.e("total file:" + taskModel.fileModelList.size());

        DownloadListener listener = new DownloadListener(taskModel);
        addListenerMap(taskModel, listener);

        FileDownloadQueueSet queueSet = new FileDownloadQueueSet(listener)
                .setAutoRetryTimes(1)
                .downloadSequentially(taskList);
        queueSet.start();

这是我的代码

在开启这组任务时，我会判断当前的WiFi 状态，但是我当前获取的状态是wifi 状态，就是不下载，看了一下你的代码，个人感觉是你判断WiFi状态有问题

**Comment by xiandao** [comment]
这是我判断WiFi状态的代码
public static boolean isNetOK() {
		initParam();
		return netStatus != NETSTATUS_INAVAILABLE;
	}

	public static boolean isWifi() {
		initParam();
		return netStatus == NETSTATUS_WIFI;
	}

	public static boolean isMobile() {
		initParam();
		return netStatus == NETSTATUS_MOBILE;
	}


	private static void initParam() {
		try {

			ConnectivityManager cm = (ConnectivityManager) Application.getInstance().getSystemService(Context.CONNECTIVITY_SERVICE);
			NetworkInfo mobileNetInfo = cm.getNetworkInfo(ConnectivityManager.TYPE_MOBILE);
			NetworkInfo wifiNetInfo = cm.getNetworkInfo(ConnectivityManager.TYPE_WIFI);
			NetworkInfo allNetInfo = cm.getActiveNetworkInfo();

			if (allNetInfo == null) {
				if (wifiNetInfo != null && (wifiNetInfo.isConnected() || wifiNetInfo.isConnectedOrConnecting())) {
					netStatus = NETSTATUS_WIFI;
				} else if (mobileNetInfo != null && (mobileNetInfo.isConnected() || mobileNetInfo.isConnectedOrConnecting())) {
					netStatus = NETSTATUS_MOBILE;

				} else {
					netStatus = NETSTATUS_INAVAILABLE;
				}
			} else {
				if (allNetInfo.isConnected() || allNetInfo.isConnectedOrConnecting()) {
					if (wifiNetInfo != null && (wifiNetInfo.isConnected() || wifiNetInfo.isConnectedOrConnecting())) {
						netStatus = NETSTATUS_WIFI;
					} else if (mobileNetInfo != null && (mobileNetInfo.isConnected() || mobileNetInfo.isConnectedOrConnecting())) {
						netStatus = NETSTATUS_MOBILE;

						switch (mobileNetInfo.getSubtype()) {
							case TelephonyManager.NETWORK_TYPE_UNKNOWN:
								netSubType = NETWORK_SUBTYPE_UNKNOWN;
								break;
							case TelephonyManager.NETWORK_TYPE_EDGE:
							case TelephonyManager.NETWORK_TYPE_GPRS:
							case TelephonyManager.NETWORK_TYPE_CDMA:
							case TelephonyManager.NETWORK_TYPE_1xRTT:
							case TelephonyManager.NETWORK_TYPE_IDEN:
								netSubType = NETWORK_SUBTYPE_2G;
								break;
							case TelephonyManager.NETWORK_TYPE_LTE:
								netSubType = NETWORK_SUBTYPE_4G;
								break;
							default:
								netSubType = NETWORK_SUBTYPE_3G;
								break;
						}
					}
				} else {
					netStatus = NETSTATUS_INAVAILABLE;
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}


这是你的：
    public static boolean isNetworkOnWifiType() {
        final ConnectivityManager manager = (ConnectivityManager) FileDownloadHelper.getAppContext().
                getSystemService(Context.CONNECTIVITY_SERVICE);
        final NetworkInfo info = manager.getActiveNetworkInfo();

        return info != null && info.getType() == ConnectivityManager.TYPE_WIFI;
    }

**Comment by Jacksgong** [comment]
你可以，修改下demo中的SingleTaskActivity这两个case:

- process.non-separate=false
- BaseDownloadTask.setWifiRequired(true)

然后跑跑看，这样应该是没有问题的。然后你再对比对比你自己的coding。

**Comment by Jacksgong** [comment]
`process.non-separate=false` 这个的默认值就是`false`，也就是即便是不配置也是`false`，有任何新的进度可以定位问题，该问题，我在最新版本中，根据相关配置是没有问题的，只有在环境下会下载，否则会回调`error`。
