### ISSUE TITLE
断点续传失败

### ISSUE THREAD

**Issue by XYScience** [lingochamp/FileDownloader#519]
你好，“http://image.widash.wiwide.com/images/56a60/shenzhijisuanqi_38.apk”这个下载链接断点续传失败，每次点下载后，暂停，再继续下载，就会从0开始下载

**Comment by XYScience** [comment]
大神求帮忙/(ㄒoㄒ)/~~使用其它应用市场的apk下载链接正常。但是这个链接用MIUI自带的下载管理也是正常断点续传的

**Comment by Jacksgong** [comment]
你可以通过下面的方法定位原因:

1. 通过`FileDownloadLog.NEED_LOG=true`开启日志，然后查看`can't continue`关键字的日志
2. Debug下载服务所在进程，断点`FileDownloadMgr#isBreakpointAvailable`方法

**Comment by XYScience** [comment]
不好意思，确认了是那个下载链接不支持断点续传。还有一个是，下载链接是否支持断点续传，只有在回调FileDownloadListener#connected才知道吗？

**Comment by Jacksgong** [comment]
是的。之后获得response的时候才知道，因为我们无法预知服务器的行为。当请求返回是206时，才是获取指定区间的局部数据，才是断点续传。
