### ISSUE TITLE
求助！报SecurityException是什么原因？

### ISSUE THREAD

**Issue by lvHongXiong** [lingochamp/FileDownloader#520]
日志：
java.lang.RuntimeException:Unable to create application com.txtw.green.one.MainApplication: java.lang.SecurityException: Not allowed to start service Intent { cmp=com.xxx/com.liulishuo.filedownloader.services.FileDownloadService$SharedMainProcessService } without permission not exported from uid 10079。

**Comment by Jacksgong** [comment]
可否提供下具体信息，如 手机版本号、手机型号，越多越有助于定位问题。

该问题猜测可能原因:

1. 某Rom的Bug
2. 某安全软件导致
