### ISSUE TITLE
process.non-separate issue

### ISSUE THREAD

**Issue by jimmy510s** [lingochamp/FileDownloader#521]
Hi,

I am using the library from gradle and i would like to use the downloader on the main process. After settings the process.non-separate = true i start the app. After some test downloads i kill the app by swiping it. Then i go to the running services and i see the process saying Restarting and the it is live again.

I tested it in your demo app and it works... 

Is there anything else i need to write in my code or just the .properties file??

ps: i used the .properties file from your project to be sure

Thank you

**Comment by Jacksgong** [comment]
> Then i go to the running services and i see the process saying Restarting and the it is live again.

Does `the process` on the above sentence means your main process?
