### ISSUE TITLE
调用 task.pause() 方法后，在回调函数的paused()里面的当前进度和总进度都为0

### ISSUE THREAD

**Issue by tommyfeng** [lingochamp/FileDownloader#523]
目前碰到一个问题，当调用pause()方法之后，回调的paused()函数里面进度都为0.然后调用start()后，再次调用pause()无法暂停下载了 。。。想请教一下，可能是什么问题引起的！ 多谢！

**Comment by Jacksgong** [comment]
你可以修改demo来测试下，然后对比下，我在demo中没有遇到这个问题。

如果是调用`pause`无法暂停，在[v1.4.0](https://github.com/lingochamp/FileDownloader/blob/master/CHANGELOG-ZH.md#version-140)版本之前确实是在某些情况下会有这个问题，不过在v1.4.0版本中已经修复了。
