### ISSUE TITLE
本地路径存在这个同名文件，但我url变化了，然后直接走到了complete方法了

### ISSUE THREAD

**Issue by wangsuicheng** [lingochamp/FileDownloader#525]
但这时我的需求是，因为url变化了，所以是个新文件，所以需要下载，但本地路径path上存在着同名的文件，这时好像不会重新下载啊？
按理来说，下载库的数据库里应该是基于url和path，来生成taskId，这个taskId虽然path不变，但url变化了，所以应该是跟之前下载过taskId的不同，然后会重新下载吧？？

**Comment by wangsuicheng** [comment]
我看了下载库的数据库，发现好像下载成功之后，会把这条下载记录删除掉~~~然后遇到下次，我还是起同一个路径文件，比如/mnt/sdcard/kkk.zip，但是url变化了，它就没法跟之前的比较，然后就变成直接到complete了。。但实际上上已经是个新文件了。。如果我加上forceReDownload的话，还能支持断点下载吗？

**Comment by Jacksgong** [comment]
FileDownloader判断文件是否存在是根据本地文件是否存在的。

早期的版本确实有处理你说的这种情况，但是那个版本本地的数据库无限膨胀，并且将是否下载完成写的相对臃肿；因为为了可持续化以及轻量，后期版本改为直接根据本地文件是否存在来判断是否已经下载完成。这是一个权衡的结果。因此目前是设计如此。如果你有更好的方案，欢迎PR或提Issue讨论，谢谢~
