### ISSUE TITLE
下载速度问题

### ISSUE THREAD

**Issue by shiweibsw** [lingochamp/FileDownloader#526]
荣耀8上测试下载同一个文件，使用系统自带浏览器下载比FileDownloader下载速度几乎快了一倍，是什么原因限制了FileDownloader的下载速度？文件写入和下载是同一个线程？filedownloader.properties采用的都是默认配置

**Comment by shiweibsw** [comment]
FileDownloader和RxDownload单线程下载的速度差不多，RxDownload如果开启多线程速度比FileDownloader快了好几倍，download.max-network-thread-count=3这个配置感觉根本没有生效，还是单线程的。

**Comment by Jacksgong** [comment]
可以告知下所用的是哪个版本的FileDownloader吗？

**Comment by Jacksgong** [comment]
下载的稳定性与速度是一个权衡的结果，一些好的网络资源的前提下，我这边在Nexus6P上有测试过跑满我自己100M网速的情况。优化的话可以参考下: [这里](https://github.com/lingochamp/FileDownloader/wiki/Optimize-Tutorial)

FileDownloader是支持各类定制的，包括input stream、database、network component等。如果是一个极速追求网速，除了上面提到的优化策略以外，完全可以定义自己的input stream机制(如非同步写入、更大的buffer，更低的io频率)、database机制(如无database写入，或者极大降低写db)、network机制(如采用多链路并行获取资源，更激进的重试机制)等等。 **目前FileDownloader是一个完全可定制化的组件**希望能够根据自身实际需求多探究多拓展。

**Comment by shiweibsw** [comment]
目前使用的是1.4.2版本，参照wiki里优化了一下，没有什么明显效果，并不是在追求极速下载，只是感觉多线程并没有发挥应有的作用

**Comment by Jacksgong** [comment]
v1.5.0之后的版本已经支持分块下载。
