### ISSUE TITLE
Exit activity without pausing the download

### ISSUE THREAD

**Issue by jawadturk** [lingochamp/FileDownloader#528]
hey , I wan't to ask does this work in background in case i want exit my activity without pausing the download , I've noticed that if i want to download some thing its starting again from where it was left . although I removed FileDownloader.getImpl().pause(downloadListener); from onDestroy . thanks !

**Comment by Jacksgong** [comment]
Please Ref [here](https://github.com/lingochamp/FileDownloader/issues/103#issuecomment-209173124), **And FileDownloader isn't bound any Activity**, I guess when you destroy your Activity, all callback messages ignore by your logic.
