### ISSUE TITLE
ETag 問題

### ISSUE THREAD

**Issue by kathychau** [lingochamp/FileDownloader#529]
在刪除應用後，FileDownloader 自動儲存了的那個ETag 還沒有刪除，在下次重新安裝應用時，還是取出相同的ETag。請問怎樣解決?

**Comment by Jacksgong** [comment]
FileDownloader存储etag是通过 [默认数据库组件](https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component) 存储在`//data/data/<Your-Application-Package-Name>/databases/filedownloader`，通常，当应用卸载以后，该目录下的数据也会一起被删除，我不是很明白**删除应用后，FileDownloader存储的Etag还没有删除**是什么概念?
