### ISSUE TITLE
请问一下下载中文路径的应该怎么配置呢？

### ISSUE THREAD

**Issue by niantuo** [lingochamp/FileDownloader#533]
我的下载链接有中文，然后下载失败，但是用其他下载方式比如Retrofit，，可以下载成功

**Comment by Godsbox** [comment]
你好，中文路径的问题解决了吗？我也遇到了

**Comment by niantuo** [comment]
没有解决，换其他的了

**Comment by Jacksgong** [comment]
可以告知报的是什么异常吗？

**Comment by Jacksgong** [comment]
我自己模拟了一个中文转发地址: `https://blog.dreamtobe.cn/test/中文` 可以正常下载，有谁能告知下，遇到的具体是什么错误吗？

**Comment by Godsbox** [comment]
我的解决办法是，，，，，，把中文转为uri编码

**Comment by Jacksgong** [comment]
@Godsbox 报的是什么错误，可否给一下遇到问题的链接（如果不方便public，可以邮件发我igzhenjie@gmail.com)

**Comment by Godsbox** [comment]
很久了忘了。。。。而且现在后台也把中文路径改掉了！

**Comment by ZhouHoubin** [comment]
中文路径404,url 编码域名后面的内容就行了

**Comment by tiewantn** [comment]
遇到类似的中文404问题，但是是偶现bug。
工程项目在二十多款手机上测试，当文件路径中或文件名称有中文时，会偶现404异常，大多数手机上下载正常，复现该bug机型为红米note2，红米note1lte。希望作者能复现，并提出借解决方案，多谢

附上一个测试用的中文url，http://222.187.222.235:8001/file/review修改要求.docx
