### ISSUE TITLE
关于https的下载

### ISSUE THREAD

**Issue by JaminFan** [lingochamp/FileDownloader#535]
使用https下载时出现这个错误：
javax.net.ssl.SSLHandshakeException: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate signature.
我搜寻了问题列表，看到有说使用FileDownloadHelper.OkHttpClientCustomMaker去进行自己的验证，但是我使用1.4.1的版本，找不到FileDownloadHelper.OkHttpClientCustomMaker这个类。

**Comment by Jacksgong** [comment]
参考下这里哈: https://github.com/lingochamp/FileDownloader/issues/437#issuecomment-270825192

--- 

- 多数情况是所请求的https资源的根证书不被信任，你可以通过这个进行检测: https://www.ssllabs.com/ssltest/index.html
- 1.3.9之后就没有了`OkHttpClientCustomMaker`，因为之后的版本已经封装了定制化的`Connection`而非仅仅okhttp，具体参考上面提到的[参考评论](https://github.com/lingochamp/FileDownloader/issues/437#issuecomment-270825192)
