### ISSUE TITLE
Exception java.lang.ExceptionInInitializerError: 

### ISSUE THREAD

**Issue by 7280423** [lingochamp/FileDownloader#537]
arrow_drop_down
Exception java.lang.ExceptionInInitializerError:
com.liulishuo.filedownloader.util.FileDownloadProperties.getImpl (FileDownloadProperties.java:118)
com.liulishuo.filedownloader.services.FileDownloadService.onCreate (FileDownloadService.java:43)
android.app.ActivityThread.handleCreateService (ActivityThread.java:2818)
android.app.ActivityThread.access$1800 (ActivityThread.java:166)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1365)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:136)
android.app.ActivityThread.main (ActivityThread.java:5584)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1268)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1084)
dalvik.system.NativeStart.main (NativeStart.java)
arrow_drop_down
Caused by java.lang.IllegalStateException: Please invoke the FileDownloader#init in Application#onCreate first.
com.liulishuo.filedownloader.util.FileDownloadProperties.<init> (FileDownloadProperties.java:127)
com.liulishuo.filedownloader.util.FileDownloadProperties.<init> (FileDownloadProperties.java:97)
com.liulishuo.filedownloader.util.FileDownloadProperties$HolderClass.<clinit> (FileDownloadProperties.java:114)
com.liulishuo.filedownloader.util.FileDownloadProperties.getImpl (FileDownloadProperties.java:118)
com.liulishuo.filedownloader.services.FileDownloadService.onCreate (FileDownloadService.java:43)
android.app.ActivityThread.handleCreateService (ActivityThread.java:2818)
android.app.ActivityThread.access$1800 (ActivityThread.java:166)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1365)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:136)
android.app.ActivityThread.main (ActivityThread.java:5584)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1268)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1084)
dalvik.system.NativeStart.main (NativeStart.java)

My app is a multi process, but I have application in the oncreate method to initialize the FileDownloader.init (appContext); but occasionally abnormal, how to solve this problem?
thanks！

**Comment by Jacksgong** [comment]
You need to invoke `FileDownloader#init` both on the main process(where you want to use FileDownloader) and the filedownloader process( `FileDownloadUtils#isDownloaderProcess`).

---

If you set `process.non-separate=true` on the filedownloader.properties file, you only need ensure invoking `FileDownloader#init` on the main process(where you want to use FileDownloader)

**Comment by SourceAdFlt** [comment]
i  got same error
