### ISSUE TITLE
FileDownloader.init(Application) and androidTest

### ISSUE THREAD

**Issue by HugoGresse** [lingochamp/FileDownloader#54]
I'm using `FileDownloader` in my application and I'm trying to test it. The fact is that I don't have an application when running an `InstrumentationTestCase`. I can have a `Context` or a `ApplicationContext` but not and `Application`. Do you already setted up testing with it? How do you manage it?

Don't you think the `init()` should take an `ApplicationContext` to be more polyvalent? 

The error when calling it without an application: 

```
03-11 18:05:03.542 19266-19303/? W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
03-11 18:05:03.542 19266-19303/? W/System.err:     at android.content.ComponentName.<init>(ComponentName.java:77)
03-11 18:05:03.542 19266-19303/? W/System.err:     at android.content.Intent.<init>(Intent.java:4160)
03-11 18:05:03.542 19266-19303/? W/System.err:     at com.liulishuo.filedownloader.services.BaseFileServiceUIGuard.bindStartByContext(BaseFileServiceUIGuard.java:128)
```

**Comment by Jacksgong** [comment]
I know, I agree with your advice, and it will be accepted.

**Comment by Jacksgong** [comment]
Enhanced in [v0.2.1](https://github.com/lingochamp/FileDownloader/releases/tag/v0.2.1).
