### ISSUE TITLE
实际文件大小问题

### ISSUE THREAD

**Issue by zhangjiakang** [lingochamp/FileDownloader#543]
请问我总文件为1G，但是我本次下载了100k就停止了，看到会默认创建一个1G的文件，后面都是0在填充。想问一下，如何设置文件大小为实际下载大小（下了100k就是100k，而不是1G，用0填充）

**Comment by wuketidai** [comment]
这个策略是为了能够让磁盘空间不足的错误尽快抛出来，如果不采用这个方案，在下载的时候需要处理这个异常，复杂度会提高，并且收获不大。

**Comment by Jacksgong** [comment]
默认是会预分配空间的，如果不需要预分配空间，可以在`filedownloader.properties`中配置`file.non-pre-allocation=true`，参考: https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties
