### ISSUE TITLE
你好，我的下载请求是Post，然后所有资源都是同一个地址，根据请求体的参数来区分下载资源。我现在有两个问题，一个是如何设置这个下载Post请求，一个是id的生成能不能自己定义规则呢？要不然如果按照你源码的规则（根据path和url生成的），那我所有的下载文件id是不是都会是一样的啊，这样会导致断点续传失败吧？

### ISSUE THREAD

**Issue by SoftGrace** [lingochamp/FileDownloader#544]

**Comment by Jacksgong** [comment]
> 如何设置这个下载Post请求

参考这里: https://github.com/lingochamp/FileDownloader/issues/502#issuecomment-285622419

> 一个是id的生成能不能自己定义规则呢？要不然如果按照你源码的规则（根据path和url生成的）

关注下这个Issue: #224
