### ISSUE TITLE
http返回码为201时无法下载

### ISSUE THREAD

**Issue by FrankKwok** [lingochamp/FileDownloader#545]

**Comment by Jacksgong** [comment]
这个支持并不困难。

可否提供下相关的资源链接给我测试下（如果担心链接泄漏，可以通过邮件发给我(igzhenjie@gmail.com))，201这个确实没有处理，不过我也没有搜索到相关下载中的处理。我看了文档，201是指“接受了请求，并且创建了新的资源”。根据描述理解，确实是可以作为200处理（差别只是创建了新的资源？），但是我并不确定，所以想要测试下。

**Comment by FrankKwok** [comment]
不好意思，才看到，因为201不能处理，所以我们后端接口做了调整，现在可以了；之前下载接口是通过同一个链接来传入不同的id来下载不同的文件，这样http返回码就变成201了，现在已经改成通过不同路径下载
