### ISSUE TITLE
为什么我进度回调的方法没执行？

### ISSUE THREAD

**Issue by xiong5201314** [lingochamp/FileDownloader#546]
多图片下载，图片都下载完了，我想把所有图片的进度放在一个里面，但在progress没回调，我在progress里打印的日志没出来

**Comment by Jacksgong** [comment]
由于我这边无法复现，提供的信息无法定位到问题所在。

建议Clone demo project下来，在上面进行复现，复现以后可以提供更详细的信息，或者是提供可复现的Demo project，我这边进一步定位问题。

**Comment by xiong5201314** [comment]
我的问题 没事了 谢谢

**Comment by Jacksgong** [comment]
okay.
