### ISSUE TITLE
One progress for multiple downloads in parallel

### ISSUE THREAD

**Issue by oligazar** [lingochamp/FileDownloader#548]
Hello! If I have multiple downloads in parallel. What is the best way to have just one total progress for all the downloads? Are the progress callbacks happen on the main thread? Or should I have some synchronized method to store and access values of individual progresses and sum them together to show in UI?

**Comment by rantianhua** [comment]
In your case, you can just hold a task list, then the list size is total progress, after finishing a task, you increase your current progress. You cannot sum the individual progresses together because we don't know every task's size at the beginning.
