### ISSUE TITLE
有没有eclipse版本？下载源码导入工程，在demo任何界面点击开始按钮都没有反应，也不报错。

### ISSUE THREAD

**Issue by wjk2813** [lingochamp/FileDownloader#55]

**Comment by Jacksgong** [comment]
参考下这个issue: #43 中的这个 [issuecomment-192182054](https://github.com/lingochamp/FileDownloader/issues/43#issuecomment-192182054)

**Comment by ishuqi** [comment]
@wjk2813  看看你的demo在点击开始按钮时  是不是有下面的异常信息打印
04-05 11:39:03.215: I/art(27820): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.RetryableSink>
04-05 11:39:03.216: I/art(27820): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.RetryableSink>
04-05 11:39:03.222: I/art(27820): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.HttpEngine$2>
04-05 11:39:03.222: I/art(27820): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.HttpEngine$2>
04-05 11:39:03.237: I/art(27820): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.RetryableSink>
04-05 11:39:03.246: I/art(27820): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.RetryableSink>
04-05 11:39:03.250: I/art(27820): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.RetryableSink>
04-05 11:39:03.251: I/art(27820): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.RetryableSink>
