### ISSUE TITLE
下载不行

### ISSUE THREAD

**Issue by asdfcjf** [lingochamp/FileDownloader#551]
就走了pending这个回调 其他什么都没有 也没下载这是什么问题？

**Comment by Jacksgong** [comment]
#### 方案一:

看看logcat中的warning与error级别日志输出

#### 方案二:

clone demo project下来对比下看看。

如果方案一方案二都无法解决你的问题: 将日志贴出来给我看看，有任何进度直接在这个issue中答复，我会重新打开这个issue.
