### ISSUE TITLE
关于返回301重定向，下载失败的问题，如何配置？

### ISSUE THREAD

**Issue by ApacheJondy** [lingochamp/FileDownloader#552]
在下载一个文件时，回调error，显示response code 301error。请问在哪里可以设置启用重定向？我在FileDownloader.init和FileDownloadUrlConnection.Configuration都没找到可以设置允许重定向的，各位大神帮帮忙!谢谢!

**Comment by Jacksgong** [comment]
参考下[这里](https://github.com/lingochamp/FileDownloader/wiki/NOT-SUPPORT-302%E3%80%81307..%3F)
