### ISSUE TITLE
关于网络切换时，下载error的问题

### ISSUE THREAD

**Issue by ApacheJondy** [lingochamp/FileDownloader#553]
测试背景及目标：从没网或数据网络切换到WiFi，可以自动下载;从WiFi或者没网切换到数据网络，下载需要提示。
已经设置了允许数据网络下载。
操作:从WiFi切换到数据网络，从数据网络切换到没有网络等，这些尝试时，下载时都会发生error，提示链接超时。求指导如何规避网络切换时出现的这种下载错误？另：7.1系统后，好像不能通过receiver接受网络变化了，此时如何处理。

PS:经测试，从WiFi切换到数据，回调到error方法时，获取的网络时Null的，receiver中的响应始终在error方法后，如何才能正确的进行网络切换？谢谢！

**Comment by Jacksgong** [comment]
你说的情况是符合FileDownloader预期的，我只能根据你的需求，给你一些建议:

### 需求: 从没网或数据网络切换到WiFi，可以自动下载;从WiFi或者没网切换到数据网络，下载需要提示。

#### 为什么WiFi切换到数据，回调到error方法时，获取的网络时Null的?

因为用户从WiFi切换到数据，其实是经历了Wifi -> 无网络 -> 数据，因此回调及时的话在`error`中检测到的是无网络的状态，因此是null。

#### 7.1系统后，好像不能通过receiver接受网络变化了，此时如何处理。

> 官方文档: https://developer.android.com/training/monitoring-device-state/connectivity-monitoring.html

1. 根据官方稳定只有将`targetSdkVersion`改为24或更高版本才有这个限制
2. 即便是`targetSdkVersion`改为24或更高版本，在代码中通过`Context.registerReceiver()`依然是可以的，只有在manifest中定义不行。

#### 建议解决方案

1. 收到`error`回调以后可以根据上下文进行处理，而非耦合FileDownloader的回调给予用户提示。
2. 收到`error`回调后下载会自动暂停，下一次重新启动任务会自动断点续传，因此如果接收到`error`并且通过receiver监听到网络是切换到数据(可以判定区间设置在500ms~1000ms内，如果超过该时间便忽略本次由于`SocketTimeoutException` `error`回调而暂停的任务)，那么就弹出提示是否继续通过数据网络下载，如果是再重新启动下载便会自动断点续传。
