### ISSUE TITLE
请教，这个可以一个文件分为3份，多线程下载吗？

### ISSUE THREAD

**Issue by wbb631094818** [lingochamp/FileDownloader#555]

**Comment by Jacksgong** [comment]
v1.5.0版本开始就支持了，可以参看[CHANGELOG](https://github.com/lingochamp/FileDownloader/blob/master/CHANGELOG-ZH.md#version-150)

**Comment by Jacksgong** [comment]
如果需要定制单任务的线程数，可以参照: https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component
