### ISSUE TITLE
快速多次点击下载暂停，下载没反应了

### ISSUE THREAD

**Issue by jarvan11** [lingochamp/FileDownloader#556]
报错信息：FileDownloader.FileDownloader: request pause but not exist 0

**Comment by Jacksgong** [comment]
这个Warning的日志，说明传进来的download id是0(这本身就是一个无效的dowload id)，并在在内部没有找到对应id的任务需要暂停。这个只是警告的日志，并非错误。

----

> 快速多次点击下载暂停，下载没反应了

我不知很理解这句话，点击暂停不就是要暂停吗？
