### ISSUE TITLE
请问如何重新进入时继续上次下载

### ISSUE THREAD

**Issue by JaneHsu** [lingochamp/FileDownloader#558]
您好，比如一个下载页面，已经开始了多线程的几个下载。退出这个页面，当再次进入时，还想显示相同的下载进度，并继续下载。这个怎么实现呢？

**Comment by cervy** [comment]
持久化状态

**Comment by JaneHsu** [comment]
我是说类似下载这种要实时更新的，也要每更新一个进度就写入数据库，然后再提取？

**Comment by lizixian18** [comment]
同问，我看demo是可以的，但是我自己不行，代码逻辑差不多，为什么会在跳界面的时候会自动暂停呢？我没手动调用暂停

**Comment by Jacksgong** [comment]
参考下这里: https://github.com/lingochamp/FileDownloader/issues/103#issuecomment-209173124

**Comment by lizixian18** [comment]
在adapter里面用#103中的单例的话，会有复用问题吧，不用的话，就同步不了
