### ISSUE TITLE
回调的频率太快了，能否加个参数设置，现在的目测是一秒十次，其实正常应用使用，一秒两次就差不多了

### ISSUE THREAD

**Issue by wjk2813** [lingochamp/FileDownloader#56]
回调的频率太快了，能否加个参数设置，现在的目测是一秒十次，其实正常应用使用，一秒两次就差不多了

**Comment by Jacksgong** [comment]
最好是能够先看下文档再提issue.

## 目前提供了两种有效的方法:

1. 你可以设置AIDL回调，下载进度回调 `BaseDownloadTask#setCallbackProgressTimes(callbackProgressTimes)` 默认是最多100次。这个用于减少回调。

2. 你可以设置全局下载引擎相关的 `FileDownloadListener` 中所有接口的回调频率: `FileDownloader#setGlobalPost2UIInterval`、`FileDownloader#setGlobalHandleSubPackageSize`。这个用于配置频次，但是回调不会少。
