### ISSUE TITLE
setCallbackProgressMinInterval回调貌似不准确

### ISSUE THREAD

**Issue by wybq1314** [lingochamp/FileDownloader#561]
测试下载1.5GB左右的视频时，我设置setCallbackProgressMinInterval(10)，但是发现需要等4-5s 才会回调progress方法，我这边界面需要每秒刷新一次 soFarBytes和speed，请问有解决方法么。附上代码：
        final BaseDownloadTask task = FileDownloader.getImpl().create(model.getUrl()).addHeader("cookie", model.getCookie())
                .setPath(Setting.downloadPath + model.getName())
                .setCallbackProgressMinInterval(10)
                .setListener(taskDownloadListener).setTag(model);

**Comment by Jacksgong** [comment]
这块问题可以参考下这里的解答: https://github.com/lingochamp/FileDownloader/issues/246#issuecomment-237133750
