### ISSUE TITLE
IllegalStateException:has already accomplished all his job, but there still are some messages in parcel queue[1]

### ISSUE THREAD

**Issue by fatbush** [lingochamp/FileDownloader#562]
最近我的工程使用了这个控件，遇到这个报错。我是怎么样都重现不了，而且报错的频率很低，但是会导致APP崩溃！

想问问大家有遇到过吗？
请问是怎么导致这个报错出现的，我应该怎么避免？

报错日志：
![default](https://cloud.githubusercontent.com/assets/10277776/26021600/d29e5a96-37c3-11e7-8d9c-7ad29fd5d6a5.png)

代码位置：
![_20170513100807](https://cloud.githubusercontent.com/assets/10277776/26021622/3108b306-37c4-11e7-98c4-a863ed4864bd.png)

**Comment by Jacksgong** [comment]
可否开启Debug日志(`FileDownloadLog.NEED_LOG = true`)，然后复现以后贴下这个异常前后尽量多的日志给我。我来看下这个问题.

**Comment by fatbush** [comment]
@Jacksgong  终于找到重现的办法了！逻辑如下：软件一启动，然后就收到连续10条的XMPP消息，收到消息后，就启动下载的逻辑了！接着就有可能报错了！下载逻辑是这样子的，使用的是方法二启动下载，在下载前，我会运行pause。

**Comment by fatbush** [comment]
启动下载的逻辑如下：
`public boolean start(List<Adv> l, String t) {
	if (isDownloading()) {
		pause();
	}
	stopTimer();

	mList = l;
	mErrorList = new ArrayList<>();
	mType = t;
	if ((null == mList) || (mList.isEmpty())) {
		Logger.e(TAG, "list is empty, FileDownload fail!!");
		return false;
	}
	mDownloadListener = setFileDownloadListener();
//        The first way-----------------------------:
//        for (int i = 0; i < count; i++) {
//            final String url = Constant.URLS[i];
//            FileDownloader.getImpl().create(url)
//                    .setListener(downloadListener)
//                    .setAutoRetryTimes(1)
//                    .setTag(i + 1)
//                    .setCallbackProgressTimes(0)
//                    .asInQueueTask()
//                    .enqueue();
//        }
//        FileDownloader.getImpl().start(downloadListener, serialRbtn.isChecked());

//        The second way----------------------------:

	final FileDownloadQueueSet queueSet = new FileDownloadQueueSet(mDownloadListener);

	final List<BaseDownloadTask> tasks = new ArrayList<>();
	//启用防掉帧
	if (FileDownloader.isEnabledAvoidDropFrame()) {
		FileDownloader.enableAvoidDropFrame();
	}
	for (int i = 0; i < mList.size(); i++) {
		//tasks.add(FileDownloader.getImpl().create(Constant.URLS[i]).setTag(i + 1));
		Adv bean = mList.get(i);
		tasks.add(FileDownloader.getImpl()
				.create(bean.getSourceURL())
				.setTag(i)
				.setPath(bean.getPath(), false));
	}
	queueSet.disableCallbackProgressTimes(); // do not want each task's download progress's callback,
	// we just consider which task will completed.

	// auto retry 1 time if download fail
	queueSet.setAutoRetryTimes(1);

	//序列下载
	Boolean isSerialDownload = true;

	if (isSerialDownload) {
		// start download in serial order
		queueSet.downloadSequentially(tasks);
		// if your tasks are not a list, invoke such following will more readable:
//            queueSet.downloadSequentially(
//                    FileDownloader.getImpl().create(url).setPath(...),
//                    FileDownloader.getImpl().create(url).addHeader(...,...),
//                    FileDownloader.getImpl().create(url).setPath(...)
//            );
	} else {
		// start parallel download
		queueSet.downloadTogether(tasks);
		// if your tasks are not a list, invoke such following will more readable:
//            queueSet.downloadTogether(
//                    FileDownloader.getImpl().create(url).setPath(...),
//                    FileDownloader.getImpl().create(url).setPath(...),
//                    FileDownloader.getImpl().create(url).setSyncCallback(true)
//            );
	}
	mDownloadCompleteCount = 0;
	mIsDownloading = true;
	queueSet.start();
	return true;
}

public void pause() {
	FileDownloader.getImpl().pause(mDownloadListener);
	mIsDownloading = false;
}

public boolean isDownloading() {
	return mIsDownloading;
}`

**Comment by fatbush** [comment]
下载逻辑代码：

`public boolean start(List<Adv> l, String t) {
	if (isDownloading()) {
		pause();
	}
	stopTimer();
	mList = l;
	mErrorList = new ArrayList<>();
	mType = t;
	if ((null == mList) || (mList.isEmpty())) {
		Logger.e(TAG, "list is empty, FileDownload fail!!");
		return false;
	}
	mDownloadListener = setFileDownloadListener();
	final FileDownloadQueueSet queueSet = new FileDownloadQueueSet(mDownloadListener);
	final List<BaseDownloadTask> tasks = new ArrayList<>();
	if (FileDownloader.isEnabledAvoidDropFrame()) {
		FileDownloader.enableAvoidDropFrame();
	}
	for (int i = 0; i < mList.size(); i++) {
		Adv bean = mList.get(i);
		tasks.add(FileDownloader.getImpl()
				.create(bean.getSourceURL())
				.setTag(i)
				.setPath(bean.getPath(), false));
	}
	queueSet.disableCallbackProgressTimes(); 
	queueSet.setAutoRetryTimes(1);
	Boolean isSerialDownload = true;
	if (isSerialDownload) {
		queueSet.downloadSequentially(tasks);
	} else {
		queueSet.downloadTogether(tasks);
	}
	mDownloadCompleteCount = 0;
	mIsDownloading = true;
	queueSet.start();
	return true;
}

public void pause() {
	FileDownloader.getImpl().pause(mDownloadListener);
	mIsDownloading = false;
}

public boolean isDownloading() {
	return mIsDownloading;
}`

**Comment by fatbush** [comment]
下载代码：

`public boolean start(List<Adv> l, String t) {
	if (isDownloading()) {
		pause();
	}
	stopTimer();
	mList = l;
	mErrorList = new ArrayList<>();
	mType = t;
	if ((null == mList) || (mList.isEmpty())) {
		Logger.e(TAG, "list is empty, FileDownload fail!!");
		return false;
	}
	mDownloadListener = setFileDownloadListener();
	final FileDownloadQueueSet queueSet = new FileDownloadQueueSet(mDownloadListener);
	final List<BaseDownloadTask> tasks = new ArrayList<>();
	if (FileDownloader.isEnabledAvoidDropFrame()) {
		FileDownloader.enableAvoidDropFrame();
	}
	for (int i = 0; i < mList.size(); i++) {
		Adv bean = mList.get(i);
		tasks.add(FileDownloader.getImpl()
				.create(bean.getSourceURL())
				.setTag(i)
				.setPath(bean.getPath(), false));
	}
	queueSet.disableCallbackProgressTimes(); 
	queueSet.setAutoRetryTimes(1);
	Boolean isSerialDownload = true;
	if (isSerialDownload) {
		queueSet.downloadSequentially(tasks);
	} else {
		queueSet.downloadTogether(tasks);
	}
	mDownloadCompleteCount = 0;
	mIsDownloading = true;
	queueSet.start();
	return true;
}

public void pause() {
	FileDownloader.getImpl().pause(mDownloadListener);
	mIsDownloading = false;
}

public boolean isDownloading() {
	return mIsDownloading;
}`

**Comment by fatbush** [comment]
附上代码和报错的日志

    下载逻辑代码：
    [下载逻辑.txt](https://github.com/lingochamp/FileDownloader/files/1021032/default.txt)

    报错日志：
    [下载引擎报错日志0.txt](https://github.com/lingochamp/FileDownloader/files/1021034/0.txt)

**Comment by Jacksgong** [comment]
根据日志我没有找到原因，根据你的描述与代码，我在Demo的混合测试的多任务串行下载中尝试编写了复现代码（在开始多任务串行前暂停相通listener的所有任务，然后再利用该listener启动串行任务），但是并没有复现。

- 可否看看[diff](https://github.com/lingochamp/FileDownloader/commit/f452a8694334f62d661574713d446d4bc7cff514)检查下是不是还没有符合你的复现路径?
- fork以后，切换到`test/reproduce-562`分支，看看哪里不符合你的场景，调整后，再进入Demo的"混合测试"的"多任务队列串行下载"，然后看看让其复现该问题。

多谢。

**Comment by fatbush** [comment]
我以前试过使用Demo，连续调用start()十几次是不会有问题的！
可是我现实场景是服务器响应的时候，启动的下载动作，我的响应的处理是线程来的！换句话说，就是有10几个这样的线程来同时调用这个start()函数！所以我们要弄几个线程来一起调用！
不过说来也奇怪~我试过重复顺序地调用我的接口请求服务器10次，也是疯狂地接到服务器的响应，疯狂地启动下载，也没有碰到这个报错！只有xmpp的方法~

**Comment by Jacksgong** [comment]
@fatbush 有新的进展随时同步。

> FileDownloader本身就是支持多线程调用`start`的，内部做了很多高并发相关的处理，本身内部就可能是多个线程对各类任务数据进行处理的。
