### ISSUE TITLE
急急急，关于初始化后下载没反应的问题

### ISSUE THREAD

**Issue by sunyuancun** [lingochamp/FileDownloader#563]
FileDownloader.init(getApplicationContext(), new DownloadMgrInitialParams.InitCustomMaker()
                .connectionCreator(new FileDownloadUrlConnection
                        .Creator(new FileDownloadUrlConnection.Configuration()
                        .connectTimeout(15_000) // set connection timeout.
                        .readTimeout(15_000) // set read timeout.
                        .proxy(Proxy.NO_PROXY) // set proxy
                )));
这个初始化 只能在application里吗？ 为什么在activity里初始化 不会触发下载，也没有报错。 我现在是在library中使用，不存在application

**Comment by Jacksgong** [comment]
可以关注下日志输出。

因为默认情况下下载服务在:filedownloader进程，不在Activity所在进程，因此如果没有在Application中进行初始化，下载服务那边无法得到初始化数据。

这个初始化放到Application也完全没有影响，不会因为这个初始化而做任何事情，只是传入CustomMaker以及ApplicationConText，源码都在，耗时在4~10ms左右。

**Comment by sunyuancun** [comment]
OK，明白了，谢谢回复😃

**Comment by yuxingfafu** [comment]
.connectTimeout(15_000) // set connection timeout.
.readTimeout(15_000) // set read timeout.
---这个超时时间和读取超时时间为什么弄成这样子的呀？  15_000  不直接写成 15000？

**Comment by rantianhua** [comment]
参考：http://www.importnew.com/12998.html

发自我的 iPhone
