### ISSUE TITLE
6.0以上的系统权限问题

### ISSUE THREAD

**Issue by shaodong2528** [lingochamp/FileDownloader#565]
请问下6.0以上的系统默认是不是做了读写存储卡的权限申请，因为我这边不申请权限也不创建下载目录也能正常下载。

**Comment by liaoxiang0808** [comment]
这个是根据你指定下载保存的path决定的, 不存储在sdcard当然不需要权限啦

**Comment by Jacksgong** [comment]
- filedownloader本身没有申请任何权限。
- 如果存储路径是在没有写入权限的路径的话，是会直接下载失败的。
- 在android 4.3或更高版本的系统中，对于`Context#getExternalxxx`的路径默认就有读写权限，不用特殊申请的。
