### ISSUE TITLE
需要的一些实用功能未实现，望参考

### ISSUE THREAD

**Issue by zhengshifei** [lingochamp/FileDownloader#567]
1、通过url过tag的删除接口
2、列出所有下载过的任务列表
3、下载空间管理，剩余空间不够时，删除最早的任务及文件

**Comment by wman0211** [comment]
记得好久以前有人问过作者这个问题, 很认可作者的回答啊, 这是一个框架而不是工具类, 作者列出了足够的接口让我们自己实现所说的这些功能了, 如果直接在框架中加入业务反而显得臃肿了
