### ISSUE TITLE
Resuming a paused task after application restart

### ISSUE THREAD

**Issue by LloydBlv** [lingochamp/FileDownloader#568]
I was wondering if there's a way to resume the downloaded task after application has been killed or phone has been restarted
thanks

**Comment by Jacksgong** [comment]
FileDownloader resumes the downloaded task automatically if you invoke `BaseDownloadTask#start`, whatever the downloaded task was paused or be interrupted.

furthermore, If you don't want the task is resumed automatically, you need to invoke `FileDownloader#clear` first.
