### ISSUE TITLE
FileDownloader- how to detect the file is downloaded

### ISSUE THREAD

**Issue by zhangchaojiong** [lingochamp/FileDownloader#569]
1.请问 如何检测 这个Url 已经被下载到指定的路径？

**Comment by Jacksgong** [comment]
下载的时候如果仅仅是给了url，那么其存储路径将会是: `FileDownloadUtils.getDefaultSaveFilePath(url)`，通过这个得到存储路径`path`后，判断该路径文件是否存在即可。如果不存在说明未下载完成或没有开始下载（下载中的路径将会是目标路径加`.temp`拓展名的路径)，如果文件存在说明已经下载完成。
