### ISSUE TITLE
下载失败后文件.temp问题

### ISSUE THREAD

**Issue by bobulucky** [lingochamp/FileDownloader#571]
所在网络环境很差，最后在下载目录下出现文件名.temp的文件是怎么回事，这种情况有回调方法处理吗？

**Comment by wman0211** [comment]
这个是下载的临时文件, 文件正常下载成功以后就没 .temp了

**Comment by Jacksgong** [comment]
是的目前的.temp是下载中的文件，下载过程所有的数据都是写入.temp的文件中，写入完成后，该文件就会重命名为目标文件。这样带来有两个好处:

1. 可以通过.temp来预分配整个下载文件的大小
2. 可以通过.temp来判断文件是否下载文件，如果文件未下载完成便是.temp文件，下载完成便不是.temp文件，无需单独存储到数据库中，导致相关判断需要加载整个数据库

**Comment by bobulucky** [comment]
谢谢解答！
