### ISSUE TITLE
请问暂停后，如何获能得下载的进度？谢谢了

### ISSUE THREAD

**Issue by keeponZhang** [lingochamp/FileDownloader#572]

**Comment by wman0211** [comment]
只要manage链接上了  随时都能拿到进度吧

**Comment by Jacksgong** [comment]
可以通过对应的任务Id，通过`FileDownloader#getSoFar` 来获取。

需要特别注意的是，这个下载进度是缓存在下载服务的数据库中的，因此需要下载服务存在的时候才获取。可以通过[这些方式](https://github.com/lingochamp/FileDownloader/issues/364) 来简化。
