### ISSUE TITLE
ArrayOutOfIndexException

### ISSUE THREAD

**Issue by yangalan123** [lingochamp/FileDownloader#574]
Hello! I try to use FileDownloader to download some files via HTTP, but I came across such exception while programming:

My Code here:  (try to combine with gridview....)
FileDownloader.init(getApplicationContext()); 
.........
DownLoadList.setOnItemClickListener(new AdapterView.OnItemClickListener() {

                @Override
                public void onItemClick(AdapterView<?> adapterView, View view, int i, long l) {
                    //Intent intent = new Intent(Intent.ACTION_VIEW);
                    //intent.setData(Uri.parse(hrefs.get(i)));
                    //startActivity(intent);
                    try {
                        FileDownloader.getImpl().create(hrefs.get(i)).setTag(1).setPath(Environment.DIRECTORY_DOWNLOADS).addHeader(titles.get(i)).setListener(createListener()).start();
                    }catch(Exception e)
                    {
                        e.printStackTrace();
                    }
                }
            });

Stacktrace shows that problems happens in com.liulishuo.filedownloader.model.FileDownloadHeader
from com.liulishuo.filedownloadTask

**Comment by Jacksgong** [comment]
Consider following way to point out cause:

1.  Whether all values on `titles` is legal: `<key>:<value>`
2. Whether the `i` is out of index for `titltes`.
