### ISSUE TITLE
正常网络限速后下载回调没执行

### ISSUE THREAD

**Issue by dd2664** [lingochamp/FileDownloader#575]
限速(1KB/s)后下载回调了pending，然后就一直没有回调了，如果一会（比如10秒内）去除限速，几秒后会继续正常下载；但是如果很久以后（比如1分钟后）才去除限速，就一直没有回调了，既没有继续下载，也没有回调失败

**Comment by dd2664** [comment]
问题已解决，设置FileDownloadUrlConnection.Configuration的超时时间

**Comment by Jacksgong** [comment]
👍 好的。
