### ISSUE TITLE
IllegalStateException:has already accomplished all his job, but there still are some messages in parcel queue[1]

### ISSUE THREAD

**Issue by fatbush** [lingochamp/FileDownloader#576]
@Jacksgong  好端端地#562被Close掉了！重新上传一遍吧！
问题描述：
最近我的工程使用了这个控件，遇到这个报错。找到重现的办法了！逻辑如下：软件一启动，然后就收到连续10条的XMPP消息，收到消息后，就马上请求服务器，服务器返回后，就直接启动下载了！接着就有可能报错了！就是线程竞争引起的！在start()中加了同步锁以后，结果一样。使用的是方法二启动下载。每个下载启动前，我会运行pause。

想问问大家有遇到过吗？
请问是怎么导致这个报错出现的，我应该怎么避免？

报错日志截图：
![_20170523234423](https://cloud.githubusercontent.com/assets/10277776/26363011/51475d42-4012-11e7-8e66-dcf8808afb29.png)

错误的代码位置：
![3108b306-37c4-11e7-98c4-a863ed4864bd](https://cloud.githubusercontent.com/assets/10277776/26363074/7c7b5d06-4012-11e7-99ce-9216608b6461.png)

附上日志和我的代码
代码：
[default.txt](https://github.com/lingochamp/FileDownloader/files/1022782/default.txt)

日志：
[下载引擎报错日志0.txt](https://github.com/lingochamp/FileDownloader/files/1022783/0.txt)

**Comment by Jacksgong** [comment]
可能是你误点了，我重新打开了，抽空的时候我看下，该Issue请转到 #562
