### ISSUE TITLE
sending message to a Handler on a dead thread

### ISSUE THREAD

**Issue by BinZhiLy** [lingochamp/FileDownloader#577]
Handler (android.os.Handler) {c7a3968} sending message to a Handler on a dead thread
                                               java.lang.IllegalStateException: Handler (android.os.Handler) {c7a3968} sending message to a Handler on a dead thread

**Comment by Jacksgong** [comment]
Could you please provide more detail error stack? And do you remember how did you encounter such exception?

**Comment by Jacksgong** [comment]
This bug has been fixed since v1.5.6.
