### ISSUE TITLE
暂停后恢复下载，有时连接资源（回调pending）要很长时间以后才能开始下载，甚至偶尔还会失败

### ISSUE THREAD

**Issue by langxia** [lingochamp/FileDownloader#58]
暂停后恢复下载，有时连接资源（回调pending）要很长时间以后才能开始下载，甚至偶尔还会失败，难道是网络原因？但是我直接下载就很快，而且貌似暂停-恢复-再暂停这样操作比较频繁的话，这种现象更容易出现，（我直接下载和恢复下载调的是同一套代码）

**Comment by Jacksgong** [comment]
是同一套代码的。这些应该是没有问题的。

**Comment by Jacksgong** [comment]
整个逻辑都只有一套，你可以理解所有下载都是恢复下载，只是一个从0开始，一个从上次下载断点那个地方开始。
