### ISSUE TITLE
pending后不执行started，一直处于等待状态

### ISSUE THREAD

**Issue by mengliyuxuan** [lingochamp/FileDownloader#580]
我设置的最大线程数是1，然后下载，但是一直处于pendin状态，不执行started，导致以后所有的任务不能下载，
1、这时同时暂停所有的任务，再启动某个下载，还是处于pending，除非把程序杀死，下次才可以继续下载。这种情况不是必现的，大神知道这是什么原因吗

**Comment by Jacksgong** [comment]
推荐排查方法:

1. 检查Logcat中的日志输出，特别关注警告、错误日志
2. 将场景套到Demo Project中看看能否复复现，保存复现前后的日志与操作细节


---

如果经过以上两个方案还无法解决，告知前后日志与操作细节，该Issue将重新打开继续跟踪该问题。
