### ISSUE TITLE
启动多任务下载的时候，progress方法怎么不回调？

### ISSUE THREAD

**Issue by bobulucky** [lingochamp/FileDownloader#581]
在多任务下载中，progress方法没有触发

**Comment by Jacksgong** [comment]
#### 推荐排查方法:

1. 看看Logcat有没有警告日志或错误日志
2. 可以通过 [这些方法](https://github.com/lingochamp/FileDownloader/issues/336#issuecomment-250646374) 来调整回调的频率
3. clone下demo的project将链接贴进去看看，对比下写法上是否存在问题，比如回调回来以后没有做相关处理?

---

经过上面的排查，依然无法解决，再贴出线索，我再重新打开该Issue。
