### ISSUE TITLE
怎样获取跳转后真实的下载地址？

### ISSUE THREAD

**Issue by tomasky** [lingochamp/FileDownloader#582]
怎样获取跳转后真实的下载地址？

**Comment by liaoxiang0808** [comment]
[](https://github.com/lingochamp/FileDownloader/issues/590)  你的问题是跟这个一样吗?

**Comment by tomasky** [comment]
@liaoxiang0808  不是，是307状态后的下载地址

**Comment by Jacksgong** [comment]
@tomasky 为了足够轻量，默认的组件是不支持的。默认组件可以看[这里](https://github.com/lingochamp/FileDownloader/issues/415#issuecomment-268950004)。

但是FileDownloader是支持[定制组件的](https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component)，这意味着你可以简单的实现自己的支持307的connection，然后注册进来就行了。

最简单的方式:

引入[okhttp组件](https://github.com/Jacksgong/filedownloader-okhttp3-connection)快速支持302、307等重定向问题。
