### ISSUE TITLE
Default FileDownloadUrlConnection Support 302

### ISSUE THREAD

**Issue by liaoxiang0808** [lingochamp/FileDownloader#584]
java.util.MissingFormatArgumentException: Format specifier '%s'

我用的com.liulishuo.filedownloader:library:1.3.9, 请问是不支持https吗?

**Comment by Jacksgong** [comment]
这个和https无关，可以贴下完整的错误栈给我看下吗?

**Comment by liaoxiang0808** [comment]
我测试https://github.com/lingochamp/FileDownloader/raw/master/art/Cause_of_Attached.png  是可以正常下载的, 但是公司的url不行, 下面是错误信息, url啥的我用xxx代替了

 FileDownloader.LostServiceConnectedHandler: The downloader service is connected.
05-31 18:40:19.011  9705 10407 V FileDownloader.DownloadTaskHunter: call start Url[xxx], Path[xxx] Listener[xxx$1@86dc510], Tag[xxx@327f809]
05-31 18:40:19.030  9705 10409 D FileDownloader.FileDownloadMessenger: notify begin 1461839756@com.liulishuo.filedownloader.DownloadTask@bd2628
05-31 18:40:19.038  9705 10409 V FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@d199f41 by 0 
05-31 18:40:19.039  9705 10409 V FileDownloader.FileDownloadList: add list in all 1461839756@com.liulishuo.filedownloader.DownloadTask@bd2628 0 1
05-31 18:40:19.058 10392 10404 D FileDownloader.FileDownloadRunnable: On resume 1461839756
05-31 18:40:19.128  9705 10415 D FileDownloader.MessageSnapshotGate: ~~~callback 1461839756 old[0] new[1] 1
05-31 18:40:19.129  9705 10415 D FileDownloader.FileDownloadMessenger: notify pending 1461839756@com.liulishuo.filedownloader.DownloadTask@bd2628
05-31 18:40:19.326  9705 10415 D FileDownloader.MessageSnapshotGate: ~~~callback 1461839756 old[1] new[6] 1
05-31 18:40:19.327  9705 10415 D FileDownloader.FileDownloadMessenger: notify started 1461839756@com.liulishuo.filedownloader.DownloadTask@bd2628
05-31 18:40:19.328 10392 10414 D FileDownloader.FileDownloadRunnable: start download 1461839756 url:xxx
05-31 18:40:19.347 10392 10414 D FileDownloader.FileDownloadMgr: can't continue 1461839756 file not suit, exists[FALSE], directory[FALSE]
05-31 18:40:19.372 10392 10414 D FileDownloader.FileDownloadRunnable: 1461839756 request header {}
05-31 18:40:19.687 10392 10414 D FileDownloader.FileDownloadRunnable: On retry 1461839756 java.util.MissingFormatArgumentException: Format specifier '%s' 1 1
05-31 18:40:19.705 10392 10414 D FileDownloader.FileDownloadRunnable: start download 1461839756 url:xxx
05-31 18:40:19.740 10392 10414 D FileDownloader.FileDownloadMgr: can't continue 1461839756 file not suit, exists[FALSE], directory[FALSE]
05-31 18:40:19.741 10392 10414 D FileDownloader.FileDownloadRunnable: 1461839756 request header {}
05-31 18:40:19.884  9705 10415 D FileDownloader.MessageSnapshotGate: ~~~callback 1461839756 old[6] new[5] 1
05-31 18:40:19.885  9705 10415 D FileDownloader.FileDownloadMessenger: notify retry 1461839756@com.liulishuo.filedownloader.DownloadTask@bd2628 1 1 java.util.MissingFormatArgumentException: Format specifier '%s'
05-31 18:40:20.219 10392 10414 D FileDownloader.FileDownloadRunnable: On error 1461839756 java.util.MissingFormatArgumentException: Format specifier '%s'
05-31 18:40:20.244  9705 10415 D FileDownloader.MessageSnapshotGate: ~~~callback 1461839756 old[5] new[-1] 1
05-31 18:40:20.245  9705 10415 V FileDownloader.FileDownloadList: remove 1461839756@com.liulishuo.filedownloader.DownloadTask@bd2628 left -1 0
05-31 18:40:20.245  9705 10415 D FileDownloader.FileDownloadMessenger: notify error 1461839756@com.liulishuo.filedownloader.DownloadTask@bd2628 java.util.MissingFormatArgumentException: Format specifier '%s'
05-31 18:40:20.246  9705 10415 V FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@d199f41 by -1 
05-31 18:40:20.358  9705  9705 W FileDownloader.FileDownloader: request pause but not exist 1461839756

**Comment by liaoxiang0808** [comment]
使用1.4.3版本后, 错误信息变成 FileDownloadHttpException: response code error: 302 了, 查了下是重定向的原因吗?

05-31 19:51:41.978  3856  3856 V FileDownloader.DownloadTaskHunter: the task[1461839756] has been into the launch pool
05-31 19:51:42.030  3856  4703 D FileDownloader.FileDownloadMessenger: notify begin 1461839756@com.liulishuo.filedownloader.DownloadTask@58d8a0e
05-31 19:51:42.030  3856  4703 V FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@2283c2f by 11 
05-31 19:51:42.031  3856  4703 V FileDownloader.FileDownloadList: add list in all 1461839756@com.liulishuo.filedownloader.DownloadTask@58d8a0e 11 1
05-31 19:51:42.036  4334  4347 D FileDownloader.FileDownloadMgr: request start the task with url(xxx) path(xxx) isDirectory(FALSE)
05-31 19:51:42.037  4334  4347 D FileDownloader.FileDownloadRunnable: On resume 1461839756
05-31 19:51:42.080  3856  4708 D FileDownloader.MessageSnapshotGate: ~~~callback 1461839756 old[11] new[1] 1
05-31 19:51:42.081  3856  4708 D FileDownloader.FileDownloadMessenger: notify pending 1461839756@com.liulishuo.filedownloader.DownloadTask@58d8a0e
05-31 19:51:42.198  3856  4708 D FileDownloader.MessageSnapshotGate: ~~~callback 1461839756 old[1] new[6] 1
05-31 19:51:42.198  3856  4708 D FileDownloader.FileDownloadMessenger: notify started 1461839756@com.liulishuo.filedownloader.DownloadTask@58d8a0e
05-31 19:51:42.226  4334  4707 D FileDownloader.FileDownloadRunnable: start download 1461839756 xxx
05-31 19:51:42.228  4334  4707 D FileDownloader.FileDownloadMgr: can't continue 1461839756 file not suit, exists[FALSE], directory[FALSE]
05-31 19:51:42.229  4334  4707 D FileDownloader.FileDownloadRunnable: 1461839756 request header {}
05-31 19:51:42.487  4334  4707 D FileDownloader.FileDownloadRunnable: On retry 1461839756 com.liulishuo.filedownloader.exception.FileDownloadHttpException: response code error: 302, 
05-31 19:51:42.487  4334  4707 D FileDownloader.FileDownloadRunnable:  request headers: {} 
05-31 19:51:42.487  4334  4707 D FileDownloader.FileDownloadRunnable:  response headers: {null=[HTTP/1.1 302 Found], Access-Control-Allow-Origin=[*], Connection=[keep-alive], Content-Type=[text/html; charset=ISO-8859-1], Date=[Wed, 31 May 2017 11:51:55 GMT], Location=[xxx], Server=[openresty/1.7.10.2], Transfer-Encoding=[chunked], X-Android-Received-Millis=[1496231502484], X-Android-Response-Source=[NETWORK 302], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1496231502380]} 1 1
05-31 19:51:42.534  3856  4708 D FileDownloader.MessageSnapshotGate: ~~~callback 1461839756 old[6] new[5] 1
05-31 19:51:42.535  3856  4708 D FileDownloader.FileDownloadMessenger: notify retry 1461839756@com.liulishuo.filedownloader.DownloadTask@58d8a0e 1 1 com.liulishuo.filedownloader.exception.FileDownloadHttpException: response code error: 302, 
05-31 19:51:42.535  3856  4708 D FileDownloader.FileDownloadMessenger:  request headers: {} 
05-31 19:51:42.535  3856  4708 D FileDownloader.FileDownloadMessenger:  response headers: {null=[HTTP/1.1 302 Found], Access-Control-Allow-Origin=[*], Connection=[keep-alive], Content-Type=[text/html; charset=ISO-8859-1], Date=[Wed, 31 May 2017 11:51:55 GMT], Location=[xxx], Server=[openresty/1.7.10.2], Transfer-Encoding=[chunked], X-Android-Received-Millis=[1496231502484], X-Android-Response-Source=[NETWORK 302], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1496231502380]}
05-31 19:51:42.598  4334  4707 D FileDownloader.FileDownloadRunnable: start download 1461839756 xxx
05-31 19:51:42.602  4334  4707 D FileDownloader.FileDownloadMgr: can't continue 1461839756 file not suit, exists[FALSE], directory[FALSE]
05-31 19:51:42.603  4334  4707 D FileDownloader.FileDownloadRunnable: 1461839756 request header {}
05-31 19:51:42.888  4334  4707 D FileDownloader.FileDownloadRunnable: On error 1461839756 com.liulishuo.filedownloader.exception.FileDownloadHttpException: response code error: 302, 
05-31 19:51:42.888  4334  4707 D FileDownloader.FileDownloadRunnable:  request headers: {} 
05-31 19:51:42.888  4334  4707 D FileDownloader.FileDownloadRunnable:  response headers: {null=[HTTP/1.1 302 Found], Access-Control-Allow-Origin=[*], Connection=[keep-alive], Content-Type=[text/html; charset=ISO-8859-1], Date=[Wed, 31 May 2017 11:51:55 GMT], Location=xxx], Server=[openresty/1.7.10.2], Transfer-Encoding=[chunked], X-Android-Received-Millis=[1496231502885], X-Android-Response-Source=[NETWORK 302], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1496231502762]}
05-31 19:51:42.915  3856  4708 D FileDownloader.MessageSnapshotGate: ~~~callback 1461839756 old[5] new[-1] 1
05-31 19:51:42.915  3856  4708 V FileDownloader.FileDownloadList: remove 1461839756@com.liulishuo.filedownloader.DownloadTask@58d8a0e left -1 0
05-31 19:51:42.916  3856  4708 D FileDownloader.FileDownloadMessenger: notify error 1461839756@com.liulishuo.filedownloader.DownloadTask@58d8a0e com.liulishuo.filedownloader.exception.FileDownloadHttpException: response code error: 302, 
05-31 19:51:42.916  3856  4708 D FileDownloader.FileDownloadMessenger:  request headers: {} 
05-31 19:51:42.916  3856  4708 D FileDownloader.FileDownloadMessenger:  response headers: {null=[HTTP/1.1 302 Found], Access-Control-Allow-Origin=[*], Connection=[keep-alive], Content-Type=[text/html; charset=ISO-8859-1], Date=[Wed, 31 May 2017 11:51:55 GMT], Location=[xxx], Server=[openresty/1.7.10.2], Transfer-Encoding=[chunked], X-Android-Received-Millis=[1496231502885], X-Android-Response-Source=[NETWORK 302], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1496231502762]}
05-31 19:51:42.916  3856  4708 V FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@2283c2f by -1 
05-31 19:51:42.971  3856  3856 W FileDownloader.FileDownloader: request pause but not exist 1461839756

**Comment by Jacksgong** [comment]
目前的处理方式与原因参考下这里: https://github.com/lingochamp/FileDownloader/issues/415#issuecomment-268950004

---

有考虑默认的网络连接器上支持重定向了。
