### ISSUE TITLE
Temp file not change to original name after download completed

### ISSUE THREAD

**Issue by vd92** [lingochamp/FileDownloader#587]
First of all thanks for this great library
as i said in title , after completing download temp files not rename to original name of link and i couldn't find a way to find out which temp file is for which link

**Comment by Jacksgong** [comment]
This information is not detail enough for me to finger out the case, because it woks well on my phone, so:

Could you please clone the demo project and reproduce your problem on there and give me more information or problem-demo project to me?

**Comment by vd92** [comment]
after review demo project I found out by using setPath(PATH,true) it doesn't rename temp file and I should use setPath(PATH) instead

**Comment by Jacksgong** [comment]
@vd92 Sorry? I test on the `SingleTaskTestActivity` and the second task is using `setPath(PATH, true)`, but when it is completed it really renamed the temp file, could you please give me the more detail inform to reproduce your problem?
