### ISSUE TITLE
请问https下载过程中，断点续传没有生效？

### ISSUE THREAD

**Issue by Likarl** [lingochamp/FileDownloader#589]
pause之后start，每次都是从头下载。
测试链接：https://github.com/lingochamp/FileDownloader/archive/master.zip

**Comment by Jacksgong** [comment]
这个与https无关，我刚刚测试了下。**原因是该资源服务端不支持断点续传**: 所提供的测试连接，每次请求返回都是200，不支持Partial(206)(按区间取回数据)，因此服务端不支持断点续传。

**Comment by 363988539** [comment]
我想问下，你那个是怎么支持https下载的呢，我用这个框架写了个demo，但是https下载不了呢？谢谢哈！

**Comment by Jacksgong** [comment]
@363988539 参考下这里: https://github.com/lingochamp/FileDownloader/issues/437#issuecomment-270825192
