### ISSUE TITLE
下载中暂停，会连接资源，在连接资源过程中点暂停，会报warn，然后又连接资源，但是progress方法就只回调一次，就卡在那里了， 这个是什么情况（反复暂停、恢复下载就容易出现这个问题）

### ISSUE THREAD

**Issue by langxia** [lingochamp/FileDownloader#59]
03-18 10:30:44.076 12044-12044/com.ciwong.fiveienglish D/downloader: pending
03-18 10:30:44.316 12044-12044/com.ciwong.fiveienglish D/downloader: paused
03-18 10:30:44.666 12044-12506/com.ciwong.fiveienglish W/FileDownloader.FileDownloadTask: warn, but no listener to receive progress, switch to pending 1065302812 1
03-18 10:30:44.686 12044-12044/com.ciwong.fiveienglish D/downloader: pending
03-18 10:30:57.606 12044-12044/com.ciwong.fiveienglish D/downloader: connected
03-18 10:30:57.646 12044-12044/com.ciwong.fiveienglish D/downloader: progress

**Comment by Jacksgong** [comment]
warn只会在启动了另外一个相同的任务的时候发生，然而我听你的描述只能猜测你是否是你把监听注册给了第二个相同的任务了。

这过程是没有问题的，建议你clone FileDownloader demo下来，执行下你的那个操作看看效果。然后再根据文档检查下调用。我们自己也在使用，做高并发反复使用。

**Comment by langxia** [comment]
warn, but no listener to receive progress, switch to pending 1065302812 1 是报这个日志，这个是什么意思，一般什么情况下会报？

**Comment by Jacksgong** [comment]
其实我代码注释里面已经写了这个注释，希望你能够从源码入手，当我这里我再给你解释下:

```
final int count = FileDownloadList.getImpl().count(getDownloadId());
if (count <= 1) {
    // 1. this progress kill by sys and relive,
    // for add at least one listener
    // or 2. pre downloading task has already completed/error/paused
    // request status
    final int currentStatus = _getStatusFromServer(downloadId);
    FileDownloadLog.w(this, "warn, but no listener to receive progress, " +
            "switch to pending %d %d", getDownloadId(), currentStatus);

    if (FileDownloadStatus.isIng(currentStatus)) {
        // ing, has callbacks
        // keep and wait callback

        setStatus(FileDownloadStatus.pending);
        getDriver().notifyPending();
        break;
    } else {
        // already over and no callback
    }

}
```

> 这个情况是，原本需要回调一个warn，但是发现这任务已经不在队列中了。

## 两种情况会走到这里:

1. 当前进程(一般是UI进程)被系统回收了，那么队列数据已经全部释放，这个当前进程在后台，系统内存不足，将该进程回收导致。
2. 上一个下载已经完结了(出现错误结束/下载完成结束/被暂停结束)。

而且我通过你的log看到的，也是符合预期的:

```
// 开始下载，回调 pending
03-18 10:30:44.076 12044-12044/com.ciwong.fiveienglish D/downloader: pending
// 点击了停止下载，回调 paused
03-18 10:30:44.316 12044-12044/com.ciwong.fiveienglish D/downloader: paused
// 这个不会回调
03-18 10:30:44.666 12044-12506/com.ciwong.fiveienglish W/FileDownloader.FileDownloadTask: warn, but no listener to receive progress, switch to pending 1065302812 1
// 重新点击了下载，回调pending
03-18 10:30:44.686 12044-12044/com.ciwong.fiveienglish D/downloader: pending
// 连接上，回调 connected
03-18 10:30:57.606 12044-12044/com.ciwong.fiveienglish D/downloader: connected
// 回调 进度
03-18 10:30:57.646 12044-12044/com.ciwong.fiveienglish D/downloader: progress
```

---

> 还有一点你要注意的是，我们引擎中各个状态回调是独立的，不会因为某个回调而对另外的回调进行代码层面的干涉。

> 还有一个你可能要明白下: progress的回调次数是不一定的，这个我和你解释下: 首先我们取数据流的buffer大小是4096byte，因此最小回调间隙是取完4096buffer以后回调一次，因此即便你设置回调1000次，但是文件大小如果没有4096*1000byte，回调次数也会小于1000次。
> 下载是自动断点续传的，如果你之前就下载快好了。被你暂停了，你又点了继续，有可能续传部分就剩4096byte了，那么progress回调就只剩一次。
