### ISSUE TITLE
FileDownloadHttpException: response code error: 302,

### ISSUE THREAD

**Issue by liaoxiang0808** [lingochamp/FileDownloader#590]
com.liulishuo.filedownloader.exception.FileDownloadHttpException: response code error: 302,
请问不支持重定向的这种下载吗?

**Comment by Jacksgong** [comment]
目前的处理方式与原因参考下这里: https://github.com/lingochamp/FileDownloader/issues/415#issuecomment-268950004

---

有考虑默认的网络连接器上支持重定向了。

**Comment by Jacksgong** [comment]
@liaoxiang0808 可以通过引入[okhttp组件](https://github.com/Jacksgong/filedownloader-okhttp3-connection)快速支持302
