### ISSUE TITLE
升级1.5.0后初始化就报空指针

### ISSUE THREAD

**Issue by lizixian18** [lingochamp/FileDownloader#592]
![image](https://cloud.githubusercontent.com/assets/16240767/26767754/4b9fd096-49d5-11e7-8cd0-af5795178450.png)

FileDownloader.init(getApplicationContext());

**Comment by Jacksgong** [comment]
一会儿发布新版本带上，谢谢提出。

**Comment by Jacksgong** [comment]
@lizixian18 @UBNTRogerLuo

[v1.5.1](https://github.com/lingochamp/FileDownloader/releases/tag/v1.5.1) 修复了该问题。

**Comment by UBNTRogerLuo** [comment]
Thanks.
