### ISSUE TITLE
https为什么不能下载呢？可以通过设置来解决么？望回复！急急急急。。。

### ISSUE THREAD

**Issue by 363988539** [lingochamp/FileDownloader#594]
我用这个框架写了个demo，然后http的可以正常下载，但是https的就是不可以下载直接回调了completed 回调 别的其它回调都没有走，这是为啥呢，是这个框架不支持https的下载，还是我设置的有问题？望作者尽快回复！谢谢！

**Comment by Jacksgong** [comment]
是支持的。参考下这里: https://github.com/lingochamp/FileDownloader/issues/437#issuecomment-270825192

如果对应资源链接有问题，可以看看对应的错误信息或者是相关Logcat。

**Comment by Jacksgong** [comment]
如果有进一步的信息可以验证存在具体问题，这个issue将被重新打开。
