### ISSUE TITLE
Network Disconnect Error Handle ?

### ISSUE THREAD

**Issue by aldocano** [lingochamp/FileDownloader#596]
How to handle network disconnect during download. 
What i want to achieve is that when the download disconnects to switch activity. But when i tried the intent on Error listener the intent wont fire.
`                    @Override
                    protected void error(BaseDownloadTask task, Throwable e) {
                        super.error(task, e);
                        Intent intent = new Intent(getApplicationContext(), MainActivity.class);
                        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
                        startActivity(intent);
                        finish();
                    }
`

**Comment by Jacksgong** [comment]
When I disconnect my network I receive `SocketException` on the `error` callback . 

so, what do you get when you Network disconnect?

**Comment by aldocano** [comment]
How can i capture the network disconnect or download error  and switch intent for example?

**Comment by Jacksgong** [comment]
we callback one `error` event with pause downloading through `FileDownloadListener` you provided when you start downloading task.

**Comment by aldocano** [comment]
Hi there while refering to this issue #103 , i have an error while downloading .

`W/System.err: java.lang.StackOverflowError: stack size 1038KB
W/System.err: at com.divitech.dynamicSignage.Services.DownloadManager$1.blockComplete(DownloadManager.java:78)
W/System.err: at com.divitech.dynamicSignage.Services.DownloadManager$1.blockComplete(DownloadManager.java:78)`

**Comment by aldocano** [comment]
Update, i deleted the part 

` @Override
        protected void blockComplete(BaseDownloadTask task) {

            blockComplete(task);
            Log.e("DownloadBlock", "Completed");
        }`
