### ISSUE TITLE
为什么在队列中，有时候点了开始，一直处于pend状态，而当前队列中并没有正在下载的任务

### ISSUE THREAD

**Issue by mengliyuxuan** [lingochamp/FileDownloader#597]

**Comment by Jacksgong** [comment]
后面是否有开始呢？ 

- `pending`是一个过度状态，pending状态说明任务已经进入下载线程池。当线程被线程池调度以后会回调`started`。
- 从`started`到`connected`涉及到第一次建连，根据网络情况这次可能会比较久
- 还有一个需要特别注意的是，在首个任务启动的时候，因为要等待启动下载的服务因此首次调用下载时需要等待下载服务启动，如果下载服务在独立进程（默认），还需要等待该进程启动，并数据库数据加载完成。因此这个过程比较久，但是如果是已经回调了`pending`那么说明这个过程早已经完成，因此下载线程池是在下载服务中的。

**Comment by Jacksgong** [comment]
有任何反馈，该issue会被重新打开。

**Comment by menshen** [comment]
我先一个问题，就是当队列里只有一个任务的时候，progress很快就有回调
如果现在队列中有一个任务，再添加一个新的任务，要很久才会回调第一次progress
