### ISSUE TITLE
Consider making FileDownloadTask public

### ISSUE THREAD

**Issue by minimalviking** [lingochamp/FileDownloader#6]
I think making FileDownloadTask public would be very beneficial, it would allow extending this class for custom usage of the library

**Comment by Jacksgong** [comment]
Thanks for your deep thinking.

Could you give me some case and I will consider about it. 

ps: I hide the `FileDownloadTask Class` because there are some internal mechanisms.

**Comment by minimalviking** [comment]
Oh you're right - I've just noticed that BaseDownloadTask has a `setTag` method:)

**Comment by Jacksgong** [comment]
Yes, you got it. thanks any way :)
