### ISSUE TITLE
after blockComplete starts again

### ISSUE THREAD

**Issue by franciscerio** [lingochamp/FileDownloader#60]
Is there any way to stop the request after blockComplete? 

My problem is after blockComplete is executed, it will connect again and re-download this request. 

private FileDownloadListener createListener(final VideoViewHolder holder, final String path, final VideoPlayerManager videoPlayerManager) {
        return new FileDownloadListener() {

            @Override
            protected void blockComplete(BaseDownloadTask task) {
                Logger.e(TAG, " BLOCKCOMPLETE " + task.getDownloadId());
                if (MediaUtils.isMediaDownloaded(media, false)) {
                    Logger.e(TAG, " BLOCKCOMPLETE downloaded");
                }
            }

            @Override
            protected void completed(final BaseDownloadTask task) {
                holder.percentageProgress.setVisibility(View.GONE);
                if (MediaUtils.isMediaDownloaded(media, false)) {
                    videoPlayerManager.playNewVideo(null, holder.videoPlayer, path);
                }

            }

            @Override
            protected void error(BaseDownloadTask task, Throwable e) {
                Logger.e(TAG, " ERROR");
            }

            @Override
            protected void warn(BaseDownloadTask task) {
                Logger.e(TAG, " WARN");
            }

            @Override
            protected void pending(BaseDownloadTask task, int soFarBytes, int totalBytes) {
                Logger.e(TAG, " PENDING " + MediaUtils.isMediaDownloaded(media, false));
            }

            @Override
            protected void progress(BaseDownloadTask task, int soFarBytes, int totalBytes) {
                try {
                    int progress = ((soFarBytes * 100) / totalBytes);
                    showProgressCounting(holder.percentageProgress, progress);
                } catch (ArithmeticException e) {
                    showProgressCounting(holder.percentageProgress, 0);
                }
            }

            @Override
            protected void paused(BaseDownloadTask task, int soFarBytes, int totalBytes) {
                Logger.e(TAG, " PAUSED");
            }

            @Override
            protected void connected(BaseDownloadTask task, String etag, boolean isContinue,
                                     int soFarBytes, int totalBytes) {
                super.connected(task, etag, isContinue, soFarBytes, totalBytes);
                Logger.e(TAG, " CONNECTED " + isContinue);
            }
        };
    }

**Comment by Jacksgong** [comment]
Sorry, we can't  stop the download request, in the fact,  when you receive the call-back blockComplete, it has been completed download. the call-back blockComplete is just recommended to unzip the downloaded file or some similar things you want to do on new-thread before you receive the exact call-back completed.

**Comment by franciscerio** [comment]
Ok. Thanks! :)

**Comment by Jacksgong** [comment]
:)
