### ISSUE TITLE
如何获取下载的位置

### ISSUE THREAD

**Issue by ranhuanbin** [lingochamp/FileDownloader#602]
你好, 调用下载, 然后退出当前界面, 再次点击下载, 会从上次下载的位置开始下载, 这个点我在源码里面没找到在哪里, 能麻烦告诉一下吗, aidl使用的有点儿牛, 看的不是很懂

**Comment by Jacksgong** [comment]
需要在下载之前获取断点的进度，可以通过`FileDownloader#getSofar(downloadId)` 获取，需要注意的的点在这里有提到: https://github.com/lingochamp/FileDownloader/issues/579#issuecomment-303930347

---

代码中处理断点，跟踪下`DownloadLaunchRunnable#isResumeAvailableOnDB`这个变量即可。
