### ISSUE TITLE
想问下，是否支持应用退出后后台服务继续下载？谢谢了

### ISSUE THREAD

**Issue by keeponZhang** [lingochamp/FileDownloader#603]

**Comment by Jacksgong** [comment]
FileDownloader的所有下载逻辑是在独立的下载服务，并且该服务默认配置也是运行在独立的进程，**因此肯定是可以的。** 

只不过应用进入后台以后，需要注意:

1. 你是否需要监听事件反馈？如果需要的话，你肯定还是需要注册相关的进度监听（如`FileDownloadListener`、`FinishListener`、FileDownloadMonitor`)。
2. 由于进入后台，那么下载服务所在进程变为服务进程，是否需要防止内存不足时被回收，是否需要防止用户在最近应用列表中移除，关联的下载服务不会被移除，需要的话参考下这里: https://github.com/lingochamp/FileDownloader/issues/347#issuecomment-252404000

---

P.S. 下载过程中各类中断，FileDownloader都已经考虑，保证可靠的断点续传: https://github.com/lingochamp/FileDownloader/wiki/Low-Memory%3F
