### ISSUE TITLE
大神，急求

### ISSUE THREAD

**Issue by wangchang163** [lingochamp/FileDownloader#604]
如果下载地址为http://192.168.2.3:91/pic/，为什么拿不到文件信息报错呢？因为这边更新代码问题，需要地址重定向一下，但是地址拿不到文件信息

**Comment by Jacksgong** [comment]
你提供的是局域网地址我这边无法进行验证。

你说的拿不到错误是什么问题，是说下载没有任何反应（没有任何Logcat、回调)吗？可说下具体情况吗。

地址如果需要重定向，参考下这里: https://github.com/lingochamp/FileDownloader/issues/415#issuecomment-268950004，也可以通过引入[okhttp组件](https://github.com/Jacksgong/filedownloader-okhttp3-connection)快速支持重定向等问题。
