### ISSUE TITLE
Is there any way to receive the completed callback when only the filedownloader process alive.

### ISSUE THREAD

**Issue by keeponZhang** [lingochamp/FileDownloader#605]

**Comment by Jacksgong** [comment]
不是很理解，你的 这些监听都是在主进程吗，如果在主进程，你的主进程如果存活着应该持续会接收到回调，如果主进程本身就被杀了，那么何来回调，这些监听都不在了？

**Comment by Jacksgong** [comment]
FileDownloader能够保障的是，即便是你主进程被杀了，下一次进来再次启动该任务，会重新attach上正在下载的任务然后持续获取到其进度监听。

**Comment by keeponZhang** [comment]
项目是个应用市场，要求应用退出后也要继续下载，下载成功实现静默安装，所以想要知道应用下载成功的回调。

**Comment by Jacksgong** [comment]
我描述下你的问题，你看看对不对:

- 下载服务所在进程存活，所以其会继续下载。
- 但是你主进程被杀了，那么你没有地方去监听进度

**Comment by keeponZhang** [comment]
对的，这个应该怎么解决？

**Comment by keeponZhang** [comment]
描述是对的，不知道这个问题现在有解决方案吗?

**Comment by Jacksgong** [comment]
@keeponZhang 目前的版本确实没有办法解决，能做的只是你下一次启动的时候，再启动这个任务可以获取到当前的下载进度。

下个版本我会新增一个广播:

1. 下个版本中`filedownloader.properties`会新增一个关键字`broadcast.completed`
2. `filedownloader.properties`中开启后，在下载完成后会发送一个广播，这样即便是主进程不在了，也能因为监听该广播被唤起。

---

P.S. 针对你的场景，你还需要确保下载服务能够得到保活，这块可以参考下: https://github.com/lingochamp/FileDownloader/issues/347#issuecomment-252404000

**Comment by keeponZhang** [comment]
好的，谢谢了
