### ISSUE TITLE
请教，download.max-network-thread-count=2 无效且不管我创建几个下载任务，它都进行下载，没有进行等待

### ISSUE THREAD

**Issue by wbb631094818** [lingochamp/FileDownloader#607]
我用的是：   public int startDownload(DownloadInfo downloadInfo) {
        BaseDownloadTask baseDownloadTask = FileDownloader.getImpl().create(downloadInfo.getDownload_url())
                .setPath(downloadInfo.getFile_path())
                .setTag(0, downloadInfo)
                .setAutoRetryTimes(3)// 当请求或下载或写文件过程中存在错误时，自动重试次数，默认为0次
                .setListener(lis);
        return baseDownloadTask.start();
    }

**Comment by Jacksgong** [comment]
原因是: **只要是单任务多线程**，其宿主线程没有被分支线程`join`，而其宿主线程在这个多线程场景下仅仅充当了检测多线程有效性的**简单建连操作，因此一结束，其他任务就可以进来占用线程池资源**。

这个问题会尽快修复，多谢反馈~

**Comment by Jacksgong** [comment]
@wbb631094818 已经在[v1.5.5](https://github.com/lingochamp/FileDownloader/releases/tag/v1.5.5)版本中修复了这个问题。
