### ISSUE TITLE
我在不同的界面添加单个下载任务，我在下载清单界面，如何控制当前只有一个任务在下载，同时当前任务下载完成会自动下载另一个任务，直到所有的清单任务全部下载完。

### ISSUE THREAD

**Issue by xinyangcuncun** [lingochamp/FileDownloader#608]

**Comment by xinyangcuncun** [comment]
引用了最新的包，解决了这个问题，可以把这个问题关闭了，谢谢大神

**Comment by Jacksgong** [comment]
@xinyangcuncun 除了设置`max-network-thread-count`为1来达到这个目的，还可以通过全局[共用一个监听器](https://github.com/lingochamp/FileDownloader/issues/103#issuecomment-209173124)，启动的时候设置为串行下载: `FileDownloader#start(listener:FileDownloadListener, isSerial:boolean)`来达到这个目的。
