### ISSUE TITLE
暂停以后，再恢复下载，会重新连接资源，即回调pending，但是重连失败，然后会retry，但是进度都没了，重新开始下载了

### ISSUE THREAD

**Issue by langxia** [lingochamp/FileDownloader#61]

**Comment by Jacksgong** [comment]
谢谢你的再次反馈。

你试试demo中的吧，你这么说这么简单的情形我们肯定是cover了的。我们自己也在高频使用，我怀疑有可能调用那里你没有理解导致的。如果你那边必现，你参考下demo，如果你参考demo也发现不了是哪里的问题，确定铁定是库的问题，希望能够提供存在问题的简单案例项目，放到github，我第一时间拉到本地，第一时间给问题解决了。

**Comment by langxia** [comment]
这个很好重现，你试试重连之前把网断掉，然后他error，然后开网开始下载，之前的进度就没了，从0开始下载了，必现的

**Comment by Jacksgong** [comment]
>参考下这个: #10 

这个bug在 0.1.5就修复了。请用最新版本 0.2.0

**Comment by langxia** [comment]
怎么看我现在在用的版本是多少啊？
