### ISSUE TITLE
java.lang.NullPointerException at FileDownloadThreadPool.findRunningTaskIdBySameTempPath 135

### ISSUE THREAD

**Issue by chiemy** [lingochamp/FileDownloader#613]

**Comment by Jacksgong** [comment]
这是一个多线程同步事件，确实是存在的高并发情况下低概率BUG，会在新版本修复。

#### 什么情况下出现?

在高并发启动各类任务的同时时候，刚好某个任务在其他任务执行`FileDownloadThreadPool#findRunningTaskIdBySameTempPath`这个方法提内的时候被移除了`FileDownloadThreadPool#cancel`。
