### ISSUE TITLE
Is there any way to receive the completed callback when only this filedownloader process alive?想问下这个问题有解决方案了吗？谢谢了。

### ISSUE THREAD

**Issue by keeponZhang** [lingochamp/FileDownloader#616]

**Comment by Jacksgong** [comment]
解决方案参考这里的评论: https://github.com/lingochamp/FileDownloader/issues/605#issuecomment-307334789

已经commit到master分支，会下下个版本[v1.5.7](https://github.com/lingochamp/FileDownloader/milestone/23)带上。

**Comment by Jacksgong** [comment]
代码改动点参考[这里](https://github.com/lingochamp/FileDownloader/commit/2445771c187ee73969404ffebab85fe7cc07e367)

**Comment by Jacksgong** [comment]
由于v1.5.6版本多是bug fix，所以希望v1.5.6是一个主要bug fix的稳定版本。因此这几个feature的支持就放到了v1.5.7版本了。

**Comment by keeponZhang** [comment]
请问现在可以用吗？

**Comment by Jacksgong** [comment]
虽然代码已经在master分支上，但是还没有发布v1.5.7版本。只能说已经完成了需求开发，但是还没有发版本。

需要等待[v1.5.7](https://github.com/lingochamp/FileDownloader/milestone/23)版本正式发布，目前预计是在下周六发布。

**Comment by keeponZhang** [comment]
是要到下周六才能用吗？

**Comment by Jacksgong** [comment]
e.... 是按照版本发布的，如果你始终依赖的旧版本，那么是始终没有更新的。

可以参考[往期的版本发布](https://github.com/lingochamp/FileDownloader/releases)。有新版本发布以后你需要修改自己gradle中所依赖的版本才行。

**Comment by Jacksgong** [comment]
你可以关注当前FileDownloader repo。

![image](https://user-images.githubusercontent.com/6176417/27267333-397303a6-54da-11e7-87bf-f75dc8b139cb.png)
如上图那里显示的是1.5.6，说明当前发布的最新版本是1.5.6，此时在gradle中引1.5.6版本:

```groovy
dependencies {
    compile 'com.liulishuo.filedownloader:library:1.5.6'
} 
```
这样默认无论从jcenter还是mavenCentral都可以拉到。

预计下周六发布1.5.7以后，修改点可以参考[CHANGELOG](https://github.com/lingochamp/FileDownloader/blob/master/CHANGELOG-ZH.md)，然后你可以看看上图的那个版本的位置是否变为1.5.7，如果是说明已经发布了，你修改gradle中的引用版本，就能用了。

**Comment by keeponZhang** [comment]
如果直接下载源码依赖就不用等到下周六，现在就可以用对吗？因为项目现在需要这个功能。

**Comment by Jacksgong** [comment]
@keeponZhang 对的，虽然不建议，但是确实是可以的，直接依赖master分支的代码就支持了。

**Comment by keeponZhang** [comment]
好的，谢谢了，帮了我的大忙了。

**Comment by Jacksgong** [comment]
@keeponZhang 嗯。要依赖master分支的libray module，因为里面还有AndroidManifest。

---

使用的话，参考下[这里的注解](https://github.com/lingochamp/FileDownloader/commit/2445771c187ee73969404ffebab85fe7cc07e367#diff-8235f845ece93964ced30d990e346138)。

> P.S. 还有一点需要特别注意的是，国内部分的ROM对广播接收这块进行了修改（如部分MIUI)，所以即便是注册了接收广播，也有可能在部分国内ROM上进程无法被唤起接收。

**Comment by keeponZhang** [comment]
好的，我测试一下。感谢。

**Comment by Jacksgong** [comment]
@keeponZhang 还有一个点要注意的是，从广播接收到的`Intent`通过`FileDownloadBroadcastHandler#parseIntent(Intent)`获取到的`FileDownloadModel`，该文件的存储路径是通过`FileDownloadModel#getTargetFilePath()`进行获取。
