### ISSUE TITLE
关于防盗链断点下载的问题

### ISSUE THREAD

**Issue by Kimxu** [lingochamp/FileDownloader#617]
你好，请教一个问题，我想做一个需求是关于防盗链的：
先用A链接下载视频，如果下次暂停之后，在尝试用A连接下载内容，如果A链接失效，就去鉴权获取新的链接B，使用B链接从A上次下载的地方开始下载视频。

我尝试使用 **FileDownloadHelper.IdGenerator** 修改id，保证这两次下载的id都是一样的。但是出现一个问题。就是当我A链接失效的时候，我在使用b链接下载，他还是会指向到A链接的下载地址。

请问防盗链的断点下载需要怎么处理，再次感谢

**Comment by Kimxu** [comment]
在 **FileDownloadManager**  **start**方法中 添加 

if (!TextUtils.equals(url, model.getUrl())) {
            model.setUrl(url);
            needUpdate2DB = true;
        }

就可以实现不同链接断点下载同一个文件  


再一次感谢作者无私开源

**Comment by Jacksgong** [comment]
赞，确实没有考虑到这样的case，不过你这样的修改是合理的，你提一个PR吧，我在下个版本带上。

**Comment by layasntx** [comment]
请问Kimxu，你是如何自定义ID的，我自定义ID以后，就无法下载了。
.idGenerator(new FileDownloadHelper.IdGenerator() {
                    @Override
                    public int transOldId(int oldId, String url, String path, boolean pathAsDirectory) {
                        return generateId(url, path, pathAsDirectory);
                    }

                    @Override
                    public int generateId(String url, String path, boolean pathAsDirectory) {
                        return FileDownloadUtils.md5(path).hashCode();
                    ｝

**Comment by layasntx** [comment]
@Kimxu

**Comment by layasntx** [comment]
@Jacksgong

**Comment by Jacksgong** [comment]
@layasntx 具体是怎么无法下载？

**Comment by Kimxu** [comment]
public class LoadIdGenerator implements FileDownloadHelper.IdGenerator {
    private Context mContext;
    private SDVodDao mVodDao;

    public LoadIdGenerator(Context context) {
        mContext = context;
        mVodDao = new SDVodDao(mContext);
    }

    @Override
    public int transOldId(int oldId, String url, String path, boolean pathAsDirectory) {
        return generateId(url, path, pathAsDirectory);
    }

    @Override
    public int generateId(String url, String path, boolean pathAsDirectory) {
        //这里只对视频缓存做id处理 /offData/文件夹
        if (path.contains("offData")) {
            if (TextUtils.isEmpty(url))
                throw new IllegalArgumentException("need auth");
            List<LoadTask> loadTasks = mVodDao.queryLoadTaskByUrl(url);
            LoadTask loadTask = loadTasks.get(0);
            if (pathAsDirectory) {
                int id = FileDownloadUtils.md5(formatString("%sp%s@dir", loadTask.getContentId(), path)).hashCode();
                Log.d("kimxu", id + " " + path + " find " + loadTasks.size() + "contentId " + loadTask.getContentId());
                return id;
            } else {
                int id = FileDownloadUtils.md5(formatString("%sp%s", loadTask.getContentId(), path)).hashCode();
                Log.d("kimxu", id + " " + path + " find " + loadTasks.size() + "contentId " + loadTask.getContentId());
                return id;
            }
        } else {
            if (pathAsDirectory) {
                return FileDownloadUtils.md5(formatString("%sp%s@dir", url, path)).hashCode();
            } else {
                return FileDownloadUtils.md5(formatString("%sp%s", url, path)).hashCode();
            }
        }
    }

    public static int generateId(String contentID, String path) {
        int id = FileDownloadUtils.md5(formatString("%sp%s", contentID, path)).hashCode();
        Log.d("kimxu static", id + " " + path);
        return id;
    }
}


这是我使用的代码，希望能帮助到你

**Comment by layasntx** [comment]
@Jacksgong 文件其实已经开始下载了，但是直到下载完成，全程都没有回调：
I/FileDownloader.MessageSnapshotGate: Receive the event 1, but there isn't any running task in the upper layer

**Comment by microDD** [comment]
@Kimxu  hi， 实现了自己的IdGenerator，但调用BaseDownloadTask.start() 方法都不会进入到FileDownloadManager的start方法中， 这该怎么处理？ 感谢感谢~
