### ISSUE TITLE
JRebel构建项目时,无法下载

### ISSUE THREAD

**Issue by LonelyMushroom** [lingochamp/FileDownloader#619]
额...我使用JRebel for Android构建项目时无法下载

**Comment by Jacksgong** [comment]
我估计是JRebel的问题，FileDownloader并没有针对JRebel做特殊的设置，而是符合Android规范的项目。

具体是报什么错误？

**Comment by LonelyMushroom** [comment]
@Jacksgong 也不是爆什么错误,就是进不去下载的监听,您有空可以试试,我觉得挺有趣的.不是您项目的问题

**Comment by Jacksgong** [comment]
好的。我抽空试试。

**Comment by pop1234o** [comment]
还真是，我用JRebel 构建的时候下载什么反应也没有，也不报错，我还以为是我写法错了，搞了好长时间才发现正常构建就可以下载，楼主有空可以看看

**Comment by Jacksgong** [comment]
@LonelyMushroom @pop1234o 测试发现这个是由于JRebel在`Service`运行在独立进程的时候，Bind始终无法绑定成功（没有`onServiceConnected`绑定成功回调）导致。

#### 解决方案

可以将FileDownload的下载服务**不运行在**独立进程，避开JRebel的这个问题，具体在[filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)中配置`process.non-separate=true`即可。
