### ISSUE TITLE
手机APN连接的客户专网服务器的文件，下载失败

### ISSUE THREAD

**Issue by zuijiusi** [lingochamp/FileDownloader#62]
手机APN连接客户专网的服务器，下载失败，弹出Toast如图；
使用不需要连接APN的服务器下载文件，正常。
![screenshot_2016-03-18-18-42-11](https://cloud.githubusercontent.com/assets/17403481/13875951/dd5a37c6-ed3b-11e5-8dac-0471cb7416bb.png)

**Comment by zuijiusi** [comment]
服务连接问题，下载正常，感谢楼主。

**Comment by Jacksgong** [comment]
:)
