### ISSUE TITLE
Unable to use v1.5.6: class not found

### ISSUE THREAD

**Issue by HugoGresse** [lingochamp/FileDownloader#620]
Hi there,

I wanted to update from 1.5.5 to 1.5.6 today and Android Studio can't find 
```
import com.liulishuo.filedownloader.BaseDownloadTask;
import com.liulishuo.filedownloader.FileDownloader;
```

Revert to 1.5.5 fix the issue. I've tried to invalidate AS cache and make the project but nothing work. I think the issue come from the library itself :/

**Comment by Jacksgong** [comment]
There is one guy also meet this problem: #618


---

But I check out the arr on jcenter everything seems okay: https://github.com/lingochamp/FileDownloader/issues/618#issuecomment-309368527

And I import on my project it seems work(from 1.5.5 to 1.5.6):

![image](https://user-images.githubusercontent.com/6176417/27278998-b212d990-5515-11e7-940b-52d0f858cfa5.png)

#### So Cloud you please provide more detail info?

- android build plugin version?
- android studio version?
- maybe your system?

**Comment by HugoGresse** [comment]
Android Studio 2.3.3
buildToolsVersion '24.0.3'
targetSdkVersion 24

my classpath : 
```

        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.4.1'
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.0'
        classpath 'com.google.gms:google-services:3.0.0'
        classpath 'me.tatarka:gradle-retrolambda:3.3.0'
```

Gradle version `gradle-2.14.1-all.zip`

Runing on Mac OS El Captain 10.11.6

**Comment by Jacksgong** [comment]
@HugoGresse I create your env, but not occur such problem, did you fix this problem?

<img width="1651" alt="screen shot 2017-06-21 at 5 10 41 pm" src="https://user-images.githubusercontent.com/6176417/27376527-03c442fc-56a5-11e7-85c6-f63434b80f78.png">

<img width="1628" alt="screen shot 2017-06-21 at 5 13 04 pm" src="https://user-images.githubusercontent.com/6176417/27376532-0960ad68-56a5-11e7-9598-b7333552725c.png">

**Comment by HugoGresse** [comment]
I still have the issue. I'll try to reproduce the problem in the coming week and let you know.

**Comment by Jacksgong** [comment]
ok. keep touch.

**Comment by HugoGresse** [comment]
I've update from 1.5.5 to 1.5.7 and no issue... the dependency was red for some time but then AS finded it. Yeaaah !

**Comment by Jacksgong** [comment]
okay...
