### ISSUE TITLE
文件下载的时候，进度好久不回调

### ISSUE THREAD

**Issue by liajt** [lingochamp/FileDownloader#621]
下载文件的时候，添加到队列，文件好久都不执行回调函数，没有进度，我查看文件，有.temp的文件存在，且大小是文件的大小，已经占用了大小，为什么没有回调呢，还有就是文件还没有下载，空间已经占了吗？

**Comment by Jacksgong** [comment]
参考下这里:

- https://github.com/lingochamp/FileDownloader/issues/246#issuecomment-237133750
- https://github.com/lingochamp/FileDownloader/issues/557#issuecomment-307994798

---

如果需要关闭预分配文件大小，可以参考[filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)中的`file.non-pre-allocation` 。
