### ISSUE TITLE
经常出现不下载的情况，没有回调进度，临时文件也没被创建，我之前频繁操作过暂停下载、启动下载

### ISSUE THREAD

**Issue by liajt** [lingochamp/FileDownloader#625]
源码：
FileDownloader.getImpl().create(realUrl)
                    .setPath(dir + bean.getRealName())
                    .setSyncCallback(true)// 不回调在ui线程
                    .setCallbackProgressTimes(3000) // 最大回调次数
                    .setCallbackProgressMinInterval(500)// 设置回调最小间隔2s
                    .setListener(demandListener)
                    .asInQueueTask()
                    .enqueue();

 FileDownloader.getImpl().start(demandListener, true);

**Comment by Jacksgong** [comment]
不好意思，按照你的描述我在demo project中频繁的操作，并未复现你说所说的情况。

#### 为了进一步定位问题:

1.  留意下Logcat看看有无Warn或者是Error级别的日志输出
2. 可否在demo project中进行复现呢？可以相对高概率的复现以后将分支发给我，我进一步定位下问题。

---

P.S. 关于无回调或回调不准确系列的QA，可以参考[这里](https://github.com/lingochamp/FileDownloader/wiki/processing-callback-frequency)。

**Comment by liajt** [comment]
大神你好，

关于不回调的问题，比较简单复复现，就是不断的开始暂停再开始，核心源码如下：
String url = "http://115.29.99.117:8080/gnamp_work/1411717214/contents/files/2015-02/000054E1CFD91F00";
FileDownloader.getImpl().create(url)
                .setPath("/mnt/sdcard/test/" + "filedownloader.mp4")
                .setMinIntervalUpdateSpeed(1000)
                .setCallbackProgressTimes(3000)
                .setListener(new FileDownloadListener() {
                    // 最后一次下载的大小
                    long lastSize = 0L;

                    @Override
                    protected void pending(BaseDownloadTask task, int soFarBytes, int totalBytes) {
                        Log.i(TAG, "pending: " + task.getFilename());
                    }

                    @Override
                    protected void progress(BaseDownloadTask task, int soFarBytes, int totalBytes) {
                        Log.i(TAG, "progress: " + task.getFilename() + " soFarBytes:" + soFarBytes + " totalBytes:" + totalBytes);
                    }

                    @Override
                    protected void paused(BaseDownloadTask task, int soFarBytes, int totalBytes) {
                        Log.i(TAG, "paused: " + task.getFilename());
                    }

                    @Override
                    protected void completed(BaseDownloadTask task) {
                        Log.i(TAG, "completed: " + task.getFilename());
                    }

                    @Override
                    protected void error(BaseDownloadTask task, Throwable e) {
                        Log.i(TAG, "error: " + task.getFilename() + " 错误：" + Log.getStackTraceString(e));
                    }

                    @Override
                    protected void warn(BaseDownloadTask task) {
                        Log.i(TAG, "warn: " + task.getFilename());
                    }
                }).start();

// 暂停
FileDownloader.getImpl().pauseAll();

**Comment by liajt** [comment]
切换不超过十次就出现了，日志如下：
06-26 17:38:24.271 13083-13083/com.example.test I/MainActivity: pending: filedownloader.mp4
06-26 17:38:25.011 13083-13083/com.example.test I/MainActivity: progress: filedownloader.mp4 soFarBytes:109245312 totalBytes:827892900
06-26 17:38:25.487 13083-13083/com.example.test I/MainActivity: progress: filedownloader.mp4 soFarBytes:109521920 totalBytes:827892900
06-26 17:38:26.203 13083-13083/com.example.test I/MainActivity: progress: filedownloader.mp4 soFarBytes:109798240 totalBytes:827892900
06-26 17:38:26.971 13083-13083/com.example.test I/MainActivity: progress: filedownloader.mp4 soFarBytes:110075648 totalBytes:827892900
06-26 17:38:27.399 13083-13083/com.example.test I/MainActivity: progress: filedownloader.mp4 soFarBytes:110352256 totalBytes:827892900
06-26 17:38:27.743 13083-13083/com.example.test I/MainActivity: progress: filedownloader.mp4 soFarBytes:110628832 totalBytes:827892900
06-26 17:38:28.031 13083-13083/com.example.test I/MainActivity: progress: filedownloader.mp4 soFarBytes:110906080 totalBytes:827892900
06-26 17:38:28.347 13083-13083/com.example.test I/MainActivity: progress: filedownloader.mp4 soFarBytes:111183360 totalBytes:827892900
06-26 17:38:28.655 13083-13083/com.example.test I/MainActivity: progress: filedownloader.mp4 soFarBytes:111459872 totalBytes:827892900
06-26 17:38:29.163 13083-13083/com.example.test I/MainActivity: progress: filedownloader.mp4 soFarBytes:111736162 totalBytes:827892900
06-26 17:38:29.667 13083-13083/com.example.test I/MainActivity: progress: filedownloader.mp4 soFarBytes:112015200 totalBytes:827892900
06-26 17:38:29.971 13083-13083/com.example.test I/MainActivity: progress: filedownloader.mp4 soFarBytes:112292672 totalBytes:827892900
06-26 17:38:30.271 13083-13083/com.example.test I/MainActivity: progress: filedownloader.mp4 soFarBytes:112571616 totalBytes:827892900
06-26 17:38:30.623 13083-13083/com.example.test I/MainActivity: progress: filedownloader.mp4 soFarBytes:112847680 totalBytes:827892900
06-26 17:38:31.083 13083-13083/com.example.test I/MainActivity: progress: filedownloader.mp4 soFarBytes:113124928 totalBytes:827892900
06-26 17:38:31.431 13083-13083/com.example.test I/MainActivity: progress: filedownloader.mp4 soFarBytes:113402208 totalBytes:827892900
06-26 17:38:32.059 13083-13083/com.example.test I/MainActivity: progress: filedownloader.mp4 soFarBytes:113678752 totalBytes:827892900
06-26 17:38:32.375 13083-13083/com.example.test I/MainActivity: progress: filedownloader.mp4 soFarBytes:113956000 totalBytes:827892900
06-26 17:38:32.691 13083-13083/com.example.test I/MainActivity: progress: filedownloader.mp4 soFarBytes:114233280 totalBytes:827892900
06-26 17:38:32.987 13083-13083/com.example.test I/MainActivity: progress: filedownloader.mp4 soFarBytes:114510560 totalBytes:827892900
06-26 17:38:34.003 13083-13083/com.example.test I/MainActivity: progress: filedownloader.mp4 soFarBytes:114790496 totalBytes:827892900
06-26 17:38:34.287 13083-13083/com.example.test I/MainActivity: progress: filedownloader.mp4 soFarBytes:115066528 totalBytes:827892900
06-26 17:38:34.559 13083-13083/com.example.test I/MainActivity: progress: filedownloader.mp4 soFarBytes:115343808 totalBytes:827892900
06-26 17:38:34.803 13083-13083/com.example.test I/MainActivity: progress: filedownloader.mp4 soFarBytes:115620352 totalBytes:827892900
06-26 17:38:35.099 13083-13083/com.example.test I/MainActivity: progress: filedownloader.mp4 soFarBytes:115896896 totalBytes:827892900
06-26 17:38:35.371 13083-13083/com.example.test I/MainActivity: progress: filedownloader.mp4 soFarBytes:116173440 totalBytes:827892900
06-26 17:38:36.147 13083-13083/com.example.test I/MainActivity: progress: filedownloader.mp4 soFarBytes:116449984 totalBytes:827892900
06-26 17:38:36.567 13083-13083/com.example.test I/MainActivity: paused: filedownloader.mp4
06-26 17:38:38.787 13083-13083/com.example.test I/MainActivity: pending: filedownloader.mp4
06-26 17:38:39.479 13083-13083/com.example.test I/MainActivity: paused: filedownloader.mp4
06-26 17:38:39.603 13083-13083/com.example.test I/MainActivity: pending: filedownloader.mp4
06-26 17:38:40.027 13083-13083/com.example.test I/MainActivity: paused: filedownloader.mp4
06-26 17:38:41.047 13083-13083/com.example.test I/MainActivity: pending: filedownloader.mp4
06-26 17:38:41.307 13083-13083/com.example.test I/MainActivity: warn: filedownloader.mp4
06-26 17:38:41.451 13083-13083/com.example.test I/MainActivity: warn: filedownloader.mp4
06-26 17:38:42.027 13083-13083/com.example.test I/MainActivity: paused: filedownloader.mp4
06-26 17:38:42.719 13083-13083/com.example.test I/MainActivity: pending: filedownloader.mp4
06-26 17:38:42.999 13083-13083/com.example.test I/MainActivity: paused: filedownloader.mp4
06-26 17:38:43.303 13083-13083/com.example.test I/MainActivity: pending: filedownloader.mp4
06-26 17:38:43.551 13083-13083/com.example.test I/MainActivity: paused: filedownloader.mp4
06-26 17:38:43.815 13083-13083/com.example.test I/MainActivity: pending: filedownloader.mp4
06-26 17:38:44.087 13083-13083/com.example.test I/MainActivity: paused: filedownloader.mp4
06-26 17:38:44.347 13083-13083/com.example.test I/MainActivity: pending: filedownloader.mp4
06-26 17:38:44.607 13083-13083/com.example.test I/MainActivity: paused: filedownloader.mp4
06-26 17:38:45.295 13083-13083/com.example.test I/MainActivity: pending: filedownloader.mp4
06-26 17:38:45.643 13083-13083/com.example.test I/MainActivity: paused: filedownloader.mp4
06-26 17:38:45.927 13083-13083/com.example.test I/MainActivity: pending: filedownloader.mp4
06-26 17:38:46.267 13083-13083/com.example.test I/MainActivity: paused: filedownloader.mp4
06-26 17:38:46.555 13083-13083/com.example.test I/MainActivity: pending: filedownloader.mp4
06-26 17:38:46.855 13083-13083/com.example.test I/MainActivity: paused: filedownloader.mp4
06-26 17:38:47.139 13083-13083/com.example.test I/MainActivity: pending: filedownloader.mp4
06-26 17:38:47.443 13083-13083/com.example.test I/MainActivity: paused: filedownloader.mp4
06-26 17:38:47.771 13083-13083/com.example.test I/MainActivity: pending: filedownloader.mp4
06-26 17:38:48.051 13083-13085/com.example.test D/dalvikvm: GC_CONCURRENT freed 280K, 5% free 8904K/9284K, paused 3ms+0ms, total 27ms
06-26 17:38:48.055 13083-13083/com.example.test I/MainActivity: paused: filedownloader.mp4
06-26 17:38:48.355 13083-13083/com.example.test I/MainActivity: pending: filedownloader.mp4

**Comment by Jacksgong** [comment]
多谢反馈，已经找到原因。

对相同的任务很快的进行频繁的暂停与启动确实可能导致这个问题。

#### 原因

1. 在下载服务中，该任务的宿主线程还没有来得及创建分支线程（可能正在进行检测连接有效性），此时被暂停了，导致宿主线程被暂停，而分支线程才被创建好运行，导致接下来的所有分支线程的进度都被宿主线程拒绝回调，并且下一次再启动由于相同任务的宿主线程还存在（由于分支线程还没有被结束），因此也无法启动再次启动该相同任务。
2. 在下载服务中，该任务的部分分支线程被创立，但是正在建立连接，此时被暂停了，导致随后的fetch任务依然被打开，导致分支线程得不到中断，随后的情况与情况1的后面的情况相同（导致接下来的所有分支线程的进度都被宿主线程拒绝回调，并且下一次再启动由于相同任务的宿主线程还存在（由于分支线程还没有被结束），因此也无法启动再次启动该相同任务。）

#### 该问题会在1.5.8中修复。

**Comment by liajt** [comment]
谢谢回复，非常感谢
