### ISSUE TITLE
一个有关于重复下载的问题，期待您的回复

### ISSUE THREAD

**Issue by Kimxu** [lingochamp/FileDownloader#626]
你好，我遇见一个bug想请教您一下。使用的版本是1.5.6，具体情况是：
  开始->暂停->开始->暂停->开始 （这一步会直接回调下载完成方法，其实文件并没有下载完成）。
**查看原因是在下载文件夹里面生成了一个0kb的下载文件（.temp也存在）**。追踪源码未发现在哪里有创建文件的方法。不知道是否是一个bug，（我现在的解决办法是每次开始下载之前都去查看是否下载目录里面有0Kb的下载文件，如果有就删除掉， 这很不优雅）可否有解决办法，期待您的回复

**Comment by Jacksgong** [comment]
这个测试流我在demo project中测了非常非常多次，无法复现你的问题。

为了进一步定位问题:

1. 留意下Logcat看看有无Warn或者是Error级别的日志输出
2. 可否在demo project中进行复现呢？可以相对高概率的复现以后将分支发给我，我进一步定位下问题。

**Comment by Kimxu** [comment]
好的，我也使用demo，但是没有复现该问题，也许是我代码逻辑出现了问题，才导致的该问题发生，如果后续发现该问题，第一时间告诉你，感谢

**Comment by Jacksgong** [comment]
@Kimxu 好的，后面如果有新的进展这个Issue将被重新打开，也欢迎PR~..
