### ISSUE TITLE
长时间运行崩溃

### ISSUE THREAD

**Issue by shi1hh** [lingochamp/FileDownloader#627]
具体不知道怎么DEBUG..
长时间运行后，查看后台服务，服务还在，但是下载没有任何回调，估计是崩溃了。
这种情况应该怎么做？

**Comment by Jacksgong** [comment]
crash应该会有crash日志的，关注下logcat

**Comment by shi1hh** [comment]
谢谢。。我估计是连接太长时间了。。

**Comment by Jacksgong** [comment]
@shi1hh 是收到SocketTimeout的`error`回调吗？
