### ISSUE TITLE
Nexus7 with low download speed

### ISSUE THREAD

**Issue by luojin** [lingochamp/FileDownloader#63]
Nexus7 
Android 4.4.4
with low download speed
Is anybody face the same problem?

**Comment by luojin** [comment]
Connecting to the same wifi and download the same file.
Nexus 7 downloads in low speed.
I am so confused.
why other devices can download file in high speed?

**Comment by luojin** [comment]
@Jacksgong help please.

**Comment by Jacksgong** [comment]
I am confused too... FileDownloader just uses OkHttp for Http request, and We didn't do anything special for Nexus 7.

**Comment by luojin** [comment]
Hi @Jacksgong ,
我试过了，如果把每次update数据库那一句注释，下载速度会成一个量级的提升，所以还是频繁写数据库的问题，需要优化

**Comment by luojin** [comment]
```
package com.liulishuo.filedownloader.services;
class FileDownloadRunnable

private void onProcess(final long soFar, final long total) {
        if (soFar != total) {
            downloadTransfer.setSoFarBytes(soFar);
            downloadTransfer.setTotalBytes(total);
            downloadTransfer.setStatus(FileDownloadStatus.progress);

            helper.update(downloadTransfer.getDownloadId(), FileDownloadStatus.progress, soFar, total);
        }

        if (maxNotifyBytes < 0 || soFar - lastNotifiedSoFar < maxNotifyBytes) {
            return;
        }

        lastNotifiedSoFar = soFar;
        if (FileDownloadLog.NEED_LOG) {
            FileDownloadLog.d(this, "On progress %d %d %d", downloadTransfer.getDownloadId(), soFar, total);
        }


        FileDownloadProcessEventPool.getImpl().asyncPublishInNewThread(event.setTransfer(downloadTransfer));

    }
```

以上是每一次更新进度都会update数据库的代码， 
```
helper.update(downloadTransfer.getDownloadId(), FileDownloadStatus.progress, soFar, total);
```
这个调用，不知是否可以移到
```
lastNotifiedSoFar = soFar;
```
这一句之前？
这样做会对其他功能造成影响吗？是否会影响断点续传？
盼望回复，谢谢。

**Comment by luojin** [comment]
包括HTC的机子，都有同样的问题，不妨测试一下。

**Comment by csenbalci** [comment]
I also faced same problem. Nexus7 android: 5.1.1
On same network other devices downloads files faster than nexus7
Why? 

@Jacksgong

**Comment by csenbalci** [comment]
Ok. I found the problem. This is just specific for nexus7 because of very low sequential writing on storage.. This is related with device writing capability. When I reset my nexus device, download speed increases as I expected.

@luojin @Jacksgong

**Comment by Jacksgong** [comment]
@csenbalci 💯 Good job.

**Comment by Jacksgong** [comment]
@csenbalci In addition, you also can speed up the downloading through configuring params in `filedownloader.properties` : `process.non-separate`、`download.min-progress-step`、`download.min-progress-time`、`download.max-network-thread-count`: https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties

**Comment by luojin** [comment]
Hi @csenbalci, What's the meaning of resetting you nexus device? How to reset?

**Comment by luojin** [comment]
@csenbalci By the way, when your codes running on users' devices, how can you prompt user to reset? Resetting device could not solve the problem, I think.
