### ISSUE TITLE
网络状态切换时会自动去切换下载网络吗？

### ISSUE THREAD

**Issue by Godsbox** [lingochamp/FileDownloader#632]
1. 当前4g下载 连上wifi后 会自动切换为 wifi吗

**Comment by Jacksgong** [comment]
网络通道是系统控制的，系统切换了网络通道以后，FileDownloader默认使用的`UrlConnection`也会随着切换。

#### 不过

一般的网络通道切换，无论是4g到wifi，还是wifi到4g，还是到飞行模式，都不是平滑的：**所以，一般4g到wifi，是4g到无网络再到wifi**，因此切换网络会伴随着`java.net.SocketException: Software caused connection abort`的错误中断下载。

**Comment by Godsbox** [comment]
从4G到wifi 是会自动抛出异常  然后自动继续下载吗？

**Comment by Jacksgong** [comment]
@Godsbox 

#### 从4G到wifi 是会自动抛出异常 然后自动继续下载吗？

不会的，只会抛出异常

#### 原因

因为对于内部而言并不清楚是切换网络或者是将网络关闭

#### 推荐做法

当收到网路关闭，而后短时间内有网络的情况，可以提示用户是否继续下载，然后重新创建(或reuse)任务，进行重新下载，内部会自动进行断点续传从上次的断点开始下载。

**Comment by Godsbox** [comment]
......我这里竟然重新开始下载了

**Comment by Godsbox** [comment]
哦  我知道了。。。。我是添加了多个任务   这个抛出异常 结束后  内部自动继续下一个下载是吧。。。
我把这些跑出异常的任务 再重新添加到队列  是不是就可以了 
这个时候 我是重新创建？

**Comment by Jacksgong** [comment]
对的，重新创建任务（或者调用`BaseDownloadTask#reuse`)，只要该任务与之前的任务生成的id相同(`idGenerator`，默认与url与存储路径相关)，就会自动关联上，自动断点续传。

**Comment by Godsbox** [comment]
这个reuse是马上执行吗  我的意思是  我有任务 在队列中  我监听到了error 然后我马上把这个error任务reuse这个时候是重新执行我这个任务吗？还是有可能会 先执行下一个任务

**Comment by Jacksgong** [comment]
`reuse`只是复用该任务的各类参数而已，并没有开始，如果要开始，还需要调用`start`开始。可以参考下接口上的注解:

```java
/**
 * Reuse this task withhold request params: path、url、header、isForceReDownloader、etc.
 * <p>
 * <strong>Note:</strong>If the task has been over({@link FileDownloadStatus#isOver(int)}), but
 * the over-message has not been handover to the listener, since the callback is asynchronous,
 * once your invoke this 'reuse' method, that message would be discard, for free the messenger.
 *
 * @return {@code true} if reuse this task successfully. {@code false} otherwise.
 */
boolean reuse();
```

**Comment by Godsbox** [comment]
我是用的是多任务下载，这多个任务组成一个完整的大下载任务。
当一个任务出错后，多任务下载会自动下载下一个任务。。。
我4g切换wifi的时候，需要平滑过渡（不显示出错状态，直接继续下载）。。。
貌似能做到吗？试了好多办法。。。
