### ISSUE TITLE
为什么下载的时候从pending 到 progress 中间要很长时间

### ISSUE THREAD

**Issue by xjl147** [lingochamp/FileDownloader#633]
单任务下载的时候，开始一个新的下载任务，执行start() 后要很长时间才会开始下载。

**Comment by Jacksgong** [comment]
参考下这里: https://github.com/lingochamp/FileDownloader/issues/597#issuecomment-306823904

**Comment by Jacksgong** [comment]
还有一点需要注意的是，如果是分块下载，从`connected`到`progress`的过程:

1. 首次建连结束后会回调`connected`
2. 但是由于是分块下载，因此每个块会单独建立新的连接，这块也会耗时。
3. 根据网络状况，当任意块有数据反馈时，并满足[进度回调设定时](https://github.com/lingochamp/FileDownloader/wiki/processing-callback-frequency)，此时会回调`progress`

---

P.S. 如果不希望分块下载（直接一个连接开始获取数据），[可以通过`IdGenerator`](https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component)返回连接数为1即可。

**Comment by tommyfeng** [comment]
@Jacksgong 您好，我也碰到了这个问题，从回调pending 到 回调progress，中间大概间隔了10秒钟。这个时间感觉太久了啊！能有什么办法可以缩短间隔时间吗？ 谢谢！

**Comment by Jacksgong** [comment]
@tommyfeng 如果是由于FileDownloader本身原因是可以的:

1. 在[filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)中配置`process.non-separate=true`，让下载服务运行在主进程保证首次请求下载时无需创建一个新的进程。 
2. [可以通过`ConnectionCountAdapter `](https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component)返回连接数为1，这样就在`connected`之后立马复用该连接进行下载，无需再重新建立新的连接给每个分块用。(估计是这一个原因导致你感觉`pending`到第一个`progress`慢的)

---

#### 详细

> 由于从`pending`到`progress`中间其实还有`started`与`connected`的回调。

1. 如果你的耗时点是在`started`到`connected`，这个我们是无能为力的，因为这个是网络环境以及所下载资源的服务器网络环境导致的；
2. 如果你的耗时点实在`connected`到第一个`progress`，这个是由于分块下载，需要为每个块重新建立独立的连接，这里你通过`ConnectionCountAdapter`返回1，这样就不会启用分块下载，就会复用`connected`这个连接的连接；但是如果原本就不是分块下载，这个依然很久，那应该网络环境导致首次取buffer速度很慢导致。

**Comment by tommyfeng** [comment]
@Jacksgong 谢谢你的回复！ 这是我的Log信息。版本是1.3.0
![qq 20170629181326](https://user-images.githubusercontent.com/20334082/27682909-dfaa3fe0-5cf6-11e7-8947-784f7b67d2bb.png)
但是升级到1.5.8时，打印信息是这样的
![qq 20170629180552](https://user-images.githubusercontent.com/20334082/27682979-1402ae76-5cf7-11e7-8a0a-0a6a426ccbe7.png)
我不清楚这个是否是Filedownloader本身的原因。

**Comment by Jacksgong** [comment]
@tommyfeng 1.5.0之后支持了分块下载，也就是上面提到的第二点原因。

**Comment by tommyfeng** [comment]
@Jacksgong 谢谢回复！，通过ConnectionCountAdapter返回1 这个是要如何操作。我没看懂。。。

**Comment by Jacksgong** [comment]
@tommyfeng 参考下这里: https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component 。

如果还不明白，具体是这样:


#### 1. 实现你自己的`ConnectionCountAdapter`:

```java
public class MyConnectionCountAdapter implements FileDownloadHelper.ConnectionCountAdapter {

    @Override
    public int determineConnectionCount(int downloadId, String url, String path, long totalLength) {
        return 1;
    }
}
```

#### 2. 在`Application#onCreate`中调用`FileDownloader.setupOnApplicationOnCreate`注册进去:

```
FileDownloader.setupOnApplicationOnCreate(this)
        .connectionCountAdapter(new MyConnectionCountAdapter())
        .commit();
```

**Comment by tommyfeng** [comment]
是像这样的吗？ 
![qq 20170629190025](https://user-images.githubusercontent.com/20334082/27684639-6569ac46-5cfd-11e7-9343-7946cf89fe9b.png)

**Comment by Jacksgong** [comment]
参考我上面给你的评论: https://github.com/lingochamp/FileDownloader/issues/633#issuecomment-311933698

---

P.S. 你这样也可以，不过`init`已经被弃用的，建议还是使用`FileDownloader.setupOnApplicationOnCreate`

**Comment by tommyfeng** [comment]
嗯嗯，刚刚我试过了，好像还是会间隔十秒 
![qq 20170629190637](https://user-images.githubusercontent.com/20334082/27684846-3b7e115a-5cfe-11e7-822c-38a283b2e6a0.png)

**Comment by Jacksgong** [comment]
![image](https://user-images.githubusercontent.com/6176417/27684897-7f815cae-5cfe-11e7-957e-b5e51954b1a8.png)
诶，不对啊，你这个说的不是标题的问题，不是pending到progress的耗时，你第一个progress回调，间隔是2s。。。。。。。。。。。。

**Comment by tommyfeng** [comment]
刚刚1.3.0是这个问题，后面升级到1.5.8就是第一个progress回调和第二个相差时间很长。。。

**Comment by Jacksgong** [comment]
ok，那么首先你不用修改分块下载这块了。

---

对与这个问题。咱们重新提一个Issue讨论: #635

**Comment by tommyfeng** [comment]
就是说第一个progress的回调和第二个progress的回调之间貌似会相隔大概7秒的时间。给人感觉像是卡住了一样，但是实际上，网速是没有问题的。不知道这个问题出在哪里！

**Comment by EngrZhou** [comment]
@tommyfeng 如果用的是OKHTTP的话，看看是不是开启了OKHTTP的日志。并且级别是BODY的。

**Comment by BinarySatan** [comment]
下载一会后，直接不回调progress, 如果暂停 在 重新开始的话， 状态会一直卡在 pending. 不走任何别的回调...
