### ISSUE TITLE
sofarBytes>totalBytes的问题．

### ISSUE THREAD

**Issue by gejiashu** [lingochamp/FileDownloader#636]
我这里经常出现sofarBytes>totalBytes的情况，看了之前提的一个问题．上面说的是content-length返回的有问题，但是我发现下载下来的文件大小实际上是和content-length的大小一样的　并不是最后的sofarBytes的大小，请问是框架的问题吗？

**Comment by Jacksgong** [comment]
FileDownloader中下载结束后会检测`sofarBytes`如果不等于`totalBytes`会直接下载失败的( `DownloadStatusCallback#interceptBeforeCompleted`)。我在demo project中各种测试并没有遇到类似的问题，你是怎么遇到这个问题的呢？

- 是某些Url遇到吗？
- 是肯定要经过断点续传才会遇到吗？
- 如何复现，可否告知下过程，最好是能够有提供下可复现的demo，或者在demo project中复现，然后推到远端。

**Comment by gejiashu** [comment]
我写了一个demo放到了百度云，地址是这个https://pan.baidu.com/s/1qX9yEBU
这个demo是通过一个第三方的网站解析youtube的真实下载地址然后下载视频对应的音频文件的一个demo，通过调用第三方网站的接口他会返回下载的地址，我测试了其他的网站返回的下载地址好像没有问题，但是这个网站返回的下载地址　使用下载库下载时候会出现sofarBytes>totalBytes的情况，但是下载完成之后实际大小又不是sofarBytes的最后的大小．
这个demo里面最后打印的日志是这个．
07-03 10:29:37.778 32195-32195/com.example.gejiashu.demo I/System.out: soFarBytes:5995670 totalBytes:4004172
我看了一下最后的文件大小是3.8M左右和totalBytes的大小是一致的
麻烦你下载一下demo看一下是什么原因导致的.
PS(请求的接口是国外的网站，可能需要连接vpn才能访问到，你也可以更换其他的youtube视频地址测试)

**Comment by gejiashu** [comment]
怀疑是框架的bug,
07-03 11:42:28.368 11540-11666/com.example.gejiashu.demo:filedownloader I/System.out: byteCount:-1 currentOffset:4004172
07-03 11:42:28.378 10664-10664/com.example.gejiashu.demo I/System.out: soFarBytes:6003862 totalBytes:4004172
我在FetchDataTask这个类的
do {
                int byteCount = inputStream.read(buff);
                System.out.println("byteCount:"+byteCount+" currentOffset:"+currentOffset);
                if (byteCount == -1) {
                    break;
                }
这里添加了一行日志，下载完成之后currentOffset的值是正确的刚好和totalSize一致，怀疑是进度回调的时候计算的有问题．

**Comment by gejiashu** [comment]
我这里已经确定问题的原因了，是下载同一个文件的时候开启了２个线程去下载的同一个文件，soFarBytes计算的有问题，但是还没搞清楚为什么有的下载链接没有问题，我自定义了connectionCount改成了一个线程就没有这个问题了，期待您修复这个问题．

**Comment by Jacksgong** [comment]
好的，我看下。

**Comment by Jacksgong** [comment]
#### 真正原因

对于所下载的连接地址: `https://www.saveitoffline.com/get/?i=0x3gdGuSV7zbjjpuvKc3nE0auFhnqE7i`

后台未正确处理`Range`请求头参数，验证发现，在请求头中如果开始是`0`时（参看下图的请求头`Range`值)，无论给的结束是多少都会返回整个数据(参看下图的响应头的`Content-Length`值，这里我们期望的是Range所指向的`2002086`大小，但是却返回了整个文件大小)。

![image](https://user-images.githubusercontent.com/6176417/27920449-2ff00786-62a7-11e7-8a47-b512b4f21b01.png)

但是该后台处理，当`Range`开始值不是`0`时（参看下图请求头`Range`值，从`2002086`到最后)，后台返回的大小是正确的大小(参看下图响应头的`Content-Length`值是正确的，因为该文件总大小是`4004172`，因此从`2002086`到最后，确实长度是`2002086`是正确的)。

![image](https://user-images.githubusercontent.com/6176417/27920698-0e683b00-62a8-11e7-9592-4bc88da35e2f.png)

#### 目前FileDownloader对该不符合http协议规范的请求处理方案

在下载结束后会监测到大小异常，回调`error`。这个其实是符合预期的。

#### 推荐解决方案

让后台同学检查下服务端代码，当`Range`开始值为`0`时，需要处理结束值，给回符合http规范的正确的内容长度的数据。

#### 临时处理方案

确实是改用单线程下载可以解决，因为单线程下载要不是从0开始到最后，要不是断点续传从某个节点到最后。

---


#### 而对于FileDownloader本身而言，要不要处理呢？

对于这种不符合http规范的，这里其实做的不够:

1. 错误返回不够及时，其实在开始下载的时候就已经可以检测到错误，可以在这里就直接返回`error`
2. 错误信息不够明朗，虽然在最终结束后有说明`sofarBytes != totalBytes`，但对于用户而言这个错误信息不够明朗。

针对上面的两个问题，FileDowloader在1.6.1版本中会作出优化。

**Comment by gejiashu** [comment]
明白了，谢谢您的回复，不过后台是国外第三方网站的，看来目前只能用单线程下载了
