### ISSUE TITLE
在APP进程杀死后再次进入使用FileDownloader.getImpl().getSoFar(downloadId)获取时0

### ISSUE THREAD

**Issue by shiyd0516** [lingochamp/FileDownloader#637]
/**
     * 获取已经下载的文件大小
     * @param downloadId
     * @return
     */
    public long getSoFarBytes(int downloadId){
        return FileDownloader.getImpl().getSoFar(downloadId);
    }
获取结果是0

**Comment by Jacksgong** [comment]
参考这里: https://github.com/lingochamp/FileDownloader/issues/579#issuecomment-303930347
