### ISSUE TITLE
question

### ISSUE THREAD

**Issue by typ0520** [lingochamp/FileDownloader#638]
作者你好请教一个问题，下载一个资源的时候中断了，下次再次下载这个资源会从断点开始下，如果这个资源在中断后被替换掉了(url没有变)那么下载下来的资源就会有问题，这种场景有处理吗？

**Comment by Jacksgong** [comment]
如果资源被替换，那么etag会改变，返回的code就会是412(precondition failed)，FileDownloader就会自动的从头开始下载。
