### ISSUE TITLE
totalBytes parameter in progress always gives -1.

### ISSUE THREAD

**Issue by awazgyawali** [lingochamp/FileDownloader#64]
@Override
                        protected void progress(BaseDownloadTask task, int soFarBytes, int totalBytes) {
                            Log.d("debug",soFarBytes +" "+totalBytes);
                            final int percentage = (int) (((float) soFarBytes / (float) totalBytes) * 100f);
                            dialog.setProgress(percentage);
                        }

This always gives  download byte and -1 as total byte

**Comment by Jacksgong** [comment]
It must be the stream media. 

We get the totalBytes in the Http response header: `content-length`. When we can't find the `content-length` in the Http response header, and get the `Transfer-Encoding` in there with `chunked`, the totalBytes will be -1. [REF](https://github.com/lingochamp/FileDownloader/blob/18dc9a1abdc691b406202a96f186771dad5e4eb8/library/src/main/java/com/liulishuo/filedownloader/services/FileDownloadRunnable.java#L222)

**Comment by awazgyawali** [comment]
I am downloading pdf from this link :-  http://www.csitnepal.com/elibrary/notes/pdf/cnotes.pdf 

Which is on my server. So would be my solution?

**Comment by Jacksgong** [comment]
@awazgyawali Already ok? I check the link(http://www.csitnepal.com/elibrary/notes/pdf/cnotes.pdf) has already had `content-length` in the Http response header.

**Comment by awazgyawali** [comment]
I am still in this problem. Can you please figure out my mistake??

Would you please see this code : 
https://github.com/Brainants/BSc-CSIT/blob/master/app/src/main/java/com/brainants/bsccsit/fragments/eLibraryPagerFragment.java#L148 to

**Comment by Jacksgong** [comment]
This line: https://github.com/Brainants/BSc-CSIT/blob/master/app/src/main/java/com/brainants/bsccsit/fragments/eLibraryPagerFragment.java#L179

> dialog.setProgress(soFarBytes / totalBytes * 100);


`soFarBytes / totalBytes * 100`  would be `0`. 

please change to : `dialog.setProgress((int)((float)soFarBytes / totalBytes * 100));` or recommend: `dialog.setMax(totalBytes); dialog.setProcess(soFarBytes);`
