### ISSUE TITLE
很无语,说句实话,demo无法编译

### ISSUE THREAD

**Issue by actor20170211030627** [lingochamp/FileDownloader#640]
代码没有注释,看起来像坨什么一样,我只是想并行下载文件而已,说明一大堆,毛焦火辣的,我反正很难看懂,提供了一大堆方法,真的很无语,

**Comment by Jacksgong** [comment]
十分感谢review代码，FileDownloader确实有一定的复杂度，不过也快速迭代了48个版本，目前jcenter中月拉去量在5000+，请放心使用。一直以来所有对外可见，外界需要了解的接口都已经全部覆盖了注解，内部想对复杂的逻辑部分都尽可能的进行了注解覆盖。也十分欢迎PR。

---

### Demo无法编译?

我觉得这个问题，很可能是你遇到了下面的这个问题:

![image](https://user-images.githubusercontent.com/6176417/27768008-cfb13a3a-5f3a-11e7-93a6-0afc8b9204cd.png)

**关于这个问题，是由于我已经在使用Android Studio 3.0，根据官方默认inspection，我采用了最新版本的gradle plugin导致的。**

#### 解决方案

考虑到这块确实还有很多开发者没有开始使用Android Studio 3.0，我会降低gralde plugin的版本，以便于你们可以编译的过demo，感谢提醒。

---

### 如何并行下载?

#### 1. 在下载之前初始化

> 对应[wiki](https://github.com/lingochamp/FileDownloader/wiki/Initialization)


```java
// 在开始使用FileDownloader之前调用setup方法，传入Context（该方法只需要调用一次)
FileDownloader.setup(this)
```

#### 2. 开始并行下载

> 对应[wiki](https://github.com/lingochamp/FileDownloader/wiki/Start-downloading)

```java
ifinal FileDownloadListener queueTarget = new FileDownloadListener() {
    ...
};

for (String url : URLS) {
    FileDownloader.getImpl().create(url)
            .setCallbackProgressIgnored() // 如果你不需要每个任务单独的进度回调，调用这个方法可以提升下载速度
            .setListener(queueTarget)
            .asInQueueTask();
            .enqueue();
}

FileDownloader.getImpl().start(queueTarget, false);
```

---

虽然FileDownloader目前已经有很多功能，我们依旧秉持希望大家可以很轻易的使用起来。也十分欢迎提出实质性的建议与具体的看法，希望一起探讨与迭代将FileDownloader做的更好。

**Comment by actor20170211030627** [comment]
不好意思,是我自己的问题

**Comment by Jacksgong** [comment]
@actor20170211030627 嗯，现在你拉master最新的代码在Android Studio 2.x中应该可以编译的过了。

**Comment by actor20170211030627** [comment]
对不起,我脾气暴躁了,从今早开始弄大神的demo,我的错,我向你道歉

**Comment by Jacksgong** [comment]
@actor20170211030627 嗯，有问题多留意wiki与Issue中搜索，也十分欢迎提Issue与PR。
