### ISSUE TITLE
安装apk失败问题

### ISSUE THREAD

**Issue by Lollipope** [lingochamp/FileDownloader#641]
测试手机:小米5s
studio版本: Android studio 2.3

报错信息:
Installation failed with message INSTALL_FAILED_DUPLICATE_PERMISSION perm=filedownloader.permission.RECEIVE_STATE pkg=com.liulishuo.filedownloader.demo.
It is possible that this issue is resolved by uninstalling an existing version of the apk if it is present, and then re-installing.

===========
Failure [INSTALL_FAILED_DUPLICATE_PERMISSION perm=filedownloader.permission.RECEIVE_STATE pkg=com.liulishuo.filedownloader.demo]

**Comment by Jacksgong** [comment]
多谢提醒。该问题是在Android 5.0或更高版本的手机上会遇到。

这个问题今晚会发新版本修复。是1.5.7引入的。
