### ISSUE TITLE
FileDownloadQueueSet下载没有任何反应，没有回调，也没有创建文件

### ISSUE THREAD

**Issue by liajt** [lingochamp/FileDownloader#642]
源码：
private void filedownloader() {
        final FileDownloadQueueSet queueSet = new FileDownloadQueueSet(downloadListener);
        final List<BaseDownloadTask> tasks = new ArrayList<>();
        tasks.add(FileDownloader.getImpl().create(url).setPath(DIR + "filedownloader.mp4"));
        queueSet.setCallbackProgressTimes(10000);
        queueSet.setCallbackProgressMinInterval(1000);
        // 串行执行该任务队列
        queueSet.downloadSequentially(tasks);

//        FileDownloader.getImpl().create(url)
//                .setPath(DIR + "filedownloader.mp4")
//                .setListener(downloadListener).start();
    }

**Comment by Jacksgong** [comment]
查看logcat的警告或错误日志。

**Comment by liajt** [comment]
调用方法时候没有任何反应，也没有任何的警告和错误日志。

**Comment by Jacksgong** [comment]
我看了下，因为没有调用`queueSet.start()`，没有启动。

**Comment by liajt** [comment]
好的，非常感谢，我试试

**Comment by Jacksgong** [comment]
嗯。欢迎PR~

**Comment by xiaoc024** [comment]
作者你好，示例代码中没有调用start，建议修改一下。

**Comment by Jacksgong** [comment]
@xiaoc024 多谢提醒，我改下。
