### ISSUE TITLE
Debug与Release逻辑不一样吗

### ISSUE THREAD

**Issue by ddrandy** [lingochamp/FileDownloader#643]
如题
我在debug模式下下载
:filedownloader进程oom
看dump信息okio的数据两百多mb
在release下就没有这种情况，可以正常下载

**Comment by Jacksgong** [comment]
FileDownloader本身没有以来okio，你用的是什么版本？

**Comment by ddrandy** [comment]
用的1.5.8配合自定义okhttpclient

**Comment by ddrandy** [comment]
因为是放到Observable里面
怀疑是没有背压导致
`
    @Override
    public Observable<Integer> startDownload(DownloadInfo info) {
        return Observable.fromCallable(() ->
                FileDownloader.getImpl()
                        .create(info.getAppUrl())
                        .setListener(DownloadListenerWrapper.getListener(info))
                        .start());
    }
`
很奇怪为什么release版没有这个问题

**Comment by ddrandy** [comment]
问题解决了
是因为我在OkHttpClient中引入了HttpLoggingInterceptor
而在debug模式日志输出模式为body
现将下载的logginginterceptor 移除就可以正常下载了

**Comment by Jacksgong** [comment]
okay~

**Comment by EngrZhou** [comment]
@ddrandy 谢谢提醒。
