### ISSUE TITLE
#868540 android.database.sqlite.SQLiteFullException

### ISSUE THREAD

**Issue by wanghaihui** [lingochamp/FileDownloader#644]
java.lang.RuntimeException:Unable to create service com.liulishuo.filedownloader.services.FileDownloadService$SeparateProcessService: android.database.sqlite.SQLiteException: Failed to change locale for db '/data/data/com.wodidashi.paint/databases/filedownloader.db' to 'zh_CN'.
2 android.app.ActivityThread.handleCreateService(ActivityThread.java:2739)
3 ......
4 Caused by:
5 android.database.sqlite.SQLiteFullException:database or disk is full (code 13)
6 android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
7 android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:559)
8 android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:371)
9 android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:218)
10 android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
11 android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
12 android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
13 android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
14 android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:829)
15 android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:814)
16 android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:709)
17 android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1029)
18 android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:256)
19 android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:224)
20 android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
21 com.liulishuo.filedownloader.services.DefaultDatabaseImpl.<init>(DefaultDatabaseImpl.java:52)
22 com.liulishuo.filedownloader.services.DownloadMgrInitialParams.i(DownloadMgrInitialParams.java:162)
23 com.liulishuo.filedownloader.services.DownloadMgrInitialParams.b(DownloadMgrInitialParams.java:67)
24 com.liulishuo.filedownloader.download.CustomComponentHolder.c(CustomComponentHolder.java:89)
25 com.liulishuo.filedownloader.services.FileDownloadManager.<init>(FileDownloadManager.java:52)
26 com.liulishuo.filedownloader.services.FileDownloadService.onCreate(FileDownloadService.java:54)
27 android.app.ActivityThread.handleCreateService(ActivityThread.java:2729)
28 android.app.ActivityThread.access$1800(ActivityThread.java:153)
29 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1410)
30 android.os.Handler.dispatchMessage(Handler.java:110)
31 android.os.Looper.loop(Looper.java:193)
32 android.app.ActivityThread.main(ActivityThread.java:5309)
33 java.lang.reflect.Method.invokeNative(Native Method)
34 java.lang.reflect.Method.invoke(Method.java:515)
35 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:831)
36 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:647)
37 dalvik.system.NativeStart.main(Native Method)

**Comment by wanghaihui** [comment]
后台报了这个崩溃

**Comment by Jacksgong** [comment]
#### SQLiteFullException

这个问题参看下这里: https://github.com/lingochamp/FileDownloader/issues/206

#### filedownloader.db' to 'zh_CN'

类似的数据库长尾问题参看下这里: https://github.com/lingochamp/FileDownloader/issues/583#issuecomment-310427579

**Comment by EngrZhou** [comment]
@Jacksgong 磁盘满触发这个异常的情况下，上层并不容易捕获到并进行处理。是否可以考虑出现异常之后，进行捕获通过目前的AIDL通道交由上层自行处理，而不是直接Crash？当然上层可以通过其他手段规避这个问题。
