### ISSUE TITLE
自定义id生成器后 广播接收到的id 与下载时id不一致

### ISSUE THREAD

**Issue by ddrandy** [lingochamp/FileDownloader#645]
如题
现有需求要在下载完成后从数据库找到下载的任务 
发现此时FileDownloadModel::getId 与下载时的任务id不同
现在解决方法是自定义的id生成器根据url重新生成

**Comment by Jacksgong** [comment]
可否提供进一步信息:

1. 这里的广播接收是说下载完成的`broadcast.completed`那个广播接收吗？
2. 使用自定义id生成器以后才出现的话，该自定义id生成器里面是否存在缓存任何数据的情况呢？因为下载服务默认在另外的进程，如果缓存数据的话，两个进程是使用不同的对象的。

**Comment by ddrandy** [comment]
1.是下载完成时发的广播 `broadcast.completed`
2.没有缓存数据
目前发现是因为我在对文件存储路径时做了修改 
而下载时没有调用setPath
所以问题解决了 下载时加上setPath就好了

**Comment by ddrandy** [comment]
多有叨扰，还望谅解

**Comment by Jacksgong** [comment]
okay.
