### ISSUE TITLE
单文件下载，直接回调completed方法，然而并没有下载

### ISSUE THREAD

**Issue by tribbianiwang** [lingochamp/FileDownloader#648]

**Comment by Jacksgong** [comment]
你看下是否存储路径的文件存在。目前FileDownloader为了足够轻量，是根据存储路径的文件是否存在来判定是否已经下载完成的。

**Comment by tribbianiwang** [comment]
我是这样解决的:保存在本地的地址用的demo里的方法FileDownloadUtils.getDefaultSaveRootPath() + File.separator + "xx" + File.separator + “xx”+ ".mp3";
