### ISSUE TITLE
没有下载文件，但是触发了completed这个函数。

### ISSUE THREAD

**Issue by supermanwu** [lingochamp/FileDownloader#649]
这是系统输出的信息：
Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1550 android.content.ContextWrapper.bindService:517 com.liulishuo.filedownloader.services.BaseFileServiceUIGuard.bindStartByContext:156 com.liulishuo.filedownloader.services.BaseFileServiceUIGuard.bindStartByContext:126 com.liulishuo.filedownloader.FileDownloadServiceProxy.bindStartByContext:112 
而且发现，在SDCARD中并没有下载的文件，但是触发了completed这个函数。

**Comment by Jacksgong** [comment]
这个应该是两个问题:

#### 问题一: `Calling a method in the system process without a qualified user: `

这个挺奇怪的，根据源码，这个是因为调用`bindService`方法是使用了系统用户(UID)来调用，但是FileDownloader调用是你的应用UID才对:

![image](https://user-images.githubusercontent.com/6176417/28011210-1dfa0d7a-6594-11e7-98a4-ebe371182045.png)

**但是**这个不会有任何影响，根据源码，这个只是输出了一个警告的日志。

#### 在SDCARD中并没有下载的文件，但是触发了completed这个函数

这个也很奇怪，需要补充下信息:

1. 遇到这个错误，是一个完整的下载结束后然后返回了`completed`但是你在SDCARD中没有找到文件吗？
2. 还是说，你启动一个下载，然后立马返回了`completed`?

这里相关逻辑:

1. FileDownloader如果是完整的下载流，在最终会检测本地文件大小与应该下载大小保证一致才会返回`completed`，否则会返回失败。
2. 启动下载，FileDownloader会先检查该文件是否已经存在，如果已经存在就会直接返回`completed`，否则会启动下载。

**Comment by supermanwu** [comment]
我这个文件比较小（小于1KB），我看了下打印信息，在下载的所有回调函数中，只触发了completed，其他都没触发，而且完成completed后，sdcard中是没有这个文件的。

**Comment by Jacksgong** [comment]
如果是只回调了`completed`，说明是一启动下载，就立马检测到文件存在返回了成功。

可否通过`FileDownloadLog.NEED_LOG=true`来打开日志，然后通过日志看看有没有其他线索。

**Comment by supermanwu** [comment]
FileDownloader.init(this); 这个初始化是不是有问题了~~
 compile 'com.liulishuo.filedownloader:library:1.5.7'

**Comment by Jacksgong** [comment]
@supermanwu 可以看下[迭代日志](https://github.com/lingochamp/FileDownloader/blob/master/CHANGELOG-ZH.md#version-157)，没有问题，只是弃用了不建议用。

```java
/**
 * @deprecated please use {@link #setup(Context)} instead.
 */
public static void init(final Context context) {
    if (context == null)
        throw new IllegalArgumentException("the provided context must not be null!");

    setup(context);
}
```

**Comment by supermanwu** [comment]
D/FileDownloader.DownloadTask: setPath /sdcard/elevator
D/FileDownloader.DownloadTask: setListener com.me.app.elevator.ElevatorActivity$4@2c95e550
V/FileDownloader.DownloadTaskHunter: call start Url[http://112.124.28.194:8080/elevator/theme/source/214c6614f5024c1dbda40501fa073911/214c6614f5024c1dbda40501fa073911.zip], Path[/sdcard/elevator] Listener[com.me.app.elevator.ElevatorActivity$4@2c95e550], Tag[null]
 V/FileDownloader.FileDownloadEventPool: setListener event.service.connect.changed
V/FileDownloader.DownloadTaskHunter: the task[1575226779] has been into the launch pool.
D/FileDownloader.FileDownloadProperties: not found filedownloader.properties
I/FileDownloader.FileDownloadProperties: init properties 0 load properties: http.lenient=FALSE; process.non-separate=FALSE; download.min-progress-step=65536; download.min-progress-time=2000; download.max-network-thread-count=3
 D/FileDownloader.LostServiceConnectedHandler: Waiting for connecting with the downloader service... 1575226779
D/FileDownloader.FileDownloadServiceUIGuard: bindStartByContext App
W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1550 android.content.ContextWrapper.bindService:517 com.liulishuo.filedownloader.services.BaseFileServiceUIGuard.bindStartByContext:156 com.liulishuo.filedownloader.services.BaseFileServiceUIGuard.bindStartByContext:126 com.liulishuo.filedownloader.FileDownloadServiceProxy.bindStartByContext:112 
W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1486 android.content.ContextWrapper.startService:494 com.liulishuo.filedownloader.services.BaseFileServiceUIGuard.bindStartByContext:157 com.liulishuo.filedownloader.services.BaseFileServiceUIGuard.bindStartByContext:126 com.liulishuo.filedownloader.FileDownloadServiceProxy.bindStartByContext:112 
D/FileDownloader.DownloadTaskHunter: free the task 1575226779, when the status is 10
D/FileDownloader.FileDownloadServiceUIGuard: onServiceConnected ComponentInfo{com.me./com.liulishuo.filedownloader.services.FileDownloadService$SeparateProcessService} com.liulishuo.filedownloader.i.IFileDownloadIPCService$Stub$Proxy@2c94a7f0
V/FileDownloader.FileDownloadEventPool: asyncPublishInNewThread event.service.connect.changed
V/FileDownloader.FileDownloadEventPool: publish event.service.connect.changed
D/FileDownloader.LostServiceConnectedHandler: The downloader service is connected.
V/FileDownloader.DownloadTaskHunter: call start Url[http://112.124.28.194:8080/elevator/theme/source/214c6614f5024c1dbda40501fa073911/214c6614f5024c1dbda40501fa073911.zip], Path[/sdcard/elevator] Listener[com.me.app.elevator.ElevatorActivity$4@2c95e550], Tag[null]
07-10 02:45:31.409 9522-10021/com.me.app.elevator V/FileDownloader.DownloadTaskHunter: the task[1575226779] has been into the launch pool.
D/FileDownloader.FileDownloadMessenger: notify begin 1575226779@com.liulishuo.filedownloader.DownloadTask@2c978980
V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@2c9f93d8 by 11 
V/FileDownloader.FileDownloadList: add list in all 1575226779@com.liulishuo.filedownloader.DownloadTask@2c978980 11 1
D/FileDownloader.MessageSnapshotGate: ~~~callback 1575226779 old[11] new[-3] 1
V/FileDownloader.FileDownloadList: remove 1575226779@com.liulishuo.filedownloader.DownloadTask@2c978980 left -3 0
D/FileDownloader.FileDownloadMessenger: notify block completed 1575226779@com.liulishuo.filedownloader.DownloadTask@2c978980 FileDownloader-LauncherTask2
D/FileDownloader.FileDownloadMessenger: notify completed 1575226779@com.liulishuo.filedownloader.DownloadTask@2c978980
V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@2c9f93d8 by -3 


这里面也看不出来什么呀~~~

**Comment by tribbianiwang** [comment]
我是这样解决的:下载的地址的demo里的方法 FileDownloadUtils.getDefaultSaveRootPath() + File.separator + "xx" + File.separator +
                   “xx”+ ".mp3";

**Comment by supermanwu** [comment]
哎，我的错~~~ 

我以为那个setpath函数里面是放存储的目录，你刚一提醒，去瞄了下，原来是要绝对路径。
谢谢你的解答。

**Comment by Jacksgong** [comment]
Okay, 如果是需要存储目录使用: `setPath(dirPath, true)`:

```java
/**
 * @param path            The absolute path for saving the download file.
 * @param pathAsDirectory {@code true}: if the {@code path} is absolute directory to store the
 *                        downloading file, and the {@code filename} will be found in
 *                        contentDisposition from the response as default, if can't find
 *                        contentDisposition,the {@code filename} will be generated by
 *                        {@link FileDownloadUtils#generateFileName(String)}  with {@code url}.
 *                        </p>
 *                        {@code false}: if the {@code path} = (absolute directory/filename).
 * @see #isPathAsDirectory()
 * @see #getFilename()
 */
BaseDownloadTask setPath(final String path, final boolean pathAsDirectory);
```
