### ISSUE TITLE
Unable to resume download

### ISSUE THREAD

**Issue by vishnu-prototyze** [lingochamp/FileDownloader#65]
Hi,

I am trying to download a single file, if i kill my application in the middle of the download, its does not resume? Where could i possibly go wrong. Need this urgently. Thanks.

**Comment by Jacksgong** [comment]
Did you mean when you re-launch your application and re-start the task, it can't resume after your kill your application?

**Comment by vishnu-prototyze** [comment]
Yes after i re-launch the app, in `onResume` i start the task if not completed by using a local storage flag like this `FileDownloader.getImpl().start(new DownloadListener(App.getInstance()), false);` but the download isnt resumed. This is the way to resume the download right?

**Comment by Jacksgong** [comment]
I think you are wrong,  `FileDownloader.getImpl().start(new DownloadListener(App.getInstance()), false) `  is used to download tasks with the same DownloadListener object as FileDownloadListner for each one, so you supported a new `DownloadListener` directly, the task queue must be empty.

If you want to resume the task, you just need to start it as the new task, FileDownloader will check(according to the save-path and download-URL)  and resume( has Etag? the old-file exist and undamaged ) automatically.

**Comment by vishnu-prototyze** [comment]
So i just checked, in `onResume` instead of start  i again used `FileDownloader.getImpl().create(buildUrl).setPath(path).setListener(new DownloadListener(App.getInstance())).start();` and that did the trick of resuming it. I guess this internally handles the 'Range' request property of Etag as u have mentioned.

**Comment by Jacksgong** [comment]
Yes, you got it.

**Comment by vishnu-prototyze** [comment]
Thanks @Jacksgong  you were really helpful and quick to respond.

**Comment by Jacksgong** [comment]
Good luck. :)
