### ISSUE TITLE
pause(downloadId)的参数downloadId怎么得到？

### ISSUE THREAD

**Issue by tribbianiwang** [lingochamp/FileDownloader#651]

**Comment by keeponZhang** [comment]
![111](https://user-images.githubusercontent.com/17671123/28054892-579e73bc-6649-11e7-8358-7170eb9e1b59.png)
![22](https://user-images.githubusercontent.com/17671123/28054897-5b47128a-6649-11e7-9854-d4b240b521c4.png)

**Comment by tribbianiwang** [comment]
谢谢

**Comment by Jacksgong** [comment]
嗯。除了创建任务时获取，还可以通过`FileDownloadUtils#generateId`来获取`downloadId`
