### ISSUE TITLE
下载完成completed的时候建议多个入参totalBytes

### ISSUE THREAD

**Issue by FreeLoopC** [lingochamp/FileDownloader#653]
建议改成protected void completed(BaseDownloadTask task, int totalBytes)

直接调用onProgress更新进度, 下载完成的最后一帧进度更新不上, 因为没有走onProgress而是走了completed, 但是 completed又没有totalBytes, 所以我只能用个变量在其他回调方法中去接收totalBytes, 这样感觉用起来不是特别的方便

**Comment by sh1tge** [comment]
task 不就可以获取到total么

**Comment by ZhouHoubin** [comment]
completed 进度不就满了?
