### ISSUE TITLE
下载Https的文件，出现CertPathValidatorException

### ISSUE THREAD

**Issue by pengveivei** [lingochamp/FileDownloader#654]
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

下载文件路径：https://inc.qufish.cn:7081/Upload/ProjectDeviceApk/a_20170707134535.apk

我用demo可以正常下载，在自己的项目中就出现这个错误。 
3ks for watch

**Comment by Jacksgong** [comment]
参考下这里: https://github.com/lingochamp/FileDownloader/issues/437#issuecomment-270825192
