### ISSUE TITLE
   退出app重新打开，获取某个下载任务的当前下载数据量和总数据量都是0

### ISSUE THREAD

**Issue by tribbianiwang** [lingochamp/FileDownloader#655]
`     long soFar = FileDownloader.getImpl().getSoFar(downloadingId);         long total = FileDownloader.getImpl().getTotal(downloadingId);`

**Comment by Jacksgong** [comment]
留意下Logcat。

参考下这里: https://github.com/lingochamp/FileDownloader/issues/364#issuecomment-253846894 https://github.com/lingochamp/FileDownloader/issues/579#issuecomment-303930347
