### ISSUE TITLE
下载到一半退出APP，再进来，拿不到下载任务的下载进度，已下载大小，总大小（拿到的是.00B）。需要开始下任务才能拿得到

### ISSUE THREAD

**Issue by SilasGao** [lingochamp/FileDownloader#656]
下载到一半退出APP，再进来，拿不到下载任务的下载进度，已下载大小，总大小（拿到的是.00B）。需要开始下任务才能拿得到

**Comment by Jacksgong** [comment]
#### 前言

- 留意下Wiki中的QA，QA中有提到这个问题。
- 留意下Logcat的输出，Logcat中有输出Warn级别日志说明原因以及解决方案。
- 搜索下Issue，过往Issue有人提过这个问题。


#### 解决方案

参考下这个Issue: https://github.com/lingochamp/FileDownloader/issues/655#issuecomment-314382892
