### ISSUE TITLE
暂停任务退出页面，重新进入页面，无法获取到pasued状态

### ISSUE THREAD

**Issue by markjoker** [lingochamp/FileDownloader#66]
感谢作者分享，但在使用过程中遇到一些问题，请解答一下，谢谢。
1. 暂停一个任务，退出页面，重新进入页面，无法获取到pasued状态。如果有完成的任务，可以获取到完成的状态。FileDownloadConnectListener 回调已经connected；
2. 暂停一个任务，重新创建相同的task并start，无法继续之前的下载。
暂停任务调用方法：
`public void pauseLoad(final int downloadId)
    {
        FileDownloader.getImpl().pause(downloadId);
    }`

**Comment by Jacksgong** [comment]
> P.S: `pause` 就是直接停止了整个任务，释放了所有的回调，除非重新开始任务(重新开始，重新注册监听，默认是会断点续传)

1. 这个你可以看看 demo 中的 `TasksManagerDemoActivity`，可能 `FileDownloader#getStatus`、`FileDownloader#getSoFar` 可以帮到你。

2. 如果无法断点续传，你看看FileDownloader回调的`connected` 中的 `etag`是否为空字符串，如果没有etag目前是无法支持断点续传的。至于重新创建相同task存在etag断点续传，可以参考demo中的 `SingleTaskTestActivity` 随便一个任务。

**Comment by markjoker** [comment]
有没有可能connected这个方法不会被回调，我试了几次，没有看到这个的回调。

**Comment by markjoker** [comment]
谢谢，确实是没有eTag。我想问问没有这个就无法断点续传么，有没有什么其他可替代的方法？

**Comment by markjoker** [comment]
能不能稍微改进一下呢？

**Comment by markjoker** [comment]
我注销了两段代码，发现没etag也可以断点续传了，不知道会不会引起其他问题，请作者指正一下。
1. FileDownloadMgr#
`if (TextUtils.isEmpty(model.getETag())) {
                 if (FileDownloadLog.NEED_LOG) {
                     FileDownloadLog.d(FileDownloadMgr.class, "can't continue %d etag is empty", downloadId);
                 }
                 break;
             }`
2. FileDownloadRunnable#addHeader
`builder.addHeader("If-Match", this.etag);`

**Comment by Jacksgong** [comment]
@markjoker 我也有打算在新的版本研究新的更可靠的方法，但是之所以依赖etag是因为etag，在绝大多数情景下，是断点续传的前置条件。有以下两个原因:

1. etag用来标记该文件是否有修改，比如你下载一个文件，过了一段时间没有下载了，服务端将该文件修改了，导致etag变更，那么客户端这边就需要重新下载，因此此时的断点续传将不再有意义。
2. etag的支持是文件下载的基本协议，服务端添加这个header现在有非常多的组件支持，非常的容易。

---
> P.S: 不过，在下个版本我会研究研究其他不依赖etag的靠谱的方案的。

**Comment by markjoker** [comment]
@Jacksgong 希望新版本能早日上线，可以新增一个配置选项，是否启用eTag。如果不启用，开发者需要自己保证下载URL对应的文件不会变化。

**Comment by Jacksgong** [comment]
ok.

**Comment by Jacksgong** [comment]
Fixed in [v0.2.1](https://github.com/lingochamp/FileDownloader/releases/tag/v0.2.1).
