### ISSUE TITLE
Estimated Time of Arrival?

### ISSUE THREAD

**Issue by SapneshNaik** [lingochamp/FileDownloader#661]
Does this library provide ETA feature? If yes How to call it?

**Comment by Jacksgong** [comment]
You can get speed through `BaseDownloadTask#getSpeed`, and you can get downloaded so far bytes from `BaseDownloadTask#getSoFarBytes`, also if response header contains(normally it would be) `content-length` you can get the total length through `BaseDownloadTask#getTotalBytes`, so you can calculate ETA by yourself through `speed`、`sofarBytes`、`TotalBytes`.

---

P.S. I think you also interest with `BaseDownloadTask#setMinIntervalUpdateSpeed`、`BaseDownloadTask#setCallbackProgressMinInterval`、`BaseDownloadTask#setCallbackProgressTimes`, there are java-doc on method please check out it feel free.
