### ISSUE TITLE
How do I know Serial Download has completed downloading all files?

### ISSUE THREAD

**Issue by virengujariya** [lingochamp/FileDownloader#662]
Is there any way to check in callback that indicates how many numbers of files left to download or is that something I need to keep track?

**Comment by rantianhua** [comment]
Actually, you can check every task's state.

**Comment by rantianhua** [comment]
If you use `FileDownloadSerialQueue` ，you can do this judgement through `getWorkingTaskId` and `getWaitingTaskCount` methods.
