### ISSUE TITLE
你好，请教一个问题：当文件预分配开关(file.non-pre-allocation)关闭时的疑惑

### ISSUE THREAD

**Issue by CHNfred** [lingochamp/FileDownloader#665]
大神，你好，关注了你的项目，功能很是强大，今天有时间来阅读了一下源码，有个地方很疑惑，还请指导：
1、当file.non-pre-allocation开关关闭时，创建临时下载文件时没有执行outputStream.setLength(contentLength)代码，也是就是这是临时文件可能是个大小为0的空文件
2、然后计算connectionCount分段数时，如果文件大于1G，则会设置connectionCount = 2，即2段
3、然后根据connectionCount拆分对应的子任务去执行，子任务运行在一个无限制大小的线程池中
4、最后子任务中根据计算好的fetchBeginOffset来seek之前创建的临时文件进行下载
疑惑：因这个线程池是无限制大小(即子任务下载的顺序不定)且临时文件也没有预分配空间(seek无法到指定位置)，怎样保证最终下载的文件是正确的？
望大神指点迷津！

**Comment by Jacksgong** [comment]
感谢阅读源码，欢迎PR~

---

其实有没有预分配空间与能不能`seek`没有直接关系。即便是没有预分配空间:

1. 如果`OutputStream`本身支持`seek`，执行`seek`超出本身的文件大小的时候`fd`的做法是将point指向对应的位置，一旦开始写数据时，文件大小就会跟着`point`发生改变。
2. 如果`OutputStream`本身不支持`seek`，默认就会只允许单个线程下载，不支持分块下载。

**Comment by CHNfred** [comment]
非常感谢！
