### ISSUE TITLE
能否分离模块，就像jackson-core, jackson-databinding

### ISSUE THREAD

**Issue by fancle** [lingochamp/FileDownloader#666]
核心功能与跨进程及Service可否分离成两个library，这样核心功能代码会比较清爽，结构也一目了然，方便测试

**Comment by Jacksgong** [comment]
感谢建议，确实值得采纳，我们会认真考虑。

#### 核心功能与跨进程及Service可否分离成两个library

 其实有没有跨进程核心代码都是同一块，并没有多余的代码，不同的只是`中间层`对通信方式的选择是走`binder`还是直接走`接口调用`。

#### 进一步思考

目前FileDownloader整体分为三层:

- [ 下载服务层 ] - 代表入口`FileDownloadManager`
- [ 中间层 ] - 代表入口`FileDownloadServiceProxy`
- [ 用户访问层 ] - 代表入口`FileDownloader`

---

核心模块:

- 通信与消息流管理
- 线程管理
- 下载与网络访问控制
- 上层接口设计
- 辅助工具相关

---

目前已拆分可定制组件（并只包含其默认实现)（[doc](https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component)):

- 网络连接组件(包含输入流相关与网络组件相关)
- 输出流组件
- 数据库组件相关
- 任务Id生成组件
- 分块下载数决策相关

---

不过你提的这个点确实可以讨论讨论，确实可以考虑剥离非主功能业务，其余尽可能赋能于组件/插件(类似retrofit、jackson的做法)或者赋能于`dispatcher`/interceptor`(类似okhttp的做法)，让用户尽可能根据需要轻量的使用FileDownloader:

- 用户使用起来能否更简单?
- 代码可读性与可维护性
- 是否足够单一轻量

---

其实我自己有打算在某个时机使用Kotlin重构FileDownloader，届时会考虑这里提到的点，包括会focus在：代码的可测试性、单元测试的代码覆盖程度、性能benchmark、可读性、轻量、简单，以及对现版本的FileDownloader接口的支持（封装一个适配器lib）等层面，因此我这边才没有进一步动作，毕竟现在在支付宝重心还是要考虑自己工作的KPI完成，因此精力也有限。

---

非常欢迎PR，或者更具体的建议，谢谢🙏～

**Comment by Ernest-su** [comment]
支持大神使用kotlin重构

**Comment by Jacksgong** [comment]
已经在[okdownload](https://github.com/lingochamp/okdownload)上做了。
