### ISSUE TITLE
How to update a database entry when the downloading completes but the application has already been killed?

### ISSUE THREAD

**Issue by Kshitij1792** [lingochamp/FileDownloader#668]
I am building a music download app where I am downloading the tracks. I write the track details in my database when the task finishes downloading. It works fine as long as UI is alive because I am doing it in the FileDownloadListener onComplete() callback. 
       BUT when the user kills the app the download which is running in the background no longer updates the database on finish because the callback has already been removed when UI died. 
  
How am I supposed to handle this situation. Where should I update my own database when the downloads finishes in background and there is no UI alive.

I read issue no #605  and learned about broadcast. But I am not sure how to use it.
Because my UI will not be alive when the broadcast occurs. So shall I need to write another Service that would update my database or there is a better way?

**Comment by Kshitij1792** [comment]
@Jacksgong Could you please take a look of this query. I am in need of your quick assistance as its kind of an urgent task for me.

**Comment by Jacksgong** [comment]
1. relate to #605, normally if the UI process is killed, it can be launched automatically when it received the `completed`  broadcast and you register the broadcast receiver on the manifest.
2. you can check download status with `FileDownloader#getStatus`.
3. you can start the task safely, if it completed download it will callback `completed` immediately; if it is paused or interrupted, it will resume from the breakpoint safely; if it is downloading on background yet, its callback would be attached with the downloading one( with the same download id) automatically.

**Comment by Kshitij1792** [comment]
Thanks for your quick reply. I tried to use it only with broadcast receiver(I mean without registering the receiver in a service). But its not reliable this way. It doesnt invoke the UI sometimes to write the "Completion time" of the downloaded file in the database. With service it worked absolutely fine. What could be possible reason of it?   
Also the file got downloaded in the background completely(So its only issue with broadcast receiver not being invoked). I registered the receiver in the AndroidManifest file. and pressed home button then task manager and swipe the app to kill it.
Please let me know if I am doing something in a wrong way.

**Comment by Jacksgong** [comment]
>  I tried to use it only with broadcast receiver(I mean without registering the receiver in a service). But its not reliable this way. It doesnt invoke the UI sometimes to write the "Completion time" of the downloaded file in the database. With service it worked absolutely fine. What could be possible reason of it?

Sorry, I can't understand why need compare between UI and service??, the receiver is just related to the component of broadcast-receiver,  what means if the downloading is completed, you will receive the completed intent, and you can do some logic you wrote on the broadcast-receiver class you implemented, simultaneously if the component of broadcast-receiver host process was killed, the process would be launched by System whatever UI process or other process, so why you compare with server?

**Comment by Kshitij1792** [comment]
By UI I meant "main process" of the app(Sorry my bad). So what Im trying to say is that after I kill the app(main process) the broadcast receiver doesnt get invoked all the  times(like it egts invoked 5 times out of 10).  here is my Broadcast receiver code:
`public class DownloadCompletedReceiver extends BroadcastReceiver {

    @Override
    public void onReceive(Context context, Intent intent) {
        Log.v("DownloadCompletedRecevr", "Inside Broad cast Receiver before updating database");
        FileDownloadModel model = null;
        if (intent != null)
            model = (FileDownloadModel) intent.getParcelableExtra(KEY_MODEL);

        Toast.makeText(context, "Download Completed for id "+model.getId(), Toast.LENGTH_SHORT).show();
        Log.v("DownloadCompletedRecevr", "Download Completed for id " + model.getId());
        TaskManager.getImpl().updateDownloadComplitionTimeForTask(model.getId(), System.currentTimeMillis());

       /* if ((new TasksManagerDBController()).getAllDownlaodingTasksList().size() == 0) {
            if (isUpdaterServiceRunning(DownloadTimeUpdateService.class,SMPApplication.getAppContext())) {

                Intent newIntent = new Intent(SMPApplication.getAppContext(), DownloadTimeUpdateService.class);

                boolean hasStopped = SMPApplication.getAppContext().stopService(newIntent);

                Toast.makeText(context, "DownloadCompletedReceiver service is stopped- " + hasStopped, Toast.LENGTH_SHORT).show();
                Log.e("DownloadCompletedRecvr", " service is stopped- " + hasStopped);
            }
        }*/

    }

   /* private boolean isUpdaterServiceRunning(Class<?> serviceClass, Context context) {
        ActivityManager manager = (ActivityManager) context.getSystemService(Context.ACTIVITY_SERVICE);
        for (ActivityManager.RunningServiceInfo service : manager.getRunningServices(Integer.MAX_VALUE)) {
            if (serviceClass.getName().equals(service.service.getClassName())) {
                Log.e("Service already", "running");
                return true;
            }
        }
        Log.e("Service not", "running");
        return false;

    }*/
}`

and this is how I have registered Broadcast Receiver in the Manifest

`...

        <receiver android:name="com.onmo.downloads.DownloadCompletedReceiver" >
            <intent-filter >
                <action android:name="filedownloader.intent.action.completed" />
            </intent-filter>
        </receiver>
    </application>

</manifest>`

If you check the Broadcast receiver code I was earlier using a service to keep the broadcast component alive by registering it in the service, which I have removed now and registering it as a normal broadcast receiver.
The problem is that in earlier (registering broadcast receiver in service) it was working (10 out of 10 times), but registering the Broadcast receiver as regular way its not working 10 out of 10 times. it would work only for say 7 out of 10 times or 8.
I hope this code would explained my problem better to you. Please let me know if you find anything confusing about it.

"simultaneously if the component of broadcast-receiver host process was killed, the process would be launched by System whatever UI process or other process, so why you compare with server?"- I understand this thing. I totally get it.

**Comment by Jacksgong** [comment]
Okay.... since this is the System behavior, so this rule must be damaged by the system manufactory(  they change the origin Android): such as on MIUI system we can't launch the process with receive the broadcast.

---

So we have to find another way to meet what you want, I think there still are several ways:

1. **CHANGE** FileDownloader, using content-provider instead of broadcast. -- too much need to change.
2. **CHANGE** FileDownloader, launch an `IntentService` which host process is main-process instead of broadcast. -- In this way the user must register local-broadcast or some interface on `Application#onCreate` to receive the callback, only do this, your logic can be attached when main-process is launched for `IntentService` -- not easy to teach users to do this, but we will consider.
3. **NO-CHANGE** FileDownloader, since you only care about whether the task is completed, why not sync your database when a user launches your application next time, you can do that on `Application#onCreate` with `FileDownloader#insureServiceBind` and `FileDownloader#getStatus`, and for better experience you also can sync it when a user enters the target `Activity` rather than on `Application#onCreate`.

**Comment by Kshitij1792** [comment]
Thanks for the detailed answer on this. I understood your points.
About point 1 and 2. I will explore these 2 options as I have barely worked on content-provider and Broadcast receiver. So I first read a bit more about it before actually implementing these on my own.

About point 3. If I wait for the user to launch the app again for sync, the "download-completion-time" for those remaining files which broadcast receiver didnt update would be totally incorrect. Like say I put 10 files on download now and for 3 files "download completion time" doesn't get updated by the broadcast receiver. Then user opens the app after 2-3 days then the sync would have "download completion time" of that day. Which is very inappropriate I believe. Though it seems like a valid workaround but its not bullet proof.

What do you think about my earlier approach of running a background service and registering the broadcast receiver in that service to keep it alive all the time until all downloads complete. What  downsides do you see in this approach?(Just want to know as it worked absolutely fine for me).

I will explore option 1 and 2 suggested by you meanwhile and would ask you in case I need any help.
Thank you very much for being so proactive and all the quick responses so far.

**Comment by Jacksgong** [comment]
and welcome PR~ :)

**Comment by Jacksgong** [comment]
so, you also concerned with the timestamp of complete not only the complete status.

---

I think if you want to run a background service on the main-process and register broadcast-receiver on it to receive the complete-broadcast( as you know if you run a service on the main-process with User exit the App, then the main-process will be the Service-Process rather than Background-Process, so the main-process can have longer survival time, it won't be reclaimed on the most case), why don't you just let FileDownloadService runs on the main-process with set `process.non-separate=true` on [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties), because of your service host process also possible to be killed with FileDownloadService host process is alive, then you also lost complete-status.

**Comment by Kshitij1792** [comment]
Ya the completion TimeStamp was main concern as I wanted to save it in order to sort them based on "Completed on so and so date".
About your  process.non-separate=true suggestion, I tried this one long back but it would stop the download as soon as the user kills the main app. So the download would not continue in the background. Therefore whole concept of trying to get competion time when app UI process is not alive goes away.
I spent time reading about Processes and Broadcast Receiver things and I was wondering if instead of starting a new service and registering the Broadcast receiver in that If I register my Broadcast Receiver in the LIBRARY'S DOWNLOAD PROCESS that is android:process=":filedownloader", then it would be alive as long as the android:process=":filedownloader" is running. 
What do you think about this approach.

**Comment by Kshitij1792** [comment]
waiting for your comments on this. Would this be a good idea. And I found out one more thing. when I start a FileDownloadNotificationListener when starting a download and kill the app its fine. But there is one clean task button provided by mobile manufecturer, if I press that icon it just stops the progress update in notification bar. Dont know how to get rid of this as well. I have screenshots to share. Let me know if you want to take a look of them.I would share it on your mail id.
Thanks

**Comment by Kshitij1792** [comment]
@Jacksgong  waiting for your comments on this. Would this be a good idea. And I found out one more thing. when I start a FileDownloadNotificationListener when starting a download and kill the app its fine. But there is one clean task button provided by mobile manufecturer, if I press that icon it just stops the progress update in notification bar. Dont know how to get rid of this as well. I have screenshots to share. Let me know if you want to take a look of them.I would share it on your mail id.
Thanks

**Comment by Kshitij1792** [comment]
Hi @Jacksgong  
Any development in this regard?

**Comment by Kshitij1792** [comment]
@Jacksgong  Just to bring this thread under your notice again. 
Did you come up with a cleaner approach for this? I found a fix but I think better and cleaner fixes could be developed.
