### ISSUE TITLE
FileDownloadRunnable.HttpRequestException is private

### ISSUE THREAD

**Issue by HugoGresse** [lingochamp/FileDownloader#67]
I wanted to have more control of download errors but the Exception when the HttpRequest failed is private (`FileDownloadRunnable` is a private class, and `FileDownloadRunnable.HttpRequestException` is in it). 

If wil be great if
- we have the http error code from the exception, or the full OkHttp `Response` of the network request 
- make `FileDownloadRunnable` public so we can check the instance of it.

**Comment by Jacksgong** [comment]
Good point, I will  enhance it in next version.

**Comment by HugoGresse** [comment]
cool, thank you! 
Did you had time to check issue #54

**Comment by Jacksgong** [comment]
Ok.

**Comment by Jacksgong** [comment]
Enhanced in [v0.2.1](https://github.com/lingochamp/FileDownloader/releases/tag/v0.2.1).
