### ISSUE TITLE
多任务下载时，一个任务出错如何阻止下一个任务自动开始？

### ISSUE THREAD

**Issue by Godsbox** [lingochamp/FileDownloader#670]
我是多任务单线程下载，当我其中一个任务出错时，下一个任务会自动开始

**Comment by rantianhua** [comment]
如果你用的是 `FileDownloadSerialQueue` 那么在 Task 出错时，你可以调用 `FileDownloadSerialQueue#pause` 或者 `FileDownloadSerialQueue#shutdown`。
