### ISSUE TITLE
startForeground后notification滑动删除不了，这个怎么解决好

### ISSUE THREAD

**Issue by keeponZhang** [lingochamp/FileDownloader#672]

**Comment by Jacksgong** [comment]
前台服务的Notification，是一个`ongoing`的Notification，本来就是无法滑动删除的。

如果你需要取消前台服务可以使用`FileDownloader#stopForeground`进行取消。

**Comment by keeponZhang** [comment]
你好，想问下，退出应用后，前台服务的notification能获取到后台服务的相关下载信息吗？

**Comment by Jacksgong** [comment]
默认下载服务是运行在下载进程的。

这里使用`startForeground`只是说将 `下载进程` 从`服务进程` 申明为 `前台进程`。始终就只有一个下载服务，不存在前台服务后台服务之说。

**Comment by keeponZhang** [comment]
是这样的，下载的一个是apk，下载完成后静默安装，当应用退出后，下载进程是继续的，有没有办法把下载过程的进度反馈到notification,把安装完成后的信息也反馈到notification呢？

**Comment by keeponZhang** [comment]
大神，还有个问题问下，下载任务完成后，下载进程还是运行着的吗？如果是，是不是太耗资源了。

**Comment by keeponZhang** [comment]
大神，在吗？可以给个思路吗？比较急，谢谢了

**Comment by Jacksgong** [comment]
关注下文档: [wiki](https://github.com/lingochamp/FileDownloader/wiki).

- 你可以通过`filedownloader.properties`配置让下载服务运行在主进程而非下载进程。
- 你可以通过`FileDownloader#unBindService`让下载服务解绑

**Comment by Jacksgong** [comment]
`filedownloader.properties`是支持配置`broadcast.completed`接收下载完成广播的。

**Comment by keeponZhang** [comment]
谢谢。我还想问下，应用退出后，下载完成后是可以收到完成广播，但在下载过程中，notification能拿到下载进度吗？
