### ISSUE TITLE
Exception handler

### ISSUE THREAD

**Issue by majidln** [lingochamp/FileDownloader#674]
hi
how can I use exception handler link FileDownloadOutOfSpaceException?
please help me? if you can show me an example?
thanks for this lib

**Comment by Jacksgong** [comment]
Sorry, If you occur the `FileDownloadOutOfSpaceException`, it means there isn't large enough on the device to store the downloading file, and you can get how much on the `FileDownloadOutOfSpaceException`, so you can handle this exception with following  ways I think:

1. toast the tips to users to let they know the reason and let user to remove some temporary files on the devices.
2.  remove temporary files your application managed and try again.
