### ISSUE TITLE
使用发现重新进入应用后下载进程并不会断点续传没有下载完的所有任务？

### ISSUE THREAD

**Issue by keeponZhang** [lingochamp/FileDownloader#675]

**Comment by keeponZhang** [comment]
大神，在吗?这个问题比较急，可以回复下吗？谢谢

**Comment by Jacksgong** [comment]
参考[文档](https://github.com/lingochamp/FileDownloader/wiki/Low-Memory%3F)。

重新所有任务就行了，会自动断点续传。

**Comment by keeponZhang** [comment]
还有个问题，有没有可能用户主动点暂停的任务不要自动断点续传，而因为应用退出而暂停的任务才自动断点续传

**Comment by keeponZhang** [comment]
在吗？可以给个思路吗？谢谢
