### ISSUE TITLE
downloadTogether启动任务，暂停任务，reuseAndStart有bug

### ISSUE THREAD

**Issue by Aimn** [lingochamp/FileDownloader#676]
首先感谢楼主好心分享
我先建立了一个list，然后用downloadTogether.start启动队列，暂停队列，通过reuseAndStart重新启动的时候，队列会0开始下载，这是为什么？

**Comment by Jacksgong** [comment]
是说从第0个开始下载吗？如果是的话是设计如此的，因为`reuseAndStart`本身就是复用原本队列，并启动该`QueueSet`。

**Comment by Aimn** [comment]
那请问下，有没有什么方法可以继续之前的位置下载了？
