### ISSUE TITLE
设置下载队列里的任务为一个，通过这种方式设置FileDownloader.getImpl().setMaxNetworkThreadCount(1);为什么不起作用？

### ISSUE THREAD

**Issue by leigejiayou** [lingochamp/FileDownloader#677]

**Comment by Jacksgong** [comment]
`FileDownloader.getImpl().setMaxNetworkThreadCount(1)`需要在 当前运行队列为空并且下载服务已经启动并绑定的情况下。

你可以留意下logcat，针对具体如果没有作用的原因与解决方法都已经通过logcat输出了。
