### ISSUE TITLE
报错FileDownloadGiveUpRetryException,已按README修改http.lenient=true。

### ISSUE THREAD

**Issue by abbenyyyyyy** [lingochamp/FileDownloader#678]
报错log：
`com.liulishuo.filedownloader.exception.FileDownloadGiveUpRetryException: require range[0-1716058) with contentLength(1716059), but the backend response contentLength is 3432118 on downloadId[-290926842]-connectionIndex[0], please ask your backend dev to fix such problem.
`
单文件下载，按照README添加`http.lenient=true`,也尝试了添加`file.non-pre-allocation=true`，无论如何依然报这个错。
附上下载URL：http://www.shaolin.com.cn/ShaolinWeb/web/Download.aspx?CID=1383&=Sequence=0

谢谢。

**Comment by Jacksgong** [comment]
`http.lenient=true`与`file.non-pre-allocation=true`与这个case无关，这个是后端的问题。即便是下载了也会是损坏的文件，原因日志里面已经写的很清楚了:

```
require range[0-1716058) with contentLength(1716059), but the backend response contentLength is 3432118 on downloadId[-290926842]-connectionIndex[0], please ask your backend dev to fix such problem.
```

翻译:

```
请求下载区间[0-1716058)需要下载长度(1716059), 但是后端返回`content-length`是 3432118, 请联系后端同学修复这个问题。
```

---

首先分包，分块请求是在后端返回允许分块下载的前提下，才会进行这个分块多线程下载的，但是请求了指定区间了，后端还是返回一个错误的长度，如果依然写入，会导致该块写入不对，导致文件有可能有问题的。

---

#### 推荐解决方法

1. 联系后端同学，让其解决该BUG
2. 尝试使用单连接下载

---

#### 使用单连接下载方案一

1. 在`filedownloader.properties`中配置不使用独立进程
2. 实现`FileDownloadHelper.ConnectionCountAdapter`，并在里面配置需要单连接的连接缓存，当下载出现类似错误的时候，将连接加入缓存，然后重新下载。
3. 通过`FileDownloder.setupOnApplicationOnCreate`注册该`ConnectionCountAdapter`

#### 使用单连接下载方案二

实现`FileDownloadHelper.ConnectionCountAdapter`全局都该用单线程下载。

**Comment by zhoukai0203** [comment]
content-length 可以从Content-Range中读取么， @Jacksgong
