### ISSUE TITLE
如何获取之前pause的 soFarBytes

### ISSUE THREAD

**Issue by AU3904** [lingochamp/FileDownloader#679]
问题描述：在页面A 触发下载，点击pause；退出。   再次进入页面A，希望看到之前的下载量，比如40% ，请问如何做？

是需要我自己将下载状态，以及之前的下载量 存储到数据库吗？ 

谢谢

**Comment by ZhangQixiangChina** [comment]
我也有这个问题
他有方法`BaseDownloadTask#getSoFarBytes` 和`FileDownloader#getSoFar(int downloadId)`
但是这两个方法我都试了, 为0
