### ISSUE TITLE
下载出现404

### ISSUE THREAD

**Issue by hkllzh** [lingochamp/FileDownloader#686]
资源是真实存在的，地址为（http://dn-easy-learn.qbox.me/Level 6 Lesson 2 At the airport.pdf）。
在下载的回调（FileDownloadSampleListener）的error方法中，出现了404错误。
已有情况是在三星和魅族的手机上出现了，不是必现但几率很大。在华为Mate 9上没有出现。
测试方式：debug 没有找到具体原因。采用了多次安装，调用下载方法做测试。

后来采用 okhttp 方式进行网络连接，多次测试没有出现。
```
final OkHttpClient.Builder builder = new OkHttpClient.Builder();
builder.connectTimeout(20_000, TimeUnit.SECONDS);
FileDownloader.setupOnApplicationOnCreate(this)
        .connectionCreator(new OkHttp3Connection.Creator(builder))
        .commit();
```

没有找到出现错误的具体位置，但问题确认存在。希望提供的信息有所帮助。

**Comment by Jacksgong** [comment]
404应该是服务器的返回值，这边返回404我估计是7牛(qbox.me)的问题，建议可以给他们提下工单。

---

- `FileDownloader`中默认的连接器是使用`UrlConnection`默认的一个实现，可以参考下`FileDownloadUrlConnection`。
- 当然正如你所使用的，FileDownloader本身是支持定制`connection`的，而由于默认的连接器上层应用层相对okhttp来说我们并没有做过多的长尾的连接处理，我们希望能够聚焦在下载这一块，因此也是开放了连接组件注册这块。
- 不过在Android 4.4或更高版本的Android其实使用`UrlConnection`本身Android原生就是使用了okhttp，因此这边还需要留意下是否使用高版本的okhttp真的handle了这个问题，毕竟这个是后台返回的404，是由后端处理的，每一次的请求除非你添加了请求头，对于FileDownloader本身都是没有变化的，而作为`UrlConnection`肯定是使用符合Http(s)协议规范的进行了请求。
