### ISSUE TITLE
I want to set the ID of the task . Not automatically generated

### ISSUE THREAD

**Issue by sd6352051** [lingochamp/FileDownloader#687]
`FileDownloadUtils.generateId(mUrl, mPath, mPathAsDirectory)` 
Task id is automatically generated via URL and PATH

**Comment by sd6352051** [comment]
I found `IdGenerator`  .but still limited

**Comment by Jacksgong** [comment]
why can't `IdGenerator` meet what you want?

**Comment by sd6352051** [comment]
IdGenerator is able to meet my needs. IdGenerator must use url and file path to generate the task id but i want to use my download file id.

But this is not important, I have modified to use the default IdGenerator 

Thx:smile:

**Comment by Jacksgong** [comment]
Okay, Please implement you own `IdGenerator` and register it to FileDownloader through `FileDownloader#setupOnApplicationOnCreate` rather than modify the default one.

---

P.S. you can generate download identify what you like, you don't have to generate it uses url and path.
