### ISSUE TITLE
android5.1智能盒子反复拔插网线问题

### ISSUE THREAD

**Issue by lxbestno1** [lingochamp/FileDownloader#688]
请教一下，这里我有一个android5.1的盒子，反复暂停、下载是没有问题的，但是如果反复拔插网线（断网的时候做了pauseAll的操作），网络重连后点击继续下载，这样反复几次之后，点击继续下载就会没有反应，从log来看，第一次没有反应是走到了pending里面，不进行后续的下载，之后都会走到warn，不但如此，出现此问题后，所有的下载都不能进行，都会只走到pending的回调后就没有后续的反应了

**Comment by Jacksgong** [comment]
在[v1.5.8](https://github.com/lingochamp/FileDownloader/releases/tag/v1.5.8)与[v1.6.0](https://github.com/lingochamp/FileDownloader/releases/tag/v1.6.0)中修复了在1.5.0中引入的类似的无响应的问题。请使用最新版本(目前最新版本是1.6.2)

**Comment by lxbestno1** [comment]
首先感谢很迅速的做出了回应，但是这里我是使用了1.6.2，这个问题依然存在

**Comment by Jacksgong** [comment]
okay.. 为了定位问题:

#### 可否进行以下配置

- 在`Application#onCreate`中设置`FileDownloadLog.NEED_LOG=true`
- 在[`filedownloader.properties`](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)中设置`process.non-separate=true`

#### 在完成以上配置后，清空Logcat，然后尝试复现问题，复现后提供所有日志。

**Comment by lxbestno1** [comment]
很头疼，这款盒子在多次拔插网线之后连接处于offline状态，就是问题复现时候看不到log...

**Comment by Ernest-su** [comment]
@lxbestno1 可以找个log工具库，把log写到文件里。
