### ISSUE TITLE
断点续传存在一定概率进度置为0，重新开始下载了？

### ISSUE THREAD

**Issue by erqian** [lingochamp/FileDownloader#689]
请问是我有什么配置不对还是有其他代码方面的问题呢

**Comment by erqian** [comment]
断点续传失败LOG：there is precondition failed on this request[-987752328] with old etag["596714ce-9a66775"]、new etag[null]、response code is 206

**Comment by Jacksgong** [comment]
这个logcat已经说的很明白了，这个是服务端返回的etag发生改变，所以后端那边前置条件验证失败，所以从头开始下载。

关于etag验证失败: 说明该连接远端资源发生变化，因此已经不是同一个文件了，因此需要重头下载，这个的抉择是后台根据其之前返回的etag决定的，如果你验证发现文件没有变化，但是etag变化了，或者是验证失败了，这个是后台bug，请咨询你的后台同学。

**Comment by erqian** [comment]
再请教一下  可不可以有什么方法不通过etag来进行判断是否是同一文件呢  ？  因为我从第三方应用平台上下载APK文件，他的APK还是没变的，只是存在偶然的情况下它的etag改变了。
