### ISSUE TITLE
Improve FinishListener parameters

### ISSUE THREAD

**Issue by HugoGresse** [lingochamp/FileDownloader#69]
When the network is disconnected while Downloader is downloading many task, each `task` call their `BaseDownloadTask.FinishListener` which is ok. But it will be great to be aware of the success or fail in the `over()` listener method. 

To generalise this, it will be great to have more information in the `over()` callback, for example FinishListener of the `FileDownloadQueueSet.addTaskFinishListener(..)` will maybe have the finished task in the `over` listener...

**Comment by Jacksgong** [comment]
It's not easy to add parameters to `over()`, consider the compatibility.
