### ISSUE TITLE
下载的时候提示错误there isn't any content need to download on 938228316--1 with the content-length is 0

### ISSUE THREAD

**Issue by supermanwu** [lingochamp/FileDownloader#690]
![tim 20170724185216](https://user-images.githubusercontent.com/20654719/28520149-f0b2a4cc-70a0-11e7-9166-3e09459d2848.png)
这是打印的日志。

我用下面的这种办法就可以下载。

![tim 20170724185348](https://user-images.githubusercontent.com/20654719/28520216-36530526-70a1-11e7-8248-af43ee97b072.png)

麻烦你帮忙看下。

**Comment by Jacksgong** [comment]
这个提示其实已经很清楚了: `there isn't any content need to download on 938228316--1 with the content-length is 0`，说明返回的`content-length`是0，也就说输入流中将不会有任何数据返回。我看了下，因该是你本地的搭建的资源服务有些问题，没有带回来正确的`content-length`；下面你自己编写的下载之所以可以执行，是因为你没有对response header进行校验。
