### ISSUE TITLE
如何获取当前下载的下载数？ 有没有办法设置下载任务的优先级？ ......

### ISSUE THREAD

**Issue by dinuscxj** [lingochamp/FileDownloader#694]
两个问题：
 1. 如何获取当前下载的下载数
 2. 有没有办法设置下载任务的优先级

如果没有办法设置优先级，有没有办法获取正在下载的任务的ID, 然后这样方便实现

**Comment by xiangyutian** [comment]
FileDownloadList.getImpl().isEmpty()参见这个方法，可以获取正在进行的任务数;

**Comment by rantianhua** [comment]
> 如何获取当前下载的下载数

目前没有这个支持，因为是使用方创建的任务，所以 FileDownloader 没有再提供该接口，况且对于所有的任务，不一定都是有关联的。简单说就是，使用方式知道当前下载数量的，单任务的话不用说了，多任务的话，一般是用的 `XXXQueue` ，既然是 Queue ，那么使用者会创建任务列表 ，根据 Listener 回调去更新任务列表，那么也自然知道任务数了。

> 有没有办法设置下载任务的优先级 

FileDownloader 是没有的，不过 [OkDownload](https://github.com/lingochamp/okdownload) 实现了，如果这是对你很重要的功能，建议使用 OkDownload ，FileDownloader 不会再添加新功能。
