### ISSUE TITLE
从服务端下载文件，失败之后能否获取到服务端返回的某些信息?

### ISSUE THREAD

**Issue by lvfaqiang** [lingochamp/FileDownloader#698]
你好，请问一下：在使用该库的时候，访问服务端下载，被拒绝之后，能否获取到服务端携带的一些返回提示呢？

**Comment by rantianhua** [comment]
`FileDownloadConnection` 提供了 `getResponseHeaderFields` 接口，所以你可以自定义该组件在你需要的时候获取，而且在你描述的情况下，日志也是有打印的。自定义组件参见 https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component 。
