### ISSUE TITLE
如何得到bitmap

### ISSUE THREAD

**Issue by MrLiKH** [lingochamp/FileDownloader#70]
hi，我想知道我根据一个url，怎么用这个工具得到我下载的bitmap对象

**Comment by HugoGresse** [comment]
Don't you think writing the issue in Enligh on an Open Source project worth it?

**Comment by Jacksgong** [comment]
这个组件主要是为了下载，如果你有这个需求可以自己将它从文件中decode出来。（p.s: 可以在回调blockComplete中做，这个回调是在非UI线程做的，并且在这个回调中已经下载完成了，并且可以同步block住complete的回调，）
