### ISSUE TITLE
connection failed with code[503] on task [-1272187019] which ic changed after verify connection so please try again

### ISSUE THREAD

**Issue by hassan379** [lingochamp/FileDownloader#700]
hello thank you very much for this great library but after updating the library to latest version every time when i try to download any file this message appear 
"connection failed with code[503] on task [-1272187019] which is changed after verify connection so please try again"
i updated to latest version because i want to use the multi connection ability in the new version 
i tried to edit DefaultConnectionCountAdapter and set determineConnectionCount to 1, the download works again without any issue but with low download speed and i want to take advantage of all internet speed 
please can you help me with this 
thanks in advance

**Comment by Jacksgong** [comment]
The description is very clear:

```
connection failed with code[503] on task [-1272187019] which is changed after verify connection so please try again
```

When you enable multiple connections, for FileDownloader we will launch the first connection as verify-connection to check out whether the resource supports multiple connections, so after the backend response declare it support multiple-connection to download the resource we will launch the multiple connections to download the resource, but the backend response 503 so we can't to download it. 

#### How to resolve?

- Way 1. please ask your backend partner, why they response 503 what is the backend problem
- Way 2.  customize you own `ConnectionCountAdapter` to let this special resource only use 1 connection count.

**Comment by hassan379** [comment]
okay thank you for your respond , but i am trying the same links on other application like ADM app which support multi connection and it works fine and it gives me full speed 
is there any way to force the downloading to make many connection by some way 
and thx again for this great library
