### ISSUE TITLE
java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)

### ISSUE THREAD

**Issue by helixs** [lingochamp/FileDownloader#703]
我用浏览器和其他工具下载都不会出问题，但是使用这个之后就会出了Throwable，感觉很奇怪。

**Comment by helixs** [comment]
url 现在是内网的ip如 http://10.5.192.86/down/appPreview_1.0.2.apk

**Comment by aqianglala** [comment]
同个情况，经常出现，希望作者能帮看下，期待回复
http://dd.myapp.com/16891/76CD334D54B21129AD9857E67D0E0BAE.apk?fsname=com.baidu.searchbox.lite_2.2.2_19013632.apk&_gdt_ma_cdn_cb=1&qz_gdt=tkyicwicaaapf53ynjra&appid=1106087470

**Comment by Jacksgong** [comment]
参考这个issue: #473
