### ISSUE TITLE
请问如何获取更加精确的下载进度？

### ISSUE THREAD

**Issue by Rogero0o** [lingochamp/FileDownloader#704]
十分感谢大神的下载库。
如题，不知道有没有办法获取到更加精确的下载进度，使用 Listener 或者 getFileSoFarBytes / getFileTotalBytes 刷新进度基本上市 1% 刷新一次，有办法提高这个频率或者是否有别的办法获取更精确的下载进度？最好能达到 00.000% 递增这样的效果。
任何提示都很有帮助，谢谢。

**Comment by Jacksgong** [comment]
参考下这里: https://github.com/lingochamp/FileDownloader/issues/246#issuecomment-237133750
