### ISSUE TITLE
FileDownloader#getStatus(url:String, path:String) 总是返回0

### ISSUE THREAD

**Issue by layasntx** [lingochamp/FileDownloader#708]
FileDownloader#getStatus() 总是返回0，即使当前正在下载

**Comment by layasntx** [comment]
如何动态修改下载线程数量，而不是通过properties 文件

**Comment by layasntx** [comment]
getStatus()发现是url改变导致id不一致造成的

**Comment by layasntx** [comment]
FileDownloader#init过期了，有其他方法初始化定制组件吗

**Comment by layasntx** [comment]
定制了IdGenerator之后，不能下载，一直停留在toFileDownloadService状态

**Comment by layasntx** [comment]
FileDownloader.setupOnApplicationOnCreate(this)
                .idGenerator(new FileDownloadHelper.IdGenerator() {
                    @Override
                    public int transOldId(int oldId, String url, String path, boolean pathAsDirectory) {
                        return generateId(url, path, pathAsDirectory);
                    }

                    @Override
                    public int generateId(String url, String path, boolean pathAsDirectory) {
                        return DownLoadUtils.generateId(url, path, pathAsDirectory);
                    }
                })
                .maxNetworkThreadCount(1);

**Comment by layasntx** [comment]
public static int generateId(String url, String path, boolean pathAsDirectory) {
        String[] split = url.split("\\?sign=");
        if (pathAsDirectory) {
            return FileDownloadUtils.md5(String.format(Locale.ENGLISH, "%sp%s@dir", split[0], path)).hashCode();
        } else {
            return FileDownloadUtils.md5(String.format(Locale.ENGLISH, "%sp%s", split[0], path)).hashCode();
        }
    }

**Comment by layasntx** [comment]
我这边的需求是要做防盗链，每次url都不一样，因此我在generateId把url后面的签名和时间戳都截掉了，结果就不能下载了，进入不了pending状态

**Comment by Jacksgong** [comment]
#### 如何动态修改下载线程数量，而不是通过properties 文件

`FileDownloader#setMaxNetworkThreadCount`

**Comment by Jacksgong** [comment]
不能下载有什么logcat输出吗？(如果默认情况，请关注主进程与`:filedownloader`进程的logcat)。

**Comment by layasntx** [comment]
08-09 21:54:19.572 22863-22863/com.caishi.cronus D/FileDownloader.DownloadTask: setPath /storage/emulated/0/Android/data/com.caishi.cronus/files/auido_down/361687e73930dc406bef628720b9cb31
08-09 21:54:19.573 22863-22863/com.caishi.cronus D/FileDownloader.DownloadTask: setListener com.caishi.cronus.ui.audio.AudioDownUtils$1@4b9affb
08-09 21:54:19.573 22863-22863/com.caishi.cronus D/FileDownloader.DownloadTask: setTag 361687e73930dc406bef628720b9cb31
08-09 21:54:19.574 22863-22863/com.caishi.cronus V/FileDownloader.DownloadTaskHunter: call start Url[http://audio.9liuda.com/audio/1499247186306/YWdjS3PwWk33ch6wJcmceRTE?sign=008ab998ce9844dfd8f0d11da3d31585&t=598b2218], Path[/storage/emulated/0/Android/data/com.caishi.cronus/files/auido_down/361687e73930dc406bef628720b9cb31] Listener[com.caishi.cronus.ui.audio.AudioDownUtils$1@4b9affb], Tag[361687e73930dc406bef628720b9cb31]
08-09 21:54:19.576 22863-22863/com.caishi.cronus D/FileDownloader.DownloadMgrInitialParams: initial FileDownloader manager with the customize id generator: com.caishi.cronus.app.CronusApplication$2@ab84271
08-09 21:54:19.576 22863-22863/com.caishi.cronus V/FileDownloader.DownloadTaskHunter: the task[-883323028] has been into the launch pool.
08-09 21:54:19.576 22863-25963/com.caishi.cronus V/FileDownloader.FileDownloadEventPool: setListener event.service.connect.changed
08-09 21:54:19.584 22863-25963/com.caishi.cronus D/FileDownloader.FileDownloadProperties: not found filedownloader.properties
08-09 21:54:19.591 22863-25963/com.caishi.cronus I/FileDownloader.FileDownloadProperties: init properties 7
                                                                                           load properties: http.lenient=FALSE; process.non-separate=FALSE; download.min-progress-step=65536; download.min-progress-time=2000; download.max-network-thread-count=3
08-09 21:54:19.593 22863-25963/com.caishi.cronus D/FileDownloader.LostServiceConnectedHandler: Waiting for connecting with the downloader service... -883323028
08-09 21:54:19.594 22863-25963/com.caishi.cronus D/FileDownloader.FileDownloadServiceUIGuard: bindStartByContext CronusApplication
08-09 21:54:19.614 22863-25963/com.caishi.cronus D/FileDownloader.DownloadTaskHunter: free the task -883323028, when the status is 10
08-09 21:54:19.708 22863-22863/com.caishi.cronus D/FileDownloader.FileDownloadServiceUIGuard: onServiceConnected ComponentInfo{com.caishi.cronus/com.liulishuo.filedownloader.services.FileDownloadService$SeparateProcessService} com.liulishuo.filedownloader.i.IFileDownloadIPCService$Stub$Proxy@ee950d7
08-09 21:54:19.709 22863-22863/com.caishi.cronus V/FileDownloader.FileDownloadEventPool: asyncPublishInNewThread event.service.connect.changed
08-09 21:54:19.710 22863-25984/com.caishi.cronus V/FileDownloader.FileDownloadEventPool: publish event.service.connect.changed
08-09 21:54:19.710 22863-25984/com.caishi.cronus D/FileDownloader.LostServiceConnectedHandler: The downloader service is connected.
08-09 21:54:19.711 22863-25984/com.caishi.cronus V/FileDownloader.DownloadTaskHunter: call start Url[http://audio.9liuda.com/audio/1499247186306/YWdjS3PwWk33ch6wJcmceRTE?sign=008ab998ce9844dfd8f0d11da3d31585&t=598b2218], Path[/storage/emulated/0/Android/data/com.caishi.cronus/files/auido_down/361687e73930dc406bef628720b9cb31] Listener[com.caishi.cronus.ui.audio.AudioDownUtils$1@4b9affb], Tag[361687e73930dc406bef628720b9cb31]
08-09 21:54:19.711 22863-25984/com.caishi.cronus V/FileDownloader.DownloadTaskHunter: the task[-883323028] has been into the launch pool.
08-09 21:54:19.713 22863-25986/com.caishi.cronus D/FileDownloader.FileDownloadMessenger: notify begin -883323028@com.liulishuo.filedownloader.DownloadTask@25333e2
08-09 21:54:19.713 22863-25986/com.caishi.cronus V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@a082373 by 11 
08-09 21:54:19.714 22863-25986/com.caishi.cronus V/FileDownloader.FileDownloadList: add list in all -883323028@com.liulishuo.filedownloader.DownloadTask@25333e2 11 1
08-09 21:54:19.734 22863-25990/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 1, but there isn't any running task in the upper layer
08-09 21:54:19.734 22863-25990/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 6, but there isn't any running task in the upper layer
08-09 21:54:51.896 22863-26444/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 2, but there isn't any running task in the upper layer
08-09 21:55:24.916 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.020 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.021 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.034 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.064 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.080 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.080 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.098 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.099 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.147 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.150 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.165 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.167 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.168 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.170 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.182 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.183 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.191 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.192 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.210 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.220 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.233 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.233 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.262 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.300 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.310 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.334 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.346 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.364 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.377 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.386 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.398 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.422 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.422 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.454 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.455 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.466 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.467 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.471 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.479 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.500 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.517 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.529 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.540 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.561 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.562 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.628 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.677 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.700 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.700 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.760 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.762 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.764 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.765 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.765 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.766 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.780 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.791 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.804 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.818 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.818 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.836 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.852 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.853 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.865 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.865 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.885 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.895 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.896 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.906 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.926 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.945 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.961 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.973 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:25.989 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:26.013 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:26.026 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:26.027 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:26.042 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:26.060 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:26.095 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:26.109 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:26.111 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:26.143 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:26.176 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:26.176 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:26.177 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:26.200 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:26.201 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:26.203 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:26.207 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:26.208 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:26.209 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:26.209 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:26.212 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.465 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.466 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.514 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.515 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.546 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.563 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.563 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.582 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.582 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.583 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.614 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.615 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.627 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.645 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.645 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.646 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.649 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.650 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.650 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.662 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.663 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.695 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.697 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.707 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.709 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.731 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.732 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.775 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.777 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.800 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.800 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.800 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.801 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.801 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.805 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.837 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.847 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.865 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.866 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.896 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.897 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.897 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.924 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.925 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.966 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.967 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.968 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.969 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.980 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.981 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:27.991 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:28.010 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:28.023 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:28.023 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:28.062 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:28.064 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:28.065 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:28.065 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:28.066 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:28.067 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:28.092 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:28.106 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:28.120 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:28.129 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:28.131 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:28.131 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event 3, but there isn't any running task in the upper layer
08-09 21:55:28.213 22863-26994/com.caishi.cronus I/FileDownloader.MessageSnapshotGate: Receive the event -3, but there isn't any running task in the upper layer

**Comment by layasntx** [comment]
ID算法：
public int generateId(String url, String path, boolean pathAsDirectory) {
                        return FileDownloadUtils.md5(path).hashCode();

**Comment by layasntx** [comment]
最后发现该文件下载完了，但是listener的一系列回调都没有被调用

**Comment by layasntx** [comment]
Receive the event 1，6，2，3....,-3，下载的几个状态都有，就是没有任何回调

**Comment by layasntx** [comment]
@Jacksgong

**Comment by kassadin** [comment]
@layasntx `Application.onCreate` 是不是有判断进程的代码

**Comment by rantianhua** [comment]
看日志输出的话，很可能还是因为 id 的前后不一致导致 `MessageSnapshotGate` 没有找到对应的 task 进行回调。 

---

为了便于排查出具体问题，请再提供下 `filedownloader` 进程的日志，如果真的是 id 的问题，那么从 `filedownloader` 的日志应该可以看出来。

--- 

另外希望提供下使用的  FileDownloader 的版本号
