### ISSUE TITLE
关于每一个下载对应一个FileDownloadConnectListener问个问题

### ISSUE THREAD

**Issue by 38017032** [lingochamp/FileDownloader#71]
写过类似的一个下载（我只是跑了跑你的Demo可能也不是类似的），我用一个Hashtable<Integer,Listener>存着一组下载和相对应的回调，下载的内容种类比较多，可能是视频，app，游戏等等。下载的状态也是用listener来更新。这样导致每次我进一个Activity的时候都需要人为的去为该Activity下载的内容设置分别一个Listener来随时的更新状态，每次onDestory的时候又需要把Hashtable中的Listener给remove掉。难道只能这么做吗？我看到你的TasksManagerDemoActivity（任务管理器案例）好像也是类似的。不知道是不是有更好的方法？

**Comment by HugoGresse** [comment]
Don't you think writing the issue in Enligh on an Open Source project worth it?

**Comment by Jacksgong** [comment]
@38017032 Ref #4 相信看看这个issue，可以直接解决你提到的问题。
