### ISSUE TITLE
如何设置为猪哥个文件下载，如何关闭并发下载

### ISSUE THREAD

**Issue by layasntx** [lingochamp/FileDownloader#717]
FileDownloader.setupOnApplicationOnCreate(this) # maxNetworkThreadCount(1)，
发现有两个任务在交替更新progress

**Comment by layasntx** [comment]
FileDownloader.getImpl().setMaxNetworkThreadCount(1)，也不行，还是有三个任务同时下载

**Comment by layasntx** [comment]
FileDownloadSerialQueue 
pause之后，enqueue 然后 resume ，崩溃了

**Comment by layasntx** [comment]
FileDownloadSerialQueue可以实现逐个下载，但是FileDownloadSerialQueue#pause之后，resume会崩，目前我的解决方案是，重新news了一个FileDownloadSerialQueue，再把task挨个enqueue。

**Comment by layasntx** [comment]
感觉FileDownloadSerialQueue的封装过于简单，也不能指定优先下载哪个，我只能第一个task加入队列之后延时100ms，enqueue其他task，但是这种实现依赖于网速，并不稳定。

**Comment by layasntx** [comment]
setCallbackProgressTimes设置为1000，似乎并不能稳定的每秒更新一次，网速慢的时候，好几秒才更新一次进度

**Comment by layasntx** [comment]
写错了，是setCallbackProgressMinInterval设置为1000，setCallbackProgressTimes没有设置

**Comment by layasntx** [comment]
setCallbackProgressMinInterval设置为1000，setCallbackProgressTimes设置为1000的时候，每秒都更新一次

**Comment by rantianhua** [comment]
请重新整理下你的信息，提供日志很重要，还有标题尽量不要写错别字。请整下后重新提个 issue 吧，这个先关掉了，谢谢！
