### ISSUE TITLE
Large file download error when pause and resume

### ISSUE THREAD

**Issue by xiangyutian** [lingochamp/FileDownloader#720]
用了最新的代码，在下载超过2G文件的时候，开始和暂停经常出现如下问题，已经添加了ConnectionCountAdapter并且设置为1
java.net.SocketException: Connection failed with code[416] on task[2063570806], which is changed after verify connection, so please try again.

**Comment by Jacksgong** [comment]
如果是单线程下载`ConnectionCountAdapter`设置为1，是不可能出现这个问题的，你检查下看看你是否有正确注册进（默认FileDownloadService是在独立进程的，因此如果在主进程动态修改线程数是无效的）。

---

你是用的哪个版本？

这个错误是因为，第一个建连检测是否允许分块下载，返回是允许的。然后开始分块下载的时候建连返回了416（range不匹配）：

只有存在两个可能:

1. 服务端那边对range处理有问题，给了range服务端那边误判了range存在问题
2. 客户端这边的代码有问题，给错了range导致。

---

#### 1. 针对服务端range处理有问题这个

- 建议联系后端同学确认。
- FileDownloader这边后面的版本会考虑这种转为单线程下载进行尝试。

#### 2. 针对客户端这边有问题

复现该问题，并且提供下下载进程与与主进程的日志，我看看是否是客户端问题（可能性较低）。

**Comment by Jacksgong** [comment]
多谢反馈，这个确实是一个BUG，关注这个Issue: #737
