### ISSUE TITLE
切换网络（从WIFI到移动网络）后再次下载只能从头下载？

### ISSUE THREAD

**Issue by sczhonghua** [lingochamp/FileDownloader#721]
切换网络（从WIFI到移动网络）后再次下载只能从头下载？这是设计如此吗？还是有什么技术上的问题？
如果只是断开连接再次连接相同的网络则能够继续下载

**Comment by JM0425** [comment]
同问！

**Comment by Jacksgong** [comment]
不是的，如果原本支持断点续传，网络断开以后，重新连上网络，重启启动任务，自动断点续传。

具体可以clone demo project下来在单任务测试中 进行测试，我刚刚测试没有问题。

**Comment by JarvisGG** [comment]
我也遇到了
