### ISSUE TITLE
forcing the links that not accept multi connection with many connection

### ISSUE THREAD

**Issue by hassan379** [lingochamp/FileDownloader#724]
i am trying the same links on other application like ADM app which support multi connection and it works fine and it gives me full speed
but some links only allow 1 connection at time by using this library
is there any way to force the downloading to make many connection by some way
thx again for this great library

**Comment by Jacksgong** [comment]
You can custom your own `ConnectionCountAdapter` to achieve that ref [here](https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component).
