### ISSUE TITLE
How can i set file format

### ISSUE THREAD

**Issue by alphaDroid89** [lingochamp/FileDownloader#725]
HI,

I have tried to download two different file formats 1. Zip 2. PNG.  Both files downloaded with out their extensions. Can you please guide me how can I set the custom name for the downloading file with its extension. 

Thanks in Advance.

**Comment by Jacksgong** [comment]
on the current version, the simplest way is remain the response recommend file name as the name of the file:

```java
/**
 * @param path            The absolute path for saving the download file.
 * @param pathAsDirectory {@code true}: if the {@code path} is absolute directory to store the
 *                        downloading file, and the {@code filename} will be found in
 *                        contentDisposition from the response as default, if can't find
 *                        contentDisposition,the {@code filename} will be generated by
 *                        {@link FileDownloadUtils#generateFileName(String)}  with {@code url}.
 *                        </p>
 *                        {@code false}: if the {@code path} = (absolute directory/filename).
 * @see #isPathAsDirectory()
 * @see #getFilename()
 */
BaseDownloadTask setPath(final String path, final boolean pathAsDirectory);
```

so you just need set `setPath(path, true)`, we will using the file name from the response header if it's provided.

after that, when the file is completed download, you will know the file extension from its name, and you can rename it to what you like.

---

If you want to get `Content-Type` on the response header or some others on response header, please follow this issue: #586, we will implement it later on, and welcome PR also.

**Comment by alphaDroid89** [comment]
@Jacksgong 

is this correct?

 @Override
            protected void connected(BaseDownloadTask task, String etag, boolean isContinue, int soFarBytes, int totalBytes) {
                super.connected(task, etag, isContinue, soFarBytes, totalBytes);
                task.setPath(getImageSaveBaseDir() + "/myImages.zip",true);
            }
