### ISSUE TITLE
大佬...问个关于下载的奇怪的问题!

### ISSUE THREAD

**Issue by asdf19910719** [lingochamp/FileDownloader#728]
我使用这个FileDonwloader下载文件,发现大多数情况下是好的,但是有少部分客户下载的文件正常应该10M,下载下来是2KB,而且很奇怪的是开始下载后并没有报错直接跳转到了completed回调里...这是啥原因

**Comment by Ernest-su** [comment]
是不是路由器被劫持，下载下来的是一个html页面的内容。我以前遇到过这种情况。

**Comment by Jacksgong** [comment]
@asdf19910719 你看看文件内容是什么？

**Comment by asdf19910719** [comment]
嗯嗯..最终,那个客户回家就能正常下载了.估计就像你们说的他们公司的网有问题,感谢两位大佬的解答(*^__^*)

**Comment by Jacksgong** [comment]
okay.
