### ISSUE TITLE
403错误，没有回调

### ISSUE THREAD

**Issue by layasntx** [lingochamp/FileDownloader#729]
日志如下：
08-16 16:44:18.488 11667-14088/com.caishi.cronus D/FileDownloader.FileDownloadMessenger: notify begin 314732264@com.liulishuo.filedownloader.DownloadTask@67c13e2
08-16 16:44:18.492 11667-14088/com.caishi.cronus V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@b22ea9 by 11 
08-16 16:44:18.494 11667-14088/com.caishi.cronus V/FileDownloader.FileDownloadList: add list in all 314732264@com.liulishuo.filedownloader.DownloadTask@67c13e2 11 1
08-16 16:44:18.515 11667-14091/com.caishi.cronus D/FileDownloader.MessageSnapshotGate: ~~~callback 314732264 old[11] new[1] 1
08-16 16:44:18.515 11667-14091/com.caishi.cronus D/FileDownloader.FileDownloadMessenger: notify pending 314732264@com.liulishuo.filedownloader.DownloadTask@67c13e2
08-16 16:44:18.515 11667-14091/com.caishi.cronus D/FileDownloader.MessageSnapshotGate: ~~~callback 314732264 old[1] new[6] 1
08-16 16:44:18.515 11667-14091/com.caishi.cronus D/FileDownloader.FileDownloadMessenger: notify started 314732264@com.liulishuo.filedownloader.DownloadTask@67c13e2
08-16 16:44:19.035 11667-14091/com.caishi.cronus D/FileDownloader.MessageSnapshotGate: ~~~callback 314732264 old[6] new[5] 1
08-16 16:44:19.036 11667-14091/com.caishi.cronus D/FileDownloader.FileDownloadMessenger: notify retry 314732264@com.liulishuo.filedownloader.DownloadTask@67c13e2 1 1 com.liulishuo.filedownloader.exception.FileDownloadHttpException: response code error: 403, 
                                                                                          request headers: {If-Match=["lgQZ7P-pkvqodI3W4E_CT2L-MgXa"], Range=[bytes=435848-], Referer=[api.5wuli.com], X-Tingyun-Processed=[true]} 
                                                                                          response headers: {null=[HTTP/1.1 403 Forbidden], Content-Type=[application/octet-stream], Date=[Wed, 16 Aug 2017 08:44:18 GMT], Proxy-Connection=[Keep-alive], Server=[marco/1.6], Transfer-Encoding=[chunked], Via=[M.ctn-sd-tna-172], X-Android-Received-Millis=[1502873058967], X-Android-Response-Source=[NETWORK 403], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1502873058546], X-Request-Id=[97862e175e5a186e234134ed46ba74b6]}
08-16 16:44:19.222 11667-14091/com.caishi.cronus D/FileDownloader.MessageSnapshotGate: ~~~callback 314732264 old[5] new[-1] 1
08-16 16:44:19.222 11667-14091/com.caishi.cronus V/FileDownloader.FileDownloadList: remove 314732264@com.liulishuo.filedownloader.DownloadTask@67c13e2 left -1 0
08-16 16:44:19.222 11667-14091/com.caishi.cronus D/FileDownloader.FileDownloadMessenger: notify error 314732264@com.liulishuo.filedownloader.DownloadTask@67c13e2 com.liulishuo.filedownloader.exception.FileDownloadHttpException: response code error: 403, 
                                                                                          request headers: {If-Match=["lgQZ7P-pkvqodI3W4E_CT2L-MgXa"], Range=[bytes=435848-], Referer=[api.5wuli.com], X-Tingyun-Processed=[true]} 
                                                                                          response headers: {null=[HTTP/1.1 403 Forbidden], Content-Type=[application/octet-stream], Date=[Wed, 16 Aug 2017 08:44:18 GMT], Proxy-Connection=[Keep-alive], Server=[marco/1.6], Transfer-Encoding=[chunked], Via=[M.ctn-sd-tna-172], X-Android-Received-Millis=[1502873059186], X-Android-Response-Source=[NETWORK 403], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1502873059041], X-Request-Id=[0804f5fd09f6be7f816d1f812e13e679]}
08-16 16:44:19.223 11667-14091/com.caishi.cronus V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@b22ea9 by -1

**Comment by Allyns** [comment]
I am using the 1.7.5 version, and I added it after seeing the prompt `        BaseDownloadTask task = FileDownloader.getImpl().create(model.getUrl())
                .addHeader("User-Agent", System.getProperty("http.agent"))
                .setPath(FileDownloadUtils.generateFilePath(FileDownloadUtils.getDefaultSaveRootPath(), model.getName()))
                .setListener(listener);
        task.setTag(model);
        task.start();`  ; but I still prompted 403 Forbidden; why is this?

**Comment by rantianhua** [comment]
看日志是已经回调了：
```
D/FileDownloader.FileDownloadMessenger: notify error 314732264@com.liulishuo.filedownloader.DownloadTask@67c13e2 
```
所以希望再描述下你的问题？

**Comment by rantianhua** [comment]
长时间未回复，先关闭了。

**Comment by Seachal** [comment]
对我来说， 第一个版本服务端没有对文件下载进行鉴权限制，可以正常下载，第二个版本，服务端开始改造增加鉴权，对已经调用过一次的下载链接进行失效处理，我这边就会遇到下面这样的异常， 
 ```
ava.net.SocketException: Connection failed with request[{Range=[bytes=4073926-8147851], User-Agent=[FileDownloader/1.7.7]}] response[{null=[HTTP/1.1 403 Forbidden], Access-Control-Allow-Methods=[GET], Access-Control-Allow-Origin=[*], Connection=[keep-alive], Content-Length=[238], Content-Type=[text/html], Date=[Mon, 29 Jan 2024 02:42:16 GMT], EagleId=[907b1f2217064961368347077e], Server=[Tengine], Timing-Allow-Origin=[*], Via=[cache14.cn1306[,0]], X-Android-Received-Millis=[1706496136376], X-Android-Response-Source=[NETWORK 403], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1706496136196]}] http-state[403] on task[-891346639-1], which is changed after verify connection, so please try again.   
```
最终发现是因为 下载库默认开启断点续传。
<img width="1058" alt="image" src="https://github.com/lingochamp/FileDownloader/assets/14776606/9e08f13e-211b-4e71-b8d3-70254f42e00d">


> Range 是一个请求首部，告知服务器返回文件的哪一部分。在一个 Range 首部中，可以一次性请求多个部分，服务器会以 multipart 文件的形式将其返回。如果服务器返回的是范围响应，需要使用 [206](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/206) Partial Content 状态码。假如所请求的范围不合法，那么服务器会返回 [416](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/416) Range Not Satisfiable 状态码，表示客户端错误。服务器允许忽略 Range 首部，从而返回整个文件，状态码用 [200](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/200) 。

所以我这边的情况是，服务端做修改适配客户端的断点续传，客户端不需要修改。
