### ISSUE TITLE
一组任务可以共享progress吗

### ISSUE THREAD

**Issue by marscl** [lingochamp/FileDownloader#731]

**Comment by Jacksgong** [comment]
#### 理论可以实现

在开始下载之前，阻塞住所有任务的开始，先为所有任务发送一个请求，分别获取到每个任务的文件长度，等到所有文件的文件大小拿到以后，再开始所有文件下载。

#### 但是目前没有支持

也许未来会考虑实现，但是这个是一个比较奇怪的需求，一般来说打包下载: 直接在服务端打包好所有的资源，然后进行下载。

#### 基于现在的库替代方案？

1. 在开始下载之前通过一个请求获取所有要下载的文件大小，然后在通过FileDownloader进行并行下载，上层根据每个文件的进度计算出总进度。
2. 根据已经下载完成的任务个数来计算粗略的进度，比如要下载100个任务，为每个任务注册`FinishListener`，下载完成一个文件1/100，下载完成两个文件2/100，以此类推。
