### ISSUE TITLE
请问我想实现多线程分段下载如何处理，就是多线程下载一个文件

### ISSUE THREAD

**Issue by a823875383** [lingochamp/FileDownloader#732]

**Comment by Jacksgong** [comment]
1.5.0版本之后就支持了，参考[这里](https://github.com/lingochamp/FileDownloader/issues/102)

如果需要定制不同文件所使用的连接数，可以自行定制[ConnectionCountAdapter](https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component)
