### ISSUE TITLE
使用DefaultConnectionCountAdapter 在下载即将结束的时候反复点击 开始 暂停 ，断点续传Range 范围传递错误

### ISSUE THREAD

**Issue by sd6352051** [lingochamp/FileDownloader#733]
使用版本 v1.6.3
使用默认 DefaultConnectionCountAdapter 
在接近下载结束时 反复暂停开始 会复现这个错误

#FileDownloader.FileDownloadMessenger: notify error 735613160@com.liulishuo.filedownloader.DownloadTask@3527784e java.net.SocketException: Connection failed with code[416] on task[735613160], which is changed after verify connection, so please try again

**Comment by sd6352051** [comment]
我使用ConnectionCountAdapter return 1 之后 使用单线程 会解决上面的问题 不会再返回错误信息

但当下载到即将100%的时候  返回信息如下
HTTP/1.1 206 Partial Content
Server: TWS/1.2
Date: Fri, 18 Aug 2017 02:52:22 GMT
Content-Type: application/zip
Content-Length: 11807183
Last-Modified: Thu, 10 Aug 2017 03:35:21 GMT
Connection: keep-alive
Content-Range: bytes 0-11807182/11807183

Content-Range即将到达百分之百
这个时候暂停下载 ，然后再次开始下载 
断点续传的Range会从0开始    
Range: bytes=0-     

导致会重新下载

**Comment by sd6352051** [comment]
当ConnectionCountAdapter return 为 1，  在即将下载完成的时候暂停,在回调中获取到的当前进度和总进度如下：
sofar:11727104,total:11807183

但抓包看到的服务器返回值是 
Content-Range: bytes 0-11807182/11807183

之后再次启动下载就会 重新下载

**Comment by sd6352051** [comment]
测试了demo 中的 TasksManagerDemoActivity     也会出现此问题   Range有误

**Comment by Jacksgong** [comment]
多谢反馈，这个确实是一个BUG，关注这个Issue: #737

**Comment by sd6352051** [comment]
好的，谢谢，期待你的新版本
