### ISSUE TITLE
出现下载不动，不回调的问题

### ISSUE THREAD

**Issue by qibin0506** [lingochamp/FileDownloader#735]
我这里设置了超时， 还是可能会出现下载不动，不回调的问题。
设置超时的方法：
``` java
 FileDownloader.setupOnApplicationOnCreate(this)
                .connectionCreator(new FileDownloadUrlConnection
                        .Creator(new FileDownloadUrlConnection.Configuration()
                        .connectTimeout(25_000) // set connection timeout.
                        .readTimeout(25_000) // set read timeout.
                        .proxy(Proxy.NO_PROXY) // set proxy
                ))
                .commit();
```

基本描述： 我是在服务里进行多文件并行下载的。

**Comment by stanhe** [comment]
同样遇到这个问题，一起下载多个文件出现下载不动的问题，需重新点击parse start

**Comment by qibin0506** [comment]
@stanhe 你的有什么日志吗？

**Comment by stanhe** [comment]
@qibin0506 没有
并且经常出现  停止不动后点击“暂停”“开始”并不继续下载的情况，就是完全卡死，只能删除任务。

**Comment by qibin0506** [comment]
@stanhe 你的解决方案是什么？

**Comment by stanhe** [comment]
@qibin0506 
maxNetworkThreadCount(2)，然而还是会大概率出现第一个下载线程下载一段时间后无故停止，但第二个下载线程能正确运行。so ~

**Comment by Jacksgong** [comment]
我无法复现，可否打开`FileDownloadLog.NEED_LOG`，然后贴下主进程与下载进程的Logcat，便于定位问题。

**Comment by qibin0506** [comment]
这是我的日志：

08-22 15:42:49.743 2428-2677/com.haiersmart.sfnation:ota V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@12226972 by -1 
08-22 15:42:50.041 2612-2673/com.haiersmart.sfnation:filedownloader D/FileDownloader.FetchDataTask: require sync id[1578382381] index[4] offset[100403638], consume[80]
08-22 15:42:51.489 2612-2672/com.haiersmart.sfnation:filedownloader D/FileDownloader.FetchDataTask: require sync id[1578382381] index[3] offset[80950594], consume[60]
08-22 15:42:51.756 2428-2428/com.haiersmart.sfnation:ota D/FileDownloader.DownloadTask: setPath /storage/emulated/0/haier/sfnation/download/ota/BXN_401_0291_0006.apk
08-22 15:42:51.756 2428-2428/com.haiersmart.sfnation:ota D/FileDownloader.DownloadTask: setTag com.haiersmart.ota.bean.ApkInfo@3512d11a
08-22 15:42:51.757 2428-2428/com.haiersmart.sfnation:ota D/FileDownloader.DownloadTask: setListener com.haiersmart.ota.OTAService$3@3ec73088
08-22 15:42:51.758 2428-2428/com.haiersmart.sfnation:ota D/FileDownloader.InQueueTaskImpl: add the task[1578382381] to the queue
08-22 15:42:51.758 2428-2428/com.haiersmart.sfnation:ota V/FileDownloader.FileDownloadList: add list in all 1578382381@com.liulishuo.filedownloader.DownloadTask@3cc94a21 0 1
08-22 15:42:51.758 2428-2428/com.haiersmart.sfnation:ota V/FileDownloader.FileDownloader: start list attachKey[1053241480] size[1] listener[com.haiersmart.ota.OTAService$3@3ec73088] isSerial[FALSE]
08-22 15:42:51.759 2428-2428/com.haiersmart.sfnation:ota V/FileDownloader.DownloadTaskHunter: call start Url[http://filedisk1.oss-cn-beijing.aliyuncs.com/OTA/BXN_401_0291_0006.apk], Path[/storage/emulated/0/haier/sfnation/download/ota/BXN_401_0291_0006.apk] Listener[com.haiersmart.ota.OTAService$3@3ec73088], Tag[com.haiersmart.ota.bean.ApkInfo@3512d11a]
08-22 15:42:51.761 2428-2428/com.haiersmart.sfnation:ota V/FileDownloader.DownloadTaskHunter: the task[1578382381] has been into the launch pool.
08-22 15:42:51.762 2428-2678/com.haiersmart.sfnation:ota D/FileDownloader.FileDownloadMessenger: notify begin 1578382381@com.liulishuo.filedownloader.DownloadTask@3cc94a21
08-22 15:42:51.762 2428-2678/com.haiersmart.sfnation:ota V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@3e55807 by 11 
08-22 15:42:51.763 2612-2632/com.haiersmart.sfnation:filedownloader D/FileDownloader.FileDownloadManager: request start the task with url(http://filedisk1.oss-cn-beijing.aliyuncs.com/OTA/BXN_401_0291_0006.apk) path(/storage/emulated/0/haier/sfnation/download/ota/BXN_401_0291_0006.apk) isDirectory(FALSE)
08-22 15:42:51.765 2612-2632/com.haiersmart.sfnation:filedownloader D/FileDownloader.FileDownloadManager: has already started download 1578382381
08-22 15:42:51.766 2428-2677/com.haiersmart.sfnation:ota D/FileDownloader.MessageSnapshotGate: ~~~callback 1578382381 old[11] new[-4] 1
08-22 15:42:51.767 2428-2677/com.haiersmart.sfnation:ota W/FileDownloader.DownloadTaskHunter: warn, but no mListener to receive, switch to pending 1578382381 3
08-22 15:42:51.767 2428-2677/com.haiersmart.sfnation:ota D/FileDownloader.FileDownloadMessenger: notify pending 1578382381@com.liulishuo.filedownloader.DownloadTask@3cc94a21
08-22 15:42:52.621 2612-2671/com.haiersmart.sfnation:filedownloader D/FileDownloader.FetchDataTask: require sync id[1578382381] index[2] offset[55117097], consume[63]
08-22 15:42:52.757 2612-2671/com.haiersmart.sfnation:filedownloader D/FileDownloader.FetchDataTask: require sync id[1578382381] index[2] offset[55117097], consume[32]
08-22 15:42:52.760 2612-2664/com.haiersmart.sfnation:filedownloader D/FileDownloader.DownloadLaunchRunnable: finish sub-task for [1578382381] TRUE FALSE
08-22 15:42:52.762 2612-2664/com.haiersmart.sfnation:filedownloader D/FileDownloader.DownloadLaunchRunnable: finish sub-task for [1578382381] TRUE FALSE
08-22 15:42:52.763 2612-2664/com.haiersmart.sfnation:filedownloader D/FileDownloader.DownloadLaunchRunnable: finish sub-task for [1578382381] TRUE FALSE
08-22 15:42:52.764 2612-2664/com.haiersmart.sfnation:filedownloader D/FileDownloader.DownloadLaunchRunnable: finish sub-task for [1578382381] TRUE FALSE
08-22 15:42:52.765 2612-2664/com.haiersmart.sfnation:filedownloader D/FileDownloader.DownloadLaunchRunnable: finish sub-task for [1578382381] TRUE FALSE

**Comment by Jacksgong** [comment]
@qibin0506 用的是哪个版本的FileDownloader？

**Comment by qibin0506** [comment]
1.6.2

**Comment by Jacksgong** [comment]
@qibin0506 你这个日志并不完整，但是从有限的日志中，可以看到的是:

```
W/FileDownloader.DownloadTaskHunter: warn, but no mListener to receive, switch to pending 1578382381 3
```

这个表明的是，队列中已经有一个完全相同的任务在运行了，又启动了相同的任务，因此准备为又启动的任务回调`warn`，但是却发现主进程的队列中却只有一个任务？，因此将`warn`转为`pending`，保证仅有的这个任务能够收到监听，这种情况只存在以下场景:

1. 下载进程存在，但是主进程被杀，导致主进程中队列的数据都被清了，此时用户又启动了该任务，这个时候下载自动将所有的回调推给新进来的任务
2. 上层主动修改了`FileDownloadList`这个情况FileDownloader是不会覆盖的，我们的demo中有任务管理的案例，并且不希望上层对`FileDownloadList`中的数据进行修改等操作，如果上层要做相关操作，请自行覆盖相关case。

**Comment by qibin0506** [comment]
“但是却发现主进程的队列中却只有一个任务” 这句话中的这个任务是说的准备warn的那个任务吗？

**Comment by qibin0506** [comment]
@Jacksgong 我是这样的场景， 多任务进行下载， 当全部完毕后检查是否有失败的情况，如果有失败的，则重新过滤失败的列表，然后重试下载， 不知道，这样是否会出现上面场景2的情况

**Comment by Jacksgong** [comment]
> 则重新过滤失败的列表

这个是具体操作是什么？有涉及到修改`FileDownloadList`吗？

**Comment by qibin0506** [comment]
@Jacksgong  我每次都会重新new出一个FileDownloadQueueSet来，不知道这会不会修改FileDownloadList

**Comment by Jacksgong** [comment]
@qibin0506 这个不会影响。

为了进一步定位问题，建议你clone demo下来看看，然后在demo上面修改代码复现你的问题，这样如果能够复现的，提供复现步骤，将代码给我，我给你看看。

**Comment by qibin0506** [comment]
@Jacksgong  我这里不太好复现，要好几天才能复现一次， 并不是每一次都能出现。

**Comment by qibin0506** [comment]
或者说，有什么情况下载任务的操作？ 我在重试之前，将所有任务先清空一下。

**Comment by Jacksgong** [comment]
@qibin0506 根据你上面的日志，只能分析出刚刚说的这个 https://github.com/lingochamp/FileDownloader/issues/735#issuecomment-324519680 情况，你可以对应你的应用场景思考下，如果没有进一步的进度，希望下次遇到该问题，提供尽可能完整的日志。

---

我不是很清楚的是，你为什么要清空?过滤FileDownloader，你只要`pause`不就行了？。你说所的清空/过滤是什么意思？

**Comment by qibin0506** [comment]
我的意思是， 既然可能是出现了重复任务， 那我再开始之前 清空一下任务列表， 然后重新添加新的任务列表不就不会出现这个问题了。

**Comment by Jacksgong** [comment]
重复任务，你会收到一个`warn`，不会影响任务运行，为什么需要清空任务列表，FileDownloader本身并没有提供清空任务列表的功能，可否提供下与FileDownloader相关的清空任务列表/过滤的代码逻辑？

**Comment by qibin0506** [comment]
收到warn不会停止下载？
但是 wiki上这么一句话：“可能会遇到以下回调而直接终止整个下载过程:paused / completed / error / warn”，不知道怎么理解

**Comment by Jacksgong** [comment]
`可能会遇到以下回调而直接终止整个下载过程:paused / completed / error / warn`，这个是对于当前任务而言的，当前任务收到`warn`以后，确实是不会再收到任何回调了，完成整个回流。

收到`warn`是因为已经有一个相同的任务在下载了，因此收到`warn`的这个回调的任务实例完成了整个下载过程（不会有进一步的回调)，但是另外一个相同的任务会继续下载，继续收到下载进度回调不受该影响。

**Comment by qibin0506** [comment]
我知道原因了，不过，我在warn里打印了日志
"listen warn, task xxx, etag is null, warn cause is none"
这是什么原因？ warn cause是打印的Throwable的message。

**Comment by qibin0506** [comment]
@Jacksgong 在调用warn之前最后一次失败， 我在error里打印的message都有值， 只有这个下次会出现warn的下载任务error信息是null， 是不是当异常为null时，下载服务没有将该task移除？

**Comment by qibin0506** [comment]
@Jacksgong 

D/FileDownloader.DownloadStatusCallback: require callback -1 but the host thread of the flow has already dead, what is occurred because of there are several reason can final this flow on different thread.

这是什么原因？ 主线程死了？

**Comment by Jacksgong** [comment]
.......... 怎么看你的情况这么奇怪。你居然能够遇到这些问题，可否遇到问题以后，如果自己能找到原因，欢迎PR，如果不能，希望提交一份完整的日志，这样也好定位问题。

---

也欢迎clone demo project，里面的测试一直交错点击线性下载与并行下载，每次都是860多个任务一起启动，每次都已经测试过几千个任务稳定执行完成才上线，可否也clone下载看看，是否本地编写存在问题。

---

你所说的，这些回调有序性，稳定性是FileDownloader本身就一直追求的，里面有大量的逻辑都是保证这一块，包括各类进程出现异常。

**Comment by qibin0506** [comment]
已解决， 出现问题的点：1. 某个任务莫名其妙的warn了， 2. 某个人物pending后不start。
解决版本： 对于warn的任务进行暂停操作， 然后另建任务进行，对于pending不start的操作，pending后延迟操作判断是否start，如果没start，直接调用warn，走warn的流程。
