### ISSUE TITLE
getSofar(downloadId)得到0

### ISSUE THREAD

**Issue by ZhangQixiangChina** [lingochamp/FileDownloader#736]
下载一半退出应用(清除后台),再次进入应用的时候想知道之前的下载进度
但是通过`getSoFar(downloadId)` 和 `getSmallFileSoFarBytes()`得到的结果都是0

**Comment by rantianhua** [comment]
`getSoFar(downloadId)` 以及 `getSmallFileSoFarBytes()` 在下载过程中或者 Service 已经连上的时候才会有效。
