### ISSUE TITLE
下载还是存在416错误

### ISSUE THREAD

**Issue by ZY9898** [lingochamp/FileDownloader#739]
你好，我已经更新到1.6.4版本了，但是我从测试服务器的数据切换到正式服务器后，下载还是会报416错误。但是把链接放浏览器或者使用httpurlconnection原生下载则没问题。请问这是什么原因？

**Comment by Jacksgong** [comment]
416不一定是本地问题，请贴出相关日志，证明本地给过去的Range是错误的Range。

**Comment by Jacksgong** [comment]
或者参考这个Issue: https://github.com/lingochamp/FileDownloader/issues/737#issuecomment-323637927 给出这些日志。

**Comment by Jacksgong** [comment]
如果你不知道如何获得下载进程的logcat，可以先通过[filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)将下载服务运行在主进程，然后给过来主进程的日志即可。

**Comment by Jacksgong** [comment]
至于: `浏览器或者使用httpurlconnection原生下载则没问题`:  原因是他们没有分块下载，因此你的服务器很少有触及到分块给数据的case。

**Comment by Jacksgong** [comment]
根据你在这个Issue中的回复: https://github.com/lingochamp/FileDownloader/issues/737#issuecomment-323901754

---

```
D/FileDownloader.ConnectTask: 547991145 request header {Range=[bytes=2257205-4514409]}
D/FileDownloader.ConnectTask: 547991145 request header {Range=[bytes=4514410-]}
D/FileDownloader.ConnectTask: 547991145 request header {Range=[bytes=0-2257204]}
D/FileDownloader.DownloadRunnable: the connection[1] for 547991145, is connected range[2257205, 4514409) current offset[2257205] with code[416]
D/FileDownloader.DownloadRunnable: the connection[0] for 547991145, is connected range[0, 2257204) current offset[0] with code[206]
```

> P.S. 我上面提到的是分块下载不是断点续传。

---

根据日志:

```
D/FileDownloader.DownloadRunnable: the connection[1] for 547991145, is connected range[2257205, 4514409) current offset[2257205] with code[416] 
```

这里的`range[2257205, 4514409)`是没有问题的，应该是你的后端的问题，咨询你的后端工程师，为什么说这里的range有问题。

#### 为什么说是后端BUG?

1. 在检验资源时，后端返回的是206，说明该资源支持指定`range`下载
2. 但是在分块下载时，指定了正确的`range[2257205, 4514409)`(具体的请求头与返回头已经在错误信息中带回可自行查看），但是后台却返回了416（range不满足)

#### 后端可能存在什么BUG应该如何修复?

1. 本身对指定区间不支持  -- 如果是这个问题，便不应该返回206，让该资源始终从头开始下载
2. 本身对起始值不为0的分块不支持 -- 那么说明区间下载支持不完全，也不应该返回206

#### 如果你们后端工程师不修复该BUG怎么办

针对于本身对起始值不为0的分块不支持的，并且后端又返回206的，可以通过FileDownloder定制为非分块下载，可以参考[ConnectionCountAdapter](https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component)定制非分块下载。
