### ISSUE TITLE
downloadId 是否会产生hash碰撞?

### ISSUE THREAD

**Issue by xns1001** [lingochamp/FileDownloader#74]
downloadId是通过取md5值后再hash得到的,但是可能会有同一个的downloadId的不同任务的。是这种hash碰撞的概率可以忽略吗?

**Comment by Jacksgong** [comment]
> 参考这边的计算结果: [Hash算法的碰撞概率](http://www.freezhongzi.info/?p=100)

:100: 谢谢你的细心。

目前我们是32位的hash，也就是说同时存在 `77161` 个 `downloadId` 之后，再增加一个下载，出现`downloadId` 碰撞的概率会到50%。目前我们的 `downloadId` 也会根据本地文件是否存在，是否有效自我维护，自我清除(在每次 **FileDownloader进程启动的时候** )，目前来说这个应该还不是 FileDownloader的瓶颈。

不过这个肯定是以后不断迭代需要面对的问题。

**Comment by Jacksgong** [comment]
This has been covered on [okdownload](https://github.com/lingochamp/okdownload).
