### ISSUE TITLE
下载完安装，一直报解析包错误

### ISSUE THREAD

**Issue by JarvisGG** [lingochamp/FileDownloader#745]
#### Before Issue

1. Please search on the [Issues](https://github.com/lingochamp/FileDownloader/issues)
2. Please search on the [wiki](https://github.com/lingochamp/FileDownloader/wiki)
3. Please set `FileDownloadLog.NEED_LOG=true` and review the Logcat output from main process and `:filedownloader` process ( pay attention to Warn and Error level logcat)

#### Issue

1. What problem do you get?
2. Which version of FileDownloader are you using when you produce such problem?
3. How to reproduce such problem?
4. Do you set `FileDownloadLog.NEED_LOG=true`?
5. Could you please reproduce this problem and provide all main process and `:filedownloader` process logcat on here:

```
```

>P.S. If you don't know how to get `:filedownloader` process, it's recommended to using `pidcat` to just filter all your application logcat, or define `process.non-separate=true` on [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)

**Comment by JarvisGG** [comment]
很着急

**Comment by Jacksgong** [comment]
1. FileDownloader本身有在下载完成的时候对需要下载的文件大小进行较验，如果文件大小与响应头给的大小不一致会抛`error`，因此如果下载完成文件大小肯定是对的。
2. 在`blockComplete`中可以做一些md5校验之类的。

---

#### 进一步 

你可以把下载下来的文件，进行md5校验，或者是拷贝到电脑看看有什么问题。与服务端下发的有什么差别。

**Comment by JarvisGG** [comment]
我是下载的apk，然后就下载完点击安装，就一直报解析包错误，然后我就打log看了一下，发现总是最后差一点点

**Comment by JarvisGG** [comment]
方便的话，可以加下Q吗？真的很着急

**Comment by Jacksgong** [comment]
这边只要回调`completed`肯定是与后端给过来的文件大小是一致的，如果你发现本地文件在`completed`以后，还差一点点，咨询下后台同学，是否给过来的`content-length`本来就少了一点点?

**Comment by JarvisGG** [comment]
你好，我这边发现了根本原因不是下载不全造成的，我打印了一下File.length，没问题。问题出在我是下载到data/data/<package name>/files 这个路径下的，然后直接安装这个，就报解析包错误

**Comment by Jacksgong** [comment]
那你比对下电脑下载的与FileDownloader下载的文件的md5
