### ISSUE TITLE
请问能不能多个多任务并发下载？

### ISSUE THREAD

**Issue by Godsbox** [lingochamp/FileDownloader#748]
1. 一个下载任务是，其中包含了多个下载文件，并且是并发
2. 我开启第二个的时候，发现并没有马上开始，而是pengding
3. 我只能等我的那个多任务的并发的下载完才可以开始第二的下载吗？

**Comment by rantianhua** [comment]
第一个问题没看懂，什么叫一个下载任务包含多个下载文件，一个下载文件不就是一个下载任务吗？多个下载文件的话不就是多个下载任务吗？

---

每个 Task 都会有个短暂的 pending 状态，这是正常的。

---

并没有，FileDownloader 可以同时下载多个任务。
