### ISSUE TITLE
关于这个项目怎么学习

### ISSUE THREAD

**Issue by baoyachi** [lingochamp/FileDownloader#75]
你好，谢谢你的开源项目，在项目中使用了你的FileDownloader，极大简化了开发进度！我现在想学学你代码思想，看的源码有点复杂，能给个这个学习的教程吗，我觉得这个开源项目写的太牛逼了，我想参考学学

**Comment by Jacksgong** [comment]
谢谢~ 

我之前有粗略话画了一个回调图，你可以看下:

![](https://raw.githubusercontent.com/lingochamp/FileDownloader/master/art/filedownload_sample_description.png)

---

> 这个组件其实还有很多需要优化的地方，我这周末会进行新一轮迭代。(P.S：最近有些忙，迭代没有跟上Zzzzz.)。

**Comment by baoyachi** [comment]
谢谢啊，我以为大神会忽略我这个issue了呢？因为用了FileDownload,省了太多事了，用的很方便，舒服，就想看看源码！谢谢指导！

**Comment by Jacksgong** [comment]
:100: 屌屌地。

**Comment by yanbin92** [comment]
mark
