### ISSUE TITLE
Could not find method android.os.StatFs.getAvailableBytes, referenced from method com.liulishuo.filedownloader.util.FileDownloadUtils.getFreeSpaceBytes

### ISSUE THREAD

**Issue by a8469758** [lingochamp/FileDownloader#750]
Could not find method android.os.StatFs.getAvailableBytes, referenced from method com.liulishuo.filedownloader.util.FileDownloadUtils.getFreeSpaceBytes

**Comment by a8469758** [comment]
重启修复好了，但是还是不能下载，有太多bug了，继续加油

**Comment by Jacksgong** [comment]
什么bug?

**Comment by Jacksgong** [comment]
这个Api在 Api level 1就已经带上 : 

![image](https://user-images.githubusercontent.com/6176417/29864363-05d3fcc2-8da5-11e7-933b-7706d65c2c35.png)

**Comment by Jacksgong** [comment]
@a8469758 有问题其实十分欢迎提PR的。

很多Issue都是文档或者wiki，或者Logcat里面都有输出的。

希望一起将FileDownloader维护的更加稳定吧。
