### ISSUE TITLE
一个会导致文件重新下载的异常

### ISSUE THREAD

**Issue by BigExcalibur** [lingochamp/FileDownloader#753]
09-01 09:13:38.916 7683-18798/:filedownloader W/System.err:     at java.io.FileDescriptor.sync(FileDescriptor.java:77)
09-01 09:13:38.916 7683-18798/:filedownloader W/System.err:     at com.liulishuo.filedownloader.stream.FileDownloadRandomAccessFile.sync(FileDownloadRandomAccessFile.java:44)
09-01 09:13:38.917 7683-18798/:filedownloader W/System.err:     at com.liulishuo.filedownloader.download.FetchDataTask.sync(FetchDataTask.java:210)
09-01 09:13:38.917 7683-18798/:filedownloader W/System.err:     at com.liulishuo.filedownloader.download.FetchDataTask.pause(FetchDataTask.java:60)
09-01 09:13:38.917 7683-18798/:filedownloader W/System.err:     at com.liulishuo.filedownloader.download.DownloadRunnable.pause(DownloadRunnable.java:60)
09-01 09:13:38.917 7683-18798/:filedownloader W/System.err:     at com.liulishuo.filedownloader.download.DownloadRunnable.discard(DownloadRunnable.java:64)
09-01 09:13:38.917 7683-18798/:filedownloader W/System.err:     at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.onError(DownloadLaunchRunnable.java:767)
09-01 09:13:38.917 7683-18798/:filedownloader W/System.err:     at com.liulishuo.filedownloader.download.DownloadRunnable.run(DownloadRunnable.java:135)
09-01 09:13:38.917 7683-18798/:filedownloader W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
09-01 09:13:38.917 7683-18798/:filedownloader W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-01 09:13:38.917 7683-18798/:filedownloader W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
09-01 09:13:38.918 7683-18798/:filedownloader W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
09-01 09:13:38.918 7683-18798/:filedownloader W/System.err:     at java.lang.Thread.run(Thread.java:818)
09-01 09:13:38.918 7683-18798/:filedownloader W/System.err: Caused by: android.system.ErrnoException: fsync failed: EBADF (Bad file number)
09-01 09:13:38.918 7683-18798/:filedownloader W/System.err:     at libcore.io.Posix.fsync(Native Method)
09-01 09:13:38.918 7683-18798/:filedownloader W/System.err:     at libcore.io.BlockGuardOs.fsync(BlockGuardOs.java:143)
09-01 09:13:38.918 7683-18798/:filedownloader W/System.err:     at java.io.FileDescriptor.sync(FileDescriptor.java:74)
09-01 09:13:38.919 7683-18798/:filedownloader W/System.err: 	... 12 more

通常在下载300M以上的较大文件时出现，低于100M的目前还没有发现这个问题

**Comment by serious198706** [comment]
我也发现了这个问题。小文件没什么问题，大文件有问题。多线程下载的原因？

**Comment by BigExcalibur** [comment]
该问题较严重，目前已停用此框架，希望作者能维护一下，非常感谢。

**Comment by Jacksgong** [comment]
1. 遇到问题，尝试查看CHANGELOG，是否在新版本中修复，建议使用最新的版本
2. 提供问题的时候请根据issue要求，提供版本等各信息
3. 本项目为开源项目，请在遇到问题的时候尝试自己解决，欢迎PR，如果无法解决，请提供解决的思路为什么行不通
4. 根据这个日志，这个只是FileDescriptor的一个warning，由于分块下载对同一个文件进行同时的sync的场景，因此比较容易促发该警告，但是 **不会影响下载本身** ，只是某一次flush没有flush到文件系统，但是依然存在cache中，在下载完成后，或者输出流关闭时，会正常flush会文件系统。由于该警告目前来看对下载没有任何影响，暂时没有修复计划。如果有更好的建议，或者直接的PR也十分欢迎。
