### ISSUE TITLE
下载的时候可以设置token吗?

### ISSUE THREAD

**Issue by onyx-hehai** [lingochamp/FileDownloader#756]
#### Before Issue

1. Please search on the [Issues](https://github.com/lingochamp/FileDownloader/issues)
2. Please search on the [wiki](https://github.com/lingochamp/FileDownloader/wiki)
3. Please set `FileDownloadLog.NEED_LOG=true` and review the Logcat output from main process and `:filedownloader` process ( pay attention to Warn and Error level logcat)

#### Issue

1. What problem do you get?
2. Which version of FileDownloader are you using when you produce such problem?
3. How to reproduce such problem?
4. Do you set `FileDownloadLog.NEED_LOG=true`?
5. Could you please reproduce this problem and provide all main process and `:filedownloader` process logcat on here:

```
```

>P.S. If you don't know how to get `:filedownloader` process, it's recommended to using `pidcat` to just filter all your application logcat, or define `process.non-separate=true` on [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)

**Comment by Jacksgong** [comment]
可以添加到请求头中: 

`BaseDownloadTask`:

```java
 /**
  * Add the params to the request header.
  * <p>
  * <strong>Note:</strong> We have already handled Etag internal for guaranteeing tasks resuming
  * from the breakpoint, in other words, if the task has downloaded and got Etag, we will add the
  * 'If-Match' and the 'Range' K-V to its request header automatically.
  */
 BaseDownloadTask addHeader(final String name, final String value);

 /**
  * Add a field with the specified value to the request header.
  */
 BaseDownloadTask addHeader(final String line);
```
