### ISSUE TITLE
有时候progress为负值

### ISSUE THREAD

**Issue by chinahbpyj** [lingochamp/FileDownloader#759]
percent = soFarBytes * 100 / totalBytes;

下载开始，然后点暂停，再下载，percent会出现负值，怎么解决，谢谢

**Comment by zdunex25** [comment]
Yeah, I faced this issue as well.

`int lastProgress = -1;
int progress = ((soFarBytes*100)/totalBytes);
    if (progress > lastProgress) {
        progressBar.setProgress(progress);
    }`

**Comment by chinahbpyj** [comment]
我已经解决，
 final double percent = (double) soFarBytes * 100 / (double) totalBytes;

**Comment by zdunex25** [comment]
(double) - right, thanks!

**Comment by Jacksgong** [comment]
This is not the FileDownloader problem, you occur such problem because of the `soFarBytes * 100` out of the range of Integer.

so I think the better solution would be `float percent = soFarBytes * (100f/totalBytes)`
