### ISSUE TITLE
急求：在网络不好的情况下，在频繁切换开始和暂停的时候，进度有时候会从0开始，这是为什么？

### ISSUE THREAD

**Issue by liuhaipeng** [lingochamp/FileDownloader#760]
#### Before Issue

1. Please search on the [Issues](https://github.com/lingochamp/FileDownloader/issues)
2. Please search on the [wiki](https://github.com/lingochamp/FileDownloader/wiki)
3. Please set `FileDownloadLog.NEED_LOG=true` and review the Logcat output from main process and `:filedownloader` process ( pay attention to Warn and Error level logcat)

#### Issue

1. What problem do you get?
2. Which version of FileDownloader are you using when you produce such problem?
3. How to reproduce such problem?
4. Do you set `FileDownloadLog.NEED_LOG=true`?
5. Could you please reproduce this problem and provide all main process and `:filedownloader` process logcat 
6. Can you fix it by yourself and request PR, if not, what's problem do you get when you try to fix it

>P.S. If you don't know how to get `:filedownloader` process, it's recommended to using `pidcat` to just filter all your application logcat, or define `process.non-separate=true` on [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)

---

请在Issue前认真的跟进上面提到的建议，这样将可以极大的加快你遇到问题的处理。

**Comment by Jacksgong** [comment]
关注下logcat，文件损坏，etag变换，后台返回非206，等等原因为了保证文件完整性会重头开始下载。

**Comment by liuhaipeng** [comment]
DownLoadManager$2.error(Line:377): error....13594902--"ll89DsjcrgfkZLM53kAltKUzei8K"
:DownLoadManager$2.error(Line:380): error....Connection failed with code[416] on task[1898804747], which is changed after verify connection, so please try again.
W/FileDownloader.DownloadTaskHunter: warn, but no mListener to receive, switch to pending :DownLoadManager$2.warn(Line:385): warn....

**Comment by Jacksgong** [comment]
416的reponse status是1.6.4之前的版本在一些情况下存在该问题，请参看[变更](https://github.com/lingochamp/FileDownloader/blob/master/CHANGELOG-ZH.md) ，并且使用最新的版本(1.6.5)。

如果使用了1.6.4或者1.6.5之后还有该416问题，一般来说是后台的问题，如果后台确定没有问题，可以根据提issue时的提示文档查看日志，自行分析，请求头中的range是否有错。

**Comment by liuhaipeng** [comment]
好多时候报的都是这个错：我刚才已经替换到1.6.5了
 notify error 631020202@com.liulishuo.filedownloader.DownloadTask@427023a0 java.net.ProtocolException: unexpected end of stream
FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@4296d250 by -1 
FileDownloader.SerialHandlerCallback: start next com.acmeway.medical.video.DownLoadManager$2@42ce50d0 1
FileDownloader.SerialHandlerCallback: final serial null 1
DownLoadManager$2.error(Line:377): error....21547451--"lj78xljtbKC1_nbs0qfexMiXIzWZ"
DownLoadManager$2.error(Line:380): error....unexpected end of stream

**Comment by liuhaipeng** [comment]
大神，急求解决方案啊
DownloadTaskHunter: High concurrent cause, this task -888727152 will not start, because the of status isn't toLaunchPool: -2
09-12 09:34:43.844 3004-9564/com.acmeway.medical W/FileDownloader.DownloadTaskHunter: High concurrent cause, this task 1898804747 will not start, the status can't assign to toFileDownloadService, because the status isn't toLaunchPool: -2
09-12 09:34:43.845 3004-9565/com.acmeway.medical W/FileDownloader.DownloadTaskHunter: High concurrent cause, this task -706855230 will not start, because the of status isn't toLaunchPool: -2
09-12 09:34:43.848 3004-9563/com.acmeway.medical W/FileDownloader.DownloadTaskHunter: High concurrent cause, this task -476943013 will not start, because the of status isn't toLaunchPool: -2
09-12 09:34:43.866 3004-3004/com.acmeway.medical I/acmewaylogger:DownLoadManager$3.error(Line:366): error....8235323--"lr3G2kP25dpOSV5eGOiT8JPwxgWG"
09-12 09:34:43.867 3004-3004/com.acmeway.medical I/acmewaylogger:DownLoadManager$3.error(Line:369): error....unexpected end of stream

**Comment by chenycu** [comment]
@Jacksgong 网速快的情况下只要快速重复点击开始暂停都会从0开始，概率100%，文件应该没这么容易损坏吧，应该是代码的问题，就用您给的demo测试的，用在项目上，测试这关过不了。

**Comment by Jacksgong** [comment]
@chenycu 切到最新版本的分支，运行，出现问题时，请关注logcat，以及对应日志在代码中注解，在遇到问题的时候，先自己尝试的去解决，这是最快的方式。因为我这边没有对应场景（我这边无法复现），最好是定位到怀疑的代码所在行，给出你的分析结果以及路径，来加快问题处理流程，也欢迎PR。
