### ISSUE TITLE
任务管理器内快速重复点击开始暂停button进度条从有值变为0

### ISSUE THREAD

**Issue by chenycu** [lingochamp/FileDownloader#762]
我在1.6.5版本的任务管理器案例界面，点击某个item的开始按钮后，任务下载进度条开始走动，然后快速重复点击button在开始和暂停状态之间切换，进度条会从>0%变为0%。这个bug比较严重，请您帮忙解决下，谢谢！

**Comment by rantianhua** [comment]
现在已经是 1.7.6 版本了，我自己试验没有复现这个问题。如果你发现还有问题的话，请 Reopen 同时附上日志。
