### ISSUE TITLE
无法下载文件，但是使用Chrome浏览器却是可以打开的

### ISSUE THREAD

**Issue by caiyoufei** [lingochamp/FileDownloader#765]
FileDownloader.FileDownloader: request pause but not exist -1248118760

response code error: 404, request headers: {Range=[bytes=0-]}  response headers: {null=[HTTP/1.1 404 Not Found], Connection=[keep-alive], Content-Type=[text/html], Date=[Fri, 15 Sep 2017 08:38:52 GMT], Server=[Tengine/2.1.1], Transfer-Encoding=[chunked], X-Android-Received-Millis=[1505464730786], X-Android-Response-Source=[NETWORK 404], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1505464730742]};
文件下载地址为:http://storage.singworld.net/46/2/G99174_20170905222624_0.mp3
经常出现无法下载，但是浏览器却是可以打开并下载的，不知道是服务器不稳定，还是这个工具有点问题，谢谢。

**Comment by zhoukai0203** [comment]
服务器端不支持断点下载

**Comment by caiyoufei** [comment]
@zhoukai0203 好的，可能是测试服务器的问题

**Comment by ApacheJondy** [comment]
@zhoukai0203  麻烦帮忙看看，怎么判断是服务器不知道断点续传？我这边有个类似的故障，谢谢！：
下载一个apk文件，出现下面的错误
response code error: 403, 
request headers: {if-match=["59ccc1a8-247c51e"], range=[bytes=0-]} 
response headers: {connection=[keep-alive], content-length=[162], content-type=[text/html], date=[Wed, 11 Oct 2017 06:35:08 GMT], server=[nginx]}

**Comment by Jacksgong** [comment]
@ApacheJondy 你找你们服务器了解下，为什么返回403给你，是不是要带什么请求头，为什么拒绝访问。

**Comment by ApacheJondy** [comment]
@Jacksgong 这个服务器那边没有返回，另外我提了一个163邮箱附件下载的，返回500，用chrome是可以下载的，麻烦抽空看下，谢谢！

**Comment by Jacksgong** [comment]
1. @ApacheJondy 这个返回值肯定是服务端返回的，这个如果服务端存在质疑，请抓包后提供给他们
2. 500是服务端错误；但是一般来说如果Chrome可以下载，FileDownloader不行，请抓包看看Chrome带的请求头是什么，带上相同的请求头即可。

**Comment by zhoukai0203** [comment]
@ApacheJondy 用框架下载对应的链接，暂停，再继续下载看是否可以就可以判断是否为断点下载了，还有一种情况是公司的网管给限制了，一版的自己搭建一个tomcat直接把文件放进去都支持断点。
@Jacksgong 网络请求超时在哪里设置，在有些情况下超时时间太长

**Comment by Jacksgong** [comment]
@zhoukai0203 默认连接器的超时设置参看`FileDownloadUrlConnection#Configuration`，连接器设置参考: [这里](https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component)

**Comment by Khaos116** [comment]
有的必须设置User-Agent才能下载
 builder.addHeader("User-Agent", WebSettings.getDefaultUserAgent(Utils.getApp()));

**Comment by ApacheJondy** [comment]
邮件已收到，将尽快给你回复。
