### ISSUE TITLE
权限设置

### ISSUE THREAD

**Issue by AndyGu** [lingochamp/FileDownloader#77]
demo里的android:maxSdkVersion="18"是为什么？只支持到 18的sdkversion么？

**Comment by Jacksgong** [comment]
> demo中的所有代码，都不会对library进行有关约定。

library的minSdk是到 8。

---

Demo中的 `android:maxSdkVersion="18"` 是为了在18以上的 手机不申请 对应的权限，至于原因，建议直接看下这篇文章比较快: [Android中尽量不用Storage Permission](http://blog.dreamtobe.cn/2015/11/30/android_storage_permission/)
