### ISSUE TITLE
javax.net.ssl.SSLException: Read error: ssl=0x743c10e800: I/O error during system call, Connection reset by peer

### ISSUE THREAD

**Issue by leoncoding** [lingochamp/FileDownloader#773]
你好，在使用三星手机下载单个视频文件时，连接某个wifi网络下载每次都是失败，回调error：notify error -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 javax.net.ssl.SSLException: Read error: ssl=0x743c10e800: I/O error during system call, Connection reset by peer

25 17:15:12.101 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify pending -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93
09-25 17:15:12.103 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[1] new[6] 1
09-25 17:15:12.103 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify started -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93
09-25 17:15:12.103 4620-11895/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.ConnectTask: -2108620344 request header {Range=[bytes=0-]}
09-25 17:15:13.632 4620-11895/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FileDownloadUtils: etag find "69e304385b148360137e9c2e286aa027-2" for task(-2108620344)
09-25 17:15:13.644 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[6] new[2] 1
09-25 17:15:13.645 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify connected -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93
09-25 17:15:13.676 4620-11895/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.DownloadLaunchRunnable: fetch data with multiple connection(count: [3]) for task[-2108620344] totalLength[7391596]
09-25 17:15:13.677 4620-11895/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.DownloadLaunchRunnable: enable multiple connection: id[-2108620344] index[0] range[0, 2463864) current offset(0)
09-25 17:15:13.678 4620-11895/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.DownloadLaunchRunnable: enable multiple connection: id[-2108620344] index[1] range[2463865, 4927729) current offset(2463865)
09-25 17:15:13.679 4620-11895/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.DownloadLaunchRunnable: enable multiple connection: id[-2108620344] index[2] range[4927730, 0) current offset(4927730)
09-25 17:15:13.685 4620-11923/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.ConnectTask: -2108620344 request header {Range=[bytes=0-2463864]}
09-25 17:15:13.686 4620-11924/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.ConnectTask: -2108620344 request header {Range=[bytes=2463865-4927729]}
09-25 17:15:13.694 4620-11925/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.ConnectTask: -2108620344 request header {Range=[bytes=4927730-]}
09-25 17:15:14.960 4620-11924/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.DownloadRunnable: the connection[1] for -2108620344, is connected range[2463865, 4927729) current offset[2463865] with code[206]
09-25 17:15:14.962 4620-11924/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FetchDataTask: start fetch(1): range [2463865, 4927729), seek to[2463865]
09-25 17:15:14.963 4620-11925/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.DownloadRunnable: the connection[2] for -2108620344, is connected range[4927730, 0) current offset[4927730] with code[206]
09-25 17:15:14.966 4620-11923/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.DownloadRunnable: the connection[0] for -2108620344, is connected range[0, 2463864) current offset[0] with code[206]
09-25 17:15:14.967 4620-11925/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FetchDataTask: start fetch(2): range [4927730, 0), seek to[4927730]
09-25 17:15:14.969 4620-11923/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FetchDataTask: start fetch(0): range [0, 2463864), seek to[0]
09-25 17:15:14.994 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[2] new[3] 1
09-25 17:15:14.995 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 4096 7391596
09-25 17:15:15.000 4620-11924/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FetchDataTask: require sync id[-2108620344] index[1] offset[2467961], consume[9]
09-25 17:15:15.036 4620-11925/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FetchDataTask: require sync id[-2108620344] index[2] offset[4931826], consume[17]
09-25 17:15:15.213 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:15.214 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 84735 7391596
09-25 17:15:15.218 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:15.221 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 85783 7391596
09-25 17:15:16.699 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:16.700 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 163607 7391596
09-25 17:15:16.701 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:16.703 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 171775 7391596
09-25 17:15:16.706 4620-11923/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FetchDataTask: require sync id[-2108620344] index[0] offset[68169], consume[9]
09-25 17:15:18.070 4620-11924/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FetchDataTask: require sync id[-2108620344] index[1] offset[2537172], consume[8]
09-25 17:15:18.100 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:18.100 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 245503 7391596
09-25 17:15:18.244 4620-11925/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FetchDataTask: require sync id[-2108620344] index[2] offset[5001037], consume[17]
09-25 17:15:18.469 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:18.472 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 333591 7391596
09-25 17:15:18.919 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:18.921 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 414439 7391596
09-25 17:15:18.924 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:18.926 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 414439 7391596
09-25 17:15:19.248 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:19.249 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 493311 7391596
09-25 17:15:19.251 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:19.252 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 501479 7391596
09-25 17:15:19.788 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:19.788 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 576255 7391596
09-25 17:15:20.018 4620-11923/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FetchDataTask: require sync id[-2108620344] index[0] offset[133729], consume[21]
09-25 17:15:20.096 4620-11924/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FetchDataTask: require sync id[-2108620344] index[1] offset[2724564], consume[20]
09-25 17:15:20.112 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:20.116 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 659199 7391596
09-25 17:15:20.120 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:20.124 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 660247 7391596
09-25 17:15:21.489 4620-11925/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FetchDataTask: require sync id[-2108620344] index[2] offset[5192525], consume[16]
09-25 17:15:21.520 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:21.521 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 737023 7391596
09-25 17:15:22.101 4620-11923/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FetchDataTask: require sync id[-2108620344] index[0] offset[203361], consume[8]
09-25 17:15:22.374 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:22.376 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 815871 7391596
09-25 17:15:23.165 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:23.168 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 894743 7391596
09-25 17:15:23.171 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:23.174 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 902911 7391596
09-25 17:15:23.290 4620-11924/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FetchDataTask: require sync id[-2108620344] index[1] offset[2793148], consume[11]
09-25 17:15:23.423 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:23.424 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 977687 7391596
09-25 17:15:23.642 4620-11925/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FetchDataTask: require sync id[-2108620344] index[2] offset[5296973], consume[18]
09-25 17:15:23.650 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:23.653 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 1058535 7391596
09-25 17:15:24.221 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:24.222 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 1138455 7391596
09-25 17:15:24.469 4620-11923/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FetchDataTask: require sync id[-2108620344] index[0] offset[334433], consume[7]
09-25 17:15:24.473 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:24.474 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 1216255 7391596
09-25 17:15:24.785 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:24.790 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 1291031 7391596
09-25 17:15:25.060 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:25.061 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 1372927 7391596
09-25 17:15:25.371 4620-11924/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FetchDataTask: require sync id[-2108620344] index[1] offset[2954964], consume[29]
09-25 17:15:25.424 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:25.427 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 1447703 7391596
09-25 17:15:25.684 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:25.685 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 1529599 7391596
09-25 17:15:25.686 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:25.687 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 1529599 7391596
09-25 17:15:25.840 4620-11925/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FetchDataTask: require sync id[-2108620344] index[2] offset[5471053], consume[17]
09-25 17:15:26.040 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:26.043 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 1604375 7391596
09-25 17:15:26.396 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:26.397 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 1678103 7391596
09-25 17:15:27.796 4620-11923/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FetchDataTask: require sync id[-2108620344] index[0] offset[525921], consume[20]
09-25 17:15:27.818 4620-11924/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FetchDataTask: require sync id[-2108620344] index[1] offset[3059412], consume[19]
09-25 17:15:27.834 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:27.837 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 1765143 7391596
09-25 17:15:27.840 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:27.843 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 1773311 7391596
09-25 17:15:27.893 4620-11925/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FetchDataTask: require sync id[-2108620344] index[2] offset[5540685], consume[21]
09-25 17:15:30.237 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:30.240 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 1848087 7391596
09-25 17:15:30.453 4620-11923/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FetchDataTask: require sync id[-2108620344] index[0] offset[595553], consume[26]
09-25 17:15:30.462 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:30.466 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 1925911 7391596
09-25 17:15:30.672 4620-11925/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FetchDataTask: require sync id[-2108620344] index[2] offset[5610317], consume[22]
09-25 17:15:30.827 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:30.829 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 2003711 7391596
09-25 17:15:30.835 4620-11924/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FetchDataTask: require sync id[-2108620344] index[1] offset[3129044], consume[23]
09-25 17:15:31.196 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:31.199 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 2081535 7391596
09-25 17:15:31.202 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:31.205 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 2085607 7391596
09-25 17:15:31.935 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:31.937 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 2164479 7391596
09-25 17:15:31.940 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:31.942 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 2168575 7391596
09-25 17:15:32.396 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:32.397 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 2252567 7391596
09-25 17:15:32.399 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:32.400 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 2260735 7391596
09-25 17:15:32.480 4620-11923/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FetchDataTask: require sync id[-2108620344] index[0] offset[748129], consume[19]
09-25 17:15:32.835 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[3] 1
09-25 17:15:32.838 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify progress -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 2335511 7391596
09-25 17:15:32.851 4620-11925/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FetchDataTask: require sync id[-2108620344] index[2] offset[5749581], consume[23]
09-25 17:15:32.940 4620-11923/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FetchDataTask: require sync id[-2108620344] index[0] offset[765537], consume[7]
09-25 17:15:32.961 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.MessageSnapshotGate: ~~~callback -2108620344 old[3] new[-1] 1
09-25 17:15:32.963 3088-11896/com.ubtechinc.alpha2_alexa V/FileDownloader.FileDownloadList: remove -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 left -1 0
09-25 17:15:32.964 3088-11896/com.ubtechinc.alpha2_alexa D/FileDownloader.FileDownloadMessenger: notify error -2108620344@com.liulishuo.filedownloader.DownloadTask@cc33e93 javax.net.ssl.SSLException: Read error: ssl=0x743c10e800: I/O error during system call, Connection reset by peer
09-25 17:15:32.965 3088-11896/com.ubtechinc.alpha2_alexa V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@29b2ec9 by -1 
09-25 17:15:32.970 4620-11924/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FetchDataTask: require sync id[-2108620344] index[1] offset[3216084], consume[9]
09-25 17:15:32.989 4620-11925/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FetchDataTask: require sync id[-2108620344] index[2] offset[5762893], consume[7]
09-25 17:15:32.990 4620-11925/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.DownloadStatusCallback: require callback -1 but the host thread of the flow has already dead, what is occurred because of there are several reason can final this flow on different thread.
09-25 17:15:33.018 4620-11924/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.FetchDataTask: require sync id[-2108620344] index[1] offset[3216084], consume[11]
09-25 17:15:33.020 4620-11895/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.DownloadLaunchRunnable: finish sub-task for [-2108620344] TRUE FALSE
09-25 17:15:33.021 4620-11895/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.DownloadLaunchRunnable: finish sub-task for [-2108620344] TRUE FALSE
09-25 17:15:33.022 4620-11895/com.ubtechinc.alpha2_alexa:filedownloader D/FileDownloader.DownloadLaunchRunnable: finish sub-task for [-2108620344] TRUE FALSE

**Comment by didikeeLunaon** [comment]
我刚刚也遇到这个问题，我下载的视频地址为：
`https://scontent-sin6-1.cdninstagram.com/t50.2886-16/20639948_1877553475898837_2968671662599307264_n.mp4`

**Comment by Jacksgong** [comment]
这个应该不是FileDownloader的问题，是网络连接的问题，参考这里: https://github.com/lingochamp/FileDownloader/issues/473#issuecomment-278847797
