### ISSUE TITLE
时有时无的 java.net.ProtocolException: unexpected end of stream

### ISSUE THREAD

**Issue by liqian685** [lingochamp/FileDownloader#775]
1.65版本 下载一个任务的时候，同一个任务 有时会出现：
如果是服务器返回的 content_length 问题 不应该每次都出错吗？
09-25 18:15:32.779 21664-21664/com.liulishuo.filedownloader.demo W/System.err: java.net.ProtocolException: unexpected end of stream
09-25 18:15:32.780 21664-21664/com.liulishuo.filedownloader.demo W/System.err:     at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:421)
09-25 18:15:32.780 21664-21664/com.liulishuo.filedownloader.demo W/System.err:     at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
09-25 18:15:32.780 21664-21664/com.liulishuo.filedownloader.demo W/System.err:     at java.io.InputStream.read(InputStream.java:101)
09-25 18:15:32.780 21664-21664/com.liulishuo.filedownloader.demo W/System.err:     at com.liulishuo.filedownloader.download.FetchDataTask.run(FetchDataTask.java:135)
09-25 18:15:32.780 21664-21664/com.liulishuo.filedownloader.demo W/System.err:     at com.liulishuo.filedownloader.download.DownloadRunnable.run(DownloadRunnable.java:114)
09-25 18:15:32.782 21664-21664/com.liulishuo.filedownloader.demo W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
09-25 18:15:32.782 21664-21664/com.liulishuo.filedownloader.demo W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-25 18:15:32.782 21664-21664/com.liulishuo.filedownloader.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-25 18:15:32.782 21664-21664/com.liulishuo.filedownloader.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-25 18:15:32.782 21664-21664/com.liulishuo.filedownloader.demo W/System.err:     at java.lang.Thread.run(Thread.java:761)

**Comment by yichang666** [comment]
怎么解决的呢

**Comment by Jacksgong** [comment]
参考下这里: #652

**Comment by Yonghejiunian** [comment]
这个并没有被解决，怎么被close了？我这里大约有0.5% 的失败率来自这个错误

**Comment by Yonghejiunian** [comment]
> 参考下这里: #652

这里的也没有被解决
