### ISSUE TITLE
文件下载完成后progress也没有回调，看到有类似issue但是没有看到解答，请教一下诸位大神

### ISSUE THREAD

**Issue by mityao** [lingochamp/FileDownloader#779]
#### Before Issue

1. Please search on the [Issues](https://github.com/lingochamp/FileDownloader/issues)
2. Please search on the [wiki](https://github.com/lingochamp/FileDownloader/wiki)
3. Please set `FileDownloadLog.NEED_LOG=true` and review the Logcat output from main process and `:filedownloader` process ( pay attention to Warn and Error level logcat)

#### Issue

1. What problem do you get?
2. Which version of FileDownloader are you using when you produce such problem?
3. How to reproduce such problem?
4. Do you set `FileDownloadLog.NEED_LOG=true`?
5. Could you please reproduce this problem and provide all main process and `:filedownloader` process logcat 
6. Can you fix it by yourself and request PR, if not, what's problem do you get when you try to fix it

>P.S. If you don't know how to get `:filedownloader` process, it's recommended to using `pidcat` to just filter all your application logcat, or define `process.non-separate=true` on [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)

---

请在Issue前认真的跟进上面提到的建议，这样将可以极大的加快你遇到问题的处理。

**Comment by Jacksgong** [comment]
可否按照Issue的步骤，提供相关日志，以便于定位问题？

**Comment by mityao** [comment]
@Jacksgong 您好，以下是我模仿demo中的MultitaskTestActivity对多个task依次进行下载的代码，我使用的是1.6.5版本


    private FileDownloadListener createLis() {
        return new FileDownloadListener() {
            @Override
            protected void pending(BaseDownloadTask task, int soFarBytes, int totalBytes) {
                if (task.getListener() != downloadFileListener) {
                    return;
                }
                Logd("Pending download file ===== " + task.getFilename() + " soFarBytes " + soFarBytes + " totalBytes " + totalBytes);
            }

            @Override
            protected void progress(BaseDownloadTask task, int soFarBytes, int totalBytes) {
                if (task.getListener() != downloadFileListener) {
                    return;
                }
                FileDownloadLog.NEED_LOG = true;
                FileDownloadLog.d(this, "FileDownloadLog Download file ===== " + task.getFilename() + " ===== soFarBytes ===== " + soFarBytes +
                        " ===== totalBytes ===== " + totalBytes);
                Logd("Download file ===== " + task.getFilename() + " ===== soFarBytes ===== " + soFarBytes +
                        " ===== totalBytes ===== " + totalBytes);
            }
...
}
===========================在调用start方法后开始下载任务
    private void start() {
        final int count = adapter.SelectItem.size();
        // =================== How to Download tasks: =============================
        downloadFileListener = createLis();
        final FileDownloadQueueSet queueSet = new FileDownloadQueueSet(downloadFileListener);
        final List<BaseDownloadTask> tasks = new ArrayList<>();
        for (int i = 0; i < count; i++) {
            final String fileName = adapter.SelectItem.get(i).mName;
            final String url = "http://" + Application.DVR_IP + fileName;
            final String filePath = FileSystemManager.getInstance().getFileDownDirectory() +
                    fileName.substring(fileName.lastIndexOf("/") + 1); // not sure if the download file path passed is right
            Logd("File Download url " + url);
            tasks.add(createTask(url, filePath));
        }
        queueSet.disableCallbackProgressTimes(); // do not want each task's download progress's callback,
        // we just consider which task will completed.
        queueSet.setAutoRetryTimes(1);          // auto retry 1 time if download fail
        queueSet.downloadSequentially(tasks);   // Download files sequentially
        queueSet.start();
    }
=================================
    private BaseDownloadTask createTask(String url, String filePath) {
        return FileDownloader.getImpl().create(url)
                .setPath(filePath) // By invoke this method we can change the file name as our wish
                .setCallbackProgressTimes(300)
                .setMinIntervalUpdateSpeed(400);
    }
但是progress没有回调，然后我在您的demo中，在MultitaskTestActivity的progress中日志同样没有被打印，这是什么原因呢

**Comment by mityao** [comment]
@Jacksgong 汗颜。。因为我加了这一句queueSet.disableCallbackProgressTimes(); // do not want each task's download progress's callback。。。是我疏忽大意了，浪费了时间。。谢谢大牛
