### ISSUE TITLE
新手弱弱问下：怎么实现文件下载完成后的重命名呢？另外，如何访问数据库，db放在那里了。。

### ISSUE THREAD

**Issue by ApacheJondy** [lingochamp/FileDownloader#780]
之前看过一段时间，后来没做了，最近看了下发现了上面的问题，求大神指导下，谢谢~

**Comment by 244317809** [comment]
1. 可以在 `void completed(final BaseDownloadTask task)` 这个回调里由 task 取出文件的路径，然后创建file对象，再重命名;

2. /data/data/com.xxx.xxx/databases/filedownloader.db (可能需要root才能访问)

**Comment by ApacheJondy** [comment]
@244317809 感谢~另研究一段时间，发现几点：
1、filedownloader.db数据库中只有正在下载的记录，下载完成的已经删除。
2、如果需要记录所有的下载记录，就需要另建db
3、重命名：文件名称重命名、update 自建的db

**Comment by rantianhua** [comment]
Plase refer to #960
