### ISSUE TITLE
如何自定义下载目录及重命名文件(响应头缺少contentDescription)

### ISSUE THREAD

**Issue by FiveKilling** [lingochamp/FileDownloader#782]
响应头里没有ContentDescription字段情况下如何自定义下载目录和重命名文件？

**Comment by Jacksgong** [comment]
参看`BaseDownloadTask`的注解:

```java
/**
 * @param path {@code path} = (absolute directory/filename); and {@link #isPathAsDirectory()}
 *             assign to {@code false}.
 */
BaseDownloadTask setPath(final String path);

/**
 * @param path            The absolute path for saving the download file.
 * @param pathAsDirectory {@code true}: if the {@code path} is absolute directory to store the
 *                        downloading file, and the {@code filename} will be found in
 *                        contentDisposition from the response as default, if can't find
 *                        contentDisposition,the {@code filename} will be generated by
 *                        {@link FileDownloadUtils#generateFileName(String)}  with {@code url}.
 *                        </p>
 *                        {@code false}: if the {@code path} = (absolute directory/filename).
 * @see #isPathAsDirectory()
 * @see #getFilename()
 */
BaseDownloadTask setPath(final String path, final boolean pathAsDirectory);
```

**Comment by FiveKilling** [comment]
👌OK。搞定了！感谢~


原始邮件
发件人:Jacksgongnotifications@github.com
收件人:lingochamp/FileDownloaderFileDownloader@noreply.github.com
抄送:FiveKillinghonkerunionofchina@foxmail.com; Authorauthor@noreply.github.com
发送时间:2017年9月29日(周五) 15:23
主题:Re: [lingochamp/FileDownloader] 如何自定义下载目录及重命名文件(响应头缺少contentDescription) (#782)


参看BaseDownloadTask的注解:
/** * @param path {@code path} = (absolute directory/filename); and {@link #isPathAsDirectory()} * assign to {@code false}. */ BaseDownloadTask setPath(final String path); /** * @param path The absolute path for saving the download file. * @param pathAsDirectory {@code true}: if the {@code path} is absolute directory to store the * downloading file, and the {@code filename} will be found in * contentDisposition from the response as default, if can't find * contentDisposition,the {@code filename} will be generated by * {@link FileDownloadUtils#generateFileName(String)} with {@code url}. * /p * {@code false}: if the {@code path} = (absolute directory/filename). * @see #isPathAsDirectory() * @see #getFilename() */ BaseDownloadTask setPath(final String path, final boolean pathAsDirectory);
