### ISSUE TITLE
Progressive download not as TEMP file

### ISSUE THREAD

**Issue by JakubJedrecki** [lingochamp/FileDownloader#783]
Is is possible to save file with proper extension instead of TEMP file while downloading ? 
I have to create progressive download for vod player, so you can play movie after xx MB downloaded and download the rest of it at the same time.
Right now file exists as a TEMP file until download is completed so I can't play it while downloading.

**Comment by rantianhua** [comment]
FileDownloader will not add new feature, please pay attention to OkDownload.

**Comment by rantianhua** [comment]
OkDownload will not create a temp file, so you can use OkDownload.
