### ISSUE TITLE
163邮箱附件下载，返回500错误，如何解决？

### ISSUE THREAD

**Issue by ApacheJondy** [lingochamp/FileDownloader#786]
导入了包，也没法修改请求设置的参数。有遇到的解决了的没？
我目前想到的大概思路;
FileDownloadUrlConnection类中
URLConnection没有设置setrequestproperty参数；
是不是设置了Referer、Cookies就好了？

具体如下：
com.liulishuo.filedownloader.d.b: response code error: 500, 
 request headers: {range=[bytes=0-]} 
 response headers: {connection=[keep-alive], content-type=[text/html;charset=GBK], date=[Mon, 09 Oct 2017 02:05:22 GMT], server=[nginx], transfer-encoding=[chunked]}

**Comment by ApacheJondy** [comment]
@Jacksgong  这个是两个原因导致的：
1、request header需要添加cookie
2、添加cookie后会有416错误，分析发现是range头的原因，看文档说是要和If-Range一起使用。
有两个疑问：
1、If-Range 和已经添加的If-Match的 有什么区别，代码中如果etag为null，该怎么设置If-Range 的值
2、虽然找到了原因，在下载时，如何在FileDownloadUrlConnection 或者 OkHttp3Connection 中如何添加request header。看到有个addHeader方法，该怎么加上去。
谢谢~

**Comment by Jacksgong** [comment]
416，错误，你看看日志本地提供的请求头的Range是多少，和后台核对下，是否是本地提供的Range是错误的。

**Comment by ApacheJondy** [comment]
@Jacksgong 3Q,加头部的我等下试试，另外有没有删除头部的，163邮箱下载的，有range就不会正常下载。
1、If-Range的资料我是参考这里的：
https://baike.baidu.com/item/HTTP%E7%8A%B6%E6%80%81%E7%A0%81/5053660?fr=aladdin#4_17
   如果请求中包含了 Range 请求头，并且 Range 中指定的任何数据范围都与当前资源的可用范围不重合，同时请求中又没有定义 If-Range 请求头，那么服务器就应当返回416状态码。
       假如 Range 使用的是字节范围，那么这种情况就是指请求指定的所有数据范围的首字节位置都超过了当前资源的长度。服务器也应当在返回416状态码的同时，包含一个 Content-Range 实体头，用以指明当前资源的长度。这个响应也被禁止使用 multipart/byteranges 作为其 Content-Type

2、Log信息如下：从信息看rang头应该是正常的。

response code error: 416, 
request headers: {
cookie=[starttime=; NTES_SESS=...; locale=], 
range=[bytes=0-]} 

response headers: {
connection=[keep-alive], 
content-language=[en], 
content-length=[997], 
content-type=[text/html;charset=utf-8], 
date=[Thu, 12 Oct 2017 09:45:07 GMT], server=[nginx]} ;

**Comment by ApacheJondy** [comment]
@Jacksgong  感谢答疑！关于BaseDownloadTask#addHeader 添加header的，确认可以添加。
另：使用removeAllHeaders("Range");并不会生效，request中任然会有range字段
range=[bytes=0-]，怎么解决。

**Comment by Jacksgong** [comment]
#### removeAllHeaders("Range");并不会生效

是的，，，内部为了确定是否支持分块下载，以及断点续传，主动添加了`Range`；为了防止资源过期，主动添加了`If-Match`，这两个不受上层控制。 `FileDownloadHeader`中的文档:

```java
/**
 * We have already handled Etag internal for guaranteeing tasks resuming from the breakpoint, in
 * other words, if the task has downloaded and got Etag, we will add the 'If-Match' and the 'Range'
 * K-V to its request header automatically.
 */
public class FileDownloadHeader implements Parcelable
```

相关代码:  `ConnectTask#addRangeHeader`、`ConnectTask#addUserRequiredHeader`。

---

#### I. 根据416的描述，正确的Http协议，此时就不应该返回416

返回416的情况，是需要下面与情况的:

- 请求头包含了Range -- **True**
- Range 中指定的任何数据范围都与当前资源的可用范围不重合 -- **False**
- 请求头没有包含If-Range -- **True**

#### II. 你这个的情况挺奇怪的，既然Range都可以与资源大小范围重合了，为什么还是返回416呢？ 

如果实在是这种特殊情况，又是后端的防御措施才返回416，**在确定只要带Range无论Range对不对，都会返回416的情况下**，可以采用下面这个解决方案：

1. 实现自己的`FileDownloadConnection`，在该`Connection`中，添加头的时候过滤掉`Range`
2. 将定制的`FileDownloadConnection`通过[这个方法](https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component)注入到FileDownloader
3. 实现自己的`ConnectionCountAdapter`始终传回`1`，避免分块下载(由于不支持`Range`分块下载会始终失败)，然后通过与2相同的方法注入

但是由于Range无效了，会带来以下问题:

1. 无法分块下载
2. 无法断点续传，每次都是从头开始下载

**Comment by ApacheJondy** [comment]
@Jacksgong 多谢解答。你说的方案是否可以理解成这样：
1、在初始化的时候，传入FileDownloader.setupOnApplicationOnCreate(application).connectionCreator()，
connectionCreator() 方法的参数应该是自己定义继承 FileDownloadConnection 接口的类。 类似：new OkHttp3Connection.Creator(builder)
2、在自己实现的MyFileDownloadConnection 类中，通过url或者其他方式判断，滤掉Range。
3、将实现自己的MyConnectionCountAdapter ，替换DefaultConnectionCountAdapter

**Comment by Jacksgong** [comment]
@ApacheJondy 定制的话，参考下[这里](https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component)。也可以参考下这个: https://github.com/lingochamp/FileDownloader/issues/911#issuecomment-357615005
