### ISSUE TITLE
支持多进程调用吗？

### ISSUE THREAD

**Issue by SyllaJay** [lingochamp/FileDownloader#788]
是否支持多进程调用？
看源码为了优化性能，是利用service去做上传业务，service可以独立进程也可以挂在主进程。如果app中除了主进程外，还存在其他子进程，多个进程调用是否OK？

**Comment by rantianhua** [comment]
你的问题有些模糊，FileDownloader 默认是将下载操作放在 `filedownloader` 进程，而且这个进程是固定的，不可以随意更改。你的描述中有个错误，不是利用 Service 做上传业务，而是下载业务。

多个进程通信自然是 ok 的，但不清楚你具体问题多个进程调用是什么意思？调用什么呢？
