### ISSUE TITLE
0KB文件不会下载

### ISSUE THREAD

**Issue by xuanu** [lingochamp/FileDownloader#789]
文件大小：0kb
文件名：.nomedia
错误提示：java.net.MalformedURLException: Protocol not found：xxx

**Comment by SelenaWong** [comment]
遇到相同的问题，0字节的文件，下载时直接报错：status = -1

**Comment by BinarySatan** [comment]
同报错，什么原因?

**Comment by rantianhua** [comment]
0 字节的文件，目前是直接当做异常抛出。

**Comment by rantianhua** [comment]
@xuanu 根据你的错误提示，是你的链接没有指定协议造成的，详情可以参考[这里](http://blog.csdn.net/qq_35246620/article/details/70162106)

**Comment by rantianhua** [comment]
@SelenaWong 希望能提供下具体的错误日志。
