### ISSUE TITLE
BaseDownloadTask has pause(), have method like cancel() or stop()?

### ISSUE THREAD

**Issue by markjoker** [lingochamp/FileDownloader#79]
I want remove the task when task is downloading and reset task status to idle.any ideas?

**Comment by Jacksgong** [comment]
If you invoke `pause()` for one task, We will clear all memory about it and stop it.

If you don't want to reuse the already-downloaded one, you can restart with `BaseDownloadTask#setForceReDownload(true)`.

**Comment by markjoker** [comment]
@Jacksgong I just want cancel the downloading task, after cancel task getStatus() is IDLE,not Paused?

**Comment by Jacksgong** [comment]
In FileDownloader, `Paused` also means IDLE. 

All statuses below are IDEL in FileDownloader for one task:

> [FileDownloadStatus](https://github.com/lingochamp/FileDownloader/blob/master/library/src/main/java/com/liulishuo/filedownloader/model/FileDownloadStatus.java)

- `Paused`
- `Warn`
- `Completed`
- `Error`

---

You can recognize IDLE as easy as judge the status value is less than 0.

```
public final static byte pending = 1;
public final static byte connected = 2;
public final static byte progress = 3;
public final static byte blockComplete = 4;
public final static byte retry = 5;
public final static byte error = -1;
public final static byte paused = -2;
public final static byte completed = -3;
public final static byte warn = -4;
```

**Comment by markjoker** [comment]
invoke pause(), After restart APP ,I still get status is pause use same url and path. Pause status in my app, i will show the load progress. but if there has method like  cancel(), After restart app, I get status is INVALID_STATUS = 0. and i will not show any progress about this task.

**Comment by Jacksgong** [comment]
You can delete the file manually, and when the `:filedownloader` process restart, it will clear the data in DB automatically, so in this situation, you can get status is INVALID_STATUS.

---

In addition, the status in the FileDownlaoder DB  is used to handling the logic for FileDownloader internal, so it would not match all requirement for the upper business requirements. In other words,  if there are very clear requirements for your App, I recommend build your own DB for your business requirements.

**Comment by Jacksgong** [comment]
And there is no method like `cancel()`.  In my point, `pause()` has already meant `cancel()` for FileDownloader.

---

#### Why not use `cancel` instead of  `paused` status for this case?

Because for FileDownloader, it will resume from the breakpoint automatically, not start from non-status.
