### ISSUE TITLE
下载几个文件，然后同时暂停再继续概率出现从头开始下载

### ISSUE THREAD

**Issue by hongbiangoal** [lingochamp/FileDownloader#793]
#### Before Issue

1. Please search on the [Issues](https://github.com/lingochamp/FileDownloader/issues)
2. Please search on the [wiki](https://github.com/lingochamp/FileDownloader/wiki)
3. Please set `FileDownloadLog.NEED_LOG=true` and review the Logcat output from main process and `:filedownloader` process ( pay attention to Warn and Error level logcat)

#### Issue

1. What problem do you get?
2. Which version of FileDownloader are you using when you produce such problem?
3. How to reproduce such problem?
4. Do you set `FileDownloadLog.NEED_LOG=true`?
5. Could you please reproduce this problem and provide all main process and `:filedownloader` process logcat 
6. Can you fix it by yourself and request PR, if not, what's problem do you get when you try to fix it

>P.S. If you don't know how to get `:filedownloader` process, it's recommended to using `pidcat` to just filter all your application logcat, or define `process.non-separate=true` on [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)

---

请在Issue前认真的跟进上面提到的建议，这样将可以极大的加快你遇到问题的处理。

**Comment by Jacksgong** [comment]
1. 如果使用的1.6.7之前的版本，存在低概率该问题，已经在1.6.7中修复。
2. 没有进行断点续传，不一定是FileDownloader的问题，有可能是服务端返回不支持，请进一步根据日志进行分析。

**Comment by hongbiangoal** [comment]
代码我大概看到这里有点疑惑
类FileDownloadManager的start方法里
```
if (model != null && (model.getStatus() == FileDownloadStatus.paused ||
            model.getStatus() == FileDownloadStatus.error) // FileDownloadRunnable invoke){
           // #isBreakpointAvailable to determine whether it is really invalid.
           。。。
}else{
if (model == null) {
                model = new FileDownloadModel();
            }
            model.setUrl(url);
            model.setPath(path, pathAsDirectory);
            model.setId(id);
            model.setSoFar(0);
            model.setTotal(0);
            model.setStatus(FileDownloadStatus.pending);
            model.setConnectionCount(1);
}
```

出问题时model.getStatus值时3(progress)

**Comment by Jacksgong** [comment]
@hongbiangoal 你用的哪个版本，1.6.6或之前的版本，确实有可能由于你提到的这里获取到3(process)导致断点续传失败。1.6.7中专门修复了这个问题。

**Comment by hongbiangoal** [comment]
ok 那我用最新的试试

**Comment by Jacksgong** [comment]
详细请参见: [changelog-zh](https://github.com/lingochamp/FileDownloader/blob/master/CHANGELOG-ZH.md#version-167)

**Comment by hongbiangoal** [comment]
试了下最新版本，还是有一种情况会导致从0开始下载
出问题时model.getStatus值时1(pending)

**Comment by Jacksgong** [comment]
@hongbiangoal 多谢提醒，其实这个状态我们在上层回调的时候有控制，但是确实在底层下载处理的时候，从某个版本开始，没有把`pending`的状态恢复。

我尽快修复下这个问题。

**Comment by Jacksgong** [comment]
#### 该问题具体如下

##### 1. 依然存在`status`为`process`导致无法断点续传问题

- **原因:** 这个目前是线程高并发时，由于JMM在不同线程未及时更新，导致`status`在不同线程不一致 
- **解决方法:** `volatile`解决

##### 2. 存在`status`为`pending`或者`started`导致无法断点续传

- **原因:** `pending`在早期版本有处理，后面某个版本后便没有处理了，`status`虽然没有存储在数据库中，但是如果不重启进程，该值依然会影响
- **解决方法:**: `pending`不再入库，并且如果是`pending`/`started`直接复用其上次进度
