### ISSUE TITLE
在哪里创建的下载文件

### ISSUE THREAD

**Issue by Kimxu** [lingochamp/FileDownloader#794]
你好我想实现的需求是 在开始下载文件（xx.temp）的时候，在 这个文件里面添加字节。我追查代码没有发现下载的文件在哪里创建的。请问在哪里创建的下载文件。

**Comment by Kimxu** [comment]
下载文件创建在FileDownloadUtils类中的createOutputStream方法：

public static FileDownloadOutputStream createOutputStream(final String path) throws IOException {
        Log.d("kimxu","isStart");
        if (TextUtils.isEmpty(path)) {
            throw new RuntimeException("found invalid internal destination path, empty");
        }

        //noinspection ConstantConditions
        if (!FileDownloadUtils.isFilenameValid(path)) {
            throw new RuntimeException(
                    FileDownloadUtils.formatString("found invalid internal destination filename" +
                            " %s", path));
        }

        File file = new File(path);

        if (file.exists() && file.isDirectory()) {
            throw new RuntimeException(
                    FileDownloadUtils.formatString("found invalid internal destination path[%s]," +
                            " & path is directory[%B]", path, file.isDirectory()));
        }
        if (!file.exists()) {
            if (!file.createNewFile()) {
                throw new IOException(
                        FileDownloadUtils.formatString("create new file error  %s",
                                file.getAbsolutePath()));
            }
          **//我添加的**
            **FileOutputStream fos = new FileOutputStream(file);
            fos.write("KOOCAN01".getBytes());
            fos.close();**
        }

        return CustomComponentHolder.getImpl().createOutputStream(file);
    }



当时在做debug 的时候，发现我修改的这个地方没有走到，以为不是在该方法中创建的文件。后来发现应该debug下载线程才对。感谢作者。

**Comment by Jacksgong** [comment]
其实你也可以通过定制你的`outputStream`实现，具体参考[这里](https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component).
