### ISSUE TITLE
如何重至 listener:FileDownloadListener

### ISSUE THREAD

**Issue by junchenChow** [lingochamp/FileDownloader#795]
@Q1: hashCode不一样的listener就直接忽略了 我想每次new FileDownloadQueueSet(fileDownloadListener) 都能以新的 listener为准，该怎么做呢。
或者 有没有api是清除老的 FileDownloadListener～
@Q2: pauseAll() 然后再开始队列并行下载 之前已经下载的进度全部都从0开始了

**Comment by Jacksgong** [comment]
##### I. 我想每次new FileDownloadQueueSet(fileDownloadListener) 都能以新的 listener为准，该怎么做呢?

这个，你直接传入新的`listener`不就行了，我没有get到问题点。

##### II. 然后再开始队列并行下载 之前已经下载的进度全部都从0开始了

每个任务是会自动断点续传的。。如果你说是一个队列，那已经下载完成的会直接返回完成。
如果你的意思是单个任务无法自动断点续传，你先留意下你是否使用的是最新的FileDownloader版本，然后通过日志看看为什么无法断点续传，是服务端返回不支持呢，还是所有资源都是chunked资源。

**Comment by junchenChow** [comment]
@Jacksgong 是我有一个页面 每次进来都会调一边这个` FileDownloader.setup(this);
        FileDownloader.getImpl().setMaxNetworkThreadCount(5);
        mediaDownloadBinder = new MediaDownloadBinder();
        List<MediaTask> mediaTasks = MediaTaskManager.getImpl().getMediaTasks();
        final FileDownloadQueueSet queueSet = new FileDownloadQueueSet(fileDownloadListener);
        baseDownloadTasks = new ArrayList<>();
        for (int i = 0; i < mediaTasks.size(); i++) {
            BaseDownloadTask baseDownloadTask = FileDownloader.getImpl().create(mediaTasks.get(i).getUrl()).setTag(i + 1);
            baseDownloadTasks.add(baseDownloadTask);
        }
        queueSet.setAutoRetryTimes(1);
        queueSet.downloadTogether(baseDownloadTasks);
        queueSet.start();`
问题所在就是只有第一次注册的fileDownloadListener有作用 后面注册的并不是覆盖之前的 所以就导致进来没有callback的回调 但是调用pauseAll()倒是可以恢复我当前的callback，然后调用pauseAll() 之后你说的下载完成的会直接返回完成这个没错 但是还有一些任务是下载了一些进度的 这个时候再开始下载就是直接进度跳到0开始了

**Comment by Jacksgong** [comment]
#### 但是还有一些任务是下载了一些进度的 这个时候再开始下载就是直接进度跳到0开始了

先留意下你是否使用的是最新的FileDownloader版本，然后通过日志看看为什么无法断点续传，是服务端返回不支持呢，还是所有资源都是chunked资源。

#### 只有第一次注册的fileDownloadListener有作用 后面注册的并不是覆盖之前的

我大概知道你的一次，你是这个页面推出以后，依然没有推出下载；然后下次进入这个页面的时候，又重新创建了一个QueueSet启动对吧。 --- **这个做法是错误的**

每个任务本身只会存一个`callback`；如果你重新创建一个QueueSet启动，对于FileDownloader来说，只是重新又来了一批要处理的任务，如果其中有相同任务正在处理，新的启动会收到`warn`而直接结束。如果其中相同的任务之前已经完成了，会直接回调完成。

**解决方法: ** 如果你本身任务监听与页面是解耦的，那你自己管理监听器，可以参考[这里](https://github.com/lingochamp/FileDownloader/issues/103#issuecomment-209173124)

**Comment by junchenChow** [comment]
嗯嗯 ，其实我是故意没有退出下载的。
正常情况下断点下载是可以的 只有调用了pauseAll()然后再继续下载才会出现从0开始的进度。
