### ISSUE TITLE
The file is too large to store, breakpoint in bytes: 0, required space in bytes: 1967487, but free space in bytes: 0 

### ISSUE THREAD

**Issue by susirsusir** [lingochamp/FileDownloader#799]
use version  'com.liulishuo.filedownloader:library:1.6.3'
du: 4.4.2_PE-TL20
full-content: [gid]=2; [errorUrl]=https://miscimg01.jiaoliuqu.com//4005151503300187.zip; 
[exception]=The file is too large to store, breakpoint in bytes: 0, required space in bytes: 1967487, but free space in bytes: 0 
[com.liulishuo.filedownloader.download.DownloadLaunchRunnable.a(SourceFile:687),
com.liulishuo.filedownloader.download.DownloadLaunchRunnable.run(SourceFile:275), 
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587),
java.lang.Thread.run(Thread.java:841)]

**Comment by Jacksgong** [comment]
The reason is clearly: 

```
The file is too large to store, breakpoint in bytes: 0, required space in bytes: 1967487, but free space in bytes: 0
```

**Comment by suzfsir** [comment]
but the file is not too large
