### ISSUE TITLE
如何获取所有下载任务

### ISSUE THREAD

**Issue by pengjianbo** [lingochamp/FileDownloader#8]

**Comment by Jacksgong** [comment]
目前确实是没有对外开发该接口(`FileDownloadList#copy()`(拷贝一份正在进行中的`BaseDownloadTask`)), 但是有提供暂停所有任务的接口(`FileDownloader#pause()`)。

你是有什么用途吗？这个接口暴露也无关紧要，只是目前确实只要有id，就可以得到对应的task，或者是自由操作。

**Comment by pengjianbo** [comment]
项目需要下载管理功能，得先获取到所有的任务列表及其相关信息（下载进度，下载状态等），能把这个功能补上发个版本吗？谢谢

**Comment by Jacksgong** [comment]
`FileDownloadList#copy()` 内部已有的这个接口是一个正在进行中的队列，也就是正在执行中（不包含结束以后的任务），这个队列可以对外提供，但是这个队列里面的任务状态是不断变化的，你是希望这个队列吗？

如果你是希望外部的一个完整的下载状态之类的（包含已经结束了的，包含业务逻辑之类的），我比较建议自己维护一张表，这样比较可控。在下载进程确实有一张所有下载的表，但是这里的表是为了下载引擎业务存在，可能为了引擎的稳定性，我们会定期会对其进行管理，并且字段也是根据引擎需要定制的与 任务解耦关系，我觉得这张表并不适合外部使用。

**Comment by Jacksgong** [comment]
ps: 我们现在自己使用FileDownloader 如果是业务相关需要记录下载状态之类的也是外面根据业务单独管理的（比如可能下载状态与课程绑定，就有一张课程的表在上面会有字段保存相关下载信息）。

**Comment by Jacksgong** [comment]
后面预计会有一个feature，暴露一个接口，为外界提供判断文件是否健在(参考`FileDownloadMgr#checkReuse`)。

**Comment by Jacksgong** [comment]
我建议你可以存储对应的 downloadId，通过`FileDownloader#getSofar`/`FileDownload#getTotal` 是可以取到存储在我那边的下载进度，与完整文件应该有的总大小的。如果下载进程那边的数据依然存在的话。

**Comment by Jacksgong** [comment]
不知道，存储对应的downloadId，是否会满足你的需求。包括提到的暴露一个 检测文件是否健在的接口（如果这个十分需要我会尽快commit）

**Comment by pengjianbo** [comment]
嗯呢，我是需要一整套的下载管理，包括已完成和未完成的下载，就像应用市场下载管理那样，已完成点击安卓未完成可以点击继续，可以删除。好像FileDownloader在这方面不是很完善。

**Comment by pengjianbo** [comment]
个人任务具备管理功能FileDownloader还是很有必要的，开发者的需求千奇百态，对外暴露一些信息，比较容易满足业务需求。希望作者能完善下。致谢

**Comment by Jacksgong** [comment]
@pengjianbo 很感谢你的建议，不过下载引擎只是负责下载相关的事务，你所说的需求其实我们应用里面也有的，但是这个我们理解是属于业务需求层面的，我们的做法是存储downloadId与业务相关字段。

---
> 已完成、未完成的下载

这个里面确实有记录但是只是为了下载引擎内部维护。如果暴露外界使用，一来这部分数据并不是非常正确的，因为这个只是引擎内部架构层的数据，引擎在使用这部分数据的时候也只是作为参考，而且会因为维护而清除掉部分数据。

ps: 其实我们自己的应用也有这个需求，但是我们是作为上层业务耦合维护的，下载引擎已经提供通过downloadId查询相关进度之类的，已经很灵活了。

> 未完成可以继续

这些引擎内是自动完成的，如果你给过来的是下载一半的，引擎内部判断可以有效断点续传，会执行断点续传的。

> 文件删除

文件删除的feature，其实并不是下载引擎应该管理的，引擎内部只需要保证你文件删除了，或者被修改了，引擎可以正确决策是否可以继续断点下载等。


---

如果我描述的并不是很清楚，周末的时候，我会写你一个类似你提到的下载管理的demo的。

ps，如果你有更好的解决方案，其实也十分欢迎PR的，

**Comment by pengjianbo** [comment]
恩，明白。不过你说的那两个类都不是public的

**Comment by Jacksgong** [comment]
你说的是`FileDownloadMgr`与`FileDownloadList`吗？

---

> `FileDownloadList#copy()`

`FileDownloadList`是内部严格控制的，所以之前没有对外开放，我问你是否是需要暴露这里面的`#copy()`接口？之所以没有对外暴露这个接口，因为这个接口原本只是为了引擎内部需求存在的，因为`FileDownloadList#copy()`出来的是非常有时效性的，如你这个是1s前的队列和1s后`copy()`出来的都不一样。

> `FileDownloadMgr#checkReuse`

`FileDownloadMgr`是在下载进程的，是无法直接对外开放的，我说的是下个版本应该会考虑对外提供仅仅判断文件的接口，走的是`FileDownloadMgr#checkReuse`的流程。

**Comment by pengjianbo** [comment]
对。好的。谢谢，如果有时间的话，麻烦写个下载管理的demo。

**Comment by Jacksgong** [comment]
恩。ok。我周末会着手写在demo里的。

**Comment by pengjianbo** [comment]
嘿嘿，大谢

**Comment by Jacksgong** [comment]
已经添加了:

[test(Taks Manager): add task manager demo](https://github.com/lingochamp/FileDownloader/commit/f344bad26668344fede5870cb63cec644f2cbcda)
