### ISSUE TITLE
connect failed: ENETUNREACH (Network is unreachable)

### ISSUE THREAD

**Issue by susirsusir** [lingochamp/FileDownloader#800]
use version com.liulishuo.filedownloader:library:1.6.3
du: 5.1_OPPO A37m
full-content: [gid]=8; [errorUrl]=https://miscimg01.jiaoliuqu.com//4005071505195222.zip; [exception]=failed to connect to miscimg01.jiaoliuqu.com/118.112.15.95 (port 443): connect failed: ENETUNREACH (Network is unreachable) [libcore.io.IoBridge.connect(IoBridge.java:129), java.net.PlainSocketImpl.connect(PlainSocketImpl.java:188), java.net.PlainSocketImpl.connect(PlainSocketImpl.java:461), java.net.Socket.connect(Socket.java:918), com.android.okhttp.internal.Platform.connectSocket(Platform.java:174), com.android.okhttp.Connection.connect(Connection.java:152), com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:282), com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:216), com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:392), com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:107), com.android.okhttp.internal.http.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89), com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:25), com.networkbench.agent.impl.instrumentation.NBSHttpsURLConnectionExtension.connect(SourceFile:66), com.liulishuo.filedownloader.a.c.d(SourceFile:95), com.liulishuo.filedownloader.download.ConnectTask.a(SourceFile:74), com.liulishuo.filedownloader.download.DownloadLaunchRunnable.run(SourceFile:262), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:818)]

**Comment by Jacksgong** [comment]
The reason is clearly:

```
failed to connect to miscimg01.jiaoliuqu.com/118.112.15.95 (port 443): connect failed: ENETUNREACH (Network is unreachable) [libcore.io.IoBridge.connect(IoBridge.java:129)
```
