### ISSUE TITLE
unexpected end of stream [com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:421),

### ISSUE THREAD

**Issue by susirsusir** [lingochamp/FileDownloader#801]
use version com.liulishuo.filedownloader:library:1.6.3
du: 7.1.1_OPPO R11
full-content: [gid]=5; [errorUrl]=https://miscimg01.jiaoliuqu.com//xzmm1504149545.zip; 
[exception]=unexpected end of stream [com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:421), 
com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:371),
java.io.InputStream.read(InputStream.java:101), 
com.liulishuo.filedownloader.download.e.b(SourceFile:133),
com.liulishuo.filedownloader.download.c.run(SourceFile:113), 
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428), 
java.util.concurrent.FutureTask.run(FutureTask.java:237),
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133), 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607), 
java.lang.Thread.run(Thread.java:761)]

**Comment by Jacksgong** [comment]
The reason is clear:

```
unexpected end of stream 
```

If you ensure that is not filesystem error, please raise issue to okhttp.
