### ISSUE TITLE
根据URL和PATH获取已有的TASK

### ISSUE THREAD

**Issue by vzhilong** [lingochamp/FileDownloader#806]
能否根据URL和PATH获取已有的TASK，如果TASK == NULL，说明这个任务没有开始过，否则就可以获取到TASK信息从而获取之前的下载进度。

需求就是用户可能会中断下载，能否在启动后获取中断前的下载进度？

**Comment by vzhilong** [comment]
或者需要在上层去持久化DOWNLOAD ID？

**Comment by Jacksgong** [comment]
#### 能否根据URL和PATH获取已有的TASK，如果TASK == NULL，说明这个任务没有开始过，否则就可以获取到TASK信息从而获取之前的下载进度。

- `FileDownloader#getTotal`
- `FileDownloader#getSofar`

参考demo中的任务管理案例

#### 用户可能会中断下载，能否在启动后获取中断前的下载进度？

`DownloadListener#pending`会带回数据库中上一次的进度。
