### ISSUE TITLE
Create parent directory failed

### ISSUE THREAD

**Issue by susirsusir** [lingochamp/FileDownloader#807]
download : https://miscimg01.jiaoliuqu.com/4005121502958303.zip;
下载文件，下载完成应该是/storage/emulated/0/xingjiabi/live/AiyaEffect/4005121502958303.zip
才对，但是报错。
Create parent directory failed, please make sure you have permission to create file or directory on the path: /storage/emulated/0/xingjiabi/live/AiyaEffect 
 [com.liulishuo.filedownloader.DownloadTaskHunter.prepare(DownloadTaskHunter.java:546), 
 com.liulishuo.filedownloader.DownloadTaskHunter.intoLaunchPool(DownloadTaskHunter.java:371),
 com.liulishuo.filedownloader.DownloadTask.startTaskUnchecked(DownloadTask.java:326), 
 com.liulishuo.filedownloader.DownloadTask.start(DownloadTask.java:305), 
 com.xingjiabi.shengsheng.live.aiyaeffect.AiyaEffectHelper.downloadEffect(AiyaEffectHelper.java:327), 
 com.xingjiabi.shengsheng.live.aiyaeffect.AiyaEffectHelper$7.handleMessage(AiyaEffectHelper.java:424), 
 android.os.Handler.dispatchMessage(Handler.java:102), 
 android.os.Looper.loop(Looper.java:136),
 android.app.ActivityThread.main(ActivityThread.java:5128), 
 java.lang.reflect.Method.invokeNative(Native Method), 
 java.lang.reflect.Method.invoke(Method.java:515), 
 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893), 
 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702), 
 dalvik.system.NativeStart.main(Native Method)]
打开文件管理器，在/storage/emulated/0/xingjiabi/live有一个AiyaEffect的文件

**Comment by ApacheJondy** [comment]
Do  you have permission ? 权限有没申请，如果是M版本及以上，请注意添加动态申请权限的代码。。

**Comment by susirsusir** [comment]
@ApacheJondy 权限是有的，在下载之前获取sdk权限以及写权限都是正常的

**Comment by rantianhua** [comment]
在开始下载前，需要确保文件的父目录存在，如果不存在则需要创建目录。根据日志是因为执行 `file.mkdirs()` 操作之后检查文件依然不存在，抛出了上述错误。 如果你想操作 /storage/emulated/0 目录，请务必确保两件事：一是要有  `WRITE_EXTERNAL_STORAGE` 权限；二是在使用之前要用 `getExternalStorageState()` 检查当前目录的状态。不过通常不建议直接操作 /storage/emulated/0 目录，详情可参考：https://developer.android.com/reference/android/os/Environment.html#getExternalStorageDirectory()

**Comment by rantianhua** [comment]
No response for a long time.
