### ISSUE TITLE
【求解】下载大文件（500M）时，相比小文件（50M），FileDownloadListener方法progress(BaseDownloadTask task, int soFarBytes, int totalBytes)的更新频率慢了很多。

### ISSUE THREAD

**Issue by ApacheJondy** [lingochamp/FileDownloader#808]
下载一个游戏apk时，大概500M，发现 progress(BaseDownloadTask task, int soFarBytes, int totalBytes)的更新频率简直太满了，差不多10~15s左右更新一次；而小文件一般几十M的，通常progress更新的很快。
试过更大一点的差不多900M的，更慢了。
通过FileDownloadListener 的progress(BaseDownloadTask task, int soFarBytes, int totalBytes)，来更新显示速度，怎么保证能在5秒或者短时间内能更新呢？

**Comment by stanhe** [comment]
FileDownloader#setCallbackProgressMinInterval and FileDownloader#setCallbackProgressTimes

**Comment by 425540302** [comment]
层主你这个问题了解决了没有，我也遇到了

**Comment by rantianhua** [comment]
@stanhe 说的就是正确的解决方案。
