### ISSUE TITLE
ANR 

### ISSUE THREAD

**Issue by kangshifu** [lingochamp/FileDownloader#809]
ANR in com.liulishuo.filedownloader.demo (com.liulishuo.filedownloader.demo/.performance.PerformanceTestActivity)
                                                  PID: 15714
                                                  Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 7.  Wait queue head age: 5661.2ms.)

**Comment by rantianhua** [comment]
It's possible to occur this problem in FileDownloader, especially in old device. However, OkDownload solves it and welcome to try it.
