### ISSUE TITLE
如果一个任务一开始就异常结束，重启后就无法获取Task状态？

### ISSUE THREAD

**Issue by vzhilong** [lingochamp/FileDownloader#812]
#### Before Issue

1. Please search on the [Issues](https://github.com/lingochamp/FileDownloader/issues)
2. Please search on the [wiki](https://github.com/lingochamp/FileDownloader/wiki)
3. Please set `FileDownloadLog.NEED_LOG=true` and review the Logcat output from main process and `:filedownloader` process ( pay attention to Warn and Error level logcat)

#### Issue

1. What problem do you get?
2. Which version of FileDownloader are you using when you produce such problem?
3. How to reproduce such problem?
4. Do you set `FileDownloadLog.NEED_LOG=true`?
5. Could you please reproduce this problem and provide all main process and `:filedownloader` process logcat 
6. Can you fix it by yourself and request PR, if not, what's problem do you get when you try to fix it

>P.S. If you don't know how to get `:filedownloader` process, it's recommended to using `pidcat` to just filter all your application logcat, or define `process.non-separate=true` on [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)

---

如题，或者说，BaseDownloadTask.start之后，还需要什么条件才能从FileDownloader.getImpl中查询到这个任务的状态？

**Comment by vzhilong** [comment]
我看到CustomComponentHolder.maintainDatabase会清理异常、下载完成的记录。

**Comment by rantianhua** [comment]
如果在非下载状态想要获取任务的状态，需要确保 FileDownloaderService 已经开启，具体使用方法可参考 #1248 。
