### ISSUE TITLE
下载、暂停状态切换有时候会重新下载，已有错误log，请帮忙看一下

### ISSUE THREAD

**Issue by lxbestno1** [lingochamp/FileDownloader#815]
如题、错误日志为：FileDownloader.FileDownloadManager: 1623258047 status is[3](not finish) & but not in the pool

**Comment by Jacksgong** [comment]
旧版本有可能遇到。你是用哪个版本呢?

**Comment by lxbestno1** [comment]
已更新至1.6.8版本

**Comment by Jacksgong** [comment]
1.6.8版本还有这个问题? 频繁切换会重新下载?

**Comment by lxbestno1** [comment]
是这样的、一个应用点击暂停、立即点击继续下载就会重新下载，暂停后间隔几秒钟就会断点续传

**Comment by Jacksgong** [comment]
旧版本有可能。1.6.8版本专门修复了这个问题，并且在demo中单任务测试中快速的暂停启动来回测试过。具体你可以clone demo project下来试试。

**Comment by lxbestno1** [comment]
可否请问一下出现这个问题的大概原因是什么，以及1.6.8版本里初始化调用 FileDownloader.setupOnApplicationOnCreate(this)就可以了吗

**Comment by lxbestno1** [comment]
还在么，我发现这里暂停了立即继续下载这个问题是必现的，但是间隔一会几乎是不复现的，可否请问一下这个异常发生的原因，我好定位一下

**Comment by Jacksgong** [comment]
参考这里: https://github.com/lingochamp/FileDownloader/issues/793#issuecomment-336370126

更多的可以参考下[迭代日志](https://github.com/lingochamp/FileDownloader/blob/master/CHANGELOG-ZH.md)中1.6.7与1.6.8部分以及相关commit.

**Comment by Jeffin21** [comment]
same problem in 1.6.8

**Comment by ViTess** [comment]
用FileDownloadSerialQueue来快速start、pause也会出现这种重新下载的情况

**Comment by ViTess** [comment]
@Jacksgong 我使用demo中的单任务测试，在快速点击的情况下也会重新下载。
现在在我的项目内，如果快速start、pause，也会出现but not in the pool的情况，然后回调completed，基本上能重现

**Comment by ViTess** [comment]
今天跟进了一下代码，初步认为是在重复start、pause期间，线程没有执行到位，导致状态没有及时设置到当前下载任务对应的model中。目前的解决办法是在FileDownloadManager.pause(int id)方法中，提前给model设置status：

```java
    public boolean pause(final int id) {
        if (FileDownloadLog.NEED_LOG) {
            FileDownloadLog.d(this, "request pause the task %d", id);
        }

        final FileDownloadModel model = mDatabase.find(id);
        if (model == null) {
            return false;
        }

        //TODO:20171208 fix
        model.setStatus(FileDownloadStatus.paused);

        mThreadPool.cancel(id);
        return true;
    }
```

这样可以避免重新下载，但是会导致另一个现象：当多次开始、暂停时，有几率出现`FileDownloadGiveUpRetryException`异常。异常的log为：

`12-08 16:43:04.957 16259-16259/com.liulishuo.filedownloader.demo W/System.err: com.liulishuo.filedownloader.exception.FileDownloadGiveUpRetryException: sofar[13720622] not equal total[37630310]
12-08 16:43:04.957 16259-16259/com.liulishuo.filedownloader.demo W/System.err:     at com.liulishuo.filedownloader.download.DownloadStatusCallback.interceptBeforeCompleted(DownloadStatusCallback.java:393)
12-08 16:43:04.957 16259-16259/com.liulishuo.filedownloader.demo W/System.err:     at com.liulishuo.filedownloader.download.DownloadStatusCallback.onCompletedDirectly(DownloadStatusCallback.java:191)
12-08 16:43:04.957 16259-16259/com.liulishuo.filedownloader.demo W/System.err:     at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.run(DownloadLaunchRunnable.java:353)
12-08 16:43:04.957 16259-16259/com.liulishuo.filedownloader.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-08 16:43:04.957 16259-16259/com.liulishuo.filedownloader.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-08 16:43:04.957 16259-16259/com.liulishuo.filedownloader.demo W/System.err:     at java.lang.Thread.run(Thread.java:818)`

推测出现异常是因为状态提前设置了pause，而在DownloadLaunchRunnable.run()方法中，会先判断状态是否为pending，否则直接return，然后进入run()方法中最后的finally代码块。

**Comment by ViTess** [comment]
目前测试出另一个问题：单任务时重复开始、暂停，次数过多之后，会出现SocketTimeout的异常，或者过了很久时间都无法下载的现象，是否过多的生成task、暂停task导致内部的连接池无法释放多余的Socket？我使用okhttp作为网络链接 @Jacksgong

**Comment by Jacksgong** [comment]
@ViTess `SocketTimeout` 是网络异常，如果timeout时间太长，可以参考readme文档，进行定制。

**Comment by rantianhua** [comment]
已在 #949 修复
