### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by ainiyiwan** [lingochamp/FileDownloader#816]
1. What problem do you get?
正在做一个类似应用市场的项目  现在有一个问题就是  我在应用列表里点击其中的一个条目进行下载 然后列表里需要监听进度 同时点击的那个条目需要加入到应用下载管理的一个单独的界面 这个界面也需要监听下载进度 两个界面可能会来回切换 能同时监听吗？
2. Which version of FileDownloader are you using when you produce such problem?
我用的是最新的版本
望回复 非常感谢

**Comment by Jacksgong** [comment]
参考这里: https://github.com/lingochamp/FileDownloader/issues/103#issuecomment-209173124
