### ISSUE TITLE
How can I start (resume) downloading at specific byte offset?

### ISSUE THREAD

**Issue by vadimgoroshevsky** [lingochamp/FileDownloader#819]
Hi, thank you for this amazing library. My problem is that when I start downloading a file and downloading stops for a reason (internet disappears, for example), I would like to save the current `soFarBytes` and after that, when I will open the app next time, to start new task with saved `soFarBytes` offset, like `--continue-at` argument in `curl` utility. Thanks!

**Comment by rantianhua** [comment]
FileDownloader supports downloading from breakpoints, you just create a same task and start it, FileDownloader will handle the rest.
