### ISSUE TITLE
在eclipse中将下载的library用作引用library时，出现下面的异常信息，导致直接出现下载出错error

### ISSUE THREAD

**Issue by ishuqi** [lingochamp/FileDownloader#82]
04-05 11:39:03.215: I/art(27820): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.RetryableSink>
04-05 11:39:03.216: I/art(27820): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.RetryableSink>
04-05 11:39:03.222: I/art(27820): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.HttpEngine$2>
04-05 11:39:03.222: I/art(27820): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.HttpEngine$2>
04-05 11:39:03.237: I/art(27820): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.RetryableSink>
04-05 11:39:03.246: I/art(27820): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.RetryableSink>
04-05 11:39:03.250: I/art(27820): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.RetryableSink>
04-05 11:39:03.251: I/art(27820): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.RetryableSink>

**Comment by Jacksgong** [comment]
通过这个日志，无法定位到问题。

eclipse，参考下这个issue: #43 中的这个 [issuecomment-192182054](https://github.com/lingochamp/FileDownloader/issues/43#issuecomment-192182054)

**Comment by ishuqi** [comment]
我直接是用的你的demo中的TasksManagerDemoActivity，在application中执行FileDownloader.init，manifest中也有声明下载的服务FileDownloadService，然后点击start按钮后就出现上面的异常，UI上显示就是"状态：出错"

**Comment by Jacksgong** [comment]
根据你的描述，我估计是jar包导入问题([Android studio java module does not compile static jar files for use at runtime](https://code.google.com/p/android/issues/detail?id=186012)) ，如果用eclipse的话，按照我在 #43 上面的描述重新操作下。然后clean re-build下试试。

**Comment by ishuqi** [comment]
@Jacksgong 按照你在#43描述步骤，下载 library-0.2.0-sources.jar上面的 library-0.2.0.aar ，然后用zip工具打开，取其中的 classes.jar放到demo中的libs目录下，clean后重新安装还是一样的问题。

**Comment by ishuqi** [comment]
04-05 13:25:51.353: I/art(15085): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.RetryableSink>
04-05 13:25:51.354: I/art(15085): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.RetryableSink>
04-05 13:25:51.358: I/art(15085): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.HttpEngine$2>
04-05 13:25:51.360: I/art(15085): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.HttpEngine$2>
04-05 13:25:51.373: I/art(15085): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.RetryableSink>
04-05 13:25:51.378: I/art(15085): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.RetryableSink>
04-05 13:25:51.383: I/art(15085): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.RetryableSink>
04-05 13:25:51.384: I/art(15085): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.RetryableSink>
04-05 13:25:52.414: I/art(15070): Background sticky concurrent mark sweep GC freed 2906(247KB) AllocSpace objects, 0(0B) LOS objects, 16% free, 1831KB/2MB, paused 16.909ms total 35.464ms

**Comment by ishuqi** [comment]
04-05 11:39:03.215: I/art(27820): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.RetryableSink>
04-05 11:39:03.216: I/art(27820): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.RetryableSink>
04-05 11:39:03.222: I/art(27820): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.HttpEngine$2>
04-05 11:39:03.222: I/art(27820): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.HttpEngine$2>
04-05 11:39:03.237: I/art(27820): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.RetryableSink>
04-05 11:39:03.246: I/art(27820): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.RetryableSink>
04-05 11:39:03.250: I/art(27820): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.RetryableSink>
04-05 11:39:03.251: I/art(27820): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.RetryableSink>

**Comment by ishuqi** [comment]
Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.RetryableSink>
Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.http.HttpEngine$2>

**Comment by ishuqi** [comment]
![image 1](https://cloud.githubusercontent.com/assets/7396663/14272138/a037a194-fb32-11e5-828e-b3b963d11fce.png)

**Comment by Jacksgong** [comment]
这句log不是我打的，就这一句log，我一时半会无法追踪到，其次，我在网络上面稍微搜索了下，应该是jar包引入的问题。所以，你用Eclipse，你先查查看有没有解决方案。我等有空了再看看，之前应该是有人在Eclipse导入成功的，就是用我上面的那个方案。或者你直接fork源码，转成eclipse试试看？

> P.S：我实在无法理解，为什么还有人在用Eclipse做Android开发，而不用Android studio。这也是为什么项目README中我没有给出Eclipse适配的原因。

**Comment by ishuqi** [comment]
@Jacksgong  搞定了  我加上okio这个jar就可以了

**Comment by Jacksgong** [comment]
:100:  

为什么需要用到okio，你引用的是低版本的okhttp吗？

**Comment by ishuqi** [comment]
之前用的是okhttp-3.2.0，我看到你写的是依赖3.1.2，然后就改成3.1.2的jar了，依然有问题，但是再加上okio后就好了。

**Comment by Jacksgong** [comment]
:+1: 那我知道了，估计是有依赖关系，gradle这边是直接引用aar，并且会处理这层关系。而eclipse不会。

> P.S: 今天会发布新版本的FileDownloader 到时候会更上新版本的okhttp。
