### ISSUE TITLE
您好！想请教个问题，比如有A B C三个界面，我在a界面点击下载后，C界面就会出现一个条目，显示这个下载的回调，然后我在B界面点击下载后，C会在增加一个条目显示B下载的回调，请问这个支持吗！项目中要用到，希望能尽快回复~非常感谢！

### ISSUE THREAD

**Issue by 541954852** [lingochamp/FileDownloader#824]
#### Before Issue

1. Please search on the [Issues](https://github.com/lingochamp/FileDownloader/issues)
2. Please search on the [wiki](https://github.com/lingochamp/FileDownloader/wiki)
3. Please set `FileDownloadLog.NEED_LOG=true` and review the Logcat output from main process and `:filedownloader` process ( pay attention to Warn and Error level logcat)

#### Issue

1. What problem do you get?
2. Which version of FileDownloader are you using when you produce such problem?
3. How to reproduce such problem?
4. Do you set `FileDownloadLog.NEED_LOG=true`?
5. Could you please reproduce this problem and provide all main process and `:filedownloader` process logcat 
6. Can you fix it by yourself and request PR, if not, what's problem do you get when you try to fix it

>P.S. If you don't know how to get `:filedownloader` process, it's recommended to using `pidcat` to just filter all your application logcat, or define `process.non-separate=true` on [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)

---

请在Issue前认真的跟进上面提到的建议，这样将可以极大的加快你遇到问题的处理。

**Comment by ainiyiwan** [comment]
参考这里: #103

**Comment by 541954852** [comment]
我该怎么在C中显示出下载清单与回调呀，有什么方法吗，还是说只能通过广播发送状态在C改

**Comment by Jacksgong** [comment]
具体可以看 @ainiyiwan 提到的，其实上层这类问题完全可以自己实现的，FileDownloader本身支持多文件、单文件、并行、串行、分块等下载。
