### ISSUE TITLE
怎么跟TasksManagerDemoActivity交互？

### ISSUE THREAD

**Issue by MickeyBadBad** [lingochamp/FileDownloader#827]
引用了Demo中的TasksManagerDemoActivity来做下载管理页面，但是在其他Activity用FileDownloader创建下载的话，下载管理中是看不到的。
然后我改成用TaskManager来AddTask，然后用Model创建BaseDownloadTask启动。
可以显示在下载管理页面了，也能启动下载了。但是不能用TasksManagerDemoActivity中自定义的FileDownloadListner，所以就是各种毛病，试图不能更新之类的。

卡在这个问题了，跪求解决思路。

Demo能不能优化优化，TasksManager应该弄成可交互的吧～

**Comment by MickeyBadBad** [comment]
发现 #103 已经说明了想要的类似功能，但是是要写自己的Manager。。。

Demo中的TasksManager除了不能外部创建任务（还有Holder不能刷新等问题外），其他功能都是好的。

所以有没有可能在Demo现有的TasksManager上增加这个功能？毕竟Manager的作用就应该是管理外部创建的任务。

**Comment by rantianhua** [comment]
如果你要跨 Activity 进行交互，还是请参考 #103 。

Demo 中的 TasksManager 只是展示如果自己管理自己的下载任务，不涉及多个 Activity 间的交互。
