### ISSUE TITLE
FileDownloadSerialQueue 怎么获取下载进度

### ISSUE THREAD

**Issue by susirsusir** [lingochamp/FileDownloader#829]
FileDownloadSerialQueue 怎么获取下载进度？
是否只能单个BaseDownloadTask进行监听下载完成及失败请求？
FileDownloadSerialQueue应该是串行下载吧，能否设置为比如说同时两个线程下载？

**Comment by rantianhua** [comment]
因为这个 Queue 是动态的，所以确实没法做总任务的进度。
