### ISSUE TITLE
How I get all download task info list when my app is restored from a crash or a reboot

### ISSUE THREAD

**Issue by ericxiang** [lingochamp/FileDownloader#83]
当我的APP崩溃或者被杀死以后，当APP重新启动时，我如何能比较方便的获取之前进行中的所有下载任务状态，需要我自己通过DB存储下载ID去查询吗？

**Comment by Jacksgong** [comment]
是的，最好是你的业务层为你的显示以及业务相关做一层存储，当然你也可以直接通过 `FileDownloadUtils#generateId(url,path)`来生成对应的 DownloadId，再通过 `FileDownloader#getStatus(downloadId)` 来进行获取。

具体情况，你可以参考下:  `TasksManagerDemoActivity`。

**Comment by ericxiang** [comment]
好的，了解了，非常感谢！

**Comment by Jacksgong** [comment]
:100:

**Comment by ericxiang** [comment]
作者你好，我今天在尝试自己封装一个DownloadManager的时候有一些疑惑：
1. 需求是，用户点击暂停/继续按钮控制下载任务
2. 我尝试用pause(downloadId）暂停下载任务，但没有找到resume(downloadId)的API
3. 我发现有pause(filedownloadlistener)的API和start(filedownloadlistener,...)的API，但貌似不适用于我的场景，pause之后再调用start，并不能产生效果
4. 我尝试理解你的API设计思路：pause并不是Android自带DownloadManager的暂停。当我调用Pause之后，我需要使用FileDownloader.getImpl().create(url)，重新获取DownloadTask，并start这个任务，对吗？

P.S. downloadId是会出现为负的场景的对吗，如果我要使用一个默认值表示downloadId不存在，使用什么值会比较合适？
谢谢！
