### ISSUE TITLE
FileDownloader library not working 

### ISSUE THREAD

**Issue by karimi12** [lingochamp/FileDownloader#830]
hello 
i want use FileDownloader library.
i setup it with wik but it not working i use `FileDownloadLog.NEED_LOG=true` i understand that download service not running but two weeks ago FileDownloader library worked well.
please help me.
 i use this dependencies:
 compile 'com.afollestad.material-dialogs:core:0.9.4.5'
    compile 'com.github.dmytrodanylyk.android-process-button:library:1.0.4'
    compile 'com.amulyakhare:com.amulyakhare.textdrawable:1.0.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.5.1'
    compile 'com.flurry.android:analytics:7.0.0@aar'
    compile 'com.google.android.gms:play-services-analytics:11.2.2'

//    compile 'com.readystatesoftware.sqliteasset:sqliteassethelper:+'
    compile 'com.aurelhubert:ahbottomnavigation:2.1.0'
    compile 'cn.aigestudio.downloader:Downloader:1.4.3'
    compile 'de.hdodenhof:circleimageview:2.1.0'
    compile 'com.liulishuo.filedownloader:library:1.6.8'

**Comment by Jacksgong** [comment]
Sorry, I still don't know what problem do you get, could you please provide exception stack..

**Comment by karimi12** [comment]
i turn on log but i don't get any error!!!

**Comment by rantianhua** [comment]
Maybe you can show your code.

**Comment by rantianhua** [comment]
No response for a long time.
