### ISSUE TITLE
退出应用后，再次进入应用时下载队列问题

### ISSUE THREAD

**Issue by YangShaoXiong** [lingochamp/FileDownloader#831]
我设置了download.max-network-thread-count=2，当我添加3个以上任务时，其中处于pending状态的任务，这时候我在下载还没有完成的时候，退出应用，再次启动应用，这时候会出现处于pending状态的任务，点击重新启动它，会出现 FileDownloader.FileDownloader: request pause but not exist -176739817的警告。我确定我退出应用的时候调用了 FileDownloader.getImpl().pauseAll(); 我试了下demo中的TasksManagerDemoActivity功能，也存在同样的问题。@Jacksgong 麻烦有空看下这个问题。提前谢谢了。

**Comment by YangShaoXiong** [comment]
在新版本中1.6.9中已经解决这个问题。多谢作者。

**Comment by Jacksgong** [comment]
ok
