### ISSUE TITLE
App Crash!

### ISSUE THREAD

**Issue by ahao99** [lingochamp/FileDownloader#834]
crash happened in v1.6.8
main(1)
junit.framework.AssertionFailedError:

junit.framework.Assert.fail(Assert.java:50)
junit.framework.Assert.assertTrue(Assert.java:20)
com.liulishuo.filedownloader.FileDownloadMessenger.handoverMessage(FileDownloadMessenger.java:255)
com.liulishuo.filedownloader.FileDownloadMessageStation$UIHandlerCallback.dispose(FileDownloadMessageStation.java:169)
com.liulishuo.filedownloader.FileDownloadMessageStation$UIHandlerCallback.handleMessage(FileDownloadMessageStation.java:160)
android.os.Handler.dispatchMessage(Handler.java:98)
android.os.Looper.loop(Looper.java:154)
android.app.ActivityThread.main(ActivityThread.java:6088)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by ahao99** [comment]
# main(1)

junit.framework.AssertionFailedError

**Comment by ahao99** [comment]
hannped in v1.6.8

**Comment by rantianhua** [comment]
Duplicate with #943
