### ISSUE TITLE
当在Application中判断是否下载进程时，报ExceptionInInitializerError

### ISSUE THREAD

**Issue by ykrank** [lingochamp/FileDownloader#841]
一开始只在主进程中初始化FileDownloader，结果接收不到Listener，于是打算在下载进程中也初始化。然而一旦使用FileDownloadUtils#isDownloaderProcess判断是否下载进程，就会在下载进程中crash

**Comment by Jacksgong** [comment]
初始化可以参考下 [文档](https://github.com/lingochamp/FileDownloader/wiki/Initialization)。

---

如果出现异常，可否提供下Exception的错误栈，我看下。
