### ISSUE TITLE
request pause but not exists 11

### ISSUE THREAD

**Issue by iamZ2z** [lingochamp/FileDownloader#843]
不能暂停到，提示这样错误

**Comment by Jacksgong** [comment]
这个是任务不存在，并没有在运行。

你收到这个提示的同时，还有相关进度回调吗？

**Comment by iamZ2z** [comment]
已经没有进度回调了，是在点击了下载之后没反应，事实上还是在下载的就是无法暂停

**Comment by iamZ2z** [comment]
11为id，停止不了该id，我是使用SingleTaskTestActivity的下载方法，然后pauseAll()可以就是pause(id)不行

**Comment by iamZ2z** [comment]
发现问题了，打自己脸，从后台上下载item获取的id（即position），在id=createDownloadTask(argv[])时会发送变化，导致停止不了

**Comment by Jacksgong** [comment]
okay...
