### ISSUE TITLE
The FileDownloader  is removing the entry from "default database" if error occurs and user closes the app. How to stop it

### ISSUE THREAD

**Issue by Kshitij1792** [lingochamp/FileDownloader#844]
I need to have the status of a file that either failed/retry and want to restart that when user clicks on the Reload/Resume button. But as the FileDownloader is removing the entry from database on closing the app I cant find it after resatart.
 Could you tell me how to stop the lib  from removing the entries whose status was either failed/retry???

**Comment by Jacksgong** [comment]
1. If the task is failed or retried, the data would be retained on the database, and after you restart it, it will be resumed if it's possible.
2. The data will be removed from the database only if: 1) the task is complete downloading (or) 2) the data on the database is dirty to resume which checked when the download process is launched or task is started.
3.  Please using the latest version of FileDownloader on the old version maybe the resume behavior has some problem
4. If you want to define your own database please move to [here](https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component).

**Comment by Kshitij1792** [comment]
Thanks for the quick reply.
About your 4th point,  I indeed want to have all this status related info in my database as well if possible, So is it what you meant when you said I can define my own database??? How can I do that?

Also if The app is force closed I was not getting the proper TIME_STAMP of the files download completion. If I use my Custom Implementation for store these values directly as the Default Databse get updated from service itself, Would this give me correct status?
