### ISSUE TITLE
下载404的url不进error

### ISSUE THREAD

**Issue by wangzhiqiang** [lingochamp/FileDownloader#846]
在设置了 参数 file.non-pre-allocation=true 后 如果下载地址是一个不存在的地址,下载进程 NPE并无线重启下载该文件.

**Comment by Jacksgong** [comment]
我设置了`file.non-pre-allocation=true`并且在1.6.8的demo上，分别测试了设置10次重试，以及没有设置重试的情况，均表现正常，回调404的`error`。

请问有无其他复现路径，可否在demo上进行复现呢？

![image](https://user-images.githubusercontent.com/6176417/33897920-c5df3736-dfa1-11e7-951a-e09b50e12887.png)

**Comment by rantianhua** [comment]
No response for a long time.
