### ISSUE TITLE
Question: How to use the multi-thread downloading?

### ISSUE THREAD

**Issue by ali-idrizi** [lingochamp/FileDownloader#847]
I saw that a while ago the multi-thread downloading a file was implemented in the class **DownloadLaunchRunnable**? I have been trying to use this class but had no success so far. Can someone please provide a sample code on how to use it?

**Comment by rantianhua** [comment]
`DownloadLaunchRunnable ` is not a public class, you don't need to use it in your own code. FileDownloader will manage multi-thread downloading, you can custom `ConnectionCountAdapter` to decide how many threads to start downloading if you want. The default implementation is `DefaultConnectionCountAdapter`. You can custom it during you init the FileDownloader in `Application#onCreate()` method, just like below:

```
 FileDownloader.setupOnApplicationOnCreate(this)
                .connectionCountAdapter(new FileDownloadHelper.ConnectionCountAdapter() {
                    @Override
                    public int determineConnectionCount(int downloadId, String url, String path, long totalLength) {
                        return 0;
                    }
                })
                .commit();
```
