### ISSUE TITLE
403 error on this URL

### ISSUE THREAD

**Issue by Jeffin21** [lingochamp/FileDownloader#848]
403 error on this URL http://hindimp3.mobi/hindi/load/A-Z/Y/Yeh%20Jawaani%20Hai%20Deewani%20(2013)%20HQ/Ilahi_-_(HindiMp3.Mobi).mp3

D/FileDownloader.FileDownloadUtils: can't continue -953053119 file not suit, exists[FALSE], directory[FALSE]
 D/FileDownloader.ConnectTask: -953053119 request header {Range=[bytes=0-]}
filedownloader D/FileDownloader.FileDownloadUtils: etag find null for task(-953053119)
 D/FileDownloader.MessageSnapshotGate: ~~~callback -953053119 old[5] new[-1] 1
11-24 16:05:04.838 18312-19124/ V/FileDownloader.FileDownloadList: remove -953053119@com.liulishuo.filedownloader.DownloadTask@886ae09 left -1 0
 D/FileDownloader.FileDownloadMessenger: notify error -953053119@com.liulishuo.filedownloader.DownloadTask@886ae09 com.liulishuo.filedownloader.exception.FileDownloadHttpException: response code error: 403, 
                                                                                       request headers: {Range=[bytes=0-]} 
                                                                                       response headers: {null=[HTTP/1.1 403 Forbidden], Accept-Ranges=[bytes], Cache-Control=[private, no-cache, no-store, must-revalidate, max-age=0], Connection=[Keep-Alive], Content-Length=[1139], Content-Type=[text/html], Date=[Fri, 24 Nov 2017 10:33:29 GMT], Pragma=[no-cache], X-Android-Received-Millis=[1511579104778], X-Android-Response-Source=[NETWORK 403], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1511579104371]}
11-24 16:05:04.839 18312-19124/ V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@e55080e by -1 
11-24 16:05:04.849 18312-18312/ V/SRL: Exception :com.liulishuo.filedownloader.exception.FileDownloadHttpException: response code error: 403, 
                                                      request headers: {Range=[bytes=0-]} 
                                                      response headers: {null=[HTTP/1.1 403 Forbidden], Accept-Ranges=[bytes], Cache-Control=[private, no-cache, no-store, must-revalidate, max-age=0], Connection=[Keep-Alive], Content-Length=[1139], Content-Type=[text/html], Date=[Fri, 24 Nov 2017 10:33:29 GMT], Pragma=[no-cache], X-Android-Received-Millis=[1511579104778], X-Android-Response-Source=[NETWORK 403], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1511579104371]}
11-24 16:05:04.849 18312-18312/ V/SRL: Error:response code error: 403, 
                                                      request headers: {Range=[bytes=0-]} 
                                                      response headers: {null=[HTTP/1.1 403 Forbidden], Accept-Ranges=[bytes], Cache-Control=[private, no-cache, no-store, must-revalidate, max-age=0], Connection=[Keep-Alive], Content-Length=[1139], Content-Type=[text/html], Date=[Fri, 24 Nov 2017 10:33:29 GMT], Pragma=[no-cache], X-Android-Received-Millis=[1511579104778], X-Android-Response-Source=[NETWORK 403], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1511579104371]}
11-24 16:05:04.849 18312-18312/ W/System.err: com.liulishuo.filedownloader.exception.FileDownloadHttpException: response code error: 403, 
11-24 16:05:04.849 18312-18312/W/System.err:  request headers: {Range=[bytes=0-]} 
11-24 16:05:04.849 18312-18312/ W/System.err:  response headers: {null=[HTTP/1.1 403 Forbidden], Accept-Ranges=[bytes], Cache-Control=[private, no-cache, no-store, must-revalidate, max-age=0], Connection=[Keep-Alive], Content-Length=[1139], Content-Type=[text/html], Date=[Fri, 24 Nov 2017 10:33:29 GMT], Pragma=[no-cache], X-Android-Received-Millis=[1511579104778], X-Android-Response-Source=[NETWORK 403], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1511579104371]}
11-24 16:05:04.849 18312-18312/ W/System.err:     at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.handleFirstConnected(DownloadLaunchRunnable.java:526)
11-24 16:05:04.849 18312-18312/ W/System.err:     at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.run(DownloadLaunchRunnable.java:268)
11-24 16:05:04.849 18312-18312/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-24 16:05:04.849 18312-18312/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-24 16:05:04.849 18312-18312/ W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by Jacksgong** [comment]
ok.. refer your another issue, capture request process on chrome, I find out  it can access because of it add `"User-Agent"` but we not, and then I check out `okhttp`, it will add `"User-Agent` if upper layer does not add it, So on the next version I will make the same things as `okhttp` do.

**Comment by Jeffin21** [comment]
Thanks !!

**Comment by Allyns** [comment]
I have solved this problem by adding `.addHeader("Referer", "download link" to addHeader;` I hope to help others.

**Comment by Seachal** [comment]
对我来说， 第一个版本服务端没有对文件下载进行鉴权限制，可以正常下载，第二个版本，服务端开始改造增加鉴权，对已经调用过一次的下载链接进行失效处理，我这边就会遇到下面这样的异常， 
 ```
ava.net.SocketException: Connection failed with request[{Range=[bytes=4073926-8147851], User-Agent=[FileDownloader/1.7.7]}] response[{null=[HTTP/1.1 403 Forbidden], Access-Control-Allow-Methods=[GET], Access-Control-Allow-Origin=[*], Connection=[keep-alive], Content-Length=[238], Content-Type=[text/html], Date=[Mon, 29 Jan 2024 02:42:16 GMT], EagleId=[907b1f2217064961368347077e], Server=[Tengine], Timing-Allow-Origin=[*], Via=[cache14.cn1306[,0]], X-Android-Received-Millis=[1706496136376], X-Android-Response-Source=[NETWORK 403], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1706496136196]}] http-state[403] on task[-891346639-1], which is changed after verify connection, so please try again.   
```
最终发现是因为 下载库默认开启断点续传。
<img width="1058" alt="image" src="https://github.com/lingochamp/FileDownloader/assets/14776606/9e08f13e-211b-4e71-b8d3-70254f42e00d">


> Range 是一个请求首部，告知服务器返回文件的哪一部分。在一个 Range 首部中，可以一次性请求多个部分，服务器会以 multipart 文件的形式将其返回。如果服务器返回的是范围响应，需要使用 [206](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/206) Partial Content 状态码。假如所请求的范围不合法，那么服务器会返回 [416](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/416) Range Not Satisfiable 状态码，表示客户端错误。服务器允许忽略 Range 首部，从而返回整个文件，状态码用 [200](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/200) 。

所以我这边的情况是，服务端做修改适配客户端的断点续传，客户端不需要修改。
