### ISSUE TITLE
基于FileDownloader封装自己的DownloadManager碰到的一些疑惑

### ISSUE THREAD

**Issue by ericxiang** [lingochamp/FileDownloader#85]
作者你好，我今天在尝试自己封装一个DownloadManager的时候有一些疑惑：
1. 需求是，用户点击暂停/继续按钮控制下载任务
2. 我尝试用pause(downloadId）暂停下载任务，但没有找到resume(downloadId)的API
3. 我发现有pause(filedownloadlistener)的API和start(filedownloadlistener,...)的API，但貌似不适用于我的场景，pause之后再调用start，并不能产生效果
4. 我尝试理解你的API设计思路：pause并不是Android自带DownloadManager的暂停。当我调用Pause之后，我需要使用FileDownloader.getImpl().create(url)，重新获取DownloadTask，并start这个任务，对吗？

P.S. downloadId是会出现为负的场景的对吗，如果我要使用一个默认值表示downloadId不存在，使用什么值会比较合适？
谢谢！

**Comment by Jacksgong** [comment]
恩。

是的 `pause()` 之后，重新创建相同任务 `start()` 会自动断点续传的，就是你的resume

`downloadId` 存在负数的场景，可以用0表示一个不存在的downloadId。
