### ISSUE TITLE
How to get the JSON Error response from lib.

### ISSUE THREAD

**Issue by Kshitij1792** [lingochamp/FileDownloader#851]
If we have the auth_token in the URL, which become invalid after some time.  I want to know the exact JSON response that the URL throws. How can I get that in FileDownloader lib.
     I checked the DefaultDatabse of the library. There it was sometimes Software initiated error/somtimes server error(like Server error 400), But I couldn't find the JSON error message in it too.
How could I get it in this downloader lib.

**Comment by rantianhua** [comment]
400 is a client error instead server error. It means the server cannot understand your request. For your case, it is probably because the token is invalid.

---  

What do you mean the `JSON error message`? Is the message returned by the server, or you mean response header?

**Comment by rantianhua** [comment]
No response for a long time.
