### ISSUE TITLE
网络不好时由于unexpected end of stream进度回滚

### ISSUE THREAD

**Issue by vzhilong** [lingochamp/FileDownloader#852]
在下载包比较大时，非常容易出现unexpected end of stream，
比如我设置了10个最大下载线程、10次重试，但是我也只看到了5个unexpected end of stream，
然后就下载失败了。
比较好的情况就是看到多次unexpected end of stream后，下载进度回滚了，有时候回滚到一半，有时候直接回滚到0%。

**Comment by yangxiaoyafly** [comment]
我也是有遇到这个问题，有时候下载出现error后重试，进度很多时候都直接变成0%，然后又重新下载

**Comment by rantianhua** [comment]
@vzhilong @yangxiaoyafly 
有些情况下确实会使断点失效，比如后端返回的 Http 码为 416、200，或者 Etag 有更新。所以希望能提供完整的 FileDownloader 的日志，包括主进程和 filedownloader 的进程。

---  

另外 @yangxiaoyafly 说下载出现 error 时重试，很多时候进度也变为 0 ，也希望提供相关日志，这样对分析问题能提供有效帮助。

**Comment by Jeffin21** [comment]
@rantianhua  this problem not because of server and i think this problem not seen in latest version of file downloader

**Comment by yangxiaoyafly** [comment]
这个我有去断点看过源码， 是http response中没有“Etag”标签，所以该框架会把本地文件的下载状态重置。这样继续下载的时候会出现速度为负数

**Comment by yangxiaoyafly** [comment]
但是不清楚 为什么服务器有时候没有返回Etag

**Comment by rantianhua** [comment]
@yangxiaoyafly 如果 Etag 没有返回，那么和之前的 Etag 就不能匹配，所以根据 http 协议，只能认为内容发生了变化，所以之前断点下载的数据需要丢弃重新下载。所以如果你认为内容没有发生变化的话，那么服务器端应该返回相同的 Etag ，否则的话这就是服务器的问题，需要你们服务器的同学去解决。

**Comment by Jeffin21** [comment]
Problem happen when the retry happens major issue

**Comment by Jeffin21** [comment]
this issues still in latest file downloader version , please fix this . Thank You

**Comment by rantianhua** [comment]
Please refer to #949
