### ISSUE TITLE
莫名其妙下载不动了，手动暂停后，获取状态一直为progress

### ISSUE THREAD

**Issue by lxpeng** [lingochamp/FileDownloader#857]
1.莫名其妙下载不动了，手动暂停后，获取状态一直为progress
2. 杀掉退出APP，杀掉进程后，才可恢复正常

截取部分日志如下：

12-06 14:58:09.442 19617-19972/com.gtmc.test D/FileDownloader.MessageSnapshotGate: ~~~callback 1740509613 old[3] new[3] 1
12-06 14:58:09.446 19617-19972/com.gtmc.test D/FileDownloader.FileDownloadMessenger: notify progress 1740509613@com.liulishuo.filedownloader.DownloadTask@8d244c 86355043 86548501
12-06 14:58:10.924 19617-19972/com.gtmc.test D/FileDownloader.MessageSnapshotGate: ~~~callback 1740509613 old[3] new[-3] 1
12-06 14:58:10.930 19617-19972/com.gtmc.test V/FileDownloader.FileDownloadList: remove 1740509613@com.liulishuo.filedownloader.DownloadTask@8d244c left -3 0
12-06 14:58:10.943 19617-19972/com.gtmc.test D/FileDownloader.FileDownloadMessenger: notify block completed 1740509613@com.liulishuo.filedownloader.DownloadTask@8d244c FileDownloader-Flow-02
12-06 14:58:10.951 19617-20046/com.gtmc.test D/FileDownloader.FileDownloadMessenger: notify completed 1740509613@com.liulishuo.filedownloader.DownloadTask@8d244c
12-06 14:58:10.953 19617-20046/com.gtmc.test V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@befcc95 by -3 
12-06 14:58:35.095 19617-19617/com.gtmc.test D/FileDownloader.LaunchTaskPool: expire 0 tasks
12-06 14:58:43.218 19617-19617/com.gtmc.test D/FileDownloader.LaunchTaskPool: expire 0 tasks
12-06 15:06:08.709 19617-19617/com.gtmc.test D/FileDownloader.DownloadTask: setPath /data/user/0/com.gtmc.test/cache/ar/VR2017120501/1.1/high/car.zip
12-06 15:06:08.710 19617-19617/com.gtmc.test D/FileDownloader.DownloadTask: setListener com.yongyou.ui.ar.ARActivity$1$1@559d6bf
12-06 15:06:08.710 19617-19617/com.gtmc.test V/FileDownloader.DownloadTaskHunter: call start Url[http://ozkde5ivh.bkt.clouddn.com/file/ar/car.zip], Path[/data/user/0/com.gtmc.test/cache/ar/VR2017120501/1.1/high/car.zip] Listener[com.yongyou.ui.ar.ARActivity$1$1@559d6bf], Tag[null]
12-06 15:06:08.712 19617-20564/com.gtmc.test D/FileDownloader.FileDownloadMessenger: notify begin 1740509613@com.liulishuo.filedownloader.DownloadTask@48040ea
12-06 15:06:08.712 19617-19617/com.gtmc.test V/FileDownloader.DownloadTaskHunter: the task[1740509613] has been into the launch pool.
12-06 15:06:08.712 19617-20564/com.gtmc.test V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@d5f1fdb by 11 
12-06 15:06:08.713 19617-20564/com.gtmc.test V/FileDownloader.FileDownloadList: add list in all 1740509613@com.liulishuo.filedownloader.DownloadTask@48040ea 11 1
12-06 15:09:25.468 19617-20578/com.gtmc.test D/FileDownloader.FileDownloadMessenger: notify progress 1740509613@com.liulishuo.filedownloader.DownloadTask@48040ea 45642347 86548501

12-06 15:11:00.831 19617-19617/com.gtmc.test V/FileDownloader.DownloadTaskHunter: the task[1740509613] has been expired from the launch pool.
12-06 15:11:00.839 19617-19617/com.gtmc.test D/FileDownloader.FileDownloadMessenger: notify begin 1740509613@com.liulishuo.filedownloader.DownloadTask@48040ea
12-06 15:11:00.841 19617-19617/com.gtmc.test V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@d5f1fdb by -2 
12-06 15:11:00.843 19617-19617/com.gtmc.test V/FileDownloader.FileDownloadList: remove 1740509613@com.liulishuo.filedownloader.DownloadTask@48040ea left -2 0
12-06 15:11:00.845 19617-19617/com.gtmc.test D/FileDownloader.FileDownloadMessenger: notify paused 1740509613@com.liulishuo.filedownloader.DownloadTask@48040ea
12-06 15:11:00.846 19617-19617/com.gtmc.test V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@d5f1fdb by -2 

12-06 15:11:35.116 19617-19617/com.gtmc.test W/FileDownloader.FileDownloader: request pause but not exist 1740509613

**Comment by virengujariya** [comment]
have similar issue

**Comment by rantianhua** [comment]
This bug has been solved, you can know more from pull request #900
