### ISSUE TITLE
使用setPath(path, true); 文件下载成功后断开网络会调error，直接使用setPath(path）没有问题

### ISSUE THREAD

**Issue by DINGJIN90** [lingochamp/FileDownloader#859]
#### Before Issue

1. Please search on the [Issues](https://github.com/lingochamp/FileDownloader/issues)
2. Please search on the [wiki](https://github.com/lingochamp/FileDownloader/wiki)
3. Please set `FileDownloadLog.NEED_LOG=true` and review the Logcat output from main process and `:filedownloader` process ( pay attention to Warn and Error level logcat)

#### Issue

1. What problem do you get?
2. Which version of FileDownloader are you using when you produce such problem?
3. How to reproduce such problem?
4. Do you set `FileDownloadLog.NEED_LOG=true`?
5. Could you please reproduce this problem and provide all main process and `:filedownloader` process logcat 
6. Can you fix it by yourself and request PR, if not, what's problem do you get when you try to fix it

>P.S. If you don't know how to get `:filedownloader` process, it's recommended to using `pidcat` to just filter all your application logcat, or define `process.non-separate=true` on [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)

---

请在Issue前认真的跟进上面提到的建议，这样将可以极大的加快你遇到问题的处理。

**Comment by DINGJIN90** [comment]
@Jacksgong 麻烦帮忙看一下这个问题

**Comment by Jacksgong** [comment]
无法复现该问题，理论上来说，在下载成功后（回调`completed`），就不会再接收到任何回调了。

---

可否在demo中复现?

**Comment by DINGJIN90** [comment]
private void doDownload(final String url) {
        final File fileDir = new File(Environment.getExternalStorageDirectory() + "/image/tmp");
        if (!fileDir.isDirectory() || !fileDir.exists()) {
            fileDir.mkdirs();
        }
        FileDownloader.getImpl().create(url)
                .setPath(fileDir.getAbsolutePath(), true)
                .setListener(new FileDownloadSampleListener() {

                    @Override
                    protected void error(BaseDownloadTask task, Throwable e) {
                        super.error(task, e);
                    }

                    @Override
                    protected void completed(BaseDownloadTask task) {
                        super.completed(task);  
                }).start();
    }
这是我的部分代码，网络正常的情况下文件下载成功，此刻断掉所有网络包括wifi和移动，再进入应用就直接call error了，显示网络未连接找不到host name的error，但是文件已经下载好了。如果直接setPath(path)，不传第二个参数true，且参数path直接是文件路径，则网络断开后回调complete

**Comment by DINGJIN90** [comment]
`private void doDownload(final String url) {
final File fileDir = new File(Environment.getExternalStorageDirectory() + "/image/tmp");
if (!fileDir.isDirectory() || !fileDir.exists()) {
fileDir.mkdirs();
}
FileDownloader.getImpl().create(url)
.setPath(fileDir.getAbsolutePath(), true)
.setListener(new FileDownloadSampleListener() {

                @Override
                protected void error(BaseDownloadTask task, Throwable e) {
                    super.error(task, e);
                }

                @Override
                protected void completed(BaseDownloadTask task) {
                    super.completed(task);  
            }).start();
}`
这是我的部分代码，网络正常的情况下文件下载成功，此刻断掉所有网络包括wifi和移动，再进入应用就直接call error了，显示网络未连接找不到host name的error，但是文件已经下载好了。如果直接setPath(path)，不传第二个参数true，且参数path直接是文件路径，则网络断开后回调complete

**Comment by DINGJIN90** [comment]
`private void doDownload(final String url) {
final File fileDir = new File(Environment.getExternalStorageDirectory() + "/image/tmp");
if (!fileDir.isDirectory() || !fileDir.exists()) {
fileDir.mkdirs();
}
FileDownloader.getImpl().create(url)
.setPath(fileDir.getAbsolutePath(), true)
.setListener(new FileDownloadSampleListener() {

                @Override
                protected void error(BaseDownloadTask task, Throwable e) {
                    super.error(task, e);
                }

                @Override
                protected void completed(BaseDownloadTask task) {
                    super.completed(task);  
            }).start();
}
} `

**Comment by DINGJIN90** [comment]
@Jacksgong 区别就在于setPath(directory, true); 和 setPath(path)；理论上setPath(directory, true)，文件下载完成后断开网络也应该直接回调complete了，而事实上回调了error； 但是setPath(path)则正常。

**Comment by DINGJIN90** [comment]
@Jacksgong

**Comment by DINGJIN90** [comment]
@Jacksgong 断网后报错java.net.UnknownHostException: Unable to resolve host: No address associated with hostname；如果我不setPath()直接用默认的就没有问题，你看下我创建文件目录有没有问题，String fileDir = Environment.getExternalStorageDirectory() + "/Docker/image/tmp"; setPath(fileDir, true)；谢谢！

**Comment by DINGJIN90** [comment]
@Jacksgong 你的demo也是一样报错啊，文件下载到文件目录后断网，但是如果不setPath(path, true)则没有问题，文件下载成功后断网，加载之前下载成功的文件

**Comment by DINGJIN90** [comment]
@Jacksgong BaseDownloadTask#setPath(path, true), 此时给的路径是目录(path = directory/)，这种情况下，FileDownloader会先检查response回来的头中是否根据http协议带回文件名，如果有就使用response带回的，如果没有就将url做md5作为文件名。我看了下源码，如果没有setPath()会将url做md5作为文件名，我感觉是这里的问题

**Comment by Jacksgong** [comment]
好的，最近比较忙，我周末的时候跟进下看下。

**Comment by DINGJIN90** [comment]
ok~ 麻烦周末check一下

**Comment by Jacksgong** [comment]
@DINGJIN90 根据你的描述，我大概理解是：

### 文件已经下载完成，断开网络

**此时：** 如果使用`setPath(path)`的重新下载，会直接回调完成；如何使用`setPath(path, true)`会报网络异常

这个Case是完全符合预期的，因为如果指定的是目录，我们不得不重新建立网络连接来获取有效的文件名，如果网络异常，便直接返回网络错误；如果指定是文件，那么判定文件存在便直接返回完成。

---

你确定下是否是我描述的情况。无论提供的是文件名还是目录名除了上述逻辑其他下载逻辑都是一样的。

**Comment by DINGJIN90** [comment]
@Jacksgong 根据你的描述，也就是说不设置setPath，默认也是存储的路径也是文件路径，所以网络断开后依然可以获取到文件。那么，为何我设置setPath(path)后，依次下载多个文件到ViewPager后，文件会被覆盖，是我文件路径设置有问题？不是多任务下载，就是多个文件一个一个下载

**Comment by Jacksgong** [comment]
#### 也就是说不设置setPath，默认也是存储的路径也是文件路径

对的，相当于调用了`setPath(FileDownloadUtils.getDefaultSaveFilePath(url), false)`

#### 为何我设置setPath(path)后，依次下载多个文件到ViewPager后，文件会被覆盖

如果都是相同文件路径与下载链接

- 如果几个任务同时启动，只有其中一个会被启动，其余的会收到`warn`
- 如果已经下载完成，所有的都会立马回调完成
- 如果已经下载完成，但是设置了`setForceReDownload(true)`，会被对应的Task覆盖下载

如果按你说的，已经下载完成，还会被覆盖，请尝试在demo上复现。

**Comment by DINGJIN90** [comment]
@Jacksgong 这个问题归根结底还是文件路径set有问题，确实源码的路径有MD5(url)的file name，而我没有加file name作为不同文件的区分所以导致文件覆盖了，谢谢！
