### ISSUE TITLE
downloaded audio not shown in music player

### ISSUE THREAD

**Issue by e4basil** [lingochamp/FileDownloader#86]
In my app, i download audios using your lib
there is no issues in downloading but audios not shown in music player(tested in asus music player)
`FileDownloader.getImpl().create(Functions.base_url+v.getTag().toString()).setPath("/storage/emulated/0/Music"+ File.separator + Uri.parse ( Functions.base_url +v .getTag() .toString()) .getLastPathSegment())
				.setTag(Uri.parse(Functions.base_url+v.getTag().toString()).getLastPathSegment())
 .setListener(...........).start();`

**Comment by Jacksgong** [comment]
..Sorry, I can follow you, could you talk more detail about your problem for using this lib?

**Comment by e4basil** [comment]
I downloaded audios from server without any problem and not listed in music player. I downloaded same file using browser(uc browser,....) in same location and listed in music player

**Comment by nukc** [comment]
@e4basil Maybe because the downloaded audios filename extension?
you can check the downloadTask.setPath( path ) , path decided the name of the download file.
(eg:  xxx/xxx/xxx.mp3    or .wma/…)

**Comment by nukc** [comment]
After download (notify the media update):
```java
Uri fileUri = Uri.fromFile(file);
sendBroadcast(new Intent(
         Intent.ACTION_MEDIA_SCANNER_SCAN_FILE,
         fileUri);
```
you can try it

**Comment by e4basil** [comment]
@nukc  thanks i got it

**Comment by Jacksgong** [comment]
@nukc :100:
