### ISSUE TITLE
403 error 

### ISSUE THREAD

**Issue by Jeffin21** [lingochamp/FileDownloader#860]
I checked this URL with other downloader and it downloaded  

12-06 16:46:56.555 3482-5370/download V/FileDownloader.FileDownloadList: remove -493166675@com.liulishuo.filedownloader.DownloadTask@56888d6 left -1 0
12-06 16:46:56.555 3482-5370/download D/FileDownloader.FileDownloadMessenger: notify error -493166675@com.liulishuo.filedownloader.DownloadTask@56888d6 java.net.SocketException: Connection failed with request[{Range=[bytes=13772337-27544673]}] response[{null=[HTTP/1.1 403 Forbidden], Connection=[keep-alive], Content-Length=[226], Content-Type=[text/html], Date=[Wed, 06 Dec 2017 11:16:56 GMT], Server=[nginx], X-Android-Received-Millis=[1512559016529], X-Android-Response-Source=[NETWORK 403], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1512559016289]}] http-state[403] on task[-493166675-1], which is changed after verify connection, so please try again.
12-06 16:46:56.555 3482-5370/download V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@2b7a757 by -1 
12-06 16:46:56.566 3482-3482/download V/SRL: Exception :java.net.SocketException: Connection failed with request[{Range=[bytes=13772337-27544673]}] response[{null=[HTTP/1.1 403 Forbidden], Connection=[keep-alive], Content-Length=[226], Content-Type=[text/html], Date=[Wed, 06 Dec 2017 11:16:56 GMT], Server=[nginx], X-Android-Received-Millis=[1512559016529], X-Android-Response-Source=[NETWORK 403], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1512559016289]}] http-state[403] on task[-493166675-1], which is changed after verify connection, so please try again.
12-06 16:46:56.566 3482-3482/download V/SRL: Error:Connection failed with request[{Range=[bytes=13772337-27544673]}] response[{null=[HTTP/1.1 403 Forbidden], Connection=[keep-alive], Content-Length=[226], Content-Type=[text/html], Date=[Wed, 06 Dec 2017 11:16:56 GMT], Server=[nginx], X-Android-Received-Millis=[1512559016529], X-Android-Response-Source=[NETWORK 403], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1512559016289]}] http-state[403] on task[-493166675-1], which is changed after verify connection, so please try again.
12-06 16:46:56.566 3482-3482/download W/System.err: java.net.SocketException: Connection failed with request[{Range=[bytes=13772337-27544673]}] response[{null=[HTTP/1.1 403 Forbidden], Connection=[keep-alive], Content-Length=[226], Content-Type=[text/html], Date=[Wed, 06 Dec 2017 11:16:56 GMT], Server=[nginx], X-Android-Received-Millis=[1512559016529], X-Android-Response-Source=[NETWORK 403], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1512559016289]}] http-state[403] on task[-493166675-1], which is changed after verify connection, so please try again.
12-06 16:46:56.566 3482-3482/download W/System.err:     at com.liulishuo.filedownloader.download.DownloadRunnable.run(DownloadRunnable.java:92)
12-06 16:46:56.566 3482-3482/download W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
12-06 16:46:56.566 3482-3482/download W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-06 16:46:56.566 3482-3482/download W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-06 16:46:56.566 3482-3482/download W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-06 16:46:56.566 3482-3482/download W/System.err:     at java.lang.Thread.run(Thread.java:818)
12-06 16:46:56.566 3482-3482/download V/SRL: notification show : -1

**Comment by Jacksgong** [comment]
@Jeffin21 Which version of FileDownloader do you using? 

> the older version of FileDownloader may raise this problem

**Comment by Jeffin21** [comment]
Using the latest version , but having the same problem!

**Comment by Jacksgong** [comment]
Sorry, I'm wrong, I thought it was 416...

So, If you occur 403 Forbidden, It's the backend behavior, I think you can request headers on other downloaders which backend accept its request, and mock request headers with `BaseDownloadTask#`addHeader` on FileDownloade.

**Comment by Allyns** [comment]
I have solved this problem by adding .addHeader("Referer", "download link" to addHeader; I hope to help others.

**Comment by Seachal** [comment]
对我来说， 第一个版本服务端没有对文件下载进行鉴权限制，可以正常下载，第二个版本，服务端开始改造增加鉴权，对已经调用过一次的下载链接进行失效处理，我这边就会遇到下面这样的异常， 
 ```
ava.net.SocketException: Connection failed with request[{Range=[bytes=4073926-8147851], User-Agent=[FileDownloader/1.7.7]}] response[{null=[HTTP/1.1 403 Forbidden], Access-Control-Allow-Methods=[GET], Access-Control-Allow-Origin=[*], Connection=[keep-alive], Content-Length=[238], Content-Type=[text/html], Date=[Mon, 29 Jan 2024 02:42:16 GMT], EagleId=[907b1f2217064961368347077e], Server=[Tengine], Timing-Allow-Origin=[*], Via=[cache14.cn1306[,0]], X-Android-Received-Millis=[1706496136376], X-Android-Response-Source=[NETWORK 403], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1706496136196]}] http-state[403] on task[-891346639-1], which is changed after verify connection, so please try again.   
```
最终发现是因为 下载库默认开启断点续传。
<img width="1058" alt="image" src="https://github.com/lingochamp/FileDownloader/assets/14776606/9e08f13e-211b-4e71-b8d3-70254f42e00d">


> Range 是一个请求首部，告知服务器返回文件的哪一部分。在一个 Range 首部中，可以一次性请求多个部分，服务器会以 multipart 文件的形式将其返回。如果服务器返回的是范围响应，需要使用 [206](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/206) Partial Content 状态码。假如所请求的范围不合法，那么服务器会返回 [416](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/416) Range Not Satisfiable 状态码，表示客户端错误。服务器允许忽略 Range 首部，从而返回整个文件，状态码用 [200](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/200) 。

所以我这边的情况是，服务端做修改适配客户端的断点续传，客户端不需要修改。
