### ISSUE TITLE
Occur Unknown Error

### ISSUE THREAD

**Issue by a741762308** [lingochamp/FileDownloader#862]
您好，项目一直集成该库，没有什么问题，但是今天发现集成了MQTT后就出现了Occur Unknown Error, when request to start maybe some problem in binder, maybe the process was killed in unexpected，导致所有的任务无法下载，请问出现这个错误的原因是什么？

**Comment by a741762308** [comment]
请问android:process=":filedownloader" 这个一定要加吗

**Comment by Jacksgong** [comment]
我周末看下，我不是很清楚MQTT对FileDownloader照成的影响。不过可以确定的是:

`Occur Unknown Error, when request to start maybe some problem in binder, maybe the process was killed in unexpected` 出现该问题，正如描所说：在启动下载时发现下载服务并没有绑定上，有可能是下载进程被杀（如果下载在独立进程）；或者下载服务的连接binder被异常断开。

---

关于`android:process=":filedownloader"`，这个你可以不用修改，如果你希望下载服务不运行在独立进程，只需要在`filedownloader.properties`中添加`process.non-separate=true`即可，具体参考[这里](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)。

**Comment by a741762308** [comment]
您好，我使用了filedownloader.properties，取消了独立进程，发现可以用了，可能需要修改相关代码才支持跨进程绑定,地址:https://github.com/eclipse/paho.mqtt.android

**Comment by Jacksgong** [comment]
okay，那么你参考下mqtt对应的文档，这个应该是由于mqtt需要进行相关配置。
