### ISSUE TITLE
分片的策略优化

### ISSUE THREAD

**Issue by Haoxiqiang** [lingochamp/FileDownloader#863]
我看了一下分片的策略
现在的分片大小取决于下载大小/连接数
final long eachRegion = totalLength / connectionCount;

同时现在的 同时任务数为
private final static ThreadPoolExecutor DOWNLOAD_EXECUTOR = FileDownloadExecutors
            .newDefaultThreadPool(Integer.MAX_VALUE, "download-executor");

我觉得这里应该修改一下
比如DOWNLOAD_EXECUTOR任务数是connectionCount
eachRegion 应该是设置的一大小

我想问一下,现在分分片策略基于什么的考量?

**Comment by Haoxiqiang** [comment]
@Jacksgong  https://github.com/lingochamp/FileDownloader/pull/864  大改这个意思

**Comment by Jacksgong** [comment]
我明白你的意思，不过目前下载分块就是可定制的，因此暂时没有考虑再引入其他配置，具体可以参考: [这里](https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component)的`ConnectionCountAdapter`。

**Comment by Haoxiqiang** [comment]
Thks,我大概懂了这个库的代码思路了。



发自我的小米手机
在 2017年12月10日 上午6:52，Jacksgong <notifications@github.com>写道：

我明白你的意思，不过目前下载分块就是可定制的，因此暂时没有考虑再引入其他配置，具体可以参考: 这里<https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component>的ConnectionCountAdapter。

―

**Comment by Haoxiqiang** [comment]
现在机制没有办法解决，我想一个块是1M，但是我想三块三块的按照队列下，我继续看看

**Comment by Jacksgong** [comment]
.可以的，传回总大小，可以按照总大小决定分块个数。

```java
        /**
         * Before invoke this method to determine how many connection will be used to downloading this task,
         * there are several conditions must be confirmed:
         * <p>
         * 1. the connection is support multiple connection(SUPPORT"Partial Content(206)" AND NOT Chunked)
         * 2. the current {@link FileDownloadOutputStream} support seek(The default one({@link FileDownloadRandomAccessFile} is support)
         * 3. this is a new task NOT resume from breakpoint( If the task resume from breakpoint
         * the connection count would be using
         * the one you determined when the task
         * first created ).
         * <p/>
         * The best strategy is refer to how much speed of each connection for the ip:port not file size.
         *
         * @param downloadId  the download id.
         * @param url         the task url.
         * @param path        the task path.
         * @param totalLength the total length of the file.
         * @return the count of connection you want for the task. the value must be large than 0.
         */
        int determineConnectionCount(int downloadId, String url, String path, long totalLength);
```
