### ISSUE TITLE
大视频无法下载问题

### ISSUE THREAD

**Issue by yannanzheng** [lingochamp/FileDownloader#865]
3G左右的视频似乎无法下载，直接点击无用。已经改成了FileDownloadLargeFileListener。

**Comment by Jacksgong** [comment]
无法下载是提示什么错误？

**Comment by yannanzheng** [comment]
首先感谢奉献。
下载大文件回调监听 error回调
 e = java.net.SocketException: Connection failed with request[{Range=[bytes=1634062124-2451093185]}] response[{null=[HTTP/1.1 416 Requested Range Not Satisfiable], Connection=[keep-alive], Content-Length=[213], Content-Range=[bytes */4085155312], Content-Type=[text/html], Date=[Mon, 11 Dec 2017 05:06:48 GMT], Server=[nginx/1.10.2], X-Android-Received-Millis=[1512968809466], X-Android-Response-Source=[NETWORK 416], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1512968809407]}] http-state[416] on task[-215316023-2], which is changed after verify connection, so please try again.
   
    我只是把下载回调改成了如下，其他调用方式与下载小文件相同，下载小文件没有问题。
    private FileDownloadLargeFileListener fileDownloadListener = new FileDownloadLargeFileListener(){...}

**Comment by zhaolu19900510** [comment]
我也遇到同样的问题，但是我下载文件大小是2.8MB。

**Comment by 1525685999** [comment]
700mb大小的文件出现了类似的问题，下载了十几分钟后出现java.net.SocketException: recvfrom failed: ECONNRESET

**Comment by rantianhua** [comment]
@yannanzheng 416 错误代表 range 越界，但是根据你的描述，文件总大小为 3.88G ，而出现 416 的 range 是 [1634062124-2451093185] ，按理说这是一个合法的 range ，但是 server 返回了 416 ，所以这很可能是后端的问题，你需要和后端沟通解决一下。

**Comment by rantianhua** [comment]
@1525685999 你的问题请参考 [这里](https://stackoverflow.com/questions/21699061/getting-java-net-socketexception-recvfrom-failed-econnreset-connection-reset)

**Comment by yannanzheng** [comment]
非常感谢 @rantianhua
