### ISSUE TITLE
部分小米手机直接崩溃

### ISSUE THREAD

**Issue by VliceZ** [lingochamp/FileDownloader#867]
No static method a(Ljava/lang/String;Ljava/lang/Object;)V in class Ljunit/framework/Assert; or its super classes (declaration of 'junit.framework.Assert' appears in /system/framework/core-junit.jar)

com.liulishuo.filedownloader.event.DownloadEventPoolImpl.a(SourceFile:42)

1.6.8版本，部分小米手机会直接崩溃，错误如上。

**Comment by VliceZ** [comment]
通过bugly查询得知上述bug和部分厂商定制rom系统有关，不知道作者有没有解决过此问题？

**Comment by Jacksgong** [comment]
好的。
