### ISSUE TITLE
1.6.8一下载就error

### ISSUE THREAD

**Issue by JarvisGG** [lingochamp/FileDownloader#868]
#### Before Issue

1. Please search on the [Issues](https://github.com/lingochamp/FileDownloader/issues)
2. Please search on the [wiki](https://github.com/lingochamp/FileDownloader/wiki)
3. Please set `FileDownloadLog.NEED_LOG=true` and review the Logcat output from main process and `:filedownloader` process ( pay attention to Warn and Error level logcat)

#### Issue

1. What problem do you get?
2. Which version of FileDownloader are you using when you produce such problem?
3. How to reproduce such problem?
4. Do you set `FileDownloadLog.NEED_LOG=true`?
5. Could you please reproduce this problem and provide all main process and `:filedownloader` process logcat 
6. Can you fix it by yourself and request PR, if not, what's problem do you get when you try to fix it

>P.S. If you don't know how to get `:filedownloader` process, it's recommended to using `pidcat` to just filter all your application logcat, or define `process.non-separate=true` on [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)

---

请在Issue前认真的跟进上面提到的建议，这样将可以极大的加快你遇到问题的处理。

**Comment by JarvisGG** [comment]
java.net.ConnectException: Failed to connect to /100.100.100.100:80

**Comment by JarvisGG** [comment]
换到新版本，现在不了了
com.liulishuo.filedownloader.exception.FileDownloadGiveUpRetryException: sofar[74966] not equal total[133603550]

**Comment by JarvisGG** [comment]
！！！！！！！

**Comment by Jacksgong** [comment]
这个错误很有可能是资源问题，因为FileDownloader在取完输入流的数据以后会对比：后端告知的文件大小(total)是否与输入流全部取完的完整大小(sofar)是否相等，如果不相等，便会返回`error`。

---

可否将对应资源丢到Demo中验证是否该资源必现。

**Comment by JarvisGG** [comment]
我这边用的就是demo里的链接

**Comment by JarvisGG** [comment]
每次都是调用一次progress然后直接就error了

**Comment by Jacksgong** [comment]
是demo中的哪个连接？`sofar not equal total` 如何复现的？

**Comment by JarvisGG** [comment]
http://cdn.llsapp.com/android/LLS-v4.0-595-20160908-143200.apk
代码：
 Observable.create((ObservableOnSubscribe<String>) e -> e.onNext(url))
                .filter(s -> !TextUtils.isEmpty(s))
                .filter(s -> {
                    if (mDownloadUrl.containsKey(url)) {
                        mDownloadCallBack.get(url).downloadFailed(url, null, R.string.text_task_exist);
                        return false;
                    }
                    return false;
                })
                .subscribe(s -> {
                    mDownloadCallBack.put(url, listener);

                    BaseDownloadTask task = FileDownloader.getImpl()
                            .create(url)
                            .setPath(getFilePath(mContext, url))
                            .setAutoRetryTimes(10)
                            .setCallbackProgressMinInterval(1000)
                            .setListener(mDownloadCallBack.get(url) == null ? null : new FileDownloadSampleListener() {
                                @Override
                                protected void started(BaseDownloadTask task) {
                                    super.started(task);
                                    mDownloadCallBack.get(task.getUrl()).startDownload(task.getUrl());
                                }

                                @Override
                                protected void pending(BaseDownloadTask task, int i, int i1) {

                                }

                                @Override
                                protected void progress(BaseDownloadTask task, int soFarBytes, int totalBytes) {
                                    mDownloadCallBack.get(task.getUrl()).downloadProgress(task.getUrl(), Math.round(100 * (long) soFarBytes / totalBytes));
                                }

                                @Override
                                protected void completed(BaseDownloadTask task) {
                                    mDownloadCallBack.get(task.getUrl()).downloadSuccess(task.getUrl(), task.getPath());
                                    if (emitter != null) {
                                        emitter.onNext(task.getUrl());
                                    } else {
                                        mDownloadUrl.remove(task.getUrl());
                                    }
                                }

                                @Override
                                protected void paused(BaseDownloadTask task, int i, int i1) {
                                    mDownloadCallBack.get(task.getUrl()).downloadPause(task.getUrl());
                                    mDownloadCallBack.get(task.getUrl()).downloadFailed(task.getUrl(), null, R.string.network_error);
                                    mDownloadUrl.remove(task.getUrl());
                                }

                                @Override
                                protected void error(BaseDownloadTask task, Throwable throwable) {
                                    if (throwable instanceof FileDownloadOutOfSpaceException) {
                                        mDownloadCallBack.get(task.getUrl()).downloadFailed(task.getUrl(), throwable, R.string.text_clear_memory);
                                    } else if (throwable instanceof PathConflictException) {
                                        mDownloadCallBack.get(task.getUrl()).downloadFailed(task.getUrl(), throwable, R.string.network_error);
                                    } else if (throwable instanceof FileDownloadNetworkPolicyException) {
                                        mDownloadCallBack.get(task.getUrl()).downloadFailed(task.getUrl(), throwable, R.string.network_error);
                                    } else if (throwable instanceof UnknownHostException) {
                                        mDownloadCallBack.get(task.getUrl()).downloadFailed(task.getUrl(), throwable, R.string.network_error);
                                    } else if (throwable instanceof ConnectException) {
                                        mDownloadCallBack.get(task.getUrl()).downloadFailed(task.getUrl(), throwable, R.string.network_error);
                                    } else if (throwable instanceof SocketException) {
                                        mDownloadCallBack.get(task.getUrl()).downloadFailed(task.getUrl(), throwable, R.string.network_error);
                                    }
                                    mDownloadUrl.remove(task.getUrl());
                                }

                                @Override
                                protected void warn(BaseDownloadTask baseDownloadTask) {

                                }
                            });
                    mDownloadUrl.put(url, task);
                    task.start();
                }, throwable -> {

                });

**Comment by JarvisGG** [comment]
完整逻辑：
        sendConversionTracks(AdTracksStatistics.AD_DOWNLOAD_START, mLastUrl, url);
        mDisposable = Observable.create((ObservableOnSubscribe<String>) e -> e.onNext(url))
                .filter(s -> {
                    if (ApkDownloaderImpl.isFileExist(mContext, url)) {
                        downloadSuccess(url);
                        return false;
                    } else {
                        return true;
                    }
                })
                .filter(s -> {
                    if (!mDownloadApkUrl.containsKey(s)) {
                        mDownloadApkUrl.put(s, true);
                        return true;
                    } else {
                        return false;
                    }
                })
                .filter(s -> {
                    if (NetworkUtils.isNetworkAvailable(activity)) {
                        return true;
                    } else {
                        activity.runOnUiThread(() -> {
                            Toast.makeText(activity, R.string.network_error, Toast.LENGTH_SHORT).show();
                        });
                        return false;
                    }
                })
//                .filter(s -> {
//                    if (NetworkUtilsworkUtils.getNetworkState(activity) == NETWORK_WIFI || !isMustWifiAvaliable2DownLoad) {
//                        return true;
//                    } else {
//                        ConfirmDialog dialog = ConfirmDialog.newInstance(activity, R.string.text_dialog_tips,
//                                R.string.network_hint, R.string
//                                        .common_text_edit_confirm_quit_sure, R.string.common_text_edit_confirm_quit_cancel, true);
//                        dialog.setNegativeClickListener(() -> {
//
//                        });
//                        dialog.setPositiveClickListener(() -> {
//                            isMustWifiAvaliable2DownLoad = false;
//                            startDownLoad(activity, url, creative, mLastUrl);
//                        });
//                        dialog.show(activity.getSupportFragmentManager());
//                        return false;
//                    }
//                })
                .map(s -> {
                    activity.runOnUiThread(() -> {
                        Toast.makeText(activity, R.string.text_download_start, Toast.LENGTH_SHORT).show();
                    });
                    return s;
                })
                .map(s -> {
                    downloadStart(url, creative);
                    return s;
                })
                .map(s -> Glide.with(activity).load(creative.image).asBitmap().into(100, 100).get())
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .map(bitmap -> {
                    mDownloadApkCurrentLogo.put(url, bitmap);
                    return bitmap;
                })
                .compose(mApkDownloaderImpl.transformerDownload(url,
                        new ZhihuDownloadListener() {

                            @Override
                            void downloadProgress(String url, @IntRange(from = 0, to = 100) int progress) {
                                super.downloadProgress(url, progress);
                                downloadProcessing(url, progress, creative);
                            }

                            @Override
                            void downloadFailed(String url, Throwable e, int hint) {
                                super.downloadFailed(url, e, hint);
                                downloadFail(url, hint, creative);
                            }

                        }))
                .subscribe(file -> {
                    downloadSuccess(url);
                    sendConversionTracks(AdTracksStatistics.AD_DOWNLOAD_COMPLETE, mDownloadLastUrl.get(url), url);
                    sendConversionTracks(AdTracksStatistics.AD_DOWNLOAD_INSTALL_SUCCESS, mDownloadLastUrl.get(url), url);
                }, throwable -> {
                }, () -> {
                });






public class ApkDownloaderImpl implements ApkDownloader {


    private Context mContext;
    private Map<String, BaseDownloadTask> mDownloadUrl = new ArrayMap<>();
    private Map<String, ApkDownloaderManager.ZhihuDownloadListener> mDownloadCallBack
            = new ArrayMap<>();
    private static ApkDownloaderImpl sFileDownLoaderImpl;

    public static ApkDownloaderImpl getInstance(Context context) {
        if (sFileDownLoaderImpl == null) {
            synchronized (ApkDownloaderImpl.class) {
                if (sFileDownLoaderImpl == null) {
                    sFileDownLoaderImpl = new ApkDownloaderImpl(context);
                }
            }
        }
        return sFileDownLoaderImpl;
    }

    private ApkDownloaderImpl(Context context) {
        this.mContext = context;
        init();
    }

    private void init() {

    }

    @Override
    public void start(String url) {
        start(url, null, null);
    }

    @Override
    public void start(String url, ApkDownloaderManager.ZhihuDownloadListener listener) {
        start(url, listener, null);
    }

    @Override
    public void start(String url, ApkDownloaderManager.ZhihuDownloadListener listener, ObservableEmitter<String> emitter) {

        Observable.create((ObservableOnSubscribe<String>) e -> e.onNext(url))
                .filter(s -> !TextUtils.isEmpty(s))
                .filter(s -> {
                    if (mDownloadUrl.containsKey(url)) {
                        mDownloadCallBack.get(url).downloadFailed(url, null, R.string.text_task_exist);
                        return false;
                    }
                    return false;
                })
                .subscribe(s -> {
                    mDownloadCallBack.put(url, listener);

                    BaseDownloadTask task = FileDownloader.getImpl()
                            .create(url)
                            .setPath(getFilePath(mContext, url))
                            .setAutoRetryTimes(10)
                            .setCallbackProgressMinInterval(1000)
                            .setListener(mDownloadCallBack.get(url) == null ? null : new FileDownloadSampleListener() {
                                @Override
                                protected void started(BaseDownloadTask task) {
                                    super.started(task);
                                    mDownloadCallBack.get(task.getUrl()).startDownload(task.getUrl());
                                }

                                @Override
                                protected void pending(BaseDownloadTask task, int i, int i1) {

                                }

                                @Override
                                protected void progress(BaseDownloadTask task, int soFarBytes, int totalBytes) {
                                    mDownloadCallBack.get(task.getUrl()).downloadProgress(task.getUrl(), Math.round(100 * (long) soFarBytes / totalBytes));
                                }

                                @Override
                                protected void completed(BaseDownloadTask task) {
                                    mDownloadCallBack.get(task.getUrl()).downloadSuccess(task.getUrl(), task.getPath());
                                    if (emitter != null) {
                                        emitter.onNext(task.getUrl());
                                    } else {
                                        mDownloadUrl.remove(task.getUrl());
                                    }
                                }

                                @Override
                                protected void paused(BaseDownloadTask task, int i, int i1) {
                                    mDownloadCallBack.get(task.getUrl()).downloadPause(task.getUrl());
                                    mDownloadCallBack.get(task.getUrl()).downloadFailed(task.getUrl(), null, R.string.network_error);
                                    mDownloadUrl.remove(task.getUrl());
                                }

                                @Override
                                protected void error(BaseDownloadTask task, Throwable throwable) {
                                    if (throwable instanceof FileDownloadOutOfSpaceException) {
                                        mDownloadCallBack.get(task.getUrl()).downloadFailed(task.getUrl(), throwable, R.string.text_clear_memory);
                                    } else if (throwable instanceof PathConflictException) {
                                        mDownloadCallBack.get(task.getUrl()).downloadFailed(task.getUrl(), throwable, R.string.network_error);
                                    } else if (throwable instanceof FileDownloadNetworkPolicyException) {
                                        mDownloadCallBack.get(task.getUrl()).downloadFailed(task.getUrl(), throwable, R.string.network_error);
                                    } else if (throwable instanceof UnknownHostException) {
                                        mDownloadCallBack.get(task.getUrl()).downloadFailed(task.getUrl(), throwable, R.string.network_error);
                                    } else if (throwable instanceof ConnectException) {
                                        mDownloadCallBack.get(task.getUrl()).downloadFailed(task.getUrl(), throwable, R.string.network_error);
                                    } else if (throwable instanceof SocketException) {
                                        mDownloadCallBack.get(task.getUrl()).downloadFailed(task.getUrl(), throwable, R.string.network_error);
                                    }
                                    mDownloadUrl.remove(task.getUrl());
                                }

                                @Override
                                protected void warn(BaseDownloadTask baseDownloadTask) {

                                }
                            });
                    mDownloadUrl.put(url, task);
                    task.start();
                }, throwable -> {

                });
    }

    @Override
    public void pause(String url) {
        Observable.create((ObservableOnSubscribe<String>) e -> e.onNext(url))
                .map(s -> mDownloadUrl.get(s))
                .subscribe(BaseDownloadTask::pause);
    }

    @Override
    public void pauseAll() {
//        FileDownloader.getImpl().pauseAll();
        for (String key : mDownloadUrl.keySet()) {
            mDownloadUrl.get(key).pause();
        }
    }

    @Override
    public void resume(String url) {
        Observable.create((ObservableOnSubscribe<String>) e -> e.onNext(url))
                .map(s -> mDownloadUrl.get(s))
                .subscribe(BaseDownloadTask::start);
    }

    @Override
    public void resumeAll() {
        for (String key : mDownloadUrl.keySet()) {
            mDownloadUrl.get(key).start();
        }
    }

    @Override
    public void cancel(String url) {
        Observable.create((ObservableOnSubscribe<String>) e -> e.onNext(url))
                .map(s -> mDownloadUrl.get(s))
                .subscribe(BaseDownloadTask::pause);
    }

    @Override
    public void cancelAll() {
        for (String key : mDownloadUrl.keySet()) {
            mDownloadUrl.get(key).pause();
        }
    }

    @Override
    public void delete(String url) {
        mDownloadUrl.get(url).pause();
        mDownloadUrl.remove(url);
        new File(getFilePath(mContext, url)).delete();
        new File(FileDownloadUtils.getTempPath(getFilePath(mContext, url))).delete();
    }

    public boolean isApksDownload() {
        return mDownloadUrl.size() > 0;
    }

    /**
     * 切换线程
     * @param <Upstream>
     * @return
     */
    public <Upstream> ObservableTransformer<Upstream, Upstream> transformerThread() {
        return upstream -> upstream
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread());
    }

    /**
     * rxjava 下载转换器
     * @param url
     * @param listener
     * @param <Upstream>
     * @return
     */
    public <Upstream> ObservableTransformer<Upstream, File> transformerDownload(final String url, ApkDownloaderManager.ZhihuDownloadListener listener) {

        return upstream -> upstream.flatMap(new Function<Upstream, ObservableSource<File>>() {
            @Override
            public ObservableSource<File> apply(@NonNull Upstream upstream) throws Exception {
                return Observable
                        .create((ObservableOnSubscribe<String>) emitter -> {
                            start(url, listener, emitter);
                        })
                        .compose(transformerThread())
                        .map(s -> {
                            BaseDownloadTask task = mDownloadUrl.get(s);
                            mDownloadUrl.remove(s);
                            String path = task.getPath();
                            File file = new File(path);
                            if (file.isFile() && file.exists()) {
                                return file;
                            }
                            return null;
                        });
            }
        });
    }


    public static boolean isFileExist(Context context, String url) {
        File file = new File(getFilePath(context, url));
        return file.isFile() && file.length() > 0L;
    }

    public static String getFilePath(Context context, String url) {
        return context.getFilesDir().getAbsolutePath() + "/" + getDownloadFileName(url);
    }

    public static String getDownloadFileName(String fileName) {
        String temoFileName;
        if (fileName.contains(".")) {
            temoFileName = fileName.hashCode() + fileName.substring(fileName.lastIndexOf("."));
        } else {
            temoFileName = String.valueOf(fileName.hashCode());
        }
        return temoFileName;
    }


}

**Comment by Jacksgong** [comment]
可否通过修改Demo上的代码，直接在Demo中复现，然后发对应的project给我，或者推到Github上面给我。这样贴代码很难定位问题。

**Comment by JarvisGG** [comment]
好的，我改一下

**Comment by JarvisGG** [comment]
FileDownloader.getImpl().create("http://cdn.llsapp.com/android/LLS-v4.0-595-20160908-143200.apk")
                .setPath(FileDownloadUtils.getDefaultSaveRootPath() + File.separator + "tmpdir1" + File.separator +
                        "LLS-v4.0-595-20160908-143200.apk", false)
                .setCallbackProgressTimes(300)
                .setMinIntervalUpdateSpeed(400)
                .setListener(new FileDownloadSampleListener() {

                    @Override
                    protected void started(BaseDownloadTask task) {
                        super.started(task);
                    }

                    @Override
                    protected void pending(BaseDownloadTask task, int soFarBytes, int totalBytes) {
                        super.pending(task, soFarBytes, totalBytes);
                    }

                    @Override
                    protected void progress(BaseDownloadTask task, int soFarBytes, int totalBytes) {
                        super.progress(task, soFarBytes, totalBytes);
                    }

                    @Override
                    protected void error(BaseDownloadTask task, Throwable e) {
                        super.error(task, e);
                    }

                    @Override
                    protected void connected(BaseDownloadTask task, String etag, boolean isContinue, int soFarBytes, int totalBytes) {
                        super.connected(task, etag, isContinue, soFarBytes, totalBytes);
                    }

                    @Override
                    protected void paused(BaseDownloadTask task, int soFarBytes, int totalBytes) {
                        super.paused(task, soFarBytes, totalBytes);
                    }

                    @Override
                    protected void completed(BaseDownloadTask task) {
                        super.completed(task);
                    }

                    @Override
                    protected void warn(BaseDownloadTask task) {
                        super.warn(task);
                    }
                }).start();

**Comment by JarvisGG** [comment]
这段代码放我项目里，
com.liulishuo.filedownloader.exception.FileDownloadGiveUpRetryException: sofar[77761] not equal total[37629451]
还是这个错误

**Comment by JarvisGG** [comment]
相同的代码在demo里面就没问题

**Comment by JarvisGG** [comment]
之前我这边是1.5.9，没问题，但是wifi切4g的时候没法断点下载，我就换到1.6.8，结果，在项目里，progress调用一次，就立马进error

**Comment by JarvisGG** [comment]
我这边测了一下，1.6.5还是好的

**Comment by JarvisGG** [comment]
821388334 可以具体聊一下吗，谢谢大神

**Comment by lpcrow** [comment]
你好，我这里也出现了类似的问题。我试了几个资源链接都会出现这个异常。就是连续3次暂停，继续之后，点继续没反应，过一会儿就抛出了这个异常。我观察了下，继续的次数可能跟filedownloader.properties里的download.max-network-thread-count的值有关，我试了把它改为1，第一次暂停继续后就复现了。麻烦帮忙看一下。

**Comment by rantianhua** [comment]
@lpcrow 这里的问题和你的问题应该是两个问题。

**Comment by rantianhua** [comment]
@JarvisGG 试了 1.6.8 的 Demo ，没有你提到的问题。请提供你项目的 Github 地址吗？

**Comment by lpcrow** [comment]
@rantianhua 有可能是两个问题，但是我看了其他的提问者，他们的FileDownloadGiveUpRetryException这个异常和sofar[74966] not equal total[133603550]这个问题一般都没有同时出现，就这个开发者这里出现了跟我一样的情况（两个问题并存）。我做了测试，是经过这样操作之后才出现的，所以在这里提问的~

**Comment by rantianhua** [comment]
No response for a long time.
