### ISSUE TITLE
怎么获取下载成功时请求头的内容

### ISSUE THREAD

**Issue by jixionghui** [lingochamp/FileDownloader#872]
#### Before Issue

1. Please search on the [Issues](https://github.com/lingochamp/FileDownloader/issues)
2. Please search on the [wiki](https://github.com/lingochamp/FileDownloader/wiki)
3. Please set `FileDownloadLog.NEED_LOG=true` and review the Logcat output from main process and `:filedownloader` process ( pay attention to Warn and Error level logcat)

#### Issue

1. What problem do you get?
2. Which version of FileDownloader are you using when you produce such problem?
3. How to reproduce such problem?
4. Do you set `FileDownloadLog.NEED_LOG=true`?
5. Could you please reproduce this problem and provide all main process and `:filedownloader` process logcat 
6. Can you fix it by yourself and request PR, if not, what's problem do you get when you try to fix it

>P.S. If you don't know how to get `:filedownloader` process, it's recommended to using `pidcat` to just filter all your application logcat, or define `process.non-separate=true` on [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)

---

请在Issue前认真的跟进上面提到的建议，这样将可以极大的加快你遇到问题的处理。

**Comment by Jacksgong** [comment]
在FileDownloader中目前要获取请求头没有支持。

但是FileDownloader2 -> [okdownload](https://github.com/lingochamp/okdownload)上已经支持，并且okdownload会做一层FileDownloader的适配层让尽可能的无缝过渡，并且这段时间会尽快Release第一个版本。
