### ISSUE TITLE
下载任务列表中的下载任务有几十个后，滑动列表卡顿问题？

### ISSUE THREAD

**Issue by YangShaoXiong** [lingochamp/FileDownloader#874]
在Adapter中的 onBindViewHolder方法中，有一行查询下载状态的代码
 int status=TasksManager.getImpl().getStatus(model.getId(), model.getPath());
就是这行代码导致滑动任务列表卡顿问题。但是又不得不用，不知道有没有相应的解决方案，希望作者在百忙之中能够看到。提前谢谢了。

**Comment by Jacksgong** [comment]
## 分两个Case

#### CASE 1. 如果某个任务正在下载

那么获取该任务的该值应该不会很慢，因为该任务的状态在`FileDownloadList`中会有缓存

#### CASE 2. 如果某个并不是在下载

那么确实有可能慢，就不得不检测下载服务中该任务的状态。

那么如果默认情况(`process.non-separate=false`)，由于下载服务在独立进程，这里就涉及了跨进程通信，那么有存在I/O操作，有可能在一些性能较差的手机上会略微耗时。

## 解决方案，有两种方案可以解决

#### SCHEME 1. 自己缓存所有任务的状态

可以在启动的时候，或者是刚进入页面的时候一次性获取所有任务的状态，或者是动态的将状态补充到缓存，当已经从`FileDownloader`获取到状态后，而后的所有的状态自己维护，在下载监听中不断的把状态同步到自己的缓存，而后直接或者缓存中的状态即可。

#### SCHEME 2. 异步获取部分状态

对于CASE 1的情况(`FileDownloadList`中有缓存），就可以直接在`FileDownloadList`中取得状态。
对于CASE 2的情况，与加载图片类似的逻辑，异步的将状态同步的对应的`View`，这里要注意`RecyclerView/ListView`中对`View`的复用问题
