### ISSUE TITLE
possible to customize properties to run tasks in background as well as main process?

### ISSUE THREAD

**Issue by virengujariya** [lingochamp/FileDownloader#875]
Question:

Is it possible to customize library that allows to run some tasks in background and some on main process?

**Comment by Jacksgong** [comment]
Nope, In the FileDownloader, it's very hard to do that.

but in the [okdownload](https://github.com/lingochamp/okdownload/issues/1), you can accomplish this requirement through implement 3 `DownloadDispatcher` :

1. `DownloadDispatcher`1 running in the main process
2. `DownloadDispatcher`2 running in the background progress
3. `DownloadDispatcher`3 is just used for proxy and route tasks to 1 or 2 `DownloadDispatcher`

and then you just register `DownloadDispatcher`3 to `OkDownload`.

**Comment by xCalifier** [comment]
The only possible solution is to Start the download in Foreground Service.
