### ISSUE TITLE
你好： 下载邮箱附件的时候直接报错

### ISSUE THREAD

**Issue by fewwind** [lingochamp/FileDownloader#876]
貌似是https 证书的问题，应该很常见，但是没见到有人提，请问怎么解决 
error = javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by Jacksgong** [comment]
参考下这里: https://github.com/lingochamp/FileDownloader/issues/437#issuecomment-270825192
