### ISSUE TITLE
Retry data not storing 

### ISSUE THREAD

**Issue by Jeffin21** [lingochamp/FileDownloader#877]
I got a problem in slow network very slow network , when the retry happens the data not storing. for example i'm downloading a 50mb file on a slow network and downloaded almost 25mb, when the retry happens and i paused the download and download data going back to 24mb or 20mb sudden decreasing the data, download speed under 10KB/sec

**Comment by Jacksgong** [comment]
Sorry, could you please provide more detail about this, I can't get your point.

**Comment by Jeffin21** [comment]
This is a major issue for a downloader please fix it

**Comment by Jeffin21** [comment]
Download a file in very slow network better to catch the bug in 2kb/sec network and the downloader tries to retry the download and press pause then you see the decrease in the download data

**Comment by Jeffin21** [comment]
#852 this issue , 

log
 12-20 14:57:21.477 23929-23929/com.download.gdm V/SRL: task item status:3
12-20 14:57:21.477 23929-23929/com.download.gdm V/SRL: task item status1:3
12-20 14:57:22.481 23929-23929/com.download.gdm V/SRL: task item status:3
12-20 14:57:22.481 23929-23929/com.download.gdm V/SRL: task item status1:3
12-20 14:57:22.983 23929-23929/com.download.gdm V/SRL: notification show : 5
12-20 14:57:22.984 23929-23929/com.download.gdm I/System.out: show notiiify: 330226
12-20 14:57:22.992 23929-23929/com.download.gdm V/SRL: remainingTimeStr getSpeed: 3.6 KB/s | 9h:42m:41s
12-20 14:57:22.992 23929-23929/com.download.gdm V/SRL: remainingTimeStr getSpeed: 3.6 KB/s | 9h:42m:41s
12-20 14:57:23.473 23929-23929/com.download.gdm V/SRL: task item status:5
12-20 14:57:23.473 23929-23929/com.download.gdm V/SRL: task item status1:5
12-20 14:57:24.227 28433-28433/? E/NEW_BHD: Battery Power Supply logging Daemon start!!!!!
12-20 14:57:24.228 28433-28433/? E/NEW_BHD: Cannot run on production devices!
12-20 14:57:24.468 23929-23929/com.download.gdm V/SRL: task item status:5
12-20 14:57:24.468 23929-23929/com.download.gdm V/SRL: task item status1:5
12-20 14:57:25.024 24091-28289/com.download.gdm:filedownloader I/System.out: findContentLength: 18596143
12-20 14:57:25.024 24091-28289/com.download.gdm:filedownloader V/SRL: FileDownloadOutputStream:/storage/3B1F-1B05/music/Watch Kal Ho Naa Ho Online-Free -.mp4.temp
12-20 14:57:25.029 24091-28289/com.download.gdm:filedownloader I/System.out: getItemByPath1Watch Kal Ho Naa Ho Online-Free -.mp4
12-20 14:57:25.029 24091-28289/com.download.gdm:filedownloader I/System.out: getItemByPathhhhhh 2222:Watch Kal Ho Naa Ho Online-Free -.mp4
12-20 14:57:25.030 24091-28289/com.download.gdm:filedownloader I/System.out: getItemByPathhhhhhN;Watch Kal Ho Naa Ho Online-Free -.mp4
12-20 14:57:25.037 24091-28289/com.download.gdm:filedownloader I/System.out: File Utile:SDcard==/storage/3B1F-1B05/music/Watch Kal Ho Naa Ho Online-Free -.mp4.tempFileLocationDetails:SDcard
12-20 14:57:25.037 24091-28289/com.download.gdm:filedownloader V/SRL: DocFil:/storage/3B1F-1B05/music/Watch Kal Ho Naa Ho Online-Free -.mp4.temp==true
12-20 14:57:25.037 24091-28289/com.download.gdm:filedownloader I/System.out: File Utile file:/storage/3B1F-1B05/music/Watch Kal Ho Naa Ho Online-Free -.mp4.temp
12-20 14:57:25.043 24091-28289/com.download.gdm:filedownloader I/System.out: getItemByPath1Watch Kal Ho Naa Ho Online-Free -.mp4
12-20 14:57:25.044 24091-28289/com.download.gdm:filedownloader I/System.out: getItemByPathhhhhh 2222:Watch Kal Ho Naa Ho Online-Free -.mp4
12-20 14:57:25.044 24091-28289/com.download.gdm:filedownloader I/System.out: getItemByPathhhhhhN;Watch Kal Ho Naa Ho Online-Free -.mp4
12-20 14:57:25.473 23929-23929/com.download.gdm V/SRL: task item status:5
12-20 14:57:25.473 23929-23929/com.download.gdm V/SRL: task item status1:5
12-20 14:57:26.468 23929-23929/com.download.gdm V/SRL: task item status:5
12-20 14:57:26.469 23929-23929/com.download.gdm V/SRL: task item status1:5
12-20 14:57:27.469 23929-23929/com.download.gdm V/SRL: task item status:5
12-20 14:57:27.469 23929-23929/com.download.gdm V/SRL: task item status1:5
12-20 14:57:28.469 23929-23929/com.download.gdm V/SRL: task item status:5
12-20 14:57:28.469 23929-23929/com.download.gdm V/SRL: task item status1:5
12-20 14:57:29.255 28435-28435/? E/NEW_BHD: Battery Power Supply logging Daemon start!!!!!
12-20 14:57:29.256 28435-28435/? E/NEW_BHD: Cannot run on production devices!
12-20 14:57:29.468 23929-23929/com.download.gdm V/SRL: task item status:5
12-20 14:57:29.468 23929-23929/com.download.gdm V/SRL: task item status1:5
12-20 14:57:29.599 266-266/? I/SFPerfTracer:      triggers: (rate: 102:5714) (compose: 15:650) (post: 0:757) (render: 29:1127) (1:207086 frames) (2:244221)
12-20 14:57:29.599 266-266/? D/SFPerfTracer:        layers: (3:9) (FocusedStackFrame (0xb8d355c8): 0:2097)* (DimLayer (0xb8dbaa58): 0:45)* (StatusBar (0xb8d89e20): 0:24160) (com.android.systemui.ImageWallpaper (0xb8db3b38): 0:494)* (DimLayer (0xb8d7f790): 0:114)* (DimLayer (0xb8d9ff48): 0:16)* (NavigationBar (0xb8da90e8): 0:28) (com.download.gdm/com.ggates.android.gdm.residingmenu.MainActivity_Residing_Menu (0xb8d80a58): 2:315) 
12-20 14:57:30.486 23929-23929/com.download.gdm V/SRL: task item status:5
12-20 14:57:30.486 23929-23929/com.download.gdm V/SRL: task item status1:5
12-20 14:57:31.486 23929-23929/com.download.gdm V/SRL: task item status:5
12-20 14:57:31.486 23929-23929/com.download.gdm V/SRL: task item status1:5
12-20 14:57:32.484 23929-23929/com.download.gdm V/SRL: task item status:5
12-20 14:57:32.484 23929-23929/com.download.gdm V/SRL: task item status1:5
12-20 14:57:33.483 23929-23929/com.download.gdm V/SRL: task item status:5
12-20 14:57:33.483 23929-23929/com.download.gdm V/SRL: task item status1:5
12-20 14:57:34.282 28436-28436/? E/NEW_BHD: Battery Power Supply logging Daemon start!!!!!
12-20 14:57:34.283 28436-28436/? E/NEW_BHD: Cannot run on production devices!
12-20 14:57:34.482 23929-23929/com.download.gdm V/SRL: task item status:5
12-20 14:57:34.482 23929-23929/com.download.gdm V/SRL: task item status1:5
12-20 14:57:35.218 23929-23929/com.download.gdm V/SRL: notification show : 5
12-20 14:57:35.218 23929-23929/com.download.gdm I/System.out: show notiiify: 403983
12-20 14:57:35.477 23929-23929/com.download.gdm V/SRL: task item status:5
12-20 14:57:35.477 23929-23929/com.download.gdm V/SRL: task item status1:5
12-20 14:57:35.878 24091-28396/com.download.gdm:filedownloader I/System.out: findContentLength: 18566744
12-20 14:57:35.878 24091-28396/com.download.gdm:filedownloader V/SRL: FileDownloadOutputStream:/storage/3B1F-1B05/music/Watch Kal Ho Naa Ho Online-Free -.mp4.temp
12-20 14:57:35.884 24091-28396/com.download.gdm:filedownloader I/System.out: getItemByPath1Watch Kal Ho Naa Ho Online-Free -.mp4
12-20 14:57:35.885 24091-28396/com.download.gdm:filedownloader I/System.out: getItemByPathhhhhh 2222:Watch Kal Ho Naa Ho Online-Free -.mp4
12-20 14:57:35.885 24091-28396/com.download.gdm:filedownloader I/System.out: getItemByPathhhhhhN;Watch Kal Ho Naa Ho Online-Free -.mp4
12-20 14:57:35.889 24091-28396/com.download.gdm:filedownloader I/System.out: File Utile:SDcard==/storage/3B1F-1B05/music/Watch Kal Ho Naa Ho Online-Free -.mp4.tempFileLocationDetails:SDcard
12-20 14:57:35.889 24091-28396/com.download.gdm:filedownloader V/SRL: DocFil:/storage/3B1F-1B05/music/Watch Kal Ho Naa Ho Online-Free -.mp4.temp==true
12-20 14:57:35.889 24091-28396/com.download.gdm:filedownloader I/System.out: File Utile file:/storage/3B1F-1B05/music/Watch Kal Ho Naa Ho Online-Free -.mp4.temp
12-20 14:57:35.894 24091-28396/com.download.gdm:filedownloader I/System.out: getItemByPath1Watch Kal Ho Naa Ho Online-Free -.mp4
12-20 14:57:35.895 24091-28396/com.download.gdm:filedownloader I/System.out: getItemByPathhhhhh 2222:Watch Kal Ho Naa Ho Online-Free -.mp4
12-20 14:57:35.895 24091-28396/com.download.gdm:filedownloader I/System.out: getItemByPathhhhhhN;Watch Kal Ho Naa Ho Online-Free -.mp4
12-20 14:57:36.245 7206-7304/? D/audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
12-20 14:57:36.254 23929-23929/com.download.gdm V/SRL: notification show : -2
12-20 14:57:36.254 23929-23929/com.download.gdm I/System.out: show notiiify: 192641
12-20 14:57:36.255 23929-23929/com.download.gdm V/SRL: remainingTimeStr getSpeed: 5.9 KB/s | 5h:58m:41s

**Comment by Jeffin21** [comment]
@Jacksgong any update for this issue ?

**Comment by rantianhua** [comment]
@Jeffin21 从你给的日志看，确实最后出现了断点失败的情况，但因为这些日志是你们自己项目打的，不是 FileDownloader 日志，所以没法分析出是什么原因造成的。有些情况下确实会使断点失效，比如后端返回的 Http 码为 416、200，或者 Etag 有更新。所以希望能提供完整的 FileDownloader 的日志，包括主进程和 filedownloader 的进程。

**Comment by rantianhua** [comment]
Duplicate with #852. Please pay attention to #852.
