### ISSUE TITLE
当没有网络时，完成错误回调之后会删除本地文件

### ISSUE THREAD

**Issue by 15915367650** [lingochamp/FileDownloader#878]
当我重新下载一个文件时(此时本地已经存在),开启下载时没有网络，进入错误回调，此时会将我本地原来下载好的文件删除掉，请问有没有方法控制，当下载错误时不删除原来已经下载的这个文件的方法

**Comment by rantianhua** [comment]
应该是你在常见 BaseDownloadTask 的时候调用了 `BaseDownloadTask#setForceReDownload(boolean)` 为 true 才会出现这种情况。如果是的话，那么删除掉原有文件是合理的，否则不会开启新的下载任务。如果你想保留原始文件，那么建议最好新的下载设置新的保存地址。
