### ISSUE TITLE
SocketTimeoutException

### ISSUE THREAD

**Issue by atulsethi** [lingochamp/FileDownloader#88]
always give SocketTimeoutException . I have dwonloaded same file on mobile browser and with another code but when i am using FileDownloader library then error throw during start downloading 

java.lang.RuntimeException: SocketTimeoutException

i have also set timeout time 

 FileDownloader.init(this,
                new FileDownloadHelper.OkHttpClientCustomMaker() { // is not has to provide.
                    @Override
                    public OkHttpClient customMake() {
                        // just for OkHttpClient customize.
                        final OkHttpClient.Builder builder = new OkHttpClient.Builder();
                        // you can set the connection timeout.
                        builder.connectTimeout(3*60 * 1000, TimeUnit.MILLISECONDS);
                        // you can set the HTTP proxy.
                        builder.proxy(Proxy.NO_PROXY);
                        // etc.
                        return builder.build();
                    }
                });

Please help....

Thanks

**Comment by Jacksgong** [comment]
Sorry, this is Http-Connection Error, Please change your Net-Environment and retry.
