### ISSUE TITLE
开启独立进程真的坑！！！

### ISSUE THREAD

**Issue by developergx** [lingochamp/FileDownloader#880]
为什么默认开启独立进程？   真的坑啊，我自己的Service都绑定不上了...   建议把默认独立进程关掉，共享app主进程！！！

**Comment by Jacksgong** [comment]
为了保持行为一致性，不至于大家升级以后，发现行为被修改，FileDownloader默认配置不再进行调整。

---

如果需要配置共享进程可以参考[文档](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)进行快速配置。

---

这个库在设计之初就默认运行在独立进程了，支持共享主进程是后面的版本才加上的，因此考虑到旧版本已经很多同学在使用了，如果我们默认配置存在变化，将会对旧版本同学产生不符合预期的影响。

---

考虑到实际情况，很多新同学没有留意文档，无法预期默认在独立进程，因此FileDownloader2 - [okdownload](https://github.com/lingochamp/okdownload)，将默认共享主进程，如果需要独立进程，需要单独引里面`okdownload-process`的library才会开启。
