### ISSUE TITLE
SocketTimeoutException when pauseAll is called few times on running task

### ISSUE THREAD

**Issue by virengujariya** [lingochamp/FileDownloader#881]
#### Issue
1. What problem do you get?
After calling `pauseAll` back to back (try more than 3 times) on download and then trying to start download again is causing `java.net.SocketTimeoutException: timeout` (okhttp)

2. Which version of FileDownloader are you using when you produce such problem?
1.6.9

3. How to reproduce such problem?
Start download with following properties
`queueSet.setAutoRetryTimes(3);
        queueSet.setForceReDownload(true);
        queueSet.downloadSequentially(tasks);
        queueSet.start();`
Now canceling download when it's running (calling `pauseAll`), repeat this step more than 3 times (may 4 or 5)

I have `process.non-separate=true` enabled. 

I also reviewed LOG
`FileDownloadMessenger: notify retry -2112314570@com.liulishuo.filedownloader.DownloadTask@3d6e6637 3 1 java.net.SocketTimeoutException: timeout`

`FileDownloadMessenger: notify retry -2112314570@com.liulishuo.filedownloader.DownloadTask@3d6e6637 3 2 java.net.SocketTimeoutException: timeout`

`FileDownloadMessenger: notify retry -2112314570@com.liulishuo.filedownloader.DownloadTask@3d6e6637 3 3 java.net.SocketTimeoutException: timeout`

try following urls:
- https://dogeo4ne9xfxq.cloudfront.net/instagram/c83b31ba73870234860944d6.jpg?1507917511
https://dogeo4ne9xfxq.cloudfront.net/instagram/79afd5193eccda99279068b8.jpg?1507917806

weird solution: it works if I reconnect internet/wifi or kill and restart the app.

**Comment by rantianhua** [comment]
Sorry for a very late response. But I cannot reproduce your issue, so can you reproduce the problem in the demo, for example in class `MultitaskTestActivity`?

**Comment by rantianhua** [comment]
From the log, the exception is thrown by okhttp (by the way, i didn't use okhttp during reproducing your problem, so you can also try to reproduce it using default FileDownloadConnection instead okhttp), so it's probably not caused by FileDownloader. Looking forward to your any response.
