### ISSUE TITLE
下载阿里云中的文件断点下载失效

### ISSUE THREAD

**Issue by stromcuijie** [lingochamp/FileDownloader#885]
下载别的url文件一起正常，后来后台把视频文件放在阿里云中 断点下载就失效了 求解 很急的！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by rantianhua** [comment]
具体遇到的现象是什么？下载启动不了？有没有具体的错误回调？最好能提供 FileDownloader 的日志。否则不知道你具体遇到了什么问题。

**Comment by rantianhua** [comment]
一般造成断点失败的原因有：服务端返回 416、200、Etag 变化了。所以可以先排除下这些问题。另外希望提供 FileDownloader 的日志方便分析问题。
