### ISSUE TITLE
FileDownloadSerialQueue，应该提供一个清空下载进程的方法

### ISSUE THREAD

**Issue by susirsusir** [lingochamp/FileDownloader#888]
FileDownloadSerialQueue，应该提供一个清空下载进程的方法

**Comment by rantianhua** [comment]
`FileDownloadSerialQueue` 有一个 `shutdown` 方法，改方法会先暂停所有队列中的任务，然清空任务列表，最后关闭 `FileDownloadSerialQueue` 开启的维护下载任务的线程。这个应该就能满足你所提的了。

**Comment by susirsusir** [comment]
if (queue != null && queue.getWaitingTaskCount() > 0) {
            List<BaseDownloadTask> tasks = queue.shutdown();
            for (BaseDownloadTask task : tasks) {
                FileDownloader.getImpl().clear(task.getId(), task.getTargetFilePath());
            }
            FileDownloader.getImpl().clearAllTaskData();
        }

最后尝试了这样的操作，但是不太确定这样操作的正确性，仅仅是在使用过程当中没有出现错误和异常情况，仅仅使用queue.shutdown();并不能够立即中断并清空下载进程数据，需要1秒以上时间还在进行继续下载

需求可以理解，存在一个按钮，点击：多个文件下载请求添加到队列当中，开始下载
再次点击：中断并且清空数据
再次点击：多个文件下载请求添加到队列当中，开始下载（不是继续下载，是重新开始）
这样快速点击切换，会因为线程根文件资源没有立即释放造成异常
期望：能够提供一种方法，能够立即中断清空数据

**Comment by susirsusir** [comment]
@rantianhua

**Comment by rantianhua** [comment]
你的调用方式是正确的，但需要注意一点，最后一句：FileDownloader.getImpl().clearAllTaskData(); 它会清楚所有 FileDownloader 数据库中保存的数据，即不仅仅是 FiledownloadSerialQueue 里面的 task 的数据。所以如果你只想删除 FiledownloadSerialQueue 里面的数据，那么去掉最后一句即可。
