### ISSUE TITLE
1.6.9  快速点击暂停继续依然会重新从零下载文件

### ISSUE THREAD

**Issue by chaopengTan** [lingochamp/FileDownloader#891]
如题

**Comment by Jeffin21** [comment]
please post a log

**Comment by rantianhua** [comment]
请问你是指某个 Demo 还是你自己使用的过程中，反复并快速调用 start 和 pause ？这样一句描述很难定位问题。

**Comment by Leovy** [comment]
@rantianhua @Jacksgong 反复调用pause和start，在start的时候，有时候并不是从端点开始下载，而是从0开始，FileDownloadListener#progress(DownloadTask)参数中的DownloadTask#isResuming() return false,意味着未从断点处下载.麻烦看下这个问题

**Comment by Jeffin21** [comment]
@Leovy post log

**Comment by Leovy** [comment]
01-25 15:29:57.998 29033-29033/com.allin.appbasefeature I/Download2Activity: (status1)Download2Activity-->onPending--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=1}
01-25 15:29:58.027 29033-29033/com.allin.appbasefeature I/Download2Activity: (status1)Download2Activity-->onStart--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=1}
01-25 15:29:58.401 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onConnected--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}
01-25 15:29:58.429 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->4096, total->163162080, speed:0
01-25 15:29:59.323 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->1621314, total->163162080, speed:1792
01-25 15:30:00.086 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->3239234, total->163162080, speed:1792
01-25 15:30:00.760 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->4857154, total->163162080, speed:2253
01-25 15:30:00.882 29033-29033/com.allin.appbasefeature I/Download2Activity: (status5)Download2Activity-->onPause--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=5}, cur:4857154, total:163162080
01-25 15:30:06.025 29033-29033/com.allin.appbasefeature I/Download2Activity: (status1)Download2Activity-->onPending--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=1}
01-25 15:30:06.055 29033-29033/com.allin.appbasefeature I/Download2Activity: (status1)Download2Activity-->onStart--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=1}
01-25 15:30:06.260 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onConnected--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}
01-25 15:30:06.289 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->5344578, total->163162080, speed:0
01-25 15:30:06.818 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->6961790, total->163162080, speed:3028
01-25 15:30:07.061 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->8579710, total->163162080, speed:3028
01-25 15:30:07.404 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->10197630, total->163162080, speed:3028
01-25 15:30:07.659 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->11815550, total->163162080, speed:3028
01-25 15:30:07.948 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->13433470, total->163162080, speed:5788
01-25 15:30:08.209 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->15051390, total->163162080, speed:5788
01-25 15:30:08.487 29033-29033/com.allin.appbasefeature I/Download2Activity: (status5)Download2Activity-->onPause--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=5}, cur:15051390, total:163162080
01-25 15:30:15.559 29033-29033/com.allin.appbasefeature I/Download2Activity: (status1)Download2Activity-->onPending--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=1}
01-25 15:30:15.593 29033-29033/com.allin.appbasefeature I/Download2Activity: (status1)Download2Activity-->onStart--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=1}
01-25 15:30:15.801 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onConnected--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}
01-25 15:30:15.827 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->16312958, total->163162080, speed:0
01-25 15:30:16.231 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->17930169, total->163162080, speed:3954
01-25 15:30:16.488 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->19548089, total->163162080, speed:3954
01-25 15:30:16.758 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->21166009, total->163162080, speed:3954
01-25 15:30:17.007 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->22783929, total->163162080, speed:3954
01-25 15:30:17.254 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->24401849, total->163162080, speed:6307
01-25 15:30:17.509 29033-29033/com.allin.appbasefeature I/Download2Activity: (status5)Download2Activity-->onPause--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=5}, cur:24401849, total:163162080
01-25 15:30:28.842 29033-29033/com.allin.appbasefeature I/Download2Activity: (status1)Download2Activity-->onPending--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=1}
01-25 15:30:28.875 29033-29033/com.allin.appbasefeature I/Download2Activity: (status1)Download2Activity-->onStart--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=1}
01-25 15:30:29.121 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onConnected--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}
01-25 15:30:29.148 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->25995193, total->163162080, speed:0
01-25 15:30:29.560 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->27612163, total->163162080, speed:3849
01-25 15:30:29.825 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->29230083, total->163162080, speed:3849
01-25 15:30:30.087 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->30848003, total->163162080, speed:3849
01-25 15:30:30.361 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->32465923, total->163162080, speed:3849
01-25 15:30:30.615 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->34083843, total->163162080, speed:6145
01-25 15:30:30.807 29033-29033/com.allin.appbasefeature I/Download2Activity: (status5)Download2Activity-->onPause--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=5}, cur:34083843, total:163162080
01-25 15:30:38.367 29033-29033/com.allin.appbasefeature I/Download2Activity: (status1)Download2Activity-->onPending--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=1}
01-25 15:30:38.398 29033-29033/com.allin.appbasefeature I/Download2Activity: (status1)Download2Activity-->onStart--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=1}
01-25 15:30:38.710 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onConnected--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}
01-25 15:30:38.740 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->35210243, total->163162080, speed:0
01-25 15:30:39.090 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->36827213, total->163162080, speed:4358
01-25 15:30:39.401 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->38445133, total->163162080, speed:4358
01-25 15:30:39.652 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->40063053, total->163162080, speed:4358
01-25 15:30:39.930 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->41680973, total->163162080, speed:4358
01-25 15:30:40.248 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->43298893, total->163162080, speed:5603
01-25 15:30:40.601 29033-29033/com.allin.appbasefeature I/Download2Activity: (status5)Download2Activity-->onPause--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=5}, cur:43298893, total:163162080
01-25 15:30:47.605 29033-29033/com.allin.appbasefeature I/Download2Activity: (status1)Download2Activity-->onPending--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=1}
01-25 15:30:47.655 29033-29033/com.allin.appbasefeature I/Download2Activity: (status1)Download2Activity-->onStart--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=1}
01-25 15:30:47.942 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onConnected--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}
01-25 15:30:47.973 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->44892237, total->163162080, speed:0
01-25 15:30:48.485 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->46509207, total->163162080, speed:3079
01-25 15:30:48.797 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->48127127, total->163162080, speed:3079
01-25 15:30:49.079 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->49745047, total->163162080, speed:3079
01-25 15:30:49.339 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->51362967, total->163162080, speed:3079
01-25 15:30:49.610 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->52980887, total->163162080, speed:5783
01-25 15:30:49.901 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->54598807, total->163162080, speed:5783
01-25 15:30:50.273 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->56216727, total->163162080, speed:5783
01-25 15:30:50.458 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->57834647, total->163162080, speed:5783
01-25 15:30:50.537 29033-29033/com.allin.appbasefeature I/Download2Activity: (status5)Download2Activity-->onPause--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=5}, cur:57834647, total:163162080
01-25 15:30:55.555 29033-29033/com.allin.appbasefeature I/Download2Activity: (status1)Download2Activity-->onPending--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=1}
01-25 15:30:55.590 29033-29033/com.allin.appbasefeature I/Download2Activity: (status1)Download2Activity-->onStart--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=1}
01-25 15:30:56.101 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onConnected--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}
01-25 15:30:56.128 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->4096, total->163162080, speed:0
01-25 15:30:56.685 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->1621314, total->163162080, speed:2857
01-25 15:30:56.964 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->3239234, total->163162080, speed:2857
01-25 15:30:57.220 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->4857154, total->163162080, speed:2857
01-25 15:30:57.540 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->6475074, total->163162080, speed:2857
01-25 15:30:57.815 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->8092994, total->163162080, speed:5809
01-25 15:30:58.102 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->9710914, total->163162080, speed:5809
01-25 15:30:58.479 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->11328834, total->163162080, speed:5809
01-25 15:30:58.693 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->12946754, total->163162080, speed:5809
01-25 15:30:58.973 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->14564674, total->163162080, speed:5507
01-25 15:30:59.248 29033-29033/com.allin.appbasefeature I/Download2Activity: (status4)Download2Activity-->onProgress--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=4}, current->16182594, total->163162080, speed:5507
01-25 15:30:59.371 29033-29033/com.allin.appbasefeature I/Download2Activity: (status5)Download2Activity-->onPause--> DownloadModel{id=-198470420, fileName='1515980102_480_320.mp4', path='/storage/emulated/0/Download/1515980102_480_320.mp4', url='https://vpro.medplus.net/1515980102_480_320.mp4?1515988809', status=5}, cur:16182594, total:163162080
@Jeffin21

**Comment by rantianhua** [comment]
Duplicate with #815
