### ISSUE TITLE
百度网盘总是出错，有log，貌似跟请求头有关

### ISSUE THREAD

**Issue by fewwind** [lingochamp/FileDownloader#893]
error = com.liulishuo.filedownloader.exception.FileDownloadHttpException: response code error: 403, 
equest headers: {Range=[bytes=0-]} 
response headers: {null=[HTTP/1.1 403 Forbidden], Connection=[keep-alive], Content-Length=[62], Content-Type=[text/html], Date=[Wed, 27 Dec 2017 09:39:53 GMT], ETag=["5566be1c-3e"], Server=[POMS/CloudUI 1.0], X-Android-Received-Millis=[1514367593686], X-Android-Response-Source=[NETWORK 403], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1514367592883]}

**Comment by rantianhua** [comment]
错误码已经很清楚了，服务器拒绝你的请求，比如这个下载链接是否需要认证？所以这个其实不是 Filedownloader 本身的问题。

**Comment by Seachal** [comment]
对我来说， 第一个版本服务端没有对文件下载进行鉴权限制，可以正常下载，第二个版本，服务端开始改造增加鉴权，对已经调用过一次的下载链接进行失效处理，我这边就会遇到下面这样的异常， 
 ```
ava.net.SocketException: Connection failed with request[{Range=[bytes=4073926-8147851], User-Agent=[FileDownloader/1.7.7]}] response[{null=[HTTP/1.1 403 Forbidden], Access-Control-Allow-Methods=[GET], Access-Control-Allow-Origin=[*], Connection=[keep-alive], Content-Length=[238], Content-Type=[text/html], Date=[Mon, 29 Jan 2024 02:42:16 GMT], EagleId=[907b1f2217064961368347077e], Server=[Tengine], Timing-Allow-Origin=[*], Via=[cache14.cn1306[,0]], X-Android-Received-Millis=[1706496136376], X-Android-Response-Source=[NETWORK 403], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1706496136196]}] http-state[403] on task[-891346639-1], which is changed after verify connection, so please try again.   
```
最终发现是因为 下载库默认开启断点续传。
<img width="1058" alt="image" src="https://github.com/lingochamp/FileDownloader/assets/14776606/9e08f13e-211b-4e71-b8d3-70254f42e00d">


> Range 是一个请求首部，告知服务器返回文件的哪一部分。在一个 Range 首部中，可以一次性请求多个部分，服务器会以 multipart 文件的形式将其返回。如果服务器返回的是范围响应，需要使用 [206](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/206) Partial Content 状态码。假如所请求的范围不合法，那么服务器会返回 [416](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/416) Range Not Satisfiable 状态码，表示客户端错误。服务器允许忽略 Range 首部，从而返回整个文件，状态码用 [200](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/200) 。

所以我这边的情况是，服务端做修改适配客户端的断点续传，客户端不需要修改。
