### ISSUE TITLE
在Android 5.0以上无法下载到外置SD卡

### ISSUE THREAD

**Issue by waynell** [lingochamp/FileDownloader#896]
#### Issue
由于Android 4.4之后限制了直接读写外置SD卡的能力，因此想要下载文件到外置SD卡上需要使用SAF框架来获取相应的文件读写权限。目前代码中操作文件的方法都在FileDownloadUtils中，但都是直接使用File类，这样必然会因无读写权限导致一直下载失败

建议：抽象出FileDownloadUtils，让上层可以通过定制的方式实现自己的文件操作类

**Comment by Jacksgong** [comment]
这个问题其实很早就有讨论了: #32

---

之前我尝试过在FileDownloader上面实现，但是一直没有合入，甚至有朋友单独拉出来提PR: #821 ，但是在FileDownloader上面的改动点很大，而FileDownloader本身的单元测试有限，显得不够可靠。

---

### 为什么我拉单独分支搞改动点大，而非开放如你说所的`FileDownloadUtils`来实现呢?

具体原因也可以参看下这里: https://github.com/lingochamp/FileDownloader/issues/349#issuecomment-306375234

主要是因为，这块涉及重新设计断点续传相关文件存储机制，还有涉及的所有旧版本升级的一个数据迁移的问题等。

---

回答下你的问题，其实现在输出流本身就支持定制: [wiki-customizable-component](https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component)

---

### 这个问题就置之不理了吗？

根源问题是FileDownloader本身整个设计问题，因此我重新写了[FileDownloader2-okdownload](https://github.com/lingochamp/okdownload)，这个问题已经在okdownload上解决了，近期公司这边事情比较多，不过okdownload马上会release第一个版本了。
