### ISSUE TITLE
希望能够提供一个错误码，对于各种错误类型做出对应处理

### ISSUE THREAD

**Issue by susirsusir** [lingochamp/FileDownloader#897]
The file is too large to store, breakpoint in bytes: 0, required space in bytes: 2537339, but free space in bytes: 1638400 
The file is too large to store, breakpoint in bytes: 0, required space in bytes: 2537339, but free space in bytes: 0   
这类错误希望能够提供一个错误码，以便于给用户做出相对应提示

**Comment by rantianhua** [comment]
对于这个错误 FileDownloader 已经封装了 FileDownloadOutOfSpaceException 这个错误类型，所以其实不需要错误码的。

**Comment by Jacksgong** [comment]
这点其实作为Android项目不像iOS项目，Android(Java)项目更推荐的是采用不同的`Exception`类型来区分不同的异常以带回更多的信息，而非单纯错误码。
