### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by e4basil** [lingochamp/FileDownloader#9]
protected void FileDownloadManager() {
		     if (isNetworkAvailable()) {

			String[] URLS = {
					"http://www.test............mp3",
					"http://www.test2..........mp3"};
			downloadListener = createLis();
			int i = 0;
			for (String url : URLS) {

				
				FileDownloader.getImpl().create(url)
						
						.setPath(locationCreation() + File.separator + url.substring(url.lastIndexOf("/") + 1))
						.setListener(downloadListener)
						.setAutoRetryTimes(1)
						.setTag(i + 1)
						.setCallbackProgressTimes(1)
						.ready();

				i++;
			}

	
			FileDownloader.getImpl().start(downloadListener, true);

		}
	}

	private FileDownloadListener createLis() {

		return new FileDownloadListener() {
			@Override
			protected void pending(BaseDownloadTask task, int soFarBytes, int totalBytes) {
				if (task.getListener() != downloadListener) {
					return;
				}
				Log.d(TAG, "pending() :" + task.getTag());
			}

			@Override
			protected void connected(BaseDownloadTask task, String etag, boolean isContinue, int soFarBytes, int totalBytes) {
				super.connected(task, etag, isContinue, soFarBytes, totalBytes);
				if (task.getListener() != downloadListener) {
					return;
				}
				Log.d(TAG,"connected() :"+task.getTag());
			}

			@Override
			protected void progress(BaseDownloadTask task, int soFarBytes, int totalBytes) {
				if (task.getListener() != downloadListener) {
					return;
				}
				Log.d(TAG,"progress() :"+task.getTag());
			}

			@Override
			protected void blockComplete(BaseDownloadTask task) {
				if (task.getListener() != downloadListener) {
					return;
				}
				Log.d(TAG,"blockComplete() :"+task.getTag());
			}

			@Override
			protected void retry(BaseDownloadTask task, Throwable ex, int retryingTimes, int soFarBytes) {
				super.retry(task, ex, retryingTimes, soFarBytes);
				if (task.getListener() != downloadListener) {
					return;
				}
				Log.d(TAG,"retry() :"+task.getTag());
			}

			@Override
			protected void completed(BaseDownloadTask task) {
				if (task.getListener() != downloadListener) {
					return;
				}

				if (task.isReusedOldFile()) {

				} else {

				}
				Log.d(TAG,"completed() :"+task.getTag());
			}

			@Override
			protected void paused(BaseDownloadTask task, int soFarBytes, int totalBytes) {
				if (task.getListener() != downloadListener) {
					return;
				}
				Log.d(TAG,"paused() :"+task.getTag());
			}

			@Override
			protected void error(BaseDownloadTask task, Throwable e) {
				if (task.getListener() != downloadListener) {
					return;
				}
				Log.d(TAG,"error() :"+task.getTag());
				Log.d(TAG, "error() : "+e.getMessage());
			}

			@Override
			protected void warn(BaseDownloadTask task) {
				if (task.getListener() != downloadListener) {
					return;
				}
				Log.d(TAG,"warn() :"+task.getTag());
			}
		};
	}

it shows error() : sofar[377462] not equal total[-1]
but it downloads file

**Comment by Jacksgong** [comment]
Could you give me your download link,  i will try and give you solution.

---

That means has read all bytes from remote but downloaded size not equal contentLength( we get the Content-Length from the header in the response object)

**Comment by e4basil** [comment]
for testing i used 
http://www.funonsite.com/funarea/ringtones/download-ringtone-953-funonsite.com.mp3
and http://www.funonsite.com/funarea/ringtones/download-ringtone-951-funonsite.com.mp3

**Comment by Jacksgong** [comment]
Thanks for your feedback very much.

those are stream medias(which not give `Content-Length` (don't konw) instance of `Transfer-Encoding: chunked``, I will consider support this in next version.

**Comment by Jacksgong** [comment]
add support: [feat(chunked): support chunked transfer encoding data download](https://github.com/lingochamp/FileDownloader/commit/4102c4ba95a8f7c9f6d5ab2ba5028f59b48e3225)

and test(Single task test page): [test(chunk): add chunked transfer encoding data download test](https://github.com/lingochamp/FileDownloader/commit/a39ede526bac0f97be2c63fd50ede40b304a77fb)
