### ISSUE TITLE
测试发现的问题

### ISSUE THREAD

**Issue by ynlh** [lingochamp/FileDownloader#90]
1.建立了一个下载，下载未完成，直接关闭应用，FileDownloader的service未被kill，然后重新打开应用，重新走 start 流程，发现不会回调 progress 了，只会在一段时间后回调 completed。请问是 bug吗？要怎么才能继续回调 progress  呢？
2. 测试下载中，默认 10ms回调，progress  里面的进度走势并不顺畅，感觉是跳动一下，然后顿一下，然后又 迅速跳几下进度，又卡顿一会， 比较了其它几个下载库，感觉不顺畅。即使时间设置为0.1s 也并无改观。是否就是这样的呢？

**Comment by Jacksgong** [comment]
💯 

感谢你提供的反馈。

#### 第一个问题:

其实这个问题根据 0.2.2 以后的提交有进行了优化。。我刚刚检查了下，并不是不会回调了。而是回调回来带回来的totalBytes是0，因此progress给了max是0，无论给sofar多少就不会有进度。 ---- 这个问题，我一会儿修复掉。

#### 第二个问题:

是这样子的，这个和用户的网络情况有关，是因为下载过程中的下载速度无法达到匀速，由于受到用户所处的网络情况影响，比如信号情况、同一个网络环境下其他人突然暂用了网络、服务端的带宽突然吃紧、异或是同一个手机其他App占用了网络资源等等。因此即便是做 10ms轮询一下但是由于下载进程不是均匀的也会有跳跃的情况。不过在一种理论的情况下可以达到顺畅，那就是下载速度足够快，并且回调足够频繁，不过用户的网络情况是无法预估的，因此如果想要让跳跃不会突兀，我推荐一个很轻的库: [PercentSmoothHandler](https://github.com/Jacksgong/PercentSmoothHandler)。

目前FileDownloader提供的回调 `setCallbackProgressTimes` 是设置 最大回调 `progress` 的次数。FileDownloader能够做到的是根据所需要回调次数计算并保证: 每个 `progress` 回调之间 所下载的 文件大小 是均匀的，比如 通过计算，针对某一任务需求，保证 每下载5kb回调一次。

> P.S: 在FileDownloader中，根据这个回调的次数计算多少字节回调一次: 由于FileDownloader取buffer是4096byte一次，因此最小的回调单元是4096byte并且 一般情况下回调间隙也会是4096byte(或者一些特殊情况下，取回的buffer更少些如2048byte) 的倍数。

**Comment by Jacksgong** [comment]
Has been supported since [v0.2.3](https://github.com/lingochamp/FileDownloader/releases/tag/v0.2.3).
