### ISSUE TITLE
setCallbackProgressTimes这个方法设置回调次数和实际的次数不一致

### ISSUE THREAD

**Issue by iammasir** [lingochamp/FileDownloader#901]
#### Before Issue

1. Please search on the [Issues](https://github.com/lingochamp/FileDownloader/issues)
2. Please search on the [wiki](https://github.com/lingochamp/FileDownloader/wiki)
3. Please set `FileDownloadLog.NEED_LOG=true` and review the Logcat output from main process and `:filedownloader` process ( pay attention to Warn and Error level logcat)

#### Issue

1. What problem do you get?
2. Which version of FileDownloader are you using when you produce such problem?
3. How to reproduce such problem?
4. Do you set `FileDownloadLog.NEED_LOG=true`?
5. Could you please reproduce this problem and provide all main process and `:filedownloader` process logcat 
6. Can you fix it by yourself and request PR, if not, what's problem do you get when you try to fix it

>P.S. If you don't know how to get `:filedownloader` process, it's recommended to using `pidcat` to just filter all your application logcat, or define `process.non-separate=true` on [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)

---

请在Issue前认真的跟进上面提到的建议，这样将可以极大的加快你遇到问题的处理。

**Comment by iammasir** [comment]
我设置的3，结果回掉了5次，有时候甚至更多次。这个不是设置的最大回调次数吗？1.6.9，单任务下载

**Comment by rantianhua** [comment]
你的下载链接是支持分片下载的吗？如果是的话，那这个方法不会起作用，这一点在方法注释上也有说明：
> <strong>Note:</strong> this function will not work if the URL is refer to 'chucked' resource.

**Comment by iammasir** [comment]
https://image.xianimi.org/video_o_1c11h45ap13ui15vsppb1m9vn9i905.mp4    我用的是这个地址，应该支持分片的吧

**Comment by rantianhua** [comment]
@iammasir 这确实是个 bug
