### ISSUE TITLE
Cancel a task (Not pause)

### ISSUE THREAD

**Issue by dreasn** [lingochamp/FileDownloader#903]
How to cancel a task?  (not pause)
And then when start download again it will start from zero.

**Comment by rantianhua** [comment]
You can reference this method:
https://github.com/lingochamp/FileDownloader/blob/2129bfaeb261e29b301fd5d6c1ebb00bdb0071e1/library/src/main/java/com/liulishuo/filedownloader/FileDownloader.java#L309-L349
