### ISSUE TITLE
网络状态切换，任务的状态是progress，导致无法继续下载

### ISSUE THREAD

**Issue by AngelSpace** [lingochamp/FileDownloader#904]
当正在下载的过程中，断开网络然后再连上，此时任务的状态是progress。
1、如果重新加到下载队列，会回调warn，队列已经有这个任务
2、如果调用task.reuse()提示
This task[-1647075470] is running, if you want start the same task, please create a new one by FileDownloader#create
3、重新创建任务也不能继续下载。

请问网络切换如何续传。

**Comment by YangShaoXiong** [comment]
我觉得可以写个监听网络变化的广播，如果网络发生发变化，那么就可以吧所有下载任务暂停pauseAll()，这时候可以给个对话框提示，是否要继续下载，如果需要继续下载，那么就把下载任务列表中只要任务状态不是complete的，全部添加到下载队列中。

**Comment by rantianhua** [comment]
主要的问题在于：
> 当正在下载的过程中，断开网络然后再连上，此时任务的状态是progress
网络断开重连并不是一个平滑的操作，当网络断开后，正在下载的任务会抛出 Error ，所以你上面的 case 下，任务的状态应该是 error 而不是 progress 。我用 Demo 中 任务管理器案例 中的最后一个任务测试，情况是符合我所描述的。所以我不清楚你是在哪种使用条件下出现断开网络后获取任务的状态为 progress ，关于这个希望提供更详细的信息。

对于网络切换后继续下载的讨论，可以参考 #632
