### ISSUE TITLE
java.net.ProtocolException: unexpected end of stream

### ISSUE THREAD

**Issue by yuxingfafu** [lingochamp/FileDownloader#906]
01-09 16:03:24.319 27846-27846/com.abc.tu W/System.err: java.net.ProtocolException: unexpected end of stream
01-09 16:03:24.319 27846-27846/com.abc.tue W/System.err:     at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:434)
01-09 16:03:24.319 27846-27846/com.abc.tu W/System.err:     at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:349)
01-09 16:03:24.319 27846-27846/com.abc.tu W/System.err:     at java.io.InputStream.read(InputStream.java:162)
01-09 16:03:24.319 27846-27846/com.abc.tu W/System.err:     at com.liulishuo.filedownloader.download.FetchDataTask.run(FetchDataTask.java:133)
01-09 16:03:24.319 27846-27846/com.abc.tu W/System.err:     at com.liulishuo.filedownloader.download.DownloadRunnable.run(DownloadRunnable.java:113)
01-09 16:03:24.319 27846-27846/com.abc.tu W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
01-09 16:03:24.319 27846-27846/com.abc.tu W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-09 16:03:24.319 27846-27846/com.abc.tu W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
01-09 16:03:24.319 27846-27846/com.abc.tuW/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
01-09 16:03:24.319 27846-27846/com.abc.tu W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by rantianhua** [comment]
请提供下上下文，比如下载链接，在哪种使用情况下出现这个错误？目前这个我只能推测这是一个无效的下载链接。

**Comment by Jacksgong** [comment]
相关问题，参考这里 https://github.com/lingochamp/FileDownloader/issues/652#issuecomment-314389397
