### ISSUE TITLE
一个视频多个分块，我用多任务 下载如何获取当前总速度呢

### ISSUE THREAD

**Issue by yang0000meng** [lingochamp/FileDownloader#907]
一个视频多个分块，我用多任务 下载如何获取当前总速度呢
看demo只能获取当前某一个BaseDownloadTask 的速度。

**Comment by rantianhua** [comment]
对于你的描述，我有两个理解：
1. 如果是单任务分块下载的话，那么进度获取的问题可以参考 #913 。
2. 如果你是多个任务（我理解的是多个 BaseDownloadTask ），那么请参考  #256
