### ISSUE TITLE
FileDownloadUtils里的CONTENT_DISPOSITION_PATTERN正则貌似多匹配了2个引号

### ISSUE THREAD

**Issue by dzbx** [lingochamp/FileDownloader#908]
注释的W3C链接（http://www.w3.org/Protocols/rfc2616/rfc2616-sec19.html） 里虽然举了个例子：attachment; filename="fname.ext"，但并没有强制要求文件名必须要使用双引号，然后W3C链接里还有个RFC 1806（http://www.ietf.org/rfc/rfc1806.txt） 的链接来解释了Content-Disposition，但里面的例子里文件名并没有双引号：attachment; filename=genome.jpeg。

现在这个正则强制匹配文件名的双引号，导致没有没有双引号的时候拿不到文件名了，这是当时故意这么设计的吗？

**Comment by rantianhua** [comment]
是的，当时只是按照 http://www.w3.org/Protocols/rfc2616/rfc2616-sec19.html 上面设计的。

**Comment by Jacksgong** [comment]
@dzbx 多谢提醒。。
@rantianhua 这个问题还是需要处理一下的。。

---

早期这个是参照w3c，后来改用Android [DownloadThread](http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android-apps/5.1.1_r1/com/android/providers/downloads/Helpers.java#44) 上的这个正则。

---

这个问题我在1.7.0上修复吧。
