### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by ynlh** [lingochamp/FileDownloader#91]
1.测试一个下载，下载进行中时，主动断开了手机的网络连接（wifi），发现只回调了retry一次（初始下载时设置了 自动重试 3次）
2.然后进入了 error，我收到 error后，主动调用 task.start(); 但发现并未发生预计出现的任何事情（比如，继续回调 error 或者 retry）（这时主动调用时， 即使是我主动开启了网络连接依然如此），是机制就这这样的吗？感觉这样子，出现了异常，难道只能 主动delete下载包继续新建下载 重新下载吗？
3.setCallbackProgressTimes 是有默认值吗？发现 设置 1000 后，回调progress会平滑很多，是否可以关闭这个限制？就以设置的回调间隔来回调 progress 呢？
4.是否可以拓展个内部的数据，downloadSpeed 和 remainingTime，如果自己实现的话，因为 progress回调的间隔时间实在是业务层无法掌握的节奏，它是不确定的，我本想自己通过间隔来算，发现回调的不确定 算不了这个速度，剩余时间也同样算不了。是否可以在 lib 内部实现这个 速度和时间的 估算呢？这个需求应该算是很常规的需要把

**Comment by Jacksgong** [comment]
💯 

#### 第一个问题:

屌屌的， 第一个问题，确实是一个bug，内部实际是有回调的，但是在安全检查过程中，`KeepFlow` 没有考虑到，retry之后连连接都没有连接上去的情况，也就是用户可能会接连收到retry的情况。这个问题，我一会儿提交。


#### 第二个问题:

很好的点，之前我没有表述清楚，我相信你是直接用了返回回来的参数 `BaseDownloadTask` 然后调用它的 `start` 进行开始的，实际上，这里返回的Task，是为了获取当前Task的信息，而由于这个task在内部消息流中已经是结束状态因此你无法重新用这个task启动该任务，当然你可以通过 `FileDownloader` 重新创建一个相同的Task开始是没有任何问题的。P.S: 这里我考虑在架构层进行封装下，避免这样的误会，也会考虑一些 `build` 或者是 `cloneOperation` 的方法。

#### 第三个问题:

至于默认值我相信你看下源码上面就有注解:

```
/**
 * Set maximal callback times on
 * callback {@link FileDownloadListener#progress(BaseDownloadTask, int, int)}
 *
 * @param callbackProgressTimes Maximal callback progress status times,
 *                              Default 100, <=0 will not have any progress callback
 */
public BaseDownloadTask setCallbackProgressTimes(int callbackProgressTimes) {
    this.callbackProgressTimes = callbackProgressTimes;
    return this;
}
```

至于你说的限制，我不是很明白，这里没有存在什么限制，没有上限。如果非要说限制恐怕有一个就是我之前在你的另外一个task提到的，我们去文件buffer是 4096byte 取一次，因此这里只能是他的倍数，举一个比较极端的例子，假如文件只有 5K，这时候你设置的回调是1000次，那么回调也只有1次。

#### 第4个问题

首先目前的回调而言，在上层业务层是可以做的，而且比较简单: 通过已经消耗的时间，以及在progress回调回来的sofar完全可以估算出速度以及剩余时间。

其实，其实作为下载器来说我觉得应该是基本需求，但是如果作为下载库来说，这个需求不是很紧急，绝大多数的人（包括我们自己）也都只是需要用这个来稳定以及高并发下载，但是在未来的版本迭代中，我们会考虑的。

**Comment by ynlh** [comment]
谢谢及时解答哈，真速度！
第三个问题，我的意思是，是否可以禁用掉设置callback次数的这个特性，只想就根据10ms那个值来回调，并不考虑其它，（额，这个需求很奇怪吗，啊哈·····）
第四个问题，确实是我自己思维蠢了，我之前只想在 progress 回调中算 速度，但因为回调并不是严格按照10ms来的，所以算出的值是错误的。。。其实你一说发现完全可以，跳出来算，唉，思维不够发散，哈哈

**Comment by Jacksgong** [comment]
👍 

其实即使 10ms回调一次，每次填充文件都是4096byte，因此如果没有填充，就会存在很多相同的可以说是冗余的回调。而对于一些对性能要求苛刻的用户恐怕还是需要这块的设置项存在的。

**Comment by Jacksgong** [comment]
Has been supported since [v0.2.3](https://github.com/lingochamp/FileDownloader/releases/tag/v0.2.3).
