### ISSUE TITLE
您好,请问如何判断当前整个项目是否还有正在下载的进程?

### ISSUE THREAD

**Issue by justziyang** [lingochamp/FileDownloader#910]
因为在当前正在下载的列表界面,需要显示一个全部开始和全部暂停的按钮,如果有一个任务在就得显示全部暂停,如果一个都没有就要显示全部开始,所以需要判断一下全局还有没有正在下载的进程()

**Comment by YangShaoXiong** [comment]
我觉得可以循环遍历下载列表中的状态，如果有状态等于pending、started、connected、progress中的一个，那么就表示当前下载列表有正在进行的任务，反之则没有。

**Comment by rantianhua** [comment]
补充 @YangShaoXiong 所说的，其实只要 task 的状态不是 completed ，都可以当做 “可继续下载” 的任务，至于一些特殊的状态，比如 error ，你想忽略还是希望当做可以再次重下的任务都取决于你自己。
