### ISSUE TITLE
怎样去除http头 Range，下载搜狐视频http头不能有Range

### ISSUE THREAD

**Issue by yang0000meng** [lingochamp/FileDownloader#911]
task.removeAllHeaders("Range"); 好像不管用

**Comment by Jacksgong** [comment]
正常情况，如果不支持`Range`，返回状态码非`206`为其他正确的状态码，就会自动从头开始下载，下载不受影响。

---

如果说，你说的不支持`Range`，是只要给了`Range`那么就直接连接被断开，或返回5xx、4xx之类的状态码，那么就只能考虑将请求头中的`Range`去掉。但是去掉`Range`并没有想的那么简单，需要考量亮点:

1. 移除请求头上的`Range`
2. 保证每次都是从0开始下载

---

### 如何操作呢?

首先，添加`Range`是在`ConnectTask#addRangeHeader`，但这些都不重要，你完全可以定制自己的`FileDownloadConnection`，在`addHeader`的地方把`Range`过滤掉。
其次，你需要在每次启动该任务之前，通过`FileDownloader#clear`将该任务从数据库中清楚掉，以保证每次输出流都是从`0`开始写入数据。

**Comment by yang0000meng** [comment]
可否用另一种思路 ，HttpProxyCacheServer 用代理实现
地址是这样的。
http://127.0.0.1:36134/http%3A%2F%2F42.236.121.136%2Fsohu%2Fv1%2FTmPGTmwGqAIWb2sBDt87g661yM83o4wmDBybTToF5m47fFoGRMNiNw.mp4%3Fk%3DPSfMkr%26p%3Dj9lvzSw3oSsdopkAopwdoprWXZxIWhoVqTPcWFbOZYy4ZhoBoJ2svm1BqVPcNmsdytP%26r%3DTmI20LscWOo70Sc2ZDASqt8IS3pOZb7kkvGkws7SkwU4fGHjkI6eAcIZaEJiYvS9bgO5wW49JLzSkioKOyOHXIY%26q%3DOpCmhW7IWJodRD64WYbSotE7ZD6OfOXXlG6sfJXsWB1S0F2OfDvtfGdsWOoURD6tZYoUZDJ%26cip%3D123.9.102.170

**Comment by Jacksgong** [comment]
是支持传入`Proxy`的，即便是默认的`FileDownloadConnection`，如Demo中强制使用`NO_PROXY`:

```
/**
* just for cache Application's Context, and ':filedownloader' progress will NOT be launched
* by below code, so please do not worry about performance.
* @see FileDownloader#init(Context)
*/
FileDownloader.setupOnApplicationOnCreate(this)
        .connectionCreator(new FileDownloadUrlConnection
                .Creator(new FileDownloadUrlConnection.Configuration()
                .connectTimeout(15_000) // set connection timeout.
                .readTimeout(15_000) // set read timeout.
                .proxy(Proxy.NO_PROXY) // set proxy
        ))
        .commit();
```

**Comment by congwiny** [comment]
@Jacksgong 126、163邮箱无法下载附件。原因是不支持断点下载，416状态码。
如果不添加Range就能下载了，但是大多服务器是支持Range的，怎么能做到兼容呢？
-----------
能不能在retry的时候，把Range这个请求参数给去掉呢？

**Comment by luofeng225** [comment]
**问题**：使用过程中发现问题，请求头带range ，请求被网络设备截断

**分析**：

最后导入整个库点，修改请求时候，通过head参数携带是否启用range信息，在
com\liulishuo\filedownloader\download\DownloadLaunchRunnable.java
对isNeedForceDiscardRange属性进行设定

每次清理，从0开始下载
