### ISSUE TITLE
How To Check Progress Of multiple connection ??

### ISSUE THREAD

**Issue by creativelabsofficial** [lingochamp/FileDownloader#913]
Hi i can get progress of file download using lisner.
This library can stat multi threaded connections.
So how to set no of threads for download and get progress for every thread??

**Comment by Jacksgong** [comment]
FileDownloader doesn't callback each threads progress. but FileDownloader2 -> [okdownload](https://github.com/lingochamp/okdownload) has already provided such feature, please wait for okdownload release.

**Comment by creativelabsofficial** [comment]
Currently i am using Filedownloader for my app. but okdownload looks better and more promising. is it possible to start developing my app using "OKdownload" ( i mean okdownload is currently usable or not)

**Comment by Jacksgong** [comment]
@creativelabsofficial thanks, but okdownload isn't released now, it's very not recommended integrate it to your publish project now, please wait for its release.
