### ISSUE TITLE
您好,请问如何设置最多同时下载一个任务?使其他任务都处于等待状态

### ISSUE THREAD

**Issue by justziyang** [lingochamp/FileDownloader#914]
有一个需求,就是一个任务列表,同时只能有一个任务正在下载,其他的都在等待,类似于迅雷的最大同时任务数.请问该使用哪个方法?

**Comment by rantianhua** [comment]
你可以使用 `FileDownloadSerialQueue` ，它可以动态添加下载任务，并且保证任务是按添加的顺序一个一个下载。

**Comment by justziyang** [comment]
如果我有一个队列 有五个任务 我想暂停这个队列中的第三个任务 应该怎么做啊?我在demo中没有找到这个类的用法..

**Comment by rantianhua** [comment]
既然是队列，你可以直接拿出第三个 BaseDownloadTask 然后调用它的 pause 方法即可。
