### ISSUE TITLE
how resume current progress at progressbar when exit from activity and enter again this activity.

### ISSUE THREAD

**Issue by heinzan** [lingochamp/FileDownloader#915]

**Comment by rantianhua** [comment]
There are two ways to do that.
---
The first way you can create a global `FileDownloaderListener` for your download, a singleton class holds the listener in usual. And then you can dispatch any callback method to a new `FileDownloaderListener` as a field in the singleton class. So you just need to set a listener to the singleton class during `Activity#onCreate()` and  set null during `Activity#onDestroy()`.
---
Of course you can do it simpler in the second way. What you need is the method `FileDownloader#replaceListener(int, FileDownloadListener)`. The first parameter is the id of task and the second is the listener. So you can set a real listener every time you enter the activity and set null every time you exit from activity.

**Comment by rantianhua** [comment]
There are two ways to do that.

---

The first way you can create a global `FileDownloaderListener` for your download, a singleton class holds the listener in usual. And then you can dispatch any callback method to a new `FileDownloaderListener` as a field in the singleton class. So you just need to set a listener to the singleton class during `Activity#onCreate()` and  set null during `Activity#onDestroy()`.

---

Of course you can do it simpler in the second way. What you need is the method `FileDownloader#replaceListener(int, FileDownloadListener)`. The first parameter is the id of task and the second is the listener. So you can set a real listener every time you enter the activity and set null every time you exit from activity. There are two similar methods: `FileDownloader#replaceListener(String, FileDownloadListener)` and `#replaceListener(String, String, FileDownloadListener)`, you can get more information from the [api document](https://fd.dreamtobe.cn/)

**Comment by heinzan** [comment]
Please show me sample code.I cann't understand what you mean ako

**Comment by rantianhua** [comment]
@heinzan you can reference #4
