### ISSUE TITLE
您好,当一个任务暂停以后,再次启动只能调用最开始的create方法吗?

### ISSUE THREAD

**Issue by justziyang** [lingochamp/FileDownloader#917]
1.我通过FileDownloadList.getImpl().get(DownloadId).getOrigin().pause();暂停了一个任务,但是我再次调用这个方法start()的时候 返回的iRunningTask为空,所以只能通过FileDownloader.getImpl().create(mVideoUrl).setPath().start();这个方法来再次开始任务么?
2.一个暂停了的任务 我通过FileDownloader.getImpl().getStatus(DownloadId,path);获取当前的状态 只能拿到INVALID_STATUS,而且无法获取到sofar和total,我应该怎样去获取一个暂停以后的任务的sofar和total还有status呢?
求指点,非常感谢!

**Comment by rantianhua** [comment]
1. 重新创建任务并 start 是可以的，FileDownloader 内部会自动断点续传。但如果你想重用之前的任务，可以使用 BaseDownloadTask#reuse() 方法，需要注意的是，reuse 之后需要调用 start 方法才能开启下载。关于 pause ，可以参考 https://github.com/lingochamp/FileDownloader/wiki/Pause-or-Stop 。还有关于类似的讨论也可以参考：#108
2. 一个暂停了的任务，获取的状态应该是 paused ，除非你的下载进程挂掉了，获取 soFar 和 total 也是类似的。如果是下载进程挂掉了，你可以使用 `FileDownloader#bindService(final Runnable runnable)` 方法，将获取状态等操作放在 Runnable 里面执行。

**Comment by Jacksgong** [comment]
@justziyang 确保下载服务存在来获取相关状态，也可以参考下这个: https://github.com/lingochamp/FileDownloader/issues/497#issuecomment-282973160
