### ISSUE TITLE
多个下载队列，如何只停止其中一个下载队列，pauseAll应该是停止全部下载队列吧

### ISSUE THREAD

**Issue by qyjandroid** [lingochamp/FileDownloader#918]
应用中有可能同时开启多个下载队列，有的队列是串行，有的是并行，我想问下怎样停止其中的一个队列！

**Comment by rantianhua** [comment]
如果你是队列下载且设置的有 `FileDownloadListener` 的话，暂停一个下载队列是很简单的事情：
https://github.com/lingochamp/FileDownloader/blob/f6dbb5e9b40f2db10c1ea6e3447e07a66b9214ee/library/src/main/java/com/liulishuo/filedownloader/FileDownloader.java#L242-L255

--- 

如果你不想设置 `FileDownloadListener` 且不想用 pauseAll 方法，那就遍历队列中的 `BaseDownloadTask` ，逐个暂停。

**Comment by qyjandroid** [comment]
好的，谢谢了
