### ISSUE TITLE
新问题，关于自动重试

### ISSUE THREAD

**Issue by ynlh** [lingochamp/FileDownloader#92]
测试发现，如果设置了自动重试（比如 3次），我进行如下操作： 下载一个文件，在进行了一段时间后，这时切到后天，主动关闭手机的网络（wifi），这是切回应用，会回调 error，这时我主动重新开始 调用下载，不是（task.start()）而是： FileDownloader.getImpl().create(url).setPath(path).setCallbackProgressTimes(1000).setListener(mFileDownloadListener).start(); 因为这时还没有网络，所以会回调 retry 一次（只有一次），然后 error，这时主动去开启网络，继续重新开始下载，这时下载进度却从 0开始了，不管测试是 第一次回调 error之前重新联网还是 回调了error之后重新联网，都是这样的结果，断点续传失效了。
然后继续测试 建立下载的时候 不设置自动重试的次数，重试以上的过程，主动联网后，再次调用下载，可以断点续传，以前的下载进度存在。

**Comment by Jacksgong** [comment]
自动重试这个在 #91 已经修复了。

👍  恩，我看了下，这个断网以后，再重新下载，确实会导致sofar被覆盖，我已经找到原因了，一会儿处理下。

很感谢你的细心。

**Comment by Jacksgong** [comment]
Has been fixed since [v0.2.3](https://github.com/lingochamp/FileDownloader/releases/tag/v0.2.3).
