### ISSUE TITLE
文件大于25兆的时候下载到80，会突然变成－80 ,然后出现问题，代码如下

### ISSUE THREAD

**Issue by panjichang** [lingochamp/FileDownloader#922]
@Override
    protected void completed(BaseDownloadTask task) {
        super.completed(task);
        if(mListener!=null)
        mListener.onCompleted();
    }
    @Override
    protected void progress(final BaseDownloadTask task, final int soFarBytes, final int totalBytes) {
        super.progress(task,soFarBytes,totalBytes);
        if(mListener!=null)
        mListener.onProgress(soFarBytes*100/totalBytes);
    }

    @Override
    protected void error(BaseDownloadTask task, Throwable e) {
        super.error(task,e);
        if(mListener!=null)
        mListener.onError(e);
    }

用的是 compile 'com.liulishuo.filedownloader:library:1.0.0'版本

**Comment by panjichang** [comment]
D/logkc: 当前下载进度:80
01-19 16:56:27.017 30619-30619/com.viapalm.kidcares D/logkc: 当前下载进度:81
01-19 16:56:27.207 30619-30619/com.viapalm.kidcares D/logkc: 当前下载进度:82
01-19 16:56:27.375 30619-30619/com.viapalm.kidcares D/logkc: 当前下载进度:83
01-19 16:56:27.575 30619-30619/com.viapalm.kidcares D/logkc: 当前下载进度:84
01-19 16:56:27.745 30619-30619/com.viapalm.kidcares D/logkc: 当前下载进度:85
01-19 16:56:27.783 30619-30619/com.viapalm.kidcares D/logkc: 当前下载进度:85
01-19 16:56:27.791 30619-30619/com.viapalm.kidcares D/logkc: 当前下载进度:85
01-19 16:56:27.797 30619-30619/com.viapalm.kidcares D/logkc: 当前下载进度:85
01-19 16:56:27.815 30619-30619/com.viapalm.kidcares D/logkc: 当前下载进度:85
01-19 16:56:27.949 30619-30619/com.viapalm.kidcares D/logkc: 当前下载进度:86
01-19 16:56:28.138 30619-30619/com.viapalm.kidcares D/logkc: 当前下载进度:-86

**Comment by rantianhua** [comment]
请更新到最新的 1.6.9 版本试试

**Comment by panjichang** [comment]
更新到1.6.9试过了，也是存在这个问题！  小于20兆的下载没什么问题，我测试了几百兆的！ 都会出现这个问题

**Comment by JsonZhangCZ** [comment]
这个问题是int最大值是21亿多，然而超过20兆回调的进度就超过21亿了，所以进度的中int就越界了。导致数据进度到80后就错乱了，你需要用large那个监听器FileDownloadLargeFileListener 。这样就好了！

**Comment by rantianhua** [comment]
@JsonZhangCZ 20M 是 20971520 B，怎么会使 int 越界呢？当下载文件大小超过 2G 的时候才是你所描述的问题，这个在 `FileDownloadLargeFileListener` 的注释已经有说明。

---

@panjichang 我试了我们 Demo 中一个下载 45M 的示例都没有出现你所所的情况，所以想看下具体你打日志的代码。

**Comment by LuckyStar521** [comment]
soFarBytes*100/totalBytes，这么计算是有问题的，soFarBytes*100已经超过int类型最大值，越界导致数值变成负数了，改成soFarBytes / totalBytes * 100 就好了

**Comment by rantianhua** [comment]
所以是自己使用时计算错误。
