### ISSUE TITLE
APP HOME 至后台，偶现pause的问题

### ISSUE THREAD

**Issue by Pluckypan** [lingochamp/FileDownloader#923]
仍然是使用 1.6.8的版本，非单机问题，下载过程中，切换至系统桌面，偶尔出现下载任务被暂停的情况，查看日志 在回调的状态为 `paused`. 

业务代码中，有一个全局下载监听，然后再将下载信息 分发至各个需要的界面(比如 `Fragment` 中: 在 `onCreateView` 中 `register` 在 `onDestoryView`  中  `unregister`)，没有任何调用 `pause`  `stop` 的地方。

上一次解决 [issues-912](https://github.com/lingochamp/FileDownloader/issues/912) 时本来想升级到 最新版本 **1.6.9** ，发现升级完也出现 偶尔切后台被pause掉的问题，所以最后决定先不升级，暂时使用 `tag v1.6.8` 版本修复 [issues-912](https://github.com/lingochamp/FileDownloader/issues/912)  。

@Jacksgong [issues-912](https://github.com/lingochamp/FileDownloader/issues/912) 应该也是存在被 `paused` 的问题的。请问这个 `puase` 是怎么产生的，有哪些可能。没有附上日志，但是确实是存在这个问题。

**Comment by rantianhua** [comment]
@Pluckypan 还是希望提供 FileDownloader 的详细日志，还有就是有没有通过 `FileDownloader#addServiceConnectListener(final FileDownloadConnectListener listener) ` 方法添加过任何的 FileDownloadConnectListener ，如果有的话，内部实现是怎样？

**Comment by Pluckypan** [comment]
@rantianhua 周一再给你提供 **复现日志**。暂时没有添加过 `FileDownloadConnectListener`

**Comment by Pluckypan** [comment]
[filedownloader-error.txt](https://github.com/lingochamp/FileDownloader/files/1681659/filedownloader-error.txt)

**Comment by Pluckypan** [comment]
@rantianhua  问题找到了 ，同事有个操作，在内存比较低的情况下 （TRIM_MEMORY_BACKGROUND ，TRIM_MEMORY_MODERATE ，TRIM_MEMORY_COMPLETE）或者 （TRIM_MEMORY_RUNNING_CRITICAL、TRIM_MEMORY_RUNNING_LOW、TRIM_MEMORY_RUNNING_MODERATE） 的时候 ` FileDownloader.getImpl().clearAllTaskData();` 暂停了所有任务，以前没排除到，今天看到日志 `onTrimMemory level=80` 才发现。问题我关闭了。

**Comment by rantianhua** [comment]
好的，我刚看日志也正准备回复你的。
