### ISSUE TITLE
416 range越界并不停重试

### ISSUE THREAD

**Issue by jiangyanlily** [lingochamp/FileDownloader#929]
Hi 作者好：

我们在使用1.5.6版本，遇到了416越界并不停重试的问题，不确定是否最新版本也有这个问题，我下载了最新版本的代码，阅读代码有一处不解，想和作者求证一下自己的猜想
表象：服务器log很多都越界一个byte，但不停重试
 类似这样GET xxx.mp3 HTTP/1.1" # bytes=14727382- # http # 0.106 # 416 # 由于本地没法复现，所以只能阅读代码看这个问题，其中有一处怀疑会导致不停重试，疑点如下：
DownloadLaunchRunnable中，handleFirstConnected里面
if (code == HTTP_REQUESTED_RANGE_NOT_SATISFIABLE) {会把isPreconditionFailed 设置为true，最后可能会抛出throw new RetryDirectly(); 这个异常被捕获后会直接重试，但不会对retry次数减一，这点是否会导致不停循环重试？

**Comment by rantianhua** [comment]
抱歉现在才回复，之前一直在处理其他问题。

当因为 416 问题把 isPreconditionFailed 设置为 true 时，会重置下载进度，重试的时候，如果有 range 参数的话，那么 range 参数为 0- 。所以正常来说，不会因为这一点导致不停重试。

当然，触发 `RetryDirectly()` 异常的不止 416，还有可能是 412 、etag 变化、在 range 的初始值不为 0 的情况下返回 201 。所以你可以根据服务器的 log 进一步排查下。

**Comment by rantianhua** [comment]
刚才看的时候忘记你说的是 1.5.6 版本，在 1.5.6 版本里，处理 416 问题的方法不是 `handleFirstConnected` ，而是：
```
 @Override
    public boolean isRetry(Exception exception) {
        if (exception instanceof FileDownloadHttpException) {
            final FileDownloadHttpException httpException = (FileDownloadHttpException) exception;

            final int code = httpException.getCode();

            if (isSingleConnection && code == HTTP_REQUESTED_RANGE_NOT_SATISFIABLE) {
                if (!isTriedFixRangeNotSatisfiable) {
                    FileDownloadUtils.deleteTaskFiles(model.getTargetFilePath(), model.getTempFilePath());
                    isTriedFixRangeNotSatisfiable = true;
                    return true;
                }
            }
        }

        return validRetryTimes > 0 && !(exception instanceof FileDownloadGiveUpRetryException);
    }
```

可以看到这里在判断是否可以重试时，如果是单连接且出现 416 的话，重试次数就无效了。所以这里应该就是出现你遇到无限重试的原因。根据最新版本的代码，新版本是没有这个问题的，建议升级到新版本。

**Comment by rantianhua** [comment]
你说的服务器越界一个 byte ，这个问题好像和 #737 出现的问题很像，即最后一块儿 range 越界。你可以进一步根据服务器的日志确认下是不是都是最后一个 byte 越界了。#737 中的 bug 在 1.6.4 版本中已经修复。

**Comment by jiangyanlily** [comment]
谢谢，我这里观察到的特征的确是最后一个byte越界，我已经升级到1.6.9，进一步观察问题是否重现，我看到最新的代码应该是没有这样的问题了
