### ISSUE TITLE
新Bug

### ISSUE THREAD

**Issue by ynlh** [lingochamp/FileDownloader#93]
依然是主动kill主应用，FileDownloader的service依然存在，这时候发现，重新打开应用，新建下载，会回调 pending，但却不会回调 connected，progress 的回调已经修复了。
通过手机上的任务管理器 kill 该应用（会kill service），重新打开应用，会回调 connected。

**Comment by Jacksgong** [comment]
> 0.2.2的版本我对这块进行了优化，这边提到的都是根据最新代码的情况。

首先，在 Download-Process 与 Main-Process 都被杀了，这种情况如你所说是没有问题的。

聊聊你提到有问题的这个情况，那就是 Download-Process 还存活，但是 Main-Process 被杀了，重新启动相同任务。 这里出现你说的 `connected` 不会回调的问题，其实这是个权衡点:

这个是目前设计如此的，其实认真想一下你就会明白了，此时虽然你重新启动了你的任务，但是你的任务已经在 Download-Process 上运行了，因此这个时候，FileDownloader的安检机制，在遇到这种Case的情况下，就将你新启动的任务绑定上了在Download-Process上已经运行着的相同任务，这个时候有三种情况:

1. 在重新启动下载的时候，已经下载完成   --- 直接回调 `Completed`
2. 在重新启动下载的时候，在 Download-Process 上运行的相同任务还在 Pending中 --- 会回调 `Pending` 并且接下来的各种回调都会符合预期。
3. 在重新启动下载的时候，在 Download-Process 上运行的相同任务正在下载 ---  会回调 `Pending` 告知入队成功，但是由于正在下载，如果任务已经 `Connected`，将不会再收到 `Connected`回调，如果刚好过了最后一次的 `Process` 也不会有 `Process` 回调。

**Comment by Jacksgong** [comment]
👍  你确实观察十分认真，不过这个确实是一个权衡点，已经过了那个回调了，此时如果是做一个fake的回调，会违背 回调接口 原本的含义，会引起误会。

因此，这一层如果 业务层面需要保证这个回调生命周期，我想这个时候业务层自己去fake应该会更灵活些。

**Comment by ynlh** [comment]
好的，明白你的设计初衷了，之前主要是想计算下载速度，放在了 connected  里面初始化一些数值，所以中断时出乎了预期，但是现在看起来放在 Pending 中，应该也一样。感谢作者解答，棒棒哒！

**Comment by Jacksgong** [comment]
:)
