### ISSUE TITLE
任务管理器需求

### ISSUE THREAD

**Issue by fgq233** [lingochamp/FileDownloader#930]
谢谢作者的开源，现在有个任务管理器的需求，在A页面有一个列表可以下载，可以添加下载任务，在B页面可以回显这些下载任务的进度，看了[#4](https://github.com/lingochamp/FileDownloader/issues/4#issuecomment-168692266)，[#103](https://github.com/lingochamp/FileDownloader/issues/103)，[#165](https://github.com/lingochamp/FileDownloader/issues/165) 
但还是不太明白如何在进入B页面后更新下载进度，写了一个小Demo，希望作者可以指点一下，十分感谢
[这是Demo的地址](https://github.com/fgq233/demo)

**Comment by didikeeLunaon** [comment]
我建议提供查询任务的api，仅供查询即可，方便用户什么都不需要处理就可以实现一个简单的任务管理器。我看 OK-Go这个库的拓展库 Ok-Download 提供的api就比较好，查询的都开放，随便使用者怎么用，提供可用性。性比较而言，这个库所提供的API全部围绕着下载。这样做是很好，但实际用来却不是很方便，处处被约束的感觉。个人感觉而已。

**Comment by rantianhua** [comment]
@fgq233 其实 #4 里面的示例代码已经很清晰了。如果你想让大家帮你查看 demo 的话，建议你提供一个 Demo 的 Github 地址，而不是一个百度云链接，因为去下载、解压、用 AS 打开是一个很繁琐的过程，而且这其中每一步都可能遇到麻烦，这样十分不高效。

**Comment by rantianhua** [comment]
@didikeeLunaon FileDownloader 本身已经提供了很多灵活的 api ，比如针对查询任务相关的，可以参考[这里](https://github.com/lingochamp/FileDownloader/wiki/BaseDownloadTask)。

如果你感觉哪些 api 不够友好或者缺乏哪些 api ，欢迎提出。另外可以你也可以关注下我们新的下载[工具](https://github.com/lingochamp/okdownload)，相比于 FileDownloader ，它更关注稳定性和轻量化以及灵活性。

**Comment by fgq233** [comment]
@rantianhua Demo已经传到GitHup了，配合GreenDao做了一个任务管理器样式，进度更新页页做出来了，不知道对不对

**Comment by rantianhua** [comment]
@fgq233 代码我已经看了，你的实现是可以的。
