### ISSUE TITLE
回调过于频繁问题

### ISSUE THREAD

**Issue by 425540302** [lingochamp/FileDownloader#932]
#### Before Issue

为了实现下载管理，我自己维护了一张任务实体表，在每次回调的时候，我得去更新数据库数据，在回调下载的进度的时候过于频繁，导致性能不好，这个回调要怎么控制1秒回调一次，现在的回调是这样的，下载大文件的时候回调比较慢，下载小文件的时候，回调反而特别快，要怎么设置成一样的时间点回调一次

**Comment by rantianhua** [comment]
__怎么控制回调时间间隔？__

---  


默认的回调时间间隔是5毫秒，你可以通过 `BaseDownloadTask#setCallbackProgressMinInterval(int)` 进行设置。

__为什么大文件回调慢，小文件回调快?__

---

进度回调不光有时间间隔控制，还有回调次数的限制，默认次数是 100 ，所以同等次数下，大文件回调的比小文件慢。你可以通过 `BaseDownloadTask#setCallbackProgressTimes(int)` 设置。

__怎么设置成一样的回调次数？__

---

progress 的回调由回调时间间隔和回调次数共同控制，所以一半情况下就算设置了 1 秒回调一次，但这是最小回调时间间隔，所以实际中并不会说完全就是一秒回调一次。但如果你非要这个效果的话，那么讲回调次数设置地很大，比如 Integer.MAX_VALUE，那么这个相当于忽略了回调次数的影响，回调主要由时间间隔控制。

**Comment by 425540302** [comment]
BaseDownloadTask#setCallbackProgressMinInterval(int)这个要在哪里设置，我在pendding里面设置无效

**Comment by rantianhua** [comment]
要在创建 task 的时候设置，在任何 FileDownloadListener 里设置是无效的，因为任务已经构造完毕。
