### ISSUE TITLE
进程关闭时如何停止任务

### ISSUE THREAD

**Issue by 425540302** [lingochamp/FileDownloader#934]
#### Before Issue

任务在下载时，手动把app的进程关闭，关闭后，任务还在一直下载，停不下来，进程关闭时如何停止任务

**Comment by rantianhua** [comment]
正常情况下，如果主进程被杀了，那么 filedownloader 进程也就挂了，那么所有的下载也都终止了。所以 *进程关闭时如何停止任务？* 这实际上是一个不存在的问题。

在你描述里，手动把 APP 进程关闭后，FileDownloader 依然在继续下载当前任务。我理解的 “手动把 App 进程关闭” 是在手机的任务管理器中将你所指定的 App 移除，这样所有和 app 相关的进程，包括 app 主进程都被 kill 掉了，那么就像我第一段所说，不可能 FileDownloader 还在下载。所以，你所指的手动把 app 进程关闭是我所理解的那样吗？

FileDownloader 如果是因为进程挂掉而停止了当前任务，那么尽管进程再次启动，也不会自动去开启下载任务，所以按照你的描述，很难理解进程关闭后任务一直在下载这一现象，除非进程并没有被杀掉。所以还是希望确认一下进程是否真的被杀掉。

**Comment by techGay** [comment]
这个问题似乎我也遇到过，我想应该是没有设置服务方式引起的，认真看文档：

FileDownloadService 默认是运行在独立进程':filedownloader'上的, 如果你想要FileDownloadService共享并运行在主进程上, 将该关键字参数设置为true，可以有效减少IPC产生的I/O，通过配置assets里配置文件即可

亦或者手动退出程序的时候主动调用pauseAll吧
