### ISSUE TITLE
大文件Progress回调慢，

### ISSUE THREAD

**Issue by 425540302** [lingochamp/FileDownloader#937]
#### Before Issue
我在回调pending的时候，去设置这个任务的Progress回调回调次数和回调间隔都没效果，文件1.5G的回调要几十秒，不知道要怎么弄才能正常

**Comment by rantianhua** [comment]
无效的问题已经在 #938 回复了，是你使用上的问题。

关于回调慢的问题，我已经在 #932 仔细向你解释了回调是有哪些参数控制，也向你解释了为什么有时候回调慢，有时候回调快，同时也描述了哪些方法可以让你自己控制回调，请再自己理解下 #932 的回复。

这是我们的 [Wiki](https://github.com/lingochamp/FileDownloader/wiki) ，里面有 Api 的详细介绍，也有一些常见问题的概述，你可以在这里了解到更多。

也可以通过 Demo 快速了解如何使用 FileDownloader ，所以推荐下载我们的工程然后编译运行我们的 Demo ，这样能了解得更快。
