### ISSUE TITLE
Task is still downloading when the file has already deleted on the Android version below or equal to 4.1.1

### ISSUE THREAD

**Issue by ynlh** [lingochamp/FileDownloader#94]
额，很奇葩的测试，我开启一个下载，这时候下载已经进行了一段时间，主动去文件管理器中删除了这个文件，测试发现：下载依然正常进行，不报任何错误，一直等到下载完成，也正常回调到 completed 。但是这个文件确实是不存在了的。这种情况是否是正常的呢？还是说交给业务层自己处理？最后发现文件没了再重新下载？

**Comment by Jacksgong** [comment]
目前内部用的是 `java.io.RandomAccessFile` 进行写文件，其实之前我就有去cover这个点，我在 Android 4.4.4及以上版本的手机上测试过，写文件过程中，删除该文件会直接抛 `fstat failed enoent (no such file or directory) `  不过我在 Android 4.1.1及以下手机测试，都不会抛任何异常，就像你说的，我也再思考这个点。

**Comment by ynlh** [comment]
那确实很蛋疼啊，目前看来只能业务层自己处理这种极端情况了。不过是否可以 FileDownloader 在写文件的时候主动检测这个文件是否存在，不存在就主动抛出异常呢？

**Comment by weikano** [comment]
笨办法可以用FileObserver监控文件改变，但是总感觉这样不太合适

**Comment by Jacksgong** [comment]
@weikano 这样性能不好，因为我们本身也是对文件不断的修改。

**Comment by xanaduo** [comment]
没找到取消正在下载的方法啊，我想取消下载。

**Comment by Jacksgong** [comment]
Any suggestion about this issue is very welcome.

**Comment by rantianhua** [comment]
在一个系统为 4.2 的华为手机上测试：连续执行一万次 `file.exists()` 耗时差不多在 500 毫秒左右。即这个开销是很小的，可以考虑在写文件之前执行检查文件是否存在的操作。不过在 FileDownloader 里面不考虑处理这个 case 了，会在 [okdownload](https://github.com/lingochamp/okdownload) 进行覆盖。
