### ISSUE TITLE
FileDownloadHttpException: response code error: 405

### ISSUE THREAD

**Issue by ZABone** [lingochamp/FileDownloader#942]
### 我在做apk下载的时候遇到了405错误，然后根据提示确实是ResponseHeader没有文件的大小，随后根据提示在filedownloader.properties 的文件中配置http.lenient=true来忽略这个错误，但是依然没有得到解决。此外在之前使用的时候1.6.8是可以下载的不存在这个情况。我下载的链接是：http://open.game.163.com/web-download-apk/?gameId=ga8a49e80f5fed7546015ffca86c88009b
> 02-03 22:58:08.312 10213-10213/com.wangxia.battleroyale W/System.err: com.liulishuo.filedownloader.exception.FileDownloadHttpException: response code error: 405, 
02-03 22:58:08.312 10213-10213/com.wangxia.battleroyale W/System.err:  request headers: {Range=[bytes=0-0], User-Agent=[FileDownloader/1.7.0]} 
02-03 22:58:08.312 10213-10213/com.wangxia.battleroyale W/System.err:  response headers: {null=[HTTP/1.1 405 Method Not Allowed], Allow=[GET], Connection=[keep-alive], Content-Language=[en], Content-Length=[1047], Content-Type=[text/html;charset=utf-8], Date=[Sun, 04 Feb 2018 03:58:08 GMT], Server=[nginx], Set-Cookie=[JVM_ROUTE=610c93cae28f6afa99f7255a9f95e88f743151759023efd58c33a05d7b0444940f30288d450d4a643c2e604cfc7f18d0; Domain=game.yixin.im; Expires=Fri, 22-Feb-2086 07:12:15 GMT; Path=/, JVM_ROUTE=610c93cae28f6afa99f7255a9f95e88f743151759023efd58c33a05d7b0444940f30288d450d4a643c2e604cfc7f18d0; Domain=open.yixin.im; Expires=Fri, 22-Feb-2086 07:12:15 GMT; Path=/], X-Android-Received-Millis=[1517716688291], X-Android-Response-Source=[NETWORK 405], X-Android-Sent-Millis=[1517716688245]}
02-03 22:58:08.312 10213-10213/com.wangxia.battleroyale W/System.err:     at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.handleTrialConnectResult(DownloadLaunchRunnable.java:552)
02-03 22:58:08.312 10213-10213/com.wangxia.battleroyale W/System.err:     at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.trialConnect(DownloadLaunchRunnable.java:374)
02-03 22:58:08.312 10213-10213/com.wangxia.battleroyale W/System.err:     at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.run(DownloadLaunchRunnable.java:253)
02-03 22:58:08.312 10213-10213/com.wangxia.battleroyale W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-03 22:58:08.312 10213-10213/com.wangxia.battleroyale W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-03 22:58:08.312 10213-10213/com.wangxia.battleroyale W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by Jacksgong** [comment]
这个是由于在1.7.0版本的首个试探请求采用`HEAD`方法请求，而后端没有支持导致的，这个问题，我们会在1.7.1版本修复。
