### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by BinarySatan** [lingochamp/FileDownloader#945]
我看了 #473 ，不太明白，这个问题到底是服务端，还是客户端的事情（根本问题是什么）。 调用重试的话我这并不试用，而重写File..Connection 来优化TCP 我也不是很会，请问有什么比较简单的解决方法吗？
比如出现这个错误的时候， 我在start开启这个任务？

**Comment by rantianhua** [comment]
@BinarySatan 针对 Connection reset by peer 这个问题，已经在 Wiki#QA 里做了详细的描述，请在 [这里](https://github.com/lingochamp/FileDownloader/wiki/QA#5-connection-reset-by-peer) 查看详情。

**Comment by jueran** [comment]
但是有的android手机存在这个问题，有的手机没有？
