### ISSUE TITLE
How to replace a new URL when the old URL expired ? 

### ISSUE THREAD

**Issue by Jeffin21** [lingochamp/FileDownloader#948]
How could i possibly update the download URL when the download is error ? updating the database

**Comment by rantianhua** [comment]
Is it impossible to open a new task to satisfy your requirement?

**Comment by Jeffin21** [comment]
let me explain , I'm downloading 100mb and  downloaded 50mb that time the URL got expired so need to update the URL to continue the download the rest of the file.

**Comment by cervy** [comment]
四国以

**Comment by rantianhua** [comment]
I get it. This question has been discussed in issue #617 and #687
