### ISSUE TITLE
Data lose when retry 

### ISSUE THREAD

**Issue by Jeffin21** [lingochamp/FileDownloader#949]
using latest downloader version 

02-09 13:41:50.111 18475-20616/com.downloader I/FileDownloader.DownloadStatusCallback: inspectNeedCallbackToUser need callback to user
02-09 13:41:50.111 18475-20615/com.downloader I/FileDownloader.DownloadStatusCallback: handleProgress notify user progress status
02-09 13:41:50.111 18475-20584/com.downloader D/FileDownloader.MessageSnapshotGate: ~~~callback -488320154 old[3] new[3] 1
02-09 13:41:50.111 18475-20584/com.downloader D/FileDownloader.FileDownloadMessenger: notify progress -488320154@com.liulishuo.filedownloader.DownloadTask@b888cee 3515292 466862114
02-09 13:41:50.111 18475-20584/com.downloader D/FileDownloader.MessageSnapshotGate: updateKeepFlow
02-09 13:41:50.121 18475-18475/com.downloader V/SRL: notification show : 3515292=  Speed:7
02-09 13:41:50.121 18475-18475/com.downloader V/SRL: notification soFar : 3515292==3
02-09 13:42:03.121 18475-20616/com.downloader I/FileDownloader.DownloadStatusCallback: inspectNeedCallbackToUser need callback to user
02-09 13:42:03.121 18475-20615/com.downloader I/FileDownloader.DownloadStatusCallback: handleProgress notify user progress status
02-09 13:42:03.121 18475-20584/com.downloader D/FileDownloader.MessageSnapshotGate: ~~~callback -488320154 old[3] new[3] 1
02-09 13:42:03.121 18475-20584/com.downloader D/FileDownloader.FileDownloadMessenger: notify progress -488320154@com.liulishuo.filedownloader.DownloadTask@b888cee 3536112 466862114
02-09 13:42:03.121 18475-20584/com.downloader D/FileDownloader.MessageSnapshotGate: updateKeepFlow
02-09 13:42:03.141 18475-18475/com.downloader V/SRL: notification show : 3536112=  Speed:1
02-09 13:42:03.141 18475-18475/com.downloader V/SRL: notification soFar : 3536112==3
02-09 13:42:12.431 18475-20616/com.downloader I/FileDownloader.DownloadStatusCallback: inspectNeedCallbackToUser need callback to user
02-09 13:42:12.431 18475-20615/com.downloader I/FileDownloader.DownloadStatusCallback: handleProgress notify user progress status
02-09 13:42:12.431 18475-20584/com.downloader D/FileDownloader.MessageSnapshotGate: ~~~callback -488320154 old[3] new[3] 1
02-09 13:42:12.431 18475-20616/com.downloader I/System.out: FileDownloadRandomAccessFile : null==Internal
02-09 13:42:12.431 18475-20584/com.downloader D/FileDownloader.FileDownloadMessenger: notify progress -488320154@com.liulishuo.filedownloader.DownloadTask@b888cee 3556932 466862114
02-09 13:42:12.441 18475-20584/com.downloader D/FileDownloader.MessageSnapshotGate: updateKeepFlow
02-09 13:42:12.451 18475-18475/com.downloader V/SRL: notification show : 3556932=  Speed:2
02-09 13:42:12.451 18475-18475/com.downloader V/SRL: notification soFar : 3556932==3
02-09 13:42:33.651 18475-20620/com.downloader D/FileDownloader.FetchDataTask: require flushAndSync id[-488320154] index[4] offset[373492082], consume[7]
02-09 13:42:33.661 18475-20620/com.downloader D/FileDownloader.ConnectTask: <---- -488320154 request header {Range=[bytes=373489688-], User-Agent=[FileDownloader/1.0.78]}
02-09 13:42:33.671 18475-20977/com.downloader D/FileDownloader.MessageSnapshotGate: ~~~callback -488320154 old[3] new[5] 1
02-09 13:42:33.671 18475-20977/com.downloader D/FileDownloader.FileDownloadMessenger: notify retry -488320154@com.liulishuo.filedownloader.DownloadTask@b888cee 10 5 java.net.SocketTimeoutException
02-09 13:42:33.671 18475-20977/com.downloader D/FileDownloader.MessageSnapshotGate: updateKeepFlow
02-09 13:42:48.241 18475-20618/com.downloader D/FileDownloader.FetchDataTask: require flushAndSync id[-488320154] index[2] offset[187682750], consume[9]
02-09 13:42:48.251 18475-20618/com.downloader D/FileDownloader.ConnectTask: <---- -488320154 request header {Range=[bytes=186744844-280117265], User-Agent=[FileDownloader/1.0.78]}
02-09 13:42:48.261 18475-20977/com.downloader D/FileDownloader.MessageSnapshotGate: ~~~callback -488320154 old[5] new[5] 1
02-09 13:42:48.261 18475-20977/com.downloader D/FileDownloader.FileDownloadMessenger: notify retry -488320154@com.liulishuo.filedownloader.DownloadTask@b888cee 10 6 java.net.SocketTimeoutException: timeout
02-09 13:42:48.261 18475-20977/com.downloader D/FileDownloader.MessageSnapshotGate: updateKeepFlow
02-09 13:42:56.071 18475-18475/com.downloader V/FileDownloader.DownloadTaskHunter: the task[-488320154] has been expired from the launch pool.
02-09 13:42:56.071 18475-18475/com.downloader D/FileDownloader.FileDownloadManager: request pause the task -488320154
02-09 13:42:56.071 18475-18475/com.downloader D/FileDownloader.FileDownloadThreadPool: successful cancel -488320154 FALSE
02-09 13:42:56.071 18475-18475/com.downloader D/FileDownloader.FileDownloadMessenger: notify begin -488320154@com.liulishuo.filedownloader.DownloadTask@b888cee
02-09 13:42:56.071 18475-18475/com.downloader V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@e41101c by -2 
02-09 13:42:56.071 18475-18475/com.downloader V/FileDownloader.FileDownloadList: remove -488320154@com.liulishuo.filedownloader.DownloadTask@b888cee left -2 0
02-09 13:42:56.071 18475-18475/com.downloader D/FileDownloader.FileDownloadMessenger: notify paused -488320154@com.liulishuo.filedownloader.DownloadTask@b888cee
02-09 13:42:56.071 18475-18475/com.downloader V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@e41101c by -2 
02-09 13:42:56.081 18475-18475/com.downloader V/SRL: notification soFar : 3442708==-2
02-09 13:43:02.571 18475-20619/com.downloader D/FileDownloader.FetchDataTask: require flushAndSync id[-488320154] index[3] offset[280708172], consume[13]
02-09 13:43:02.571 18475-20619/com.downloader D/FileDownloader.DownloadLaunchRunnable: the task[-488320154] has already been paused, so pass the retry callback
02-09 13:43:02.591 18475-20617/com.downloader D/FileDownloader.FetchDataTask: require flushAndSync id[-488320154] index[1] offset[94142381], consume[10]
02-09 13:43:02.591 18475-20617/com.downloader D/FileDownloader.DownloadLaunchRunnable: the task[-488320154] has already been paused, so pass the retry callback

**Comment by Jeffin21** [comment]
Please consider this issue. It happens in slow internet connection rolling back the download file

**Comment by Jeffin21** [comment]
waiting for a fix , Thank You

**Comment by Jeffin21** [comment]
any update for this bug? thanks

**Comment by rantianhua** [comment]
Not yet, very busy recently, please be more patient and welcome your pull request.

**Comment by rantianhua** [comment]
I have updated some changes for this issue, you can verify it previously in [here](https://github.com/rantianhua/FileDownloader)
