### ISSUE TITLE
Download Speed

### ISSUE THREAD

**Issue by atulsethi** [lingochamp/FileDownloader#95]
Hi ,
 firstly thanks for this library .. 
Can we find out speed for individual download id with this library if no then how can i do that ?

Thanks

**Comment by Jacksgong** [comment]
Thank you.

No, As a lib,  we just want to use this lib to download files, simply、easily、stability、flexibly.

But, If you want to find out the speed for individual download id, you can do it easily. Just need to maintain the time use for progressing  and with the `FileDownloadListener#progress` call-back you can get how bytes has downloaded so far, so you have the elapsed-time which is maintained by yourself and soFarBytes which call-back by `FileDownlaodListener#progress`, so, just find out. Furthermore, if you want to calculate the speed more exacter, just let the `FileDownloadListener#progress` call-back more frequently with `BaseDownloadTask#setCallbackProgressTimes`.

In addition, if you care about how much time on the connection, in the current master branch or next version, you can find out with: `FileDownloadListener#started` and `FileDownloadListener#connected`.

**Comment by Jacksgong** [comment]
Tips: You can wrap such function in the special Listener extended by `FileDownloadListener`. You can find out `pendingTime`、`connectionTime`、`progressTime`、`totalTime`、`downloadTime` with the call-back method in `FileDownloadListener`. 

And welcome PR. :)

**Comment by Jacksgong** [comment]
Has been supported in [v0.2.4](https://github.com/lingochamp/FileDownloader/releases/tag/v0.2.4).
