### ISSUE TITLE
com.liulishuo.filedownloader.exception.FileDownloadHttpException: response code error: 400, 

### ISSUE THREAD

**Issue by HappinessKing** [lingochamp/FileDownloader#950]
02-09 19:41:54.356 17720-17720/io.zysjh.listener W/System.err:  request headers: {Range=[bytes=0-0], User-Agent=[FileDownloader/1.7.1]} 
02-09 19:41:54.356 17720-17720/io.zysjh.listener W/System.err:  response headers: {null=[HTTP/1.1 400 Bad Request], Connection=[close], Content-Length=[324], Content-Type=[text/html; charset=us-ascii], Date=[Fri, 09 Feb 2018 11:41:55 GMT], Server=[Microsoft-HTTPAPI/2.0], X-Android-Received-Millis=[1518176514201], X-Android-Response-Source=[NETWORK 400], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1518176514166]}
02-09 19:41:54.356 17720-17720/io.zysjh.listener W/System.err:     at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.handleTrialConnectResult(DownloadLaunchRunnable.java:552)
02-09 19:41:54.356 17720-17720/io.zysjh.listener W/System.err:     at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.trialConnect(DownloadLaunchRunnable.java:374)
02-09 19:41:54.356 17720-17720/io.zysjh.listener W/System.err:     at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.run(DownloadLaunchRunnable.java:253)
02-09 19:41:54.356 17720-17720/io.zysjh.listener W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
02-09 19:41:54.356 17720-17720/io.zysjh.listener W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
02-09 19:41:54.356 17720-17720/io.zysjh.listener W/System.err:     at java.lang.Thread.run(Thread.java:833)
02-09 19:41:54.364 17720-18277/io.zysjh.listener I/System: core_booster, getBoosterConfig = false

有点手机下载不报错，有的手机会报错，报400错误，不知道怎么解决，

**Comment by rantianhua** [comment]
400 错误一般是请求参数非法造成的，所以你可以先和后端沟通下为什么这里出现了 400 ，是哪个参数非法了?

**Comment by rantianhua** [comment]
长时间未回复，先关掉了。
