### ISSUE TITLE
connectionCountAdapter 分片控制无效

### ISSUE THREAD

**Issue by dilongl** [lingochamp/FileDownloader#952]
FileDownloader.setupOnApplicationOnCreate(this)
                .connectionCountAdapter(new FileDownloadHelper.ConnectionCountAdapter() {
                    @Override
                    public int determineConnectionCount(int downloadId, String url, String path, long totalLength) {
                        return 1;
                    }
                })
                .commit();

无效

**Comment by rantianhua** [comment]
1. 请问具体什么表现让你认为无效？
2. 请问你提供的这段代码具体在哪里调用的？

**Comment by dilongl** [comment]
1.determineConnectionCount 里面 return 1； 还是进行分块获取了，我在服务器端看到range获取数据了
2.application的oncreate 调用

**Comment by rantianhua** [comment]
> 在服务端看到 range 获取数据了

这个描述依然不足以说明问题，如果是只有一个 connection ，那么 range 将会是 bytes=start- 其中 start 为断点处的偏移量，比如第一次下载的话，start 为 0 ；下载到 1000 后停止，下次重新开启同一个下载任务，那么从断点处开始，此时 start 就为 1000 。

---


在 onCreate 调用你提供的代码是正确的。

---

还有一种情况是：一开始你没有自定义 ConnectionCountAdapter ，并且开启了下载任务，没有下载完成的时候停止了，接下来你自定义了 ConnectionCountAdapter ，然后覆盖安装，开启了同一个下载任务，那么此时下载 ConnectionCountAdapter 不会起作用，因为数据库里已经保存了上次下载的 connection count
 并重用上次的配置。这种情况下，在下载前你需要调用 `FileDownloader#clear(int, String)` 清除数据库相关信息。

不过最好能提供 FileDownloader 的日志，这样能清楚地分析问题。

**Comment by superxlcr** [comment]
我这边也遇到了相同的问题，在application的onCreate中设置了自定义的组件，但是发现并没有效果
打印日志发现，并没有加载自定义组件的日志“initial FileDownloader manager with  the customize xxx”出现，后来在debug的时候偶然关闭了在另一进程下载的参数（设置process.non-separate=true），就解决了问题：自定义组件的log出现了，抓包工具也看到了正确的连接数
不过奇怪的是在demo里进行测试却不能复现这种情况

**Comment by rantianhua** [comment]
需要说明的一点是，当开启一个新的下载时，下载之前会检查数据库是否有可复用的数据，如果有， 那么会使用之前的相关配置，这其中就包括连接数。根据上面的描述，推测很可能是因为在自定义 `ConnectionCountAdapter` 后，开启的是一个之前一个已经开启的任务，所以复用了之前的配置。

要排除是上面的原因也很简单，在自定义 `ConnectionCountAdapter ` 之后，开启一个新的之前没有下载过的任务。观察连接数是否按照自定义的即可。

**Comment by rantianhua** [comment]
长时间没有回复，先关掉了。
