### ISSUE TITLE
Download Failed WIth Exception 

### ISSUE THREAD

**Issue by creativelabsofficial** [lingochamp/FileDownloader#954]
I try to download file from "usercloud" which does not support multi connection.
downloads always failed with Error message
`Connection failed with request[{range=[bytes=309258675-618517349], user-agent=[FileDownloader/1.6.9]}] response[{connection=[keep-alive], content-disposition=[attachment], content-length=[383], content-type=[text/html], date=[Sun, 18 Feb 2018 19:09:43 GMT], etag=["55ae9d59-17f"], server=[nginx]}] http-state[503] on task[-669991391-1], which is changed after verify connection, so please try again.`

Please Help ??

**Comment by rantianhua** [comment]
The http status code is 503, so it's a server error.

---

The number of connections can be configured, you can refer to [here](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties).
