### ISSUE TITLE
Change url inside retry

### ISSUE THREAD

**Issue by SaeedRe** [lingochamp/FileDownloader#955]
Is it possible to change the download url of the task inside the retry callback ?
Lets say we have an alternative server which we want to download the file from it in case of an error.

**Comment by rantianhua** [comment]
Yes, It's possible to do that. You can refer to #431. I close this issue, and if #431 cannot solve your problem, you can reopen this issue and tell me why.

**Comment by SaeedRe** [comment]
Unfortunately It didn't help, because my scenario was different.
I have a queue set with about 600 tasks, and I'm sure some tasks will fail during the download process because my download server is not able to handle that much request.
Therefore I want to use my Website server to download the **failed tasks** from it, so I was wondering if is it possible to change the task's url in the retry callback so it can be downloaded from another server without starting the task from beginning.
I currently found a way to deal with this issue by creating a list from failed tasks and downloading them again, but a more cleaner way such as only changing the url would be better.

I figure out that the url of a task is set at the beginning and can not be changed during the download process, am I right ?

**Comment by rantianhua** [comment]
Yes, you are right. But if you custom your own IDGenerator, a new task with different url will download from the beginning of the breakpoint as long as two tasks have the same id.

发自我的 iPhone
