### ISSUE TITLE
it can't takes a snapshot for the task

### ISSUE THREAD

**Issue by suzfsir** [lingochamp/FileDownloader#957]
du: 4.4.2_vivo X5L
token: cf0d99f0f0de1281d4d423c6e5cdf2e5
full-content: [gid]=22; [errorUrl]=https://miscimg01.jiaoliuqu.com//chunbaihuajia1516677860.zip; [filePath]=/storage/sdcard0/xingjiabi/live/AiyaEffect; [exception]=it can't takes a snapshot for the task(id[-1383423261], url[https://miscimg01.jiaoliuqu.com//chunbaihuajia1516677860.zip], path[/storage/sdcard0/xingjiabi/live/AiyaEffect/chunbaihuajia.zip], status[-3], sofar[3723903], total[3723903], etag[&quot;FlJEm7KLjKdvFXQMrbXBMSNlWqc6&quot;], com.liulishuo.filedownloader.model.FileDownloadModel@42536320) when its status is -3, [com.liulishuo.filedownloader.message.d.a(SourceFile:189), com.liulishuo.filedownloader.download.d.a(SourceFile:487), com.liulishuo.filedownloader.download.d.i(SourceFile:384), com.liulishuo.filedownloader.download.d.g(SourceFile:197), com.liulishuo.filedownloader.download.DownloadLaunchRunnable.run(SourceFile:363), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)]; [freeSpace]=7133921280; [totalMemSpace]=3169599488; [freeMemSpace]=863551488; [totalSdSpace]=10118307840; [freeSdSpace]=7133921280

这个是什么问题，不明白

**Comment by rantianhua** [comment]
请问你使用的 FileDownloader 版本？

**Comment by suzfsir** [comment]
@rantianhua  compile 'com.liulishuo.filedownloader:library:1.6.9'

**Comment by rantianhua** [comment]
@suzfsir 错误抛出的地方位于：
https://github.com/lingochamp/FileDownloader/blob/09cce328030df1331d3eed32eca1b2243708cf3e/library/src/main/java/com/liulishuo/filedownloader/message/MessageSnapshotTaker.java#L102-L203

在你的错误信息中，是在获取 complete 的 message 时抛出了异常（status = -3），不过这从原有代码角度看是不可能的，因为 `FileDownloadStatus.complete` 是在 switch 块儿里面的。所以请问是否对源代码做过修改？

**Comment by suzfsir** [comment]
没有，直接使用的

**Comment by rantianhua** [comment]
没有找到可能得原因，而且这个应该是个极其特殊的 case ，先关掉了。如果日后你又复现的话，请务必提供 FileDownloader 的完整日志。
