### ISSUE TITLE
文件下载完后不进入Completed, 还是temp文件. 

### ISSUE THREAD

**Issue by espring** [lingochamp/FileDownloader#959]
使用的版本: com.liulishuo.filedownloader:library:1.6.9
已经打开了debug log  : FileDownloadLog.NEED_LOG=true;

串行下载一批文件(8个), 最大的140M的mp4文件. 
        new FileDownloadQueueSet(serialTarget)
                .setCallbackProgressTimes(1)
                .setAutoRetryTimes(6)
                .downloadSequentially(taskList)
                .start();

有20%概率会有一个mp4文件一直无法完成下载,  查看后文件size已经是目标文件的大小, 但还是temp形式的文件. 

log如下:

D/FileDownloader.SerialHandlerCallback: start next com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096 1
V/FileDownloader.DownloadTaskHunter: call start Url[http://xxx.com/group1/M00/00/2F/wKgBA1pqpryASTl-AN3jWeRgPLU912.mp4], Path[/storage/emulated/0/XinFa/download/wKgBA1pqpryASTl-AN3jWeRgPLU912.mp4] Listener[com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096], Tag[2]
V/FileDownloader.DownloadTaskHunter: the task[-1634755956] has been into the launch pool.
D/FileDownloader.FileDownloadMessenger: notify begin -1634755956@com.liulishuo.filedownloader.DownloadTask@88c7004
V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@f6de234 by 11 
D/FileDownloader.MessageSnapshotGate: ~~~callback -1634755956 old[5] new[-4] 2
D/FileDownloader.DownloadTaskHunter: can't update mStatus change by keep flow, 5, but the current mStatus is 5, -1634755956
D/FileDownloader.FileDownloadMessenger: notify warn -1634755956@com.liulishuo.filedownloader.DownloadTask@88c7004
V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@f6de234 by -4 
D/FileDownloader.SerialHandlerCallback: start next com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096 2
V/FileDownloader.DownloadTaskHunter: call start Url[http://xxx.com/group1/M00/00/32/wKgBA1qcpE-Abn4HAMS0WxheBrQ969.mp4], Path[/storage/emulated/0/XinFa/download/wKgBA1qcpE-Abn4HAMS0WxheBrQ969.mp4] Listener[com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096], Tag[3]
V/FileDownloader.DownloadTaskHunter: the task[139022803] has been into the launch pool.
D/XINFA: FileDownloadListener Finished downloading http://xxxx.com/group1/M00/00/2D/wKgBo1qACzCAGXFFAAAGe5h1_aI469.jpg
D/XINFADIAGNOSIS: 	......文件下载完成( wKgBo1qACzCAGXFFAAAGe5h1_aI469.jpg) (tag:1)
D/XINFA: Program downloading process (14678) : 8 : 1 : 12
D/FileDownloader.FileDownloadMessenger: notify begin 139022803@com.liulishuo.filedownloader.DownloadTask@50519ed
V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@5679d2a by 11 
D/FileDownloader.MessageSnapshotGate: ~~~callback 139022803 old[11] new[-3] 1
D/FileDownloader.FileDownloadMessenger: notify block completed 139022803@com.liulishuo.filedownloader.DownloadTask@50519ed FileDownloader-LauncherTask12
D/XINFA: FileDownloadListener.blockComplete 
D/FileDownloader.FileDownloadMessenger: notify completed 139022803@com.liulishuo.filedownloader.DownloadTask@50519ed
V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@5679d2a by -3 

-----------
看log里, 有这样一句和其他不同:
can't update mStatus change by keep flow, 5, but the current mStatus is 5, -1634755956

**Comment by espring** [comment]
另外, filedownloader是跑在一个独立线程中, 这样做有没有问题?

**Comment by rantianhua** [comment]
> filedownloader是跑在一个独立线程中

这句请再描述清楚一点，因为默认 FileDownloader 运行在一个独立的进程，所以你所说的运行在一个独立的线程是什么意思？是指启动 task 的时候吗？

mp4 文件下载时出现了 warn ，这通常是因为启动的任务已经在正在下载的任务里了，不过因为提供的日志不全，所以这里看不到更多的信息，所以请提供完整的 FileDownloader 日志。

**Comment by espring** [comment]
filedownloader是跑在一个独立线程中
: 是指启动task的调用是在一个独立线程中的, 我是在主程序里开的工作线程, 这样做有没有问题?


完整日志, 我现在已经没有了, 当时看过日志, 其他地方没有问题, 和这一段的差别, 就是上面提到那一句: 
can't update mStatus change by keep flow, 5, but the current mStatus is 5, -1634755956
: 请问这一句log是什么意思? 是表示出错了?

**Comment by rantianhua** [comment]
>  是指启动task的调用是在一个独立线程中的, 我是在主程序里开的工作线程, 这样做有没有问题?

没有什么问题。

> can't update mStatus change by keep flow, 5, but the current mStatus is 5, -1634755956

这个表示想通知一个 Task 的状态变为重试了，不过在这个状态已经通知过了，所以没必要更新了，这个是正常现象。


---

还是希望能复现然后提供完整日志，从现在你提供的部分日志看，已经回调了 complete 方法，所以看不出问题。

**Comment by espring** [comment]
D/XINFA: Begin downloading program... 
D/XINFADIAGNOSIS: 	...开始下载节目( 14678)
D/FileDownloader.DownloadTask: setPath /storage/emulated/0/XinFa/download/wKgBo1qACzCAGXFFAAAGe5h1_aI469.jpg
D/FileDownloader.DownloadTask: setTag 1
D/XINFADIAGNOSIS: 等待下载:  wKgBo1qACzCAGXFFAAAGe5h1_aI469.jpg (tag:01
D/FileDownloader.DownloadTask: setPath /storage/emulated/0/XinFa/download/wKgBA1pqpryASTl-AN3jWeRgPLU912.mp4
D/FileDownloader.DownloadTask: setTag 2
D/XINFADIAGNOSIS: 等待下载:  wKgBA1pqpryASTl-AN3jWeRgPLU912.mp4 (tag:11
D/FileDownloader.DownloadTask: setPath /storage/emulated/0/XinFa/download/wKgBA1qcpE-Abn4HAMS0WxheBrQ969.mp4
D/FileDownloader.DownloadTask: setTag 3
D/XINFADIAGNOSIS: 等待下载:  wKgBA1qcpE-Abn4HAMS0WxheBrQ969.mp4 (tag:21
D/FileDownloader.DownloadTask: setPath /storage/emulated/0/XinFa/download/wKgBo1qcpQGAMdQWARH4pLsmsUU088.mp4
D/FileDownloader.DownloadTask: setTag 4
D/XINFADIAGNOSIS: 等待下载:  wKgBo1qcpQGAMdQWARH4pLsmsUU088.mp4 (tag:31
D/FileDownloader.DownloadTask: setPath /storage/emulated/0/XinFa/download/wKgBo1qc0vaAMt_yAAc-NqEK3cY331.jpg
D/FileDownloader.DownloadTask: setTag 5
D/XINFADIAGNOSIS: 等待下载:  wKgBo1qc0vaAMt_yAAc-NqEK3cY331.jpg (tag:41
D/FileDownloader.DownloadTask: setPath /storage/emulated/0/XinFa/download/wKgBo1qct0eAJYsEAAiqezQUy6U562.jpg
D/FileDownloader.DownloadTask: setTag 6
D/XINFADIAGNOSIS: 等待下载:  wKgBo1qct0eAJYsEAAiqezQUy6U562.jpg (tag:51
D/FileDownloader.DownloadTask: setPath /storage/emulated/0/XinFa/download/wKgBA1qcpXiATMmkAA0Bputo4V4236.jpg
D/FileDownloader.DownloadTask: setTag 7
D/XINFADIAGNOSIS: 等待下载:  wKgBA1qcpXiATMmkAA0Bputo4V4236.jpg (tag:61
D/FileDownloader.DownloadTask: setPath /storage/emulated/0/XinFa/download/wKgBA1qcpXeAQFSeAAqFIYEs_WM708.jpg
D/FileDownloader.DownloadTask: setTag 8
D/XINFADIAGNOSIS: 等待下载:  wKgBA1qcpXeAQFSeAAqFIYEs_WM708.jpg (tag:71
D/FileDownloader.DownloadTask: setListener com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096
D/FileDownloader.InQueueTaskImpl: add the task[-510333661] to the queue
V/FileDownloader.FileDownloadList: add list in all -510333661@com.liulishuo.filedownloader.DownloadTask@1978417 0 8
D/FileDownloader.DownloadTask: setListener com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096
D/FileDownloader.InQueueTaskImpl: add the task[-1634755956] to the queue
V/FileDownloader.FileDownloadList: add list in all -1634755956@com.liulishuo.filedownloader.DownloadTask@88c7004 0 9
D/FileDownloader.DownloadTask: setListener com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096
D/FileDownloader.InQueueTaskImpl: add the task[139022803] to the queue
V/FileDownloader.FileDownloadList: add list in all 139022803@com.liulishuo.filedownloader.DownloadTask@50519ed 0 10
D/FileDownloader.DownloadTask: setListener com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096
D/FileDownloader.InQueueTaskImpl: add the task[100926082] to the queue
V/FileDownloader.FileDownloadList: add list in all 100926082@com.liulishuo.filedownloader.DownloadTask@b607022 0 11
D/FileDownloader.DownloadTask: setListener com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096
D/FileDownloader.InQueueTaskImpl: add the task[-1399312757] to the queue
V/FileDownloader.FileDownloadList: add list in all -1399312757@com.liulishuo.filedownloader.DownloadTask@6864ab3 0 12
D/FileDownloader.DownloadTask: setListener com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096
D/FileDownloader.InQueueTaskImpl: add the task[-132000858] to the queue
V/FileDownloader.FileDownloadList: add list in all -132000858@com.liulishuo.filedownloader.DownloadTask@b628870 0 13
D/FileDownloader.DownloadTask: setListener com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096
D/FileDownloader.InQueueTaskImpl: add the task[2061180553] to the queue
V/FileDownloader.FileDownloadList: add list in all 2061180553@com.liulishuo.filedownloader.DownloadTask@52667e9 0 14
D/FileDownloader.DownloadTask: setListener com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096
D/FileDownloader.InQueueTaskImpl: add the task[-1419675611] to the queue
V/FileDownloader.FileDownloadList: add list in all -1419675611@com.liulishuo.filedownloader.DownloadTask@c396c6e 0 15
V/FileDownloader.FileDownloader: start list attachKey[244375311] size[8] listener[com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096] isSerial[TRUE]
D/FileDownloader.SerialHandlerCallback: start next com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096 0
V/FileDownloader.DownloadTaskHunter: call start Url[http://xxx.com/group1/M00/00/2D/wKgBo1qACzCAGXFFAAAGe5h1_aI469.jpg], Path[/storage/emulated/0/XinFa/download/wKgBo1qACzCAGXFFAAAGe5h1_aI469.jpg] Listener[com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096], Tag[1]
V/FileDownloader.DownloadTaskHunter: the task[-510333661] has been into the launch pool.
D/FileDownloader.FileDownloadMessenger: notify begin -510333661@com.liulishuo.filedownloader.DownloadTask@1978417
V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@9065d2b by 11 
D/FileDownloader.MessageSnapshotGate: ~~~callback -510333661 old[11] new[-3] 1
D/FileDownloader.FileDownloadMessenger: notify block completed -510333661@com.liulishuo.filedownloader.DownloadTask@1978417 FileDownloader-LauncherTask10
D/XINFA: FileDownloadListener.blockComplete 
D/FileDownloader.FileDownloadMessenger: notify completed -510333661@com.liulishuo.filedownloader.DownloadTask@1978417
V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@9065d2b by -3 
D/FileDownloader.SerialHandlerCallback: start next com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096 1
V/FileDownloader.DownloadTaskHunter: call start Url[http://xxx.com/group1/M00/00/2F/wKgBA1pqpryASTl-AN3jWeRgPLU912.mp4], Path[/storage/emulated/0/XinFa/download/wKgBA1pqpryASTl-AN3jWeRgPLU912.mp4] Listener[com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096], Tag[2]
V/FileDownloader.DownloadTaskHunter: the task[-1634755956] has been into the launch pool.
D/FileDownloader.FileDownloadMessenger: notify begin -1634755956@com.liulishuo.filedownloader.DownloadTask@88c7004
V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@f6de234 by 11 
D/FileDownloader.MessageSnapshotGate: ~~~callback -1634755956 old[5] new[-4] 2
D/FileDownloader.DownloadTaskHunter: can't update mStatus change by keep flow, 5, but the current mStatus is 5, -1634755956
D/FileDownloader.FileDownloadMessenger: notify warn -1634755956@com.liulishuo.filedownloader.DownloadTask@88c7004
V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@f6de234 by -4 
D/FileDownloader.SerialHandlerCallback: start next com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096 2
V/FileDownloader.DownloadTaskHunter: call start Url[http://xxx.com/group1/M00/00/32/wKgBA1qcpE-Abn4HAMS0WxheBrQ969.mp4], Path[/storage/emulated/0/XinFa/download/wKgBA1qcpE-Abn4HAMS0WxheBrQ969.mp4] Listener[com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096], Tag[3]
V/FileDownloader.DownloadTaskHunter: the task[139022803] has been into the launch pool.
D/XINFA: FileDownloadListener Finished downloading http://xxx.com/group1/M00/00/2D/wKgBo1qACzCAGXFFAAAGe5h1_aI469.jpg
D/XINFADIAGNOSIS: 	......文件下载完成( wKgBo1qACzCAGXFFAAAGe5h1_aI469.jpg) (tag:1)
D/XINFA: Program downloading process (14678) : 8 : 1 : 12
D/XINFA: MainHandler received : { when=0 what=204 obj=com.example.scott.zhihuiapplication.command.CommandJournalReport@520eda0 target=com.example.scott.zhihuiapplication.MainHandler planTime=1520305918022 dispatchTime=0 finishTime=0 }
D/FileDownloader.FileDownloadMessenger: notify begin 139022803@com.liulishuo.filedownloader.DownloadTask@50519ed
V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@5679d2a by 11 
D/FileDownloader.MessageSnapshotGate: ~~~callback 139022803 old[11] new[-3] 1
D/FileDownloader.FileDownloadMessenger: notify block completed 139022803@com.liulishuo.filedownloader.DownloadTask@50519ed FileDownloader-LauncherTask12
D/XINFA: FileDownloadListener.blockComplete 
D/FileDownloader.FileDownloadMessenger: notify completed 139022803@com.liulishuo.filedownloader.DownloadTask@50519ed
V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@5679d2a by -3 
E/XINFA: FileDownloadListener.warnwKgBA1pqpryASTl-AN3jWeRgPLU912.mp4
E/XINFADIAGNOSIS: ...异常下载文件wKgBA1pqpryASTl-AN3jWeRgPLU912.mp4
D/FileDownloader.SerialHandlerCallback: start next com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096 3
D/XINFADIAGNOSIS: 	...节目单下载失败( 14665)
E/XINFADIAGNOSIS: 	:下载失败的URL  http://xxx.com/group1/M00/00/2F/wKgBA1pqpryASTl-AN3jWeRgPLU912.mp4
D/XINFADIAGNOSIS: 	...节目单下载失败( 14668)
E/XINFADIAGNOSIS: 	:下载失败的URL  http://xxx.com/group1/M00/00/2F/wKgBA1pqpryASTl-AN3jWeRgPLU912.mp4
D/XINFADIAGNOSIS: 	...节目单下载失败( 14678)
E/XINFADIAGNOSIS: 	:下载失败的URL  http://xxx.com/group1/M00/00/2F/wKgBA1pqpryASTl-AN3jWeRgPLU912.mp4
D/XINFA: MainHandler received : { when=0 what=204 obj=com.example.scott.zhihuiapplication.command.CommandJournalReport@43a61f6 target=com.example.scott.zhihuiapplication.MainHandler planTime=1520305918032 dispatchTime=0 finishTime=0 }
D/XINFA: MainHandler received : { when=-1ms what=204 obj=com.example.scott.zhihuiapplication.command.CommandJournalReport@8d71e93 target=com.example.scott.zhihuiapplication.MainHandler planTime=1520305918032 dispatchTime=0 finishTime=0 }
V/FileDownloader.DownloadTaskHunter: call start Url[http://xxx.com/group1/M00/00/2E/wKgBo1qcpQGAMdQWARH4pLsmsUU088.mp4], Path[/storage/emulated/0/XinFa/download/wKgBo1qcpQGAMdQWARH4pLsmsUU088.mp4] Listener[com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096], Tag[4]
V/FileDownloader.DownloadTaskHunter: the task[100926082] has been into the launch pool.
D/FileDownloader.FileDownloadMessenger: notify begin 100926082@com.liulishuo.filedownloader.DownloadTask@b607022
V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@4f937fc by 11 
D/FileDownloader.MessageSnapshotGate: ~~~callback 100926082 old[11] new[-3] 1
D/FileDownloader.FileDownloadMessenger: notify block completed 100926082@com.liulishuo.filedownloader.DownloadTask@b607022 FileDownloader-LauncherTask10
D/XINFA: MainHandler received : { when=-4ms what=204 obj=com.example.scott.zhihuiapplication.command.CommandJournalReport@661cd0b target=com.example.scott.zhihuiapplication.MainHandler planTime=1520305918032 dispatchTime=0 finishTime=0 }
D/XINFA: FileDownloadListener.blockComplete 
D/FileDownloader.FileDownloadMessenger: notify completed 100926082@com.liulishuo.filedownloader.DownloadTask@b607022
V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@4f937fc by -3 
D/XINFA: FileDownloadListener Finished downloading http://xxx.com/group1/M00/00/32/wKgBA1qcpE-Abn4HAMS0WxheBrQ969.mp4
D/XINFADIAGNOSIS: 	......文件下载完成( wKgBA1qcpE-Abn4HAMS0WxheBrQ969.mp4) (tag:3)
D/FileDownloader.SerialHandlerCallback: start next com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096 4
D/XINFA: Program downloading process (14678) : 8 : 2 : 25
D/XINFA: MainHandler received : { when=0 what=204 obj=com.example.scott.zhihuiapplication.command.CommandJournalReport@8d4d283 target=com.example.scott.zhihuiapplication.MainHandler planTime=1520305918043 dispatchTime=0 finishTime=0 }
V/FileDownloader.DownloadTaskHunter: call start Url[http://xxx.com/group1/M00/00/2E/wKgBo1qc0vaAMt_yAAc-NqEK3cY331.jpg], Path[/storage/emulated/0/XinFa/download/wKgBo1qc0vaAMt_yAAc-NqEK3cY331.jpg] Listener[com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096], Tag[5]
V/FileDownloader.DownloadTaskHunter: the task[-1399312757] has been into the launch pool.
D/FileDownloader.FileDownloadMessenger: notify begin -1399312757@com.liulishuo.filedownloader.DownloadTask@6864ab3
V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@e3e62f5 by 11 
D/FileDownloader.MessageSnapshotGate: ~~~callback -1399312757 old[11] new[-3] 1
D/FileDownloader.FileDownloadMessenger: notify block completed -1399312757@com.liulishuo.filedownloader.DownloadTask@6864ab3 FileDownloader-LauncherTask11
D/XINFA: FileDownloadListener.blockComplete 
D/FileDownloader.FileDownloadMessenger: notify completed -1399312757@com.liulishuo.filedownloader.DownloadTask@6864ab3
V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@e3e62f5 by -3 
D/FileDownloader.SerialHandlerCallback: start next com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096 5
V/FileDownloader.DownloadTaskHunter: call start Url[http://xxx.com/group1/M00/00/2E/wKgBo1qct0eAJYsEAAiqezQUy6U562.jpg], Path[/storage/emulated/0/XinFa/download/wKgBo1qct0eAJYsEAAiqezQUy6U562.jpg] Listener[com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096], Tag[6]
V/FileDownloader.DownloadTaskHunter: the task[-132000858] has been into the launch pool.
D/FileDownloader.FileDownloadMessenger: notify begin -132000858@com.liulishuo.filedownloader.DownloadTask@b628870
V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@b6d0b18 by 11 
D/FileDownloader.MessageSnapshotGate: ~~~callback -132000858 old[11] new[-3] 1
D/FileDownloader.FileDownloadMessenger: notify block completed -132000858@com.liulishuo.filedownloader.DownloadTask@b628870 FileDownloader-LauncherTask12
D/XINFA: FileDownloadListener.blockComplete 
D/FileDownloader.FileDownloadMessenger: notify completed -132000858@com.liulishuo.filedownloader.DownloadTask@b628870
V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@b6d0b18 by -3 
D/FileDownloader.SerialHandlerCallback: start next com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096 6
V/FileDownloader.DownloadTaskHunter: call start Url[http://xxx.com/group1/M00/00/32/wKgBA1qcpXiATMmkAA0Bputo4V4236.jpg], Path[/storage/emulated/0/XinFa/download/wKgBA1qcpXiATMmkAA0Bputo4V4236.jpg] Listener[com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096], Tag[7]
V/FileDownloader.DownloadTaskHunter: the task[2061180553] has been into the launch pool.
D/FileDownloader.FileDownloadMessenger: notify begin 2061180553@com.liulishuo.filedownloader.DownloadTask@52667e9
V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@9fa9fd7 by 11 
D/XINFA: FileDownloadListener Finished downloading http://xxx.com/group1/M00/00/2E/wKgBo1qcpQGAMdQWARH4pLsmsUU088.mp4
D/XINFADIAGNOSIS: 	......文件下载完成( wKgBo1qcpQGAMdQWARH4pLsmsUU088.mp4) (tag:4)
D/FileDownloader.MessageSnapshotGate: ~~~callback 2061180553 old[11] new[-3] 1
D/FileDownloader.FileDownloadMessenger: notify block completed 2061180553@com.liulishuo.filedownloader.DownloadTask@52667e9 FileDownloader-LauncherTask10
D/XINFA: Program downloading process (14678) : 8 : 3 : 37
D/XINFA: FileDownloadListener.blockComplete 
D/XINFA: MainHandler received : { when=0 what=204 obj=com.example.scott.zhihuiapplication.command.CommandJournalReport@3b3c0c4 target=com.example.scott.zhihuiapplication.MainHandler planTime=1520305918053 dispatchTime=0 finishTime=0 }
D/FileDownloader.FileDownloadMessenger: notify completed 2061180553@com.liulishuo.filedownloader.DownloadTask@52667e9
V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@9fa9fd7 by -3 
D/FileDownloader.SerialHandlerCallback: start next com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096 7
V/FileDownloader.DownloadTaskHunter: call start Url[http://xxx.com/group1/M00/00/32/wKgBA1qcpXeAQFSeAAqFIYEs_WM708.jpg], Path[/storage/emulated/0/XinFa/download/wKgBA1qcpXeAQFSeAAqFIYEs_WM708.jpg] Listener[com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096], Tag[8]
V/FileDownloader.DownloadTaskHunter: the task[-1419675611] has been into the launch pool.
D/FileDownloader.FileDownloadMessenger: notify begin -1419675611@com.liulishuo.filedownloader.DownloadTask@c396c6e
V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@6e8372e by 11 
D/FileDownloader.MessageSnapshotGate: ~~~callback -1419675611 old[11] new[-3] 1
D/FileDownloader.FileDownloadMessenger: notify block completed -1419675611@com.liulishuo.filedownloader.DownloadTask@c396c6e FileDownloader-LauncherTask11
D/XINFA: FileDownloadListener.blockComplete 
D/FileDownloader.FileDownloadMessenger: notify completed -1419675611@com.liulishuo.filedownloader.DownloadTask@c396c6e
V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@6e8372e by -3 
D/FileDownloader.SerialHandlerCallback: start next com.example.scott.zhihuiapplication.http.DownloadHelper$2@a1ee096 8
D/FileDownloader.SerialHandlerCallback: final serial null 8
D/XINFA: FileDownloadListener Finished downloading http://xxx.com/group1/M00/00/2E/wKgBo1qc0vaAMt_yAAc-NqEK3cY331.jpg
D/XINFADIAGNOSIS: 	......文件下载完成( wKgBo1qc0vaAMt_yAAc-NqEK3cY331.jpg) (tag:5)
D/XINFA: Program downloading process (14678) : 8 : 4 : 50
D/XINFA: FileDownloadListener Finished downloading http://xxx.com/group1/M00/00/2E/wKgBo1qct0eAJYsEAAiqezQUy6U562.jpg
D/XINFADIAGNOSIS: 	......文件下载完成( wKgBo1qct0eAJYsEAAiqezQUy6U562.jpg) (tag:6)
D/XINFA: Program downloading process (14678) : 8 : 5 : 62
D/XINFA: MainHandler received : { when=-1ms what=204 obj=com.example.scott.zhihuiapplication.command.CommandJournalReport@d43b2cf target=com.example.scott.zhihuiapplication.MainHandler planTime=1520305918063 dispatchTime=0 finishTime=0 }
D/XINFA: MainHandler received : { when=-1ms what=204 obj=com.example.scott.zhihuiapplication.command.CommandJournalReport@a456a48 target=com.example.scott.zhihuiapplication.MainHandler planTime=1520305918063 dispatchTime=0 finishTime=0 }
D/XINFA: FileDownloadListener Finished downloading http://xxx.com/group1/M00/00/32/wKgBA1qcpXiATMmkAA0Bputo4V4236.jpg
D/XINFADIAGNOSIS: 	......文件下载完成( wKgBA1qcpXiATMmkAA0Bputo4V4236.jpg) (tag:7)
D/XINFA: Program downloading process (14678) : 8 : 6 : 75
D/XINFA: FileDownloadListener Finished downloading http://xxx.com/group1/M00/00/32/wKgBA1qcpXeAQFSeAAqFIYEs_WM708.jpg
D/XINFADIAGNOSIS: 	......文件下载完成( wKgBA1qcpXeAQFSeAAqFIYEs_WM708.jpg) (tag:8)
D/XINFA: Program downloading process (14678) : 8 : 7 : 87

**Comment by rantianhua** [comment]
在下载 wKgBA1pqpryASTl-AN3jWeRgPLU912.mp4  的时候出现了 warn ，这是因为同样的 task 已经正在下载了。不过看里的列表里并没有同样的 task ，所以想问你有没有自定义 `IDGenerator` ？

另外希望提供完整的 FileDownloader 的日志，现在看到的是你自己的日志和部分 FileDownloader 的日志混在一起，不便于分析。FileDownloader 默认是运行在 `filedownloader` 进程，所以提取日志的时候要把该进程的 FileDownloader 日志页提取出来。

**Comment by espring** [comment]
所以想问你有没有自定义 IDGenerator ？
: 我没有自定义过IDGenerator, 我的使用方式也比较简单,  
在工程线程里, 
串行下载一批文件(8个), 最大的140M的mp4文件.
new FileDownloadQueueSet(serialTarget)
.setCallbackProgressTimes(1)
.setAutoRetryTimes(6)
.downloadSequentially(taskList)
.start();


出现warn的原因, 我不知道是不是因为这个temp文件在上一次下载失败后存在造成的.

非常抱歉, log比较乱, 我之后再做重现, 整理出来后发上来.

**Comment by hegelsu** [comment]
我这里也有个回调的提问，就是用FileDownloadQueueSet串行下载多个文件时如何得到所有任务下载完成的回调？如果是并行又如何得到？

**Comment by rantianhua** [comment]
@hegelsu 你的问题和这里描述的不一样，请参考 #256

**Comment by espring** [comment]
我这里是按#256中的方式自己实现了监听所有task完成.
* 注意重复下载的, 有warn, 不过, completed回调也有, 所以可以不用响应warn.
* error的处理.  这里要反应到你所有任务监控的出错报告上.

以上, 不知道有没有什么遗漏或问题.

**Comment by hegelsu** [comment]
FileDownloadQueueSet的Complete还是每个任务完成都会调一次，没法实现最终所有任务的完成的回调，只能是说在每个Complete里去判断FileDownloadQueueSet是否还有未完成的任务来判断，这个好像也没有什么方法来判断啊

**Comment by espring** [comment]
@rantianhua 正好请教一下, 异常情况下的回调.

文档中说: 可能会遇到以下回调而直接终止整个下载过程:
paused / completed / error / warn

我这里看下来, error时, 不会走completed, 一般是网络异常等.
warn时, 会走一遍completed回调. 一般是文件已经下载.

以上理解是否正确?

**Comment by espring** [comment]
@hegelsu 要自己维护一个任务列表,  可以用tag, 或url来查找.
completed回调中, 把自己任务列表中的对应项目状态改为完成.
error回调时, 把对应项改成error, 

上述的两个回调中, 最后都遍历一下自维护任务列表. 判断: 全部完成, 或有错

**Comment by hegelsu** [comment]
你说的这种做法理论上没有问题，但个人认为这个判断的功能应该纳入组件的功能合理些。因为FileDownloadQueueSet的初始化我已经明确给到了相应的任务，那么FileDownloadQueueSet应该对这些任务有个明确的状态信息处理更好些

**Comment by espring** [comment]
我理解, 这是因为这个基本库是以单例方式运行着, FileDownloadQueueSet考虑的是不断的有task进出, 它设定是有多个输入源,  所以它很难界定"哪些task算是一组, 并且给出一组完成的消息".
所以, 它的粒度都是task.

**Comment by rantianhua** [comment]
@espring 

>
我这里看下来, error时, 不会走completed, 一般是网络异常等.
warn时, 会走一遍completed回调. 一般是文件已经下载.

这里有点儿问题，如果一个 Task 执行了 warn 回调，就不会再对它进行 complete 的回调，你看到的 complete 回调应该是和它重复的另一个 task 的。

**Comment by espring** [comment]
@rantianhua
不好意思, 隔了这么长时间.
我今天在一个比较差的wifi环境下, 又出现上述问题.
文件已经下载下来, .temp的大小看是完整的.但就是走不下去.

log比较长, 放在这里了. 
https://gist.github.com/espring/13c62c55e94a7d7b5c4ba97cdb21063c

麻烦你了.

**Comment by rantianhua** [comment]
@espring 看了你提供的日志，感觉是不是不全，我看最后还有 task 在 progress 。

**Comment by espring** [comment]
@rantianhua 是的. 我这里有很多同步下载的任务.
中间一段是.temp文件对应的task, 从它的log里能看到什么? 
还能再开什么log么?

**Comment by rantianhua** [comment]
@espring 能把完整的 log 都提出来吗？从开始下载到出现问题的。

**Comment by espring** [comment]
不好意思, 有一段时间在做其他事情.
完整log没有, 就之前那么多内容了. 
这张票我先关闭了.
谢谢!
