### ISSUE TITLE
能否拿到数据库中所有已下载完、还未下载完的任务

### ISSUE THREAD

**Issue by ChenPengHuang** [lingochamp/FileDownloader#960]
找了一下好像没有这个API。
不能拿到之前所有的下载记录吗。
进入下载列表界面显示下载记录的需求，想应用市场那种。

**Comment by rantianhua** [comment]
FileDownloader 中数据库的作用是用来标记任务的状态以及下载的进度，进而提供断点下载的能力。所以它是 FileDownloader 内部私用的记录表，并不为外部提供服务，而且外部也不应该关心 FileDownloader  的数据库。你所描述的下载记录，这其实是具体的业务需求，这不是 FileDownloader 关心的内容。FileDownloader 作为一个下载器，而不是一个任务管理器。况且外部的业务需求，作为一个 library 来讲，它不应该也不会去干涉你的业务需求。

综上，所有和业务需求相关的东西，需要外部自己实现。
