### ISSUE TITLE
请问: 1 .如何在数据库中添加字段? 2. 如何保留数据库已经下载完成的记录？

### ISSUE THREAD

**Issue by Wangct23** [lingochamp/FileDownloader#963]
我自己修改了库里面的代码，但是这样就不方便随着库的版本更新。不知道是否有这样的接口开放？或者其他方法可以实现又不需要改动现有的库。
ps：我觉得删除数据库记录操作应该交给用户来做。
谢谢！

**Comment by rantianhua** [comment]
目前不考虑开发数据库接口，具体请参见 #960 ，作为备选方案，你可以自定义 `FileDownloadDatabase`。
