### ISSUE TITLE
无论设置串行还是并行执行，都是先下载3个，这几个结束后再下其他的

### ISSUE THREAD

**Issue by Zhangxd77** [lingochamp/FileDownloader#964]
你好，问题如题所示。这个是属于我少写什么代码了吗?还是机制就是如此？
麻烦懂的朋友能给讲解一下，谢谢

**Comment by espring** [comment]
同时进行的下载线程数默认是3个.

中文文档里:

* setMaxNetworkThreadCount(int) : 设置最大并行下载的数目(网络下载线程数), [1,12]
这里没说, 

后面配置说明中
download.max-network-thread-count: 用于同时下载的最大网络线程数, 区间[1, 12]
默认值是3
