### ISSUE TITLE
关于文件名相同的问题

### ISSUE THREAD

**Issue by yangwuan55** [lingochamp/FileDownloader#966]
如果文件名相同但是域名不同的情况会重新下载吗？
场景是这样的，我有N个cdn，下载的时候可能出现md5校验失败的情况，这时候我会先把下好的文件删除，然后换一个cdn去下载，但是我发现md5全部失败。所以我怀疑是不是框架内有缓存，发现我下载的文件路径是一样的就直接从缓存中拿文件了？

我之所以这样怀疑是因为我从新下载文件的时间是一瞬间。

跪求解决。。。

**Comment by rantianhua** [comment]
是的，如果你保存的文件名相同，那么 FileDownloader 会认为文件已经下载完成了。关于 dynamic download url 的问题，请参考 #431 。你可以自定义 `IdGenerator` 解决你的问题。
