### ISSUE TITLE
下载文件需要cookies登录验证怎么办

### ISSUE THREAD

**Issue by AnJiuZhe** [lingochamp/FileDownloader#969]
https://yaohw.com/bbs/download.aspx?siteid=1000&classid=201&book_id=598727&id=450506&RndPath=UploadFiles&n=111578400.apk
类似上面这种url,需要登录后才可以下载，用浏览器登录过该网站的话，打开这个网址就直接开始下载了。
请问要如何把cookies添加进去呢？

**Comment by rantianhua** [comment]
请参考 `BaseDownloadTask#addHeader(String)` 和 `BaseDownloadTask#addHeader(String, String)` 。

**Comment by AnJiuZhe** [comment]
你好，我知道有这个方法。但是我不知道要怎样添加头部信息，试过了添加task.addHeader("Referer", "http://..."); 好像不行，还是不能下载。

**Comment by rantianhua** [comment]
如果是添加 Cookie 的话，应该是添加 "cookie" ，为什么要添加 "referer" 呢？

**Comment by AnJiuZhe** [comment]
@rantianhua 好的，我试试。谢谢！
