### ISSUE TITLE
无法获取请求头

### ISSUE THREAD

**Issue by s347719** [lingochamp/FileDownloader#971]
#### Issue

在下载文件成功之后，无法获取到请求头信息
FileDownloadHeader 为null
---

**Comment by rantianhua** [comment]
如果你在构建 `BaseDownloadTask` 的时候没有调用 `addHeader` 方法的话，那么通过 `DownloadTask` 里面的 `FileDownloadHeader` 不会实例化。

**Comment by s347719** [comment]
感谢。我根据你的建议已经能拿到我在初始化header的时候传入的值，那么我想请问我如何能拿到服务器返回的header里面的值
