### ISSUE TITLE
File Creation Listener

### ISSUE THREAD

**Issue by xCalifier** [lingochamp/FileDownloader#973]
**Is there any Listener to get the file creation status in the pending state.** 

For fast internal storage the creation time is very short but i know in slow SD cards, the creation takes a long time, So it would be a good way to notify what's taking so long.

**Comment by rantianhua** [comment]
Sorry, there is no such listener to do that thing. For FileDownloader, it just needs to create a temp file before the real downloading, just a normal file operation.

So are you sure that the operation on SD cards takes too much time? Or you just have a guess and you want to confirm it?

**Comment by xCalifier** [comment]
Yes i guess that it will take time to create it proportional to sdcard speed.. 

Do you think that doesn't require much time whatever the memory write capacity is ?

I will try a very large file on a slow card and let you know.

**Comment by rantianhua** [comment]
I mean FileDownloader just creates a empty temp file during pending status, so I think it will not be a problem anyway. But FileDownloader will write file all the time during progress status, you can provide the log of FileDownloader and I can check whether the file operation takes too long or not.

On the other hand, there is `Output performance test` in `PerformanceTestActivity` in our demo, you can use it to have a test and tell me the result.

**Comment by rantianhua** [comment]
If you have any new discovery, please reopen this issue.
