### ISSUE TITLE
对一个任务进行重复下载会如何？

### ISSUE THREAD

**Issue by wangsuicheng** [lingochamp/FileDownloader#976]
就是比如对同一个任务，每次都会创建一个task，然后start，以前start过task会被取消，然后启动这个task吗？这个task是会带有自己的listener的，文件比较大，所以还在下载中，我每次都new task来启动下载，没有使用上一个task来pause，会如何？

**Comment by rantianhua** [comment]
FileDownloader 是用下载的 URL 和保存文件的地址来作为 Task 的 id。所以对于同样的保存地址和 Url，建多个 Task ，实际上对于  FileDownloader 来说，是进行断点下载的，即第一次建了一个 Task 下载了 20% ，第二次用同样的 URL 和保存地址建了个  Task ，FileDownloader 会从  20% 初开始下载。

**Comment by wangsuicheng** [comment]
@rantianhua 我是是想说短时间内创建多个同一个下载的task，以前是task是会被移除掉的吧？它的各个监听listener，例如finishListener的。

**Comment by rantianhua** [comment]
请看 [这里](https://github.com/lingochamp/FileDownloader/wiki/FileDownloadListener)
