### ISSUE TITLE
启动任务后，还未下载完，短时间内再启动相同的链接task

### ISSUE THREAD

**Issue by wangsuicheng** [lingochamp/FileDownloader#977]
这时这个新的task会被warn吧？然后呢？它身上的各个监听应该被回调了吧？不会加入FileDownloder库的taskQueue里吧？ 是不是只是触发监听回调，然后实质是不会运行了？

**Comment by rantianhua** [comment]
不会再运行了，请仔细查看[这里](https://github.com/lingochamp/FileDownloader/wiki/FileDownloadListener)
