### ISSUE TITLE
Unable to download this url?? Connection closed by server

### ISSUE THREAD

**Issue by creativelabsofficial** [lingochamp/FileDownloader#978]
http://fs1.bdworlds.me:182/d/45oh7mrsyockkzylkhtvwtqnrcqclx7hw3vxxbv3y63y7uwchpxlxej3fzgymfgodh32qulx/The%20Hurricane%20Heist%20(2018)%20Hindi%20300MB%20Dual%20Audio%20HDCAM-Rip%20300mb.movie.mkv

this url works with normal browser but with filedownloader gives following error.

` I/RETRYERROR: retry: Connection failed with request[{accept=[*/*], pragma=[no-cache], range=[bytes=229923969-306565291], user-agent=[FileDownloader/1.6.9]}] response[{connection=[close], content-disposition=[attachment], content-length=[162], content-type=[text/html], date=[Sun, 25 Mar 2018 14:50:36 GMT], server=[nginx]}] http-state[403] on task[-2018132277-3], which is changed after verify connection, so please try again.`

My Code to start download
`        BaseDownloadTask task = FileDownloader.getImpl().create(download.getURL())
                .setPath(download.getPath()+"/"+download.getName(),false)
                .setCallbackProgressTimes(200)
                .setListener(mMainDownloadLisner)
                .setAutoRetryTimes(download.getRetry())
                .addHeader("Pragma","no-cache")
                .addHeader("Accept","*/*");`

**Comment by rantianhua** [comment]
If you can download it from chrome but not on FileDownloader, the problem must be on the request header, so please check the request headers from chrome and mock the same request headers on the FileDownloader and test again. You can refer to [this](https://github.com/lingochamp/FileDownloader/wiki/Can't-download-for-some-Urls%3F)

**Comment by creativelabsofficial** [comment]
Chrome Usages http protocol {HTTP1.0) and detect host:**"fs1.bdworlds.me"**  but file downloader  usages http protocol(HTTP1.1) which i assume more advanced and should have all fratures of (HTTP1.0) and host field send by file downloader is **"http://fs1.bdworlds.me:182/d/"** .

I think host is wrong but how to correct this error??
