### ISSUE TITLE
任务暂停下载恢复后获取已下载文件大小为0

### ISSUE THREAD

**Issue by AnJiuZhe** [lingochamp/FileDownloader#980]
您好,问题是这样的,使用FileDownloadSerialQueue串行下载3个任务,依次将3个任务下载一部分后暂停,然后依次恢复下载任务,此时获取正在等待任务的已下载文件大小为0(之前文件应该是下载了一部分),请问这个问题要怎么解决呢?
![image](https://user-images.githubusercontent.com/30287547/37960287-e0639118-31e7-11e8-824c-c28a6cd05da8.png)
![image](https://user-images.githubusercontent.com/30287547/37960310-eeceada0-31e7-11e8-9cfd-e37e345bbbdf.png)

**Comment by Jacksgong** [comment]
获取到进度为0的问题，参考这里: https://github.com/lingochamp/FileDownloader/issues/572#issuecomment-303915958
