### ISSUE TITLE
不能自定义手机下载路径吗？

### ISSUE THREAD

**Issue by Icando26** [lingochamp/FileDownloader#981]
在TasksManagerDemoActivity中要想修改保存路径，
                    final BaseDownloadTask task = FileDownloader.getImpl().create(model.getUrl())
                            .setPath(model.getPath())
                            .setCallbackProgressTimes(100)
                            .setListener(taskDownloadListener);

中  .setPath(model.getPath())改成  .setPath(Environment.getExternalStorageDirectory().getPath()+“down”)

运行结果总是显示tag 为null，而造成闪退。
  **private TaskItemViewHolder checkCurrentHolder(final BaseDownloadTask task) {
                final TaskItemViewHolder tag = (TaskItemViewHolder) task.getTag();
                if (tag.id != task.getId()) {
                    return null;
                }
                return tag;
            }**

**Comment by Jacksgong** [comment]
如果是demo项目，改为`Environment.getExternalStorageDirectory().getPath()+“down”`目录在高版本手机上肯定是crash的，因为`demo`项目没有申请高版本系统的读写权限。参考这里: https://github.com/lingochamp/FileDownloader/issues/77#issuecomment-205245349
