### ISSUE TITLE
通过url下载zip文件的时候遇到返回的总大小为-1，head里面的contetn-length有值

### ISSUE THREAD

**Issue by ForestWangxt** [lingochamp/FileDownloader#983]
在下载一个zip文件的时候获取下载进度的时候，返回的总文件大小为-1，抓包查看返回信息的head，发现content-length是有值的。自己写了个HttpUrlConnection去得到content-length没问题，但是使用FileDownloader得到的总文件大小一直是-1

**Comment by rantianhua** [comment]
请提供 FileDownloader 的日志，这样才能确认问题。

**Comment by ForestWangxt** [comment]
D/FileDownloader.DownloadTask: setPath /storage/emulated/0/data00.zip
03-30 13:43:00.505 5698-5698/ai.jinghang.www.testfiledown D/FileDownloader.DownloadTask: setListener ai.jinghang.www.testfiledown.MainActivity$1$1@4bfd0e3
03-30 13:43:00.506 5698-5698/ai.jinghang.www.testfiledown V/FileDownloader.DownloadTaskHunter: call start Url[http://139.199.123.104:5000/getquizdata], Path[/storage/emulated/0/data00.zip] Listener[ai.jinghang.www.testfiledown.MainActivity$1$1@4bfd0e3], Tag[null]
03-30 13:43:00.521 5698-6053/ai.jinghang.www.testfiledown V/FileDownloader.FileDownloadEventPool: setListener event.service.connect.changed
03-30 13:43:00.525 5698-5698/ai.jinghang.www.testfiledown V/FileDownloader.DownloadTaskHunter: the task[-90926864] has been into the launch pool.
03-30 13:43:00.527 5698-6053/ai.jinghang.www.testfiledown D/FileDownloader.FileDownloadProperties: not found filedownloader.properties
03-30 13:43:00.528 5698-6053/ai.jinghang.www.testfiledown I/FileDownloader.FileDownloadProperties: init properties 3
                                                                                                    load properties: http.lenient=FALSE; process.non-separate=FALSE; download.min-progress-step=65536; download.min-progress-time=2000; download.max-network-thread-count=3; file.non-pre-allocation=FALSE; broadcast.completed=FALSE; download.trial-connection-head-method=FALSE
03-30 13:43:00.534 5698-6053/ai.jinghang.www.testfiledown D/FileDownloader.LostServiceConnectedHandler: Waiting for connecting with the downloader service... -90926864
03-30 13:43:00.608 5698-6053/ai.jinghang.www.testfiledown D/FileDownloader.FileDownloadServiceUIGuard: bindStartByContext Application
03-30 13:43:00.624 5698-6053/ai.jinghang.www.testfiledown D/FileDownloader.DownloadTaskHunter: free the task -90926864, when the status is 10
03-30 13:43:01.696 5698-5698/ai.jinghang.www.testfiledown D/FileDownloader.FileDownloadServiceUIGuard: onServiceConnected ComponentInfo{ai.jinghang.www.testfiledown/com.liulishuo.filedownloader.services.FileDownloadService$SeparateProcessService} com.liulishuo.filedownloader.i.IFileDownloadIPCService$Stub$Proxy@d417058
03-30 13:43:01.697 5698-5698/ai.jinghang.www.testfiledown V/FileDownloader.FileDownloadEventPool: asyncPublishInNewThread event.service.connect.changed
03-30 13:43:01.699 5698-6105/ai.jinghang.www.testfiledown V/FileDownloader.FileDownloadEventPool: publish event.service.connect.changed
03-30 13:43:01.700 5698-6105/ai.jinghang.www.testfiledown D/FileDownloader.LostServiceConnectedHandler: The downloader service is connected.
03-30 13:43:01.701 5698-6105/ai.jinghang.www.testfiledown V/FileDownloader.DownloadTaskHunter: call start Url[http://139.199.123.104:5000/getquizdata], Path[/storage/emulated/0/data00.zip] Listener[ai.jinghang.www.testfiledown.MainActivity$1$1@4bfd0e3], Tag[null]
03-30 13:43:01.701 5698-6105/ai.jinghang.www.testfiledown V/FileDownloader.DownloadTaskHunter: the task[-90926864] has been into the launch pool.
03-30 13:43:01.702 5698-6106/ai.jinghang.www.testfiledown D/FileDownloader.FileDownloadMessenger: notify begin -90926864@com.liulishuo.filedownloader.DownloadTask@fc13617
03-30 13:43:01.702 5698-6106/ai.jinghang.www.testfiledown V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@893a04 by 11 
03-30 13:43:01.702 5698-6106/ai.jinghang.www.testfiledown V/FileDownloader.FileDownloadList: add list in all -90926864@com.liulishuo.filedownloader.DownloadTask@fc13617 11 1
03-30 13:43:01.743 5698-6109/ai.jinghang.www.testfiledown D/FileDownloader.MessageSnapshotGate: ~~~callback -90926864 old[11] new[1] 1
03-30 13:43:01.743 5698-6109/ai.jinghang.www.testfiledown D/FileDownloader.FileDownloadMessenger: notify pending -90926864@com.liulishuo.filedownloader.DownloadTask@fc13617
03-30 13:43:01.744 5698-6109/ai.jinghang.www.testfiledown D/FileDownloader.MessageSnapshotGate: updateKeepFlow
03-30 13:43:01.745 5698-6109/ai.jinghang.www.testfiledown D/FileDownloader.MessageSnapshotGate: ~~~callback -90926864 old[1] new[6] 1
03-30 13:43:01.745 5698-6109/ai.jinghang.www.testfiledown D/FileDownloader.FileDownloadMessenger: notify started -90926864@com.liulishuo.filedownloader.DownloadTask@fc13617
03-30 13:43:01.745 5698-6109/ai.jinghang.www.testfiledown D/FileDownloader.MessageSnapshotGate: updateKeepFlow
03-30 13:43:04.837 5698-6109/ai.jinghang.www.testfiledown D/FileDownloader.MessageSnapshotGate: ~~~callback -90926864 old[6] new[2] 1
03-30 13:43:04.838 5698-6109/ai.jinghang.www.testfiledown D/FileDownloader.FileDownloadMessenger: notify connected -90926864@com.liulishuo.filedownloader.DownloadTask@fc13617
03-30 13:43:04.838 5698-6109/ai.jinghang.www.testfiledown D/FileDownloader.MessageSnapshotGate: updateKeepFlow
03-30 13:43:07.802 5698-6109/ai.jinghang.www.testfiledown D/FileDownloader.MessageSnapshotGate: ~~~callback -90926864 old[2] new[3] 1
03-30 13:43:07.803 5698-6109/ai.jinghang.www.testfiledown D/FileDownloader.FileDownloadMessenger: notify progress -90926864@com.liulishuo.filedownloader.DownloadTask@fc13617 4096 -1
03-30 13:43:07.803 5698-6109/ai.jinghang.www.testfiledown D/FileDownloader.MessageSnapshotGate: updateKeepFlow
03-30 13:43:07.813 5698-5698/ai.jinghang.www.testfiledown I/System.out: ===========4096==========-1
03-30 13:43:08.208 5698-6109/ai.jinghang.www.testfiledown D/FileDownloader.MessageSnapshotGate: ~~~callback -90926864 old[3] new[3] 1
03-30 13:43:08.209 5698-6109/ai.jinghang.www.testfiledown D/FileDownloader.FileDownloadMessenger: notify progress -90926864@com.liulishuo.filedownloader.DownloadTask@fc13617 17836 -1
03-30 13:43:08.209 5698-6109/ai.jinghang.www.testfiledown D/FileDownloader.MessageSnapshotGate: updateKeepFlow
03-30 13:43:08.219 5698-5698/ai.jinghang.www.testfiledown I/System.out: ===========17836==========-1
03-30 13:43:08.419 5698-6109/ai.jinghang.www.testfiledown D/FileDownloader.MessageSnapshotGate: ~~~callback -90926864 old[3] new[3] 1
03-30 13:43:08.419 5698-6109/ai.jinghang.www.testfiledown D/FileDownloader.FileDownloadMessenger: notify progress -90926864@com.liulishuo.filedownloader.DownloadTask@fc13617 21932 -1
03-30 13:43:08.420 5698-6109/ai.jinghang.www.testfiledown D/FileDownloader.MessageSnapshotGate: updateKeepFlow
03-30 13:43:08.430 5698-5698/ai.jinghang.www.testfiledown I/System.out: ===========21932==========-1
**************************************************************************************************************
**************************************************************************************************************
03-30 13:43:01.755 6055-6108/ai.jinghang.www.testfiledown:filedownloader I/System.out: sLuckyMoneyUrl = wx.gtimg.com/hongbao/
03-30 13:43:01.757 6055-6108/ai.jinghang.www.testfiledown:filedownloader I/System.out: [socket] connection /192.168.1.25:8888;LocalPort=53349(0)
03-30 13:43:04.758 6055-6108/ai.jinghang.www.testfiledown:filedownloader I/System.out: [socket][:53349] exception
03-30 13:43:04.759 6055-6108/ai.jinghang.www.testfiledown:filedownloader I/System.out: [socket] connection /139.199.123.104:5000;LocalPort=45375(0)
03-30 13:43:04.797 6055-6108/ai.jinghang.www.testfiledown:filedownloader W/FileDownloader.FileDownloadUtils: don't get instance length fromContent-Range header
03-30 13:43:04.977 6055-6108/ai.jinghang.www.testfiledown:filedownloader I/System.out: [socket] connection /192.168.1.25:8888;LocalPort=38649(0)
03-30 13:43:07.758 6055-6108/ai.jinghang.www.testfiledown:filedownloader I/System.out: [socket][:38649] exception
03-30 13:43:07.759 6055-6108/ai.jinghang.www.testfiledown:filedownloader I/System.out: [socket] connection /139.199.123.104:5000;LocalPort=36240(0)
****************************************************************************************
****************************************************************************************
============================================
上面的是加了log输出的结果
下面是调用FileDownloader的过程。
FileDownloader.setup(this);
 FileDownloadLog.NEED_LOG = true;
                FileDownloader.getImpl().create("http://139.199.123.104:5000/getquizdata")
                        .setPath(str)
                        .setListener(new FileDownloadLargeFileListener() {
                            @Override
                            protected void pending(BaseDownloadTask task, long soFarBytes, long totalBytes) {
                            }
                            @Override
                            protected void progress(BaseDownloadTask task, long soFarBytes, long totalBytes) {
                                System.out.println("==========="+soFarBytes+"=========="+totalBytes);
                            }
                            @Override
                            protected void paused(BaseDownloadTask task, long soFarBytes, long totalBytes) {
                            }
                            @Override
                            protected void completed(BaseDownloadTask task) {
                                System.out.println("下载完成");
                            }
                            @Override
                            protected void error(BaseDownloadTask task, Throwable e) {
                                System.out.println(e.toString());
                            }
                            @Override
                            protected void warn(BaseDownloadTask task) {
                            }
                        }).start();
            }

**Comment by ForestWangxt** [comment]
这个是完整的filedownloader日志：

03-30 14:05:48.472 8326-8326/ai.jinghang.www.testfiledown:filedownloader I/art: Late-enabling -Xcheck:jni
03-30 14:05:48.544 8326-8326/ai.jinghang.www.testfiledown:filedownloader W/art: oat_file_name = /data/dalvik-cache/arm64/data@app@ai.jinghang.www.testfiledown-1@split_lib_dependencies_apk.apk@classes.dex, b = 0
03-30 14:05:48.601 8326-8326/ai.jinghang.www.testfiledown:filedownloader W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/ai.jinghang.www.testfiledown-1/split_lib_dependencies_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@ai.jinghang.www.testfiledown-1@split_lib_dependencies_apk.apk@classes.dex) because non-0 exit status
03-30 14:05:48.906 8326-8326/ai.jinghang.www.testfiledown:filedownloader W/art: oat_file_name = /data/dalvik-cache/arm64/data@app@ai.jinghang.www.testfiledown-1@split_lib_slice_0_apk.apk@classes.dex, b = 0
03-30 14:05:48.965 8326-8326/ai.jinghang.www.testfiledown:filedownloader W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/ai.jinghang.www.testfiledown-1/split_lib_slice_0_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@ai.jinghang.www.testfiledown-1@split_lib_slice_0_apk.apk@classes.dex) because non-0 exit status
03-30 14:05:48.973 8326-8326/ai.jinghang.www.testfiledown:filedownloader W/art: oat_file_name = /data/dalvik-cache/arm64/data@app@ai.jinghang.www.testfiledown-1@split_lib_slice_1_apk.apk@classes.dex, b = 0
03-30 14:05:49.030 8326-8326/ai.jinghang.www.testfiledown:filedownloader W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/ai.jinghang.www.testfiledown-1/split_lib_slice_1_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@ai.jinghang.www.testfiledown-1@split_lib_slice_1_apk.apk@classes.dex) because non-0 exit status
03-30 14:05:49.031 8326-8326/ai.jinghang.www.testfiledown:filedownloader W/art: oat_file_name = /data/dalvik-cache/arm64/data@app@ai.jinghang.www.testfiledown-1@split_lib_slice_2_apk.apk@classes.dex, b = 0
03-30 14:05:49.091 8326-8326/ai.jinghang.www.testfiledown:filedownloader W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/ai.jinghang.www.testfiledown-1/split_lib_slice_2_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@ai.jinghang.www.testfiledown-1@split_lib_slice_2_apk.apk@classes.dex) because non-0 exit status
03-30 14:05:49.101 8326-8326/ai.jinghang.www.testfiledown:filedownloader W/art: oat_file_name = /data/dalvik-cache/arm64/data@app@ai.jinghang.www.testfiledown-1@split_lib_slice_3_apk.apk@classes.dex, b = 0
03-30 14:05:49.160 8326-8326/ai.jinghang.www.testfiledown:filedownloader W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/ai.jinghang.www.testfiledown-1/split_lib_slice_3_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@ai.jinghang.www.testfiledown-1@split_lib_slice_3_apk.apk@classes.dex) because non-0 exit status
03-30 14:05:49.162 8326-8326/ai.jinghang.www.testfiledown:filedownloader W/art: oat_file_name = /data/dalvik-cache/arm64/data@app@ai.jinghang.www.testfiledown-1@split_lib_slice_4_apk.apk@classes.dex, b = 0
03-30 14:05:49.219 8326-8326/ai.jinghang.www.testfiledown:filedownloader W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/ai.jinghang.www.testfiledown-1/split_lib_slice_4_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@ai.jinghang.www.testfiledown-1@split_lib_slice_4_apk.apk@classes.dex) because non-0 exit status
03-30 14:05:49.221 8326-8326/ai.jinghang.www.testfiledown:filedownloader W/art: oat_file_name = /data/dalvik-cache/arm64/data@app@ai.jinghang.www.testfiledown-1@split_lib_slice_5_apk.apk@classes.dex, b = 0
03-30 14:05:49.278 8326-8326/ai.jinghang.www.testfiledown:filedownloader W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/ai.jinghang.www.testfiledown-1/split_lib_slice_5_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@ai.jinghang.www.testfiledown-1@split_lib_slice_5_apk.apk@classes.dex) because non-0 exit status
03-30 14:05:49.281 8326-8326/ai.jinghang.www.testfiledown:filedownloader W/art: oat_file_name = /data/dalvik-cache/arm64/data@app@ai.jinghang.www.testfiledown-1@split_lib_slice_6_apk.apk@classes.dex, b = 0
03-30 14:05:49.338 8326-8326/ai.jinghang.www.testfiledown:filedownloader W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/ai.jinghang.www.testfiledown-1/split_lib_slice_6_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@ai.jinghang.www.testfiledown-1@split_lib_slice_6_apk.apk@classes.dex) because non-0 exit status
03-30 14:05:49.340 8326-8326/ai.jinghang.www.testfiledown:filedownloader W/art: oat_file_name = /data/dalvik-cache/arm64/data@app@ai.jinghang.www.testfiledown-1@split_lib_slice_7_apk.apk@classes.dex, b = 0
03-30 14:05:49.394 8326-8326/ai.jinghang.www.testfiledown:filedownloader W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/ai.jinghang.www.testfiledown-1/split_lib_slice_7_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@ai.jinghang.www.testfiledown-1@split_lib_slice_7_apk.apk@classes.dex) because non-0 exit status
03-30 14:05:49.405 8326-8326/ai.jinghang.www.testfiledown:filedownloader W/art: oat_file_name = /data/dalvik-cache/arm64/data@app@ai.jinghang.www.testfiledown-1@split_lib_slice_8_apk.apk@classes.dex, b = 0
03-30 14:05:49.459 8326-8326/ai.jinghang.www.testfiledown:filedownloader W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/ai.jinghang.www.testfiledown-1/split_lib_slice_8_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@ai.jinghang.www.testfiledown-1@split_lib_slice_8_apk.apk@classes.dex) because non-0 exit status
03-30 14:05:49.463 8326-8326/ai.jinghang.www.testfiledown:filedownloader W/art: oat_file_name = /data/dalvik-cache/arm64/data@app@ai.jinghang.www.testfiledown-1@split_lib_slice_9_apk.apk@classes.dex, b = 0
03-30 14:05:49.519 8326-8326/ai.jinghang.www.testfiledown:filedownloader W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/ai.jinghang.www.testfiledown-1/split_lib_slice_9_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@ai.jinghang.www.testfiledown-1@split_lib_slice_9_apk.apk@classes.dex) because non-0 exit status
03-30 14:05:49.521 8326-8326/ai.jinghang.www.testfiledown:filedownloader W/System: ClassLoader referenced unknown path: /data/app/ai.jinghang.www.testfiledown-1/lib/arm64
03-30 14:05:49.609 8326-8387/ai.jinghang.www.testfiledown:filedownloader I/DpmTcmClient: RegisterTcmMonitor from: com.android.okhttp.TcmIdleTimerMonitor
03-30 14:05:49.613 8326-8387/ai.jinghang.www.testfiledown:filedownloader I/System.out: sLuckyMoneyUrl = wx.gtimg.com/hongbao/
03-30 14:05:49.615 8326-8387/ai.jinghang.www.testfiledown:filedownloader I/System.out: [socket] connection /192.168.1.25:8888;LocalPort=59558(0)
03-30 14:05:52.618 8326-8387/ai.jinghang.www.testfiledown:filedownloader I/System.out: [socket][:59558] exception
03-30 14:05:52.619 8326-8387/ai.jinghang.www.testfiledown:filedownloader I/System.out: [socket] connection /139.199.123.104:5000;LocalPort=36402(0)
03-30 14:05:52.662 8326-8387/ai.jinghang.www.testfiledown:filedownloader W/FileDownloader.FileDownloadUtils: don't get instance length fromContent-Range header
03-30 14:05:52.859 8326-8387/ai.jinghang.www.testfiledown:filedownloader I/System.out: [socket] connection /192.168.1.25:8888;LocalPort=40741(0)
03-30 14:05:55.619 8326-8387/ai.jinghang.www.testfiledown:filedownloader I/System.out: [socket][:40741] exception
03-30 14:05:55.620 8326-8387/ai.jinghang.www.testfiledown:filedownloader I/System.out: [socket] connection /139.199.123.104:5000;LocalPort=42713(0)

**Comment by Jacksgong** [comment]
这里已经说明的很清楚了:

```
W/FileDownloader.FileDownloadUtils: don't get instance length from Content-Range header
```

由于没有`Content-Range`所以拿不到文件的总大小；

由于试探链接是在决定分块之前，所以试探链接发起的请求是`Range: 0-0`的请求，此时返回的`Content-Length`是无效的，根据协议，此时的`Content-Length`始终为`1`(即此时返回的body中只会带有开始的一个字节)：

1. 根据协议，请求为`Range:0-0`，如果返回的`Content-Length`是`1`或者根本没有，如果此时`Content-Length`为文件的总大小，这个是不符合协议的，并且这个大小我们也无法确定是否就是文件大小
2. 如果试探请求不是`Range:0-0`，使用`GET`做试探请求，便会导致[该文章](https://blog.dreamtobe.cn/tcp-window/)提到的问题，所以我们不得不在试探连接中采用该请求参数的请求头，否则用户就会面临每次都多余下载了一部分数据的问题
3. 在okdownload中会对这块做一层补救，也就是说，如果`GET`试探链接发现存在`Content-Length`但是不存在`Content-Range`的情况下，会尝试再发起一次`HEAD`方法的请求，如果后端支持`HEAD`请求，此时便会使用`Content-Length`返回的有效数值，由于这个不是FileDownloader的问题，目前这个需求不会再在FileDownloader中添加，后续所有的需求都只会在okdownload上进行迭代。
