### ISSUE TITLE
FileDownloader.FileDownloadUtils: don't get instance length fromContent-Range header

### ISSUE THREAD

**Issue by TrumenXing** [lingochamp/FileDownloader#984]
FileDownloader.FileDownloadUtils: don't get instance length fromContent-Range header
在更新APK的时候出现这样的错误，请问是怎么回事？如果服务器不支持断点续传如何获取到待下载文件的大小？

**Comment by kerneltea** [comment]
我也遇到这个问题了。
但是之前的版本是好的：
https://github.com/lingochamp/FileDownloader/issues/974

所以不知道他们改了什么，现在也没办法降回去，一降回去就崩溃，因为内部用了数据库。

**Comment by rantianhua** [comment]
之前为了解决 #933 ，获取文件大小改为两种方式，默认方式为：在获取文件大小的时候，发送一个 range 为 0-0 的请求，此时会在 `Content-Range` 这个 response header 里面获取文件总大小，如果你的服务器没有实现这个 response header ，那么这一次请求就拿不到文件总大小。可配置的方式为：通过 `filedownloader.properties` 文件可以配置 `trial-connection-head-method` 为 true ，那么此时获取文件大小采用 Head 请求而不是 Get 请求，文件大小依然在 `Content-Range` 里面获取。

如果没有获取到文件总大小，那么会按照 chunk  的方式下载，即此时下载进度无效 ，但最终也会正常下载完成。
