### ISSUE TITLE
关于主线程卡顿的问题

### ISSUE THREAD

**Issue by 13107422824** [lingochamp/FileDownloader#986]
你好，请教一下，我最初使用的版本是 0.3.3版本，最近更新到1.5.8,同时执行3个下载任务，然后做其他的操作，发现整个应用非常卡，但是在用0.3.3版本的时候没有这种情况。是我继承的问题嘛？

**Comment by Jacksgong** [comment]
你可以试试demo project，如果你的主线程的卡顿相关，与demo project点击启动与暂停的时候的反应的情况类似，那么这个问题已经在okdownload中修复。如果是其他问题你这么说我不是很理解，不过FileDownloader中很多点在okdownload中已经得到了大量的优化。
