### ISSUE TITLE
在filedownloader进程中看到这个打印？

### ISSUE THREAD

**Issue by csshine** [lingochamp/FileDownloader#989]
04-10 00:26:59.952 29125-29125/? E/System:  ********** PLEASE READ ************ 
     * 
     * New versions of the Android SDK no longer support the Crypto provider.
     * If your app was relying on setSeed() to derive keys from strings, you
     * should switch to using SecretKeySpec to load raw key bytes directly OR
     * use a real key derivation function (KDF). See advice here : 
     * http://android-developers.blogspot.com/2016/06/security-crypto-provider-deprecated-in.html 
     *********************************** 
04-10 00:26:59.965 29125-29125/? E/Minikin: Could not get cmap table size!
04-10 00:26:59.990 29125-29183/? D/NetworkSecurityConfig: No Network Security Config specified, using platform default

**Comment by rantianhua** [comment]
这应该是 Android SDK 不支持加密算法的问题，你可以点击它日志给出的链接查看详情，或者看看 [这里](https://blog.csdn.net/drkcore/article/details/69931654)。FileDownloader 内部没有什么加密逻辑，是你自己在项目中使用了什么加密功能吗？

**Comment by Jacksgong** [comment]
感谢你的提醒，不过正如 @rantianhua 说的，FileDownloader确实没有用到这块逻辑，因此这个应该与FileDownloader本身无关。
