### ISSUE TITLE
下载进程重命名文件时崩溃NullPointerException

### ISSUE THREAD

**Issue by ykrank** [lingochamp/FileDownloader#991]
# FileDownloader-Network28(808)
java.lang.NullPointerException

1 java.io.File.<init>(File.java:282)
--
2 com.liulishuo.filedownloader.download.DownloadStatusCallback.void renameTempFile()(Proguard:9295)
3 ##_parent_##2##_parent_##
4 ##_child_## void handleCompleted()##_child_##
5 ##_child_## void onCompletedDirectly()##_child_##
6 com.liulishuo.filedownloader.download.DownloadLaunchRunnable.void run()(Proguard:330)
7 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
8 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
9 java.lang.Thread.run(Thread.java:764)

可能是下载的网址并不是文件，导致网络请求成功，然而文件找不到

**Comment by rantianhua** [comment]
下载的网址并不是文件是什么意思？可以直接把链接分享出来看看吗？还有能提供 FileDownloader 的详细日志吗？

**Comment by ykrank** [comment]
比如图片网址其实是个网页或者网页跳转之类，这时候
DownloadStatusCallback final File tempFile = new File(tempPath);会报错

**Comment by rantianhua** [comment]
@ykrank 请告诉我最重要的信息，即 FileDownloader 的日志和版本号。否则真的无法从你现有的信息中找出什么问题。

**Comment by rantianhua** [comment]
长时间未回复，先关掉，希望提供更详细的信息后再 reopen
