### ISSUE TITLE
库只支持http下载协议

### ISSUE THREAD

**Issue by pinixiong** [lingochamp/FileDownloader#997]
thunder:// ftp:// http:// ed2k:// 磁力链接 库能新增这些协议下载吗

**Comment by Jacksgong** [comment]
默认是采用UrlConnection，如果你希望实现其他协议，自行实现`FileDownloadConnection`然后通过[该方法](https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component)注入即可。
