### ISSUE TITLE
demo多任务管理器那里滑动列表卡顿，排查好久，都没有找到问题？可否解答一下，谢谢

### ISSUE THREAD

**Issue by xyZangGit** [lingochamp/FileDownloader#998]

**Comment by xyZangGit** [comment]
Tasks with the listener can't start, because can't find any task with the provided listener, maybe tasks instance has been started in the past, so they are all are inUsing, if in this case, you can use [BaseDownloadTask#reuse] to reuse theme first then start again: [com.creatoo.culturaltv.mvp.DownLoad2Activity$3@50688db, TRUE]

多任务串行下载报错

**Comment by rantianhua** [comment]
@xyZangGit 请提供详细日志，否则很难提供帮助。这个我先关掉，希望能按照问题模版重新提 issue ，尤其是 FileDownloader 日志，如果 FileDownloader 运行在 'filedownload' 进程，改进程的日志也需要提供。
