### ISSUE TITLE
process.non-separate=true的时候，Service的onCreate有时候耗时长达3s多？

### ISSUE THREAD

**Issue by iceAnson** [lingochamp/FileDownloader#999]
process.non-separate=true的时候，Service的onCreate有时候耗时长达3s多？
机型：htc d826w
系统：5.0.1

**Comment by rantianhua** [comment]
你描述的问题不够清 。process.non-separate=true 表示下载是在主进程进行，但是你问的又是和 Service 相关，而且我不知道你说的是什么 Service  ，和 FileDownloader 又有什么关系。

**Comment by Jacksgong** [comment]
这个主要是和所使用的手机，以及断点续传的数据数量有关，由于Service onCreate的时候会加载数据库中的所有数据，并且对数据库中的所有数据进行整理(这块参看 `CustomComponentHolder#maintainDatabase`)，具体这块的耗时，可以参看`FileDownloadDatabase` TAG的日志。这块已经在okdownload中得到优化。
